assets/queries/openAPI/general/template_path_parameter_with_no_corresponding_path_parameter/test/negative1.yaml, assets/queries/openAPI/general/template_path_parameter_with_no_corresponding_path_parameter/test/negative2.json, assets/queries/openAPI/general/template_path_parameter_with_no_corresponding_path_parameter/test/negative3.yaml, assets/queries/openAPI/general/template_path_parameter_with_no_corresponding_path_parameter/test/negative4.json, assets/queries/openAPI/general/template_path_parameter_with_no_corresponding_path_parameter/test/positive1.yaml, assets/queries/openAPI/general/template_path_parameter_with_no_corresponding_path_parameter/test/positive2.json, assets/queries/openAPI/general/template_path_parameter_with_no_corresponding_path_parameter/test/positive3.yaml, assets/queries/openAPI/general/template_path_parameter_with_no_corresponding_path_parameter/test/positive4.json, assets/queries/openAPI/general/template_path_parameter_with_no_corresponding_path_parameter/test/positive5.yaml, assets/queries/openAPI/general/template_path_parameter_with_no_corresponding_path_parameter/test/positive6.json, assets/queries/openAPI/general/template_path_parameter_with_no_corresponding_path_parameter/test/positive7.yaml, assets/queries/openAPI/general/template_path_parameter_with_no_corresponding_path_parameter/test/positive8.json, assets/queries/openAPI/general/template_path_parameter_with_no_corresponding_path_parameter/test/positive_expected_result.json
- Fix samples in "Template Path With No Corresponding Path Parameter" query
=> feat(query): fix samples in 'Template Path With No Corresponding Path Parameter' query

internal/console/printer/printer.go, internal/console/printer/printer_test.go
Closes #3536 
- Changed `log-path` to create all directories and the file, if necessary
=> fix(log): creates directories and file for log-path flag

assets/queries/openAPI/3.0/api_key_exposed_in_global_security/metadata.json, assets/queries/openAPI/3.0/api_key_exposed_in_global_security_scheme/metadata.json, assets/queries/openAPI/3.0/api_key_exposed_in_operation_security/metadata.json, assets/queries/openAPI/3.0/cleartext_api_key_in_global_security/metadata.json, assets/queries/openAPI/3.0/cleartext_api_key_in_operation_security/metadata.json
=> fix(query): corrected some aggregations on metadata

pkg/engine/inspector_test.go, pkg/engine/source/filesystem_test.go, test/fixtures/all_auth_users_get_read_access/metadata.json
Closes #3557
- changing test fixture query ID
=> fix(test): change test fixture query UUID #3557

docs/roadmap.md
Closes #3604
- fixing typo in roadmap
=> docs(roadmap): fix typo in roadmap

assets/queries/cloudFormation/ec2_instance_has_no_iam_role/query.rego, assets/queries/cloudFormation/ec2_instance_has_no_iam_role/test/positive3.yaml, assets/queries/cloudFormation/ec2_instance_has_no_iam_role/test/positive_expected_result.json
=> fix(query): Attempt to fix query

assets/libraries/openapi/library.rego, assets/queries/openAPI/2.0/components_parameter_definition_unused/metadata.json, assets/queries/openAPI/2.0/components_parameter_definition_unused/query.rego, assets/queries/openAPI/2.0/components_parameter_definition_unused/test/negative1.json, assets/queries/openAPI/2.0/components_parameter_definition_unused/test/negative2.yaml, assets/queries/openAPI/2.0/components_parameter_definition_unused/test/positive1.json, assets/queries/openAPI/2.0/components_parameter_definition_unused/test/positive2.yaml, assets/queries/openAPI/2.0/components_parameter_definition_unused/test/positive_expected_result.json, assets/queries/openAPI/3.0/parameter_object_incorrect_ref/metadata.json, assets/queries/openAPI/3.0/parameter_object_incorrect_ref/test/positive_expected_result.json
- added "Parameter Object With Incorrect Ref (v2)" for open api 2.0
=> feat(query): added "Parameter Object With Incorrect Ref (v2)" for open api 2.0

internal/console/helpers/helpers_test.go, internal/constants/constants_test.go, pkg/engine/debug.go, pkg/engine/inspector_test.go, pkg/engine/provider/filesystem_test.go, pkg/kics/sink.go, pkg/parser/terraform/terraform_test.go, pkg/parser/yaml/parser_test.go
- Increased unit testing coverage to 85%
=> Increased unit testing to 85%

assets/libraries/openapi/library.rego, assets/queries/openAPI/2.0/json_reference_does_not_exists_parameter/metadata.json, assets/queries/openAPI/2.0/json_reference_does_not_exists_parameter/query.rego, assets/queries/openAPI/2.0/json_reference_does_not_exists_parameter/test/negative1.json, assets/queries/openAPI/2.0/json_reference_does_not_exists_parameter/test/negative2.yaml, assets/queries/openAPI/2.0/json_reference_does_not_exists_parameter/test/positive1.json, assets/queries/openAPI/2.0/json_reference_does_not_exists_parameter/test/positive2.yaml, assets/queries/openAPI/2.0/json_reference_does_not_exists_parameter/test/positive_expected_result.json, assets/queries/openAPI/3.0/json_reference_does_not_exists_parameter/metadata.json, assets/queries/openAPI/3.0/json_reference_does_not_exists_parameter/query.rego, test/main_test.go
- Added Parameter JSON Reference Does Not Exists (v2) for swagger
=> feat(query): added Parameter JSON Reference Does Not Exists (v2) for swagger

docs/cdk.md, mkdocs.yml
closes #3103
closes #3427
- adding using KICS with AWS CDK guide
=> docs(guides): adding guide on using KICS with AWS CDK

assets/libraries/openapi/library.rego, assets/queries/openAPI/2.0/body_parameter_without_schema/metadata.json, assets/queries/openAPI/2.0/body_parameter_without_schema/query.rego, assets/queries/openAPI/2.0/body_parameter_without_schema/test/negative1.json, assets/queries/openAPI/2.0/body_parameter_without_schema/test/negative2.yaml, assets/queries/openAPI/2.0/body_parameter_without_schema/test/positive1.json, assets/queries/openAPI/2.0/body_parameter_without_schema/test/positive2.yaml, assets/queries/openAPI/2.0/body_parameter_without_schema/test/positive_expected_result.json, assets/queries/openAPI/3.0/parameter_object_without_schema/query.rego
- Added "Body Parameter Without Schema" query to openAPI 2.0
=> feat(query): added 'Body Parameter Without Schema' to openAPI 2.0

assets/queries/openAPI/2.0/json_reference_does_not_exists_parameter/metadata.json, assets/queries/openAPI/2.0/json_reference_does_not_exists_response/metadata.json, assets/queries/openAPI/2.0/json_reference_does_not_exists_response/query.rego, assets/queries/openAPI/2.0/json_reference_does_not_exists_response/test/negative1.json, assets/queries/openAPI/2.0/json_reference_does_not_exists_response/test/negative2.yaml, assets/queries/openAPI/2.0/json_reference_does_not_exists_response/test/positive1.json, assets/queries/openAPI/2.0/json_reference_does_not_exists_response/test/positive2.yaml, assets/queries/openAPI/2.0/json_reference_does_not_exists_response/test/positive_expected_result.json, assets/queries/openAPI/3.0/json_reference_does_not_exists_response/metadata.json, assets/queries/openAPI/3.0/json_reference_does_not_exists_response/query.rego
- Responses JSON Reference Does Not Exists
=> feat(query): added Responses JSON Reference Does Not Exists query for swagger

assets/queries/openAPI/2.0/json_reference_does_not_exists_schema/metadata.json, assets/queries/openAPI/2.0/json_reference_does_not_exists_schema/query.rego, assets/queries/openAPI/2.0/json_reference_does_not_exists_schema/test/negative1.json, assets/queries/openAPI/2.0/json_reference_does_not_exists_schema/test/negative2.yaml, assets/queries/openAPI/2.0/json_reference_does_not_exists_schema/test/positive1.json, assets/queries/openAPI/2.0/json_reference_does_not_exists_schema/test/positive2.yaml, assets/queries/openAPI/2.0/json_reference_does_not_exists_schema/test/positive_expected_result.json, assets/queries/openAPI/3.0/json_reference_does_not_exists_schema/metadata.json, assets/queries/openAPI/3.0/json_reference_does_not_exists_schema/query.rego, assets/queries/openAPI/3.0/json_reference_does_not_exists_schema/test/positive_expected_result.json
- Added Schema JSON Reference Does Not Exists for swagger
=> feat(query): added Schema JSON Reference Does Not Exists for swagger

assets/queries/openAPI/2.0/implicit_flow_oauth2/metadata.json, assets/queries/openAPI/2.0/implicit_flow_oauth2/query.rego, assets/queries/openAPI/2.0/implicit_flow_oauth2/test/negative1.json, assets/queries/openAPI/2.0/implicit_flow_oauth2/test/negative2.yaml, assets/queries/openAPI/2.0/implicit_flow_oauth2/test/positive1.json, assets/queries/openAPI/2.0/implicit_flow_oauth2/test/positive2.yaml, assets/queries/openAPI/2.0/implicit_flow_oauth2/test/positive_expected_result.json, assets/queries/openAPI/3.0/implicit_flow_oauth2/metadata.json, assets/queries/openAPI/3.0/implicit_flow_oauth2/test/positive_expected_result.json
- Added Implicit Flow in OAuth2 (v2) to Swagger
=> feat(query): Added Implicit Flow in OAuth2 (v2) to Swagger

assets/queries/openAPI/2.0/security_definitions_using_basic_auth/metadata.json, assets/queries/openAPI/2.0/security_definitions_using_basic_auth/query.rego, assets/queries/openAPI/2.0/security_definitions_using_basic_auth/test/negative1.json, assets/queries/openAPI/2.0/security_definitions_using_basic_auth/test/negative2.yaml, assets/queries/openAPI/2.0/security_definitions_using_basic_auth/test/positive1.json, assets/queries/openAPI/2.0/security_definitions_using_basic_auth/test/positive2.yaml, assets/queries/openAPI/2.0/security_definitions_using_basic_auth/test/positive_expected_result.json
- Added Security Definitions Using Basic Auth query to Swagger
=> feat(query): Added Security Definitions Using Basic Auth query to Swagger

assets/libraries/openapi/library.rego, assets/queries/openAPI/2.0/unknown_prefix/metadata.json, assets/queries/openAPI/2.0/unknown_prefix/query.rego, assets/queries/openAPI/2.0/unknown_prefix/test/negative1.json, assets/queries/openAPI/2.0/unknown_prefix/test/negative2.json, assets/queries/openAPI/2.0/unknown_prefix/test/negative3.yaml, assets/queries/openAPI/2.0/unknown_prefix/test/negative4.yaml, assets/queries/openAPI/2.0/unknown_prefix/test/positive1.json, assets/queries/openAPI/2.0/unknown_prefix/test/positive2.json, assets/queries/openAPI/2.0/unknown_prefix/test/positive3.yaml, assets/queries/openAPI/2.0/unknown_prefix/test/positive4.yaml, assets/queries/openAPI/2.0/unknown_prefix/test/positive_expected_result.json, assets/queries/openAPI/3.0/unknown_prefix/query.rego
- Added Unknown Prefix query for swagger
=> feat(query): added Unknown Prefix query for swagger

e2e/cli_test.go, e2e/fixtures/E2E_CLI_011_PAYLOAD.json, internal/console/helpers/helpers_test.go, internal/console/scan.go, pkg/report/commons.go, pkg/report/gitlab_sast.go, pkg/report/json.go, pkg/report/pdf.go, pkg/report/sarif.go, test/helpers.go
closes #3676
- using relative filepath in report.json
=> fix(report): relative filepaths in report.json #3676

assets/queries/openAPI/2.0/operation_summary_too_long/metadata.json, assets/queries/openAPI/2.0/operation_summary_too_long/query.rego, assets/queries/openAPI/2.0/operation_summary_too_long/test/negative1.json, assets/queries/openAPI/2.0/operation_summary_too_long/test/negative2.yaml, assets/queries/openAPI/2.0/operation_summary_too_long/test/positive1.json, assets/queries/openAPI/2.0/operation_summary_too_long/test/positive2.yaml, assets/queries/openAPI/2.0/operation_summary_too_long/test/positive_expected_result.json
- Added "Operation Summary Too Long" to openAPI 2.0
=> feat(query): added "Operation Summary Too Long" to openAPI 2.0

assets/queries/openAPI/2.0/security_definitions_using_password_flow/metadata.json, assets/queries/openAPI/2.0/security_definitions_using_password_flow/query.rego, assets/queries/openAPI/2.0/security_definitions_using_password_flow/test/negative1.json, assets/queries/openAPI/2.0/security_definitions_using_password_flow/test/negative2.yaml, assets/queries/openAPI/2.0/security_definitions_using_password_flow/test/positive1.json, assets/queries/openAPI/2.0/security_definitions_using_password_flow/test/positive2.yaml, assets/queries/openAPI/2.0/security_definitions_using_password_flow/test/positive_expected_result.json
- Added Security Definitions Using Password Flow query to Swagger
=> feat(query): Added Security Definitions Using Password Flow query to Swagger

assets/queries/openAPI/general/default_invalid/metadata.json, assets/queries/openAPI/general/header_response_name_is_invalid/metadata.json, assets/queries/openAPI/general/schema_enum_invalid/metadata.json, assets/queries/openAPI/general/schema_object_empty/metadata.json, assets/queries/openAPI/general/schema_object_properties_with_duplicated_keys/metadata.json
- added some missing aggregations
=> fix(query): added some missing aggregations

pkg/report/pdf.go, pkg/report/pdf_test.go
=> fix(report): wrong pdf data type assertion during generation

docs/index.md
Triggered by SHA: _5174a8bb8d478406599b13c1d74ee507dfd64bff_
=> docs(index): updating links in index page - 1.3.3

docs/roadmap.md
corrected list of next features
=> docs(roadmap): corrected list of next features

assets/queries/openAPI/2.0/body_parameter_without_schema/test/positive_expected_result.json, assets/queries/openAPI/2.0/non_body_parameter_with_schema/metadata.json, assets/queries/openAPI/2.0/non_body_parameter_with_schema/query.rego, assets/queries/openAPI/2.0/non_body_parameter_with_schema/test/negative1.json, assets/queries/openAPI/2.0/non_body_parameter_with_schema/test/negative2.yaml, assets/queries/openAPI/2.0/non_body_parameter_with_schema/test/positive1.json, assets/queries/openAPI/2.0/non_body_parameter_with_schema/test/positive2.yaml, assets/queries/openAPI/2.0/non_body_parameter_with_schema/test/positive_expected_result.json
- Added Non Body Parameter Without Schema for swagger
=> feat(query): added Non Body Parameter Without Schema for swagger

assets/queries/terraform/azure/storage_share_file_allows_all_acl_permissions/metadata.json, assets/queries/terraform/azure/storage_share_file_allows_all_acl_permissions/query.rego, assets/queries/terraform/azure/storage_share_file_allows_all_acl_permissions/test/negative.tf, assets/queries/terraform/azure/storage_share_file_allows_all_acl_permissions/test/positive.tf, assets/queries/terraform/azure/storage_share_file_allows_all_acl_permissions/test/positive_expected_result.json
Closes #3655
- Add "Storage Share File Allows All ACL Permissions" query for Terraform (ensure least privileges)
=> feat(query): "Storage Share File Allows All ACL Permissions" query for Terraform (Closes #3655)

assets/queries/terraform/azure/storage_table_allows_all_acl_permissions/metadata.json, assets/queries/terraform/azure/storage_table_allows_all_acl_permissions/query.rego, assets/queries/terraform/azure/storage_table_allows_all_acl_permissions/test/negative.tf, assets/queries/terraform/azure/storage_table_allows_all_acl_permissions/test/positive.tf, assets/queries/terraform/azure/storage_table_allows_all_acl_permissions/test/positive_expected_result.json
Closes #3657
- Add "Storage Table Allows All ACL Permissions" query for Terraform (ensure least privileges)
=> feat(query): "Storage Table Allows All ACL Permissions" query for Terraform (Closes #3657)

assets/queries/terraform/azure/role_definition_allows_custom_role_creation/metadata.json, assets/queries/terraform/azure/role_definition_allows_custom_role_creation/query.rego, assets/queries/terraform/azure/role_definition_allows_custom_role_creation/test/negative.tf, assets/queries/terraform/azure/role_definition_allows_custom_role_creation/test/positive1.tf, assets/queries/terraform/azure/role_definition_allows_custom_role_creation/test/positive2.tf, assets/queries/terraform/azure/role_definition_allows_custom_role_creation/test/positive_expected_result.json
Closes #3659
- Add "Role Definition Allows Custom Role Creation" query for Terraform (ensure least privileges)
=> feat(query): "Role Definition Allows Custom Role Creation" query for Terraform (Closes #3659)

README.md
=> docs: KICS Security & DevOps conference information

assets/queries/openAPI/general/schema_enum_invalid/test/negative1.json, assets/queries/openAPI/general/schema_enum_invalid/test/negative2.json, assets/queries/openAPI/general/schema_enum_invalid/test/negative3.yaml, assets/queries/openAPI/general/schema_enum_invalid/test/negative4.yaml, assets/queries/openAPI/general/schema_enum_invalid/test/negative5.json, assets/queries/openAPI/general/schema_enum_invalid/test/negative6.yaml, assets/queries/openAPI/general/schema_enum_invalid/test/positive1.json, assets/queries/openAPI/general/schema_enum_invalid/test/positive2.json, assets/queries/openAPI/general/schema_enum_invalid/test/positive3.yaml, assets/queries/openAPI/general/schema_enum_invalid/test/positive4.yaml, assets/queries/openAPI/general/schema_enum_invalid/test/positive5.json, assets/queries/openAPI/general/schema_enum_invalid/test/positive6.yaml, assets/queries/openAPI/general/schema_enum_invalid/test/positive_expected_result.json
=> feat(query): updated 'Schema Enum Invalid'

assets/queries/openAPI/general/type_has_invalid_keyword/metadata.json, assets/queries/openAPI/general/type_has_invalid_keyword/test/negative5.json, assets/queries/openAPI/general/type_has_invalid_keyword/test/negative6.yaml, assets/queries/openAPI/general/type_has_invalid_keyword/test/positive10.yaml, assets/queries/openAPI/general/type_has_invalid_keyword/test/positive9.json, assets/queries/openAPI/general/type_has_invalid_keyword/test/positive_expected_result.json
- Updated samples with Header Object cases (since it also applies to this object)
=> feat(query): updated 'Type Has Invalid Keyword'

assets/queries/openAPI/2.0/operation_using_basic_auth/metadata.json, assets/queries/openAPI/2.0/operation_using_basic_auth/query.rego, assets/queries/openAPI/2.0/operation_using_basic_auth/test/negative1.json, assets/queries/openAPI/2.0/operation_using_basic_auth/test/negative2.yaml, assets/queries/openAPI/2.0/operation_using_basic_auth/test/positive1.json, assets/queries/openAPI/2.0/operation_using_basic_auth/test/positive2.yaml, assets/queries/openAPI/2.0/operation_using_basic_auth/test/positive_expected_result.json, assets/queries/openAPI/2.0/security_definitions_using_basic_auth/query.rego
- Added 'Operation Using Basic Auth' for swagger
=> feat(query): added 'Operation Using Basic Auth' for swagger

assets/queries/openAPI/2.0/operation_using_password_flow/metadata.json, assets/queries/openAPI/2.0/operation_using_password_flow/query.rego, assets/queries/openAPI/2.0/operation_using_password_flow/test/negative1.json, assets/queries/openAPI/2.0/operation_using_password_flow/test/negative2.yaml, assets/queries/openAPI/2.0/operation_using_password_flow/test/positive1.json, assets/queries/openAPI/2.0/operation_using_password_flow/test/positive2.yaml, assets/queries/openAPI/2.0/operation_using_password_flow/test/positive_expected_result.json, assets/queries/openAPI/2.0/security_definitions_using_password_flow/metadata.json, assets/queries/openAPI/2.0/security_definitions_using_password_flow/query.rego
- Added 'Operation Using Password Flow' for swagger
=> feat(query): added 'Operation Using Password Flow' for swagger

pkg/report/commons.go, pkg/report/pdf.go
Closes #3730
- display PDF file creation report in stdout
=> fix(cli): display PDF file creation report in stdout

assets/queries/openAPI/2.0/file_parameter_with_wrong_consumes_property/metadata.json, assets/queries/openAPI/2.0/file_parameter_with_wrong_consumes_property/query.rego, assets/queries/openAPI/2.0/file_parameter_with_wrong_consumes_property/test/negative1.json, assets/queries/openAPI/2.0/file_parameter_with_wrong_consumes_property/test/negative2.yaml, assets/queries/openAPI/2.0/file_parameter_with_wrong_consumes_property/test/positive1.json, assets/queries/openAPI/2.0/file_parameter_with_wrong_consumes_property/test/positive2.yaml, assets/queries/openAPI/2.0/file_parameter_with_wrong_consumes_property/test/positive_expected_result.json
- Added File Parameter With Wrong Consumes Property query for swagger
=> feat(query): added File Parameter With Wrong Consumes Property query for swagger

docs/CONTRIBUTING.md
- updating pull request title project conventions
=> docs(contributing): updating pull request title conventions

README.md
=> Add DevSecCon24 2021 video

assets/libraries/openapi/library.rego, assets/queries/openAPI/2.0/invalid_media_type_value/metadata.json, assets/queries/openAPI/2.0/invalid_media_type_value/query.rego, assets/queries/openAPI/2.0/invalid_media_type_value/test/negative1.json, assets/queries/openAPI/2.0/invalid_media_type_value/test/negative2.yaml, assets/queries/openAPI/2.0/invalid_media_type_value/test/positive1.json, assets/queries/openAPI/2.0/invalid_media_type_value/test/positive2.yaml, assets/queries/openAPI/2.0/invalid_media_type_value/test/positive_expected_result.json, assets/queries/openAPI/3.0/invalid_media_type_value/query.rego, assets/queries/openAPI/3.0/invalid_media_type_value/test/positive_expected_result.json
- Added 'Invalid Media Type Value' for swagger
=> feat(query): add 'Invalid Media Type Value' for swagger

assets/queries/openAPI/2.0/operation_using_implicit_flow/metadata.json, assets/queries/openAPI/2.0/operation_using_implicit_flow/query.rego, assets/queries/openAPI/2.0/operation_using_implicit_flow/test/negative1.json, assets/queries/openAPI/2.0/operation_using_implicit_flow/test/negative2.yaml, assets/queries/openAPI/2.0/operation_using_implicit_flow/test/positive1.json, assets/queries/openAPI/2.0/operation_using_implicit_flow/test/positive2.yaml, assets/queries/openAPI/2.0/operation_using_implicit_flow/test/positive_expected_result.json
- Added Operation Using Implicit Flow query to Swagger
Operation Object should not use implicit flow
=> feat(query): add Operation Using Implicit Flow query to Swagger

assets/libraries/openapi/library.rego, assets/queries/openAPI/2.0/constraining_enum_property/metadata.json, assets/queries/openAPI/2.0/constraining_enum_property/query.rego, assets/queries/openAPI/2.0/constraining_enum_property/test/negative1.json, assets/queries/openAPI/2.0/constraining_enum_property/test/negative2.yaml, assets/queries/openAPI/2.0/constraining_enum_property/test/positive1.json, assets/queries/openAPI/2.0/constraining_enum_property/test/positive2.yaml, assets/queries/openAPI/2.0/constraining_enum_property/test/positive_expected_result.json
- Added Constraining Enum Property query for swagger
=> feat(query): added Constraining Enum Property query for swagger

assets/queries/openAPI/2.0/property_not_unique/metadata.json, assets/queries/openAPI/2.0/property_not_unique/query.rego, assets/queries/openAPI/2.0/property_not_unique/test/negative1.json, assets/queries/openAPI/2.0/property_not_unique/test/negative2.yaml, assets/queries/openAPI/2.0/property_not_unique/test/positive1.json, assets/queries/openAPI/2.0/property_not_unique/test/positive2.yaml, assets/queries/openAPI/2.0/property_not_unique/test/positive_expected_result.json
- Added Property Not Unique to Swagger
Every defined property must be unique throughout the whole API
=> feat(query): Added Property Not Unique to Swagger

.github/dependabot.yml
- Commit/PR title conventions described here https://github.com/Checkmarx/kics/blob/master/docs/CONTRIBUTING.md
=> ci: make dependabot commit messages follow conventions

assets/queries/openAPI/2.0/property_not_unique/query.rego, assets/queries/openAPI/2.0/property_not_unique/test/positive_expected_result.json
- Updated Property Not Unique query with detect line issue
=> fix(query): Updated Property Not Unique query with detect line issue

docs/creating-queries.md
- this should fix the code snippets that are broken in the mkdocs generated pages
=> docs: fix query creation guide code snippets generation

docs/index.md
Triggered by SHA: _2caca81f65301f9f2f411d073c841e391044277f_
=> docs: preparing for release 1.3.4

docs/index.md
=> revert: #3783

.github/workflows/update-docs-release.yaml
- fixing wrong subshell syntax
=> ci: fix docs release process

examples/github/kics-docker-runner-sarif.yaml
=> fix: wrong version github action workflow example

assets/queries/ansible/aws/iam_group_without_users/metadata.json, assets/queries/ansible/aws/iam_group_without_users/query.rego, assets/queries/ansible/aws/iam_group_without_users/test/negative.yaml, assets/queries/ansible/aws/iam_group_without_users/test/positive1.yaml, assets/queries/ansible/aws/iam_group_without_users/test/positive2.yaml, assets/queries/ansible/aws/iam_group_without_users/test/positive_expected_result.json, assets/queries/cloudFormation/iam_group_without_users/metadata.json, assets/queries/cloudFormation/iam_group_without_users/query.rego, assets/queries/cloudFormation/iam_group_without_users/test/negative1.yaml, assets/queries/cloudFormation/iam_group_without_users/test/negative2.json, assets/queries/cloudFormation/iam_group_without_users/test/positive1.yaml, assets/queries/cloudFormation/iam_group_without_users/test/positive2.json, assets/queries/cloudFormation/iam_group_without_users/test/positive_expected_result.json, assets/queries/terraform/aws/iam_group_without_users/metadata.json, assets/queries/terraform/aws/iam_group_without_users/query.rego, assets/queries/terraform/aws/iam_group_without_users/test/negative.tf, assets/queries/terraform/aws/iam_group_without_users/test/positive.tf, assets/queries/terraform/aws/iam_group_without_users/test/positive_expected_result.json
Closes #3814
- Added "IAM Group Without Users" query for Ansible, CloudFormation, and Terraform
=> feat(query): "IAM Group Without Users" for Ansible, CloudFormation, and Terraform (Closes #3814)

assets/queries/terraform/aws/sns_topic_not_encrypted/metadata.json, assets/queries/terraform/aws/sns_topic_not_encrypted/query.rego, assets/queries/terraform/aws/sns_topic_not_encrypted/test/negative.tf, assets/queries/terraform/aws/sns_topic_not_encrypted/test/positive1.tf, assets/queries/terraform/aws/sns_topic_not_encrypted/test/positive2.tf, assets/queries/terraform/aws/sns_topic_not_encrypted/test/positive_expected_result.json
- Added SNS Topic Not Encrypted query for terraform
=> feat(query): Added SNS Topic Not Encrypted query for terraform

assets/queries/terraform/aws/security_groups_not_used/metadata.json, assets/queries/terraform/aws/security_groups_not_used/query.rego, assets/queries/terraform/aws/security_groups_not_used/test/negative1.tf, assets/queries/terraform/aws/security_groups_not_used/test/positive1.tf, assets/queries/terraform/aws/security_groups_not_used/test/positive_expected_result.json
- Added Security Group Not Used query for terraform
=> feat(query): Added Security Group Not Used query for terraform

docs/release_checklist.md
=> docs: release checklist

.github/workflows/sonarcloud-scan-branch.yml
=> ci: sonarcloud scan branch

docs/dockerhub.md
=> docs: usage update

assets/queries/dockerfile/npm_install_without_pinned_version/query.rego, assets/queries/dockerfile/npm_install_without_pinned_version/test/negative.dockerfile, assets/queries/dockerfile/npm_install_without_pinned_version/test/positive.dockerfile, assets/queries/dockerfile/npm_install_without_pinned_version/test/positive_expected_result.json
Closes #3767 
- Corrected npm query to skip flag parameters
=> fix(query): Updated npm query to skip flag parameters

go.mod, go.sum
=> Revert "build(deps): bump github.com/open-policy-agent/opa from 0.28.0 to 0.30.1"

.github/scripts/samples-linters/ignore-list/terraform, assets/queries/terraform/general/generic_git_module_without_revision/metadata.json, assets/queries/terraform/general/generic_git_module_without_revision/query.rego, assets/queries/terraform/general/generic_git_module_without_revision/test/negative1.tf, assets/queries/terraform/general/generic_git_module_without_revision/test/positive1.tf, assets/queries/terraform/general/generic_git_module_without_revision/test/positive_expected_result.json, test/main_test.go
- Added Generic Git Module Without Revision for terraform
=> feat(query): Added Generic Git Module Without Revision for terraform

assets/queries/terraform/general/name_is_not_snake_case/metadata.json, assets/queries/terraform/general/name_is_not_snake_case/query.rego, assets/queries/terraform/general/name_is_not_snake_case/test/negative1.tf, assets/queries/terraform/general/name_is_not_snake_case/test/positive1.tf, assets/queries/terraform/general/name_is_not_snake_case/test/positive_expected_result.json, e2e/cli_test.go, test/main_test.go
- Added Name Is Not Snake Case query for terraform
=> feat(query): Added Name Is Not Snake Case query for terraform

assets/queries/terraform/general/output_without_description/metadata.json, assets/queries/terraform/general/output_without_description/query.rego, assets/queries/terraform/general/output_without_description/test/negative1.tf, assets/queries/terraform/general/output_without_description/test/positive1.tf, assets/queries/terraform/general/output_without_description/test/positive2.tf, assets/queries/terraform/general/output_without_description/test/positive3.tf, assets/queries/terraform/general/output_without_description/test/positive_expected_result.json, test/main_test.go
- Added Output Without Description for terraform
=> feat(query): Added Output Without Description for terraform

docs/integrations_gitlabci.md, examples/gitlab/KICS.gitlabci.yaml, examples/gitlab/KICS.v1.gitlabci.yaml
=> docs: fixing gitlab examples

docs/index.md
Triggered by SHA: _1704fbe0b7bbc0e3d87390a4f85e59c4e6dd3802_
=> docs: preparing for release 1.3.5

docs/index.md
=> Revert "docs: preparing for release 1.3.5"

.github/workflows/update-docs-release.yaml
=> fix update-docs-release.yaml

e2e/cli_test.go, e2e/utils/json.go
Closes #
- The purpose of this PR is to bring more readability to E2E (tests) error messages.
- It is very useful to help the developer quickly identify where the error is occurring.
=> feat(e2e) better readability in error messages in e2e tests

assets/queries/common/passwords_and_secrets_in_infrastructure_code/query.rego
- Removed Chars regex check for secrets 
=> fix(query): Fix Passwords query FN

README.md
=> Added Yalla DevOps video

.github/workflows/release-nightly.yml
=> fix: nightly build docker push

assets/queries/cloudFormation/ec2_sensitive_port_is_publicly_exposed/metadata.json, assets/queries/cloudFormation/elb_sensitive_port_is_exposed_to_entire_network/metadata.json, assets/queries/terraform/aws/workspaces_workspace_volume_not_encrypted/metadata.json
#3897 accidentally removed some query aggregation from the metadata
=> fix: fixing accidentally removed aggregation metadata

assets/libraries/common/library.rego, assets/queries/azureResourceManager/aks_cluster_rbac_disabled/metadata.json, assets/queries/azureResourceManager/aks_cluster_rbac_disabled/query.rego, assets/queries/azureResourceManager/aks_cluster_rbac_disabled/test/negative.json, assets/queries/azureResourceManager/aks_cluster_rbac_disabled/test/positive1.json, assets/queries/azureResourceManager/aks_cluster_rbac_disabled/test/positive2.json, assets/queries/azureResourceManager/aks_cluster_rbac_disabled/test/positive_expected_result.json, assets/queries/azureResourceManager/phone_number_not_set_security_contacts/query.rego
- Adding query 'AKS Cluster RBAC Disabled' for Azure Resource Manager
=> feat: add query 'AKS Cluster RBAC Disabled' for ARM

docs/creating-queries.md
- Added 'Package Cx' usage reminder + typos
=> Added 'Package Cx' usage reminder

assets/queries/azureResourceManager/azure_instance_using_basic_authentication/metadata.json, assets/queries/azureResourceManager/azure_instance_using_basic_authentication/query.rego, assets/queries/azureResourceManager/azure_instance_using_basic_authentication/test/negative1.json, assets/queries/azureResourceManager/azure_instance_using_basic_authentication/test/negative2.json, assets/queries/azureResourceManager/azure_instance_using_basic_authentication/test/positive1.json, assets/queries/azureResourceManager/azure_instance_using_basic_authentication/test/positive2.json, assets/queries/azureResourceManager/azure_instance_using_basic_authentication/test/positive_expected_result.json
- Added Azure Instance Using Basic Authentication for ARM
=> feat(query): Added Azure Instance Using Basic Authentication for ARM

assets/queries/azureResourceManager/azure_managed_disk_without_encryption/metadata.json, assets/queries/azureResourceManager/azure_managed_disk_without_encryption/query.rego, assets/queries/azureResourceManager/azure_managed_disk_without_encryption/test/negative1.json, assets/queries/azureResourceManager/azure_managed_disk_without_encryption/test/positive1.json, assets/queries/azureResourceManager/azure_managed_disk_without_encryption/test/positive2.json, assets/queries/azureResourceManager/azure_managed_disk_without_encryption/test/positive_expected_result.json
- Added Azure Managed Disk Without Encryption for ARM
=> feat(query): Added Azure Managed Disk Without Encryption for ARM

assets/queries/azureResourceManager/standard_price_not_selected/metadata.json, assets/queries/azureResourceManager/standard_price_not_selected/query.rego, assets/queries/azureResourceManager/standard_price_not_selected/test/negative1.json, assets/queries/azureResourceManager/standard_price_not_selected/test/positive1.json, assets/queries/azureResourceManager/standard_price_not_selected/test/positive_expected_result.json
- Added Standard Price Is Not Selected query for ARM
=> feat(query): Added Standard Price Is Not Selected query for ARM

assets/queries/azureResourceManager/aks_cluster_network_policy_not_configured/metadata.json, assets/queries/azureResourceManager/aks_cluster_network_policy_not_configured/query.rego, assets/queries/azureResourceManager/aks_cluster_network_policy_not_configured/test/negative1.json, assets/queries/azureResourceManager/aks_cluster_network_policy_not_configured/test/positive1.json, assets/queries/azureResourceManager/aks_cluster_network_policy_not_configured/test/positive2.json, assets/queries/azureResourceManager/aks_cluster_network_policy_not_configured/test/positive_expected_result.json
- Added AKS Cluster Network Policy Not Configured query for ARM
=> feat(query): Added AKS Cluster Network Policy Not Configured query for ARM

.github/scripts/metrics/get-metrics.py, .github/workflows/go-ci-coverage.yaml, .github/workflows/go-ci-metrics.yaml
=> fix: fixin get-metrics.py to support ARM

test/queries_test.go
=> test: adding test for duplicate description ID

.github/workflows/go-ci-coverage.yaml, .github/workflows/go-ci-metrics.yaml
=> fix: queries counter

assets/queries/azureResourceManager/aks_with_authorized_ip_ranges_disabled/metadata.json, assets/queries/azureResourceManager/aks_with_authorized_ip_ranges_disabled/query.rego, assets/queries/azureResourceManager/aks_with_authorized_ip_ranges_disabled/test/negative1.json, assets/queries/azureResourceManager/aks_with_authorized_ip_ranges_disabled/test/negative2.json, assets/queries/azureResourceManager/aks_with_authorized_ip_ranges_disabled/test/positive1.json, assets/queries/azureResourceManager/aks_with_authorized_ip_ranges_disabled/test/positive2.json, assets/queries/azureResourceManager/aks_with_authorized_ip_ranges_disabled/test/positive3.json, assets/queries/azureResourceManager/aks_with_authorized_ip_ranges_disabled/test/positive4.json, assets/queries/azureResourceManager/aks_with_authorized_ip_ranges_disabled/test/positive5.json, assets/queries/azureResourceManager/aks_with_authorized_ip_ranges_disabled/test/positive_expected_result.json
- Added AKS With Authorized IP Ranges Disabled for ARM
=> feat(query): Added AKS With Authorized IP Ranges Disabled for ARM

.github/workflows/go-ci-coverage.yaml, .github/workflows/go-ci-metrics.yaml
=> fix: ci queries counter

.github/workflows/validate-arm-samples.yaml, assets/queries/azureResourceManager/phone_number_not_set_security_contacts/test/negative.json
- adding schema validation for ARM samples
=> feat: add ARM validation

assets/queries/ansible/aws/ami_not_encrypted/query.rego
Signed-off-by: Tiago Cruz tiago.cruz@checkmarx.com
- refactoring `object.get` function to `valid.key` function
=> feat(query): Refactoring 'object.get' function for ansible

assets/queries/azureResourceManager/storage_blob_service_containter_with_public_access/metadata.json, assets/queries/azureResourceManager/storage_blob_service_containter_with_public_access/query.rego, assets/queries/azureResourceManager/storage_blob_service_containter_with_public_access/test/negative1.json, assets/queries/azureResourceManager/storage_blob_service_containter_with_public_access/test/negative2.json, assets/queries/azureResourceManager/storage_blob_service_containter_with_public_access/test/negative3.json, assets/queries/azureResourceManager/storage_blob_service_containter_with_public_access/test/positive1.json, assets/queries/azureResourceManager/storage_blob_service_containter_with_public_access/test/positive2.json, assets/queries/azureResourceManager/storage_blob_service_containter_with_public_access/test/positive3.json, assets/queries/azureResourceManager/storage_blob_service_containter_with_public_access/test/positive_expected_result.json
- Added Storage Blob Service Container With Public Access query for ARM
=> feat(query): Added Storage Blob Service Container With Public Access query for ARM

assets/queries/azureResourceManager/aks_logging_azure_monitoring_disabled/metadata.json, assets/queries/azureResourceManager/aks_logging_azure_monitoring_disabled/query.rego, assets/queries/azureResourceManager/aks_logging_azure_monitoring_disabled/test/negative1.json, assets/queries/azureResourceManager/aks_logging_azure_monitoring_disabled/test/positive1.json, assets/queries/azureResourceManager/aks_logging_azure_monitoring_disabled/test/positive2.json, assets/queries/azureResourceManager/aks_logging_azure_monitoring_disabled/test/positive_expected_result.json
- Added AKS Logging To Azure Monitoring Is Disabled query for ARM
=> feat(query): Added AKS Logging To Azure Monitoring Is Disabled query for ARM

assets/queries/azureResourceManager/aks_dashboard_enabled/metadata.json, assets/queries/azureResourceManager/aks_dashboard_enabled/query.rego, assets/queries/azureResourceManager/aks_dashboard_enabled/test/negative1.json, assets/queries/azureResourceManager/aks_dashboard_enabled/test/positive1.json, assets/queries/azureResourceManager/aks_dashboard_enabled/test/positive2.json, assets/queries/azureResourceManager/aks_dashboard_enabled/test/positive_expected_result.json
- Added AKS Dashboard Is Enabled query for ARM
=> feat(query): Added AKS Dashboard Is Enabled query for ARM

assets/queries/azureResourceManager/aks_cluster_rbac_disabled/query.rego, assets/queries/azureResourceManager/app_service_authentication_not_set/metadata.json, assets/queries/azureResourceManager/app_service_authentication_not_set/query.rego, assets/queries/azureResourceManager/app_service_authentication_not_set/test/negative1.json, assets/queries/azureResourceManager/app_service_authentication_not_set/test/negative2.json, assets/queries/azureResourceManager/app_service_authentication_not_set/test/positive1.json, assets/queries/azureResourceManager/app_service_authentication_not_set/test/positive2.json, assets/queries/azureResourceManager/app_service_authentication_not_set/test/positive3.json, assets/queries/azureResourceManager/app_service_authentication_not_set/test/positive4.json, assets/queries/azureResourceManager/app_service_authentication_not_set/test/positive_expected_result.json
- Added App Service Authentication Is Not Set for ARM
=> feat(query): Added App Service Authentication Is Not Set for ARM

assets/queries/azureResourceManager/hardcoded_securestring_parameter_default_value/metadata.json, assets/queries/azureResourceManager/hardcoded_securestring_parameter_default_value/query.rego, assets/queries/azureResourceManager/hardcoded_securestring_parameter_default_value/test/negative1.json, assets/queries/azureResourceManager/hardcoded_securestring_parameter_default_value/test/negative2.json, assets/queries/azureResourceManager/hardcoded_securestring_parameter_default_value/test/positive.json, assets/queries/azureResourceManager/hardcoded_securestring_parameter_default_value/test/positive_expected_result.json
- Added Hardcoded SecureString Parameter Default Value query for ARM
=> feat(query): Added Hardcoded SecureString Parameter Default Value query for ARM

assets/queries/azureResourceManager/storage_account_allows_network_default_access/metadata.json, assets/queries/azureResourceManager/storage_account_allows_network_default_access/query.rego, assets/queries/azureResourceManager/storage_account_allows_network_default_access/test/negative.json, assets/queries/azureResourceManager/storage_account_allows_network_default_access/test/positive1.json, assets/queries/azureResourceManager/storage_account_allows_network_default_access/test/positive2.json, assets/queries/azureResourceManager/storage_account_allows_network_default_access/test/positive3.json, assets/queries/azureResourceManager/storage_account_allows_network_default_access/test/positive_expected_result.json
=> feat(query): add 'Storage Account Allows Network Default Access' for ARM

assets/libraries/common/library.rego, assets/queries/azureResourceManager/postgres_sql_server_ssl_disabled/metadata.json, assets/queries/azureResourceManager/postgres_sql_server_ssl_disabled/query.rego, assets/queries/azureResourceManager/postgres_sql_server_ssl_disabled/test/negative.json, assets/queries/azureResourceManager/postgres_sql_server_ssl_disabled/test/positive1.json, assets/queries/azureResourceManager/postgres_sql_server_ssl_disabled/test/positive2.json, assets/queries/azureResourceManager/postgres_sql_server_ssl_disabled/test/positive_expected_result.json
- adding 'PostgreSQL Database Server SSL Disabled' for ARM
=> feat(query): add 'PostgreSQL Database Server SSL Disabled' for ARM

assets/queries/azureResourceManager/postgres_sql_server_log_checkpoint_disabled/metadata.json, assets/queries/azureResourceManager/postgres_sql_server_log_checkpoint_disabled/query.rego, assets/queries/azureResourceManager/postgres_sql_server_log_checkpoint_disabled/test/negative1.json, assets/queries/azureResourceManager/postgres_sql_server_log_checkpoint_disabled/test/positive1.json, assets/queries/azureResourceManager/postgres_sql_server_log_checkpoint_disabled/test/positive2.json, assets/queries/azureResourceManager/postgres_sql_server_log_checkpoint_disabled/test/positive3.json, assets/queries/azureResourceManager/postgres_sql_server_log_checkpoint_disabled/test/positive4.json, assets/queries/azureResourceManager/postgres_sql_server_log_checkpoint_disabled/test/positive_expected_result.json, pkg/scanner/scanner_test.go
=> feat(query): add 'PostgreSQL Database Server Log Checkpoints Disabled' in ARM

assets/queries/azureResourceManager/postgres_sql_server_log_connections_disabled/metadata.json, assets/queries/azureResourceManager/postgres_sql_server_log_connections_disabled/query.rego, assets/queries/azureResourceManager/postgres_sql_server_log_connections_disabled/test/negative1.json, assets/queries/azureResourceManager/postgres_sql_server_log_connections_disabled/test/negative2.json, assets/queries/azureResourceManager/postgres_sql_server_log_connections_disabled/test/positive1.json, assets/queries/azureResourceManager/postgres_sql_server_log_connections_disabled/test/positive2.json, assets/queries/azureResourceManager/postgres_sql_server_log_connections_disabled/test/positive3.json, assets/queries/azureResourceManager/postgres_sql_server_log_connections_disabled/test/positive4.json, assets/queries/azureResourceManager/postgres_sql_server_log_connections_disabled/test/positive_expected_result.json
- adding query 'PostgreSQL Database Server Log Connections Disabled' for ARM
=> feat(query): add PostgreSQL Database Server Log Connections Disabled for ARM

assets/queries/azureResourceManager/storage_logging_for_read_write_delete_requests_disabled/metadata.json, assets/queries/azureResourceManager/storage_logging_for_read_write_delete_requests_disabled/query.rego, assets/queries/azureResourceManager/storage_logging_for_read_write_delete_requests_disabled/test/negative.json, assets/queries/azureResourceManager/storage_logging_for_read_write_delete_requests_disabled/test/positive1.json, assets/queries/azureResourceManager/storage_logging_for_read_write_delete_requests_disabled/test/positive2.json, assets/queries/azureResourceManager/storage_logging_for_read_write_delete_requests_disabled/test/positive3.json, assets/queries/azureResourceManager/storage_logging_for_read_write_delete_requests_disabled/test/positive_expected_result.json
- Added Storage Logging For Read Write And Delete Requests Disabled for ARM
Storage Logging should be enabled for read, write and delete methods
=> feat(query): Added Storage Logging For Read Write And Delete Requests Disabled for ARM

assets/queries/azureResourceManager/website_azure_active_directory_disabled/metadata.json, assets/queries/azureResourceManager/website_azure_active_directory_disabled/query.rego, assets/queries/azureResourceManager/website_azure_active_directory_disabled/test/negative1.json, assets/queries/azureResourceManager/website_azure_active_directory_disabled/test/negative2.json, assets/queries/azureResourceManager/website_azure_active_directory_disabled/test/positive1.json, assets/queries/azureResourceManager/website_azure_active_directory_disabled/test/positive2.json, assets/queries/azureResourceManager/website_azure_active_directory_disabled/test/positive3.json, assets/queries/azureResourceManager/website_azure_active_directory_disabled/test/positive_expected_result.json
=> feat(query): add 'Website Azure Active Directory Disabled' for ARM

pkg/descriptions/client.go, pkg/descriptions/client_test.go, pkg/descriptions/descriptions.go, pkg/descriptions/descriptions_test.go, pkg/descriptions/mock/client_mock.go
=> feat: check connection before getting descriptions

Dockerfile.debian
=> fix: debian image build

README.md
=> docs: switch logo locations between Helm and OpenAPI

pkg/model/summary.go, pkg/model/summary_test.go
Closes #3869
- Fixing bug related to the path when printing result from remote repository
=> fix(cli): correcting wrong path when printing result from remote repository

docs/index.md
Triggered by SHA: _8bdc31f8b5c082b770a8db830f8cc1ad6ab6e8b8_
=> docs: preparing for release 1.4.0

docs/roadmap.md
=> docs: update roadmap - up till 1.4.0 and beyond

docs/index.md
=> Fixed spelling mistake in the word favorite

README.md
Adding ARM to the docs
Closes #
-
-
-
=> Adding ARM to the docs

docs/platforms.md, mkdocs.yml
=> docs: add ARM to documentation

.github/workflows/release-apispec.yml
=> ci: release apispec

assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/negative.tf, assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/positive1.tf, assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/positive2.tf, assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/positive_expected_result.json, assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/negative1.tf, assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/positive1.tf, assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/positive2.tf, assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/positive_expected_result.json, assets/queries/terraform/aws/s3_bucket_without_restriction_of_public_bucket/test/negative.tf
- Updated "S3 Bucket Without Restriction Of Public Bucket" query for Terraform. Fixed negative sample.
=> feat(query): updated "S3 Bucket Without Restriction Of Public Bucket" query for Terraform

go.mod, go.sum
=> Revert "build(deps): bump github.com/open-policy-agent/opa from 0.28.0 to 0.31.0"

go.mod, go.sum, internal/console/kics.go
=> Revert "build(deps): bump github.com/spf13/cobra from 1.1.3 to 1.2.1"

docs/roadmap.md
=> docs(roadmap): BoM support

assets/template/query/metadata.json
=> fix: add descriptionID to the template

assets/libraries/terraform/library.rego, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/metadata.json, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/query.rego, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/negative.tf, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/positive.tf, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/positive_expected_result.json, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/metadata.json, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/query.rego, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/negative.tf, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/positive.tf, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/positive_expected_result.json, assets/queries/terraform/aws/security_group_with_unrestricted_access_to_ssh/metadata.json, assets/queries/terraform/aws/security_group_with_unrestricted_access_to_ssh/query.rego
- Added "Network ACL With Unrestricted Access To SSH" and "Network ACL With Unrestricted Access To RDP" for Terraform
=> feat(query): added "Network ACL With Unrestricted Access To SSH" and "Network ACL With Unrestricted Access To RDP" for Terraform

.goreleaser-apispec.yml
=> fix: apispec scanner goreleaser config

Makefile
- adding `test-unit` makefile task
=> feat: adding make test-unit task

.github/workflows/go-ci-integration.yml, docs/commands.md, docs/configuration-file.md, docs/dockerhub.md, docs/flags.md, e2e/fixtures/assets/scan_help, internal/console/assets/flags.json, internal/console/flags.go, internal/console/scan.go
- deprecating flag `--disable-cis-descriptions` in favor of `--disable-full-descriptions`
=> refactor(flags): change disable descriptions flag

assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_is_publicly_accessible/metadata.json, assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_is_publicly_accessible/query.rego, assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_is_publicly_accessible/test/negative.tf, assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_is_publicly_accessible/test/positive.tf, assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_is_publicly_accessible/test/positive_expected_result.json
- Added "CloudTrail Log Files S3 Bucket is Publicly Accessible" for Terraform (missing severity and severity)
=> feat(query): added "CloudTrail Log Files S3 Bucket is Publicly Accessible" for Terraform

assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_with_logging_disabled/metadata.json, assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_with_logging_disabled/query.rego, assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_with_logging_disabled/test/negative.tf, assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_with_logging_disabled/test/positive.tf, assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_with_logging_disabled/test/positive_expected_result.json
- Added "CloudTrail Log Files S3 Bucket Logging Disabled" for Terraform (missing severity and severity)
=> feat(query): added "CloudTrail Log Files S3 Bucket Logging Disabled" for Terraform

docs/index.md
Triggered by SHA: _37c64af52f963fb0ea263a07f103eb7f437f13a8_
=> docs: preparing for release 1.4.1

docs/index.md
=> Revert "docs: preparing for release 1.4.1"

pkg/engine/inspector.go, pkg/engine/inspector_test.go, pkg/engine/source/filesystem.go, test/main_test.go
=> fix: panics when path to libraries is not found

pkg/engine/source/filesystem.go
- Fixed wrong package usage in 'getKicsDirPath' function (credit to @joaoReigota1)
=> fix: wrong package usage in 'getKicsDirPath' function

e2e/fixtures/E2E_CLI_032_RESULT.json, e2e/fixtures/E2E_CLI_033_RESULT.json, e2e/fixtures/schemas/result.json, e2e/utils/json.go, pkg/model/summary.go, pkg/report/html.go, pkg/report/json.go, pkg/report/json_test.go, pkg/report/pdf.go, pkg/report/template/html/report.tmpl
Closes #4090 
- Added KICS version to all reports
=> feat(report): Added KICS version to reports

docs/integrations_gitlabci.md, docs/integrations_jenkins.md, examples/gitlab/KICS.gitlabci.yaml, examples/gitlab/KICS.v2.gitlabci.yaml, examples/jenkins/agent-docker-html-report-declarative.jenkinsfile, examples/jenkins/agent-linux-simple-declarative.jenkinsfile
=> fix: KICS integrations docs and examples

assets/queries/terraform/aws/sagemaker_endpoint_configuration_encryption_disabled/metadata.json, assets/queries/terraform/aws/sagemaker_endpoint_configuration_encryption_disabled/query.rego, assets/queries/terraform/aws/sagemaker_endpoint_configuration_encryption_disabled/test/negative.tf, assets/queries/terraform/aws/sagemaker_endpoint_configuration_encryption_disabled/test/positive.tf, assets/queries/terraform/aws/sagemaker_endpoint_configuration_encryption_disabled/test/positive_expected_result.json
- added a query to check if kms key arn is undefined for Sagemaker Endpoint Configuration resource
=> feat(query): add Sagemaker Endpoint Configuration Disabled for Terraform

assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/metadata.json, assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/query.rego, assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/test/negative1.yaml, assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/test/negative2.json, assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/test/positive1.yaml, assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/test/positive2.json, assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/test/positive3.yaml, assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/test/positive4.json, assets/queries/cloudFormation/api_gateway_cache_encrypted_disabled/test/positive_expected_result.json
- added a query to check if cache encrypted is disabled for API gateway resource
=> feat(query): add API Gateway Cache Encrypted Disabled

assets/queries/terraform/azure/mysql_server_public_access_enabled/metadata.json, assets/queries/terraform/azure/mysql_server_public_access_enabled/query.rego, assets/queries/terraform/azure/mysql_server_public_access_enabled/test/negative.tf, assets/queries/terraform/azure/mysql_server_public_access_enabled/test/positive1.tf, assets/queries/terraform/azure/mysql_server_public_access_enabled/test/positive2.tf, assets/queries/terraform/azure/mysql_server_public_access_enabled/test/positive_expected_result.json
- added a query to check if public access enabled is true for mysql server resource
=> feat(query): add MySQL Server public access enabled for Terraform

internal/console/helpers/helpers.go, internal/console/printer/printer.go, pkg/detector/helper.go, pkg/kics/service.go
- Log in case of error (internal/console/printer/printer.go:134)
- Return err in case of error (internal/console/printer/printer.go:100)
- Log in case of error (pkg/detector/helper.go:81)
- Log in case of error (pkg/detector/helper.go:84)
=> fix(pkg): Treated unhandled errors in pkg(printer.go, detector/helper.go)

.gitignore
=> feat: ignore payload.json from root directory

assets/queries/terraform/aws/cloudtrail_not_integrated_with_cloudwatch/test/negative.tf, assets/queries/terraform/aws/cloudtrail_not_integrated_with_cloudwatch/test/positive.tf, assets/queries/terraform/aws/cloudtrail_not_integrated_with_cloudwatch/test/positive_expected_result.json
- Updated "CloudTrail Not Integrated With CloudWatch" for Terraform: Corrected invalid samples
=> refactor(query): "CloudTrail Not Integrated With CloudWatch" for Terraform 

README.md
=> Added new appearance - Black Hat Europe 2021

pkg/descriptions/descriptions.go
=> fix: full descriptions integration

.github/workflows/go-ci.yml
- saving unit test logs as an artifact that can be downloaded for debugging
=> feat: saving unit test logs as job artifact

.github/workflows/release-nightly.yml
=> feat: multi-platform nightly builds docker image

.github/workflows/release-nightly.yml
=> fix: multi platform docker images

pkg/parser/terraform/converter/default.go
=> fix: cxSAST untreated error - low result

pkg/model/summary_test.go
=> fix: unit tests

.github/workflows/release-nightly.yml
=> Revert "fix: multi platform docker images"

pkg/detector/search_line_detector.go
- Treated `pathItems` on search_line_detector to prevent invalid access
=> fix(core): corrected nil pointer access on detector line array

.github/workflows/release-nightly.yml
=> fix: removing QEMU from pipeline

docs/running-kics.md
- Fixed 4 small typos in docs.
=> fix small typo

.github/scripts/watchers/change-flags-email.py, .github/workflows/notification-update-flags.yaml
=> ci(email): Send email when flags are changed

docs/index.md
Triggered by SHA: _45ee9bdfa93bd67b50818db3b1eeb94f78f797cf_
=> docs: preparing for release 1.4.2

docs/index.md
=> Revert "docs: preparing for release 1.4.2"

assets/queries/terraform/aws/authentication_without_mfa/test/negative.tf, assets/queries/terraform/aws/authentication_without_mfa/test/positive1.tf, assets/queries/terraform/aws/authentication_without_mfa/test/positive2.tf
=> fix: auth without mfa samples

pkg/engine/source/source.go
- KICS will remove from embedded libraries variables that are declared in custom libraries
=> fix(core): Corrected library merge to merge variables

pkg/engine/inspector.go
- Changed library loading to load once, instead to load multiple times
=> fix(core): Fixed getLibraries to execute once, instead for every query

README.md
=> docs: add HashiTalks IL 2021

assets/queries/terraform/aws/glue_security_configuration_encryption_disabled/metadata.json, assets/queries/terraform/aws/glue_security_configuration_encryption_disabled/query.rego, assets/queries/terraform/aws/glue_security_configuration_encryption_disabled/test/negative.tf, assets/queries/terraform/aws/glue_security_configuration_encryption_disabled/test/positive1.tf, assets/queries/terraform/aws/glue_security_configuration_encryption_disabled/test/positive2.tf, assets/queries/terraform/aws/glue_security_configuration_encryption_disabled/test/positive3.tf, assets/queries/terraform/aws/glue_security_configuration_encryption_disabled/test/positive_expected_result.json
- Added "Glue Security Configuration Encryption Disabled" for Terraform
- **Category and Severity are provisory**
=> feat(query): added "Glue Security Configuration Encryption Disabled" for Terraform

assets/queries/terraform/aws/glue_data_catalog_encryption_disabled/metadata.json, assets/queries/terraform/aws/glue_data_catalog_encryption_disabled/query.rego, assets/queries/terraform/aws/glue_data_catalog_encryption_disabled/test/negative.tf, assets/queries/terraform/aws/glue_data_catalog_encryption_disabled/test/positive1.tf, assets/queries/terraform/aws/glue_data_catalog_encryption_disabled/test/positive2.tf, assets/queries/terraform/aws/glue_data_catalog_encryption_disabled/test/positive3.tf, assets/queries/terraform/aws/glue_data_catalog_encryption_disabled/test/positive4.tf, assets/queries/terraform/aws/glue_data_catalog_encryption_disabled/test/positive_expected_result.json
-  Added "Glue Data Catalog Encryption Disabled" for Terraform
- **Category and Severity are provisory**
=> feat(query): added "Glue Data Catalog Encryption Disabled" for Terraform

assets/queries/terraform/aws/eks_cluster_encryption_disabled/metadata.json, assets/queries/terraform/aws/eks_cluster_encryption_disabled/query.rego, assets/queries/terraform/aws/eks_cluster_encryption_disabled/test/negative1.tf, assets/queries/terraform/aws/eks_cluster_encryption_disabled/test/positive1.tf, assets/queries/terraform/aws/eks_cluster_encryption_disabled/test/positive2.tf, assets/queries/terraform/aws/eks_cluster_encryption_disabled/test/positive_expected_result.json
- Added "EKS Cluster Encryption Disabled" for Terraform
=> feat(query): added "EKS Cluster Encryption Disabled" for Terraform

README.md
Update HashiTalks IL 2021 video
=> docs: Update HashiTalks IL 2021 video

assets/queries/terraform/aws/rds_database_cluster_not_encrypted/metadata.json, assets/queries/terraform/aws/rds_database_cluster_not_encrypted/query.rego, assets/queries/terraform/aws/rds_database_cluster_not_encrypted/test/negative.tf, assets/queries/terraform/aws/rds_database_cluster_not_encrypted/test/positive.tf, assets/queries/terraform/aws/rds_database_cluster_not_encrypted/test/positive1.tf, assets/queries/terraform/aws/rds_database_cluster_not_encrypted/test/positive2.tf, assets/queries/terraform/aws/rds_database_cluster_not_encrypted/test/positive_expected_result.json
- added a query to check if storage_encrypted is enabled for RDS Database Cluster
=> feat(query): added RDS Database Cluster not Encrypted for Terraform

assets/queries/terraform/aws/vpc_subnet_assigns_public_ip/metadata.json, assets/queries/terraform/aws/vpc_subnet_assigns_public_ip/query.rego, assets/queries/terraform/aws/vpc_subnet_assigns_public_ip/test/negative1.tf, assets/queries/terraform/aws/vpc_subnet_assigns_public_ip/test/negative2.tf, assets/queries/terraform/aws/vpc_subnet_assigns_public_ip/test/positive.tf, assets/queries/terraform/aws/vpc_subnet_assigns_public_ip/test/positive_expected_result.json
- Added "VPC Subnet Assigns Public IP" for Terraform
=> feat(query): added "VPC Subnet Assigns Public IP" for Terraform

assets/queries/terraform/azure/security_contact_email/metadata.json, assets/queries/terraform/azure/security_contact_email/query.rego, assets/queries/terraform/azure/security_contact_email/test/negative.tf, assets/queries/terraform/azure/security_contact_email/test/positive.tf, assets/queries/terraform/azure/security_contact_email/test/positive_expected_result.json
- added a query to check if email is set in Security Contact
=> feat(query): added Security Contact Email for Terraform

docs/integrations_travisci.md, examples/travis/.travis.yml, mkdocs.yml
- add integration examples for TravisCI with KICS 
=> docs: TravisCI example and docs

assets/queries/terraform/azure/azure_active_directory_authentication/metadata.json, assets/queries/terraform/azure/azure_active_directory_authentication/query.rego, assets/queries/terraform/azure/azure_active_directory_authentication/test/negative.tf, assets/queries/terraform/azure/azure_active_directory_authentication/test/positive.tf, assets/queries/terraform/azure/azure_active_directory_authentication/test/positive1.tf, assets/queries/terraform/azure/azure_active_directory_authentication/test/positive2.tf, assets/queries/terraform/azure/azure_active_directory_authentication/test/positive_expected_result.json
- added a query to check if Azure Active Directory is defined for authentication for Service Fabric
=> feat(query): added Azure Active Directory Authentication for Terraform

assets/queries/terraform/azure/azure_front_door_waf_disabled/metadata.json, assets/queries/terraform/azure/azure_front_door_waf_disabled/query.rego, assets/queries/terraform/azure/azure_front_door_waf_disabled/test/negative.tf, assets/queries/terraform/azure/azure_front_door_waf_disabled/test/positive.tf, assets/queries/terraform/azure/azure_front_door_waf_disabled/test/positive_expected_result.json
- added a query to check if WAF is enabled for Azure Front Door
=> feat(query): added Azure Front Door WAF Disabled for Terraform

assets/queries/terraform/aws/iam_policies_attached_to_user/test/positive3.tf, assets/queries/terraform/aws/iam_policies_attached_to_user/test/positive_expected_result.json, assets/queries/terraform/aws/public_and_private_ec2_share_role/test/negative.tf, assets/queries/terraform/aws/public_and_private_ec2_share_role/test/positive.tf, assets/queries/terraform/aws/public_and_private_ec2_share_role/test/positive_expected_result.json
- fixed some samples based on linter feedback
=> fix(query): fixed some samples based on linter feedback

docs/secrets.md, mkdocs.yml
- Added docs related to "Passwords and Secrets" query
=> docs(secrets): added docs related to "Passwords and Secrets" query

assets/queries/common/passwords_and_secrets/regex_rules.json
=> fix: asymmetric private key regex

docs/index.md
Triggered by SHA: _8de1166cbfda156fbe397255d360e7874bc6ea72_
=> docs: preparing for release 1.4.3

docs/dockerhub.md
=> docs: fixing missing flags in dockerhub.md

assets/queries/common/passwords_and_secrets/regex_rules.json
=> fix: added \ before / in regexes

assets/queries/common/passwords_and_secrets/regex_rules.json, assets/queries/common/passwords_and_secrets/test/negative41.yaml, assets/queries/common/passwords_and_secrets/test/negative42.yaml, assets/queries/common/passwords_and_secrets/test/negative43.yaml
- Added negative samples + avoiding FP's for Passwords and Secrets Mechanism 
=> fix: added negative samples + avoiding FP's for Passwords and Secrets Mechanism 

.github/scripts/watchers/change-flags-email.py
- Fixed script to send alert when flags changes
=> fix(ci): fixed script to send alert when flags changes

assets/queries/terraform/aws/ec2_instance_monitoring_disabled/query.rego, assets/queries/terraform/aws/ec2_instance_monitoring_disabled/test/negative2.tf, assets/queries/terraform/aws/ec2_instance_monitoring_disabled/test/positive3.tf, assets/queries/terraform/aws/ec2_instance_monitoring_disabled/test/positive4.tf, assets/queries/terraform/aws/ec2_instance_monitoring_disabled/test/positive_expected_result.json
- Support of Terraform module for "EC2 Instance Monitoring Disabled"
=> feat(query): support of Terraform module for "EC2 Instance Monitoring Disabled"

assets/queries/terraform/aws/ec2_not_ebs_optimized/query.rego, assets/queries/terraform/aws/ec2_not_ebs_optimized/test/negative2.tf, assets/queries/terraform/aws/ec2_not_ebs_optimized/test/positive3.tf, assets/queries/terraform/aws/ec2_not_ebs_optimized/test/positive4.tf, assets/queries/terraform/aws/ec2_not_ebs_optimized/test/positive_expected_result.json
- Support of Terraform module for "EC2 Not EBS Optimized"
=> feat(query): support of Terraform module for "EC2 Not EBS Optimized"

assets/queries/terraform/aws/ec2_not_ebs_optimized/query.rego
Closes #
- changed searchLine to search correct value
=> fix(query): changed searchLine to search correct value

internal/console/scan.go
- Removing progress bar when --log-level=debug
=> feat(cli): removing progress bar when --log-level=debug

assets/queries/common/passwords_and_secrets/test/positive15.tf, assets/queries/common/passwords_and_secrets/test/positive17.tf, assets/queries/terraform/aws/security_groups_not_used/query.rego, assets/queries/terraform/aws/security_groups_not_used/test/negative2.tf
- Added modules for security not used query
- Updated passwords samples
=> feat(query): Added terraform modules for 'security not used' query

assets/queries/k8s/psp_with_unrestricted_access_to_host_path/metadata.json, assets/queries/k8s/psp_with_unrestricted_access_to_host_path/query.rego, assets/queries/k8s/psp_with_unrestricted_access_to_host_path/test/negative1.yaml, assets/queries/k8s/psp_with_unrestricted_access_to_host_path/test/positive1.yaml, assets/queries/k8s/psp_with_unrestricted_access_to_host_path/test/positive2.yaml, assets/queries/k8s/psp_with_unrestricted_access_to_host_path/test/positive3.yaml, assets/queries/k8s/psp_with_unrestricted_access_to_host_path/test/positive_expected_result.json
- Added "PSP With Unrestricted Access to Host Path" for Kubernetes
=> feat(query): added "PSP With Unrestricted Access to Host Path" for Kubernetes

sonar-project.properties
=> fix: sonar.properties

assets/queries/terraform/aws/s3_bucket_access_to_any_principal/query.rego, assets/queries/terraform/aws/s3_bucket_access_to_any_principal/test/negative1.tf, assets/queries/terraform/aws/s3_bucket_access_to_any_principal/test/negative2.tf, assets/queries/terraform/aws/s3_bucket_access_to_any_principal/test/positive1.tf, assets/queries/terraform/aws/s3_bucket_access_to_any_principal/test/positive2.tf, assets/queries/terraform/aws/s3_bucket_access_to_any_principal/test/positive_expected_result.json
- Support of Terraform modules for "S3 Bucket Access to Any Principal"
=> feat(query): support of Terraform modules for "S3 Bucket Access to Any Principal"

assets/queries/terraform/aws/sqs_queue_exposed/query.rego, assets/queries/terraform/aws/sqs_queue_exposed/test/negative1.tf, assets/queries/terraform/aws/sqs_queue_exposed/test/negative2.tf, assets/queries/terraform/aws/sqs_queue_exposed/test/positive1.tf, assets/queries/terraform/aws/sqs_queue_exposed/test/positive2.tf, assets/queries/terraform/aws/sqs_queue_exposed/test/positive_expected_result.json
- Support of Terraform modules for "SQS Queue Exposed"
=> feat(query): support of Terraform modules for "SQS Queue Exposed"

assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/query.rego, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/negative4.tf, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/negative5.tf, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/positive4.tf, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/positive_expected_result.json
- Added modules to 'Network ACL With Unrestricted Access To SSH' query
=> feat(query): Added modules to 'Network ACL With Unrestricted Access To SSH' query

assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/query.rego, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/negative4.tf, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/negative5.tf, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/positive4.tf, assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/positive_expected_result.json
- Added modules to 'Network ACL With Unrestricted Access To RDP' query
=> feat(query): Added modules to 'Network ACL With Unrestricted Access To RDP' query

.github/ISSUE_TEMPLATE/bug_report.md
=> chore(template): bug reports requires more info

assets/queries/terraform/aws/s3_bucket_without_enabled_mfa_delete/query.rego, assets/queries/terraform/aws/s3_bucket_without_enabled_mfa_delete/test/negative.tf, assets/queries/terraform/aws/s3_bucket_without_enabled_mfa_delete/test/negative2.tf, assets/queries/terraform/aws/s3_bucket_without_enabled_mfa_delete/test/positive1.tf, assets/queries/terraform/aws/s3_bucket_without_enabled_mfa_delete/test/positive5.tf, assets/queries/terraform/aws/s3_bucket_without_enabled_mfa_delete/test/positive6.tf, assets/queries/terraform/aws/s3_bucket_without_enabled_mfa_delete/test/positive7.tf, assets/queries/terraform/aws/s3_bucket_without_enabled_mfa_delete/test/positive8.tf, assets/queries/terraform/aws/s3_bucket_without_enabled_mfa_delete/test/positive_expected_result.json
- Support of Terraform modules for "S3 Bucket Without Enabled MFA Delete"
=> feat(query): support of Terraform modules for "S3 Bucket Without Enabled MFA Delete"

assets/queries/terraform/aws/sqs_with_sse_disabled/query.rego
- Corrected key actual value in "SQS With SSE Disabled" query
=> feat(query): corrected key actual value in "SQS With SSE Disabled" query

assets/queries/terraform/aws/s3_bucket_public_acl_overridden_by_public_access_block/query.rego, assets/queries/terraform/aws/s3_bucket_public_acl_overridden_by_public_access_block/test/negative2.tf, assets/queries/terraform/aws/s3_bucket_public_acl_overridden_by_public_access_block/test/positive2.tf, assets/queries/terraform/aws/s3_bucket_public_acl_overridden_by_public_access_block/test/positive_expected_result.json
- Updated "S3 Bucket Public ACL Overridden By Public Access Block"
=> feat(query): updated "S3 Bucket Public ACL Overridden By Public Access Block"

assets/queries/cloudFormation/s3_bucket_without_ssl_in_write_actions/query.rego, assets/queries/cloudFormation/s3_bucket_without_ssl_in_write_actions/test/negative3.yaml, assets/queries/cloudFormation/s3_bucket_without_ssl_in_write_actions/test/positive10.json, assets/queries/cloudFormation/s3_bucket_without_ssl_in_write_actions/test/positive9.yaml, assets/queries/cloudFormation/s3_bucket_without_ssl_in_write_actions/test/positive_expected_result.json
- Included check for cases when a statement is an object for "S3 Bucket Without SSL In Write Actions"
=> feat(query): included check for cases when a statement is an object for "S3 Bucket Without SSL In Write Actions"

docs/index.md
Triggered by SHA: _704851ae20c493093dce54da1040cddca64d0334_
=> docs: preparing for release 1.4.4

assets/queries/k8s/service_does_not_target_pod/query.rego
Closes #4302
- fixed service_does_not_target_pod query issues
=> fix(query): fixed service_does_not_target_pod query issues #4302

pkg/parser/json/json_line.go
Closes #4327
- fixed json parser with incorrect kics_line
=> fix(parser): fixed json parser with incorrect kics_line #4327

.github/workflows/go-test-race.yml, internal/console/helpers/helpers.go, internal/storage/memory.go, internal/tracker/ci.go, pkg/engine/inspector_test.go, pkg/progress/circle/circle_progress.go, pkg/progress/circle/circle_progress_test.go, pkg/scan/scan.go
Closes #4399 
- fix(race): fix kics Go data races
=> fix(race): fix kics Go data races (#4399 )

assets/libraries/azureresourcemanager.rego, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_rdp/query.rego, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_rdp/test/negative2.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_rdp/test/negative3.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_rdp/test/negative5.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_rdp/test/negative6.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_rdp/test/positive1.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/query.rego, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/negative1.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/negative2.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/negative3.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/negative4.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/negative5.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/negative6.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/positive1.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/positive2.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/positive3.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/positive4.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/positive5.json, assets/queries/azureResourceManager/network_security_group_with_unrestricted_access_to_ssh/test/positive6.json
Closes #4434
- Fixed 59cb3da7-f206-4ae6-b827-7abf0a9cab9d and 2ade1579-4b2c-4590-bebb-f99bf597f612: corrected the function get_sg_info and adapted both queries
=> fix(query): fixed 59cb3da7-f206-4ae6-b827-7abf0a9cab9d and 2ade1579-4b2c-4590-bebb-f99bf597f612

.github/workflows/go-test-race.yml
-  increased go-test-race action timeout to 1 hour
=> refactor(go-test-race): increase timeout to 1 hour

.github/scripts/report/main.go
- This PR introduces some changes to the script E2E Report to follow security aspects. 
=> feat(ci): Mitigating report script issues (E2E Tests)

pkg/descriptions/client.go
=> fix: increase client timeout to 20s

assets/queries/terraform/aws_bom/elasticache/query.rego, assets/queries/terraform/aws_bom/msk/query.rego, assets/queries/terraform/aws_bom/sns/query.rego
- fix resource categories for BoM POC queries.
=> fix(bom): appropriate resource categories

assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/metadata.json, assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/query.rego, assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/test/negative1.tf, assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/test/negative2.tf, assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/test/positive1.tf, assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/test/positive2.tf, assets/queries/terraform/azure/app_service_not_using_latest_tls_encryption_version/test/positive_expected_result.json
- Added "App Service Not Using Latest TLS Encryption Version" for Terraform
=> feat(query): added "App Service Not Using Latest TLS Encryption Version" for Terraform

pkg/detector/helper.go, pkg/detector/helper_test.go
Closes #4415
- fixed panic from interpolated brackets in KICS detector GetBracketValues function
=> fix(detector): fix panic with interpolated brackets in detector (#4415)

assets/queries/terraform/azure/function_app_managed_identity_disabled/metadata.json, assets/queries/terraform/azure/function_app_managed_identity_disabled/query.rego, assets/queries/terraform/azure/function_app_managed_identity_disabled/test/negative.tf, assets/queries/terraform/azure/function_app_managed_identity_disabled/test/positive1.tf, assets/queries/terraform/azure/function_app_managed_identity_disabled/test/positive_expected_result.json
- Added "Function App Managed Identity Disabled" for Terraform
=> feat(query): added "Function App Managed Identity Disabled" for Terraform

assets/queries/terraform/azure/mssql_server_public_network_access_disabled/metadata.json, assets/queries/terraform/azure/mssql_server_public_network_access_disabled/query.rego, assets/queries/terraform/azure/mssql_server_public_network_access_disabled/test/negative1.tf, assets/queries/terraform/azure/mssql_server_public_network_access_disabled/test/positive1.tf, assets/queries/terraform/azure/mssql_server_public_network_access_disabled/test/positive2.tf, assets/queries/terraform/azure/mssql_server_public_network_access_disabled/test/positive_expected_result.json, assets/queries/terraform/azure/mysql_server_public_access_enabled/metadata.json
- Added "MSSQL Server Public Network Access Enabled" for Terraform
- Corrected severity for query "MySQL Server Public Access Enabled"
=> feat(query): added "MSSQL Server Public Network Access Enabled" for Terraform

assets/queries/terraform/azure/function_app_http2_disabled/metadata.json, assets/queries/terraform/azure/function_app_http2_disabled/query.rego, assets/queries/terraform/azure/function_app_http2_disabled/test/negative.tf, assets/queries/terraform/azure/function_app_http2_disabled/test/positive1.tf, assets/queries/terraform/azure/function_app_http2_disabled/test/positive2.tf, assets/queries/terraform/azure/function_app_http2_disabled/test/positive3.tf, assets/queries/terraform/azure/function_app_http2_disabled/test/positive_expected_result.json
- Added  "Function App HTTP2 Disabled" for Terraform
=> feat(query): added "Function App HTTP2 Disabled" for Terraform

assets/queries/terraform/azure/app_service_http2_disabled/metadata.json, assets/queries/terraform/azure/app_service_http2_disabled/query.rego, assets/queries/terraform/azure/app_service_http2_disabled/test/negative.tf, assets/queries/terraform/azure/app_service_http2_disabled/test/positive1.tf, assets/queries/terraform/azure/app_service_http2_disabled/test/positive2.tf, assets/queries/terraform/azure/app_service_http2_disabled/test/positive3.tf, assets/queries/terraform/azure/app_service_http2_disabled/test/positive_expected_result.json
- Added "App Service HTTP2 Disabled" for Terraform
=> feat(query): added "App Service HTTP2 Disabled" for Terraform

docs/integrations.md
- Add MegaLinter in the list of integrations-
=> Add MegaLinter in the list of integrations

assets/queries/dockerfile/chown_flag_exists/metadata.json
Closes #3768
- Updated description to be more clear on what the vulnerability implies
=> refactor(query): Updated query Chown Flag Exists description (#3768)

pkg/engine/secrets/inspector.go
Closes #4349
- Validation of query ids in custom secrets regexes
=> feat(passwords and secrets): validation of query ids in custom secrets regexes

assets/queries/terraform/azure/app_service_managed_identity_disabled/metadata.json, assets/queries/terraform/azure/app_service_managed_identity_disabled/query.rego, assets/queries/terraform/azure/app_service_managed_identity_disabled/test/negative1.tf, assets/queries/terraform/azure/app_service_managed_identity_disabled/test/positive1.tf, assets/queries/terraform/azure/app_service_managed_identity_disabled/test/positive_expected_result.json
- Added "App Service Managed Identity Disabled" for Terraform
=> feat(query): added "App Service Managed Identity Disabled" for Terraform

docs/certifications-cis.md
=> fix(docs): removed duplicate lines from docs

.github/ISSUE_TEMPLATE/bug_report.md
=> Add gitter badge to new issue template

README.md
https://www.meetup.com/OWASP-Canberra-Chapter/events/281946376/
Closes #
-
-
-
=> Added OWASP-Canberra-Chapter Meetup

assets/libraries/common.json, assets/libraries/terraform.rego, assets/queries/terraform/aws_bom/mq/query.rego, assets/queries/terraform/aws_bom/mq/test/positive2.tf, assets/queries/terraform/aws_bom/s3_bucket/query.rego, assets/queries/terraform/aws_bom/sns/query.rego, assets/queries/terraform/aws_bom/sns/test/positive5.tf, assets/queries/terraform/aws_bom/sqs/query.rego, docs/bom.md, test/queries_test.go
- Added more information to BoM
=> feat(bom): added more information

docs/getting-started.md
Closes  #1657 (at least the brew part)
- Add instructions to install kics with homebrew
=> add homebrew install

assets/libraries/terraform.rego, assets/queries/ansible/gcp/google_compute_network_using_default_firewall_rule/metadata.json, assets/queries/ansible/gcp/google_compute_network_using_default_firewall_rule/query.rego, assets/queries/ansible/gcp/google_compute_network_using_default_firewall_rule/test/negative.yaml, assets/queries/ansible/gcp/google_compute_network_using_default_firewall_rule/test/positive.yaml, assets/queries/ansible/gcp/google_compute_network_using_default_firewall_rule/test/positive_expected_result.json, assets/queries/terraform/gcp/google_compute_network_using_default_firewall_rule/metadata.json, assets/queries/terraform/gcp/google_compute_network_using_default_firewall_rule/query.rego, assets/queries/terraform/gcp/google_compute_network_using_default_firewall_rule/test/negative.tf, assets/queries/terraform/gcp/google_compute_network_using_default_firewall_rule/test/positive.tf, assets/queries/terraform/gcp/google_compute_network_using_default_firewall_rule/test/positive_expected_result.json
-  Added "Google Compute Network Using Default Firewall Rule" for Ansible and Terraform
=> feat(query): added "Google Compute Network Using Default Firewall Rule" for Ansible and Terraform

assets/libraries/terraform.rego, assets/queries/terraform/gcp/user_with_iam_role/metadata.json, assets/queries/terraform/gcp/user_with_iam_role/query.rego, assets/queries/terraform/gcp/user_with_iam_role/test/negative.tf, assets/queries/terraform/gcp/user_with_iam_role/test/positive1.tf, assets/queries/terraform/gcp/user_with_iam_role/test/positive2.tf, assets/queries/terraform/gcp/user_with_iam_role/test/positive_expected_result.json
- Added "User with IAM Role" for Terraform
=> feat(query): added "User with IAM Role" for Terraform

docs/platforms.md
Closes #4493 
- Added documentation for terraform modules
=> docs(terraform): Added docs for terraform modules feature

assets/libraries/terraform.rego, assets/queries/terraform/gcp/service_account_with_improper_privileges/metadata.json, assets/queries/terraform/gcp/service_account_with_improper_privileges/query.rego, assets/queries/terraform/gcp/service_account_with_improper_privileges/test/negative1.tf, assets/queries/terraform/gcp/service_account_with_improper_privileges/test/negative2.tf, assets/queries/terraform/gcp/service_account_with_improper_privileges/test/positive1.tf, assets/queries/terraform/gcp/service_account_with_improper_privileges/test/positive2.tf, assets/queries/terraform/gcp/service_account_with_improper_privileges/test/positive_expected_result.json
- Added "Service Account with Improper Privileges" for Terraform
- Function `check_member` in Terraform library will be used in the next queries
=> feat(query): added "Service Account with Improper Privileges" for Terraform

assets/queries/terraform/azure/virtual_network_with_ddos_protection_plan_disabled/metadata.json, assets/queries/terraform/azure/virtual_network_with_ddos_protection_plan_disabled/query.rego, assets/queries/terraform/azure/virtual_network_with_ddos_protection_plan_disabled/test/negative.tf, assets/queries/terraform/azure/virtual_network_with_ddos_protection_plan_disabled/test/positive1.tf, assets/queries/terraform/azure/virtual_network_with_ddos_protection_plan_disabled/test/positive2.tf, assets/queries/terraform/azure/virtual_network_with_ddos_protection_plan_disabled/test/positive_expected_result.json
- Added "Virtual Network with DDoS Protection Plan disabled" for Terraform
:rotating_light: SEVERITY AND CATEGORY NEED REVIEW :rotating_light:
=> feat(query): added "Virtual Network with DDoS Protection Plan disabled" for Terraform

assets/queries/terraform/gcp/kms_crypto_key_publicly_accessible/metadata.json, assets/queries/terraform/gcp/kms_crypto_key_publicly_accessible/query.rego, assets/queries/terraform/gcp/kms_crypto_key_publicly_accessible/test/negative.tf, assets/queries/terraform/gcp/kms_crypto_key_publicly_accessible/test/positive1.tf, assets/queries/terraform/gcp/kms_crypto_key_publicly_accessible/test/positive2.tf, assets/queries/terraform/gcp/kms_crypto_key_publicly_accessible/test/positive_expected_result.json
- Added "KMS Crypto Key is Publicly Accessible" for Terraform
=> feat(query): added "KMS Crypto Key is Publicly Accessible" for Terraform

assets/queries/ansible/gcp/gke_using_default_service_account/metadata.json, assets/queries/ansible/gcp/gke_using_default_service_account/query.rego, assets/queries/ansible/gcp/gke_using_default_service_account/test/negative1.yaml, assets/queries/ansible/gcp/gke_using_default_service_account/test/positive1.yaml, assets/queries/ansible/gcp/gke_using_default_service_account/test/positive2.yaml, assets/queries/ansible/gcp/gke_using_default_service_account/test/positive_expected_result.json, assets/queries/terraform/gcp/gke_using_default_service_account/metadata.json, assets/queries/terraform/gcp/gke_using_default_service_account/query.rego, assets/queries/terraform/gcp/gke_using_default_service_account/test/negative.tf, assets/queries/terraform/gcp/gke_using_default_service_account/test/positive1.tf, assets/queries/terraform/gcp/gke_using_default_service_account/test/positive2.tf, assets/queries/terraform/gcp/gke_using_default_service_account/test/positive_expected_result.json
- Added "GKE Using Default Service Account" for Ansible and Terraform
=> feat(query): added "GKE Using Default Service Account" for Ansible and Terraform

pkg/report/pdf.go
-  Added expected value to PDF report
=> feat(report): Added expected value to PDF report

assets/queries/cloudFormation/shield_advanced_not_in_use/metadata.json, assets/queries/cloudFormation/shield_advanced_not_in_use/query.rego, assets/queries/cloudFormation/shield_advanced_not_in_use/test/negative1.yaml, assets/queries/cloudFormation/shield_advanced_not_in_use/test/negative2.json, assets/queries/cloudFormation/shield_advanced_not_in_use/test/positive1.yaml, assets/queries/cloudFormation/shield_advanced_not_in_use/test/positive2.json, assets/queries/cloudFormation/shield_advanced_not_in_use/test/positive_expected_result.json, assets/queries/terraform/aws/shield_advanced_not_in_use/metadata.json, assets/queries/terraform/aws/shield_advanced_not_in_use/query.rego, assets/queries/terraform/aws/shield_advanced_not_in_use/test/negative1.tf, assets/queries/terraform/aws/shield_advanced_not_in_use/test/negative2.tf, assets/queries/terraform/aws/shield_advanced_not_in_use/test/positive1.tf, assets/queries/terraform/aws/shield_advanced_not_in_use/test/positive2.tf, assets/queries/terraform/aws/shield_advanced_not_in_use/test/positive_expected_result.json
- Added "Shield Advanced Not In Use" for CloudFormation and Terraform
=> feat(query): added "Shield Advanced Not In Use" for CloudFormation and Terraform

docs/integrations.md, mkdocs.yml
- Added pre-commit hooks to docs correctly
=> feat(docs): Added pre-commit hooks

.github/workflows/release-docker-github-actions.yaml
- Created workflow to run on dispatch to upload KICS GitHub action to Docker
=> feat(ci): add workflow to upload github-actions image to dockerhub

README.md
=> Added video to last meetup

README.md
=> Added AWS re:invent interview

assets/queries/googleDeploymentManager/disk_encryption_disabled/metadata.json, assets/queries/googleDeploymentManager/disk_encryption_disabled/query.rego, assets/queries/googleDeploymentManager/disk_encryption_disabled/test/negative1.yaml, assets/queries/googleDeploymentManager/disk_encryption_disabled/test/negative2.yaml, assets/queries/googleDeploymentManager/disk_encryption_disabled/test/positive1.yaml, assets/queries/googleDeploymentManager/disk_encryption_disabled/test/positive2.yaml, assets/queries/googleDeploymentManager/disk_encryption_disabled/test/positive3.yaml, assets/queries/googleDeploymentManager/disk_encryption_disabled/test/positive_expected_result.json
- Added "Disk Encryption Disabled" for Google Deployment Manager
=> feat(query): added "Disk Encryption Disabled" for Google Deployment Manager

pkg/analyzer/analyzer.go, pkg/parser/yaml/parser.go
=> fix log error messages polution

pkg/report/pdf.go
Closes #4601 
- Corrected scan end time in pdf report
=> fix(report): corrected scan end time in pdf report

assets/queries/googleDeploymentManager/cloud_dns_without_dnnsec/metadata.json, assets/queries/googleDeploymentManager/cloud_dns_without_dnnsec/query.rego, assets/queries/googleDeploymentManager/cloud_dns_without_dnnsec/test/negative1.yaml, assets/queries/googleDeploymentManager/cloud_dns_without_dnnsec/test/positive1.yaml, assets/queries/googleDeploymentManager/cloud_dns_without_dnnsec/test/positive2.yaml, assets/queries/googleDeploymentManager/cloud_dns_without_dnnsec/test/positive3.yaml, assets/queries/googleDeploymentManager/cloud_dns_without_dnnsec/test/positive_expected_result.json
- Added "Cloud DNS Without DNSSEC" for Google Deployment Manager
=> feat(query): added "Cloud DNS Without DNSSEC" for Google Deployment Manager

pkg/parser/docker/parser.go
Closes #4591
- Instead of having args as a from structure, the payload will now contain a separate args structure for arguments
=> fix(parser): fixed Dockerfile parser with wrong payload when using arguments (#4591)

assets/queries/googleDeploymentManager/dnssec_using_rsasha1/metadata.json, assets/queries/googleDeploymentManager/dnssec_using_rsasha1/query.rego, assets/queries/googleDeploymentManager/dnssec_using_rsasha1/test/negative1.yaml, assets/queries/googleDeploymentManager/dnssec_using_rsasha1/test/positive1.yaml, assets/queries/googleDeploymentManager/dnssec_using_rsasha1/test/positive_expected_result.json
- Added "DNSSEC Using RSASHA1" for Google Deployment Manager
=> feat(query): added "DNSSEC Using RSASHA1" for Google Deployment Manager

assets/queries/googleDeploymentManager/compute_instance_is_publicly_accessible/metadata.json, assets/queries/googleDeploymentManager/compute_instance_is_publicly_accessible/query.rego, assets/queries/googleDeploymentManager/compute_instance_is_publicly_accessible/test/negative1.yaml, assets/queries/googleDeploymentManager/compute_instance_is_publicly_accessible/test/positive1.yaml, assets/queries/googleDeploymentManager/compute_instance_is_publicly_accessible/test/positive_expected_result.json
- Added "Compute Instance Is Publicly Accessible" for Google Deployment Manager
=> feat(query): added "Compute Instance Is Publicly Accessible" for Google Deployment Manager

docs/configuration-file.md
=> add example in docs for config setting exclude paths

docs/index.md
=> fix(docs): fix docs wrong version

assets/queries/googleDeploymentManager/shielded_vm_disabled/metadata.json, assets/queries/googleDeploymentManager/shielded_vm_disabled/query.rego, assets/queries/googleDeploymentManager/shielded_vm_disabled/test/negative1.yaml, assets/queries/googleDeploymentManager/shielded_vm_disabled/test/positive1.yaml, assets/queries/googleDeploymentManager/shielded_vm_disabled/test/positive2.yaml, assets/queries/googleDeploymentManager/shielded_vm_disabled/test/positive_expected_result.json
- Added "Shielded VM Disabled" for Google Deployment Manager
=> feat(query): added "Shielded VM Disabled" for Google Deployment Manager

assets/queries/terraform/aws_bom/sns/query.rego, assets/queries/terraform/aws_bom/sqs/query.rego, assets/queries/terraform/aws_bom/sqs/test/positive6.tf, assets/queries/terraform/aws_bom/sqs/test/positive_expected_result.json
=> feat(bom): added  SQS Queue Policy

pkg/scan/path_utils.go, pkg/scan/scan.go
Closes #4585
- Deleted extraction folder after KICS scan
=> fix: deleted extraction folder after KICS scan

.github/scripts/metrics/get-metrics.py
=> Fix queries counter after aws / aws sam split

assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_api_endpoint_config_not_private/metadata.json, assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_api_endpoint_config_not_private/query.rego, assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_api_endpoint_config_not_private/test/negative1.yaml, assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_api_endpoint_config_not_private/test/positive1.yaml, assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_api_endpoint_config_not_private/test/positive2.yaml, assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_api_endpoint_config_not_private/test/positive3.yaml, assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_api_endpoint_config_not_private/test/positive_expected_result.json
- Added "Serverless API Endpoint Config Not Private" for CloudFormation
=> feat(query): added "Serverless API Endpoint Config Not Private" for CloudFormation

assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_function_without_tags/metadata.json, assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_function_without_tags/query.rego, assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_function_without_tags/test/negative1.yaml, assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_function_without_tags/test/positive1.yaml, assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_function_without_tags/test/positive_expected_result.json
- Added "Serverless Function Without Tags" for CloudFormation
=> feat(query): added "Serverless Function Without Tags" for CloudFormation

assets/queries/cloudFormation/aws_sam/serverless_function_without_x-ray_tracing/metadata.json, assets/queries/cloudFormation/aws_sam/serverless_function_without_x-ray_tracing/query.rego, assets/queries/cloudFormation/aws_sam/serverless_function_without_x-ray_tracing/test/negative1.yaml, assets/queries/cloudFormation/aws_sam/serverless_function_without_x-ray_tracing/test/positive1.yaml, assets/queries/cloudFormation/aws_sam/serverless_function_without_x-ray_tracing/test/positive2.yaml, assets/queries/cloudFormation/aws_sam/serverless_function_without_x-ray_tracing/test/positive_expected_result.json
- Added "Serverless Function Without X-Ray Tracing" for CloudFormation
=> feat(query): added "Serverless Function Without X-Ray Tracing" for CloudFormation

pkg/parser/grpc/converter/converter.go
Closes #4655 
- Fixed KICS panic in getLastElementLine: added length check
=> fix(parser): fixed KICS panic in getLastElementLine

pkg/parser/json/json_line.go
- Fixed KICS panic in empty fifo value access: added length check
=> fix(parser): fixed KICS panic in empty fifo value access

pkg/engine/secrets/inspector_test.go, pkg/kics/resolver_sink.go, pkg/kics/sink.go, pkg/model/comment_yaml.go, pkg/model/comment_yaml_test.go, pkg/model/model.go
Closes #4563 
Closes #4661
- Fixed YAML comments
=> fix(yaml): ignore lines by comments

assets/queries/terraform/aws_bom/s3_bucket/query.rego
- Corrected get_accessibility for aws_bucket
=> fix(bom): corrected get_accessibility for aws_bucket

internal/console/helpers/helpers.go
Closes #4667
- Added chars limit on vulnerable line display
=> feat(cli): added chars limit on vulnerable line display

pkg/detector/helper.go
- Fixed KICS panic in getKeyWithCurlyBrackets
=> fix(detector): fixed KICS panic in getKeyWithCurlyBrackets

assets/queries/ansible/aws/ec2_not_ebs_optimized/metadata.json, assets/queries/ansible/aws/ec2_not_ebs_optimized/query.rego, assets/queries/ansible/aws/ec2_not_ebs_optimized/test/negative.yaml, assets/queries/ansible/aws/ec2_not_ebs_optimized/test/positive1.yaml, assets/queries/ansible/aws/ec2_not_ebs_optimized/test/positive2.yaml, assets/queries/ansible/aws/ec2_not_ebs_optimized/test/positive_expected_result.json
- Added "Ansible aws ec2 not ebs optimized" for ansible aws
=> feat(query): added "Ansible aws ec2 not ebs optimized"

assets/queries/cloudFormation/aws/ec2_not_ebs_optimized/metadata.json, assets/queries/cloudFormation/aws/ec2_not_ebs_optimized/query.rego, assets/queries/cloudFormation/aws/ec2_not_ebs_optimized/test/negative1.yaml, assets/queries/cloudFormation/aws/ec2_not_ebs_optimized/test/negative2.json, assets/queries/cloudFormation/aws/ec2_not_ebs_optimized/test/positive1.yaml, assets/queries/cloudFormation/aws/ec2_not_ebs_optimized/test/positive2.json, assets/queries/cloudFormation/aws/ec2_not_ebs_optimized/test/positive3.yaml, assets/queries/cloudFormation/aws/ec2_not_ebs_optimized/test/positive4.json, assets/queries/cloudFormation/aws/ec2_not_ebs_optimized/test/positive_expected_result.json
- Added "Cloudformation aws ec2 not ebs optimized"
=> feat(query): added "Cloudformation aws ec2 not ebs optimized"

assets/queries/cloudFormation/aws/api_gateway_cache_cluster_disabled/metadata.json, assets/queries/cloudFormation/aws/api_gateway_cache_cluster_disabled/query.rego, assets/queries/cloudFormation/aws/api_gateway_cache_cluster_disabled/test/negative1.yaml, assets/queries/cloudFormation/aws/api_gateway_cache_cluster_disabled/test/negative2.json, assets/queries/cloudFormation/aws/api_gateway_cache_cluster_disabled/test/positive1.yaml, assets/queries/cloudFormation/aws/api_gateway_cache_cluster_disabled/test/positive2.yaml, assets/queries/cloudFormation/aws/api_gateway_cache_cluster_disabled/test/positive3.json, assets/queries/cloudFormation/aws/api_gateway_cache_cluster_disabled/test/positive4.json, assets/queries/cloudFormation/aws/api_gateway_cache_cluster_disabled/test/positive_expected_result.json, assets/queries/cloudFormation/aws_sam/serverless_api_cache_cluster_disabled/metadata.json, assets/queries/cloudFormation/aws_sam/serverless_api_cache_cluster_disabled/query.rego, assets/queries/cloudFormation/aws_sam/serverless_api_cache_cluster_disabled/test/negative1.yaml, assets/queries/cloudFormation/aws_sam/serverless_api_cache_cluster_disabled/test/positive1.yaml, assets/queries/cloudFormation/aws_sam/serverless_api_cache_cluster_disabled/test/positive2.yaml, assets/queries/cloudFormation/aws_sam/serverless_api_cache_cluster_disabled/test/positive_expected_result.json
- [AWS] added "API Gateway Cache Cluster Disabled"
- [AWS_SAM] added "Serverless API Cache Cluster Disabled"
=> feat(query): added "API Gateway Cache Cluster Disabled" and "Serverless API Cache Cluster Disabled" for Cloudformation

assets/queries/cloudFormation/aws_sam/serverless_api_without_content_encoding/metadata.json, assets/queries/cloudFormation/aws_sam/serverless_api_without_content_encoding/query.rego, assets/queries/cloudFormation/aws_sam/serverless_api_without_content_encoding/test/negative1.yaml, assets/queries/cloudFormation/aws_sam/serverless_api_without_content_encoding/test/positive1.yaml, assets/queries/cloudFormation/aws_sam/serverless_api_without_content_encoding/test/positive2.yaml, assets/queries/cloudFormation/aws_sam/serverless_api_without_content_encoding/test/positive3.yaml, assets/queries/cloudFormation/aws_sam/serverless_api_without_content_encoding/test/positive_expected_result.json
- Added "Serverless API Without Content Encoding" for CloudFormation
=> feat(query): added "Serverless API Without Content Encoding" for CloudFormation

assets/queries/cloudFormation/aws/lambda_function_without_dead_letter_queue/metadata.json, assets/queries/cloudFormation/aws/lambda_function_without_dead_letter_queue/query.rego, assets/queries/cloudFormation/aws/lambda_function_without_dead_letter_queue/test/negative1.yaml, assets/queries/cloudFormation/aws/lambda_function_without_dead_letter_queue/test/positive1.yaml, assets/queries/cloudFormation/aws/lambda_function_without_dead_letter_queue/test/positive2.yaml, assets/queries/cloudFormation/aws/lambda_function_without_dead_letter_queue/test/positive_expected_result.json, assets/queries/cloudFormation/aws_sam/serverless_function_without_dead_letter_queue/metadata.json, assets/queries/cloudFormation/aws_sam/serverless_function_without_dead_letter_queue/query.rego, assets/queries/cloudFormation/aws_sam/serverless_function_without_dead_letter_queue/test/negative1.yaml, assets/queries/cloudFormation/aws_sam/serverless_function_without_dead_letter_queue/test/positive1.yaml, assets/queries/cloudFormation/aws_sam/serverless_function_without_dead_letter_queue/test/positive_expected_result.json
- [AWS] "Lambda Function Without Dead Letter Queue"
- [AWS_SAM] "Serverless Function Without Dead Letter Queue"
=> feat(query): added "Lambda Function Without Dead Letter Queue" and "Serverless Function Without Dead Letter Queue" for CloudFormation

assets/queries/cloudFormation/aws_sam/serverless_function_environment_variables_not_encrypted/metadata.json, assets/queries/cloudFormation/aws_sam/serverless_function_environment_variables_not_encrypted/query.rego, assets/queries/cloudFormation/aws_sam/serverless_function_environment_variables_not_encrypted/test/negative1.yaml, assets/queries/cloudFormation/aws_sam/serverless_function_environment_variables_not_encrypted/test/positive1.yaml, assets/queries/cloudFormation/aws_sam/serverless_function_environment_variables_not_encrypted/test/positive_expected_result.json
- Added "Serverless Function Environment Variables Not Encrypted" for CloudFormation
=> feat(query): added "Serverless Function Environment Variables Not Encrypted" for CloudFormation

assets/queries/ansible/aws/redshift_using_default_port/metadata.json, assets/queries/ansible/aws/redshift_using_default_port/query.rego, assets/queries/ansible/aws/redshift_using_default_port/test/negative.yaml, assets/queries/ansible/aws/redshift_using_default_port/test/positive.yaml, assets/queries/ansible/aws/redshift_using_default_port/test/positive_expected_result.json, assets/queries/cloudFormation/aws/redshift_using_default_port/metadata.json, assets/queries/cloudFormation/aws/redshift_using_default_port/query.rego, assets/queries/cloudFormation/aws/redshift_using_default_port/test/negative1.yaml, assets/queries/cloudFormation/aws/redshift_using_default_port/test/negative2.json, assets/queries/cloudFormation/aws/redshift_using_default_port/test/positive1.yaml, assets/queries/cloudFormation/aws/redshift_using_default_port/test/positive2.json, assets/queries/cloudFormation/aws/redshift_using_default_port/test/positive_expected_result.json, assets/queries/terraform/aws/redshift_using_default_port/metadata.json, assets/queries/terraform/aws/redshift_using_default_port/query.rego, assets/queries/terraform/aws/redshift_using_default_port/test/negative1.tf, assets/queries/terraform/aws/redshift_using_default_port/test/positive1.tf, assets/queries/terraform/aws/redshift_using_default_port/test/positive2.tf, assets/queries/terraform/aws/redshift_using_default_port/test/positive_expected_result.json, e2e/fixtures/E2E_CLI_031_RESULT.html, e2e/fixtures/E2E_CLI_032_RESULT.json, e2e/fixtures/E2E_CLI_033_RESULT.json, e2e/fixtures/samples/scan-ignore/disable.tf, e2e/testcases/e2e-cli-018_scan_exclude-categories.go, e2e/testcases/e2e-cli-020_scan_exclude-queries.go, e2e/testcases/e2e-cli-035_scan_exclude-results.go
- Added "Redshift Using Default Port" for Ansible, CloudFormation, and Terraform
=> feat(query): added "Redshift Using Default Port" for Ansible, CloudFormation, and Terraform

assets/queries/terraform/gcp/kms_admin_and_crypto_key_roles_in_use/metadata.json, assets/queries/terraform/gcp/kms_admin_and_crypto_key_roles_in_use/query.rego, assets/queries/terraform/gcp/kms_admin_and_crypto_key_roles_in_use/test/negative1.tf, assets/queries/terraform/gcp/kms_admin_and_crypto_key_roles_in_use/test/positive1.tf, assets/queries/terraform/gcp/kms_admin_and_crypto_key_roles_in_use/test/positive_expected_result.json
- Added "KMS Admin and CryptoKey Roles In Use" for Terraform
=> feat(query): added "KMS Admin and CryptoKey Roles In Use" for Terraform

assets/queries/googleDeploymentManager/gke_legacy_authorization_enabled/metadata.json, assets/queries/googleDeploymentManager/gke_legacy_authorization_enabled/query.rego, assets/queries/googleDeploymentManager/gke_legacy_authorization_enabled/test/negative1.yaml, assets/queries/googleDeploymentManager/gke_legacy_authorization_enabled/test/negative2.yaml, assets/queries/googleDeploymentManager/gke_legacy_authorization_enabled/test/positive1.yaml, assets/queries/googleDeploymentManager/gke_legacy_authorization_enabled/test/positive_expected_result.json
- Added "GKE Legacy Authorization Enabled" for Google Deployment Manager
=> feat(query): added "GKE Legacy Authorization Enabled" for Google Deployment Manager

assets/queries/googleDeploymentManager/cloud_storage_bucket_is_publicly_accessible/metadata.json, assets/queries/googleDeploymentManager/cloud_storage_bucket_is_publicly_accessible/query.rego, assets/queries/googleDeploymentManager/cloud_storage_bucket_is_publicly_accessible/test/negative1.yaml, assets/queries/googleDeploymentManager/cloud_storage_bucket_is_publicly_accessible/test/negative2.yaml, assets/queries/googleDeploymentManager/cloud_storage_bucket_is_publicly_accessible/test/positive1.yaml, assets/queries/googleDeploymentManager/cloud_storage_bucket_is_publicly_accessible/test/positive2.yaml, assets/queries/googleDeploymentManager/cloud_storage_bucket_is_publicly_accessible/test/positive_expected_result.json
- Added "Cloud Storage Bucket Is Publicly Accessible" for Google Deployment Manager
=> feat(query): added "Cloud Storage Bucket Is Publicly Accessible" for Google Deployment Manager

assets/queries/googleDeploymentManager/cluster_master_authentication_disabled/metadata.json, assets/queries/googleDeploymentManager/cluster_master_authentication_disabled/query.rego, assets/queries/googleDeploymentManager/cluster_master_authentication_disabled/test/negative1.yaml, assets/queries/googleDeploymentManager/cluster_master_authentication_disabled/test/positive1.yaml, assets/queries/googleDeploymentManager/cluster_master_authentication_disabled/test/positive2.yaml, assets/queries/googleDeploymentManager/cluster_master_authentication_disabled/test/positive3.yaml, assets/queries/googleDeploymentManager/cluster_master_authentication_disabled/test/positive_expected_result.json
- Added "Cluster Master Authentication Disabled" for Google Deployment Manager
=> feat(query): added "Cluster Master Authentication Disabled" for Google Deployment Manager

assets/queries/googleDeploymentManager/node_auto_upgrade_disabled/metadata.json, assets/queries/googleDeploymentManager/node_auto_upgrade_disabled/query.rego, assets/queries/googleDeploymentManager/node_auto_upgrade_disabled/test/negative1.yaml, assets/queries/googleDeploymentManager/node_auto_upgrade_disabled/test/positive1.yaml, assets/queries/googleDeploymentManager/node_auto_upgrade_disabled/test/positive2.yaml, assets/queries/googleDeploymentManager/node_auto_upgrade_disabled/test/positive3.yaml, assets/queries/googleDeploymentManager/node_auto_upgrade_disabled/test/positive4.yaml, assets/queries/googleDeploymentManager/node_auto_upgrade_disabled/test/positive_expected_result.json
- Added "Node auto upgrade disabled" for Google Deployment Manager
=> feat(query): added "Node auto upgrade disabled" for Google Deployment Manager

assets/queries/googleDeploymentManager/ip_aliasing_disabled/metadata.json, assets/queries/googleDeploymentManager/ip_aliasing_disabled/query.rego, assets/queries/googleDeploymentManager/ip_aliasing_disabled/test/negative1.yaml, assets/queries/googleDeploymentManager/ip_aliasing_disabled/test/positive1.yaml, assets/queries/googleDeploymentManager/ip_aliasing_disabled/test/positive2.yaml, assets/queries/googleDeploymentManager/ip_aliasing_disabled/test/positive3.yaml, assets/queries/googleDeploymentManager/ip_aliasing_disabled/test/positive_expected_result.json
- Added "IP Aliasing Disabled" for Google Deployment Manager
=> feat(query): added "IP Aliasing Disabled" for Google Deployment Manager

assets/queries/googleDeploymentManager/network_policy_disabled/metadata.json, assets/queries/googleDeploymentManager/network_policy_disabled/query.rego, assets/queries/googleDeploymentManager/network_policy_disabled/test/negative1.yaml, assets/queries/googleDeploymentManager/network_policy_disabled/test/positive1.yaml, assets/queries/googleDeploymentManager/network_policy_disabled/test/positive2.yaml, assets/queries/googleDeploymentManager/network_policy_disabled/test/positive3.yaml, assets/queries/googleDeploymentManager/network_policy_disabled/test/positive4.yaml, assets/queries/googleDeploymentManager/network_policy_disabled/test/positive_expected_result.json
- Added "Network Policy Disabled" for Google Deployment Manager
=> feat(query): added "Network Policy Disabled" for Google Deployment Manager

assets/queries/ansible/gcp/sql_db_instance_with_ssl_disabled/metadata.json, assets/queries/googleDeploymentManager/sql_db_instance_with_ssl_disabled/metadata.json, assets/queries/googleDeploymentManager/sql_db_instance_with_ssl_disabled/query.rego, assets/queries/googleDeploymentManager/sql_db_instance_with_ssl_disabled/test/negative1.yaml, assets/queries/googleDeploymentManager/sql_db_instance_with_ssl_disabled/test/positive1.yaml, assets/queries/googleDeploymentManager/sql_db_instance_with_ssl_disabled/test/positive2.yaml, assets/queries/googleDeploymentManager/sql_db_instance_with_ssl_disabled/test/positive3.yaml, assets/queries/googleDeploymentManager/sql_db_instance_with_ssl_disabled/test/positive_expected_result.json, assets/queries/terraform/gcp/sql_db_instance_with_ssl_disabled/metadata.json
- Added "SQL DB Instance With SSL Disabled" for Google Deployment Manager
=> feat(query): added "SQL DB Instance With SSL Disabled" for Google Deployment Manager

.github/workflows/release.yml
=> ci(goreleaser): increase time out to 2 hours

pkg/scan/utils.go
-fix terraformer output dir being deleted
=> fix(terraformer): fix terraformer output dir being deleted

develop/integrations_terraformer/index.html
=> fix(pages): fixed Terraformer gifs path

latest/integrations_terraformer/index.html
- fixed Terraformer gif paths in latest
=> fix(pages): fixed Terraformer gif paths in latest

.github/workflows/go-ci.yml, .github/workflows/go-e2e.yaml, Makefile, README.md, pkg/terraformer/aws/aws_cloud_provider.go, pkg/terraformer/aws/aws_cloud_provider_test.go, pkg/terraformer/terraformer.go, pkg/terraformer/terraformer_alt.go, pkg/terraformer/terraformer_test.go
=> build(env): added dev build tag

assets/queries/terraform/aws/security_group_rules_without_description/query.rego, assets/queries/terraform/aws/security_group_rules_without_description/test/negative2.tf, assets/queries/terraform/aws/security_group_rules_without_description/test/positive2.tf, assets/queries/terraform/aws/security_group_rules_without_description/test/positive_expected_result.json
Signed-off-by: Felipe Avelar <felipe.avelar@outlook.com>
Closes #4691 
- update ingress/egress description terraform query to check when there are multiple ingress/egress blocks
=> fix(query): fix terraform query for ingress/egress description

assets/queries/googleDeploymentManager/cloud_storage_anonymous_or_publicly_accessible/metadata.json, assets/queries/googleDeploymentManager/cloud_storage_anonymous_or_publicly_accessible/query.rego, assets/queries/googleDeploymentManager/cloud_storage_anonymous_or_publicly_accessible/test/negative1.yaml, assets/queries/googleDeploymentManager/cloud_storage_anonymous_or_publicly_accessible/test/positive1.yaml, assets/queries/googleDeploymentManager/cloud_storage_anonymous_or_publicly_accessible/test/positive2.yaml, assets/queries/googleDeploymentManager/cloud_storage_anonymous_or_publicly_accessible/test/positive3.yaml, assets/queries/googleDeploymentManager/cloud_storage_anonymous_or_publicly_accessible/test/positive_expected_result.json
- Added "Cloud Storage Anonymous or Publicly Accessible" for Google Deployment Manager
=> feat(query): added "Cloud Storage Anonymous or Publicly Accessible" for Google Deployment Manager

assets/queries/googleDeploymentManager/bigquery_database_is_public/metadata.json, assets/queries/googleDeploymentManager/bigquery_database_is_public/query.rego, assets/queries/googleDeploymentManager/bigquery_database_is_public/test/negative1.yaml, assets/queries/googleDeploymentManager/bigquery_database_is_public/test/negative2.yaml, assets/queries/googleDeploymentManager/bigquery_database_is_public/test/positive1.yaml, assets/queries/googleDeploymentManager/bigquery_database_is_public/test/positive_expected_result.json
- Added "BigQuery Dataset Is Public" for Google Deployment Manager
=> feat(query): added "BigQuery Dataset Is Public" for Google Deployment Manager

assets/queries/googleDeploymentManager/gke_master_authorized_networks_disabled/metadata.json, assets/queries/googleDeploymentManager/gke_master_authorized_networks_disabled/query.rego, assets/queries/googleDeploymentManager/gke_master_authorized_networks_disabled/test/negative1.yaml, assets/queries/googleDeploymentManager/gke_master_authorized_networks_disabled/test/positive1.yaml, assets/queries/googleDeploymentManager/gke_master_authorized_networks_disabled/test/positive2.yaml, assets/queries/googleDeploymentManager/gke_master_authorized_networks_disabled/test/positive_expected_result.json
- Added "GKE Master Authorized Networks Disabled" for Google Deployment Manager
=> feat(query): added "GKE Master Authorized Networks Disabled" for Google Deployment Manager

assets/queries/googleDeploymentManager/stackdriver_monitoring_disabled/metadata.json, assets/queries/googleDeploymentManager/stackdriver_monitoring_disabled/query.rego, assets/queries/googleDeploymentManager/stackdriver_monitoring_disabled/test/negative1.yaml, assets/queries/googleDeploymentManager/stackdriver_monitoring_disabled/test/positive1.yaml, assets/queries/googleDeploymentManager/stackdriver_monitoring_disabled/test/positive2.yaml, assets/queries/googleDeploymentManager/stackdriver_monitoring_disabled/test/positive_expected_result.json
- Added "Stackdriver Monitoring Disabled" for Google Deployment Manager
=> feat(query): added "Stackdriver Monitoring Disabled" for Google Deployment Manager

assets/libraries/common.rego, assets/queries/ansible/gcp/ssh_access_is_not_restricted/query.rego, assets/queries/googleDeploymentManager/ssh_access_is_not_restricted/metadata.json, assets/queries/googleDeploymentManager/ssh_access_is_not_restricted/query.rego, assets/queries/googleDeploymentManager/ssh_access_is_not_restricted/test/negative1.yaml, assets/queries/googleDeploymentManager/ssh_access_is_not_restricted/test/positive1.yaml, assets/queries/googleDeploymentManager/ssh_access_is_not_restricted/test/positive2.yaml, assets/queries/googleDeploymentManager/ssh_access_is_not_restricted/test/positive_expected_result.json, assets/queries/terraform/gcp/ssh_access_is_not_restricted/query.rego
- Added "SSH Access Is Not Restricted" for Google Deployment Manager
=> feat(query): added "SSH Access Is Not Restricted" for Google Deployment Manager

assets/queries/googleDeploymentManager/cluster_labels_disabled/metadata.json, assets/queries/googleDeploymentManager/cluster_labels_disabled/query.rego, assets/queries/googleDeploymentManager/cluster_labels_disabled/test/negative1.yaml, assets/queries/googleDeploymentManager/cluster_labels_disabled/test/positive1.yaml, assets/queries/googleDeploymentManager/cluster_labels_disabled/test/positive_expected_result.json
- Added "Cluster Labels Disabled" for Google Deployment Manager
=> feat(query): added "Cluster Labels Disabled" for Google Deployment Manager

assets/queries/googleDeploymentManager/stackdriver_logging_disabled/metadata.json, assets/queries/googleDeploymentManager/stackdriver_logging_disabled/query.rego, assets/queries/googleDeploymentManager/stackdriver_logging_disabled/test/negative1.yaml, assets/queries/googleDeploymentManager/stackdriver_logging_disabled/test/positive1.yaml, assets/queries/googleDeploymentManager/stackdriver_logging_disabled/test/positive2.yaml, assets/queries/googleDeploymentManager/stackdriver_logging_disabled/test/positive_expected_result.json
- Added "Stackdriver Logging Disabled" for Google Deployment Manager
=> feat(query): added "Stackdriver Logging Disabled" for Google Deployment Manager

assets/queries/googleDeploymentManager/client_certificate_disabled/metadata.json, assets/queries/googleDeploymentManager/client_certificate_disabled/query.rego, assets/queries/googleDeploymentManager/client_certificate_disabled/test/negative1.yaml, assets/queries/googleDeploymentManager/client_certificate_disabled/test/positive1.yaml, assets/queries/googleDeploymentManager/client_certificate_disabled/test/positive2.yaml, assets/queries/googleDeploymentManager/client_certificate_disabled/test/positive3.yaml, assets/queries/googleDeploymentManager/client_certificate_disabled/test/positive_expected_result.json
- Added "Client Certificate Disabled" for Google Deployment Manager
=> feat(query): added "Client Certificate Disabled" for Google Deployment Manager

pkg/model/model_yaml.go, pkg/parser/yaml/parser_test.go
=> fix(parser): added YAML alias as string

pkg/parser/terraform/converter/default.go
- Added type handler to Terraform convertBody function 
=> fix(parser):  added type handler to Terraform convertBody function 

assets/queries/terraform/aws/ec2_instance_monitoring_disabled/test/negative3.json, assets/queries/terraform/aws/ec2_instance_monitoring_disabled/test/positive5.json, assets/queries/terraform/aws/ec2_instance_monitoring_disabled/test/positive_expected_result.json, docs/platforms.md, pkg/analyzer/analyzer.go
Closes #4764 
- Added support to Cloud Development Kit for Terraform (CDKTF)
=> feat(analyzer): added support to Cloud Development Kit for Terraform (CDKTF)

assets/queries/ansible/gcp/oslogin_is_disabled_for_vm_instance/metadata.json, assets/queries/googleDeploymentManager/os_login_is_disabled_for_vm_instance/metadata.json, assets/queries/googleDeploymentManager/os_login_is_disabled_for_vm_instance/query.rego, assets/queries/googleDeploymentManager/os_login_is_disabled_for_vm_instance/test/negative1.yaml, assets/queries/googleDeploymentManager/os_login_is_disabled_for_vm_instance/test/negative2.yaml, assets/queries/googleDeploymentManager/os_login_is_disabled_for_vm_instance/test/positive1.yaml, assets/queries/googleDeploymentManager/os_login_is_disabled_for_vm_instance/test/positive_expected_result.json
- Added "OSLogin Is Disabled In VM Instance" for Google Deployment Manager
=> feat(query): added "OSLogin Is Disabled In VM Instance" for Google Deployment Manager

assets/queries/googleDeploymentManager/mysql_instance_with_local_infile_on/metadata.json, assets/queries/googleDeploymentManager/mysql_instance_with_local_infile_on/query.rego, assets/queries/googleDeploymentManager/mysql_instance_with_local_infile_on/test/negative1.yaml, assets/queries/googleDeploymentManager/mysql_instance_with_local_infile_on/test/negative2.yaml, assets/queries/googleDeploymentManager/mysql_instance_with_local_infile_on/test/positive1.yaml, assets/queries/googleDeploymentManager/mysql_instance_with_local_infile_on/test/positive_expected_result.json
- Added "MySQL Instance With Local Infile On" for Google Deployment Manager
=> feat(query): added "MySQL Instance With Local Infile On" for Google Deployment Manager

assets/queries/cloudFormation/aws/api_gateway_without_configured_authorizer/metadata.json, assets/queries/cloudFormation/aws/api_gateway_without_configured_authorizer/query.rego, assets/queries/cloudFormation/aws/api_gateway_without_configured_authorizer/test/negative1.yaml, assets/queries/cloudFormation/aws/api_gateway_without_configured_authorizer/test/negative2.yaml, assets/queries/cloudFormation/aws/api_gateway_without_configured_authorizer/test/negative3 .json, assets/queries/cloudFormation/aws/api_gateway_without_configured_authorizer/test/negative4.json, assets/queries/cloudFormation/aws/api_gateway_without_configured_authorizer/test/positive1.yaml, assets/queries/cloudFormation/aws/api_gateway_without_configured_authorizer/test/positive2.yaml, assets/queries/cloudFormation/aws/api_gateway_without_configured_authorizer/test/positive3.yaml, assets/queries/cloudFormation/aws/api_gateway_without_configured_authorizer/test/positive4.yaml, assets/queries/cloudFormation/aws/api_gateway_without_configured_authorizer/test/positive5.json, assets/queries/cloudFormation/aws/api_gateway_without_configured_authorizer/test/positive6.json, assets/queries/cloudFormation/aws/api_gateway_without_configured_authorizer/test/positive7.json, assets/queries/cloudFormation/aws/api_gateway_without_configured_authorizer/test/positive8.json, assets/queries/cloudFormation/aws/api_gateway_without_configured_authorizer/test/positive_expected_result.json, assets/queries/terraform/aws/api_gateway_without_configured_authorizer/metadata.json, assets/queries/terraform/aws/api_gateway_without_configured_authorizer/query.rego, assets/queries/terraform/aws/api_gateway_without_configured_authorizer/test/negative.tf, assets/queries/terraform/aws/api_gateway_without_configured_authorizer/test/positive.tf, assets/queries/terraform/aws/api_gateway_without_configured_authorizer/test/positive_expected_result.json
- Added "API Gateway Without Configured Authorizer" for CloudFormation and Terraform
=> feat(query): added "API Gateway Without Configured Authorizer" for CloudFormation and Terraform

docs/results.md
=> feat(docs): updated ASFF documentation

pkg/engine/provider/extract.go
- Fix generic error message go-getter
=> fix(golang): Generic error message go-getter

assets/queries/ansible/aws/ec2_instance_using_default_vpc/metadata.json, assets/queries/ansible/aws/ec2_instance_using_default_vpc/query.rego, assets/queries/ansible/aws/ec2_instance_using_default_vpc/test/negative.yaml, assets/queries/ansible/aws/ec2_instance_using_default_vpc/test/positive.yaml, assets/queries/ansible/aws/ec2_instance_using_default_vpc/test/positive_expected_result.json, assets/queries/cloudFormation/aws/ec2_instance_using_default_vpc/metadata.json, assets/queries/cloudFormation/aws/ec2_instance_using_default_vpc/query.rego, assets/queries/cloudFormation/aws/ec2_instance_using_default_vpc/test/negative1.yaml, assets/queries/cloudFormation/aws/ec2_instance_using_default_vpc/test/negative2.json, assets/queries/cloudFormation/aws/ec2_instance_using_default_vpc/test/positive1.yaml, assets/queries/cloudFormation/aws/ec2_instance_using_default_vpc/test/positive2.json, assets/queries/cloudFormation/aws/ec2_instance_using_default_vpc/test/positive_expected_result.json, assets/queries/terraform/aws/ec2_instance_using_default_vpc/metadata.json, assets/queries/terraform/aws/ec2_instance_using_default_vpc/query.rego, assets/queries/terraform/aws/ec2_instance_using_default_vpc/test/negative1.tf, assets/queries/terraform/aws/ec2_instance_using_default_vpc/test/positive1.tf, assets/queries/terraform/aws/ec2_instance_using_default_vpc/test/positive_expected_result.json
- Added "EC2 Instance Using Default VPC" for Ansible, CloudFormation, and Terraform
=> feat(query): added "EC2 Instance Using Default VPC" for Ansible, CloudFormation, and Terraform

docs/commands.md, docs/dockerhub.md, e2e/fixtures/assets/scan_help, e2e/fixtures/schemas/result-asff.json, internal/console/assets/scan-flags.json, internal/console/scan.go, pkg/engine/inspector_test.go, pkg/engine/source/filesystem.go, pkg/engine/source/filesystem_test.go, pkg/scan/client.go, pkg/scan/utils.go, pkg/scanner/scanner_test.go
Closes #4809 
- changed flag `-q` from string to strings
- changed patterns of ASFF schema
=> feat(cli): multiple paths for queries

.github/scripts/release-commits/get_commits.py, .github/scripts/release-commits/requirements.txt, .github/workflows/release-commits.yaml
- Added release commits action: collect all the commits between the last version and master as well as the community contributors during this period
=> feat(ci): added release commits action

assets/queries/k8s/readiness_probe_is_not_configured/query.rego
**Problem**
- `document.spec[types[x]][j]` only applies to Pods but not Deployment, DaemonSet, etc. 
- Related to that, `searchKey` points to the wrong location with resources other than Pods
- `readinessProbe`, by design, is not working with `initContainers` (see [here](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/)):
> Also, init containers do not support lifecycle, livenessProbe, readinessProbe, or startupProbe because they must run to completion before the Pod can be ready.
- A rule implementation analogous to the livenessProbe rule which remediates the described issues
=> fix(query): extended readinessProbe k8s rule to cover additional resources

assets/queries/terraform/aws_bom/sqs/query.rego, assets/queries/terraform/aws_bom/sqs/test/positive_expected_result.json
- Fixed SQS: deleted rule related to `aws_sqs_queue_policy`
=> fix(bom): fixed SQS

assets/queries/ansible/aws/rds_associated_with_public_subnet/metadata.json, assets/queries/ansible/aws/rds_associated_with_public_subnet/query.rego, assets/queries/ansible/aws/rds_associated_with_public_subnet/test/negative.yaml, assets/queries/ansible/aws/rds_associated_with_public_subnet/test/positive.yaml, assets/queries/ansible/aws/rds_associated_with_public_subnet/test/positive_expected_result.json, assets/queries/cloudFormation/aws/rds_associated_with_public_subnet/metadata.json, assets/queries/cloudFormation/aws/rds_associated_with_public_subnet/query.rego, assets/queries/cloudFormation/aws/rds_associated_with_public_subnet/test/negative1.yaml, assets/queries/cloudFormation/aws/rds_associated_with_public_subnet/test/negative2.json, assets/queries/cloudFormation/aws/rds_associated_with_public_subnet/test/positive1.yaml, assets/queries/cloudFormation/aws/rds_associated_with_public_subnet/test/positive2.json, assets/queries/cloudFormation/aws/rds_associated_with_public_subnet/test/positive_expected_result.json, assets/queries/terraform/aws/rds_associated_with_public_subnet/metadata.json, assets/queries/terraform/aws/rds_associated_with_public_subnet/query.rego, assets/queries/terraform/aws/rds_associated_with_public_subnet/test/negative1.tf, assets/queries/terraform/aws/rds_associated_with_public_subnet/test/positive1.tf, assets/queries/terraform/aws/rds_associated_with_public_subnet/test/positive2.tf, assets/queries/terraform/aws/rds_associated_with_public_subnet/test/positive_expected_result.json
- Added "RDS Associated with Public Subnet" for Ansible, CloudFormation, and Terraform
=> feat(query): added "RDS Associated with Public Subnet" for Ansible, CloudFormation, and Terraform

docs/integrations_gitlabci.md, examples/gitlab/KICS.v1.gitlabci.yaml, examples/jenkins/agent-linux-simple-declarative.jenkinsfile
- Removed gitlab ci binary example
=> doc(integrations): Removed GitlabCI binary example

pkg/report/template/html/report.tmpl
- Added Checkmarx logo to HTML report
=> feat(report): added Checkmarx logo to HTML report

e2e/fixtures/samples/queries/valid/multiple_query/s3_bucket_without_enabled_mfa_delete/metadata.json, e2e/fixtures/samples/queries/valid/multiple_query/s3_bucket_without_enabled_mfa_delete/query.rego, e2e/testcases/e2e-cli-031_scan_report-formats.go, e2e/testcases/e2e-cli-054_scan_multiple-queries-path.go, pkg/engine/inspector_test.go, pkg/engine/source/filesystem_test.go, pkg/scan/utils.go, pkg/scan/utils_test.go, pkg/scanner/scanner_test.go
- added unit tests for multiple query path
=> feat(tests): added unit tests for multiple query path

assets/queries/azureResourceManager/trusted_microsoft_services_not_enabled/metadata.json
- Update "Trusted Microsoft Services Not Enabled" descriptionUrl to reflect the updated Azure documentation.
=> Update "Trusted Microsoft Services Not Enabled".

pkg/report/model/junit.go, pkg/report/model/junit_test.go, pkg/report/pdf.go
- Fixed version output on junit and pdf reports
=> fix(reports): Version output on reports

assets/queries/k8s/docker_daemon_socket_is_exposed_to_containers/query.rego
- Merge CxPolicy rules into one by leveraging `data.generic.k8s.getSpecInfo`
=> refactor(query): Simplify docker_daemon_socket_is_exposed_to_containers k8s rule

assets/queries/k8s/invalid_image/test/positive_expected_result.json
- Fixed expected result with the wrong query name
=> fix(query): fixed positive expected results for Invalid Image Tag

assets/queries/terraform/alicloud/oss_bucket_transfer_acceleration_disabled/metadata.json, assets/queries/terraform/alicloud/oss_bucket_transfer_acceleration_disabled/query.rego, assets/queries/terraform/alicloud/oss_bucket_transfer_acceleration_disabled/test/negative1.tf, assets/queries/terraform/alicloud/oss_bucket_transfer_acceleration_disabled/test/positive1.tf, assets/queries/terraform/alicloud/oss_bucket_transfer_acceleration_disabled/test/positive2.tf, assets/queries/terraform/alicloud/oss_bucket_transfer_acceleration_disabled/test/positive_expected_result.json, test/main_test.go
- added "OSS Bucket Transfer Acceleration Disabled" for terraform.
=> Feat(query): added "OSS Bucket Transfer Acceleration Disabled" for terraform.

pkg/report/pdf.go
- Changed row length of description on pdf
=> fix(report): Fix pdf description row length

assets/queries/terraform/alicloud/rds_instance_log_disconenctions_disabled/metadata.json, assets/queries/terraform/alicloud/rds_instance_log_disconenctions_disabled/query.rego, assets/queries/terraform/alicloud/rds_instance_log_disconenctions_disabled/test/negative1.tf, assets/queries/terraform/alicloud/rds_instance_log_disconenctions_disabled/test/positive1.tf, assets/queries/terraform/alicloud/rds_instance_log_disconenctions_disabled/test/positive2.tf, assets/queries/terraform/alicloud/rds_instance_log_disconenctions_disabled/test/positive_expected_result.json
- Added Alicloud RDS Instance Log Disconnections Disabled
=> Feat(query): Added Alicloud RDS Instance Log Disconnections Disabled for Terraform

assets/queries/terraform/alicloud/oss_bucket_public_access_enabled/metadata.json, assets/queries/terraform/alicloud/oss_bucket_public_access_enabled/query.rego, assets/queries/terraform/alicloud/oss_bucket_public_access_enabled/test/negative1.tf, assets/queries/terraform/alicloud/oss_bucket_public_access_enabled/test/negative2.tf, assets/queries/terraform/alicloud/oss_bucket_public_access_enabled/test/positive1.tf, assets/queries/terraform/alicloud/oss_bucket_public_access_enabled/test/positive2.tf, assets/queries/terraform/alicloud/oss_bucket_public_access_enabled/test/positive_expected_result.json
- Alicloud Oss Bucket Public Access Enabled Query for Terraform
=> Feat.(query): Added Alicloud Oss Bucket Public Access Enabled Query for Terraform

assets/libraries/terraform.rego, assets/queries/terraform/alicloud/oss_buckets_securetransport_disabled/metadata.json, assets/queries/terraform/alicloud/oss_buckets_securetransport_disabled/query.rego, assets/queries/terraform/alicloud/oss_buckets_securetransport_disabled/test/negative1.tf, assets/queries/terraform/alicloud/oss_buckets_securetransport_disabled/test/negative2.tf, assets/queries/terraform/alicloud/oss_buckets_securetransport_disabled/test/positive1.tf, assets/queries/terraform/alicloud/oss_buckets_securetransport_disabled/test/positive2.tf, assets/queries/terraform/alicloud/oss_buckets_securetransport_disabled/test/positive_expected_result.json, test/main_test.go
- Added Alicloud Oss Buckets Secure Transport Disabled Query for Terraform
=> Feat.(query): Added Alicloud Oss Buckets Secure Transport Disabled Query for Terraform

assets/queries/terraform/alicloud/oss_bucket_lifecycle_disabled/metadata.json, assets/queries/terraform/alicloud/oss_bucket_lifecycle_disabled/query.rego, assets/queries/terraform/alicloud/oss_bucket_lifecycle_disabled/test/negative1.tf, assets/queries/terraform/alicloud/oss_bucket_lifecycle_disabled/test/positive1.tf, assets/queries/terraform/alicloud/oss_bucket_lifecycle_disabled/test/positive2.tf, assets/queries/terraform/alicloud/oss_bucket_lifecycle_disabled/test/positive_expected_result.json
- Lifecycle_rule Disabled Query for Alicloud Terraform
=> Feat(query): Added Lifecycle_rule Disabled Query for Alicloud Terraform

assets/queries/terraform/alicloud/oss_bucket_ip_restriction_disabled/metadata.json, assets/queries/terraform/alicloud/oss_bucket_ip_restriction_disabled/query.rego, assets/queries/terraform/alicloud/oss_bucket_ip_restriction_disabled/test/negative1.tf, assets/queries/terraform/alicloud/oss_bucket_ip_restriction_disabled/test/negative2.tf, assets/queries/terraform/alicloud/oss_bucket_ip_restriction_disabled/test/positive1.tf, assets/queries/terraform/alicloud/oss_bucket_ip_restriction_disabled/test/positive_expected_result.json
- Ip Restriction Disabled Query for Terraform Alicloud
=> Feat.(Query) Added Ip Restriction Disabled Query for Terraform Alicloud

assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/query.rego, assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/negative4.tf
- Added Allow true to deny_http_requests function
=> Fix(query): S3 Bucket Policy Accepts Http Requests

assets/libraries/common.rego, assets/libraries/terraform.rego, assets/queries/terraform/alicloud/public_security_group_rule_sensitive_port/metadata.json, assets/queries/terraform/alicloud/public_security_group_rule_sensitive_port/query.rego, assets/queries/terraform/alicloud/public_security_group_rule_sensitive_port/test/negative1.tf, assets/queries/terraform/alicloud/public_security_group_rule_sensitive_port/test/negative2.tf, assets/queries/terraform/alicloud/public_security_group_rule_sensitive_port/test/positive1.tf, assets/queries/terraform/alicloud/public_security_group_rule_sensitive_port/test/positive2.tf, assets/queries/terraform/alicloud/public_security_group_rule_sensitive_port/test/positive3.tf, assets/queries/terraform/alicloud/public_security_group_rule_sensitive_port/test/positive_expected_result.json, assets/queries/terraform/aws/sensitive_port_is_exposed_to_entire_network/metadata.json, assets/queries/terraform/aws/sensitive_port_is_exposed_to_entire_network/test/positive_expected_result.json, assets/queries/terraform/aws/sensitive_port_is_exposed_to_small_public_network/metadata.json, assets/queries/terraform/aws/sensitive_port_is_exposed_to_small_public_network/test/positive_expected_result.json, assets/queries/terraform/aws/sensitive_port_is_exposed_to_wide_private_network/metadata.json, assets/queries/terraform/aws/sensitive_port_is_exposed_to_wide_private_network/test/positive_expected_result.json, assets/queries/terraform/azure/sensitive_port_is_exposed_to_entire_network/metadata.json, assets/queries/terraform/azure/sensitive_port_is_exposed_to_small_public_network/metadata.json, assets/queries/terraform/azure/sensitive_port_is_exposed_to_wide_private_network/metadata.json
Closes #
- Added Alicloud Public Security Group Rule Sensitive Port for Terraform
- Added port 4333: MySQL in tcpPortsMap on common.rego library
- Fixed agregation and positive_expected_result in querys that use  tcpPortsMap on common.rego library
=> feat(Query): Added Alicloud Public Security Group Rule Sensitive Port for Terraform

pkg/scan/utils_test.go
=> fix(test): Test_GetQueryPath

assets/queries/terraform/alicloud/oss_bucket_logging_disabled/metadata.json, assets/queries/terraform/alicloud/oss_bucket_logging_disabled/query.rego, assets/queries/terraform/alicloud/oss_bucket_logging_disabled/test/negative1.tf, assets/queries/terraform/alicloud/oss_bucket_logging_disabled/test/positive1.tf, assets/queries/terraform/alicloud/oss_bucket_logging_disabled/test/positive_expected_result.json
-Logging Disabled Query for Terraform Alicloud
=> Feat(query): Added Logging Disabled Query for Terraform Alicloud

assets/queries/terraform/alicloud/action_trail_logging_all_regions_disabled/metadata.json, assets/queries/terraform/alicloud/action_trail_logging_all_regions_disabled/query.rego, assets/queries/terraform/alicloud/action_trail_logging_all_regions_disabled/test/negative1.tf, assets/queries/terraform/alicloud/action_trail_logging_all_regions_disabled/test/positive1.tf, assets/queries/terraform/alicloud/action_trail_logging_all_regions_disabled/test/positive2.tf, assets/queries/terraform/alicloud/action_trail_logging_all_regions_disabled/test/positive3.tf, assets/queries/terraform/alicloud/action_trail_logging_all_regions_disabled/test/positive4.tf, assets/queries/terraform/alicloud/action_trail_logging_all_regions_disabled/test/positive5.tf, assets/queries/terraform/alicloud/action_trail_logging_all_regions_disabled/test/positive6.tf, assets/queries/terraform/alicloud/action_trail_logging_all_regions_disabled/test/positive7.tf, assets/queries/terraform/alicloud/action_trail_logging_all_regions_disabled/test/positive8.tf, assets/queries/terraform/alicloud/action_trail_logging_all_regions_disabled/test/positive9.tf, assets/queries/terraform/alicloud/action_trail_logging_all_regions_disabled/test/positive_expected_result.json
- Query: Terraform alicloud action trail logging for all regions disabled
=> Feat(Query): Terraform alicloud action trail logging for all regions disabled

.github/ISSUE_TEMPLATE/bug_report.md, README.md, docs/CONTRIBUTING.md, docs/about.md, docs/index.md, docs/roadmap.md
- Replaced all links pointing to gitter with links pointing to GitHub discussions.
=> feat(docs): replaced all links pointing to gitter with links pointing to github discussions

assets/queries/terraform/alicloud/rds_instance_publicly_accessible/metadata.json, assets/queries/terraform/alicloud/rds_instance_publicly_accessible/query.rego, assets/queries/terraform/alicloud/rds_instance_publicly_accessible/test/negative1.tf, assets/queries/terraform/alicloud/rds_instance_publicly_accessible/test/negative2.tf, assets/queries/terraform/alicloud/rds_instance_publicly_accessible/test/positive1.tf, assets/queries/terraform/alicloud/rds_instance_publicly_accessible/test/positive2.tf, assets/queries/terraform/alicloud/rds_instance_publicly_accessible/test/positive_expected_result.json
- Added Alicloud RDS Instance Publicly Acessible for Terraform
=> feat(Query): Added Alicloud RDS Instance Publicly Acessible for Terraform

assets/queries/terraform/alicloud/api_gateway_api_protocol_not_https/metadata.json, assets/queries/terraform/alicloud/api_gateway_api_protocol_not_https/query.rego, assets/queries/terraform/alicloud/api_gateway_api_protocol_not_https/test/negative1.tf, assets/queries/terraform/alicloud/api_gateway_api_protocol_not_https/test/positive1.tf, assets/queries/terraform/alicloud/api_gateway_api_protocol_not_https/test/positive2.tf, assets/queries/terraform/alicloud/api_gateway_api_protocol_not_https/test/positive_expected_result.json
-Added Alicloud API Gateway API protocol Not HTTPS for Terraform
=> feat(query): Added Alicloud API Gateway API protocol Not HTTPS for Terraform

docs/environment_variables_list.md
- added environment variables list
=> feat(docs): added environment variables list

assets/queries/terraform/alicloud/ecs_data_disk_kms_key_id_undefined/metadata.json, assets/queries/terraform/alicloud/ecs_data_disk_kms_key_id_undefined/query.rego, assets/queries/terraform/alicloud/ecs_data_disk_kms_key_id_undefined/test/negative1.tf, assets/queries/terraform/alicloud/ecs_data_disk_kms_key_id_undefined/test/positive1.tf, assets/queries/terraform/alicloud/ecs_data_disk_kms_key_id_undefined/test/positive_expected_result.json
- Query: Ecs Data Disk Kms Key Id Undefined
=> Feat(Query): Terraform Alicloud Query Ecs Data Disk Kms Key Id Undefined

assets/queries/terraform/alicloud/rds_instance_tde_status_disable/metadata.json, assets/queries/terraform/alicloud/rds_instance_tde_status_disable/query.rego, assets/queries/terraform/alicloud/rds_instance_tde_status_disable/test/negative1.tf, assets/queries/terraform/alicloud/rds_instance_tde_status_disable/test/negative2.tf, assets/queries/terraform/alicloud/rds_instance_tde_status_disable/test/negative3.tf, assets/queries/terraform/alicloud/rds_instance_tde_status_disable/test/negative4.tf, assets/queries/terraform/alicloud/rds_instance_tde_status_disable/test/negative5.tf, assets/queries/terraform/alicloud/rds_instance_tde_status_disable/test/positive1.tf, assets/queries/terraform/alicloud/rds_instance_tde_status_disable/test/positive2.tf, assets/queries/terraform/alicloud/rds_instance_tde_status_disable/test/positive3.tf, assets/queries/terraform/alicloud/rds_instance_tde_status_disable/test/positive4.tf, assets/queries/terraform/alicloud/rds_instance_tde_status_disable/test/positive_expected_result.json
-Added Alicloud RDS Instance TDE Status Disabled for Terraform
=> feat(query): Added Alicloud RDS Instance TDE Status Disabled for Terraform

assets/queries/terraform/alicloud/rds_instance_retention_not_recommended/metadata.json, assets/queries/terraform/alicloud/rds_instance_retention_not_recommended/query.rego, assets/queries/terraform/alicloud/rds_instance_retention_not_recommended/test/negative.tf, assets/queries/terraform/alicloud/rds_instance_retention_not_recommended/test/positive1.tf, assets/queries/terraform/alicloud/rds_instance_retention_not_recommended/test/positive2.tf, assets/queries/terraform/alicloud/rds_instance_retention_not_recommended/test/positive3.tf, assets/queries/terraform/alicloud/rds_instance_retention_not_recommended/test/positive4.tf, assets/queries/terraform/alicloud/rds_instance_retention_not_recommended/test/positive_expected_result.json
-Added Alicloud RDS Instance Retention Period Not Recommended for Terraform
=> feat(query): Added Alicloud RDS Instance Retention Period Not Recommended for Terraform

.github/scripts/docs-generator/docs-generator.py
=> update(docs-generator): added trace to severities

assets/queries/terraform/alicloud/kubernetes_cluster_without_terway_as_cni_network_plugin/metadata.json, assets/queries/terraform/alicloud/kubernetes_cluster_without_terway_as_cni_network_plugin/query.rego, assets/queries/terraform/alicloud/kubernetes_cluster_without_terway_as_cni_network_plugin/test/negative1.tf, assets/queries/terraform/alicloud/kubernetes_cluster_without_terway_as_cni_network_plugin/test/positive1.tf, assets/queries/terraform/alicloud/kubernetes_cluster_without_terway_as_cni_network_plugin/test/positive2.tf, assets/queries/terraform/alicloud/kubernetes_cluster_without_terway_as_cni_network_plugin/test/positive3.tf, assets/queries/terraform/alicloud/kubernetes_cluster_without_terway_as_cni_network_plugin/test/positive_expected_result.json, assets/queries/terraform/alicloud/rds_instance_publicly_accessible/metadata.json, assets/queries/terraform/alicloud/rds_instance_publicly_accessible/test/positive_expected_result.json
- Added "Kubernetes Cluster Without Terway as CNI Network Plugin" for Terraform
Alicloud doc:
Terraform doc:
=> feat(query): added "Kubernetes Cluster Without Terway as CNI Network Plugin" for Terraform

docs/commands.md, docs/configuration-file.md, docs/dockerhub.md, docs/results.md, e2e/fixtures/assets/scan_help, go.mod, go.sum, internal/console/helpers/helpers.go, pkg/report/commons.go, pkg/report/csv.go, pkg/report/csv_test.go, pkg/report/model/csv.go, pkg/report/model/csv_test.go
=> feat(report): CSV report

assets/queries/k8s/kubelet_client_certificate_or_key_not_set/metadata.json, assets/queries/k8s/kubelet_client_certificate_or_key_not_set/query.rego, assets/queries/k8s/kubelet_client_certificate_or_key_not_set/test/negative1.yaml, assets/queries/k8s/kubelet_client_certificate_or_key_not_set/test/negative2.yaml, assets/queries/k8s/kubelet_client_certificate_or_key_not_set/test/positive1.yaml, assets/queries/k8s/kubelet_client_certificate_or_key_not_set/test/positive2.yaml, assets/queries/k8s/kubelet_client_certificate_or_key_not_set/test/positive3.yaml, assets/queries/k8s/kubelet_client_certificate_or_key_not_set/test/positive_expected_result.json
-Added Kubelet Client Certificate Or Key Not Set for Kubernetes
=> feat(query): Added Kubelet Client Certificate Or Key Not Set for Kubernetes

assets/libraries/k8s.rego, assets/queries/k8s/authorization_mode_rbac_not_set/metadata.json, assets/queries/k8s/authorization_mode_rbac_not_set/query.rego, assets/queries/k8s/authorization_mode_rbac_not_set/test/negative1.yaml, assets/queries/k8s/authorization_mode_rbac_not_set/test/negative2.yaml, assets/queries/k8s/authorization_mode_rbac_not_set/test/positive1.yaml, assets/queries/k8s/authorization_mode_rbac_not_set/test/positive2.yaml, assets/queries/k8s/authorization_mode_rbac_not_set/test/positive_expected_result.json
- Added Authorization Mode RBAC Not Set for Kubernetes
=> feat(query): Added Authorization Mode RBAC Not Set for Kubernetes

assets/libraries/k8s.rego, assets/queries/k8s/authorization_mode_node_not_set/metadata.json, assets/queries/k8s/authorization_mode_node_not_set/query.rego, assets/queries/k8s/authorization_mode_node_not_set/test/negative1.yaml, assets/queries/k8s/authorization_mode_node_not_set/test/negative2.yaml, assets/queries/k8s/authorization_mode_node_not_set/test/positive1.yaml, assets/queries/k8s/authorization_mode_node_not_set/test/positive2.yaml, assets/queries/k8s/authorization_mode_node_not_set/test/positive_expected_result.json, assets/queries/k8s/authorization_mode_set_to_always_allow/query.rego
-Added Authorization Mode Node Not Set for Kubernetes
=> feat(query): Added Authorization Mode Node Not Set for Kubernetes

assets/libraries/k8s.rego, assets/queries/k8s/authorization_mode_set_to_always_allow/query.rego, assets/queries/k8s/security_context_deny_admission_control_plugin_not_set/metadata.json, assets/queries/k8s/security_context_deny_admission_control_plugin_not_set/query.rego, assets/queries/k8s/security_context_deny_admission_control_plugin_not_set/test/negative1.yaml, assets/queries/k8s/security_context_deny_admission_control_plugin_not_set/test/negative2.yaml, assets/queries/k8s/security_context_deny_admission_control_plugin_not_set/test/negative3.yaml, assets/queries/k8s/security_context_deny_admission_control_plugin_not_set/test/positive1.yaml, assets/queries/k8s/security_context_deny_admission_control_plugin_not_set/test/positive_expected_result.json
- Added Security Context Deny Admission Control Plugin Not Set for Kubernetes
=> feat(query): Added Security Context Deny Admission Control Plugin Not Set for Kubernetes

assets/queries/k8s/kubelet_event_qps_not_properly_set/metadata.json, assets/queries/k8s/kubelet_event_qps_not_properly_set/query.rego, assets/queries/k8s/kubelet_event_qps_not_properly_set/test/negative1.yaml, assets/queries/k8s/kubelet_event_qps_not_properly_set/test/negative2.yaml, assets/queries/k8s/kubelet_event_qps_not_properly_set/test/negative3.yaml, assets/queries/k8s/kubelet_event_qps_not_properly_set/test/negative4.json, assets/queries/k8s/kubelet_event_qps_not_properly_set/test/positive1.yaml, assets/queries/k8s/kubelet_event_qps_not_properly_set/test/positive2.yaml, assets/queries/k8s/kubelet_event_qps_not_properly_set/test/positive3.yaml, assets/queries/k8s/kubelet_event_qps_not_properly_set/test/positive4.yaml, assets/queries/k8s/kubelet_event_qps_not_properly_set/test/positive_expected_result.json
- Added Kubelet Event QPS Not Properly Set for Kubernetes
=> feat(query): Added Kubelet Event QPS Not Properly Set for Kubernetes

e2e/cli_test.go, e2e/fixtures/schemas/result-csv-cis.json, e2e/fixtures/schemas/result-csv.json, e2e/testcases/e2e-cli-031_scan_report-formats.go, e2e/utils/csv.go
Closes #
- This PR introduces a schema validation for the new result format (CSV) provided by kics.
- It also includes validation for CSV reports with CIS DESCRIPTIONS.
=> Feat(E2E): Added E2E Test to validate CSV reports

.github/scripts/metrics/get_metrics.py
- added dockerCompose to queries metric
=> update(metrics): added dockerCompose to queries metric

assets/queries/k8s/service_account_lookup_set_to_false/metadata.json, assets/queries/k8s/service_account_lookup_set_to_false/query.rego, assets/queries/k8s/service_account_lookup_set_to_false/test/negative1.yaml, assets/queries/k8s/service_account_lookup_set_to_false/test/negative2.yaml, assets/queries/k8s/service_account_lookup_set_to_false/test/positive1.yaml, assets/queries/k8s/service_account_lookup_set_to_false/test/positive_expected_result.json
- Added Service Account Lookup Set To False for Kubernetes
=> feat(query): Added Service Account Lookup Set To False for Kubernetes

assets/queries/k8s/auto_tls_set_to_true/metadata.json, assets/queries/k8s/auto_tls_set_to_true/query.rego, assets/queries/k8s/auto_tls_set_to_true/test/negative1.yaml, assets/queries/k8s/auto_tls_set_to_true/test/negative2.yaml, assets/queries/k8s/auto_tls_set_to_true/test/positive1.yaml, assets/queries/k8s/auto_tls_set_to_true/test/positive_expected_result.json
- Added Auto TLS Set To True for kubernetes
=> feat(query): Added Auto TLS Set To True for kubernetes

assets/queries/k8s/peer_auto_tls_set_to_true/metadata.json, assets/queries/k8s/peer_auto_tls_set_to_true/query.rego, assets/queries/k8s/peer_auto_tls_set_to_true/test/negative1.yaml, assets/queries/k8s/peer_auto_tls_set_to_true/test/negative2.yaml, assets/queries/k8s/peer_auto_tls_set_to_true/test/positive1.yaml, assets/queries/k8s/peer_auto_tls_set_to_true/test/positive_expected_result.json
- Added Peer Auto TLS Set To True for Kubernetes
=> feat(query): Added Peer Auto TLS Set To True for Kubernetes

assets/libraries/k8s.rego, assets/queries/k8s/permissive_access_to_create_pods/metadata.json, assets/queries/k8s/permissive_access_to_create_pods/test/positive_expected_result.json, assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/metadata.json, assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/query.rego, assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/test/negative1.yaml, assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/test/negative2.yaml, assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/test/positive1.yaml, assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/test/positive2.yaml, assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/test/positive_expected_result.json
- Terminated Pod Garbage Collector Threshold Not Properly Set for Kubernetes
=> feat(query): Added Terminated Pod Garbage Collector Threshold Not Properly Set for Kubernetes

assets/queries/k8s/service_account_private_key_file_not_defined/metadata.json, assets/queries/k8s/service_account_private_key_file_not_defined/query.rego, assets/queries/k8s/service_account_private_key_file_not_defined/test/negative1.yaml, assets/queries/k8s/service_account_private_key_file_not_defined/test/negative2.yaml, assets/queries/k8s/service_account_private_key_file_not_defined/test/positive1.yaml, assets/queries/k8s/service_account_private_key_file_not_defined/test/positive_expected_result.json
- Added Service Account Private Key File Not Defined for Kubernetes
=> feat(query): Added Service Account Private Key File Not Defined for Kubernetes

assets/queries/k8s/root_ca_file_not_defined/metadata.json, assets/queries/k8s/root_ca_file_not_defined/query.rego, assets/queries/k8s/root_ca_file_not_defined/test/negative1.yaml, assets/queries/k8s/root_ca_file_not_defined/test/negative2.yaml, assets/queries/k8s/root_ca_file_not_defined/test/positive1.yaml, assets/queries/k8s/root_ca_file_not_defined/test/positive_expected_result.json
- Added Root CA File Not Defined for kubernetes
=> feat(query): Added Root CA File Not Defined for kubernetes

assets/queries/k8s/bind_address_not_properly_set/metadata.json, assets/queries/k8s/bind_address_not_properly_set/query.rego, assets/queries/k8s/bind_address_not_properly_set/test/negative1.yaml, assets/queries/k8s/bind_address_not_properly_set/test/negative2.yaml, assets/queries/k8s/bind_address_not_properly_set/test/negative3.yaml, assets/queries/k8s/bind_address_not_properly_set/test/negative4.yaml, assets/queries/k8s/bind_address_not_properly_set/test/positive1.yaml, assets/queries/k8s/bind_address_not_properly_set/test/positive2.yaml, assets/queries/k8s/bind_address_not_properly_set/test/positive3.yaml, assets/queries/k8s/bind_address_not_properly_set/test/positive4.yaml, assets/queries/k8s/bind_address_not_properly_set/test/positive_expected_result.json
- Added Bind Address Not Properly Set for Kubernetes
=> feat(query): Added Bind Address Not Properly Set for Kubernetes

assets/queries/k8s/etcd_tls_certificate_files_not_properly_set/metadata.json, assets/queries/k8s/etcd_tls_certificate_files_not_properly_set/query.rego, assets/queries/k8s/etcd_tls_certificate_files_not_properly_set/test/negative1.yaml, assets/queries/k8s/etcd_tls_certificate_files_not_properly_set/test/negative2.yaml, assets/queries/k8s/etcd_tls_certificate_files_not_properly_set/test/positive1.yaml, assets/queries/k8s/etcd_tls_certificate_files_not_properly_set/test/positive2.yaml, assets/queries/k8s/etcd_tls_certificate_files_not_properly_set/test/positive_expected_result.json
- Added ETCD TLS Certificate Files Not Properly Set for Kubernetes
=> feat(query): Added ETCD TLS Certificate Files Not Properly Set for Kubernetes

assets/queries/k8s/audit_log_path_not_set/metadata.json, assets/queries/k8s/audit_log_path_not_set/query.rego, assets/queries/k8s/audit_log_path_not_set/test/negative1.yaml, assets/queries/k8s/audit_log_path_not_set/test/negative2.yaml, assets/queries/k8s/audit_log_path_not_set/test/positive1.yaml, assets/queries/k8s/audit_log_path_not_set/test/positive_expected_result.json
- Added Audit Log Path Not Set for Kubernetes
=> feat(query): Added Audit Log Path Not Set for Kubernetes

.github/workflows/validate-k8s-samples.yml, assets/queries/k8s/encryption_provider_not_properly_configured/metadata.json, assets/queries/k8s/encryption_provider_not_properly_configured/query.rego, assets/queries/k8s/encryption_provider_not_properly_configured/test/negative1.yaml, assets/queries/k8s/encryption_provider_not_properly_configured/test/positive1.yaml, assets/queries/k8s/encryption_provider_not_properly_configured/test/positive_expected_result.json
- Added Encryption Provider Not Properly Configured for Kubernetes
=> feat(query): Added Encryption Provider Not Properly Configured for Kubernetes

assets/queries/k8s/etcd_peer_tls_certificate_files_not_properly_set/metadata.json, assets/queries/k8s/etcd_peer_tls_certificate_files_not_properly_set/query.rego, assets/queries/k8s/etcd_peer_tls_certificate_files_not_properly_set/test/negative1.yaml, assets/queries/k8s/etcd_peer_tls_certificate_files_not_properly_set/test/negative2.yaml, assets/queries/k8s/etcd_peer_tls_certificate_files_not_properly_set/test/positive1.yaml, assets/queries/k8s/etcd_peer_tls_certificate_files_not_properly_set/test/positive2.yaml, assets/queries/k8s/etcd_peer_tls_certificate_files_not_properly_set/test/positive_expected_result.json
- Added Etcd Peer TLS Certificate Files Not Properly Set for Kubernetes
=> feat(query): Added Etcd Peer TLS Certificate Files Not Properly Set for Kubernetes

assets/queries/k8s/etcd_peer_client_certificate_authentication_set_to_false/metadata.json, assets/queries/k8s/etcd_peer_client_certificate_authentication_set_to_false/query.rego, assets/queries/k8s/etcd_peer_client_certificate_authentication_set_to_false/test/negative1.yaml, assets/queries/k8s/etcd_peer_client_certificate_authentication_set_to_false/test/positive1.yaml, assets/queries/k8s/etcd_peer_client_certificate_authentication_set_to_false/test/positive2.yaml, assets/queries/k8s/etcd_peer_client_certificate_authentication_set_to_false/test/positive_expected_result.json
- Added Etcd Peer Client Certificate Authentication Set To False for Kubernetes
=> feat(query): Added Etcd Peer Client Certificate Authentication Set To False for Kubernetes

assets/queries/k8s/basic_auth_file_is_set/metadata.json, assets/queries/k8s/basic_auth_file_is_set/query.rego, assets/queries/k8s/basic_auth_file_is_set/test/negative1.yaml, assets/queries/k8s/basic_auth_file_is_set/test/negative2.yaml, assets/queries/k8s/basic_auth_file_is_set/test/positive1.yaml, assets/queries/k8s/basic_auth_file_is_set/test/positive2.yaml, assets/queries/k8s/basic_auth_file_is_set/test/positive_expected_result.json
- Added Basic Auth File Is Set for Kubernetes
=> feat(query): Added Basic Auth File Is Set for Kubernetes

assets/queries/k8s/kubelet_https_set_to_false/metadata.json, assets/queries/k8s/kubelet_https_set_to_false/query.rego, assets/queries/k8s/kubelet_https_set_to_false/test/negative1.yaml, assets/queries/k8s/kubelet_https_set_to_false/test/negative2.yaml, assets/queries/k8s/kubelet_https_set_to_false/test/positive1.yaml, assets/queries/k8s/kubelet_https_set_to_false/test/positive_expected_result.json
- Added Kubelet HTTPS Set To False for kubernetes
=> feat(query): Added Kubelet HTTPS Set To False for kubernetes

assets/queries/k8s/insecure_bind_address_set/metadata.json, assets/queries/k8s/insecure_bind_address_set/query.rego, assets/queries/k8s/insecure_bind_address_set/test/negative1.yaml, assets/queries/k8s/insecure_bind_address_set/test/negative2.yaml, assets/queries/k8s/insecure_bind_address_set/test/positive1.yaml, assets/queries/k8s/insecure_bind_address_set/test/positive2.yaml, assets/queries/k8s/insecure_bind_address_set/test/positive_expected_result.json
- Added Insecure Bind Address Set for Kubernetes
=> feat(query): Added Insecure Bind Address Set for Kubernetes

assets/queries/k8s/insecure_port_not_properly_set/metadata.json, assets/queries/k8s/insecure_port_not_properly_set/query.rego, assets/queries/k8s/insecure_port_not_properly_set/test/negative1.yaml, assets/queries/k8s/insecure_port_not_properly_set/test/negative2.yaml, assets/queries/k8s/insecure_port_not_properly_set/test/positive1.yaml, assets/queries/k8s/insecure_port_not_properly_set/test/positive2.yaml, assets/queries/k8s/insecure_port_not_properly_set/test/positive_expected_result.json
- Added Insecure Port Not Properly Set for Kubernetes
=> feat(query): Added Insecure Port Not Properly Set for Kubernetes

assets/queries/dockerCompose/volume_mounted_in_multiple_containers/metadata.json, assets/queries/dockerCompose/volume_mounted_in_multiple_containers/query.rego, assets/queries/dockerCompose/volume_mounted_in_multiple_containers/test/negative1.yaml, assets/queries/dockerCompose/volume_mounted_in_multiple_containers/test/negative2.yaml, assets/queries/dockerCompose/volume_mounted_in_multiple_containers/test/negative3.yaml, assets/queries/dockerCompose/volume_mounted_in_multiple_containers/test/positive1.yaml, assets/queries/dockerCompose/volume_mounted_in_multiple_containers/test/positive2.yaml, assets/queries/dockerCompose/volume_mounted_in_multiple_containers/test/positive3.yaml, assets/queries/dockerCompose/volume_mounted_in_multiple_containers/test/positive4.yaml, assets/queries/dockerCompose/volume_mounted_in_multiple_containers/test/positive_expected_result.json
- Query: Volume Mounted In Multiple Containers for docker compose
=> Feat(Query): Volume Mounted In Multiple Containers for docker compose

assets/queries/cloudFormation/aws/viewer_protocol_policy_allows_http/query.rego, assets/queries/cloudFormation/aws/viewer_protocol_policy_allows_http/test/negative3.yaml
Closes #5156
- update to verify if is defined to allow-all
=> update(query): Viewer Protocol Policy Allows HTTP

assets/queries/terraform/aws/security_groups_not_used/query.rego, assets/queries/terraform/aws/security_groups_not_used/test/negative4.tf
Closes #5183
- Added: Possibility of security group being declared as a variable.
=> Fix(Query): Added possibility of security group being declared as a variable

assets/queries/dockerfile/add_instead_of_copy/metadata.json, assets/queries/dockerfile/add_instead_of_copy/test/positive_expected_result.json
- Updated metadata of Add Instead Copy query
=> update(query): Updated metadata of Add Instead Copy query

assets/queries/terraform/azure/network_interfaces_dont_use_public_ip/metadata.json, docs/creating-queries.md, docs/release_checklist.md, pkg/analyzer/analyzer.go, pkg/analyzer/analyzer_test.go, pkg/engine/provider/filesystem.go, pkg/engine/provider/filesystem_test.go, pkg/scan/utils.go
- Refactored analyzer: analyzer usage when types flag is passed + discard files pointed in --exclude-paths in the analyzer + fix bug related to excluding a single file
- Updated documentation related to release
- Updated documentation related to searchKey
- Updated query description of `Network Interfaces With Public IP (c1573577-e494-4417-8854-7e119368dc8b)`
=> refactor(analyzer): analyzer usage when types flag is passed

docs/integrations_bitbucketpipelines.md, docs/integrations_gitlabci.md, docs/integrations_jenkins.md
- Removed -q flag from integration examples
=> update(docs): Removed -q flag from integration examples

assets/queries/terraform/alicloud/db_instance_publicly_accessible/metadata.json, assets/queries/terraform/alicloud/db_instance_publicly_accessible/query.rego, assets/queries/terraform/alicloud/db_instance_publicly_accessible/test/negative1.tf, assets/queries/terraform/alicloud/db_instance_publicly_accessible/test/negative2.tf, assets/queries/terraform/alicloud/db_instance_publicly_accessible/test/positive1.tf, assets/queries/terraform/alicloud/db_instance_publicly_accessible/test/positive_expected_result.json
- DB Instance Publicly Accessible
=> feat(query): Added DB Instance Publicly Accessible for Terraform Alicloud

assets/queries/terraform/alicloud/nas_file_system_not_encrypted/metadata.json, assets/queries/terraform/alicloud/nas_file_system_not_encrypted/query.rego, assets/queries/terraform/alicloud/nas_file_system_not_encrypted/test/negative.tf, assets/queries/terraform/alicloud/nas_file_system_not_encrypted/test/negative2.tf, assets/queries/terraform/alicloud/nas_file_system_not_encrypted/test/positive.tf, assets/queries/terraform/alicloud/nas_file_system_not_encrypted/test/positive2.tf, assets/queries/terraform/alicloud/nas_file_system_not_encrypted/test/positive_expected_result.json
- NAS File System Not Encrypted
=> feat(query): Added NAS File System Not Encrypted for Terraform Alicloud

assets/queries/terraform/alicloud/nas_file_system_without_kms/metadata.json, assets/queries/terraform/alicloud/nas_file_system_without_kms/query.rego, assets/queries/terraform/alicloud/nas_file_system_without_kms/test/negative.tf, assets/queries/terraform/alicloud/nas_file_system_without_kms/test/negative2.tf, assets/queries/terraform/alicloud/nas_file_system_without_kms/test/positive.tf, assets/queries/terraform/alicloud/nas_file_system_without_kms/test/positive2.tf, assets/queries/terraform/alicloud/nas_file_system_without_kms/test/positive_expected_result.json
- NAS File System Without KMS for Alicloud
=> feat(query): Added NAS File System Without KMS for Alicloud

assets/queries/terraform/alicloud/oss_bucket_has_static_website/metadata.json, assets/queries/terraform/alicloud/oss_bucket_has_static_website/query.rego, assets/queries/terraform/alicloud/oss_bucket_has_static_website/test/negative1.tf, assets/queries/terraform/alicloud/oss_bucket_has_static_website/test/positive1.tf, assets/queries/terraform/alicloud/oss_bucket_has_static_website/test/positive_expected_result.json, assets/queries/terraform/aws/s3_static_website_host_enabled/metadata.json
- Query: OSS Bucket Has Static Website for Alicloud Terraform
=> Feat(Query): OSS Bucket Has Static Website for Alicloud Terraform

assets/queries/terraform/alicloud/ros_stack_retention_disabled/metadata.json, assets/queries/terraform/alicloud/ros_stack_retention_disabled/query.rego, assets/queries/terraform/alicloud/ros_stack_retention_disabled/test/negative.tf, assets/queries/terraform/alicloud/ros_stack_retention_disabled/test/positive.tf, assets/queries/terraform/alicloud/ros_stack_retention_disabled/test/positive2.tf, assets/queries/terraform/alicloud/ros_stack_retention_disabled/test/positive_expected_result.json
- ROS Stack Retention Disabled
=> feat(query): ROS Stack Retention Disabled for Terraform Alicloud

assets/queries/terraform/alicloud/ros_stack_notifications_disabled/metadata.json, assets/queries/terraform/alicloud/ros_stack_notifications_disabled/query.rego, assets/queries/terraform/alicloud/ros_stack_notifications_disabled/test/negative.tf, assets/queries/terraform/alicloud/ros_stack_notifications_disabled/test/positive.tf, assets/queries/terraform/alicloud/ros_stack_notifications_disabled/test/positive2.tf, assets/queries/terraform/alicloud/ros_stack_notifications_disabled/test/positive_expected_result.json
- ROS Stack Notifications Disabled
=> feat(query): Added ROS Stack Notifications Disabled for Terraform Alicloud

assets/queries/terraform/alicloud/high_kms_key_rotation_period/metadata.json, assets/queries/terraform/alicloud/high_kms_key_rotation_period/query.rego, assets/queries/terraform/alicloud/high_kms_key_rotation_period/test/negative1.tf, assets/queries/terraform/alicloud/high_kms_key_rotation_period/test/positive.tf, assets/queries/terraform/alicloud/high_kms_key_rotation_period/test/positive2.tf, assets/queries/terraform/alicloud/high_kms_key_rotation_period/test/positive3.tf, assets/queries/terraform/alicloud/high_kms_key_rotation_period/test/positive4.tf, assets/queries/terraform/alicloud/high_kms_key_rotation_period/test/positive_expected_result.json
- High KMS Key Rotation Period
=> feay(query): Added High KMS Key Rotation Period in Alicloud Terraform

assets/queries/ansible/gcp/google_container_node_pool_auto_repair_disabled/metadata.json, assets/queries/terraform/alicloud/cs_kubernetes_node_pool_auto_repair_disabled/metadata.json, assets/queries/terraform/alicloud/cs_kubernetes_node_pool_auto_repair_disabled/query.rego, assets/queries/terraform/alicloud/cs_kubernetes_node_pool_auto_repair_disabled/test/negative1.tf, assets/queries/terraform/alicloud/cs_kubernetes_node_pool_auto_repair_disabled/test/positive1.tf, assets/queries/terraform/alicloud/cs_kubernetes_node_pool_auto_repair_disabled/test/positive2.tf, assets/queries/terraform/alicloud/cs_kubernetes_node_pool_auto_repair_disabled/test/positive3.tf, assets/queries/terraform/alicloud/cs_kubernetes_node_pool_auto_repair_disabled/test/positive_expected_result.json, assets/queries/terraform/gcp/google_container_node_pool_auto_repair_disabled/metadata.json
- Query: CS Kubernetes Node Pool Auto Repair Disabled for Alicloud Terraform
=> Feat(Query): CS Kubernetes Node Pool Auto Repair Disabled for Alicloud Terraform

assets/queries/terraform/alicloud/no_ros_stack_policy/metadata.json, assets/queries/terraform/alicloud/no_ros_stack_policy/query.rego, assets/queries/terraform/alicloud/no_ros_stack_policy/test/negative.tf, assets/queries/terraform/alicloud/no_ros_stack_policy/test/negative2.tf, assets/queries/terraform/alicloud/no_ros_stack_policy/test/positive.tf, assets/queries/terraform/alicloud/no_ros_stack_policy/test/positive2.tf, assets/queries/terraform/alicloud/no_ros_stack_policy/test/positive3.tf, assets/queries/terraform/alicloud/no_ros_stack_policy/test/positive_expected_result.json
=> feat(query): Added No ROS Stack Policy for Terraform Alicloud 

assets/queries/terraform/alicloud/oss_bucket_logging_disabled/query.rego, assets/queries/terraform/alicloud/oss_bucket_logging_disabled/test/positive2.tf, assets/queries/terraform/alicloud/oss_bucket_logging_disabled/test/positive_expected_result.json
- Add verification for  logging_isenable in OSS Bucket Logging Disabled
=> update(query): OSS Bucket Logging Disabled for Terraform Alicloud

assets/queries/ansible/aws/ecr_image_tag_not_immutable/metadata.json, assets/queries/terraform/aws/ecr_image_tag_not_immutable/metadata.json
=> Update(Query): Updated query descriptions for ECR Image Not Immutable Queries

assets/queries/terraform/alicloud/slb_policy_with_insecure_tls_version_in_use/metadata.json, assets/queries/terraform/alicloud/slb_policy_with_insecure_tls_version_in_use/query.rego, assets/queries/terraform/alicloud/slb_policy_with_insecure_tls_version_in_use/test/negative.tf, assets/queries/terraform/alicloud/slb_policy_with_insecure_tls_version_in_use/test/positive.tf, assets/queries/terraform/alicloud/slb_policy_with_insecure_tls_version_in_use/test/positive_expected_result.json
- SLB Policy With Insecure Tls Version In Use
=> feat(query): Added SLB Policy With Insecure TLS Version In Use for Terraform Alicloud

assets/queries/terraform/alicloud/cmk_is_unusable/metadata.json, assets/queries/terraform/alicloud/cmk_is_unusable/query.rego, assets/queries/terraform/alicloud/cmk_is_unusable/test/negative1.tf, assets/queries/terraform/alicloud/cmk_is_unusable/test/positive1.tf, assets/queries/terraform/alicloud/cmk_is_unusable/test/positive2.tf, assets/queries/terraform/alicloud/cmk_is_unusable/test/positive_expected_result.json
- Query: CMK Is Unusable for Alicloud Terraform
=> Feat(Query): CMK Is Unusable for Alicloud Terraform

assets/queries/dockerfile/unpinned_package_version_in_apk_add/query.rego, assets/queries/dockerfile/unpinned_package_version_in_apk_add/test/negative2.dockerfile
Closes #5124
- Fix issue detecting --virtual package name as a package without pinned version
=> update(query): Unpinned Package Version in Apk Add

assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/negative2.tf
Closes #5245
- Update positive sample in Network ACL With Unrestricted Access To RDP Query
=> update(query): Network ACL With Unrestricted Access To RDP for Terraform AWS

assets/queries/dockerfile/missing_flag_from_dnf_install/query.rego, assets/queries/dockerfile/missing_flag_from_dnf_install/test/negative3.dockerfile
Closes #5284
- Add support for microdnf in run command
=> update(query): Missing Flag From Dnf Install for Dockerfile

docs/results.md
- Removed results formats list from results section
=> update(docs): Removed results formats list from results section

assets/queries/terraform/azure/storage_account_not_using_latest_tls_encryption_version/query.rego, assets/queries/terraform/azure/storage_account_not_using_latest_tls_encryption_version/test/positive.tf, assets/queries/terraform/azure/storage_account_not_using_latest_tls_encryption_version/test/positive_expected_result.json
Closes #5301
- Delete check for incorrect default value
=> update(query): Storage Account Not Using Latest TLS Encryption Version for Terraform Azure

README.md, assets/queries/k8s/bind_address_not_properly_set/test/negative1.yaml, assets/queries/k8s/bind_address_not_properly_set/test/negative2.yaml, assets/queries/k8s/bind_address_not_properly_set/test/positive1.yaml, assets/queries/k8s/bind_address_not_properly_set/test/positive2.yaml, assets/queries/k8s/bind_address_not_properly_set/test/positive_expected_result.json, assets/queries/k8s/root_ca_file_not_defined/test/negative1.yaml, assets/queries/k8s/root_ca_file_not_defined/test/negative2.yaml, assets/queries/k8s/root_ca_file_not_defined/test/positive1.yaml, assets/queries/k8s/root_ca_file_not_defined/test/positive_expected_result.json, assets/queries/k8s/service_account_private_key_file_not_defined/test/negative1.yaml, assets/queries/k8s/service_account_private_key_file_not_defined/test/negative2.yaml, assets/queries/k8s/service_account_private_key_file_not_defined/test/positive1.yaml, assets/queries/k8s/service_account_private_key_file_not_defined/test/positive_expected_result.json, assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/test/negative1.yaml, assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/test/negative2.yaml, assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/test/positive1.yaml, assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/test/positive2.yaml, assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/test/positive_expected_result.json, assets/queries/k8s/use_service_account_credentials_not_set_to_true/test/negative1.yaml, assets/queries/k8s/use_service_account_credentials_not_set_to_true/test/negative2.yaml, assets/queries/k8s/use_service_account_credentials_not_set_to_true/test/positive1.yaml, assets/queries/k8s/use_service_account_credentials_not_set_to_true/test/positive2.yaml, assets/queries/k8s/use_service_account_credentials_not_set_to_true/test/positive_expected_result.json, docs/getting-started.md, docs/release_checklist.md, go.mod, go.sum
- fixed k8s queries
- updated release documentation
- added Password and Secrets note
=> fix(samples): k8s queries

assets/queries/k8s/client_certificate_authentication_not_setup_properly/metadata.json, assets/queries/k8s/client_certificate_authentication_not_setup_properly/query.rego, assets/queries/k8s/client_certificate_authentication_not_setup_properly/test/negative6.yaml, assets/queries/k8s/client_certificate_authentication_not_setup_properly/test/negative7.yaml, assets/queries/k8s/client_certificate_authentication_not_setup_properly/test/positive_expected_result.json
- Add support to the .crt file in Client Certificate Authentication Not Setup Properly query
=> update(query): Client Certificate Authentication Not Setup Properly

internal/console/helpers/helpers.go, internal/console/pre_scan.go
Closes #5364
- Look at `/sys/fs/cgroup/cpu.max` file if `/sys/fs/cgroup/cpu/cpu.cfs_quota_us` file does not exists
=> fix(cpu): fix number cpus macos

pkg/detector/helm/helm_detect.go, pkg/detector/helm/helm_detect_test.go, pkg/engine/vulnerability_builder.go
Signed-off-by: João Reigota <joao.Reigota@checkmarx.com>
=> fix(helm): fixed helm filepath bug introduced by resolver

assets/queries/dockerfile/multiple_run_add_copy_instructions_listed/metadata.json
- fixed incorrect Dockerfile metadata
=> fix(query): fixed incorrect Dockerfile metadata

Dockerfile
- added 256 color to KICS Dockerfile
=> update(dockerfile): added 256 color

e2e/fixtures/schemas/result-asff.json, e2e/fixtures/schemas/result-cyclonedx.json, e2e/fixtures/schemas/result-junit.json, pkg/report/model/asff.go, pkg/report/model/asff_test.go, pkg/report/model/cyclonedx.go, pkg/report/model/cyclonedx_test.go, pkg/report/model/junit.go, pkg/report/model/junit_test.go
Closes #5389
- improved report message for JUnit, Cyclonedx, and ASFF
=> update(report): improved report message

go.mod, go.sum, pkg/engine/provider/filesystem.go, pkg/engine/provider/filesystem_test.go
Closes #5369
- Added double start support with third package library
=> feat(filesystem): double star support to exclude folders

assets/queries/ansible/azure/role_definition_allows_custom_role_creation/metadata.json, assets/queries/ansible/azure/role_definition_allows_custom_role_creation/query.rego, assets/queries/ansible/azure/role_definition_allows_custom_role_creation/test/negative.yaml, assets/queries/ansible/azure/role_definition_allows_custom_role_creation/test/positive1.yaml, assets/queries/ansible/azure/role_definition_allows_custom_role_creation/test/positive2.yaml, assets/queries/ansible/azure/role_definition_allows_custom_role_creation/test/positive_expected_result.json
- added "Role Definition Allows Custom Role Creation" query for Ansible
=> feat(query): added "Role Definition Allows Custom Role Creation" query for Ansible

assets/libraries/openapi.rego, assets/queries/openAPI/2.0/undefined_security_scope_global_security/query.rego, assets/queries/openAPI/2.0/undefined_security_scope_security_operations/query.rego, assets/queries/openAPI/2.0/undefined_security_scope_security_operations/test/positive_expected_result.json, assets/queries/openAPI/3.0/undefined_security_scope_global_security/query.rego, assets/queries/openAPI/3.0/undefined_security_scope_global_security/test/positive_expected_result.json, assets/queries/openAPI/3.0/undefined_security_scope_security_operations/query.rego, assets/queries/openAPI/3.0/undefined_security_scope_security_operations/test/positive_expected_result.json
- fixed function `check_schemes` of OpenAPI lib (in some projects, it was returning the error 'functions must not produce multiple outputs for same inputs')
=> fix(queries): fixed function check_schemes of OpenAPI lib

pkg/engine/provider/filesystem.go
Closes #5412
- Added mutex to lock read and write on map
=> fix(filesystem): added mutex to lock read and write on map

pkg/analyzer/analyzer.go
=> fixing integrations branch

.github/workflows/sync_major_release.yaml
- cancel previous runs in sync_major_release workflow
=> update(workflow): cancel previous runs in sync_major_release workflow

assets/queries/terraform/aws/resource_not_using_tags/metadata.json, assets/queries/terraform/aws/resource_not_using_tags/query.rego, e2e/fixtures/E2E_CLI_033_RESULT.json
- improved "Resource Not Using Tags" description
=> update(query): improved "Resource Not Using Tags" description

assets/queries/terraform/aws/api_gateway_without_waf/query.rego, assets/queries/terraform/aws/api_gateway_without_waf/test/negative2.tf
=> Add wafv2 to query incl. negative test

pkg/engine/provider/filesystem.go
Closes #5512
-ignores any broken symlink and continues with the scan 
Future changes are better taken into consideration: 
- I would add a flag to let the customer decide which mode he would like to run "fail open"/"fail close" - meaning fail/stop the scan on any broken/damaged file/dir or continue with the scan and add the list of the damaged files to the output.
=> fix(scan behavior): ignore broken synlink

assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/query.rego, assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/test/negative3.tf, assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/test/negative4.tf, assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/test/positive5.tf, assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/test/positive6.tf, assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/test/positive_expected_result.json
Closes #5547
- Add check for ALB in Auto Scaling Group With No Associated ELB for Terraform AWS
=> fix(query): add check for ALB use in Terraform AWS Security Query

internal/console/remediate.go, pkg/parser/parser.go, pkg/parser/terraform/variables.go, pkg/remediation/remediation.go, pkg/remediation/scan.go, pkg/remediation/utils.go
=> fix(kics_ar): reverting go routine

assets/libraries/cloudformation.rego, assets/libraries/terraform.rego, assets/queries/cloudFormation/aws_bom/efs/query.rego, assets/queries/cloudFormation/aws_bom/s3_bucket/query.rego, assets/queries/terraform/aws_bom/s3_bucket/query.rego
- change AWS BOM resource_accessibility output values from `hasPolicy`  to `public` or `hasPolicy` once the presence of a policy is detected.
=> fix(bom): change AWS BOM resource_accessibility output values

assets/libraries/common.rego, assets/libraries/crossplane.rego, assets/libraries/pulumi.rego, assets/queries/crossplane/aws/cloudfront_logging_disabled/query.rego, assets/queries/crossplane/aws/cloudfront_without_minimum_protocol_tls_1.2/query.rego, assets/queries/crossplane/aws/cloudfront_without_waf/query.rego, assets/queries/crossplane/aws/cloudwatch_without_retention_period_specified/query.rego, assets/queries/crossplane/aws/db_instance_storage_not_encrypted/query.rego, assets/queries/crossplane/aws/db_security_group_has_public_interface/query.rego, assets/queries/crossplane/aws/efs_not_encrypted/query.rego, assets/queries/crossplane/aws/efs_without_kms/query.rego, assets/queries/crossplane/aws/elb_using_weak_ciphers/query.rego, assets/queries/crossplane/aws/neptune_database_cluster_encryption_disabled/query.rego, assets/queries/crossplane/aws/sqs_with_sse_disabled/query.rego, assets/queries/crossplane/azure/aks_rbac_disabled/query.rego, assets/queries/crossplane/azure/redis_cache_allows_non_ssl_connections/query.rego, assets/queries/crossplane/gcp/cloud_storage_bucket_logging_not_enabled/query.rego, assets/queries/crossplane/gcp/google_container_node_pool_auto_repair_disabled/query.rego, assets/queries/pulumi/gcp/cloud_storage_bucket_logging_not_enabled/metadata.json, assets/queries/pulumi/gcp/cloud_storage_bucket_logging_not_enabled/query.rego, assets/queries/pulumi/gcp/cloud_storage_bucket_logging_not_enabled/test/negative.yaml, assets/queries/pulumi/gcp/cloud_storage_bucket_logging_not_enabled/test/positive.yaml, assets/queries/pulumi/gcp/cloud_storage_bucket_logging_not_enabled/test/positive_expected_result.json, assets/queries/pulumi/gcp/google_compute_ssl_policy_weak_cipher_in_use/metadata.json, assets/queries/pulumi/gcp/google_compute_ssl_policy_weak_cipher_in_use/query.rego, assets/queries/pulumi/gcp/google_compute_ssl_policy_weak_cipher_in_use/test/negative.yaml, assets/queries/pulumi/gcp/google_compute_ssl_policy_weak_cipher_in_use/test/positive.yaml, assets/queries/pulumi/gcp/google_compute_ssl_policy_weak_cipher_in_use/test/positive_expected_result.json, test/main_test.go
- Add Pulumi GCP Security Queries
=> queries(pulumi): add pulumi gcp security queries

assets/queries/pulumi/kubernetes/missing_app_armor_config/metadata.json, assets/queries/pulumi/kubernetes/missing_app_armor_config/query.rego, assets/queries/pulumi/kubernetes/missing_app_armor_config/test/negative.yaml, assets/queries/pulumi/kubernetes/missing_app_armor_config/test/positive.yaml, assets/queries/pulumi/kubernetes/missing_app_armor_config/test/positive_expected_result.json, assets/queries/pulumi/kubernetes/psp_set_to_privileged/metadata.json, assets/queries/pulumi/kubernetes/psp_set_to_privileged/query.rego, assets/queries/pulumi/kubernetes/psp_set_to_privileged/test/negative.yaml, assets/queries/pulumi/kubernetes/psp_set_to_privileged/test/positive.yaml, assets/queries/pulumi/kubernetes/psp_set_to_privileged/test/positive_expected_result.json, test/main_test.go
- Add Pulumi Kubernetes Security Queries
=> queries(pulumi): add pulumi kubernetes security queries

assets/queries/dockerfile/update_instruction_alone/query.rego, assets/queries/dockerfile/update_instruction_alone/test/negative2.dockerfile
Closes #5703 
- fix update_instruction_alone to check multiple occurrences of update/install in the command
=> fix(query): update_instruction_alone

assets/queries/terraform/azure/app_service_without_latest_python_version/metadata.json, assets/queries/terraform/azure/app_service_without_latest_python_version/query.rego, assets/queries/terraform/azure/app_service_without_latest_python_version/test/negative1.tf, assets/queries/terraform/azure/app_service_without_latest_python_version/test/negative2.tf, assets/queries/terraform/azure/app_service_without_latest_python_version/test/negative3.tf, assets/queries/terraform/azure/app_service_without_latest_python_version/test/negative4.tf, assets/queries/terraform/azure/app_service_without_latest_python_version/test/positive1.tf, assets/queries/terraform/azure/app_service_without_latest_python_version/test/positive2.tf, assets/queries/terraform/azure/app_service_without_latest_python_version/test/positive3.tf, assets/queries/terraform/azure/app_service_without_latest_python_version/test/positive_expected_result.json
- Query added to check if App Service is running with the latest Python version.
=> feat(query): added App Service Without Latest Python Version query for Terraform

assets/queries/k8s/ensure_administrative_boundaries_between_resources/query.rego, pkg/kics/sink.go
=> fixing missing results from 5680

pkg/resolver/file/file.go
=> fix json resolver

windows.dockerfile
- create Docker Image Based in Windows
=> feat(image): add windows image

.github/scripts/samples-linters/.tflint.hcl, .github/workflows/validate-tf-samples.yml
=> fix(github_action): add tflint config file

pkg/resolver/helm/resolver.go
- renderHelm output paths update with the root folder name
=> K8s files are not being considered in the scan

latest/kics_auto_remediation/index.html
=> docs(): fix remediate

docs/kics_auto_remediation.md
=> docs(remediate): update remediate docs

docs/BADGE.md, docs/configuration-file.md, docs/dockerhub.md, docs/getting-started.md, docs/running-kics.md
- Docker Hub page information update
=> docker hub docs information update

.github/scripts/metrics/get_metrics.py
- fix bug in get metrics script
=> fix(bug): bug in get metrics script

assets/libraries/common.json
Updating assets/libraries/common.json software versions
Triggered by SHA: _55edcdf5985b3323e6cb51f2f2bef21a12088905_
=> bump: updating software versions

assets/queries/dockerfile/workdir_path_not_absolute/query.rego, assets/queries/dockerfile/workdir_path_not_absolute/test/negative.dockerfile
- fix dockerfile security query regex
=> fix(query): fix dockerfile security query regex

assets/queries/cloudFormation/aws/msk_broker_is_publicly_accessible/metadata.json, assets/queries/cloudFormation/aws/msk_broker_is_publicly_accessible/query.rego, assets/queries/cloudFormation/aws/msk_broker_is_publicly_accessible/test/negative1.yaml, assets/queries/cloudFormation/aws/msk_broker_is_publicly_accessible/test/negative2.json, assets/queries/cloudFormation/aws/msk_broker_is_publicly_accessible/test/positive1.yaml, assets/queries/cloudFormation/aws/msk_broker_is_publicly_accessible/test/positive2.json, assets/queries/cloudFormation/aws/msk_broker_is_publicly_accessible/test/positive_expected_result.json, assets/queries/cloudFormation/aws_bom/msk/query.rego, assets/queries/cloudFormation/aws_bom/msk/test/positive1.yaml, assets/queries/terraform/aws/msk_broker_is_publicly_accessible/metadata.json, assets/queries/terraform/aws/msk_broker_is_publicly_accessible/query.rego, assets/queries/terraform/aws/msk_broker_is_publicly_accessible/test/negative1.tf, assets/queries/terraform/aws/msk_broker_is_publicly_accessible/test/negative2.tf, assets/queries/terraform/aws/msk_broker_is_publicly_accessible/test/positive1.tf, assets/queries/terraform/aws/msk_broker_is_publicly_accessible/test/positive_expected_result.json, assets/queries/terraform/aws_bom/msk/query.rego, assets/queries/terraform/aws_bom/msk/test/positive1.tf
- added 'MSK Broker Is Publicly Accessible' for CloudFormation and Terraform
- Updated AWS MSK BOM
=> feat(query): added 'MSK Broker Is Publicly Accessible' for CloudFormation and Terraform

docs/integrations_ghactions.md
Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>
- replace incorrect GH action name with `Checkmarx/kics-github-action@v1.5`
=> update(documentation): correct the GH action name

docs/community.md
- Update community link for contribution with the correct value
=> fix community link for contribution

README.md, docs/CONTRIBUTING.md, docs/community.md
- Add information about community meetings
=> Add community meetings schedule & link

assets/queries/terraform/aws/memcached_disabled/test/positive_expected_result.json, assets/queries/terraform/aws/redis_disabled/metadata.json, assets/queries/terraform/aws/redis_disabled/query.rego, assets/queries/terraform/aws/redis_disabled/test/negative.tf, assets/queries/terraform/aws/redis_disabled/test/positive.tf, assets/queries/terraform/aws/redis_disabled/test/positive_expected_result.json
Closes #5855
- readjusted "Memcached Disabled" to "Redis Disabled" (the query approach was "wrong")
=> fix(query): readjusted "Memcached Disabled" to "Redis Disabled"

.github/scripts/server-mock/package-lock.json
=> bump(deps): express dependencies

assets/queries/common/passwords_and_secrets/regex_rules.json, assets/queries/common/passwords_and_secrets/test/positive42.tf, assets/queries/common/passwords_and_secrets/test/positive_expected_result.json
- improved regex of "Asymmetric private key"
=> fix(query): improved regex of "Asymmetric private key"

docs/certifications-cis.md, docs/certifications.md
- Certifications documentation is updated with CIS Kubernetes Benchmark
=> update certification documentation

docs/certifications-cis.md, docs/community.md
=> docs update

docs/community.md
Date changed due to a holiday for most team members
=> Update December community meeting

.github/workflows/kics-gh-action.yaml
- Updated KICS GH Action to comment the results summary
=> update(kics-gh): updated KICS GH Action

assets/queries/cloudFormation/aws/sqs_with_sse_disabled/query.rego, assets/queries/cloudFormation/aws/sqs_with_sse_disabled/test/negative1.yaml, assets/queries/cloudFormation/aws/sqs_with_sse_disabled/test/negative2.json, assets/queries/cloudFormation/aws/sqs_with_sse_disabled/test/positive1.yaml, assets/queries/cloudFormation/aws/sqs_with_sse_disabled/test/positive2.json, assets/queries/cloudFormation/aws/sqs_with_sse_disabled/test/positive_expected_result.json
- fix false positive in sqs with sse disabled for aws cloudformation
=> fix(query): fix false positive in sqs with sse disabled for aws cloudformation

assets/queries/terraform/gcp_bom/dataflow/metadata.json, assets/queries/terraform/gcp_bom/dataflow/query.rego, assets/queries/terraform/gcp_bom/dataflow/test/negative.tf, assets/queries/terraform/gcp_bom/dataflow/test/positive.tf, assets/queries/terraform/gcp_bom/dataflow/test/positive_expected_result.json
- add gcp bill of materials for dataflow job in terraform
=> feat(bom): add gcp bill of materials for dataflow job in terraform

assets/libraries/terraform.rego, assets/queries/terraform/gcp_bom/redis/metadata.json, assets/queries/terraform/gcp_bom/redis/query.rego, assets/queries/terraform/gcp_bom/redis/test/negative.tf, assets/queries/terraform/gcp_bom/redis/test/positive.tf, assets/queries/terraform/gcp_bom/redis/test/positive_expected_result.json
- add gcp redis bill of matterials support for terraform
=> feat(bom): add gcp redis bill of matterials support for terraform

assets/queries/terraform/gcp_bom/fi/metadata.json, assets/queries/terraform/gcp_bom/fi/query.rego, assets/queries/terraform/gcp_bom/fi/test/negative.tf, assets/queries/terraform/gcp_bom/fi/test/positive.tf, assets/queries/terraform/gcp_bom/fi/test/positive_expected_result.json
- add gcp filestore instance bill of materials for terraform
=> feat(bom): add gcp filestore instance bill of materials for terraform

assets/queries/googleDeploymentManager/gcp_bom/sb/metadata.json, assets/queries/googleDeploymentManager/gcp_bom/sb/query.rego, assets/queries/googleDeploymentManager/gcp_bom/sb/test/negative.yaml, assets/queries/googleDeploymentManager/gcp_bom/sb/test/positive.yaml, assets/queries/googleDeploymentManager/gcp_bom/sb/test/positive_expected_result.json, assets/queries/terraform/gcp_bom/sb/metadata.json, assets/queries/terraform/gcp_bom/sb/query.rego, assets/queries/terraform/gcp_bom/sb/test/negative.tf, assets/queries/terraform/gcp_bom/sb/test/positive.tf, assets/queries/terraform/gcp_bom/sb/test/positive_expected_result.json
- add bill of materials for gcp storage bucket
=> feat(bom): add bill of materials for gcp storage bucket

go.mod, go.sum
=> bump(deps)

docs/community.md
=> Update community meetings

docs/community.md
- January meeting removed from list
=> community dates update

e2e/testcases/e2e-cli-044_scan_exclude-severities.go
Closes #6109
- update e2e test 44 incorrect description
=> fix(e2e): update e2e test 44 description

pkg/parser/terraform/converter/default.go
- reducing  sentry messages sent by KICS
=> reducing  sentry messages

assets/queries/azureResourceManager/website_with_http20enabled_disabled/query.rego, assets/queries/azureResourceManager/website_with_http20enabled_disabled/test/positive_expected_result.json
- fix missing results
- fix same line detection
- change searchline in Website with 'Http20Enabled' Disabled ARM security Query
=> fix(query): fix missing results and same line detection in arm query

assets/queries/serverlessFW/serverless_function_environment_variables_not_encrypted/query.rego, assets/queries/serverlessFW/serverless_function_environment_variables_not_encrypted/test/negative2.yml
Closes #6135
- fix fp in Serverless Function Environment Variables Not Encrypted
=> fix(query): fix false positive in serverles fw security query

pkg/resolver/file/file.go, pkg/resolver/file/file_test.go, test/fixtures/unresolved_serverless/eventRouterHandler.yml, test/fixtures/unresolved_serverless/serverless.yml
- add resolver capabilities for reference like '${file(someFile.yml)}'
=> feature(resolver): add resolver for serverless file reference

assets/queries/ansible/aws/launch_configuration_is_not_encrypted/metadata.json, assets/queries/ansible/aws/viewer_protocol_policy_allows_http/metadata.json, assets/queries/ansible/aws/viewer_protocol_policy_allows_http/test/positive_expected_result.json, assets/queries/k8s/hpa_targets_invalid_object/test/negative2.yaml, assets/queries/terraform/aws/launch_configuration_is_not_encrypted/metadata.json, assets/queries/terraform/kubernetes/hpa_targets_invalid_object/metadata.json
fix and align queries
Queries:
Launch Configuration Is Not Encrypted
Cloudfront Viewer Protocol Policy Allows HTTP
HPA Targets Invalid Object
=> fix(query): fix and align queries

.github/scripts/docs-generator/templates/platform_template.md
=> fix(docs): fix docs gh action platform template

docs/queries/ansible-queries.md, docs/queries/cloudformation-queries.md, docs/queries/crossplane-queries.md, docs/queries/googledeploymentmanager-queries.md, docs/queries/openapi-queries.md, docs/queries/pulumi-queries.md, docs/queries/terraform-queries.md
Updating queries' documentation.
Triggered by SHA: _2d613a54df985c32f1b1b3cbd767e2fae8821a6b_
=> docs(queries): update queries catalog

docs/creating-queries.md, docs/flags.md, docs/queries/ansible-queries.md, docs/queries/cloudformation-queries.md, docs/queries/crossplane-queries.md, docs/queries/googledeploymentmanager-queries.md, docs/queries/openapi-queries.md, docs/queries/pulumi-queries.md, docs/queries/terraform-queries.md
=> Fix spelling of "below" in docs

assets/libraries/common.json, assets/libraries/common.rego, assets/queries/terraform/gcp/outdated_gke_version/metadata.json, assets/queries/terraform/gcp/outdated_gke_version/query.rego, assets/queries/terraform/gcp/outdated_gke_version/test/negative.tf, assets/queries/terraform/gcp/outdated_gke_version/test/positive.tf, assets/queries/terraform/gcp/outdated_gke_version/test/positive_expected_result.json
- add outdated gke version security query
- add gke entry in software version list on common.data
=> feat(query): add outdated gke version terraform gcp security query

Dockerfile
Closes #6184
- terraform version from 1.2.3 to 1.3.9
=> terraform version update

.github/workflows/kics-gh-action.yaml
- KICS gh action updated version
=> kics github action version update

assets/queries/cloudFormation/aws/s3_bucket_without_ssl_in_write_actions/query.rego, assets/queries/cloudFormation/aws/s3_bucket_without_ssl_in_write_actions/test/negative7.yaml, assets/queries/cloudFormation/aws/s3_bucket_without_ssl_in_write_actions/test/positive2.yaml, assets/queries/cloudFormation/aws/s3_bucket_without_ssl_in_write_actions/test/positive3.yaml, assets/queries/cloudFormation/aws/s3_bucket_without_ssl_in_write_actions/test/positive6.json, assets/queries/cloudFormation/aws/s3_bucket_without_ssl_in_write_actions/test/positive_expected_result.json
- Effect 'Allow' conditions added
- Tests added and updated
=> fix(query): Effect 'Allow' conditions added

assets/queries/openAPI/general/response_code_missing/query.rego, test/queries_content_test.go
- Added searchValue key in Response Code Missing query
- Added Response Code Missing query to searchValueAllowedQueriesPath
=> fix(query): Added SearchValue to diferentiate missing response codes

assets/queries/common/passwords_and_secrets/regex_rules.json, assets/queries/common/passwords_and_secrets/test/negative54.tf, assets/queries/common/passwords_and_secrets/test/positive42.tf, assets/queries/common/passwords_and_secrets/test/positive_expected_result.json
- Added regex to catch access_key values
- Added positive (with expected result)
- Added negative test
=> fix(query): add rule for generic access_key 

docs/results.md
=> Deprecated doc update

.github/workflows/release-docker-github-actions.yaml
- KICS GitHub action tag update
=> gh action tag update

docs/css/custom.css, mkdocs.yml
- Changed Scheme name in mkdocs
- Changed Scheme name in Custom.CSS
=> bug(docs): Changed Light Scheme Name

docs/secrets.md
=> docs(secrets): re add entropy info

assets/queries/pulumi/aws/elasticsearch_logs_disabled/metadata.json, assets/queries/pulumi/aws/elasticsearch_logs_disabled/query.rego, assets/queries/pulumi/aws/elasticsearch_logs_disabled/test/negative1.yaml, assets/queries/pulumi/aws/elasticsearch_logs_disabled/test/positive1.yaml, assets/queries/pulumi/aws/elasticsearch_logs_disabled/test/positive2.yaml, assets/queries/pulumi/aws/elasticsearch_logs_disabled/test/positive3.yaml, assets/queries/pulumi/aws/elasticsearch_logs_disabled/test/positive_expected_result.json
feat(query): Elasticsearch Log Disabled
- Added query and metadata for Pulumi
- Added tests
- Added positive_expected_result
=> feat(query): Elasticsearch Log Disabled

assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/metadata.json, assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/query.rego, assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/negative1.yaml, assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/negative2.json, assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/negative3.yaml, assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/positive1.yaml, assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/positive2.yaml, assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/positive3.json, assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/positive4.json, assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/positive5.json, assets/queries/cloudFormation/aws/elasticsearch_logs_disabled/test/positive_expected_result.json
- Added query and metadata for CloudFormation
- Added tests
- Added positive_expected_result
- Removed old query
=> feat(query): Elasticsearch with HTTPS disabled for CloudFormation

.github/scripts/extract-kics-info/extract-info.py
- Add condition to exclude metadata file from template query when creating extracted-info.zip
=> Fix(Extracted-Info) - Fix metadata.json from template being used

.github/scripts/extract-kics-info/extract-info.py
- ExtractedInfo was skipping queries with "." and "test" in the name, upgraded the creation process to not exclude those
=> fix missing queries

assets/queries/common/passwords_and_secrets/regex_rules.json, assets/queries/common/passwords_and_secrets/test/positive46.yaml, assets/queries/common/passwords_and_secrets/test/positive_expected_result.json, pkg/detector/docker/docker_detect_test.go, pkg/detector/helper.go, pkg/detector/helper_test.go
- update regex allow rule
- test added
=> fix(regex): update regex allow rule

.github/workflows/add-issues-labels.yaml, .github/workflows/validate-pr-title.yaml
- Update the validate PR workflow to prevent injection vulnerability
It should be a quick fix for you.
**Reference:**
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
=> fix(workflow): fix Pwn Request Vulnerability

.github/workflows/check-go-coverage.yaml, internal/console/kics_test.go
- New GitHub workflow is added to check if the PR's Go code have at least 80% of coverage. 
=> feat(workflow): new github workflow that checks the PR's Go coverage

docs/integrations_ghactions.md
- Integration with GitHub Actions documentation update
=> update(doc): kics github action version update

.github/workflows/check-apache-license.yaml, .github/workflows/validate-issues.yaml, .github/workflows/validate-prs.yaml
- Added sha full-length commit to third-party actions.
=> fix(workflows): fixed action's pin

pkg/analyzer/analyzer.go
- comments related to files extensions updated
=> update(comments): comments related to files extensions updated

assets/queries/dockerCompose/host_namespace_is_shared/query.rego
=> fix(query): dockercompose Host Namespace is Shared

docs/integrations.md, docs/integrations_aws_cdk.md, mkdocs.yml
=> update(doc): adding aws cdk integration

.github/scripts/docs-generator/query-page-generator/query-page-generator.py
=> docs(queries): fix typo

.github/scripts/queries-validator/metadata-schema.json, assets/queries/ansible/aws/alb_listening_on_http/metadata.json
- queries validator schema updated to accept 'experimental' field
=> update(metadata): queries validator schema updated

README.md, docs/index.md
- remove databricks logo from official support since it is already added into beta features
- information regarding how to run experimental queries added into readme and index page
=> update(readme): add information regarding beta features

.github/scripts/metrics/get_metrics.py
- add buildah and cicd to queries count
=> fix(metrics): add buildah and cicd to queries count

.github/workflows/go-ci-metrics.yaml
- go-ci-metrics.yaml master to v4
=> update(action): go-ci-metrics.yaml master to v4

.github/workflows/update_software_versions.yml
Closes https://github.com/Checkmarx/kics/security/dependabot/48
- version upgrade
=> update(action): tj-actions/verify-changed-files version upgrade

README.md
Based on request by Jean-Yves CAMIER (@jycamier)
=> docs(community): add Bedrock Streaming to users list

e2e/testcases/e2e-cli-069_ignore_experimental_query.go, e2e/testcases/e2e-cli-070_not_ignore_experimental_query.go
- sort paths related to the e2e
=> fix(test): sort paths related to the e2e

docs/running-kics.md
- update info how to scan zip files
=> update(docs): update info how to scan zip files

README.md
- all rights reserved year updated
=> update(readme): all rights reserved year updated

README.md
=> docs(community): add Keptn Lifecycle Toolkit

assets/queries/ansible/aws/s3_bucket_sse_disabled/metadata.json, assets/queries/cloudFormation/aws/s3_bucket_sse_disabled/metadata.json, assets/queries/terraform/aws/s3_bucket_sse_disabled/metadata.json
- description texts are updated
=> update(metadata): description texts are updated

go.mod
=> update(buildkit): buildkit upgrade to v0.12.5

.github/scripts/coverage/get-coverage.py, .github/workflows/check-go-coverage.yaml
=> update(coverage): go coverage metrics update

README.md
=> docs(community): add blog post by Firefly

docs/platforms.md
=> update(docs): update dockerfiles docs

docs/index.md, docs/roadmap.md, internal/console/kics_test.go
=> update(docs): v2.0.0 docs update

.github/workflows/kics-gh-action.yaml
- using kics gh action new version
=> update(ghaction): using kics gh action new version

assets/queries/ansible/azure/default_azure_storage_account_network_access_is_too_permissive/query.rego, assets/queries/azureResourceManager/default_azure_storage_account_network_access_is_too_permissive/query.rego, pkg/scan/scan.go
- fixed typo in two queries
- removed unreachable code in scan
=> fix(query): fix typos

assets/queries/azureResourceManager/storage_blob_service_container_with_public_access/metadata.json, docs/queries/azureresourcemanager-queries/azure/a0ab985d-660b-41f7-ac81-70957ee8e627.md
- fix typo on storage blob service container query description
=> fix(query): fix typo on storage blob service container query description

assets/queries/terraform/aws/http_port_open/query.rego
=> fix(query): removed redundant import

Dockerfile, assets/queries/dockerfile/using_platform_with_from/metadata.json
Closes #
- Remove user root 
- Add platform to command FROM
- Change GIT image tag from 'latest' to 'latest-root'
=> fix(dockerfile): remove user root and add platform

assets/queries/azureResourceManager/default_azure_storage_account_network_access_is_too_permissive/query.rego, assets/queries/azureResourceManager/default_azure_storage_account_network_access_is_too_permissive/test/negative1.json, assets/queries/azureResourceManager/default_azure_storage_account_network_access_is_too_permissive/test/negative2.json, assets/queries/azureResourceManager/default_azure_storage_account_network_access_is_too_permissive/test/positive2.json, assets/queries/azureResourceManager/default_azure_storage_account_network_access_is_too_permissive/test/positive3.json
- Test ARM files were being parsed as Kubernetes files
- Fixed search line construction in the query
=> fix(query): fixed network access too permissive query and tests

assets/queries/azureResourceManager/storage_logging_for_read_write_delete_requests_disabled/query.rego, assets/queries/azureResourceManager/storage_logging_for_read_write_delete_requests_disabled/test/positive_expected_result.json
- Changed storage_logging_for_read_write_delete_requests_disabled arm query to improve the messages and the line detection
=> fix(query): fix rwd arm query

.github/CODEOWNERS
- CODEOWNERS added to the repo configurations
=> update(repo): create CODEOWNERS

docs/roadmap.md
=> update(roadmap): roadmap is updated

.github/pull_request_template.md
- add Reason for Proposed Changes to the pull request template;
=> update(prtemplate): update pull request template

.github/CODEOWNERS, .github/workflows/validate-issues.yaml, .github/workflows/validate-prs.yaml
=> update(codeowners): update CODEOWNERS

.github/workflows/kics-gh-action.yaml
=> update(ghaction): update kics-gh-action.yaml

assets/queries/terraform/tencentcloud/cvm_instance_using_default_security_group/metadata.json, assets/queries/terraform/tencentcloud/cvm_instance_using_default_security_group/test/positive_expected_result.json
- change query name capitalization to maintain the same logic present on KICS
=> update(query): change query name to maintain the same logic

assets/queries/terraform/tencentcloud/cvm_instance_using_user_data/test/positive3.tf, assets/queries/terraform/tencentcloud/cvm_instance_using_user_data/test/positive4.tf, assets/queries/terraform/tencentcloud/cvm_instance_using_user_data/test/positive_expected_result.json
Please help review the PR
Thanks
=> fix(query): add positive expected results for "secretId" and "secretKey" for Tencentcloud

Dockerfile, docker/Dockerfile.debian, go.mod
Closes #
- sec-checks are failing
- update go version and golden images
=> update(dockerfile): update go version and golden images

.github/workflows/kics-gh-action.yaml
- update github action version
=> update(githubaction): update github action version

Makefile
- support Podman instructions on Makefile;
- add Podman commands to Makefile;
=> build(makefile): update makefile to add podman commands

README.md
- Wrong date in README.md file.
- Correct year (2025).
=> update(readme): fix date.

Dockerfile
- Fix vulnerabilities
- Update docker images to latest versions
=> update(deps): update docker images to latest versions

pkg/resolver/file/file.go, pkg/resolver/file/file_test.go, test/fixtures/direct_cyclic_references/sample.json, test/fixtures/direct_cyclic_references/sample.yaml, test/fixtures/direct_cyclic_references/sample_win.json, test/fixtures/direct_cyclic_references/sample_win.yaml
Reason for Proposed Changes
- undetected direct circular references
Proposed Changes:
- fix detection for direct circular references with relative path
=> fix(engine): direct circular dependency is causing resource exhaustion

.github/workflows/sec-checks.yaml, Dockerfile, docker/Dockerfile.debian, docker/Dockerfile.ubi8, go.mod
Closes #
- Security vulnerabilities
- Upgrade GOv1.24.4
=> update(deps): fix vulnerabilities and upgrade to GOv1.24.4

.github/workflows/update-docs-release.yaml
Closes #
- adds git pull to docs release action
=> fix(githubaction): adds git pull to docs release action
