assets/queries/terraform/aws/aws_vpc_flow_logs_enabled/metadata.json
assets/queries/terraform/aws/aws_vpc_flow_logs_enabled/query.rego
assets/queries/terraform/aws/aws_vpc_flow_logs_enabled/test/negative.tf
assets/queries/terraform/aws/aws_vpc_flow_logs_enabled/test/positive.tf
assets/queries/terraform/aws/aws_vpc_flow_logs_enabled/test/positive_expected_result.json

Sees if the id of the flow logs is the same as the vpc, if they are VPC, flow logs are Enabled #462 .

Add VPC Flow Logs are not Enabled query for Terraform #462

---

assets/queries/terraform/aws/rds_cluster_storage_not_encrypted/metadata.json
assets/queries/terraform/aws/rds_cluster_storage_not_encrypted/query.rego
assets/queries/terraform/aws/rds_cluster_storage_not_encrypted/test/negative.tf
assets/queries/terraform/aws/rds_cluster_storage_not_encrypted/test/positive.tf
assets/queries/terraform/aws/rds_cluster_storage_not_encrypted/test/positive_expected_result.json

Closes #345 
Added new query RDS Cluster Storage Not Encrypted for Terraform.
Check if RDS Cluster Storage isn't encrypted. Happens when 'storage_encrypted' field is false or undefined

Add RDS Cluster Storage Not Encrypted Terraform

---

assets/queries/k8s/shared_host_network_namespace/metadata.json
assets/queries/k8s/shared_host_network_namespace/query.rego
assets/queries/k8s/shared_host_network_namespace/test/negative.yaml
assets/queries/k8s/shared_host_network_namespace/test/positive.yaml
assets/queries/k8s/shared_host_network_namespace/test/positive_expected_result.json

Closes #476 
This query detects if containers share the host network namespace.
It checks if, in the 'spec', 'hostNetwork' field is true (default is false).

Add shared_host_network_namespace query for Kubernetes #476

---

assets/queries/terraform/aws/redis_not_compliant/metadata.json
assets/queries/terraform/aws/redis_not_compliant/query.rego
assets/queries/terraform/aws/redis_not_compliant/test/negative.tf
assets/queries/terraform/aws/redis_not_compliant/test/positive.tf
assets/queries/terraform/aws/redis_not_compliant/test/positive_expected_result.json

Closes #475 
Checks if the Redis version is compliant with the necessary AWS PCI DSS requirements

Add redis_not_compliant query Closes #475

---

assets/queries/terraform/aws/kms_key_no_deletion_window/metadata.json
assets/queries/terraform/aws/kms_key_no_deletion_window/query.rego
assets/queries/terraform/aws/kms_key_no_deletion_window/test/negative.tf
assets/queries/terraform/aws/kms_key_no_deletion_window/test/positive.tf
assets/queries/terraform/aws/kms_key_no_deletion_window/test/positive_expected_result.json
assets/queries/terraform/kubernetes_pod/container_allow_privilege_escalation_is_true/metadata.json
assets/queries/terraform/kubernetes_pod/container_allow_privilege_escalation_is_true/test/positive_expected_result.json

AWS KMS Key should have a valid deletion window and this value must be between 7 and 30 days.
So, I thought in three cases:
- Attribute 'deletion_window_in_days' is undefined
- Attribute 'deletion_window_in_days' is set but greater than 30
- Attribute 'deletion_window_in_days' is set but smaller than 7
Closes #292 (This issue was already closed because of the repository transition but the query was not validated)
P.S. I changed two files of container_allow_privilege_escalation_is_true query because I detected an orthographic error

Add kms_key_no_deletion_window Closes #292

---

assets/queries/k8s/permissive_access_to_create_pods/metadata.json
assets/queries/k8s/permissive_access_to_create_pods/query.rego
assets/queries/k8s/permissive_access_to_create_pods/test/negative.yaml
assets/queries/k8s/permissive_access_to_create_pods/test/positive.yaml
assets/queries/k8s/permissive_access_to_create_pods/test/positive_expected_result.json
pkg/engine/vulnerability_builder.go

Created query Permissive Access To Create Pods.
The permission to create pods in a cluster should be restricted because it allows privilege escalation.
Closes #649

Added query permissive_access_to_create_pods

---

assets/queries/k8s/non_kube_system_pod_with_host_mount/metadata.json
assets/queries/k8s/non_kube_system_pod_with_host_mount/query.rego
assets/queries/k8s/non_kube_system_pod_with_host_mount/test/negative.yaml
assets/queries/k8s/non_kube_system_pod_with_host_mount/test/positive.yaml
assets/queries/k8s/non_kube_system_pod_with_host_mount/test/positive_expected_result.json

Ensure pods outside of kube-system do not have access to node volume (Deployments, DaemonSets and other templated types too)
Closes #622

Add non_kube_system_pod_with_host_mount query for Kubernetes

---

assets/queries/k8s/psp_allows_sharing_host_pid/metadata.json
assets/queries/k8s/psp_allows_sharing_host_pid/query.rego
assets/queries/k8s/psp_allows_sharing_host_pid/test/negative.yaml
assets/queries/k8s/psp_allows_sharing_host_pid/test/positive.yaml
assets/queries/k8s/psp_allows_sharing_host_pid/test/positive_expected_result.json

Closes #488 
This query detects if a Pod Security Policy allows containers to share the host process ID namespace.

Add psp_allows_sharing_host_pid query for Kubernetes #488

---

assets/queries/k8s/shared_host_pid_namespace/metadata.json
assets/queries/k8s/shared_host_pid_namespace/query.rego
assets/queries/k8s/shared_host_pid_namespace/test/negative.yaml
assets/queries/k8s/shared_host_pid_namespace/test/positive.yaml
assets/queries/k8s/shared_host_pid_namespace/test/positive_expected_result.json

Closes #496 
This query checks if containers share the host process ID namespace.

Add shared_host_pid_namespace query for Kubernetes #496

---

assets/queries/k8s/psp_allows_sharing_host_ipc/metadata.json
assets/queries/k8s/psp_allows_sharing_host_ipc/query.rego
assets/queries/k8s/psp_allows_sharing_host_ipc/test/negative.yaml
assets/queries/k8s/psp_allows_sharing_host_ipc/test/positive.yaml
assets/queries/k8s/psp_allows_sharing_host_ipc/test/positive_expected_result.json

Closes #504 
This query detects if a Pod Security Policy allows containers to share the host IPC namespace.

Add psp_allows_sharing_host_ipc query for Kubernetes #504

---

assets/queries/k8s/shared_host_ipc_namespace/metadata.json
assets/queries/k8s/shared_host_ipc_namespace/query.rego
assets/queries/k8s/shared_host_ipc_namespace/test/negative.yaml
assets/queries/k8s/shared_host_ipc_namespace/test/positive.yaml
assets/queries/k8s/shared_host_ipc_namespace/test/positive_expected_result.json

Closes #505 
This query checks if containers share the host IPC namespace.

Add shared_host_ipc_namespace query for Kubernetes #505

---

assets/queries/k8s/service_account_token_automount_not_disabled/metadata.json
assets/queries/k8s/service_account_token_automount_not_disabled/query.rego
assets/queries/k8s/service_account_token_automount_not_disabled/test/negative.yaml
assets/queries/k8s/service_account_token_automount_not_disabled/test/positive.yaml
assets/queries/k8s/service_account_token_automount_not_disabled/test/positive_expected_result.json

Closes #512 
This query checks if automountServiceAccountToken is not disabled (true or undefined)

Add service_account_token_automount_not_disabled query for Kubernetes #512

---

assets/queries/k8s/secrets_as_environment_variables/metadata.json
assets/queries/k8s/secrets_as_environment_variables/query.rego
assets/queries/k8s/secrets_as_environment_variables/test/negative.yaml
assets/queries/k8s/secrets_as_environment_variables/test/positive.yaml
assets/queries/k8s/secrets_as_environment_variables/test/positive_expected_result.json

Closes #517 
This query checks if containers use secrets as environment variables.

Add secrets_as_environment_variables query for Kubernetes #517

---

assets/queries/k8s/containers_run_with_low_uid/metadata.json
assets/queries/k8s/containers_run_with_low_uid/query.rego
assets/queries/k8s/containers_run_with_low_uid/test/negative.yaml
assets/queries/k8s/containers_run_with_low_uid/test/positive.yaml
assets/queries/k8s/containers_run_with_low_uid/test/positive_expected_result.json

Check if any container has a low UID or if not set, the parent specification sets a low UID as well. Closes #552

Add query to check if there are containers running w/ low UID. Closes #552

---

assets/queries/k8s/container_cpu_requests_not_equal_limits/metadata.json
assets/queries/k8s/container_cpu_requests_not_equal_limits/query.rego
assets/queries/k8s/container_cpu_requests_not_equal_limits/test/negative.yaml
assets/queries/k8s/container_cpu_requests_not_equal_limits/test/positive.yaml
assets/queries/k8s/container_cpu_requests_not_equal_limits/test/positive_expected_result.json

Adding Container CPU Requests Not Equal Limits query for Kubernetes, that checks if the 'requests.cpu' is equal to 'limits.cpu', and if both are defined.
Closes #525

Add Container CPU Requests Not Equal Limits query for Kubernetes 

---

assets/queries/k8s/service_account_name_undefined_or_empty/metadata.json
assets/queries/k8s/service_account_name_undefined_or_empty/query.rego
assets/queries/k8s/service_account_name_undefined_or_empty/test/negative.yaml
assets/queries/k8s/service_account_name_undefined_or_empty/test/positive.yaml
assets/queries/k8s/service_account_name_undefined_or_empty/test/positive_expected_result.json

Adding Service Account Name Undefined Or Empty query for Kubernetes, that checks if the attribute 'serviceAccountName' is defined and not empty or null.
Closes #594

Add Service Account Name Undefined Or Empty query for Kubernetes

---

assets/queries/k8s/root_containers_admitted/metadata.json
assets/queries/k8s/root_containers_admitted/query.rego
assets/queries/k8s/root_containers_admitted/test/negative.yaml
assets/queries/k8s/root_containers_admitted/test/positive.yaml
assets/queries/k8s/root_containers_admitted/test/positive_expected_result.json

Adding Root Containers Admitted query for Kubernetes, that checks if the attributes 'privileged','allowPrivilegeEscalation' and 'readOnlyRootFilesystem' are set to false, 'runAsUser.rule' is set to 'MustRunAsNonRoot', and adding the root group is forbidden.
Closes #583

Add Root Containers Admitted query for Kubernetes

---

assets/queries/k8s/HPA_targets_a_invalid_object/metadata.json
assets/queries/k8s/HPA_targets_a_invalid_object/query.rego
assets/queries/k8s/HPA_targets_a_invalid_object/test/negative.yaml
assets/queries/k8s/HPA_targets_a_invalid_object/test/positive.yaml
assets/queries/k8s/HPA_targets_a_invalid_object/test/positive_expected_result.json

Added new query for Kubernetes.
Provide a HPA resource and a resource to ensure that the object is valid
Closes #524

Add HPA Targets a invalid object query

---

assets/queries/k8s/containers_run_as_root/metadata.json
assets/queries/k8s/containers_run_as_root/query.rego
assets/queries/k8s/containers_run_as_root/test/negative.yaml
assets/queries/k8s/containers_run_as_root/test/positive.yaml
assets/queries/k8s/containers_run_as_root/test/positive_expected_result.json

Check if containers run as root, either by their own settings or default parent settings. Closes #566

Add query to check if containers run as root unduly. Closes #566

---

assets/queries/k8s/container_requests_not_equal_limits/metadata.json
assets/queries/k8s/container_requests_not_equal_limits/query.rego
assets/queries/k8s/container_requests_not_equal_limits/test/negative.yaml
assets/queries/k8s/container_requests_not_equal_limits/test/positive.yaml
assets/queries/k8s/container_requests_not_equal_limits/test/positive_expected_result.json

Adding Container Requests Not Equal Limits query for Kubernetes, that checks if the 'requests.memory' and 'requests.cpu' are equal 'limits.memory' and 'limits.cpu', respectively, and all four are defined.
Closes #527

Add Container Requests Not Equal Limits query for Kubernetes

---

assets/queries/k8s/root_container_filesystem_not_readonly/metadata.json
assets/queries/k8s/root_container_filesystem_not_readonly/query.rego
assets/queries/k8s/root_container_filesystem_not_readonly/test/negative.yaml
assets/queries/k8s/root_container_filesystem_not_readonly/test/positive.yaml
assets/queries/k8s/root_container_filesystem_not_readonly/test/positive_expected_result.json

Check if a root container filesystem is mounted as read-only. Closes #574

Add query to check if root container is not readonly

---

assets/queries/k8s/container_memory_requests_not_equal_limits/metadata.json
assets/queries/k8s/container_memory_requests_not_equal_limits/query.rego
assets/queries/k8s/container_memory_requests_not_equal_limits/test/negative.yaml
assets/queries/k8s/container_memory_requests_not_equal_limits/test/positive.yaml
assets/queries/k8s/container_memory_requests_not_equal_limits/test/positive_expected_result.json

Adding Container Memory Requests Not Equal Limits query for Kubernetes, that checks if the 'requests.memory' is equal to 'limits.memory', and if both are defined.
Closes #526

Add Container Memory Requests Not Equal Limits query for Kubernetes 

---

assets/queries/k8s/readiness_probe_not_configured/metadata.json
assets/queries/k8s/readiness_probe_not_configured/query.rego
assets/queries/k8s/readiness_probe_not_configured/test/negative.yaml
assets/queries/k8s/readiness_probe_not_configured/test/positive.yaml
assets/queries/k8s/readiness_probe_not_configured/test/positive_expected_result.json

Check if any container, that is not part of a Job or CronJob, configures the readinessProbe. Closes #568 
Their utility, as mentioned in the Kubernetes [docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes), is:
> Sometimes, applications are temporarily unable to serve traffic. For example, an application might need to load large data or configuration files during startup, or depend on external services after startup. In such cases, you don't want to kill the application, but you don't want to send it requests either. Kubernetes provides readiness probes to detect and mitigate these situations.

Add query to check if ReadinessProbe is not configured in container. Closes #568

---

assets/queries/k8s/cluster_allows_unsafe_sysctls/metadata.json
assets/queries/k8s/cluster_allows_unsafe_sysctls/query.rego
assets/queries/k8s/cluster_allows_unsafe_sysctls/test/negative.yaml
assets/queries/k8s/cluster_allows_unsafe_sysctls/test/positive.yaml
assets/queries/k8s/cluster_allows_unsafe_sysctls/test/positive_expected_result.json

Adding Cluster Allows Unsafe Sysctls query for Kubernetes, that checks if any of the 'spec.securityContext.sysctls' is an Unsafe Sysctl and if the attribute 'allowedUnsafeSysctls' is defined.
Closes #620

Add Cluster Allows Unsafe Sysctls query for Kubernetes

---

assets/queries/cloudFormation/iam_user_with_inline_policies/metadata.json
assets/queries/cloudFormation/iam_user_with_inline_policies/query.rego
assets/queries/cloudFormation/iam_user_with_inline_policies/test/negative.yaml
assets/queries/cloudFormation/iam_user_with_inline_policies/test/positive.yaml
assets/queries/cloudFormation/iam_user_with_inline_policies/test/positive_expected_result.json

Closes #689
IAM User should embed managed policies instead of inline policies

Add iam_user_with_inline_policies query for AWS CloudFormation #689

---

assets/queries/cloudFormation/s3_bucket_allows_get_actions_from_all_principals/metadata.json
assets/queries/cloudFormation/s3_bucket_allows_get_actions_from_all_principals/query.rego
assets/queries/cloudFormation/s3_bucket_allows_get_actions_from_all_principals/test/negative.yaml
assets/queries/cloudFormation/s3_bucket_allows_get_actions_from_all_principals/test/positive.yaml
assets/queries/cloudFormation/s3_bucket_allows_get_actions_from_all_principals/test/positive_expected_result.json

Adding S3 Bucket Allows Get Action From All Principals query for CloudFormation, that checks if the 'Effect' is 'Allow' when the 'Action' is Get, for all Principals.
Closes #720

Add S3 Bucket Allows Get Action From All Principals query for CloudFormation

---

assets/queries/cloudFormation/s3_bucket_allows_put_actions_from_all_principals/metadata.json
assets/queries/cloudFormation/s3_bucket_allows_put_actions_from_all_principals/query.rego
assets/queries/cloudFormation/s3_bucket_allows_put_actions_from_all_principals/test/negative.yaml
assets/queries/cloudFormation/s3_bucket_allows_put_actions_from_all_principals/test/positive.yaml
assets/queries/cloudFormation/s3_bucket_allows_put_actions_from_all_principals/test/positive_expected_result.json

Adding S3 Bucket Allows Put Action From All Principals query for CloudFormation, that checks if the 'Effect' is 'Allow' when the 'Action' is Put, for all Principals.
Closes #718

Add S3 Bucket Allows Put Action From All Principals query for CloudFormation

---

assets/queries/cloudFormation/s3_bucket_allows_list_actions_from_all_principals/metadata.json
assets/queries/cloudFormation/s3_bucket_allows_list_actions_from_all_principals/query.rego
assets/queries/cloudFormation/s3_bucket_allows_list_actions_from_all_principals/test/negative.yaml
assets/queries/cloudFormation/s3_bucket_allows_list_actions_from_all_principals/test/positive.yaml
assets/queries/cloudFormation/s3_bucket_allows_list_actions_from_all_principals/test/positive_expected_result.json

Adding S3 Bucket Allows List Action From All Principals query for CloudFormation, that checks if the 'Effect' is 'Allow' when the 'Action' is List, for all Principals.
Closes #719

Add S3 Bucket Allows List Action From All Principals query for CloudFormation

---

assets/queries/cloudFormation/s3_bucket_allows_put_or_restore_actions_from_all_principals/metadata.json
assets/queries/cloudFormation/s3_bucket_allows_put_or_restore_actions_from_all_principals/query.rego
assets/queries/cloudFormation/s3_bucket_allows_put_or_restore_actions_from_all_principals/test/negative.yaml
assets/queries/cloudFormation/s3_bucket_allows_put_or_restore_actions_from_all_principals/test/positive.yaml
assets/queries/cloudFormation/s3_bucket_allows_put_or_restore_actions_from_all_principals/test/positive_expected_result.json

Adding S3 Bucket Allows Put Or Restore Actions From All Principals query for AWS CloudFormation, that checks if the 'Effect' is 'Allow' when the 'Action' is Put or Restore, for all Principals.
Closes #714

Add S3 Bucket Allows Put Or Restore Actions From All Principals query for AWS CloudFormation

---

assets/queries/cloudFormation/ec2_instance_no_iam_role/metadata.json
assets/queries/cloudFormation/ec2_instance_no_iam_role/query.rego
assets/queries/cloudFormation/ec2_instance_no_iam_role/test/negative.yaml
assets/queries/cloudFormation/ec2_instance_no_iam_role/test/positive.yaml
assets/queries/cloudFormation/ec2_instance_no_iam_role/test/positive_expected_result.json

Check EC2 instances in search of IAM profiles, that have roles associated, which control access. Flag if they are not found. Closes #658

Add query to check if EC2 instance don't have IAM roles associated. Closes #658

---

assets/queries/k8s/host_aliases_undefined_or_empty/metadata.json
assets/queries/k8s/host_aliases_undefined_or_empty/query.rego
assets/queries/k8s/host_aliases_undefined_or_empty/test/negative.yaml
assets/queries/k8s/host_aliases_undefined_or_empty/test/positive.yaml
assets/queries/k8s/host_aliases_undefined_or_empty/test/positive_expected_result.json

Adding Host Aliases Undefined Or Empty query for Kubernetes, that checks if the attribute 'spec.hostAliases' is defined and not empty or null.
Closes #596

Add Host Aliases Undefined Or Empty query for Kubernetes

---

assets/queries/cloudFormation/cloudfront_distribution_without_waf/metadata.json
assets/queries/cloudFormation/cloudfront_distribution_without_waf/query.rego
assets/queries/cloudFormation/cloudfront_distribution_without_waf/test/negative.yaml
assets/queries/cloudFormation/cloudfront_distribution_without_waf/test/positive.yaml
assets/queries/cloudFormation/cloudfront_distribution_without_waf/test/positive_expected_result.json

Closes #731 
All AWS CloudFront distributions should be integrated with the Web Application Firewall (AWS WAF) service.
This query checks if a "CloudFront::Distribution" resource isn't defining the "Properties.DistributionConfig.WebACLId" field.

Add cloudfront_distribution_without_waf query for AWS CloudFormation #731

---

assets/queries/k8s/cronjob_deadline_not_configured/metadata.json
assets/queries/k8s/cronjob_deadline_not_configured/query.rego
assets/queries/k8s/cronjob_deadline_not_configured/test/negative.yaml
assets/queries/k8s/cronjob_deadline_not_configured/test/positive.yaml
assets/queries/k8s/cronjob_deadline_not_configured/test/positive_expected_result.json

Adding CronJob Deadline Not Configured query for Kubernetes, that checks if the attribute 'startingDeadlineSeconds' is defined.
Closes #510

Add CronJob Deadline Not Configured query for Kubernetes

---

assets/queries/k8s/psp_containers_share_host_network_namespace/metadata.json
assets/queries/k8s/psp_containers_share_host_network_namespace/query.rego
assets/queries/k8s/psp_containers_share_host_network_namespace/test/negative.yaml
assets/queries/k8s/psp_containers_share_host_network_namespace/test/positive.yaml
assets/queries/k8s/psp_containers_share_host_network_namespace/test/positive_expected_result.json

Check if Pod Security Policy enables the host network to be shared by the containers. Closes #432

Add query to check if PSP allows containers to share  host network. Closes #432

---

assets/queries/k8s/seccomp_is_not_configured/metadata.json
assets/queries/k8s/seccomp_is_not_configured/query.rego
assets/queries/k8s/seccomp_is_not_configured/test/negative.yaml
assets/queries/k8s/seccomp_is_not_configured/test/positive.yaml
assets/queries/k8s/seccomp_is_not_configured/test/positive_expected_result.json

Check if any service does not use the default profile for Seccomp. Closes #587

Add query to check if seccomp profile is not configured. Closes #587

---

assets/queries/k8s/pod_network_policy_not_configured/metadata.json
assets/queries/k8s/pod_network_policy_not_configured/query.rego
assets/queries/k8s/pod_network_policy_not_configured/test/negative.yaml
assets/queries/k8s/pod_network_policy_not_configured/test/positive.yaml
assets/queries/k8s/pod_network_policy_not_configured/test/positive_expected_result.json

Check if any pod is not being targeted by a network policy in both ingress and egress traffic. Closes #603

Add query to check if a Pod does not have matching network policy. closes #603

---

assets/queries/k8s/metadata_label_is_invalid/metadata.json
assets/queries/k8s/metadata_label_is_invalid/query.rego
assets/queries/k8s/metadata_label_is_invalid/test/negative.yaml
assets/queries/k8s/metadata_label_is_invalid/test/positive.yaml
assets/queries/k8s/metadata_label_is_invalid/test/positive_expected_result.json

Check if any object metadata contains an invalid label (e.g, with /+*!?, etc). Closes #607

Add query to check if metadata labels are invalid. Closes #607

---

assets/queries/k8s/incorrect_volume_claim_access_mode_readWriteOnce/metadata.json
assets/queries/k8s/incorrect_volume_claim_access_mode_readWriteOnce/query.rego
assets/queries/k8s/incorrect_volume_claim_access_mode_readWriteOnce/test/negative.yaml
assets/queries/k8s/incorrect_volume_claim_access_mode_readWriteOnce/test/positive.yaml
assets/queries/k8s/incorrect_volume_claim_access_mode_readWriteOnce/test/positive_expected_result.json

Adding Incorrect Volume Claim Access Mode Read Write Once query for Kubernetes, that verifies Stateful Sets have one Volume Claim template with the access mode 'ReadWriteOnce'.
Closes #617

Add Incorrect Volume Claim Access Mode Read Write Once query for Kubernetes 

---

assets/queries/cloudFormation/s3_bucket_allows_delete_actions_from_all_principals/metadata.json
assets/queries/cloudFormation/s3_bucket_allows_delete_actions_from_all_principals/query.rego
assets/queries/cloudFormation/s3_bucket_allows_delete_actions_from_all_principals/test/negative.yaml
assets/queries/cloudFormation/s3_bucket_allows_delete_actions_from_all_principals/test/positive.yaml
assets/queries/cloudFormation/s3_bucket_allows_delete_actions_from_all_principals/test/positive_expected_result.json

Adding S3 Bucket Allows Delete Action From All Principals query for AWS CloudFormation, that checks if the 'Effect' is 'Allow' when the 'Action' is Delete, for all Principals.
Closes #796

Add S3 Bucket Allows Delete Action From All Principals query for AWS CloudFormation

---

assets/queries/cloudFormation/s3_bucket_allows_all_actions_from_all_principals/metadata.json
assets/queries/cloudFormation/s3_bucket_allows_all_actions_from_all_principals/query.rego
assets/queries/cloudFormation/s3_bucket_allows_all_actions_from_all_principals/test/negative.yaml
assets/queries/cloudFormation/s3_bucket_allows_all_actions_from_all_principals/test/positive.yaml
assets/queries/cloudFormation/s3_bucket_allows_all_actions_from_all_principals/test/positive_expected_result.json

Adding S3 Bucket Allows All Actions From All Principals query for CloudFormation, that checks if the 'Effect' is 'Allow' when the 'Action' is '*', for all Principals.
Closes #717

Add S3 Bucket Allows All Actions From All Principals query for CloudFormation 

---

assets/queries/cloudFormation/secure_ciphers_disabled/metadata.json
assets/queries/cloudFormation/secure_ciphers_disabled/query.rego
assets/queries/cloudFormation/secure_ciphers_disabled/test/negative.yaml
assets/queries/cloudFormation/secure_ciphers_disabled/test/positive.yaml
assets/queries/cloudFormation/secure_ciphers_disabled/test/positive_expected_result.json

Closes #732 
Check if secure ciphers aren't used in CloudFront

Add secure_ciphers_disabled query Closes #732

---

assets/queries/k8s/volume_mount_with_OS_directory_write_permissions/metadata.json
assets/queries/k8s/volume_mount_with_OS_directory_write_permissions/query.rego
assets/queries/k8s/volume_mount_with_OS_directory_write_permissions/test/negative.yaml
assets/queries/k8s/volume_mount_with_OS_directory_write_permissions/test/positive.yaml
assets/queries/k8s/volume_mount_with_OS_directory_write_permissions/test/positive_expected_result.json
go.mod

Description: Containers can mount sensitive folders from the hosts, giving them potentially dangerous access to critical host configurations and binaries.
Query looks for volume mounts, where the path startswith a Sensitive linux folder name, and then checks if the readOnly attribute of the mount is true, otherwise returns the result as a true positive.
Closes #638

Add query volumn mount with os directory write permissions

---

assets/queries/terraform/aws/authentication_without_mfa/metadata.json
assets/queries/terraform/aws/authentication_without_mfa/query.rego
assets/queries/terraform/aws/authentication_without_mfa/test/negative.tf
assets/queries/terraform/aws/authentication_without_mfa/test/positive.tf
assets/queries/terraform/aws/authentication_without_mfa/test/positive_expected_result.json

For this query, it is necessary to check if the user did authenticate with MFA through the aws:MultiFactorAuthPresent key set a true in a Bool condition. For that, it is necessary to verify if the aws:MultiFactorAuthPresent is undefined or set a false.
However, the key is only present when the user authenticates with short-term credentials. So, I thought checking the existence of a token, since session token is used for validating temporary credentials. I did not find another alternative.
Closes #711

Add authentication_without_mfa Closes #711

---

assets/queries/k8s/ingress_controller_exposes_workload/metadata.json
assets/queries/k8s/ingress_controller_exposes_workload/query.rego
assets/queries/k8s/ingress_controller_exposes_workload/test/negative.yaml
assets/queries/k8s/ingress_controller_exposes_workload/test/positive.yaml
assets/queries/k8s/ingress_controller_exposes_workload/test/positive_expected_result.json

For this query, it is necessary to check if the service name and service port of the ingress are associated with some service defined. I came across this solution through the following documents: https://kubernetes.github.io/ingress-nginx/user-guide/basic-usage/ and https://blog.cloud66.com/setting-up-secure-endpoints-in-kubernetes/. I have to give credits to @fabioGoncalvesCx since he did a similar query and helped me.
Closes #676

ingress_controller_exposes_workload Closes #676

---

assets/queries/cloudFormation/aws_support_has_no_role/metadata.json
assets/queries/cloudFormation/aws_support_has_no_role/query.rego
assets/queries/cloudFormation/aws_support_has_no_role/test/negative.yaml
assets/queries/cloudFormation/aws_support_has_no_role/test/positive.yaml
assets/queries/cloudFormation/aws_support_has_no_role/test/positive_expected_result.json

Check if any AWS support policy is not associated with a role, user, or group. Closes #778

Add query to check if AWS Support is associated to role or user. Closes #778

---

assets/queries/cloudFormation/iam_policy_full_permissions/metadata.json
assets/queries/cloudFormation/iam_policy_full_permissions/query.rego
assets/queries/cloudFormation/iam_policy_full_permissions/test/negative.yaml
assets/queries/cloudFormation/iam_policy_full_permissions/test/positive.yaml
assets/queries/cloudFormation/iam_policy_full_permissions/test/positive_expected_result.json

Check if an IAM policy is granting full permissions to a Resource that is not Admin, which should not happen, the resource should only have the necessary permissions. Closes #772

Add query to check if policy grants full permissions unduly. Closes #772

---

assets/queries/cloudFormation/redshift_cluster_publicly_accessible/metadata.json
assets/queries/cloudFormation/redshift_cluster_publicly_accessible/query.rego
assets/queries/cloudFormation/redshift_cluster_publicly_accessible/test/negative.yaml
assets/queries/cloudFormation/redshift_cluster_publicly_accessible/test/positive.yaml
assets/queries/cloudFormation/redshift_cluster_publicly_accessible/test/positive_expected_result.json

Adding Redshift Cluster Publicly Accessible query for CloudFormation, that checks if the attribute 'PubliclyAccessible' is set to false and defined.
Closes #844

Add Redshift Cluster Publicly Accessible query for CloudFormation

---

assets/queries/cloudFormation/alb_listeners_accept_http/metadata.json
assets/queries/cloudFormation/alb_listeners_accept_http/query.rego
assets/queries/cloudFormation/alb_listeners_accept_http/test/negative.yaml
assets/queries/cloudFormation/alb_listeners_accept_http/test/positive.yaml
assets/queries/cloudFormation/alb_listeners_accept_http/test/positive_expected_result.json

Closes #842 
All Application Load Balancers (ALB) should block connection requests over HTTP.
This query checks two resources:
- "AWS::ElasticLoadBalancing::LoadBalancer": if one of the elements inside the 'Listeners' list has 'Protocol' field equals to 'HTTP';
- "AWS::ElasticLoadBalancingV2::Listener": if 'Protocol' field equals to 'HTTP'.

Add alb_listeners_accept_http query for AWS CloudFormation #842

---

assets/queries/cloudFormation/elb_using_insecure_protocols/metadata.json
assets/queries/cloudFormation/elb_using_insecure_protocols/query.rego
assets/queries/cloudFormation/elb_using_insecure_protocols/test/negative.yaml
assets/queries/cloudFormation/elb_using_insecure_protocols/test/positive.yaml
assets/queries/cloudFormation/elb_using_insecure_protocols/test/positive_expected_result.json

Adding ELB Using Insecure Protocols query for AWS CloudFormation, that checks if ELB Listeners have Policies that possess Protocols that coincide with any of a predefined list of insecure protocols.
Closes #805

Add ELB Using Insecure Protocols query for AWS CloudFormation 

---

assets/queries/cloudFormation/alb_is_not_integrated_with_waf/metadata.json
assets/queries/cloudFormation/alb_is_not_integrated_with_waf/query.rego
assets/queries/cloudFormation/alb_is_not_integrated_with_waf/test/negative.yaml
assets/queries/cloudFormation/alb_is_not_integrated_with_waf/test/positive.yaml
assets/queries/cloudFormation/alb_is_not_integrated_with_waf/test/positive_expected_result.json

Closes #821 
All Application Load Balancers (ALB) must be protected with Web Application Firewall (WAF) service.
This query checks if a public ALB ('Scheme' field not "internal") has no associated WAF resource (a "AWS::WAFRegional::WebACLAssociation" resource with "ResourceArn" field referring the ALB resource).

Add alb_is_not_integrated_with_waf query for AWS CloudFormation #821

---

assets/queries/cloudFormation/ecs_no_load_balancer_attached/metadata.json
assets/queries/cloudFormation/ecs_no_load_balancer_attached/query.rego
assets/queries/cloudFormation/ecs_no_load_balancer_attached/test/negative.yaml
assets/queries/cloudFormation/ecs_no_load_balancer_attached/test/positive.yaml
assets/queries/cloudFormation/ecs_no_load_balancer_attached/test/positive_expected_result.json

Adding ECS No Load Balancer Attached query for AWS CloudFormation, that checks if there exists at least one LoadBalancer.
Closes #829

Add ECS No Load Balancer Attached query for AWS CloudFormation

---

assets/queries/cloudFormation/iam_user_too_many_access_keys/metadata.json
assets/queries/cloudFormation/iam_user_too_many_access_keys/query.rego
assets/queries/cloudFormation/iam_user_too_many_access_keys/test/negative.yaml
assets/queries/cloudFormation/iam_user_too_many_access_keys/test/positive.yaml
assets/queries/cloudFormation/iam_user_too_many_access_keys/test/positive_expected_result.json

Check if an IAM user has more than one access key associated, which increases the risk of unauthorized access. closes #804

Add query to check if user has too many access keys. closes #804

---

assets/queries/cloudFormation/kinesis_stream_without_sse/metadata.json
assets/queries/cloudFormation/kinesis_stream_without_sse/query.rego
assets/queries/cloudFormation/kinesis_stream_without_sse/test/negative.yaml
assets/queries/cloudFormation/kinesis_stream_without_sse/test/positive.yaml
assets/queries/cloudFormation/kinesis_stream_without_sse/test/positive_expected_result.json

For this query, it is necessary to check the existence of the attribute StreamEncryption and the respective attributes, since "when StreamEncryption is specified, enables or updates server-side encryption using an AWS KMS key for a specified stream. Removing this property from your stack template and updating your stack disables encryption".
Closes #849

Add kinesis_stream_without_sse Closes #849

---

assets/queries/cloudFormation/redshift_instances_not_encrypted/metadata.json
assets/queries/cloudFormation/redshift_instances_not_encrypted/query.rego
assets/queries/cloudFormation/redshift_instances_not_encrypted/test/negative.yaml
assets/queries/cloudFormation/redshift_instances_not_encrypted/test/positive.yaml
assets/queries/cloudFormation/redshift_instances_not_encrypted/test/positive_expected_result.json

For this query, it necessary to check if the attribute 'Encrypted' not exists in 'Properties' or if exists in 'Properties' and is set to false, since if set to true, the data in the cluster is encrypted at rest.
Closes #801

Add redshift_instances_not_encrypted Closes #801

---

assets/queries/cloudFormation/auto_scaling_group_with_no_associated_elb/metadata.json
assets/queries/cloudFormation/auto_scaling_group_with_no_associated_elb/query.rego
assets/queries/cloudFormation/auto_scaling_group_with_no_associated_elb/test/negative.yaml
assets/queries/cloudFormation/auto_scaling_group_with_no_associated_elb/test/positive.yaml
assets/queries/cloudFormation/auto_scaling_group_with_no_associated_elb/test/positive_expected_result.json

Adding Auto Scaling Group With No Associated ELB query for AWS CloudFormation, that checks if the attribute 'LoadBalancerNames' is defined and not empty.
Closes #883

Add Auto Scaling Group With No Associated ELB query for AWS CloudFormation

---

assets/queries/cloudFormation/api_gateway_exposed_to_the_public_internet/metadata.json
assets/queries/cloudFormation/api_gateway_exposed_to_the_public_internet/query.rego
assets/queries/cloudFormation/api_gateway_exposed_to_the_public_internet/test/negative.yaml
assets/queries/cloudFormation/api_gateway_exposed_to_the_public_internet/test/positive.yaml
assets/queries/cloudFormation/api_gateway_exposed_to_the_public_internet/test/positive_expected_result.json

Closes #859 
The API Endpoint type in API Gateway should be set to PRIVATE so it's not exposed to the public internet.
This query checks, within an "AWS::ApiGateway::RestApi" resource, if:
- 'EndpointConfiguration' is undefined or
- 'EndpointConfiguration.Types' is undefined or
- 'EndpointConfiguration.Types' does not contain 'PRIVATE'

Add api_gateway_exposed_to_the_public_internet query for AWS CloudFormation #859

---

assets/queries/cloudFormation/redshift_without_kms_cmk/metadata.json
assets/queries/cloudFormation/redshift_without_kms_cmk/query.rego
assets/queries/cloudFormation/redshift_without_kms_cmk/test/negative.yaml
assets/queries/cloudFormation/redshift_without_kms_cmk/test/positive.yaml
assets/queries/cloudFormation/redshift_without_kms_cmk/test/positive_expected_result.json

In Dome9 documentation, it is recommended to check if the attribute KmsKeyId is defined and if attribute 'Encrypted' exists and is set to true. Since we already have a query redshift_instances_not_encrypted, I just checked the attribute KmsKeyId existence
Closes #834

Add redshift_without_kms_cmk Closes #834

---

assets/queries/cloudFormation/ingress_has_cidr_not_recommended/metadata.json
assets/queries/cloudFormation/ingress_has_cidr_not_recommended/query.rego
assets/queries/cloudFormation/ingress_has_cidr_not_recommended/test/negative.yaml
assets/queries/cloudFormation/ingress_has_cidr_not_recommended/test/positive.yaml
assets/queries/cloudFormation/ingress_has_cidr_not_recommended/test/positive_expected_result.json

For this query, it is necessary to check if AWS Security Group Ingress CIDR is /32 in case of IPV4 or /128 in case of IPV6
Closes #952

Add ingress_has_cidr_not_recommended Closes #952

---

assets/queries/cloudFormation/ecs_service_in_cluster_no_task_definition/metadata.json
assets/queries/cloudFormation/ecs_service_in_cluster_no_task_definition/query.rego
assets/queries/cloudFormation/ecs_service_in_cluster_no_task_definition/test/negative.yaml
assets/queries/cloudFormation/ecs_service_in_cluster_no_task_definition/test/positive.yaml
assets/queries/cloudFormation/ecs_service_in_cluster_no_task_definition/test/positive_expected_result.json

Check if the ECS cluster has services that don't have Task Definitions Roles associated. Closes #708

Add query to check if ECS Cluster has services  without TaskDefinition with roles. Closes #708

---

assets/queries/cloudFormation/security_groups_allows_unrestricted_outbound_traffic/metadata.json
assets/queries/cloudFormation/security_groups_allows_unrestricted_outbound_traffic/query.rego
assets/queries/cloudFormation/security_groups_allows_unrestricted_outbound_traffic/test/negative.yaml
assets/queries/cloudFormation/security_groups_allows_unrestricted_outbound_traffic/test/positive.yaml
assets/queries/cloudFormation/security_groups_allows_unrestricted_outbound_traffic/test/positive_expected_result.json

It is important that no security group allows unrestricted egress access.
Closes #748

Add Sec. Groups Allows egress access query #748

---

assets/queries/cloudFormation/ecs_service_in_cluster_no_task_definition/query.rego

The query was failing when running all of them together

Fixed conflicting rule

---

assets/queries/cloudFormation/tcp_or_udp_protocol_network_acl_entry_allows_all_ports/metadata.json
assets/queries/cloudFormation/tcp_or_udp_protocol_network_acl_entry_allows_all_ports/query.rego
assets/queries/cloudFormation/tcp_or_udp_protocol_network_acl_entry_allows_all_ports/test/negative.yaml
assets/queries/cloudFormation/tcp_or_udp_protocol_network_acl_entry_allows_all_ports/test/positive.yaml
assets/queries/cloudFormation/tcp_or_udp_protocol_network_acl_entry_allows_all_ports/test/positive_expected_result.json

To check if the protocol is TCP ou UDP, it is necessary to check the attribute 'Protocol' of Properties ( TCP is represented by 6 and UDP by 17). 
Furthermore, it is necessary to check if the attribute 'PortRange' of Properties is set, as well as their attributes ('From' and 'To').
Not less important, it is necessary to check if 'From' is set to 0 and 'To' set to 65535.
Closes #1118

Add tcp_or_udp_protocol_network_acl_entry_allows_all_ports Closes #1118

---

assets/queries/cloudFormation/filter_and_alarm_exist_for_S3_bucket_policy_changes/metadata.json
assets/queries/cloudFormation/filter_and_alarm_exist_for_S3_bucket_policy_changes/query.rego
assets/queries/cloudFormation/filter_and_alarm_exist_for_S3_bucket_policy_changes/test/negative.yaml
assets/queries/cloudFormation/filter_and_alarm_exist_for_S3_bucket_policy_changes/test/positive.yaml
assets/queries/cloudFormation/filter_and_alarm_exist_for_S3_bucket_policy_changes/test/positive_expected_result.json

Provide a CloudFormation resource and a resource to ensure that changes in S3 Bucket Policy are configured in an alarm and a metric filter
Closes #1147

Add Filter&Alarm !Exists S3 Bucket Policy Changes

---

assets/queries/cloudFormation/rds_public_interface_open_to_public_scope/metadata.json
assets/queries/cloudFormation/rds_public_interface_open_to_public_scope/query.rego
assets/queries/cloudFormation/rds_public_interface_open_to_public_scope/test/negative.yaml
assets/queries/cloudFormation/rds_public_interface_open_to_public_scope/test/positive.yaml
assets/queries/cloudFormation/rds_public_interface_open_to_public_scope/test/positive_expected_result.json

Adding RDS Public Interface Open To Public Scope query for AWS CloudFormation, that checks if the IP Address in its Security Group is '0.0.0.0/0' (IPv4) or '::/0' (IPv6) when it has a public interface.
Closes #1126

Add RDS Public Interface Open To Public Scope query for AWS CloudFormation

---

assets/queries/dockerfile/missing_version_specification_in_dnf_install/metadata.json
assets/queries/dockerfile/missing_version_specification_in_dnf_install/query.rego
assets/queries/dockerfile/missing_version_specification_in_dnf_install/test/negative.dockerfile
assets/queries/dockerfile/missing_version_specification_in_dnf_install/test/positive.dockerfile
assets/queries/dockerfile/missing_version_specification_in_dnf_install/test/positive_expected_result.json

Package versions should be pinned when running `dnf install`,  as it allows to reduce failures due to unanticipated changes in required packages. Closes #1068

Add missing_version_specification_in_dnf_install query for Docker

---

assets/queries/dockerfile/missing_dnf_clean_all/metadata.json
assets/queries/dockerfile/missing_dnf_clean_all/query.rego
assets/queries/dockerfile/missing_dnf_clean_all/test/negative.dockerfile
assets/queries/dockerfile/missing_dnf_clean_all/test/positive.dockerfile
assets/queries/dockerfile/missing_dnf_clean_all/test/positive_expected_result.json

Cached package data should be cleaned after installation to reduce image size. This can be achieved by executing the `dnf clean all command` in the same `RUN` step, after installing the packages. Closes #1069

Add missing_dnf_clean_all query for Docker

---

assets/queries/dockerfile/unpinned_package_version_in_pip_install/metadata.json
assets/queries/dockerfile/unpinned_package_version_in_pip_install/query.rego
assets/queries/dockerfile/unpinned_package_version_in_pip_install/test/negative.dockerfile
assets/queries/dockerfile/unpinned_package_version_in_pip_install/test/positive.dockerfile
assets/queries/dockerfile/unpinned_package_version_in_pip_install/test/positive_expected_result.json

**Platform**
_Docker_
_Package version pinning reduces the range of versions that can be installed, reducing the chances of failure due to unanticipated changes_
Closes #1010

Add 'Unpinned Package Version in pip install' query for Docker

---

assets/queries/dockerfile/use_of_apk_upgrade/metadata.json
assets/queries/dockerfile/use_of_apk_upgrade/query.rego
assets/queries/dockerfile/use_of_apk_upgrade/test/negative.dockerfile
assets/queries/dockerfile/use_of_apk_upgrade/test/positive.dockerfile
assets/queries/dockerfile/use_of_apk_upgrade/test/positive_expected_result.json

*Docker*
*Avoid usage of 'apk upgrade' because some packages from the parent image cannot be upgraded inside an unprivileged container*
Closes #987

Add 'Use of apk upgrade' query for Docker

---

assets/queries/cloudFormation/directory_service_simple_ad_password_rule/metadata.json
assets/queries/cloudFormation/directory_service_simple_ad_password_rule/query.rego
assets/queries/cloudFormation/directory_service_simple_ad_password_rule/test/negative.yaml
assets/queries/cloudFormation/directory_service_simple_ad_password_rule/test/positive.yaml
assets/queries/cloudFormation/directory_service_simple_ad_password_rule/test/positive_expected_result.json

Description:
Directory Service Microsoft AD password must not be a plaintext string or a Ref to a Parameter with a Default value.   Can be Ref to a NoEcho Parameter without a Default, or a dynamic reference to a secretsmanager/ssm-secure value.
close #1025

Added Query Directory Service Simple AD Password Rule

---

assets/queries/cloudFormation/amplify_app_oauth_token_rule/metadata.json
assets/queries/cloudFormation/amplify_app_oauth_token_rule/query.rego
assets/queries/cloudFormation/amplify_app_oauth_token_rule/test/negative.yaml
assets/queries/cloudFormation/amplify_app_oauth_token_rule/test/positive.yaml
assets/queries/cloudFormation/amplify_app_oauth_token_rule/test/positive_expected_result.json

Description
Amplify App OAuth Token must not be a plaintext string or a Ref to a Parameter with a Default value.
Close  #1114

Added Query Amplify App OAuth Token Rule

---

assets/queries/cloudFormation/filter_and_alarm_exist_for_Management_Console/metadata.json
assets/queries/cloudFormation/filter_and_alarm_exist_for_Management_Console/query.rego
assets/queries/cloudFormation/filter_and_alarm_exist_for_Management_Console/test/negative.yaml
assets/queries/cloudFormation/filter_and_alarm_exist_for_Management_Console/test/positive.yaml
assets/queries/cloudFormation/filter_and_alarm_exist_for_Management_Console/test/positive_expected_result.json

Provide a CloudFormation resource and a resource to ensure that AWS Config Configuration exists for Management Console sign-in without MFA
Closes #1134

Add Filter&Alarm Not Exists For Management Console

---

assets/queries/ansible/azure/vm_not_attached_to_network/metadata.json
assets/queries/ansible/azure/vm_not_attached_to_network/query.rego
assets/queries/ansible/azure/vm_not_attached_to_network/test/negative.yaml
assets/queries/ansible/azure/vm_not_attached_to_network/test/positive.yaml
assets/queries/ansible/azure/vm_not_attached_to_network/test/positive_expected_result.json

Closes #1362 
This query detects if no Network Security Group is attached to a Virtual Machine

Add vm_not_attached_to_network query for Ansible #1362

---

assets/queries/ansible/azure/ad_admin_not_configured_for_sql_server/metadata.json
assets/queries/ansible/azure/ad_admin_not_configured_for_sql_server/query.rego
assets/queries/ansible/azure/ad_admin_not_configured_for_sql_server/test/negative.yaml
assets/queries/ansible/azure/ad_admin_not_configured_for_sql_server/test/positive.yaml
assets/queries/ansible/azure/ad_admin_not_configured_for_sql_server/test/positive_expected_result.json

Closes #1371 
This query checks if there is an SQL Server without an AD Admin configured.

Add ad_admin_not_configured_for_sql_server query for Ansible #1371

---

assets/queries/ansible/gcp/vm_with_full_cloud_access/metadata.json
assets/queries/ansible/gcp/vm_with_full_cloud_access/query.rego
assets/queries/ansible/gcp/vm_with_full_cloud_access/test/negative.yaml
assets/queries/ansible/gcp/vm_with_full_cloud_access/test/positive.yaml
assets/queries/ansible/gcp/vm_with_full_cloud_access/test/positive_expected_result.json

Closes #1353 
This query detects if a VM instance is configured to use the default service account with full access to all Cloud APIs.
Checks if, within a 'google_compute_instance' resource, the list 'service_accounts.scopes' contains 'cloud_platform'.

Add vm_with_full_cloud_access query for Ansible #1353

---

assets/queries/dockerfile/copy_from_references_current_from_alias/metadata.json
assets/queries/dockerfile/copy_from_references_current_from_alias/query.rego
assets/queries/dockerfile/copy_from_references_current_from_alias/test/negative.dockerfile
assets/queries/dockerfile/copy_from_references_current_from_alias/test/positive.dockerfile
assets/queries/dockerfile/copy_from_references_current_from_alias/test/positive_expected_result.json

For this query, it is necessary to check if COPY --from references the current FROM alias. To do that, we need to check if the cmd copy has an attribute 'flags' like "--from=" and keep the alias. Next, we need to check if this current alias is equal to the current FROM alias ( through attribute Values of cmd from)
Closes #1172

Add copy_from_references_current_from_alias query Closes #1172

---

assets/queries/ansible/aws/unknown_port_exposed_to_internet/metadata.json
assets/queries/ansible/aws/unknown_port_exposed_to_internet/query.rego
assets/queries/ansible/aws/unknown_port_exposed_to_internet/test/negative.yaml
assets/queries/ansible/aws/unknown_port_exposed_to_internet/test/positive.yaml
assets/queries/ansible/aws/unknown_port_exposed_to_internet/test/positive_expected_result.json

For this query, I verified if the attribute 'from_port' of 'rules' is an unknown port and if is exposed to the entire Internet ("0.0.0.0/0" or "::/0")
I did not indicate from_port in searchKey because for some reason (which I did not understand) the tests failed
(P.S. I did not find the module community to satisfy this query)
Closes #1214

Add unknown_port_exposed_to_internet Closes #1214

---

assets/queries/ansible/aws/elb_using_insecure_protocols/metadata.json
assets/queries/ansible/aws/elb_using_insecure_protocols/query.rego
assets/queries/ansible/aws/elb_using_insecure_protocols/test/negative.yaml
assets/queries/ansible/aws/elb_using_insecure_protocols/test/positive.yaml
assets/queries/ansible/aws/elb_using_insecure_protocols/test/positive_expected_result.json

Adding ELB Using Insecure Protocols query for Ansible, that checks if the 'SslPolicy' of 'listeners' must not coincide with any of a predefined list of insecure protocols.
Closes #1339

Add ELB Using Insecure Protocols query for Ansible 

---

assets/queries/ansible/gcp/cloud_storage_anonymous_or_publicly_accessible/metadata.json
assets/queries/ansible/gcp/cloud_storage_anonymous_or_publicly_accessible/query.rego
assets/queries/ansible/gcp/cloud_storage_anonymous_or_publicly_accessible/test/negative.yaml
assets/queries/ansible/gcp/cloud_storage_anonymous_or_publicly_accessible/test/positive.yaml
assets/queries/ansible/gcp/cloud_storage_anonymous_or_publicly_accessible/test/positive_expected_result.json

Adding Cloud Storage Anonymous or Publicly Accessible query for Ansible, that checks if the attribute 'entity' must not be 'allUsers' or 'allAuthenticatedUsers'.
Closes #1349

Add Cloud Storage Anonymous or Publicly Accessible query for Ansible 

---

assets/queries/ansible/gcp/dnssec_using_rsasha1/metadata.json
assets/queries/ansible/gcp/dnssec_using_rsasha1/query.rego
assets/queries/ansible/gcp/dnssec_using_rsasha1/test/negative.yaml
assets/queries/ansible/gcp/dnssec_using_rsasha1/test/positive.yaml
assets/queries/ansible/gcp/dnssec_using_rsasha1/test/positive_expected_result.json

Closes #1338 
This query checks if, within the 'dnssec_config' block, the 'default_key_specs' block exists with the 'algorithm' field is 'rsasha1' which is bad.

Add dnssec_using_rsasha1 query for Ansible #1338

---

assets/queries/ansible/gcp/cos_node_image_not_used/metadata.json
assets/queries/ansible/gcp/cos_node_image_not_used/query.rego
assets/queries/ansible/gcp/cos_node_image_not_used/test/negative.yaml
assets/queries/ansible/gcp/cos_node_image_not_used/test/positive.yaml
assets/queries/ansible/gcp/cos_node_image_not_used/test/positive_expected_result.json

Closes #1343 
This query detects if a node image that is not COS (Container-Optimized OS) is used for Kubernetes Engine Clusters Node image.

Add cos_node_image_not_used query for Ansible #1343

---

assets/queries/ansible/gcp/shielded_vm_is_disabled/metadata.json
assets/queries/ansible/gcp/shielded_vm_is_disabled/query.rego
assets/queries/ansible/gcp/shielded_vm_is_disabled/test/negative.yaml
assets/queries/ansible/gcp/shielded_vm_is_disabled/test/positive.yaml
assets/queries/ansible/gcp/shielded_vm_is_disabled/test/positive_expected_result.json

Adding Shielded VM is Disabled query for Ansible, that checks if the attribute 'shielded_instance_config' is defined and its sub attributes 'enable_secure_boot', 'enable_vtpm' and 'enable_integrity_monitoring' are set to true.
Closes #1356

Add Shielded VM is Disabled query for Ansible

---

assets/queries/ansible/aws/kinesis_not_encrypted_with_kms/metadata.json
assets/queries/ansible/aws/kinesis_not_encrypted_with_kms/query.rego
assets/queries/ansible/aws/kinesis_not_encrypted_with_kms/test/negative.yaml
assets/queries/ansible/aws/kinesis_not_encrypted_with_kms/test/positive.yaml
assets/queries/ansible/aws/kinesis_not_encrypted_with_kms/test/positive_expected_result.json

For this query, it is necessary to check if the attribute 'encryption_type' is set and defined as KMS and if the attribute 'key_id' is set, as well as the attribute 'encryption_state' set to enabled.
So, I thought in five cases:
Attribute 'encryption_state' is undefined
Attribute 'encryption_state' is not set to enabled
Attribute 'encryption_type' is undefined
Attribute 'encryption_type' is set but defined as "NONE"
Attribute 'encryption_type' is "KMS" but the attribute key_id' is undefined
Closes #1357

Add kinesis_not_encrypted_with_kms Closes #1357

---

assets/queries/ansible/gcp/ip_forwarding_is_enabled/metadata.json
assets/queries/ansible/gcp/ip_forwarding_is_enabled/query.rego
assets/queries/ansible/gcp/ip_forwarding_is_enabled/test/negative.yaml
assets/queries/ansible/gcp/ip_forwarding_is_enabled/test/positive.yaml
assets/queries/ansible/gcp/ip_forwarding_is_enabled/test/positive_expected_result.json

Adding IP Forwarding is Enabled query for Ansible, that checks if the attribute 'can_ip_forward' is true.
Closes #1361

Add IP Forwarding is Enabled query for Ansible

---

assets/queries/ansible/gcp/client_certificate_is_disabled/metadata.json
assets/queries/ansible/gcp/client_certificate_is_disabled/query.rego
assets/queries/ansible/gcp/client_certificate_is_disabled/test/negative.yaml
assets/queries/ansible/gcp/client_certificate_is_disabled/test/positive.yaml
assets/queries/ansible/gcp/client_certificate_is_disabled/test/positive_expected_result.json

Adding Client Certificate is Disabled query for Ansible, that checks if 'master_auth' has 'client_certificate_config' with the sub attribute 'issue_client_certificate' equal to true.
Closes #1315

Add Client Certificate is Disabled query for Ansible

---

assets/queries/ansible/gcp/legacy_authorization_is_enabled/metadata.json
assets/queries/ansible/gcp/legacy_authorization_is_enabled/query.rego
assets/queries/ansible/gcp/legacy_authorization_is_enabled/test/negative.yaml
assets/queries/ansible/gcp/legacy_authorization_is_enabled/test/positive.yaml
assets/queries/ansible/gcp/legacy_authorization_is_enabled/test/positive_expected_result.json

Adding Legacy Authorization is Enabled query for Ansible, that checks if the attribute 'legacy_abac.enabled' is false.
Closes #1293

Add Legacy Authorization is Enabled query for Ansible

---

assets/queries/ansible/gcp/stackdriver_logging_is_disabled/metadata.json
assets/queries/ansible/gcp/stackdriver_logging_is_disabled/query.rego
assets/queries/ansible/gcp/stackdriver_logging_is_disabled/test/negative.yaml
assets/queries/ansible/gcp/stackdriver_logging_is_disabled/test/positive.yaml
assets/queries/ansible/gcp/stackdriver_logging_is_disabled/test/positive_expected_result.json

Adding Stackdriver Logging is Disabled query for Ansible, that checks if the attribute 'logging_service' is defined and different from 'none'.
Closes #1288

Add Stackdriver Logging is Disabled query for Ansible

---

assets/queries/ansible/gcp/stackdriver_monitoring_is_disabled/metadata.json
assets/queries/ansible/gcp/stackdriver_monitoring_is_disabled/query.rego
assets/queries/ansible/gcp/stackdriver_monitoring_is_disabled/test/negative.yaml
assets/queries/ansible/gcp/stackdriver_monitoring_is_disabled/test/positive.yaml
assets/queries/ansible/gcp/stackdriver_monitoring_is_disabled/test/positive_expected_result.json

Adding Stackdriver Monitoring Is Disabled query for Ansible, that checks if the attribute 'monitoring_service' is defined and different than 'none'.
Closes #1286

Add Stackdriver Monitoring Is Disabled query for Ansible

---

assets/queries/ansible/gcp/network_policy_is_disabled/metadata.json
assets/queries/ansible/gcp/network_policy_is_disabled/query.rego
assets/queries/ansible/gcp/network_policy_is_disabled/test/negative.yaml
assets/queries/ansible/gcp/network_policy_is_disabled/test/positive.yaml
assets/queries/ansible/gcp/network_policy_is_disabled/test/positive_expected_result.json

Adding Network Policy is Disabled query for Ansible, that checks if the attribute 'network_policy.enabled' is true and the attribute 'addons_config.network_policy_config.disabled' is false.
Closes #1280

Add Network Policy is Disabled query for Ansible

---

assets/queries/ansible/gcp/object_versioning_not_enabled/metadata.json
assets/queries/ansible/gcp/object_versioning_not_enabled/query.rego
assets/queries/ansible/gcp/object_versioning_not_enabled/test/negative.yaml
assets/queries/ansible/gcp/object_versioning_not_enabled/test/positive.yaml
assets/queries/ansible/gcp/object_versioning_not_enabled/test/positive_expected_result.json

Closes #1262 
This query ensures that object versioning is enabled on a Google Storage Bucket by checking if the 'versioning' block exists within the 'google_storage_bucket' resource and with the 'enabled' field equal to 'true'.

Add object_versioning_not_enabled query for Ansible #1262

---

assets/queries/ansible/gcp/cloud_dns_without_dnnsec/metadata.json
assets/queries/ansible/gcp/cloud_dns_without_dnnsec/query.rego
assets/queries/ansible/gcp/cloud_dns_without_dnnsec/test/negative.yaml
assets/queries/ansible/gcp/cloud_dns_without_dnnsec/test/positive.yaml
assets/queries/ansible/gcp/cloud_dns_without_dnnsec/test/positive_expected_result.json
assets/queries/terraform/gcp/cloud_dns_without_dnssec/metadata.json

Closes #1269 
DNSSEC must be enabled for Cloud DNS.
Also, updated the name of the query in terraform

Add cloud_dns_without_dnssec query for Ansible #1269

---

assets/queries/dockerfile/apt-get_without_yes_flag/metadata.json
assets/queries/dockerfile/apt-get_without_yes_flag/query.rego
assets/queries/dockerfile/apt-get_without_yes_flag/test/negative.dockerfile
assets/queries/dockerfile/apt-get_without_yes_flag/test/positive.dockerfile
assets/queries/dockerfile/apt-get_without_yes_flag/test/positive_expected_result.json

Check if any apt-get call does not use "-y" flag to avoid manual user input. Closes #1059

Add query to check if apt-get is called without yes flag. Closes #1059

---

assets/queries/dockerfile/apt-get_without_no_recommends_flag/metadata.json
assets/queries/dockerfile/apt-get_without_no_recommends_flag/query.rego
assets/queries/dockerfile/apt-get_without_no_recommends_flag/test/negative.dockerfile
assets/queries/dockerfile/apt-get_without_no_recommends_flag/test/positive.dockerfile
assets/queries/dockerfile/apt-get_without_no_recommends_flag/test/positive_expected_result.json

Check if any apt-get install commands use no install recommendations to avoid installing additional packages. Closes #1064

Add query to check if apt-get not installing additional packages. Closes #1064

---

assets/queries/ansible/azure/security_group_is_not_configured/metadata.json
assets/queries/ansible/azure/security_group_is_not_configured/query.rego
assets/queries/ansible/azure/security_group_is_not_configured/test/negative.yaml
assets/queries/ansible/azure/security_group_is_not_configured/test/positive.yaml
assets/queries/ansible/azure/security_group_is_not_configured/test/positive_expected_result.json

Adding Security Group is Not Configured query for Ansible, that checks if the attribute 'security_group' is defined and not empty.
Closes #1462

Add Security Group is Not Configured query for Ansible

---

assets/queries/ansible/azure/default_network_access_allowed/metadata.json
assets/queries/ansible/azure/default_network_access_allowed/query.rego
assets/queries/ansible/azure/default_network_access_allowed/test/negative.yaml
assets/queries/ansible/azure/default_network_access_allowed/test/positive.yaml
assets/queries/ansible/azure/default_network_access_allowed/test/positive_expected_result.json

Adding Default Network Access is Allowed query for Ansible, that checks if the attribute 'default_action' is 'Deny'.
Closes #1467

Add Default Network Access is Allowed query for Ansible

---

assets/queries/ansible/aws/instance_with_no_vpc/metadata.json
assets/queries/ansible/aws/instance_with_no_vpc/query.rego
assets/queries/ansible/aws/instance_with_no_vpc/test/negative.yaml
assets/queries/ansible/aws/instance_with_no_vpc/test/positive.yaml
assets/queries/ansible/aws/instance_with_no_vpc/test/positive_expected_result.json
assets/queries/terraform/aws/instance_with_no_vpc/test/positive_expected_result.json

For this query, it is necessary to check if 'vpc_subnet_id' exists in modules community.aws.ec2_instance and amazon.aws.ec2, when they are defined
Closes #1194

Add instance_with_no_vpc Closes #1194

---

assets/queries/ansible/aws/sqs_with_sse_disabled/metadata.json
assets/queries/ansible/aws/sqs_with_sse_disabled/query.rego
assets/queries/ansible/aws/sqs_with_sse_disabled/test/negative.yaml
assets/queries/ansible/aws/sqs_with_sse_disabled/test/positive.yaml
assets/queries/ansible/aws/sqs_with_sse_disabled/test/positive_expected_result.json

Closes #1504 
Amazon Simple Queue Service (SQS) queue is not protecting the contents of their messages using Server-Side Encryption (SSE)
Checks if 'kms_master_key_id' is undefined in a 'community.aws.sqs_queue' resource

Add sqs_with_sse_disabled query for Ansible #1504

---

assets/queries/ansible/gcp/using_default_service_account/metadata.json
assets/queries/ansible/gcp/using_default_service_account/query.rego
assets/queries/ansible/gcp/using_default_service_account/test/negative.yaml
assets/queries/ansible/gcp/using_default_service_account/test/positive.yaml
assets/queries/ansible/gcp/using_default_service_account/test/positive_expected_result.json

Adding Using Default Service Account query for Ansible, that checks if the attribute 'service_account_email' is defined. Additionally, it must not be empty and must also not be a default Google Compute Engine service account.
Closes #1508

Add Using Default Service Account query for Ansible

---

assets/queries/ansible/azure/sql_server_accessibility_is_not_minimal/metadata.json
assets/queries/ansible/azure/sql_server_accessibility_is_not_minimal/query.rego
assets/queries/ansible/azure/sql_server_accessibility_is_not_minimal/test/negative.yaml
assets/queries/ansible/azure/sql_server_accessibility_is_not_minimal/test/positive.yaml
assets/queries/ansible/azure/sql_server_accessibility_is_not_minimal/test/positive_expected_result.json

Adding SQL Server Accessibility Is Not Minimal query for Ansible, that checks if the difference between the values of the 'end_ip_address' and 'start_ip_address' is lesser than 256. Additionally, both ips must be different from '0.0.0.0'.
Closes #1497

Add SQL Server Accessibility Is Not Minimal query for Ansible

---

assets/queries/ansible/aws/ami_shared_to_multiple_accounts/metadata.json
assets/queries/ansible/aws/ami_shared_to_multiple_accounts/query.rego
assets/queries/ansible/aws/ami_shared_to_multiple_accounts/test/negative.yaml
assets/queries/ansible/aws/ami_shared_to_multiple_accounts/test/positive.yaml
assets/queries/ansible/aws/ami_shared_to_multiple_accounts/test/positive_expected_result.json

For this query, it is necessary to check the attribute 'launch_permissions', which has to be set to just one user
Closes #1483

Add ami_shared_to_multiple_accounts Closes #1483

---

assets/queries/ansible/gcp/sql_database_backup_configuration_disabled/metadata.json
assets/queries/ansible/gcp/sql_database_backup_configuration_disabled/query.rego
assets/queries/ansible/gcp/sql_database_backup_configuration_disabled/test/negative.yaml
assets/queries/ansible/gcp/sql_database_backup_configuration_disabled/test/positive.yaml
assets/queries/ansible/gcp/sql_database_backup_configuration_disabled/test/positive_expected_result.json

Closes #1268 
This query detects Cloud SQL Database instances with backup_configuration disabled. Checks if, within the 'settings' block, the 'backup_configuration' block exists with the 'enable' field equal to 'false'.

Add sql_database_backup_configuration_disabled query for Ansible #1268

---

assets/queries/ansible/gcp/master_authentication_is_disabled/metadata.json
assets/queries/ansible/gcp/master_authentication_is_disabled/query.rego
assets/queries/ansible/gcp/master_authentication_is_disabled/test/negative.yaml
assets/queries/ansible/gcp/master_authentication_is_disabled/test/positive.yaml
assets/queries/ansible/gcp/master_authentication_is_disabled/test/positive_expected_result.json

Adding Master Authentication is Disabled query for Ansible, that checks if the attribute 'master_auth' has the subattributes 'username' and 'password' defined and not empty.
Closes #1232

Add Master Authentication is Disabled query for Ansible

---

assets/queries/cloudFormation/filter_and_alarm_exist_for_unauthorized_api_calls/metadata.json
assets/queries/cloudFormation/filter_and_alarm_exist_for_unauthorized_api_calls/query.rego
assets/queries/cloudFormation/filter_and_alarm_exist_for_unauthorized_api_calls/test/negative.yaml
assets/queries/cloudFormation/filter_and_alarm_exist_for_unauthorized_api_calls/test/positive.yaml
assets/queries/cloudFormation/filter_and_alarm_exist_for_unauthorized_api_calls/test/positive_expected_result.json

Provide a CloudFormation resource and a resource to ensure that Unauthorized API Calls are catched by a log metric filter and an alarm 
Closes #1145

Add Filter&alarm !Exists For Unauthorized API

---

assets/queries/ansible/azure/sql_server_predictable_active_directory_admin_account_name/metadata.json
assets/queries/ansible/azure/sql_server_predictable_active_directory_admin_account_name/query.rego
assets/queries/ansible/azure/sql_server_predictable_active_directory_admin_account_name/test/negative.yaml
assets/queries/ansible/azure/sql_server_predictable_active_directory_admin_account_name/test/positive.yaml
assets/queries/ansible/azure/sql_server_predictable_active_directory_admin_account_name/test/positive_expected_result.json

Adding SQL Server Predictable Active Directory Account Name query for Ansible, that checks if the attribute 'ad_user' is set to a name that is easy to predict.
Closes #1567

Add SQL Server Predictable Active Directory Account Name query for Ansible

---

assets/queries/ansible/aws/root_account_has_associated_active_access_keys/metadata.json
assets/queries/ansible/aws/root_account_has_associated_active_access_keys/query.rego
assets/queries/ansible/aws/root_account_has_associated_active_access_keys/test/negative.yaml
assets/queries/ansible/aws/root_account_has_associated_active_access_keys/test/positive.yaml
assets/queries/ansible/aws/root_account_has_associated_active_access_keys/test/positive_expected_result.json

Adding Root Account Has Associated Active Access Keys query for Ansible, because the AWS Root Account must not have active access keys associated.
Closes #1559

Add Root Account Has Associated Active Access Keys query for Ansible

---

assets/queries/ansible/aws/ecs_service_admin_role_present/metadata.json
assets/queries/ansible/aws/ecs_service_admin_role_present/query.rego
assets/queries/ansible/aws/ecs_service_admin_role_present/test/negative.yaml
assets/queries/ansible/aws/ecs_service_admin_role_present/test/positive.yaml
assets/queries/ansible/aws/ecs_service_admin_role_present/test/positive_expected_result.json

Adding ECS Service Admin Role Is Present query for Ansible, that checks if the attribute 'role' is an admin role.
Closes #1563

Add ECS Service Admin Role Is Present query for Ansible

---

assets/queries/cloudFormation/accessKey_not_rotated_within_90_days/metadata.json
assets/queries/cloudFormation/accessKey_not_rotated_within_90_days/query.rego
assets/queries/cloudFormation/accessKey_not_rotated_within_90_days/test/negative.yaml
assets/queries/cloudFormation/accessKey_not_rotated_within_90_days/test/positive.yaml
assets/queries/cloudFormation/accessKey_not_rotated_within_90_days/test/positive_expected_result.json

Check if there is not a ConfigRule that enforces AccessKeys to be rotated within 90 days. Closes #934

Add query to check if Access Keys are not being rotated within 90 days. Closes #934

---

assets/queries/ansible/aws/cloudwatch_retention_period/metadata.json
assets/queries/ansible/aws/cloudwatch_retention_period/query.rego
assets/queries/ansible/aws/cloudwatch_retention_period/test/negative.yaml
assets/queries/ansible/aws/cloudwatch_retention_period/test/positive.yaml
assets/queries/ansible/aws/cloudwatch_retention_period/test/positive_expected_result.json

AWS CloudWatch should have CloudWatch Logs enabled to monitor, store, and access log events. For that, we can specify the value of logs retention through the attribute 'retention'. This attribute should be defined and set to one of the following values: 1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653.
For this query, I thought in two cases:
Attribute 'retention_in_days' is undefined
Attribute 'retention_in_days' is set but not to a valid value
(P.S. I just found the module community to satisfy this query)
Closes #1236

Add cloudwatch_retention_period Closes #1236

---

assets/queries/ansible/azure/sql_server_predictable_admin_account_name/metadata.json
assets/queries/ansible/azure/sql_server_predictable_admin_account_name/query.rego
assets/queries/ansible/azure/sql_server_predictable_admin_account_name/test/negative.yaml
assets/queries/ansible/azure/sql_server_predictable_admin_account_name/test/positive.yaml
assets/queries/ansible/azure/sql_server_predictable_admin_account_name/test/positive_expected_result.json

Adding SQL Server Predictable Admin Account Name query for Ansible, that checks if the attribute 'admin_username' is set to a name that is easy to predict.
Closes #1473

Add SQL Server Predictable Admin Account Name query for Ansible

---

assets/queries/ansible/aws/no_password_policy_enabled/metadata.json
assets/queries/ansible/aws/no_password_policy_enabled/query.rego
assets/queries/ansible/aws/no_password_policy_enabled/test/negative.yaml
assets/queries/ansible/aws/no_password_policy_enabled/test/positive.yaml
assets/queries/ansible/aws/no_password_policy_enabled/test/positive_expected_result.json

For this query, it is necessary to check if module 'community.aws.iam_password_policy' or 'iam_password_policy' is set. So, if both are not set, no password policy is enabled.
I added other attributes verification like 'require_lowercase', 'require_numbers',' require_symbols ", and 'require_uppercase' because there is no query for that check, as far as I see
Closes #1472

 Add no_password_policy_enabled query Closes #1472

---

assets/queries/ansible/gcp/vm_csek_encryption_is_disabled/metadata.json
assets/queries/ansible/gcp/vm_csek_encryption_is_disabled/query.rego
assets/queries/ansible/gcp/vm_csek_encryption_is_disabled/test/negative.yaml
assets/queries/ansible/gcp/vm_csek_encryption_is_disabled/test/positive.yaml
assets/queries/ansible/gcp/vm_csek_encryption_is_disabled/test/positive_expected_result.json

Adding VM CSEK Encryption is Disabled query for Ansible, that checks if the attribute 'disk_encryption_key' is defined and its sub attribute 'raw_key' is also defined and not empty.
Closes #1455

Add VM CSEK Encryption is Disabled query for Ansible

---

assets/queries/ansible/azure/trusted_microsoft_services_not_enabled/metadata.json
assets/queries/ansible/azure/trusted_microsoft_services_not_enabled/query.rego
assets/queries/ansible/azure/trusted_microsoft_services_not_enabled/test/negative.yaml
assets/queries/ansible/azure/trusted_microsoft_services_not_enabled/test/positive.yaml
assets/queries/ansible/azure/trusted_microsoft_services_not_enabled/test/positive_expected_result.json

This query evaluates if 'Trusted Microsoft Services' is disabled for Storage Account access, by checking if the field `bypass` doesn't contain the value `AzureServices`, or it is set to `""`.
Closes #1570

Add trusted_microsoft_services_not_enabled query for Ansible

---

assets/queries/ansible/aws/cloudfront_without_waf/metadata.json
assets/queries/ansible/aws/cloudfront_without_waf/query.rego
assets/queries/ansible/aws/cloudfront_without_waf/test/negative.yaml
assets/queries/ansible/aws/cloudfront_without_waf/test/positive.yaml
assets/queries/ansible/aws/cloudfront_without_waf/test/positive_expected_result.json

Provide a aws.cloudfront_distribution resource and a resource to manage the web_acl_id
Closes #1514

Add Cloudfront without WAF query

---

assets/queries/ansible/gcp/kms_rotation_period_higher_365_days/metadata.json
assets/queries/ansible/gcp/kms_rotation_period_higher_365_days/query.rego
assets/queries/ansible/gcp/kms_rotation_period_higher_365_days/test/negative.yaml
assets/queries/ansible/gcp/kms_rotation_period_higher_365_days/test/positive.yaml
assets/queries/ansible/gcp/kms_rotation_period_higher_365_days/test/positive_expected_result.json

Check GCP KMS keys rotation period to ensure that none is higher than 3153600 seconds (365 days). Closes #1207

Add query to check kms rotation period surpasses 365 days. Closes #1207

---

assets/queries/ansible/aws/cloudwatch_without_retention_days/metadata.json
assets/queries/ansible/aws/cloudwatch_without_retention_days/query.rego
assets/queries/ansible/aws/cloudwatch_without_retention_days/test/negative.yaml
assets/queries/ansible/aws/cloudwatch_without_retention_days/test/positive.yaml
assets/queries/ansible/aws/cloudwatch_without_retention_days/test/positive_expected_result.json

Provide a aws.cloudfront_distribution resource and a resource to manage the web_acl_id
Closes #1517

Add Cloudwatch without retention days query

---

assets/queries/ansible/aws/redis_not_compliant/metadata.json
assets/queries/ansible/aws/redis_not_compliant/query.rego
assets/queries/ansible/aws/redis_not_compliant/test/negative.yaml
assets/queries/ansible/aws/redis_not_compliant/test/positive.yaml
assets/queries/ansible/aws/redis_not_compliant/test/positive_expected_result.json

Closes #1569 
Checks if the Redis version is compliant with the necessary AWS PCI DSS requirements

Add redis_not_compliant query Closes #1569

---

assets/queries/ansible/azure/public_storage_account/metadata.json
assets/queries/ansible/azure/public_storage_account/query.rego
assets/queries/ansible/azure/public_storage_account/test/negative.yaml
assets/queries/ansible/azure/public_storage_account/test/positive.yaml
assets/queries/ansible/azure/public_storage_account/test/positive_expected_result.json

The default network access rule for Storage Accounts should not be open to public.
This query evaluates if parameter `default_action`  from `azure_rm_storageaccount`  module is set to `Allow`, or if it's set to `Deny` and `ip_rules` contains the value `0.0.0.0/0`.
Closes #1561

Add public_storage_account query for Ansible

---

assets/queries/k8s/deployment_without_poddisruptionbudget/metadata.json
assets/queries/k8s/deployment_without_poddisruptionbudget/query.rego
assets/queries/k8s/deployment_without_poddisruptionbudget/test/negative.yaml
assets/queries/k8s/deployment_without_poddisruptionbudget/test/positive.yaml
assets/queries/k8s/deployment_without_poddisruptionbudget/test/positive_expected_result.json

Deployments should be targeted by PodDisruptionBudgets, which limit the number of Pods of a replicated application that can be taken offline at any given time.
This query evaluates if the `matchLabels` applied to Pods in a `Deployment` are referenced in the `matchLabels` of any `PodDisruptionBudget`.
Closes #634
Closes #1606

Add deployment_without_poddisruptionbudget query for Kubernetes

---

assets/queries/k8s/statefulset_without_poddisruptionbudget/metadata.json
assets/queries/k8s/statefulset_without_poddisruptionbudget/query.rego
assets/queries/k8s/statefulset_without_poddisruptionbudget/test/negative.yaml
assets/queries/k8s/statefulset_without_poddisruptionbudget/test/positive.yaml
assets/queries/k8s/statefulset_without_poddisruptionbudget/test/positive_expected_result.json

StatefulSets should be targeted by PodDisruptionBudgets, which limit the number of Pods of a replicated application that can be taken offline at any given time.
This query evaluates if the `matchLabels` applied to pods in a `Statefulset` are referenced in the `matchLabels` of any `PodDisruptionBudget` .
Closes #633
Closes #1602

Add statefulset_without_poddisruptionbudget query for Kubernetes

---

assets/queries/dockerfile/update_instruction_alone/metadata.json
assets/queries/dockerfile/update_instruction_alone/query.rego
assets/queries/dockerfile/update_instruction_alone/test/negative.dockerfile
assets/queries/dockerfile/update_instruction_alone/test/positive.dockerfile
assets/queries/dockerfile/update_instruction_alone/test/positive_expected_result.json

`RUN <package-manager> update`  should always be combined with `<package-manager> install` in the same `RUN` statement. Using `<package-manager> update` alone in a `RUN` statement causes caching issues and subsequent `<package-manager> install` instructions fails.
Closes #518

Add update_instruction_alone query for Docker

---

assets/queries/ansible/azure/blob_container_with_public_access/metadata.json
assets/queries/ansible/azure/blob_container_with_public_access/query.rego
assets/queries/ansible/azure/blob_container_with_public_access/test/negative.yaml
assets/queries/ansible/azure/blob_container_with_public_access/test/positive.yaml
assets/queries/ansible/azure/blob_container_with_public_access/test/positive_expected_result.json

By default, containers are private, so this query evaluates if parameter `public_access` from the `azure_rm_storageblob` module is set to `blob` or `container` . Closes #1557

Add blob_container_with_public_access query for Ansible

---

assets/queries/dockerfile/missing_user_instruction/metadata.json
assets/queries/dockerfile/missing_user_instruction/query.rego
assets/queries/dockerfile/missing_user_instruction/test/negative.dockerfile
assets/queries/dockerfile/missing_user_instruction/test/positive.dockerfile
assets/queries/dockerfile/missing_user_instruction/test/positive_expected_result.json

This query verifies if there's any `USER` instruction stated in a `dockerfile`.
Closes #1613
Closes #467

Add missing_user_instruction query for Docker

---

assets/queries/ansible/aws/config_configuration_aggregator_all_regions_not_enabled/metadata.json
assets/queries/ansible/aws/config_configuration_aggregator_all_regions_not_enabled/query.rego
assets/queries/ansible/aws/config_configuration_aggregator_all_regions_not_enabled/test/negative.yaml
assets/queries/ansible/aws/config_configuration_aggregator_all_regions_not_enabled/test/positive.yaml
assets/queries/ansible/aws/config_configuration_aggregator_all_regions_not_enabled/test/positive_expected_result.json

Added new query for Ansible
Provide a aws_config_aggregator resource and a resource to manage all_aws_regions
Closes #1550

Add AWS Config Agg All Regions Not Enabled query

---

assets/queries/ansible/gcp/google_compute_ssl_policy/metadata.json
assets/queries/ansible/gcp/google_compute_ssl_policy/query.rego
assets/queries/ansible/gcp/google_compute_ssl_policy/test/negative.yaml
assets/queries/ansible/gcp/google_compute_ssl_policy/test/positive.yaml
assets/queries/ansible/gcp/google_compute_ssl_policy/test/positive_expected_result.json

This query confirms if Google Compute SSL Policy Weak Chyper Suits is Enabled, to do so we need to check if TLS is TLS_1_2, because other version have Weak Chypers #1453

Add Google Compute SSL Policy Weak Cipher Suits is Enabled query for Ansible #1453

---

assets/queries/ansible/aws/cloudfront_configuration_allow_http/metadata.json
assets/queries/ansible/aws/cloudfront_configuration_allow_http/query.rego
assets/queries/ansible/aws/cloudfront_configuration_allow_http/test/negative.yaml
assets/queries/ansible/aws/cloudfront_configuration_allow_http/test/positive.yaml
assets/queries/ansible/aws/cloudfront_configuration_allow_http/test/positive_expected_result.json

Provide a aws.cloudfront_distribution resource and a resource to manage the viewer_protocol_policy
Closes #1506

Cloudfront configuration allow http

---

assets/queries/ansible/azure/redis_firewall_allows_too_many_users/metadata.json
assets/queries/ansible/azure/redis_firewall_allows_too_many_users/query.rego
assets/queries/ansible/azure/redis_firewall_allows_too_many_users/test/negative.yaml
assets/queries/ansible/azure/redis_firewall_allows_too_many_users/test/positive.yaml
assets/queries/ansible/azure/redis_firewall_allows_too_many_users/test/positive_expected_result.json

Check firewall rules for Redis Cache if more than 255 hosts are allowed by it. Closes #1394

Add query to check if redis cache firewall rule allows too many hosts. Closes #1394

---

assets/queries/ansible/gcp/cluster_labels_are_disabled/metadata.json
assets/queries/ansible/gcp/cluster_labels_are_disabled/query.rego
assets/queries/ansible/gcp/cluster_labels_are_disabled/test/negative.yaml
assets/queries/ansible/gcp/cluster_labels_are_disabled/test/positive.yaml
assets/queries/ansible/gcp/cluster_labels_are_disabled/test/positive_expected_result.json

Adding Cluster Labels are Disabled for Ansible, that checks if the attribute 'resource_labels' is defined.
Closes  #1219

Add Cluster Labels are Disabled for Ansible

---

assets/queries/ansible/aws/cloudtrail_log_files_not_encrypted_with_kms/metadata.json
assets/queries/ansible/aws/cloudtrail_log_files_not_encrypted_with_kms/query.rego
assets/queries/ansible/aws/cloudtrail_log_files_not_encrypted_with_kms/test/negative.yaml
assets/queries/ansible/aws/cloudtrail_log_files_not_encrypted_with_kms/test/positive.yaml
assets/queries/ansible/aws/cloudtrail_log_files_not_encrypted_with_kms/test/positive_expected_result.json

According to the documentation, "By default, the log files delivered by CloudTrail to your bucket are encrypted by Amazon server-side encryption with Amazon S3-managed encryption keys (SSE-S3). To provide a security layer that is directly manageable, you can instead use server-side encryption with AWS KMS–managed keys (SSE-KMS) for your CloudTrail log files."
So, for this query, it is necessary to check if attribute 'kms_key_id' exists.
Closes #1661

Add cloudtrail_log_files_not_encrypted_with_kms query Closes #1661

---

assets/queries/ansible/aws/s3_bucket_allows_get_action_from_all_principals/metadata.json
assets/queries/ansible/aws/s3_bucket_allows_get_action_from_all_principals/query.rego
assets/queries/ansible/aws/s3_bucket_allows_get_action_from_all_principals/test/negative.yaml
assets/queries/ansible/aws/s3_bucket_allows_get_action_from_all_principals/test/positive.yaml
assets/queries/ansible/aws/s3_bucket_allows_get_action_from_all_principals/test/positive_expected_result.json

Adding S3 Bucket Allows Get Action From All Principals query for Ansible, as to prevent leaking private information to the entire internet or allow unauthorized data tampering / deletion.
Closes #1538

Add S3 Bucket Allows Get Action From All Principals query for Ansible

---

assets/queries/ansible/aws/s3_bucket_allows_delete_action_from_all_principals/metadata.json
assets/queries/ansible/aws/s3_bucket_allows_delete_action_from_all_principals/query.rego
assets/queries/ansible/aws/s3_bucket_allows_delete_action_from_all_principals/test/negative.yaml
assets/queries/ansible/aws/s3_bucket_allows_delete_action_from_all_principals/test/positive.yaml
assets/queries/ansible/aws/s3_bucket_allows_delete_action_from_all_principals/test/positive_expected_result.json

Adding S3 Bucket Allows Delete Action From All Principals query for Ansible, as to prevent leaking private information to the entire internet or allow unauthorized data tampering / deletion.
Closes #1545

Add S3 Bucket Allows Delete Action From All Principals query for Ansible

---

assets/queries/ansible/aws/s3_bucket_allows_put_action_from_all_principals/metadata.json
assets/queries/ansible/aws/s3_bucket_allows_put_action_from_all_principals/query.rego
assets/queries/ansible/aws/s3_bucket_allows_put_action_from_all_principals/test/negative.yaml
assets/queries/ansible/aws/s3_bucket_allows_put_action_from_all_principals/test/positive.yaml
assets/queries/ansible/aws/s3_bucket_allows_put_action_from_all_principals/test/positive_expected_result.json

Adding S3 Bucket Allows Put Action From All Principals query for Ansible, as to prevent leaking private information to the entire internet or allow unauthorized data tampering / deletion.
Closes #1542

Add S3 Bucket Allows Put Action From All Principals query for Ansible

---

assets/queries/ansible/aws/s3_bucket_allows_list_action_from_all_principals/metadata.json
assets/queries/ansible/aws/s3_bucket_allows_list_action_from_all_principals/query.rego
assets/queries/ansible/aws/s3_bucket_allows_list_action_from_all_principals/test/negative.yaml
assets/queries/ansible/aws/s3_bucket_allows_list_action_from_all_principals/test/positive.yaml
assets/queries/ansible/aws/s3_bucket_allows_list_action_from_all_principals/test/positive_expected_result.json

Adding S3 Bucket Allows List Action From All Principals query for Ansible, as to prevent leaking private information to the entire internet or allow unauthorized data tampering / deletion.
Closes #1540

Add S3 Bucket Allows List Action From All Principals query for Ansible

---

assets/queries/ansible/aws/s3_bucket_with_any_principal/metadata.json
assets/queries/ansible/aws/s3_bucket_with_any_principal/query.rego
assets/queries/ansible/aws/s3_bucket_with_any_principal/test/negative.yaml
assets/queries/ansible/aws/s3_bucket_with_any_principal/test/positive.yaml
assets/queries/ansible/aws/s3_bucket_with_any_principal/test/positive_expected_result.json

Adding S3 Bucket With Any Principal query for Ansible, as to prevent leaking private information to the entire internet or allow unauthorized data tampering / deletion.
Closes #1555

Add S3 Bucket With Any Principal query for Ansible

---

assets/queries/ansible/aws/lambda_without_xray_tracing/metadata.json
assets/queries/ansible/aws/lambda_without_xray_tracing/query.rego
assets/queries/ansible/aws/lambda_without_xray_tracing/test/negative.yaml
assets/queries/ansible/aws/lambda_without_xray_tracing/test/positive.yaml
assets/queries/ansible/aws/lambda_without_xray_tracing/test/positive_expected_result.json

According to the documentation about attribute 'tracing_mode', "set mode to 'Active' to sample and trace incoming requests with AWS X-Ray. Turned off (set to 'PassThrough') by default".
So, for this query, it is necessary to check if attribute 'tracing_mode' exists. Furthermore, if when exits, is not set to 'Active' 
Closes #1686

Add lambda_without_xray_tracing query Closes #1686

---

assets/queries/ansible/aws/ecr_image_tag_not_immutable/metadata.json
assets/queries/ansible/aws/ecr_image_tag_not_immutable/query.rego
assets/queries/ansible/aws/ecr_image_tag_not_immutable/test/negative.yaml
assets/queries/ansible/aws/ecr_image_tag_not_immutable/test/positive.yaml
assets/queries/ansible/aws/ecr_image_tag_not_immutable/test/positive_expected_result.json

For this query, it is necessary to check if the attribute 'image_tag_mutability' is not set to 'immutable'
Closes #1700

Add ecr_image_tag_mutable query Closes #1700

---

assets/queries/cloudFormation/accessKey_not_rotated_within_90_days/query.rego

The query had a bad searchKey and triggered incorrect results in many other queries from other providers. Now it's fixed and is working properly.

Fixed issue with query that triggered incorrect responses

---

assets/queries/ansible/gcp/gke_master_authorized_networks_disabled/metadata.json
assets/queries/ansible/gcp/gke_master_authorized_networks_disabled/query.rego
assets/queries/ansible/gcp/gke_master_authorized_networks_disabled/test/negative.yaml
assets/queries/ansible/gcp/gke_master_authorized_networks_disabled/test/positive.yaml
assets/queries/ansible/gcp/gke_master_authorized_networks_disabled/test/positive_expected_result.json

Closes #1739 
Master authorized networks must be enabled in GKE clusters

Add gke_master_authorized_networks_disabled query for Ansible #1739

---

assets/queries/ansible/azure/web_app_accepts_http_traffic/metadata.json
assets/queries/ansible/azure/web_app_accepts_http_traffic/query.rego
assets/queries/ansible/azure/web_app_accepts_http_traffic/test/negative.yaml
assets/queries/ansible/azure/web_app_accepts_http_traffic/test/positive.yaml
assets/queries/ansible/azure/web_app_accepts_http_traffic/test/positive_expected_result.json

Web app should only accept HTTPS traffic in Azure Web App Service.
This query verifies if attribute `https_only` from the `azure_rm_webapp` module is set. If so, it should be either `true` or `yes`.
Closes #1734

Add web_app_accepts_http_traffic query for Ansible

---

assets/queries/ansible/aws/ec2_instance_has_public_ip/metadata.json
assets/queries/ansible/aws/ec2_instance_has_public_ip/query.rego
assets/queries/ansible/aws/ec2_instance_has_public_ip/test/negative.yaml
assets/queries/ansible/aws/ec2_instance_has_public_ip/test/positive.yaml
assets/queries/ansible/aws/ec2_instance_has_public_ip/test/positive_expected_result.json

An EC2 Instance should not have a public IP address.
This query makes three verifications:
1) if `assign_public_ip` from `amazon.aws.ec2` resource is set
2) if `network_interfaces.associate_public_ip_address` from `community.aws.ec2_launch_template` resource is set 
3) if `network.assign_public_ip` from `community.aws.ec2_instance` resource is set
Since there's no reference to default values in the documentation, I assumed that if the parameter was undefined there would be no public IP address associated to the instance.                   
Closes #1726

Add ec2_instance_has_public_ip query for Ansible

---

assets/queries/cloudFormation/ec2_network_acl_duplicate_rule/metadata.json
assets/queries/cloudFormation/ec2_network_acl_duplicate_rule/query.rego
assets/queries/cloudFormation/ec2_network_acl_duplicate_rule/test/negative.yaml
assets/queries/cloudFormation/ec2_network_acl_duplicate_rule/test/positive.yaml
assets/queries/cloudFormation/ec2_network_acl_duplicate_rule/test/positive_expected_result.json

Closes #1693 
A Network ACL's rule numbers cannot be repeated unless one is egress and the other is ingress

Add ec2_network_acl_duplicate_rule query for AWS CloudFormation #1693

---

assets/queries/cloudFormation/ec2_public_instance_exposed_through_subnet/metadata.json
assets/queries/cloudFormation/ec2_public_instance_exposed_through_subnet/query.rego
assets/queries/cloudFormation/ec2_public_instance_exposed_through_subnet/test/negative.yaml
assets/queries/cloudFormation/ec2_public_instance_exposed_through_subnet/test/positive.yaml
assets/queries/cloudFormation/ec2_public_instance_exposed_through_subnet/test/positive_expected_result.json

EC2 instances with public IP that permit unrestricted internet traffic to their subnets are vulnerable to breaches and various attacks.
This query begins by verifying if there's a public IP Address associated to the instance, by checking in the list of `NetworkInterfaces`  the value of `AssociatePublicIpAddress` attribute. 
If `true`, it evaluates if the subnet referenced under the `SubnetId` attribute has a route table associated, with a route with `DestinationCidrBlock`  == 0.0.0.0/0,  or `DestinationIpv6CidrBlock` == ::/0. 
Closes #1699

Add ec2_public_instance_exposed_through_subnet query for AWS CloudFormation

---

sonar-project.properties

Configure Sonar using sonar-project.properties file to find the test files and properly calculate coverage.
Currently Sonar is flagging tests as "Lines to cover":
Closes #1746

Configure Sonar to include go unit tests

---

assets/queries/ansible/aws/s3_bucket_allows_writeACP_action_from_all_principals/metadata.json
assets/queries/ansible/aws/s3_bucket_allows_writeACP_action_from_all_principals/query.rego
assets/queries/ansible/aws/s3_bucket_allows_writeACP_action_from_all_principals/test/negative.yaml
assets/queries/ansible/aws/s3_bucket_allows_writeACP_action_from_all_principals/test/positive.yaml
assets/queries/ansible/aws/s3_bucket_allows_writeACP_action_from_all_principals/test/positive_expected_result.json

Adding S3 Bucket Allows WriteACP Action From All Principals query for Ansible, that checks if the 'Effect' is'Allow' when the 'Action' is Write_ACP, for all Principals.
Closes #1691

Add S3 Bucket Allows WriteACP Action From All Principals query for Ansible

---

assets/queries/ansible/gcp/cloud_sql_instance_with_contained_database_authentication_on/metadata.json
assets/queries/ansible/gcp/cloud_sql_instance_with_contained_database_authentication_on/query.rego
assets/queries/ansible/gcp/cloud_sql_instance_with_contained_database_authentication_on/test/negative.yaml
assets/queries/ansible/gcp/cloud_sql_instance_with_contained_database_authentication_on/test/positive.yaml
assets/queries/ansible/gcp/cloud_sql_instance_with_contained_database_authentication_on/test/positive_expected_result.json

GCP SQL Instance should not have Contained Database Authentication On
Closes #1708

Add CSQL W/Contained DB Auth On query #1708

---

assets/queries/terraform/aws/msk_cluster_logging_enabled/metadata.json
assets/queries/terraform/aws/msk_cluster_logging_enabled/query.rego
assets/queries/terraform/aws/msk_cluster_logging_enabled/test/negative.tf
assets/queries/terraform/aws/msk_cluster_logging_enabled/test/positive.tf
assets/queries/terraform/aws/msk_cluster_logging_enabled/test/positive_expected_result.json

MSK cluster instances should have logging enabled. This query verifies if logging_info and broker_logs are defined and if the instances inside broker_logs have enabled defined and set true
Closes #1744

Add msk_cluster_logging_enabled query for terraform (#1744)

---

assets/queries/ansible/gcp/compute_instance_is_publicly_accessible/metadata.json
assets/queries/ansible/gcp/compute_instance_is_publicly_accessible/query.rego
assets/queries/ansible/gcp/compute_instance_is_publicly_accessible/test/negative.yaml
assets/queries/ansible/gcp/compute_instance_is_publicly_accessible/test/positive.yaml
assets/queries/ansible/gcp/compute_instance_is_publicly_accessible/test/positive_expected_result.json

Compute instances shouldn't have access configurations set, i.e. IPs via which the instances can be accessed via the Internet.
This query verifies if the attribute `access_configs` is defined.
Closes #1742

Add compute_instance_is_publicly_accessible query for Ansible

---

assets/queries/ansible/gcp/postgresql_log_checkpoints_flag_not_set_to_on/metadata.json
assets/queries/ansible/gcp/postgresql_log_checkpoints_flag_not_set_to_on/query.rego
assets/queries/ansible/gcp/postgresql_log_checkpoints_flag_not_set_to_on/test/negative.yaml
assets/queries/ansible/gcp/postgresql_log_checkpoints_flag_not_set_to_on/test/positive.yaml
assets/queries/ansible/gcp/postgresql_log_checkpoints_flag_not_set_to_on/test/positive_expected_result.json

This query evaluates if there's a `log_connections` flag under `<module>.settings.databaseFlags` with its value set to `on`.
Closes #1755

Add postgresql_log_checkpoints_flag_not_set_to_on query for Ansible

---

assets/queries/ansible/gcp/postgresql_log_connections_flag_not_set_to_on/metadata.json
assets/queries/ansible/gcp/postgresql_log_connections_flag_not_set_to_on/query.rego
assets/queries/ansible/gcp/postgresql_log_connections_flag_not_set_to_on/test/negative.yaml
assets/queries/ansible/gcp/postgresql_log_connections_flag_not_set_to_on/test/positive.yaml
assets/queries/ansible/gcp/postgresql_log_connections_flag_not_set_to_on/test/positive_expected_result.json

This query evaluates if there's a `log_connections` flag under `<module>.settings.databaseFlags` with its value set to `on`.
Closes #1752

Add postgresql_log_connections_flag_not_set_to_on query for Ansible

---

assets/queries/terraform/aws/msk_cluster_encryption_enabled/metadata.json
assets/queries/terraform/aws/msk_cluster_encryption_enabled/query.rego
assets/queries/terraform/aws/msk_cluster_encryption_enabled/test/negative.tf
assets/queries/terraform/aws/msk_cluster_encryption_enabled/test/positive.tf
assets/queries/terraform/aws/msk_cluster_encryption_enabled/test/positive_expected_result.json

MSK cluster should be encrypted i.e. should have attribute encryption_info defined and client_broker and in_cluster should be set with default value ("TLS" and true, respectively)
Closes #1761

Add msk_cluster_encryption_enabled query for Terraform (#1761)

---

assets/queries/ansible/aws/no_password_policy_enabled/query.rego
assets/queries/ansible/azure/cosmosdb_account_without_tags/query.rego
assets/queries/cloudFormation/s3_buckets_are_publicly_accessible/query.rego
assets/queries/terraform/aws/aws_config_rule_for_encrypted_vols_is_disabled/query.rego
cmd/console/main.go
internal/tracker/ci.go
pkg/engine/inspector.go
pkg/engine/vulnerability_builder.go
pkg/engine/vulnerability_builder_test.go

Closes #1791
Failed to detect line issues are now seen as a 'failed to execute query'.
The logger has been improved to print the name of the file and query name when there is a 'failed to detect line'.

Fix detect line issues

---

.github/workflows/go.yml

*Currently integration tests are only checking if the command exit code is zero, we should also verify if the number of queries loaded is more than zero*
Example:
```sh
jq '.queries_total' assets/queries/results.json | xargs -i{} test {} -gt 0 
```
Closes #1788

Assert values in integration tests' result.json

---

.github/workflows/go.yml
internal/console/scan.go
internal/tracker/ci.go
pkg/engine/inspector.go
pkg/engine/vulnerability_builder.go
pkg/model/summary.go
test/queries_content_test.go

Closes #1828
- default vulnerability builder logs the error during the similarity ID computation attempt and moves on to create the vulnerability
- adding failed to compute similarity id counter into the scan summary
- adding integration tests assertion to verify if results are greater than zero
Results output format:
```txt
{
"files_scanned": 156,
"files_parsed": 152,
"files_failed_to_scan": 0,
"queries_total": 790,
"queries_failed_to_execute": 3,
"queries_failed_to_compute_similarity_id": 493,
"queries": [
{
"query_name": "DB Security Group Higher than 256",
"query_id": "ea0ed1c7-9aef-4464-b7c7-94c762da3640",
"severity": "HIGH",
"files": [
{
"file_name": "/home/rcbop/git/amazon.aws/tests/integration/targets/ec2_group/tasks/diff_mode.yml",
"similarity_id": "", …
```

Empty vulnerability results when KICS fails to compute similarity ID

---

test/main_test.go
test/similarity_id_test.go

Refactor `main_test.go` functions to also return an error type instead of suppressing them:
```
getQueryContent
getSampleContent
getFileContent
```
fixes #1821

Supressed error treatment in similarity id tests

---

internal/console/scan.go

Closes #1805
- Logs and stdout now outputs the scan time duration in order to provide additional info

Improve logging to record scan elapsed time

---

internal/console/helpers.go
internal/console/scan.go
pkg/engine/inspector.go

Closes #1803 
- Store a failed queries map inside the inspector.
- Prints a report of failed queries in stdout in the summary at the end of a scan.
Example output:
```
Scanning with Keeping Infrastructure as Code Secure v1.1.1
Files scanned: 12
Parsed files: 12
Queries loaded: 790
Queries failed to execute: 2
- apt_get_without_no_recommends_flag:
failed to evaluate query: apt_get_without_no_recommends_flag:59:
eval_conflict_error: functions must not produce
multiple outputs for same inputs
- apt_get_without_yes_flag:
failed to evaluate query: apt_get_without_yes_flag:59:
eval_conflict_error: functions must not produce
multiple outputs for same inputs
------------------------------------
MAINTAINER Instruction Being Used, Severity: HIGH, Results: 9 …
```

Improve logging and reporting to show failed queries

---

.goreleaser-nightly.yml
.goreleaser.yml

Closes #1886
- adding assets/libraries to files in `.goreleaser.yml`

Goreleaser is not including assets/libraries to the distribution packages

---

assets/queries/cloudFormation/access_key_not_rotated_within_90_days/query.rego

Closes #1856
- Fixed with Type Check on line 5 of the query, instead of checking inside the function.

Update Query Access Key Is Not Rotated Within 90 Days for CloudFormation #1856

---

assets/queries/ansible/gcp/log_min_messages_invalid_value/query.rego

Closes #1880 
- Verifying if the flag's name is `log_min_messages` **before** checking its value in `check_database_flags_content` assures no other flags will appear in the results.

Update 'Log Min Messages Invalid Value' query for Ansible

---

assets/queries/cloudFormation/ec2_public_instance_exposed_through_subnet/test/negative.yaml
assets/queries/cloudFormation/ecs_cluster_at_rest_encryption/test/positive.yaml

Closes #1883 
- Indentation was wrong, so it was not recognizing the second sample on the negative yaml
- Had two samples, should be pointing to line 80 and 149, but since when running the test it becomes only one document, since two samples has the same name, it was fixed by changing the name.

Update VPC Has FlowLog Disabled query for CloudFormation #1883

---

assets/queries/k8s/block_workload_mounting_os_dir/query.rego
assets/queries/k8s/block_workload_mounting_os_dir/test/positive_expected_result.json

Closes #1917
- replaced `[_]` with `[j]`

Update 'Block Workload Mounting OS Directory' query for Kubernetes

---

cx.configuration

Closes #1940 
- Adds *_test.go to the files excluded from sast scans

add cxflow scan exclusion to _test.go files

---

.github/workflows/go-ci-publish-unit-tests.yml

fixing GitHub workflow_run to get sha hash of the head commit that triggered the event

hotfix publish unit tests report

---

.github/workflows/go-ci-publish-unit-tests.yml

- hiding all old unit tests PR comments but the latest one

CI Hotfix - hiding all old unit tests PR comments

---

assets/queries/cloudFormation/aws_lambda_function_without_tags/query.rego
assets/queries/cloudFormation/aws_lambda_function_without_tags/test/positive_expected_result.json
assets/queries/cloudFormation/aws_lambda_functions_tracing_disabled/query.rego
assets/queries/cloudFormation/aws_lambda_functions_tracing_disabled/test/positive_expected_result.json
assets/queries/cloudFormation/elastic_search_domain_encryption_at_rest_disabled/query.rego
assets/queries/cloudFormation/elastic_search_domain_encryption_at_rest_disabled/test/positive_expected_result.json
assets/queries/cloudFormation/ingress_with_port_range/query.rego
assets/queries/cloudFormation/ingress_with_port_range/test/positive_expected_result.json
assets/queries/cloudFormation/rds_backup_retention_period_insufficient/query.rego
assets/queries/cloudFormation/rds_backup_retention_period_insufficient/test/positive_expected_result.json
assets/queries/cloudFormation/rds_db_instance_with_deletion_protection_disabled/query.rego
assets/queries/cloudFormation/rds_multi_az_deployment_disabled/query.rego
assets/queries/cloudFormation/rds_multi_az_deployment_disabled/test/positive_expected_result.json
assets/queries/cloudFormation/sns_topic_should_specify_kms_master_key_id/query.rego

Closes #1927
- In query "Elastic Search Domain Encryption At Rest Disabled", removed "EncryptionAtRestOptions" from searchKey;
- In query "RDS DBInstance With Deletion Protection Disabled", removed "DeletionProtection" from searchKey;
- In query "AWS Security Group Ingress With Port Range", removed "FromPort" from searchKeys;
- In query "Sns Topic Should Specify KmsMasterKeyId Attribute", removed "KmsMasterKeyId" from searchKey;
- In query "RDS Multi-AZ Deployment Disabled", added "Properties" to searchKey;
- In query "RDS Backup Retention Period Insufficient", added "Properties" to searchKey;
- In query "AWS Lambda Function Without Tags", added "Properties" to searchKey;
- In query "AWS Lambda Functions Tracing Disabled", added "Properties" and …

Correcting SearchKey Depth for CloudFormation

---

assets/queries/k8s/memory_limits_not_defined/query.rego
assets/queries/k8s/memory_limits_not_defined/test/positive.yaml
assets/queries/k8s/memory_limits_not_defined/test/positive_expected_result.json
assets/queries/k8s/memory_requests_not_defined/query.rego
assets/queries/k8s/memory_requests_not_defined/test/positive.yaml
assets/queries/k8s/memory_requests_not_defined/test/positive_expected_result.json

Closes #1928 
In both queries:
- Removed the rule that verifies if a container is defined, which is not always mandatory
- Added rules to verify the contents of 'initContainers'
- Added some positive examples

Update 'Memory Limits Are Not Defined' and 'Memory Requests Are Not Defined' queries for Kubernetes

---

assets/queries/cloudFormation/aws_lambda_functions_with_full_privileges/query.rego
assets/queries/cloudFormation/ebs_volume_encryption_key_rule/query.rego
assets/queries/cloudFormation/ebs_volume_encryption_key_rule/test/positive_expected_result.json
assets/queries/cloudFormation/elasticache_with_disabled_at_rest_encryption/query.rego
assets/queries/cloudFormation/elasticache_with_disabled_at_rest_encryption/test/positive_expected_result.json
assets/queries/cloudFormation/s3_bucket_acl_allows_read_to_all_users/query.rego
assets/queries/cloudFormation/sns_topic_without_subscriber/query.rego
assets/queries/cloudFormation/workspace_without_encryption/query.rego

Closes #1945
- In query "EBS Volume Encryption Key Rule", corrected typo "properties" to "Properties" in searchKey;
- In query "Workspace Without Encryption", fixed typo in keyActualValue;
- In query "ElastiCache with disabled at Rest Encryption", corrected typo "properties" to "Properties" in searchKey;
- In query "SNS Topic Without Subscriber", removed "AlarmActions.Ref" from searchKey;
- In query "S3 Bucket ACL Allows Read to AllUsers", changed keyActualValue;
- In query "AWS Lambda Functions With Full Privileges", corrected grammatical error in keyExpectedValue and keyActualValue;
- Also changed necessary "positive_expected_result.json".

Correcting typos and mistakes in queries for AWS CloudFormation

---

internal/console/scan.go
pkg/engine/inspector_test.go
pkg/engine/query/source.go

Closes #1964 
- Changed to try to find libraries folder on same level as queries folder from assets

Corrected source to get libraries path based on queries path flag

---

assets/queries/terraform/aws/kinesis_sse_not_configured/query.rego
assets/queries/terraform/aws/kinesis_sse_not_configured/test/negative.tf
assets/queries/terraform/aws/kinesis_sse_not_configured/test/positive.tf
assets/queries/terraform/aws/kinesis_sse_not_configured/test/positive_expected_result.json

When an encrypted Kinesis Data Stream is used as datasource to a Kinesis Firehose, then it can't and must not need to have sse enabled
cf AWS details: https://docs.aws.amazon.com/firehose/latest/dev/encryption.html
cf terraform details:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream
Closes #1858
- Add policy check to allow server_side_encryption optionto be unset on aws_kinesis_firehose_delivery_stream when kinesis_source_configuration exists

fix: terraform/aws kinesis firehose ss3 rule issue #1858

---

assets/queries/cloudFormation/elb_v2_alb_access_log_disabled/query.rego
assets/queries/cloudFormation/elb_v2_alb_access_log_disabled/test/positive_expected_result.json
assets/queries/cloudFormation/s3_bucket_without_ssl_in_write_actions/query.rego

Closes #1989
- In query "ELBv2 ALB Access Log Disabled", divided query into 2, one with "MissingAttribute" issue type and another with "IncorrectValue". Also, updated "positive_expected_result.json".
- In query "S3 Bucket Without SSL In Write Actions", divided query into 2, one with "MissingAttribute" issue type and another with "IncorrectValue".

Remodeling queries to be more specific for AWS CloudFormation 

---

assets/queries/terraform/aws/api_gateway_without_cloudwatch_log/test/positive.tf

Closes #1999 
- Fixed this query not giving a positive in this folder positive.tf file, because the 'aws_api_gateway_stage' resource of the positive.tf is getting the 'aws_cloudwatch_log_group' resources from the negative.tf and positive.tf , so we needed to put a different stage_name in the 'aws_api_gateway_stage' resource in the positive.tf.

Update api_gateway_without_cloudwatch_log query Closes #1999

---

.goreleaser-nightly.yml
.goreleaser.yml

Closes #1678
- Enabled building for darwin
Testing on macOS Catalina 10.15.7
```
✗ ./bin/kics scan -p . -o result.json
Scanning with Keeping Infrastructure as Code Secure v1.1.2
[...]
Results Summary:
HIGH: 4041
MEDIUM: 4979
LOW: 1449
INFO: 87
TOTAL: 10556
Scan duration: 1m47.145168159s
```

enable building for mac (darwin)

---

.github/workflows/nightly-release.yml

Closes #2013
- fixing `asset_name` typo
- uploading macOS release assets to nightly releases
Related with: #1678

Adding macOS binaries to nightly releases 

---

assets/queries/terraform/aws/root_account_has_associated_active_access_keys/test/negative.tf
assets/queries/terraform/aws/root_account_has_associated_active_access_keys/test/positive.tf

Closes #2012 
- 'root_account_has_associated_active_access_keys' now gives more correct positive results

Update iam_policies_allow_all query Closes #2012

---

assets/queries/cloudFormation/ec2_network_acl_duplicate_rule/query.rego
assets/queries/cloudFormation/ec2_network_acl_duplicate_rule/test/positive.yaml
assets/queries/cloudFormation/ec2_network_acl_duplicate_rule/test/positive_expected_result.json
assets/queries/cloudFormation/ec2_network_acl_protocols/query.rego
assets/queries/cloudFormation/gamelift_fleet_ec2_inbound_permissions_with_port_range/query.rego
assets/queries/cloudFormation/gamelift_fleet_ec2_inbound_permissions_with_port_range/test/positive.yaml
assets/queries/cloudFormation/gamelift_fleet_ec2_inbound_permissions_with_port_range/test/positive_expected_result.json

Closes #1985
- In query "EC2 Network ACL Duplicate Rule", added methods for the different formats the value can appear, namely as a string or number;
- In query "EC2 permissive network ACL protocols", added methods for when the value is in a string format and not in number format;
- In query "AWS GameLift Fleet EC2InboundPermissions With Port Range", added variations of the query for the different formats, namely string and number.

Adding StringHandling and Correcting queries that don't handle strings for AWS CloudFormation 

---

assets/queries/cloudFormation/aws_lambda_functions_with_full_privileges/query.rego

Closes #2028
- Updated the query to handle "Action" arrays as well as single "Action";
- Added the name of the policy that triggers error;
- Simplified methods "checkResource" and "checkAction".

Update AWS Lambda Functions with Full Privileges query for AWS CloudFormation

---

assets/libraries/ansible/library.rego
assets/queries/ansible/aws/redshift_not_encrypted/query.rego
assets/queries/ansible/aws/redshift_not_encrypted/test/negative.yaml
assets/queries/ansible/aws/redshift_not_encrypted/test/positive.yaml
assets/queries/ansible/aws/redshift_not_encrypted/test/positive_expected_result.json

Closes #1910 
- Check if the 'command' field is equal to 'create' when 'encrypted' field is undefined
- Check if the 'command' field is equal to 'create' or 'modify' when 'encrypted' field is defined and false
- Change issue type to 'IncorrectValue' instead of 'WrongValue'
- Check both full path and only the module's name when searching the correct task (`community.aws.redshift` or `redshift`)

Update redshift_not_encrypted query for Ansible #1910

---

assets/queries/terraform/aws/port22_in_public_scope/query.rego
assets/queries/terraform/gcp/cloud_sql_database_has_public_access/query.rego
assets/queries/terraform/gcp/cloud_sql_database_has_public_access/test/negative.tf
assets/queries/terraform/gcp/cloud_sql_database_has_public_access/test/positive.tf
assets/queries/terraform/gcp/cloud_sql_database_has_public_access/test/positive_expected_result.json
assets/queries/terraform/gcp/using_default_service_account/query.rego

Closes #2027 
| Queries changed | Changes |
|---------------------|---------|
| Cloud SQL DB Is Publicly Accessible | Allow multiple authorized_networks rules and evaluate them separately. Fixed searchKey.  Changed samples and expected results to reflect the changes |
| SSH (TCP:22) in Public Scope | Allow multiple ingress rules and evaluate them separately. Allow values in variables since it's not possible to assess the risk. Fixed searchKey |
| Using Default Service Account |  Allow values in variables since it's not possible to assess the risk |

Fixed queries with wrong evaluations. Closes #2027

---

assets/queries/k8s/service_with_external_load_balance/query.rego
assets/queries/k8s/service_with_external_load_balance/test/negative.yaml
assets/queries/k8s/service_with_external_load_balance/test/positive.yaml
assets/queries/k8s/service_with_external_load_balance/test/positive_expected_result.json

Closes #2006 
- Refactor Query
- The query has many false positives, this is because the query never detects if the Service using an external Load Balancer provider by cloud provider.

Refactor Service With External Load Balance query #2006

---

assets/queries/terraform/aws/db_instance_auto_minor_version_upgrade_is_disabled/query.rego
assets/queries/terraform/aws/db_instance_iam_database_authentication_enabled/query.rego
assets/queries/terraform/aws/db_instance_storage_not_encrypted/query.rego
assets/queries/terraform/aws/ebs_volume_snapshot_encrypted/query.rego
assets/queries/terraform/aws/efs_not_encrypted/query.rego
assets/queries/terraform/aws/efs_not_encrypted/test/positive_expected_result.json
assets/queries/terraform/aws/launch_configuration_is_not_encrypted/query.rego
assets/queries/terraform/aws/launch_configuration_is_not_encrypted/test/positive.tf
assets/queries/terraform/aws/launch_configuration_is_not_encrypted/test/positive_expected_result.json
assets/queries/terraform/aws/unprotected_sqs_queue/query.rego
assets/queries/terraform/aws/unprotected_sqs_queue/test/positive_expected_result.json
assets/queries/terraform/azure/key_vault_soft_delete_enabled/query.rego
assets/queries/terraform/gcp/project_wide_ssh_keys_are_enabled/query.rego

Closes #1929
| Query Changed | Changes |
|-----------------|--------------|
| Auto Minor Version Upgrade Is Set To False | Add verification when the attribute is missing instead of incorrect |
| IAM Database Auth Not Enabled | Add verification when the attribute is missing instead of incorrect |
| DB Instance Storage Not Encrypted |  Add verification when the attribute is missing instead of incorrect and improve attribute retrieval with *object.get()* |
| Volume Snapshot Not Encrypted | Add verification when the attribute is missing instead of incorrect |
| EFS Is Not Encrypted | Add verification when the attribute is missing instead of incorrect. Fixed *searchKey* and expected result line |
| Launch Configuration Is Not Encrypted |  Add verification when the …

Fixed terraform queries with 'MissingAttribute' missing. Closes #1929

---

assets/queries/terraform/aws/s3_bucket_without_encryption_at_rest/query.rego
assets/queries/terraform/aws/s3_bucket_without_encryption_at_rest/test/negative.tf
assets/queries/terraform/aws/s3_bucket_without_encryption_at_rest/test/positive.tf
assets/queries/terraform/aws/s3_bucket_without_encryption_at_rest/test/positive_expected_result.json
assets/queries/terraform/aws/s3_bucket_without_versioning/query.rego
assets/queries/terraform/gcp/ssh_access_is_unrestricted/query.rego

Closes #2000
| Queries Changed | Changes |
|---------------------|----------|
| SSH Access Is Not Restricted From The Internet | Improved searchKey to locate the correct ports attribute |
| S3 bucket without versioning | Improved keyValues and attribute existence check with object.get() |
| S3 bucket without encryption at REST | Refactored query to correctly evaluate attributes and identify the proper lines. Samples and expected results were also changed for the refactor |

Fixed queries with results pointing to wrong lines. Closes #2000

---

assets/queries/cloudFormation/s3_bucket_versioning_not_enabled/query.rego

Closes #2064
- Adding verification to check if attribute "Properties" is present, as to prevent unnecessary triggering of query;
- Replace verification of "VersioningConfiguration" existence with a "object.get" method verification.

Update S3 Bucket Versioning Not Enabled query for AWS CloudFormation 

---

pkg/engine/vulnerability_builder.go
pkg/engine/vulnerability_builder_test.go

Closes #2001 
- Use the function 'getBracketValues()' to get values instead of regex

fix bug with curly brackets and rename bad variables #2001

---

.github/workflows/go-ci-integration.yml
.github/workflows/nightly-release.yml
.github/workflows/release.yml
.goreleaser-nightly.yml
.goreleaser.yml
Dockerfile
internal/console/version.go
internal/console/version_test.go

Closes #2081
- passing current version during build time with `ldflags`
- when a tag is created and pushed the workflow will trigger and goreleaser will retrieve latest tag and use it as the ldflag parameter Version
- nigthly builds will have the version named as **nightly-<COMMIT_SHORT_SHA>**
- when using `go run` to execute kics the fallback hardcoded version `dev` will be displayed. 
- docker builds will require `--build-arg VERSION=myVersion` otherwise it will fallback to `development` default arg value e.g: 
```docker build --build-arg VERSION=$(git describe --tags --always --dirty ) -t Checmarx/kics:$(git describe --tags --always --dirty ) .```

Passing version number as ldflags during build 

---

pkg/engine/query/source.go
pkg/parser/parser.go
pkg/parser/parser_test.go

fixed case sensitive issues with type flag and fixed bug with dup types #2092
Closes #2092
- type flag now ignores case sensitive
-fixed bug where if two extensions add the same type it would appear duplicated invalid arguments

fixed case sensitive issues with type flag and fixed bug with dup types

---

assets/queries/cloudFormation/workspace_without_encryption/query.rego

Closes #2095
- Correcting a mistake where "policyName" is used instead of "workspaceName".

Update Workspace Without Encryption query for AWS CloudFormation 

---

assets/queries/cloudFormation/routertable_with_default_routing/query.rego
assets/queries/cloudFormation/routertable_with_default_routing/test/negative.yaml
assets/queries/cloudFormation/routertable_with_default_routing/test/positive.yaml
assets/queries/cloudFormation/routertable_with_default_routing/test/positive_expected_result.json

Closes #2058
- Added check with "DestinationIpv6CidrBlock";
- Corrected query to check "NatGatewayId" instead of "GatewayId" as per the documentation.

Update And Correct RouterTable with Default Routing query for AWS CloudFormation 

---

.gitignore
go.mod
go.sum
internal/console/helpers/helpers.go
internal/console/helpers/helpers_test.go
internal/console/scan.go
test/fixtures/config_test/kics.config_hcl
test/fixtures/config_test/kics.config_js
test/fixtures/config_test/kics.config_json
test/fixtures/config_test/kics.config_toml
test/fixtures/config_test/kics.config_yaml
test/fixtures/config_test/kics.hcl
test/fixtures/config_test/kics.js
test/fixtures/config_test/kics.json
test/fixtures/config_test/kics.toml
test/fixtures/config_test/kics.yaml
test/fixtures/config_test/kics_wrong.js

Closes #2077
- Kics Can now be called without flags and will get the configurations from the 'kics.config' file inside the root of kics
-Kics will now check the contents of the config file and determine its extension 
-If there is no 'kics.config' file in the root of kics, kicks must be run with flags, or with the '--config' flag with the path to a configuration file 

Enhanced config flag #2077

---

assets/queries/cloudFormation/s3_bucket_should_have_bucket_policy/query.rego
assets/queries/cloudFormation/s3_bucket_should_have_bucket_policy/test/negative.yaml
assets/queries/cloudFormation/s3_bucket_should_have_bucket_policy/test/positive.yaml
assets/queries/cloudFormation/s3_bucket_should_have_bucket_policy/test/positive_expected_result.json

Closes #2116
- Adding missing reference handling;
- Adding new validation, namely, that the reference in a Bucket Policy also doesn't match the name of the resource, instead of just the "BucketName" property.

Update S3 Bucket Should Have Bucket Policy query for AWS CloudFormation 

---

assets/queries/cloudFormation/ec2_network_acl_duplicate_rule/query.rego

Closes #2107
- Updating "getTraffic()" method to consider more formats in which a value can be.

Update EC2 Network ACL Duplicate Rule query for AWS CloudFormation 

---

docs/configuration-file.md
docs/getting-started.md
internal/console/scan.go
pkg/engine/inspector.go
pkg/engine/inspector_test.go
test/queries_content_test.go
test/queries_test.go
test/similarity_id_test.go

Closes #2046
- Adding `--exclude-results` flag (shorthand `-x`) that can be provided several times or with a comma-separated string list of similarity IDs that will be removed from the scan results
Original Sample Results:
After removing all results:
With configuration file:
```json
{
"path": "assets/queries/cloudFormation/s3_bucket_should_have_bucket_policy",
"verbose": true,
"log-file": true,
"queries-path": "assets/queries/cloudFormation/s3_bucket_should_have_bucket_policy",
"output-path": "results.json",
"exclude-results": "362003f669e5e8cd5306d90b022818de771eaed92efd46cf31412863d03fbb76"
}
```

Exclude specific results by similarity ID 

---

internal/console/scan.go
pkg/engine/query/source.go

Closes #2135
- fixed bug where you couldn't pass the flag types empty

fix bug with empty type flag #2135

---

internal/console/scan.go

Closes #2139
- fix bug kics was having with config yaml 
- fix yaml arrays in config file errors
- changed local envs from VIPER_ to KICS_

Fix yaml config bug

---

.gitignore
internal/console/scan.go

Closes #2136
- print help and exit with status code 1 when provided with an invalid key in the configuration file

Print help when provided with configuration file that contains invalid keys

---

.github/workflows/go-ci-integration.yml
.github/workflows/go-ci.yml
.github/workflows/go-coverage.yml
.github/workflows/nightly-release.yml
.github/workflows/release.yml
go.mod

Closes #2142
- Bump go version to 1.16

Bump go version to 1.16

---

.github/workflows/release.yml

Fixing release workflow GH actions string interpolation issue. Invalid previous context "outputs"

Fixing release workflow GH actions interpolation

---

.github/workflows/generate-queries-docs.yaml

Fixes #2214
- Use KICS BOT Personal Access Token as recommended in this thread https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-537478081
- Removing irrelevant ref parameter from PR title.

Fix automatic PR in generate-queries-docs not triggering checks

---

.github/workflows/nightly-release.yml

Closes  #2222
-  use short (8 chars) IDs to make those easier to read.

Use short SHA for nightly builds

---

assets/queries/dockerfile/apt_get_missing_yes_flag_to_avoid_manual_input/query.rego
assets/queries/dockerfile/apt_get_missing_yes_flag_to_avoid_manual_input/test/positive.dockerfile
assets/queries/dockerfile/apt_get_missing_yes_flag_to_avoid_manual_input/test/positive_expected_result.json
assets/queries/dockerfile/yum_install_allows_manual_input/query.rego

Closes #2169
- Additional regex to include cases when the yes flag is after the packages

Update "Yum Install Allows Manual Input" and "APT-GET Missing '-y' To Avoid Manual Input" queries for Docker Closes #2169

---

.github/workflows/nightly-release.yml

Attempting to fix nightly builds naming

Getting short commit hash from git instead of env vars

---

assets/libraries/dockerfile/library.rego
assets/queries/dockerfile/apt_get_install_pin_version_not_defined/query.rego
assets/queries/dockerfile/gem_install_without_version/query.rego
assets/queries/dockerfile/gem_install_without_version/test/negative.dockerfile
assets/queries/dockerfile/gem_install_without_version/test/positive.dockerfile
assets/queries/dockerfile/gem_install_without_version/test/positive_expected_result.json
assets/queries/dockerfile/image_version_not_explicit/query.rego
assets/queries/dockerfile/image_version_not_explicit/test/negative.dockerfile
assets/queries/dockerfile/missing_version_specification_in_dnf_install/query.rego
assets/queries/dockerfile/missing_version_specification_in_dnf_install/test/negative.dockerfile
assets/queries/dockerfile/missing_version_specification_in_dnf_install/test/positive.dockerfile
assets/queries/dockerfile/missing_version_specification_in_dnf_install/test/positive_expected_result.json
assets/queries/dockerfile/unpinned_package_version_in_apk_add/query.rego
assets/queries/dockerfile/unpinned_package_version_in_apk_add/test/negative.dockerfile
assets/queries/dockerfile/unpinned_package_version_in_apk_add/test/positive.dockerfile
assets/queries/dockerfile/unpinned_package_version_in_apk_add/test/positive_expected_result.json
assets/queries/dockerfile/unpinned_package_version_in_pip_install/query.rego
assets/queries/dockerfile/workdir_path_not_absolute/query.rego
assets/queries/dockerfile/workdir_path_not_absolute/test/negative.dockerfile
assets/queries/dockerfile/yum_install_without_version/query.rego
assets/queries/dockerfile/zypper_install_without_version/query.rego

Closes #2188
- **"WORKDIR Path Not Absolute"**: considering global var in WORKDIR path. For example, "WORKDIR ${GLASSFISH_HOME}/bin"
- **"Image Version Not Explicit"**: considering global var and alias in version. For example, "ARG IMAGE=alpine:3.12
FROM $IMAGE"; "FROM python:3.7-alpine as base".
- **"Apt Get Install Pin Version Not Defined"**, **"Gem Install Without Version"**, **"Yum install Without Version"**, **"Zypper Install Without Version"**: considering another version case (grpc-tools:${GRPC_VERSION}}) and excluding cases like "RUN gem install grpc -v ${GRPC_RUBY_VERSION}"

Considering global var in some queries for Docker Closes #2188

---

.github/workflows/update-docs-index.yaml
.github/workflows/update-docs-queries.yaml
.goreleaser.yml

- Prerelease by default on pushed tags
- Automatically create PR to update documentation after the release was tested and has been manually published
- Renaming update queries docs workflow
- Update queries docs now displays changed metadata list in the PR's body

Update docs after manual release publication

---

assets/queries/cloudFormation/rds_configuration_automatic_backup_disabled/query.rego

Closes #2249
- Added a use of the method `to_number` in the query, to handle when the value comes as a string.

Update AWS RDS Configuration Automatic Backup Disabled query for AWS CloudFormation

---

assets/queries/cloudFormation/alb_is_not_integrated_with_waf/query.rego
assets/queries/cloudFormation/cloudfront_distribution_access_log_disabled/query.rego
assets/queries/cloudFormation/cloudfront_distribution_without_waf/query.rego
assets/queries/cloudFormation/ec2_network_acl_ineffective_denied_traffic/query.rego
assets/queries/cloudFormation/efs_without_tags/query.rego
assets/queries/cloudFormation/elb_without_ssl/query.rego
assets/queries/cloudFormation/lambda_function_without_tags/query.rego
assets/queries/cloudFormation/s3_bucket_should_have_bucket_policy/query.rego
assets/queries/cloudFormation/s3_bucket_versioning_not_enabled/query.rego
assets/queries/cloudFormation/s3_bucket_website_host_is_disabled/query.rego
assets/queries/cloudFormation/s3_bucket_without_server_side_encryption/query.rego
assets/queries/cloudFormation/security_group_ingress_cidr_open_to_world/query.rego
assets/queries/cloudFormation/security_groups_with_exhibited_admin_ports/query.rego
assets/queries/cloudFormation/vpc_has_flowlog_disabled/query.rego

Closes #2259
Changing keyExpectedValue and/or keyActualValue to be more explicit, in queries:
- 105ba098-1e34-48cd-b0f2-a8a43a51bf9b
- 0f139403-303f-467c-96bd-e717e6cfd62d
- de77cd9f-0e8b-46cc-b4a4-b6b436838642
- cdbb0467-2957-4a77-9992-7b55b29df7b7
- 90501b1b-cded-4cc1-9e8b-206b85cda317
- a227ec01-f97a-4084-91a4-47b350c1db54
- f6d299d2-21eb-41cc-b1e1-fe12d857500b
- 80908a75-586b-4c61-ab04-490f4f4525b8
- b2e8752c-3497-4255-98d2-e4ae5b46bbf5
- 08e39832-5e42-4304-98a0-aa5b43393162
- 8df8e857-bd59-44fa-9f4c-d77594b95b46
- 4a1e6b34-1008-4e61-a5f2-1f7c276f8d14
- 37fa8188-738b-42c8-bf82-6334ea567738
- 2623d682-dccb-44cd-99d0-54d9fd62f8f2

Update queries to be more explicit for AWS CloudFormation 

---

assets/queries/cloudFormation/cloudfront_without_minimum_protocol_tls_1.2/query.rego

Closes #2263
- Adding a different format for the CloudFront Minimum Protocol Version, using "-" instead of "_".

Update CloudFront Without Minimum Protocol TLS 1.2 query for AWS CloudFormation 

---

assets/queries/cloudFormation/ec2_permissive_network_acl_protocols/query.rego

Closes #2265
- Correcting a mistake in which the value before a conversion was being used to compare, instead of the value after the conversion.

Update EC2 Permissive Network ACL Protocols query for AWS CloudFormation 

---

.github/workflows/update-docs-index.yaml
.github/workflows/update-docs-queries.yaml
.github/workflows/update-godownloader-script.yaml

Fixing bug in update docs workflow by changing the way we provide the personal access token

Update docs workflows are not running

---

assets/queries/dockerfile/chown_flag_exists/metadata.json
assets/queries/dockerfile/chown_flag_exists/query.rego
assets/queries/dockerfile/chown_flag_exists/test/negative.dockerfile
assets/queries/dockerfile/chown_flag_exists/test/positive.dockerfile
assets/queries/dockerfile/chown_flag_exists/test/positive_expected_result.json

Closes # 2257
-Query to check the --chown flag, because we can just drop the --chown option, the user only needs execution permissions on the file, not ownership

Added Chown Flag Exists query

---

pkg/parser/json/parser.go

Closes #2408
- try to unmarshal with `map[string]interface{}`
- if an error is found unmarshal with `[]map[string]inteface{}`

Enable JSON parser to unmarshal []map[string]inteface{} 

---

pkg/engine/source/filesystem.go

Closes #2367
- Closing file handlers after reading metadata to avoid resource exaustion

Close metadata file handlers #2367

---

assets/queries/terraform/aws/sns_topic_publicity_has_allow_and_not_action_simultaneously/metadata.json
assets/queries/terraform/aws/sns_topic_publicity_has_allow_and_not_action_simultaneously/query.rego
assets/queries/terraform/aws/sns_topic_publicity_has_allow_and_not_action_simultaneously/test/negative.tf
assets/queries/terraform/aws/sns_topic_publicity_has_allow_and_not_action_simultaneously/test/positive.tf
assets/queries/terraform/aws/sns_topic_publicity_has_allow_and_not_action_simultaneously/test/positive_expected_result.json

Closes #2288
- Add support in Terraform for a query with the same name already implemented in CloudFormation.
- The query checks if a SNS Topic policy has statements `Effect: Allow` and `NotAction` simultaneously.

Add "SNS Topic Publicity Has Allow and NotAction Simultaneously" query for Terraform

---

assets/queries/terraform/aws/api_gateway_with_open_access/metadata.json
assets/queries/terraform/aws/api_gateway_with_open_access/query.rego
assets/queries/terraform/aws/api_gateway_with_open_access/test/negative.tf
assets/queries/terraform/aws/api_gateway_with_open_access/test/positive.tf
assets/queries/terraform/aws/api_gateway_with_open_access/test/positive_expected_result.json

Closes #2307
- Add support in Terraform for a query with the same name already implemented in CloudFormation.
- The query checks if the authorization type is restricted in API Gateway Method resource (therefore being different from `NONE`). The authorization type can only be `NONE` when the http method is `OPTIONS`.

Add "API Gateway With Open Access" query for Terraform

---

assets/queries/cloudFormation/iam_user_login_profile_password_is_in_plaintext/query.rego

Closes #2314
- Adding additional verification to confirm that value being looked at isn't a SecretsManager reference.

Update IAM User LoginProfile Password Is In Plaintext query for AWS CloudFormation 

---

assets/queries/cloudFormation/elb_with_security_group_without_inbound_rules/query.rego

Closes #2316
- Adding a verification for when the `SecurityGroupIngress` is defined out of the `SecurityGroup` resource.

Update ELB With Security Group Without Inbound Rules query for AWS CloudFormation

---

assets/queries/cloudFormation/elastic_search_without_slow_logs/metadata.json
assets/queries/cloudFormation/elastic_search_without_slow_logs/query.rego
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/negative1.yaml
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/negative2.json
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/positive1.yaml
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/positive2.yaml
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/positive3.yaml
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/positive4.json
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/positive5.json
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/positive6.json
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/positive_expected_result.json

Closes #2312
Ensure that AWS Elasticsearch enables support for slow logs.

Add "Elasticsearch Without Slow Logs" query for CloudFormation #2312

---

assets/queries/terraform/kubernetes_pod/psp_with_added_capabilities/metadata.json
assets/queries/terraform/kubernetes_pod/psp_with_added_capabilities/query.rego
assets/queries/terraform/kubernetes_pod/psp_with_added_capabilities/test/negative.tf
assets/queries/terraform/kubernetes_pod/psp_with_added_capabilities/test/positive.tf
assets/queries/terraform/kubernetes_pod/psp_with_added_capabilities/test/positive_expected_result.json

Closes #2355
- Support "PSP With Added Capabilities" query for Terraform (same as "PSP With Added Capabilities" for Kubernetes). It is necessary to check if the attribute `allowed_capabilities` is set 

Add "PSP With Added Capabilities" query for Terraform Closes #2355

---

assets/queries/terraform/kubernetes_pod/psp_allows_privilege_escalation/metadata.json
assets/queries/terraform/kubernetes_pod/psp_allows_privilege_escalation/query.rego
assets/queries/terraform/kubernetes_pod/psp_allows_privilege_escalation/test/negative.tf
assets/queries/terraform/kubernetes_pod/psp_allows_privilege_escalation/test/positive.tf
assets/queries/terraform/kubernetes_pod/psp_allows_privilege_escalation/test/positive_expected_result.json

Closes #2360
- Support "PSP Allows Privilege Escalation" query for Terraform (same as "PSP With Added Capabilities" for Kubernetes). It is necessary to check if the attribute `allow_privilege_escalation` is set to false. By default, is set to true

Add "PSP Allows Privilege Escalation" query for Terraform Closes #2360

---

assets/queries/cloudFormation/api_gateway_without_ssl_certificate/metadata.json
assets/queries/cloudFormation/api_gateway_without_ssl_certificate/query.rego
assets/queries/cloudFormation/api_gateway_without_ssl_certificate/test/negative1.yaml
assets/queries/cloudFormation/api_gateway_without_ssl_certificate/test/negative2.json
assets/queries/cloudFormation/api_gateway_without_ssl_certificate/test/positive1.yaml
assets/queries/cloudFormation/api_gateway_without_ssl_certificate/test/positive2.json
assets/queries/cloudFormation/api_gateway_without_ssl_certificate/test/positive_expected_result.json

Closes #2358 
Add query API Gateway Without SSL Certificate, that checks if SSL Client Certificate exists.

Add "API Gateway Without SSL Certificate" query for CloudFormation #2358

---

assets/queries/terraform/kubernetes_pod/docker_daemon_socket_is_exposed_to_containers/metadata.json
assets/queries/terraform/kubernetes_pod/docker_daemon_socket_is_exposed_to_containers/query.rego
assets/queries/terraform/kubernetes_pod/docker_daemon_socket_is_exposed_to_containers/test/negative.tf
assets/queries/terraform/kubernetes_pod/docker_daemon_socket_is_exposed_to_containers/test/positive.tf
assets/queries/terraform/kubernetes_pod/docker_daemon_socket_is_exposed_to_containers/test/positive_expected_result.json

Closes #2415
- Support "Docker Daemon Socket is Exposed to Containers" query for Terraform (same as "Docker Daemon Socket is Exposed to Containers" for Kubernetes). It is necessary to check if the attribute `volumes[c].host_path.path` is equal `"/var/run/docker.sock"`

Add "Docker Daemon Socket is Exposed to Containers" query for Terraform Closes #2415

---

assets/queries/terraform/aws/api_gateway_v2_stage_access_logging_settings_not_defined/metadata.json
assets/queries/terraform/aws/api_gateway_v2_stage_access_logging_settings_not_defined/query.rego
assets/queries/terraform/aws/api_gateway_v2_stage_access_logging_settings_not_defined/test/negative.tf
assets/queries/terraform/aws/api_gateway_v2_stage_access_logging_settings_not_defined/test/positive.tf
assets/queries/terraform/aws/api_gateway_v2_stage_access_logging_settings_not_defined/test/positive_expected_result.json

Closes #2318
- Add support for query  "API Gateway V2 Stage Access Logging Settings Not Defined"
- The query checks if the object `access_log_settings` is defined

Add "API Gateway V2 Stage Access Logging Settings Not Defined" query for Terraform

---

assets/libraries/common/library.rego
assets/queries/ansible/aws/iam_role_allows_all_principals_to_assume/query.rego
assets/queries/cloudFormation/iam_role_allows_all_principals_to_assume/metadata.json
assets/queries/cloudFormation/iam_role_allows_all_principals_to_assume/query.rego
assets/queries/cloudFormation/iam_role_allows_all_principals_to_assume/test/negative1.yaml
assets/queries/cloudFormation/iam_role_allows_all_principals_to_assume/test/negative2.json
assets/queries/cloudFormation/iam_role_allows_all_principals_to_assume/test/positive1.yaml
assets/queries/cloudFormation/iam_role_allows_all_principals_to_assume/test/positive2.json
assets/queries/cloudFormation/iam_role_allows_all_principals_to_assume/test/positive_expected_result.json
assets/queries/terraform/aws/iam_role_allows_all_principals_to_assume/query.rego

Closes #2351
- Support "IAM Role Allows All Principals To Assume" query for CloudFormation (same as "IAM Role Allows All Principals To Assume" for Terraform and Ansible). It is necessary to check if IAM role denies "arn:aws:iam::root" principal.
- Add "allowsAllPrincipalsToAssume" to common library

Add "IAM Role Allows All Principals To Assume" query for CloudFormation Closes #2351

---

assets/queries/cloudFormation/iam_password_without_lowercase_letter/query.rego
assets/queries/cloudFormation/iam_password_without_minimum_length/query.rego
assets/queries/cloudFormation/iam_password_without_number/query.rego
assets/queries/cloudFormation/iam_password_without_symbol/query.rego
assets/queries/cloudFormation/iam_password_without_uppercase_letter/query.rego

Closes #2334
- Adding a check, as to ignore if value references SecretsManager.

Update "IAM Password Without" queries for AWS CloudFormation 

---

assets/queries/ansible/aws/efs_without_kms/metadata.json
assets/queries/ansible/aws/efs_without_kms/query.rego
assets/queries/ansible/aws/efs_without_kms/test/negative.yaml
assets/queries/ansible/aws/efs_without_kms/test/positive.yaml
assets/queries/ansible/aws/efs_without_kms/test/positive_expected_result.json
assets/queries/cloudFormation/efs_not_encrypted_with_kms_cmk/metadata.json
assets/queries/cloudFormation/efs_not_encrypted_with_kms_cmk/test/positive_expected_result.json
assets/queries/terraform/aws/efs_without_kms_key_id/metadata.json

Closes #2330 
- Add a query to check if AWS EFS has KMS enabled through the key ID, in Ansible.
-Besides adding the query, updates the query name in Terraform and CloudFormation to the unified name.

Add query to check if EFS doesn't have KMS. Closes #2330

---

assets/queries/terraform/aws/api_gateway_stage_without_api_gateway_usage_plan_associated/metadata.json
assets/queries/terraform/aws/api_gateway_stage_without_api_gateway_usage_plan_associated/query.rego
assets/queries/terraform/aws/api_gateway_stage_without_api_gateway_usage_plan_associated/test/negative.tf
assets/queries/terraform/aws/api_gateway_stage_without_api_gateway_usage_plan_associated/test/positive.tf
assets/queries/terraform/aws/api_gateway_stage_without_api_gateway_usage_plan_associated/test/positive_expected_result.json

Closes #2340
- Add support for query "API Gateway Stage Without API Gateway UsagePlan Associated".
- The query checks if there's an API Gateway UsagePlan resource that references an API Gateway Stage, through attributes `stage` and `api_id`, that should be same as `stage_name` and `rest_api_id`.

Add "API Gateway Stage Without API Gateway UsagePlan Associated" query for Terraform

---

assets/queries/ansible/aws/cloudfront_without_minimum_protocol_tls_1.2/metadata.json
assets/queries/ansible/aws/cloudfront_without_minimum_protocol_tls_1.2/query.rego
assets/queries/ansible/aws/cloudfront_without_minimum_protocol_tls_1.2/test/negative.yaml
assets/queries/ansible/aws/cloudfront_without_minimum_protocol_tls_1.2/test/positive.yaml
assets/queries/ansible/aws/cloudfront_without_minimum_protocol_tls_1.2/test/positive_expected_result.json
assets/queries/cloudFormation/cloudfront_without_minimum_protocol_tls_1.2/metadata.json
assets/queries/terraform/aws/cloudfront_without_minimum_protocol_tls_1.2/metadata.json
assets/queries/terraform/aws/cloudfront_without_minimum_protocol_tls_1.2/query.rego
assets/queries/terraform/aws/cloudfront_without_minimum_protocol_tls_1.2/test/negative.tf
assets/queries/terraform/aws/cloudfront_without_minimum_protocol_tls_1.2/test/positive.tf
assets/queries/terraform/aws/cloudfront_without_minimum_protocol_tls_1.2/test/positive_expected_result.json

Closes #2427
- Added support for query "CloudFront Without Minimum Protocol TLS 1.2" in Terraform and Ansible.
- The query checks if the attribute `minimum_protocol_version` is set to one of `{TLSv1.2_2018, TLSv1.2_2019}`

Add "CloudFront Without Minimum Protocol TLS 1.2" query for Terraform and Ansible

---

.github/workflows/go-ci.yml

- Increasing golangci-lint timeout to 5 minutes

Increasing timeout for golangci-lint to 5min

---

docs/integrations_ghactions.md

Closes #2466
- fixing typo `output-path` to `output_path`

Fixing typo in github actions integrations docs #2466

---

assets/queries/cloudFormation/ecr_image_tag_not_immutable/metadata.json
assets/queries/cloudFormation/ecr_image_tag_not_immutable/query.rego
assets/queries/cloudFormation/ecr_image_tag_not_immutable/test/negative1.yaml
assets/queries/cloudFormation/ecr_image_tag_not_immutable/test/negative2.json
assets/queries/cloudFormation/ecr_image_tag_not_immutable/test/positive1.yaml
assets/queries/cloudFormation/ecr_image_tag_not_immutable/test/positive2.json
assets/queries/cloudFormation/ecr_image_tag_not_immutable/test/positive_expected_result.json
assets/queries/terraform/aws/ecr_image_tag_not_immutable/metadata.json
assets/queries/terraform/aws/ecr_image_tag_not_immutable/query.rego
assets/queries/terraform/aws/ecr_image_tag_not_immutable/test/negative.tf
assets/queries/terraform/aws/ecr_image_tag_not_immutable/test/positive.tf
assets/queries/terraform/aws/ecr_image_tag_not_immutable/test/positive_expected_result.json

Closes #2397
- Adding ECR Imag Tag Not Immutable queries for Terraform and AWS CloudFormation.

Add ECR Image Tag Not Immutable query for Terraform and AWS CloudFormation 

---

assets/queries/ansible/aws/batch_job_definition_with_privileged_container_properties/metadata.json
assets/queries/ansible/aws/batch_job_definition_with_privileged_container_properties/query.rego
assets/queries/ansible/aws/batch_job_definition_with_privileged_container_properties/test/negative.yaml
assets/queries/ansible/aws/batch_job_definition_with_privileged_container_properties/test/positive.yaml
assets/queries/ansible/aws/batch_job_definition_with_privileged_container_properties/test/positive_expected_result.json
assets/queries/terraform/aws/batch_job_definition_with_privileged_container_properties/metadata.json
assets/queries/terraform/aws/batch_job_definition_with_privileged_container_properties/query.rego
assets/queries/terraform/aws/batch_job_definition_with_privileged_container_properties/test/negative.tf
assets/queries/terraform/aws/batch_job_definition_with_privileged_container_properties/test/positive.tf
assets/queries/terraform/aws/batch_job_definition_with_privileged_container_properties/test/positive_expected_result.json

Closes #2419
- Added support for query "Batch Job Definition With Privileged Container Properties" in Terraform and Ansible.
- The query checks if the attribute `privileged` is set to `true`.

Add "Batch Job Definition With Privileged Container Properties" query for Terraform and Ansible

---

.github/workflows/go-ci.yml
.golangci.yml

- `golangci-lint` is taking longer than usual, we should try different configurations to optimize its executions.

Optimize golangci-lint

---

assets/queries/cloudFormation/rds_db_instance_iam_auth_not_enabled/metadata.json
assets/queries/cloudFormation/rds_db_instance_iam_auth_not_enabled/query.rego
assets/queries/cloudFormation/rds_db_instance_iam_auth_not_enabled/test/negative1.yaml
assets/queries/cloudFormation/rds_db_instance_iam_auth_not_enabled/test/negative2.json
assets/queries/cloudFormation/rds_db_instance_iam_auth_not_enabled/test/positive1.yaml
assets/queries/cloudFormation/rds_db_instance_iam_auth_not_enabled/test/positive2.json
assets/queries/cloudFormation/rds_db_instance_iam_auth_not_enabled/test/positive3.yaml
assets/queries/cloudFormation/rds_db_instance_iam_auth_not_enabled/test/positive4.json
assets/queries/cloudFormation/rds_db_instance_iam_auth_not_enabled/test/positive_expected_result.json

Closes #2376 
- Add query support in CloudFormation to check if DB instances are not enabling database authentication

Add query to check if database auth is enabled. Closes #2376

---

assets/queries/cloudFormation/memcached_disabled/metadata.json
assets/queries/cloudFormation/memcached_disabled/query.rego
assets/queries/cloudFormation/memcached_disabled/test/negative1.yaml
assets/queries/cloudFormation/memcached_disabled/test/negative2.json
assets/queries/cloudFormation/memcached_disabled/test/positive1.yaml
assets/queries/cloudFormation/memcached_disabled/test/positive2.json
assets/queries/cloudFormation/memcached_disabled/test/positive_expected_result.json

Closes #2292
- Add support in CloudFormation for the query that checks if the engine used in ElastiCache clusters isn't memcached

Add query to check is memcached is disabled in elasticache. Closes #2292

---

assets/queries/terraform/kubernetes_pod/host_aliases_undefined_or_empty/metadata.json
assets/queries/terraform/kubernetes_pod/host_aliases_undefined_or_empty/query.rego
assets/queries/terraform/kubernetes_pod/host_aliases_undefined_or_empty/test/negative.tf
assets/queries/terraform/kubernetes_pod/host_aliases_undefined_or_empty/test/positive.tf
assets/queries/terraform/kubernetes_pod/host_aliases_undefined_or_empty/test/positive_expected_result.json

Closes #2441 
A Kubernetes Pod should have Host Aliases defined as to prevent the container from modifying the file after a pod's containers have already been started. This means the attribute 'spec.host_aliases' must be defined and not empty or null.

Add Host Aliases Undefined Or Empty query #2441

---

assets/queries/terraform/kubernetes/pod_or_container_without_security_context/metadata.json
assets/queries/terraform/kubernetes/pod_or_container_without_security_context/query.rego
assets/queries/terraform/kubernetes/pod_or_container_without_security_context/test/negative.tf
assets/queries/terraform/kubernetes/pod_or_container_without_security_context/test/positive.tf
assets/queries/terraform/kubernetes/pod_or_container_without_security_context/test/positive_expected_result.json

Closes #2513
- Support "Pod or Container Without Security Context" query for Terraform (same as "Pod or Container Without Security Context" for Kubernetes). It is necessary to check if the attribute `security_context` exists

Add "Pod or Container Without Security Context" query for Terraform Closes #2513

---

assets/queries/k8s/using_default_namespace/query.rego
assets/queries/terraform/kubernetes_pod/using_default_namespace/metadata.json
assets/queries/terraform/kubernetes_pod/using_default_namespace/query.rego
assets/queries/terraform/kubernetes_pod/using_default_namespace/test/negative.tf
assets/queries/terraform/kubernetes_pod/using_default_namespace/test/positive.tf
assets/queries/terraform/kubernetes_pod/using_default_namespace/test/positive_expected_result.json

Closes #2502
- Support "Using Default Namespace" query for Terraform (same as "Using Default Namespace" for Kubernetes). It is necessary to check if the attribute `metadata.namespace` is set to "default"

Add "Using Default Namespace" query for Terraform Closes #2502

---

assets/queries/terraform/kubernetes/container_is_privileged/metadata.json
assets/queries/terraform/kubernetes/container_is_privileged/query.rego
assets/queries/terraform/kubernetes/container_is_privileged/test/negative.tf
assets/queries/terraform/kubernetes/container_is_privileged/test/positive.tf
assets/queries/terraform/kubernetes/container_is_privileged/test/positive_expected_result.json

Closes #2536
- Support "Container Is Privileged" query for Terraform (same as "Container Is Privileged" for Kubernetes). It is necessary to check if the attribute `security_context.privileged `is set to true

Add "Container Is Privileged" for Terraform Closes #2536

---

assets/queries/terraform/kubernetes/cpu_limits_not_set/metadata.json
assets/queries/terraform/kubernetes/cpu_limits_not_set/query.rego
assets/queries/terraform/kubernetes/cpu_limits_not_set/test/negative.tf
assets/queries/terraform/kubernetes/cpu_limits_not_set/test/positive.tf
assets/queries/terraform/kubernetes/cpu_limits_not_set/test/positive_expected_result.json

Closes #2534
- Support "CPU Limits Not Set" query for Terraform (same as "CPU Limits Not Set" for Kubernetes). It is necessary to check if the attribute `resources.limits.cpu` exists

Add "CPU Limits Not Set" query for Terraform Closes #2534

---

assets/queries/terraform/kubernetes/secoomp_profile_is_not_configured/metadata.json
assets/queries/terraform/kubernetes/secoomp_profile_is_not_configured/query.rego
assets/queries/terraform/kubernetes/secoomp_profile_is_not_configured/test/negative.tf
assets/queries/terraform/kubernetes/secoomp_profile_is_not_configured/test/positive.tf
assets/queries/terraform/kubernetes/secoomp_profile_is_not_configured/test/positive_expected_result.json

Closes #2548
- Support "Seccomp Profile Is Not Configured" query for Terraform (same as "Seccomp Profile Is Not Configured" for Kubernetes). It is necessary to check if `object.get(metadata, "annotations", "undefined") == "undefined"`, `object.get(annotations, "${seccomp.security.alpha.kubernetes.io/defaultProfileName}", "undefined") == "undefined"` or `annotations["${seccomp.security.alpha.kubernetes.io/defaultProfileName}"] != "runtime/default"`

Add "Seccomp Profile Is Not Configured" query for Terraform Closes #2548

---

assets/queries/dockerfile/secrets_stored_in_dockerfile/query.rego

Closes #2486
- Excluding flag "-p" cases. This flag is not related to the password in a common scenario. "Flag -p is short for --parents - it creates the entire directory tree up to the given directory". Returns several false positives in cases like `mkdir -p` (where flag -p is considered as a command to create subdirectories of a directory) 

Update "Secrets Stored In Dockerfile" for Docker Closes #2486

---

assets/queries/terraform/kubernetes_pod/default_service_account_in_use/metadata.json
assets/queries/terraform/kubernetes_pod/default_service_account_in_use/query.rego
assets/queries/terraform/kubernetes_pod/default_service_account_in_use/test/negative.tf
assets/queries/terraform/kubernetes_pod/default_service_account_in_use/test/positive.tf
assets/queries/terraform/kubernetes_pod/default_service_account_in_use/test/positive_expected_result.json

Closes #2499
- Support "Default Service Account In Use" query for Terraform (same as "Default Service Account In Use" for Kubernetes). It is necessary to check if the attribute `automount_service_account_token` is undefined or set to true when `metadata.name` is equal to "default"

Add "Default Service Account In Use" query for Terraform Closes #2499

---

assets/queries/k8s/role_binding_to_default_service_account/query.rego
assets/queries/terraform/kubernetes_pod/role_binding_to_default_service_account/metadata.json
assets/queries/terraform/kubernetes_pod/role_binding_to_default_service_account/query.rego
assets/queries/terraform/kubernetes_pod/role_binding_to_default_service_account/test/negative.tf
assets/queries/terraform/kubernetes_pod/role_binding_to_default_service_account/test/positive.tf
assets/queries/terraform/kubernetes_pod/role_binding_to_default_service_account/test/positive_expected_result.json

Closes #2491
- Support "Role Binding To Default Service Account" query for Terraform (same as "Role Binding To Default Service Account" for Kubernetes). It is necessary to check if the attribute `subject[k].kind` is equal to "ServiceAccount" and `subject[k].name` is equal to "default"

Add "Role Binding To Default Service Account" query for Terraform Closes #2491

---

assets/queries/terraform/kubernetes_pod/workload_mounting_with_sensitive_os_directory/metadata.json
assets/queries/terraform/kubernetes_pod/workload_mounting_with_sensitive_os_directory/query.rego
assets/queries/terraform/kubernetes_pod/workload_mounting_with_sensitive_os_directory/test/negative.tf
assets/queries/terraform/kubernetes_pod/workload_mounting_with_sensitive_os_directory/test/positive.tf
assets/queries/terraform/kubernetes_pod/workload_mounting_with_sensitive_os_directory/test/positive_expected_result.json

Closes #2388 
- Support Workload Mounting With Sensitive OS Directory in Terraform (already exist in Kubernetes)

Add Workload Mounting With Sensitive OS Directory query Closes #2388

---

assets/queries/cloudFormation/ec2_subnet_mapping_public_ip_on_launch/metadata.json
assets/queries/cloudFormation/ec2_subnet_mapping_public_ip_on_launch/test/positive_expected_result.json
assets/queries/terraform/aws/ec2_instance_has_public_ip/metadata.json
assets/queries/terraform/aws/ec2_instance_has_public_ip/query.rego
assets/queries/terraform/aws/ec2_instance_has_public_ip/test/negative.tf
assets/queries/terraform/aws/ec2_instance_has_public_ip/test/positive.tf
assets/queries/terraform/aws/ec2_instance_has_public_ip/test/positive_expected_result.json

Closes #2529
- Adding EC2 Instance Has Public IP query for Terraform;
- Updating the name of the query in CloudFormation.

Add EC2 Instance Has Public IP query for Terraform 

---

assets/queries/k8s/container_runs_unmasked/query.rego
assets/queries/terraform/kubernetes_pod/container_runs_unmasked/metadata.json
assets/queries/terraform/kubernetes_pod/container_runs_unmasked/query.rego
assets/queries/terraform/kubernetes_pod/container_runs_unmasked/test/negative.tf
assets/queries/terraform/kubernetes_pod/container_runs_unmasked/test/positive.tf
assets/queries/terraform/kubernetes_pod/container_runs_unmasked/test/positive_expected_result.json

Closes #2482
Check if a container has full access (unmasked) to the host’s /proc command, which would allow to retrieve sensitive information and possibly change the kernel parameters in runtime.

Add Container Runs Unmasked query #2482

---

assets/queries/terraform/kubernetes_pod/cluster_admin_role_binding_with_super_user_permissions/metadata.json
assets/queries/terraform/kubernetes_pod/cluster_admin_role_binding_with_super_user_permissions/query.rego
assets/queries/terraform/kubernetes_pod/cluster_admin_role_binding_with_super_user_permissions/test/negative.tf
assets/queries/terraform/kubernetes_pod/cluster_admin_role_binding_with_super_user_permissions/test/positive.tf
assets/queries/terraform/kubernetes_pod/cluster_admin_role_binding_with_super_user_permissions/test/positive_expected_result.json

Closes #2391 
- Support Cluster Admin Rolebinding With Superuser Permissions in Terraform (already exist in Kubernetes)

Add Cluster Admin Rolebinding With Superuser Permissions query Closes #2391

---

assets/queries/terraform/kubernetes/service_type_is_nodeport/metadata.json
assets/queries/terraform/kubernetes/service_type_is_nodeport/query.rego
assets/queries/terraform/kubernetes/service_type_is_nodeport/test/negative.tf
assets/queries/terraform/kubernetes/service_type_is_nodeport/test/positive.tf
assets/queries/terraform/kubernetes/service_type_is_nodeport/test/positive_expected_result.json

Closes #2587
- Support "Service Type is NodePort" query for Terraform (same as "Service Type is NodePort" for Kubernetes). It is necessary to check if the attribute `spec.type` is equal "NodePort"

Add "Service Type is NodePort" for Terraform Closes #2587

---

assets/queries/cloudFormation/amazon_mq_broker_encryption_disabled/metadata.json
assets/queries/terraform/aws/amazon_mq_broker_encryption_disabled/metadata.json
assets/queries/terraform/aws/amazon_mq_broker_encryption_disabled/query.rego
assets/queries/terraform/aws/amazon_mq_broker_encryption_disabled/test/negative.tf
assets/queries/terraform/aws/amazon_mq_broker_encryption_disabled/test/positive.tf
assets/queries/terraform/aws/amazon_mq_broker_encryption_disabled/test/positive_expected_result.json

Closes #2591
- Added a query that checks if a 'AmazonMQ Broker' resource has encryption options configured for the broker. A `encryption_options` block must be defined, although it can be empty 

Add 'AmazonMQ Broker Encryption Disabled' query for Terraform

---

assets/queries/terraform/aws/api_gateway_deployment_without_api_gateway_usage_plan_associated/metadata.json
assets/queries/terraform/aws/api_gateway_deployment_without_api_gateway_usage_plan_associated/query.rego
assets/queries/terraform/aws/api_gateway_deployment_without_api_gateway_usage_plan_associated/test/negative.tf
assets/queries/terraform/aws/api_gateway_deployment_without_api_gateway_usage_plan_associated/test/positive.tf
assets/queries/terraform/aws/api_gateway_deployment_without_api_gateway_usage_plan_associated/test/positive_expected_result.json

Closes #2551
- Add support for query "API Gateway Deployment Without API Gateway UsagePlan Associated".
- The query checks if there's an API Gateway UsagePlan resource that references an API Gateway Deployment, through attributes `stage` and `api_id`, that should be same as `stage_name` and `rest_api_id`.

Add 'API Gateway Deployment Without API Gateway UsagePlan Associated' query for Terraform

---

assets/queries/terraform/kubernetes/not_limited_capabilities_for_pod_security_policy/metadata.json
assets/queries/terraform/kubernetes/not_limited_capabilities_for_pod_security_policy/query.rego
assets/queries/terraform/kubernetes/not_limited_capabilities_for_pod_security_policy/test/negative.tf
assets/queries/terraform/kubernetes/not_limited_capabilities_for_pod_security_policy/test/positive.tf
assets/queries/terraform/kubernetes/not_limited_capabilities_for_pod_security_policy/test/positive_expected_result.json

Closes #2541
- Support "Not Limited Capabilities For Pod Security Policy" query for Terraform (same as "Not Limited Capabilities For Pod Security Policy" for Kubernetes). It is necessary to check if the attribute `spec.required_drop_capabilities` is set

Add "Not Limited Capabilities For Pod Security Policy" query for Terraform  Closes #2541

---

assets/queries/terraform/kubernetes/psp_allows_sharing_host_ipc/metadata.json
assets/queries/terraform/kubernetes/psp_allows_sharing_host_ipc/query.rego
assets/queries/terraform/kubernetes/psp_allows_sharing_host_ipc/test/negative.tf
assets/queries/terraform/kubernetes/psp_allows_sharing_host_ipc/test/positive.tf
assets/queries/terraform/kubernetes/psp_allows_sharing_host_ipc/test/positive_expected_result.json

Closes #2574
-Pod Security Policy allows containers to share the host IPC namespace

Added PSP Allows Sharing Host IPC terraform query

---

assets/queries/k8s/service_account_allows_access_secrets/query.rego
assets/queries/terraform/kubernetes_pod/service_account_allows_access_secrets/metadata.json
assets/queries/terraform/kubernetes_pod/service_account_allows_access_secrets/query.rego
assets/queries/terraform/kubernetes_pod/service_account_allows_access_secrets/test/negative.tf
assets/queries/terraform/kubernetes_pod/service_account_allows_access_secrets/test/positive.tf
assets/queries/terraform/kubernetes_pod/service_account_allows_access_secrets/test/positive_expected_result.json

Closes #2503
Kubernetes_role and Kubernetes_cluster_role when binded, should not use get, list or watch as verbs.

Add Serv.Account Allows Access Secrets query #2503

---

assets/queries/terraform/kubernetes/permissive_access_to_create_pods/metadata.json
assets/queries/terraform/kubernetes/permissive_access_to_create_pods/query.rego
assets/queries/terraform/kubernetes/permissive_access_to_create_pods/test/negative1.tf
assets/queries/terraform/kubernetes/permissive_access_to_create_pods/test/negative2.tf
assets/queries/terraform/kubernetes/permissive_access_to_create_pods/test/positive1.tf
assets/queries/terraform/kubernetes/permissive_access_to_create_pods/test/positive2.tf
assets/queries/terraform/kubernetes/permissive_access_to_create_pods/test/positive_expected_result.json

Closes #2392 
- Support Permissive Access to Create Pods in Terraform (already exist in Kubernetes)

Add Permissive Access to Create Pods query Closes #2392

---

assets/queries/terraform/kubernetes/metadata_label_is_invalid/metadata.json
assets/queries/terraform/kubernetes/metadata_label_is_invalid/query.rego
assets/queries/terraform/kubernetes/metadata_label_is_invalid/test/negative.tf
assets/queries/terraform/kubernetes/metadata_label_is_invalid/test/positive.tf
assets/queries/terraform/kubernetes/metadata_label_is_invalid/test/positive_expected_result.json

Closes #2593
- Support "Metadata Label Is Invalid" query for Terraform (same as "Metadata Label Is Invalid" for Kubernetes). It is necessary to check if `regex.match("^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?$", labels[key]) == false`

Add "Metadata Label Is Invalid" query for Terraform Closes #2593

---

.github/workflows/go-ci-integration.yml

Closes #2616
- Run kics in silent mode during integration tests to keep stdout clean
- archive info.log and results.json to be analised locally in case of failure

Archive integration tests logs and results 

---

assets/queries/terraform/kubernetes/cronjob_deadline_not_configured/metadata.json
assets/queries/terraform/kubernetes/cronjob_deadline_not_configured/query.rego
assets/queries/terraform/kubernetes/cronjob_deadline_not_configured/test/negative.tf
assets/queries/terraform/kubernetes/cronjob_deadline_not_configured/test/positive.tf
assets/queries/terraform/kubernetes/cronjob_deadline_not_configured/test/positive_expected_result.json

Closes #2611
- Support "CronJob Deadline Not Configured" query for Terraform (same as "CronJob Deadline Not Configured" for Kubernetes). It is necessary to check if the attribute `spec.starting_deadline_seconds` is undefined

Add "CronJob Deadline Not Configured" query for Terraform Closes #2611

---

assets/queries/terraform/kubernetes/memory_limits_not_defined/metadata.json
assets/queries/terraform/kubernetes/memory_limits_not_defined/query.rego
assets/queries/terraform/kubernetes/memory_limits_not_defined/test/negative.tf
assets/queries/terraform/kubernetes/memory_limits_not_defined/test/positive.tf
assets/queries/terraform/kubernetes/memory_limits_not_defined/test/positive_expected_result.json

Closes #2622
- Support "Memory Limits Not Defined" query for Terraform (same as "Memory Limits Not Defined" for Kubernetes). It is necessary to check if the attribute `resources.limits.memory` is not set

Add "Memory Limits Not Defined" query for Terraform Closes #2622

---

assets/queries/terraform/kubernetes/missing_app_armor_config/metadata.json
assets/queries/terraform/kubernetes/missing_app_armor_config/query.rego
assets/queries/terraform/kubernetes/missing_app_armor_config/test/negative.tf
assets/queries/terraform/kubernetes/missing_app_armor_config/test/positive.tf
assets/queries/terraform/kubernetes/missing_app_armor_config/test/positive_expected_result.json

Closes #2404 
- Support Missing App Armor Config in Terraform (already exist in Kubernetes)

Add Missing App Armor Config query Closes #2404

---

assets/queries/k8s/network_policy_is_not_targeting_any_pod/query.rego
assets/queries/terraform/kubernetes/network_policy_is_not_targeting_any_pod/metadata.json
assets/queries/terraform/kubernetes/network_policy_is_not_targeting_any_pod/query.rego
assets/queries/terraform/kubernetes/network_policy_is_not_targeting_any_pod/test/negative.tf
assets/queries/terraform/kubernetes/network_policy_is_not_targeting_any_pod/test/positive.tf
assets/queries/terraform/kubernetes/network_policy_is_not_targeting_any_pod/test/positive_expected_result.json

Closes #2631
- Support "Network Policy Is Not Targeting Any Pod" query for Terraform (same as "Network Policy Is Not Targeting Any Pod" for Kubernetes). It is necessary to check if the attribute `spec.pod_selector.match_labels` is not targeting any pod. We need to exclude cases like `app = "${kubernetes_pod.test2.metadata.0.labels.app}"` in TF (this is a direct reference)
- Since "Each NetworkPolicy includes a podSelector which selects the grouping of pods to which the policy applies. The example policy selects pods with the label "role=db". An empty podSelector selects all pods in the namespace.", I changed `object.get(document.spec, "podSelector", "undefined") != null` to `object.get(document.spec.podSelector, "matchLabels", "undefined") != null` in …

Add "Network Policy Is Not Targeting Any Pod" query for Terraform Closes #2631

---

.github/workflows/update-docs-index.yaml
.github/workflows/update-docs-queries.yaml
.github/workflows/update-godownloader-script.yaml

- Small change to avoid a long queue of executions in the automated PR's workflows
- The workflow should cancel previous executions to only have the latest one completed

Cancel previous runs on new push for automated PR's workflows

---

assets/queries/terraform/kubernetes_pod/rbac_roles_with_read_secrets_permissions/metadata.json
assets/queries/terraform/kubernetes_pod/rbac_roles_with_read_secrets_permissions/query.rego
assets/queries/terraform/kubernetes_pod/rbac_roles_with_read_secrets_permissions/test/negative.tf
assets/queries/terraform/kubernetes_pod/rbac_roles_with_read_secrets_permissions/test/positive.tf
assets/queries/terraform/kubernetes_pod/rbac_roles_with_read_secrets_permissions/test/positive_expected_result.json

Closes #2383
- Support RBAC Roles with Read Secrets Permissions in Terraform (already exist in Kubernetes)

Add RBAC Roles with Read Secrets Permissions query Closes #2383

---

assets/queries/terraform/kubernetes/deployment_without_pod_disruption_budget/metadata.json
assets/queries/terraform/kubernetes/deployment_without_pod_disruption_budget/query.rego
assets/queries/terraform/kubernetes/deployment_without_pod_disruption_budget/test/negative.tf
assets/queries/terraform/kubernetes/deployment_without_pod_disruption_budget/test/positive.tf
assets/queries/terraform/kubernetes/deployment_without_pod_disruption_budget/test/positive_expected_result.json

Closes #2637
- Support "Deployment Without PodDisruptionBudget" query for Terraform (same as "Deployment Without PodDisruptionBudget" for Kubernetes). It is necessary to check if the attribute `spec.selector.match_labels` is not targeted by a PodDisruptionBudget. We need to exclude cases like `k8s-app2 = "${kubernetes_pod_disruption_budget.demo2.spec.selector.0.match_labels.k8s-app2}"` in TF (this is a direct reference)

Add "Deployment Without PodDisruptionBudget" query for Terraform Closes #2637

---

assets/queries/ansible/aws/efs_without_tags/metadata.json
assets/queries/ansible/aws/efs_without_tags/query.rego
assets/queries/ansible/aws/efs_without_tags/test/negative.yaml
assets/queries/ansible/aws/efs_without_tags/test/positive.yaml
assets/queries/ansible/aws/efs_without_tags/test/positive_expected_result.json

Closes #2655
- The query checks if there are any tags associated with the Elastic Filesystem.

Add 'EFS Without Tags' query for Ansible

---

.github/workflows/go-ci-integration.yml
.github/workflows/go-ci.yml

Reverts Checkmarx/kics#2678
We cannot use `paths-ignore` feature because both workflows are "required" in our CI pipelines.
The issue is described here: https://github.community/t/feature-request-conditional-required-checks/16761
We might be able to workaround this issue by the using any of the suggestions in the thread above:
- https://github.com/marketplace/actions/skip-duplicate-actions#skip-ignored-paths
- https://github.com/technote-space/get-diff-action
cc: @joaoReigota1 @felipe-avelar @ruigomescx

Revert "Docs changes should not trigger CI #2677"

---

docs/getting-started.md
internal/console/kics.go

Closes #2690 #2691
- Added flag 'ci' to remove unwanted output for CI environment ( only print log messages)
- Fixed Bug where flag 'no-color' wasn't removing colors from log messages

Added New Flag 'ci'

---

assets/queries/k8s/service_account_token_automount_not_disabled/query.rego
assets/queries/terraform/kubernetes/service_account_token_automount_not_disabled/metadata.json
assets/queries/terraform/kubernetes/service_account_token_automount_not_disabled/query.rego
assets/queries/terraform/kubernetes/service_account_token_automount_not_disabled/test/negative.tf
assets/queries/terraform/kubernetes/service_account_token_automount_not_disabled/test/positive.tf
assets/queries/terraform/kubernetes/service_account_token_automount_not_disabled/test/positive_expected_result.json
assets/queries/terraform/kubernetes/service_type_is_nodeport/query.rego

Closes #2684
- Support "Service Account Token Automount Not Disabled" query for Terraform (same as "Service Account Token Automount Not Disabled" for Kubernetes). It is necessary to check if the attribute `automount_service_account_token` does not exist or is set to true

Add "Service Account Token Automount Not Disabled" query for Terraform Closes#2684

---

go.sum
internal/console/scan.go
pkg/parser/terraform/converter/default_test.go

Closes #2731
- Returns an error when inspector couldn't be created on scan, instead of only logging the error.

Fixed bug that panics KICS when queries path not exists

---

.github/workflows/release-dkr-image.yml
.github/workflows/update-docs-index.yaml
.github/workflows/update-install-script.yaml

Closes #2738
- This will fix the issue that github actions workflow runner could not fetch the latest tag and not running once a new release is published

Fixing fetching tags for shallow clones in release related workflows

---

assets/queries/terraform/kubernetes/secrets_as_environment_variables/metadata.json
assets/queries/terraform/kubernetes/secrets_as_environment_variables/query.rego
assets/queries/terraform/kubernetes/secrets_as_environment_variables/test/negative.tf
assets/queries/terraform/kubernetes/secrets_as_environment_variables/test/positive.tf
assets/queries/terraform/kubernetes/secrets_as_environment_variables/test/positive_expected_result.json

Closes #2701
- Support "Secrets As Environment Variables" query for Terraform (same as "Secrets As Environment Variables" for Kubernetes). It is necessary to check if the attributes `env.value_from.secret_key_ref` or `env_from.secret_ref` are set

Add "Secrets As Environment Variables" query for Terraform Closes #2701

---

docs/usage/commands.md
internal/console/kics.go

Fixes #2743
- disallow --ci and --silent to be passed at the same time

Disabling --ci and --silent flags #2743

---

assets/queries/k8s/root_containers_admitted/query.rego
assets/queries/k8s/root_containers_admitted/test/negative.yaml
assets/queries/k8s/root_containers_admitted/test/positive.yaml
assets/queries/terraform/kubernetes/root_containers_admitted/metadata.json
assets/queries/terraform/kubernetes/root_containers_admitted/query.rego
assets/queries/terraform/kubernetes/root_containers_admitted/test/negative.tf
assets/queries/terraform/kubernetes/root_containers_admitted/test/positive.tf
assets/queries/terraform/kubernetes/root_containers_admitted/test/positive_expected_result.json

Closes #2710
- Support "Root Containers Admitted" query for Terraform (same as "Root Containers Admitted" for Kubernetes). It is necessary to check if the attributes 'privileged' and 'allow_privilege_escalation' are set to true and 'run_as_user.rule' is not set to 'MustRunAsNonRoot'.
- Correcting "Root Containers Admitted" query for K8s (excluding the check of attribute 'readOnlyRootFilesystem') 

Add "Root Containers Admitted" query for Terraform Closes #2710

---

assets/queries/terraform/kubernetes/readiness_probe_is_not_configured/metadata.json
assets/queries/terraform/kubernetes/readiness_probe_is_not_configured/query.rego
assets/queries/terraform/kubernetes/readiness_probe_is_not_configured/test/negative.tf
assets/queries/terraform/kubernetes/readiness_probe_is_not_configured/test/positive.tf
assets/queries/terraform/kubernetes/readiness_probe_is_not_configured/test/positive_expected_result.json

Closes #2712
- Support "Readiness Probe Is Not Configured" query for Terraform (same as "Readiness Probe Is Not Configured" for Kubernetes). It is necessary to check if `spec.container.readiness_probe` is not set

Add "Readiness Probe Is Not Configured" query for Terraform Closes #2712

---

pkg/engine/provider/filesystem.go
pkg/engine/provider/filesystem_test.go

Closes #2761
- Fix bug where KICS was not rendering helm charts
- Increased unit testing on checkConditions func

Fix KICS not rendering Chart bug #2761

---

pkg/parser/terraform/variables.go

- When terraform.tfvars is not found on terraform directory, this will be logged

Added log when terraform.tfvars not found

---

internal/constants/constants.go
pkg/detector/default_detect.go
pkg/detector/docker/docker_detect.go
pkg/engine/source/source.go
pkg/model/model.go
pkg/resolver/helm/helm.go
tools/tools.go

Closes #2298
- Solving ineffassign issues
- Solving golint issues

Solve GoReport card issues Closes #2298

---

assets/queries/cloudFormation/api_gateway_deployment_without_access_log_setting/query.rego
assets/queries/terraform/aws/api_gateway_deployment_without_access_log_setting/metadata.json
assets/queries/terraform/aws/api_gateway_deployment_without_access_log_setting/query.rego
assets/queries/terraform/aws/api_gateway_deployment_without_access_log_setting/test/negative1.tf
assets/queries/terraform/aws/api_gateway_deployment_without_access_log_setting/test/positive1.tf
assets/queries/terraform/aws/api_gateway_deployment_without_access_log_setting/test/positive2.tf
assets/queries/terraform/aws/api_gateway_deployment_without_access_log_setting/test/positive3.tf
assets/queries/terraform/aws/api_gateway_deployment_without_access_log_setting/test/positive_expected_result.json

Closes #2760
- Support "API Gateway Deployment Without Access Log Setting" query for Terraform (same as "API Gateway Deployment Without Access Log Setting" for CloudFormation). It is necessary to check if: 
1.  when an API Gateway Deployment is set, there is no API Gateway Stage defined
2.  when an API Gateway Deployment is set, there is no API  Gateway Stage with 'access_log_settings' set associated with it
3.  an API Gateway Deployment has an API  Gateway Stage with 'access_log_settings' set associated but does not have the attribute 'stage_description' set

Add "API Gateway Deployment Without Access Log Setting" query for Terraform Closes #2760

---

assets/queries/ansible/aws/cmk_is_unusable/metadata.json
assets/queries/ansible/aws/cmk_is_unusable/query.rego
assets/queries/ansible/aws/cmk_is_unusable/test/negative1.yaml
assets/queries/ansible/aws/cmk_is_unusable/test/positive1.yaml
assets/queries/ansible/aws/cmk_is_unusable/test/positive2.yaml
assets/queries/ansible/aws/cmk_is_unusable/test/positive_expected_result.json
assets/queries/terraform/aws/cmk_is_unusable/metadata.json
assets/queries/terraform/aws/cmk_is_unusable/query.rego
assets/queries/terraform/aws/cmk_is_unusable/test/negative.tf
assets/queries/terraform/aws/cmk_is_unusable/test/positive.tf
assets/queries/terraform/aws/cmk_is_unusable/test/positive_expected_result.json

Closes #2766
- Support "CMK Is Unusable" query for Terraform and Ansible (same as "CMK Is Unusable" for CloudFormation)
1.  In the case of Terraform, it is necessary to check if the attribute 'is_enabled' is set to false
2.  In the case of Ansible, it is necessary to check if the attribute 'enabled' is set to false or if the attribute 'pending_window' is set

Add "CMK Is Unusable" query for Terraform and Ansible Closes #2766

---

assets/queries/cloudFormation/alb_is_not_integrated_with_waf/query.rego
assets/queries/cloudFormation/alb_is_not_integrated_with_waf/test/negative1.yaml
assets/queries/cloudFormation/alb_is_not_integrated_with_waf/test/negative2.json
assets/queries/cloudFormation/alb_is_not_integrated_with_waf/test/positive1.yaml
assets/queries/cloudFormation/alb_is_not_integrated_with_waf/test/positive3.json
assets/queries/cloudFormation/alb_is_not_integrated_with_waf/test/positive4.json
assets/queries/terraform/aws/alb_is_not_integrated_with_waf/metadata.json
assets/queries/terraform/aws/alb_is_not_integrated_with_waf/query.rego
assets/queries/terraform/aws/alb_is_not_integrated_with_waf/test/negative.tf
assets/queries/terraform/aws/alb_is_not_integrated_with_waf/test/positive.tf
assets/queries/terraform/aws/alb_is_not_integrated_with_waf/test/positive_expected_result.json

Closes #2783
- Support "ALB Is Not Integrated With WAF" query for Terraform (same as "ALB Is Not Integrated With WAF" for CloudFormation)
- Correcting expected and actual value in "ALB Is Not Integrated With WAF" query for CloudFormation

Add "ALB Is Not Integrated With WAF" query for Terraform Closes #2783

---

.github/workflows/release-nightly.yml

Closes #2798
- locking goreleaser version to v0.160.0 where this workflow worked
- skipping tag validation to avoid the goreleaser check preventing tags that do not follow semantic versioning pattern to trigger releases

Fix nightly releases being created as draft

---

.github/workflows/release-dkr-image.yml

Closes #2795
- Check if `published` release is not a prerelease before pushing changes

Release docker image is not being triggered on new release #2795

---

.github/workflows/mkdocs.yml
.github/workflows/update-docs-index.yaml

Closes #2799
- Pull latest changes in `gh-pages` before trying to add new commits to this branch
- Publish changes by the end of the workflow

Fixing documentation publishing without forcing changes #2799

---

assets/libraries/openapi/library.rego
assets/queries/openAPI/global_server_uses_http/metadata.json
assets/queries/openAPI/global_server_uses_http/query.rego
assets/queries/openAPI/global_server_uses_http/test/negative1.json
assets/queries/openAPI/global_server_uses_http/test/negative2.yaml
assets/queries/openAPI/global_server_uses_http/test/positive1.json
assets/queries/openAPI/global_server_uses_http/test/positive2.yaml
assets/queries/openAPI/global_server_uses_http/test/positive3.yaml
assets/queries/openAPI/global_server_uses_http/test/positive_expected_result.json
assets/queries/openAPI/security_empty_array/query.rego

Closes #2837
- Add query "Global Server Object Uses HTTP" that checks if:
- servers global object is defined
- servers global object count > 0
- servers global object's URL uses HTTP

Add query "Global Server Object Uses HTTP" #2837

---

assets/queries/openAPI/invalid_contact_email/metadata.json
assets/queries/openAPI/invalid_contact_email/query.rego
assets/queries/openAPI/invalid_contact_email/test/negative1.json
assets/queries/openAPI/invalid_contact_email/test/negative2.yaml
assets/queries/openAPI/invalid_contact_email/test/positive1.json
assets/queries/openAPI/invalid_contact_email/test/positive2.yaml
assets/queries/openAPI/invalid_contact_email/test/positive_expected_result.json

Closes #2879
- Added "Invalid Contact Email" query for OpenAPI (it checks if doc.info.contact.email does not match the defined URL validation regex

Added "Invalid Contact Email" query for OpenAPI #Closes2879

---

assets/queries/openAPI/responses_wrong_http_status_code/metadata.json
assets/queries/openAPI/responses_wrong_http_status_code/query.rego
assets/queries/openAPI/responses_wrong_http_status_code/test/negative1.json
assets/queries/openAPI/responses_wrong_http_status_code/test/negative2.yaml
assets/queries/openAPI/responses_wrong_http_status_code/test/positive1.json
assets/queries/openAPI/responses_wrong_http_status_code/test/positive2.yaml
assets/queries/openAPI/responses_wrong_http_status_code/test/positive_expected_result.json

Closes #2897
- Add Responses With Wrong HTTP Status Code query for OpenAPI 

Added Responses With Wrong HTTP Status Code query for OpenAPI #2897

---

assets/queries/terraform/kubernetes/non_kube_system_pod_with_host_mount/metadata.json
test/queries_content_test.go

Closes #2902
- Fixing the wrong platform field in the query's metadata
- adding more unit tests to catch this in the future

Fixing wrong platform and adding unit tests #2902

---

assets/queries/openAPI/schema_discriminator_not_required/metadata.json
assets/queries/openAPI/schema_discriminator_not_required/query.rego
assets/queries/openAPI/schema_discriminator_not_required/test/negative1.json
assets/queries/openAPI/schema_discriminator_not_required/test/negative2.json
assets/queries/openAPI/schema_discriminator_not_required/test/negative3.yaml
assets/queries/openAPI/schema_discriminator_not_required/test/negative4.yaml
assets/queries/openAPI/schema_discriminator_not_required/test/positive1.json
assets/queries/openAPI/schema_discriminator_not_required/test/positive2.json
assets/queries/openAPI/schema_discriminator_not_required/test/positive3.yaml
assets/queries/openAPI/schema_discriminator_not_required/test/positive4.yaml
assets/queries/openAPI/schema_discriminator_not_required/test/positive_expected_result.json

Closes #2900
- Added "Schema Discriminator Not Required" query for OpenAPI (it checks if 'schema.discriminator.propertyName' is not a required property)
- The Schema Object exists in Components Object, Parameter Object, and Media Type Object. 
- The Components Objects exists in OpenAPI Object. 

Add "Schema Discriminator Not Required" query for OpenAPI Closes#2900

---

assets/queries/openAPI/success_response_code_defined_patch_operation/metadata.json
assets/queries/openAPI/success_response_code_defined_patch_operation/query.rego
assets/queries/openAPI/success_response_code_defined_patch_operation/test/negative1.json
assets/queries/openAPI/success_response_code_defined_patch_operation/test/negative2.yaml
assets/queries/openAPI/success_response_code_defined_patch_operation/test/positive1.json
assets/queries/openAPI/success_response_code_defined_patch_operation/test/positive2.json
assets/queries/openAPI/success_response_code_defined_patch_operation/test/positive3.yaml
assets/queries/openAPI/success_response_code_defined_patch_operation/test/positive4.yaml
assets/queries/openAPI/success_response_code_defined_patch_operation/test/positive_expected_result.json

Closes #2923 
- Added "Success Response Code Defined for Patch Operation" query for OpenAPI

Added "Success Response Code Defined for Patch Operation" query for OpenAPI

---

assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/metadata.json
assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/query.rego
assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/negative1.json
assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/negative2.json
assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/negative3.yaml
assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/negative4.yaml
assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/positive1.json
assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/positive2.json
assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/positive3.yaml
assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/positive4.yaml
assets/queries/openAPI/invalid_content_type_for_multiple_files_upload/test/positive_expected_result.json

Closes #2919
- Added "Invalid Content Type For Multiple Files Upload" query for OpenAPI (it checks if Content Type is not set to 'multipart/form-data' in case of uploading an arbitrary number of files (array))

Added "Invalid Content Type For Multiple Files Upload" query for OpenAPI Closes#2919

---

assets/queries/openAPI/success_response_code_defined_put_operation/metadata.json
assets/queries/openAPI/success_response_code_defined_put_operation/query.rego
assets/queries/openAPI/success_response_code_defined_put_operation/test/negative1.json
assets/queries/openAPI/success_response_code_defined_put_operation/test/negative2.yaml
assets/queries/openAPI/success_response_code_defined_put_operation/test/positive1.json
assets/queries/openAPI/success_response_code_defined_put_operation/test/positive2.json
assets/queries/openAPI/success_response_code_defined_put_operation/test/positive3.yaml
assets/queries/openAPI/success_response_code_defined_put_operation/test/positive4.yaml
assets/queries/openAPI/success_response_code_defined_put_operation/test/positive_expected_result.json

Closes #2925 
- Added "Success Response Code Defined for Put Operation" query for OpenAPI

Added "Success Response Code Defined for Put Operation" query for OpenAPI (#2925)

---

assets/queries/openAPI/success_response_code_defined_post_operation/metadata.json
assets/queries/openAPI/success_response_code_defined_post_operation/query.rego
assets/queries/openAPI/success_response_code_defined_post_operation/test/negative1.json
assets/queries/openAPI/success_response_code_defined_post_operation/test/negative2.yaml
assets/queries/openAPI/success_response_code_defined_post_operation/test/positive1.json
assets/queries/openAPI/success_response_code_defined_post_operation/test/positive2.json
assets/queries/openAPI/success_response_code_defined_post_operation/test/positive3.yaml
assets/queries/openAPI/success_response_code_defined_post_operation/test/positive4.yaml
assets/queries/openAPI/success_response_code_defined_post_operation/test/positive_expected_result.json

Closes #2927 
- Added Success Response Code Defined for Post Operation query for OpenAPI 

Added Success Response Code Defined for Post Operation query for OpenAPI (#2927)

---

assets/queries/openAPI/server_url_not_absolute/metadata.json
assets/queries/openAPI/server_url_not_absolute/query.rego
assets/queries/openAPI/server_url_not_absolute/test/negative1.json
assets/queries/openAPI/server_url_not_absolute/test/negative2.json
assets/queries/openAPI/server_url_not_absolute/test/negative3.yaml
assets/queries/openAPI/server_url_not_absolute/test/negative4.yaml
assets/queries/openAPI/server_url_not_absolute/test/positive1.json
assets/queries/openAPI/server_url_not_absolute/test/positive2.json
assets/queries/openAPI/server_url_not_absolute/test/positive3.yaml
assets/queries/openAPI/server_url_not_absolute/test/positive4.yaml
assets/queries/openAPI/server_url_not_absolute/test/positive_expected_result.json

Closes #2930
- Added "Server URL Not Absolute" query for OpenAPI. It checks if 'servers[s].url' is not an absolute URL (in case of OpenAPI Object, Path Object and Operation Object). and if 'server.url' is not an absolute URL(in case of Link Object).
- The Link Object exists in Components Object and Response Object.
- The Response Object exists in Component Object and Operation Object.

Add "Server URL Not Absolute" query for OpenAPI #2930

---

.goreleaser.yml

Closes #2942
- Removed Windows + Arm arch build from goreleaser

Removed windows+arm64 from goreleaser #2942

---

internal/console/helpers/helpers.go
internal/console/helpers/helpers_test.go
internal/console/scan.go

Closes #2957 
- Changed KICS behaviour to generate reports if an `output-path` is defined without a file extension and `report-formats` is not defined

fix(report): generate report for all supported formats, if no format is defined

---

assets/queries/openAPI/server_object_variable_not_used/metadata.json
assets/queries/openAPI/server_object_variable_not_used/query.rego
assets/queries/openAPI/server_object_variable_not_used/test/negative1.json
assets/queries/openAPI/server_object_variable_not_used/test/negative2.json
assets/queries/openAPI/server_object_variable_not_used/test/negative3.yaml
assets/queries/openAPI/server_object_variable_not_used/test/negative4.yaml
assets/queries/openAPI/server_object_variable_not_used/test/positive1.json
assets/queries/openAPI/server_object_variable_not_used/test/positive2.json
assets/queries/openAPI/server_object_variable_not_used/test/positive3.yaml
assets/queries/openAPI/server_object_variable_not_used/test/positive4.yaml
assets/queries/openAPI/server_object_variable_not_used/test/positive_expected_result.json
assets/queries/openAPI/server_url_not_absolute/query.rego

Closes #2968
- Added "Server Object Variable Not Used" query for OpenAPI. It checks if 'servers[s].variables[x]' is not used in Service URL (in case of OpenAPI Object, Path Object and Operation Object). and if 'server.variables[x]' is not used in Service URL (in case of Link Object).
- The Link Object exists in Components Object and Response Object.
- The Response Object exists in Component Object and Operation Object.

feat(query): "Server Object Variable Not Used" for OpenAPI (#2968)

---

assets/queries/openAPI/operation_id_not_unique/metadata.json
assets/queries/openAPI/operation_id_not_unique/query.rego
assets/queries/openAPI/operation_id_not_unique/test/negative1.json
assets/queries/openAPI/operation_id_not_unique/test/negative2.yaml
assets/queries/openAPI/operation_id_not_unique/test/positive1.json
assets/queries/openAPI/operation_id_not_unique/test/positive2.yaml
assets/queries/openAPI/operation_id_not_unique/test/positive_expected_result.json

Closes #2970
- Added "OperationId Not Unique" query for OpenAPI. It checks if any 'operationId' defined in an Operation Object is not unique

feat(query): "OperationId Not Unique" for OpenAPI (#2970)

---

assets/queries/openAPI/schema_items_undefined/metadata.json
assets/queries/openAPI/schema_items_undefined/query.rego
assets/queries/openAPI/schema_items_undefined/test/negative1.json
assets/queries/openAPI/schema_items_undefined/test/negative2.json
assets/queries/openAPI/schema_items_undefined/test/negative3.yaml
assets/queries/openAPI/schema_items_undefined/test/negative4.yaml
assets/queries/openAPI/schema_items_undefined/test/positive1.json
assets/queries/openAPI/schema_items_undefined/test/positive2.json
assets/queries/openAPI/schema_items_undefined/test/positive3.yaml
assets/queries/openAPI/schema_items_undefined/test/positive4.yaml
assets/queries/openAPI/schema_items_undefined/test/positive_expected_result.json

Closes #2975
- Added "Schema Items Undefined" query for OpenAPI. It checks if 'schema items' is undefined when the schema is set to an array. 
- The Schema Object exists in Components Object, Parameter Object, and Media Type Object.
- The Components Objects exists in OpenAPI Object.

feat(query) "Schema Items Undefined" for OpenAPI (#2975)

---

assets/queries/openAPI/schema_with_both_read_only_and_write_only/metadata.json
assets/queries/openAPI/schema_with_both_read_only_and_write_only/query.rego
assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/negative1.json
assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/negative2.json
assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/negative3.yaml
assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/negative4.yaml
assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/positive1.json
assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/positive2.json
assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/positive3.yaml
assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/positive4.yaml
assets/queries/openAPI/schema_with_both_read_only_and_write_only/test/positive_expected_result.json

Closes #2981
- Added "Schema With Both ReadOnly And WriteOnly" query for OpenAPI. It checks if schema has both 'writeOnly' and 'readOnly' set to true
- The Schema Object exists in Components Object, Parameter Object, and Media Type Object.
- The Components Objects exists in OpenAPI Object.

feat(query): "Schema With Both ReadOnly And WriteOnly" for OpenAPI (#2981)

---

assets/queries/openAPI/security_operation_field_undefined/metadata.json
assets/queries/openAPI/security_operation_field_undefined/query.rego
assets/queries/openAPI/security_operation_field_undefined/test/negative1.json
assets/queries/openAPI/security_operation_field_undefined/test/negative2.yaml
assets/queries/openAPI/security_operation_field_undefined/test/positive1.json
assets/queries/openAPI/security_operation_field_undefined/test/positive2.json
assets/queries/openAPI/security_operation_field_undefined/test/positive3.yaml
assets/queries/openAPI/security_operation_field_undefined/test/positive4.yaml
assets/queries/openAPI/security_operation_field_undefined/test/positive_expected_result.json

Closes #2984 
- Added "Security Operation Field Undefined" query for OpenAPI. It checks if a security operation field is not defined in '#/components/securitySchemes'

feat(query): "Security Operation Field Undefined" for OpenAPI (#2984)

---

assets/queries/openAPI/schema_discriminator_property_not_string/metadata.json
assets/queries/openAPI/schema_discriminator_property_not_string/query.rego
assets/queries/openAPI/schema_discriminator_property_not_string/test/negative1.json
assets/queries/openAPI/schema_discriminator_property_not_string/test/negative2.json
assets/queries/openAPI/schema_discriminator_property_not_string/test/negative3.yaml
assets/queries/openAPI/schema_discriminator_property_not_string/test/negative4.yaml
assets/queries/openAPI/schema_discriminator_property_not_string/test/positive1.json
assets/queries/openAPI/schema_discriminator_property_not_string/test/positive2.json
assets/queries/openAPI/schema_discriminator_property_not_string/test/positive3.yaml
assets/queries/openAPI/schema_discriminator_property_not_string/test/positive4.yaml
assets/queries/openAPI/schema_discriminator_property_not_string/test/positive_expected_result.json

Closes #2989
- Added "Schema Discriminator Property Not String" query for OpenAPI (it checks if 'schema.discriminator.propertyName' is not set to a string)
- The Schema Object exists in Components Object, Parameter Object, and Media Type Object. 
- The Components Objects exists in OpenAPI Object. 

feat(query): "Schema Discriminator Property Not String" for OpenAPI (#2989)

---

pkg/parser/terraform/variables.go

- Changed terraform vars not found log level

fix(log): changed terraform vars not found log level

---

assets/queries/openAPI/property_allow_reserved_improperly_defined/metadata.json
assets/queries/openAPI/property_allow_reserved_improperly_defined/query.rego
assets/queries/openAPI/property_allow_reserved_improperly_defined/test/negative1.json
assets/queries/openAPI/property_allow_reserved_improperly_defined/test/negative2.yaml
assets/queries/openAPI/property_allow_reserved_improperly_defined/test/negative3.json
assets/queries/openAPI/property_allow_reserved_improperly_defined/test/negative4.yaml
assets/queries/openAPI/property_allow_reserved_improperly_defined/test/positive1.json
assets/queries/openAPI/property_allow_reserved_improperly_defined/test/positive2.yaml
assets/queries/openAPI/property_allow_reserved_improperly_defined/test/positive3.json
assets/queries/openAPI/property_allow_reserved_improperly_defined/test/positive4.yaml
assets/queries/openAPI/property_allow_reserved_improperly_defined/test/positive_expected_result.json

Closes #2993
- Added "Property 'allowReserved' Improperly Defined" query for OpenAPI. It checks if  'parameters[p].in' is not set to 'query' when 'parameters[p].allowReserved' is set

feat(query): "Property 'allowReserved' Improperly Defined" for OpenAPI (#2993)

---

assets/queries/openAPI/property_allow_empty_value_improperly_defined/metadata.json
assets/queries/openAPI/property_allow_empty_value_improperly_defined/query.rego
assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/negative1.json
assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/negative2.yaml
assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/negative3.json
assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/negative4.yaml
assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/positive1.json
assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/positive2.yaml
assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/positive3.json
assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/positive4.yaml
assets/queries/openAPI/property_allow_empty_value_improperly_defined/test/positive_expected_result.json

Closes #2995
- Added "Property 'allowEmptyValue' Improperly Defined" query for OpenAPI. It checks if  'parameters[p].in' is not set to 'query' when 'parameters[p].allowEmptyValue' is set

feat(query): "Property 'allowEmptyValue' Improperly Defined" for OpenAPI (#2995)

---

docs/integrations_jenkins.md

docs(jenkins): fixing image url in integration guide

---

assets/queries/openAPI/link_object_operation_id_does_not_target_an_operation_object/query.rego
assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/metadata.json
assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/query.rego
assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/negative1.json
assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/negative2.json
assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/negative3.json
assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/negative4.yaml
assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/negative5.yaml
assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/negative6.yaml
assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/positive1.json
assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/positive2.json
assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/positive3.json
assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/positive4.yaml
assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/positive5.yaml
assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/positive6.yaml
assets/queries/openAPI/link_object_with_both_operation_id_and_operation_ref/test/positive_expected_result.json

Closes #3026
-  Added "Link Object With Both 'operationId' And 'operationRef" query for OpenAPI (it checks if Link Object has has both 'operationId' and 'operationRef' defined)
- Correcting "Link Object OperationId Does Not Target Operation Object": wrong access to 'links'

feat(query): "Link Object With Both 'operationId' And 'operationRef'" for OpenAPI (#3026)

---

e2e/cli_test.go

Closes #
- Add new E2E test scenarios that cover the new flags & status codes.
| Test Name   | Description                                                                                                                                                                                                                            | Expected Output | Exit Status Code |
|-------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------|------------------|
| E2E-CLI-017 |                                                  KICS scan command with the -v (--verbose) flag should display …

test(e2e): new E2E test scenarios (second iteration)

---

assets/queries/openAPI/header_response_named_as_content_type/metadata.json
assets/queries/openAPI/header_response_named_as_content_type/query.rego
assets/queries/openAPI/header_response_named_as_content_type/test/negative1.json
assets/queries/openAPI/header_response_named_as_content_type/test/negative2.yaml
assets/queries/openAPI/header_response_named_as_content_type/test/positive1.json
assets/queries/openAPI/header_response_named_as_content_type/test/positive2.yaml
assets/queries/openAPI/header_response_named_as_content_type/test/positive_expected_result.json

Closes #3009
- Added "Header Response Named as 'Content-Type'" query for OpenAPI. It checks if  some header of Response Object is named as 'Content-Type'
- The Response Object exists in  Components Object and Operation Object.

feat(query): "Header Response Named as 'Content-Type'" for OpenAPI (#3009)

---

docs/CONTRIBUTING.md
docs/about.md
docs/configuration-file.md
docs/getting-started.md
docs/queries.md
docs/usage/commands.md
e2e/fixtures/E2E_CLI_002
e2e/fixtures/E2E_CLI_003
e2e/fixtures/E2E_CLI_004
e2e/fixtures/E2E_CLI_010
e2e/fixtures/E2E_CLI_016_INVALID_SCAN_FLAG
internal/console/scan.go
pkg/engine/inspector.go
pkg/engine/inspector_test.go
test/queries_content_test.go
test/queries_test.go
test/similarity_id_test.go

Closes #3047
- add --timeout flag that determines the number of seconds a rego query will be evaluated until it gets canceled.
- add the flag to the documentation
- small fixes across .md files

feat(cli): parametrizing query execution timeout #3047

---

assets/libraries/openapi/library.rego
assets/queries/openAPI/header_parameter_named_as_authorization/metadata.json
assets/queries/openAPI/header_parameter_named_as_authorization/query.rego
assets/queries/openAPI/header_parameter_named_as_authorization/test/negative1.json
assets/queries/openAPI/header_parameter_named_as_authorization/test/negative2.yaml
assets/queries/openAPI/header_parameter_named_as_authorization/test/negative3.json
assets/queries/openAPI/header_parameter_named_as_authorization/test/negative4.yaml
assets/queries/openAPI/header_parameter_named_as_authorization/test/positive1.json
assets/queries/openAPI/header_parameter_named_as_authorization/test/positive2.yaml
assets/queries/openAPI/header_parameter_named_as_authorization/test/positive3.json
assets/queries/openAPI/header_parameter_named_as_authorization/test/positive4.yaml
assets/queries/openAPI/header_parameter_named_as_authorization/test/positive_expected_result.json

Closes #3005
- Added "Header Parameter Named as 'Authorization' query for OpenAPI. It checks if  'parameters[p].name' is 'Authorization' when 'parameters[p].in' is 'header'

feat(query): "Header Parameter Named as 'Authorization'" for OpenAPI (#3005)

---

assets/queries/openAPI/schema_object_empty/metadata.json
assets/queries/openAPI/schema_object_empty/query.rego
assets/queries/openAPI/schema_object_empty/test/negative1.json
assets/queries/openAPI/schema_object_empty/test/negative2.json
assets/queries/openAPI/schema_object_empty/test/negative3.yaml
assets/queries/openAPI/schema_object_empty/test/negative4.yaml
assets/queries/openAPI/schema_object_empty/test/positive1.json
assets/queries/openAPI/schema_object_empty/test/positive2.json
assets/queries/openAPI/schema_object_empty/test/positive3.yaml
assets/queries/openAPI/schema_object_empty/test/positive4.yaml
assets/queries/openAPI/schema_object_empty/test/positive_expected_result.json

Closes #3011
- Added "Schema Object is Empty" query for OpenAPI (it checks if the schema object is empty)
- The Schema Object exists in Components Object, Parameter Object, and Media Type Object. 
- The Components Objects exists in OpenAPI Object. 

feat(query): "Schema Object is Empty" for OpenAPI (#3011)

---

assets/queries/openAPI/invalid_license_url/metadata.json
assets/queries/openAPI/invalid_license_url/query.rego
assets/queries/openAPI/invalid_license_url/test/negative1.json
assets/queries/openAPI/invalid_license_url/test/negative2.yaml
assets/queries/openAPI/invalid_license_url/test/positive1.json
assets/queries/openAPI/invalid_license_url/test/positive2.yaml
assets/queries/openAPI/invalid_license_url/test/positive_expected_result.json

Closes #3019
- Added "Invalid License URL" query for OpenAPI (it checks if doc.info.license.url does not match the defined URL validation regex

feat(query): "Invalid License URL" for OpenAPI (#3019)

---

assets/queries/openAPI/operation_without_successful_http_status_code/metadata.json
assets/queries/openAPI/operation_without_successful_http_status_code/query.rego
assets/queries/openAPI/operation_without_successful_http_status_code/test/negative1.json
assets/queries/openAPI/operation_without_successful_http_status_code/test/negative2.yaml
assets/queries/openAPI/operation_without_successful_http_status_code/test/positive1.json
assets/queries/openAPI/operation_without_successful_http_status_code/test/positive2.yaml
assets/queries/openAPI/operation_without_successful_http_status_code/test/positive_expected_result.json

Closes #3022
- Added "Operation Without Successful HTTP Status Code" query for OpenAPI (it checks if responses of Operation Object has at least one successful HTTP status code defined)

feat(query): "Operation Without Successful HTTP Status Code" for OpenAPI (#3022)

---

assets/queries/openAPI/encoding_header_content_type_improperly_defined/metadata.json
assets/queries/openAPI/encoding_header_content_type_improperly_defined/query.rego
assets/queries/openAPI/encoding_header_content_type_improperly_defined/test/negative1.json
assets/queries/openAPI/encoding_header_content_type_improperly_defined/test/negative2.json
assets/queries/openAPI/encoding_header_content_type_improperly_defined/test/negative3.yaml
assets/queries/openAPI/encoding_header_content_type_improperly_defined/test/negative4.yaml
assets/queries/openAPI/encoding_header_content_type_improperly_defined/test/positive1.json
assets/queries/openAPI/encoding_header_content_type_improperly_defined/test/positive2.json
assets/queries/openAPI/encoding_header_content_type_improperly_defined/test/positive3.yaml
assets/queries/openAPI/encoding_header_content_type_improperly_defined/test/positive4.yaml
assets/queries/openAPI/encoding_header_content_type_improperly_defined/test/positive_expected_result.json

Closes #3024
- Added "Encoding Header 'Content-Type' Improperly Defined" query for OpenAPI. It checks if  'encoding[e]' defines 'Content-Type' in the 'headers' field

feat(query): "Encoding Header 'Content-Type' Improperly Defined" for OpenAPI (#3024)

---

assets/queries/openAPI/schema_discriminator_mismatch_defined_properties/metadata.json
assets/queries/openAPI/schema_discriminator_mismatch_defined_properties/query.rego
assets/queries/openAPI/schema_discriminator_mismatch_defined_properties/test/negative1.json
assets/queries/openAPI/schema_discriminator_mismatch_defined_properties/test/negative2.json
assets/queries/openAPI/schema_discriminator_mismatch_defined_properties/test/negative3.yaml
assets/queries/openAPI/schema_discriminator_mismatch_defined_properties/test/negative4.yaml
assets/queries/openAPI/schema_discriminator_mismatch_defined_properties/test/positive1.json
assets/queries/openAPI/schema_discriminator_mismatch_defined_properties/test/positive2.json
assets/queries/openAPI/schema_discriminator_mismatch_defined_properties/test/positive3.yaml
assets/queries/openAPI/schema_discriminator_mismatch_defined_properties/test/positive4.yaml
assets/queries/openAPI/schema_discriminator_mismatch_defined_properties/test/positive_expected_result.json

Closes #2991
- Added "Schema Discriminator Mismatch Defined Properties" query for OpenAPI (it checks if 'schema.discriminator.propertyName' is not set in 'properties')
- The Schema Object exists in Components Object, Parameter Object, and Media Type Object. 
- The Components Objects exists in OpenAPI Object. 

feat(query): "Schema Discriminator Mismatch Defined Properties" for OpenAPI (#2991)

---

assets/queries/common/passwords_and_secrets_in_infrastructure_code/query.rego
assets/queries/common/passwords_and_secrets_in_infrastructure_code/test/negative4.tf
assets/queries/common/passwords_and_secrets_in_infrastructure_code/test/positive5.dockerfile
assets/queries/common/passwords_and_secrets_in_infrastructure_code/test/positive_expected_result.json

Closes #3058 
- Optimize query

fix(query): optimized passwords and secrets query

---

.github/workflows/go-ci-coverage.yaml
.github/workflows/go-ci-integration.yml
.github/workflows/mkdocs.yml
.github/workflows/release-dkr-image-for-tag.yml
.github/workflows/release-dkr-image.yml
.github/workflows/release-nightly.yml
.github/workflows/release.yml
.github/workflows/update-docs-index.yaml
.github/workflows/update-docs-queries.yaml
.github/workflows/update-install-script.yaml
.goreleaser-nightly.yml
.goreleaser.yml
Dockerfile
Dockerfile.integration
Makefile
docs/usage/commands.md
internal/console/kics.go
internal/console/scan.go
internal/console/version.go
internal/constants/constants.go

Closes #3041
- add `KICS_COLLECT_TELEMETRY` environment variable that can disable sentry telemetry if set to `0` or `false`
- fixing ldflags provisioning for goreleaser, dockerfiles and github actions

feat(telemetry): opt-out telemetry and fix sentry dsn provisioning #3041

---

assets/queries/openAPI/parameter_object_content_with_multiple_entries/metadata.json
assets/queries/openAPI/parameter_object_content_with_multiple_entries/query.rego
assets/queries/openAPI/parameter_object_content_with_multiple_entries/test/negative1.json
assets/queries/openAPI/parameter_object_content_with_multiple_entries/test/negative2.json
assets/queries/openAPI/parameter_object_content_with_multiple_entries/test/negative3.yaml
assets/queries/openAPI/parameter_object_content_with_multiple_entries/test/negative4.yaml
assets/queries/openAPI/parameter_object_content_with_multiple_entries/test/positive1.json
assets/queries/openAPI/parameter_object_content_with_multiple_entries/test/positive2.json
assets/queries/openAPI/parameter_object_content_with_multiple_entries/test/positive3.yaml
assets/queries/openAPI/parameter_object_content_with_multiple_entries/test/positive4.yaml
assets/queries/openAPI/parameter_object_content_with_multiple_entries/test/positive_expected_result.json

Closes #3068
- Added "Parameter Object Content With Multiple Entries'" query for OpenAPI. It checks if  the map content property of the parameter object has multiple entries

feat(query): "Parameter Object Content With Multiple Entries" for OpenAPI (#3068)

---

assets/queries/openAPI/success_response_code_undefined_trace_operation/metadata.json
assets/queries/openAPI/success_response_code_undefined_trace_operation/query.rego
assets/queries/openAPI/success_response_code_undefined_trace_operation/test/negative1.json
assets/queries/openAPI/success_response_code_undefined_trace_operation/test/negative2.yaml
assets/queries/openAPI/success_response_code_undefined_trace_operation/test/positive1.json
assets/queries/openAPI/success_response_code_undefined_trace_operation/test/positive2.yaml
assets/queries/openAPI/success_response_code_undefined_trace_operation/test/positive_expected_result.json

Closes #3078
- Added "Success Response Code Undefined for Trace Operation" query for OpenAPI. It checks if trace operation does not have the '200' successful code set

feat(query): "Success Response Code Undefined for Trace Operation" for OpenAPI (#3078)

---

pkg/engine/similarity_id.go
pkg/engine/similarity_id_test.go

Closes #3055 
- Changed base path comparation, when trying to compute similarity-id

fix(similarity-id): scan is not computing the Similarity ID for file path

---

pkg/parser/utils/certificate_utils.go
pkg/parser/utils/swagger_utils.go

- fixing unhandled error objects in `swagger_utils.go` and `certificate_utils.go`

fix(sast): unhandled errors flagged by cxSAST

---

assets/libraries/openapi/library.rego
assets/queries/openAPI/header_parameter_named_as_content_type/metadata.json
assets/queries/openAPI/header_parameter_named_as_content_type/query.rego
assets/queries/openAPI/header_parameter_named_as_content_type/test/negative1.json
assets/queries/openAPI/header_parameter_named_as_content_type/test/negative2.yaml
assets/queries/openAPI/header_parameter_named_as_content_type/test/negative3.json
assets/queries/openAPI/header_parameter_named_as_content_type/test/negative4.yaml
assets/queries/openAPI/header_parameter_named_as_content_type/test/positive1.json
assets/queries/openAPI/header_parameter_named_as_content_type/test/positive2.yaml
assets/queries/openAPI/header_parameter_named_as_content_type/test/positive3.json
assets/queries/openAPI/header_parameter_named_as_content_type/test/positive4.yaml
assets/queries/openAPI/header_parameter_named_as_content_type/test/positive_expected_result.json

Closes #3007
- Added "Header Parameter Named as 'Content-Type'" query for OpenAPI. It checks if  'parameters[p].name' is 'Content-Type' when 'parameters[p].in' is 'header'

feat(query): "Header Parameter Named as 'Content-Type'" for OpenAPI (#3007)

---

assets/libraries/openapi/library.rego
assets/queries/openAPI/header_parameter_named_as_accept/metadata.json
assets/queries/openAPI/header_parameter_named_as_accept/query.rego
assets/queries/openAPI/header_parameter_named_as_accept/test/negative1.json
assets/queries/openAPI/header_parameter_named_as_accept/test/negative2.yaml
assets/queries/openAPI/header_parameter_named_as_accept/test/negative3.json
assets/queries/openAPI/header_parameter_named_as_accept/test/negative4.yaml
assets/queries/openAPI/header_parameter_named_as_accept/test/positive1.json
assets/queries/openAPI/header_parameter_named_as_accept/test/positive2.yaml
assets/queries/openAPI/header_parameter_named_as_accept/test/positive3.json
assets/queries/openAPI/header_parameter_named_as_accept/test/positive4.yaml
assets/queries/openAPI/header_parameter_named_as_accept/test/positive_expected_result.json

Closes #3002
- Added "Header Parameter Named as 'Accept'" query for OpenAPI. It checks if  'parameters[p].name' is 'Accept' when 'parameters[p].in' is 'header'

feat(query): "Header Parameter Named as 'Accept'" for OpenAPI (#3002)

---

assets/libraries/openapi/library.rego
assets/queries/openAPI/request_body_incorrect_ref/query.rego
assets/queries/openAPI/response_object_incorrect_ref/query.rego
assets/queries/openAPI/schema_object_incorrect_ref/metadata.json
assets/queries/openAPI/schema_object_incorrect_ref/query.rego
assets/queries/openAPI/schema_object_incorrect_ref/test/negative1.json
assets/queries/openAPI/schema_object_incorrect_ref/test/negative2.json
assets/queries/openAPI/schema_object_incorrect_ref/test/negative3.yaml
assets/queries/openAPI/schema_object_incorrect_ref/test/negative4.yaml
assets/queries/openAPI/schema_object_incorrect_ref/test/positive1.json
assets/queries/openAPI/schema_object_incorrect_ref/test/positive2.json
assets/queries/openAPI/schema_object_incorrect_ref/test/positive3.yaml
assets/queries/openAPI/schema_object_incorrect_ref/test/positive4.yaml
assets/queries/openAPI/schema_object_incorrect_ref/test/positive_expected_result.json

Closes #3072
- Added "Schema Object Incorrect Ref" query for OpenAPI. It checks if schema object reference does not point to '#components/schemas'
- Updated "Response Object With Incorrect Ref": keyExpectedValue and keyActualValue
- Updated "Request Body With Incorrect Ref" : issueType
- The function 'regex.match' was chosen to also cover cases when '$ref' is a remote or a URL reference (function 'startswith' just covers cases when '$ref' is a local reference - https://swagger.io/docs/specification/using-ref/)

feat(query): "Schema Object Incorrect Ref" for OpenAPI (#3072)

---

assets/queries/openAPI/success_response_code_undefined_get_operation/metadata.json
assets/queries/openAPI/success_response_code_undefined_get_operation/query.rego
assets/queries/openAPI/success_response_code_undefined_get_operation/test/negative1.json
assets/queries/openAPI/success_response_code_undefined_get_operation/test/negative2.yaml
assets/queries/openAPI/success_response_code_undefined_get_operation/test/positive1.json
assets/queries/openAPI/success_response_code_undefined_get_operation/test/positive2.yaml
assets/queries/openAPI/success_response_code_undefined_get_operation/test/positive_expected_result.json

Closes #3096
- Added "Success Response Code Undefined for Get Operation" query for OpenAPI. It checks if get operation does not have the '200' or '202' successful code set

feat(query): "Success Response Code Undefined for Get Operation" for OpenAPI (#3096)

---

assets/queries/openAPI/success_response_code_undefined_head_operation/metadata.json
assets/queries/openAPI/success_response_code_undefined_head_operation/query.rego
assets/queries/openAPI/success_response_code_undefined_head_operation/test/negative1.json
assets/queries/openAPI/success_response_code_undefined_head_operation/test/negative2.yaml
assets/queries/openAPI/success_response_code_undefined_head_operation/test/positive1.json
assets/queries/openAPI/success_response_code_undefined_head_operation/test/positive2.yaml
assets/queries/openAPI/success_response_code_undefined_head_operation/test/positive_expected_result.json

Closes #3091
- Added "Success Response Code Undefined for Head Operation" query for OpenAPI. It checks if head operation does not have the '200' or '202' successful code set

feat(query): "Success Response Code Undefined for Head Operation" for OpenAPI (#3091)

---

pkg/parser/utils/file_utils.go

fix(engine): move failed to read ssl cert and swagger spec to trace level

---

assets/queries/openAPI/request_body_object_with_incorrect_media_type/metadata.json
assets/queries/openAPI/request_body_object_with_incorrect_media_type/query.rego
assets/queries/openAPI/request_body_object_with_incorrect_media_type/test/negative1.json
assets/queries/openAPI/request_body_object_with_incorrect_media_type/test/negative2.json
assets/queries/openAPI/request_body_object_with_incorrect_media_type/test/negative3.yaml
assets/queries/openAPI/request_body_object_with_incorrect_media_type/test/negative4.yaml
assets/queries/openAPI/request_body_object_with_incorrect_media_type/test/positive1.json
assets/queries/openAPI/request_body_object_with_incorrect_media_type/test/positive2.json
assets/queries/openAPI/request_body_object_with_incorrect_media_type/test/positive3.yaml
assets/queries/openAPI/request_body_object_with_incorrect_media_type/test/positive4.yaml
assets/queries/openAPI/request_body_object_with_incorrect_media_type/test/positive_expected_result.json

Closes #3070
- Added "Request Body Object With Incorrect Media Type" query for OpenAPI. It checks if  the field 'content' of the request body object is not set to 'multipart' or 'application/x-www-form-urlencoded' when field 'encoding' is set

feat(query): "Request Body Object With Incorrect Media Type" for OpenAPI (#3070)

---

assets/queries/openAPI/invalid_global_external_documentation_url/metadata.json
assets/queries/openAPI/invalid_global_external_documentation_url/query.rego
assets/queries/openAPI/invalid_global_external_documentation_url/test/negative1.json
assets/queries/openAPI/invalid_global_external_documentation_url/test/negative2.yaml
assets/queries/openAPI/invalid_global_external_documentation_url/test/positive1.json
assets/queries/openAPI/invalid_global_external_documentation_url/test/positive2.yaml
assets/queries/openAPI/invalid_global_external_documentation_url/test/positive_expected_result.json

Closes #2999
- Added "Invalid Global External Documentation URL" query for OpenAPI (it checks if 'externalDocs.url' is not a valid URL)

feat(query): "Invalid Global External Documentation URL" for OpenAPI (#2999)

---

assets/queries/openAPI/response_code_missing/metadata.json
assets/queries/openAPI/response_code_missing/query.rego
assets/queries/openAPI/response_code_missing/test/negative1.json
assets/queries/openAPI/response_code_missing/test/negative2.json
assets/queries/openAPI/response_code_missing/test/negative3.yaml
assets/queries/openAPI/response_code_missing/test/negative4.yaml
assets/queries/openAPI/response_code_missing/test/positive1.json
assets/queries/openAPI/response_code_missing/test/positive2.json
assets/queries/openAPI/response_code_missing/test/positive3.yaml
assets/queries/openAPI/response_code_missing/test/positive4.yaml
assets/queries/openAPI/response_code_missing/test/positive_expected_result.json

Closes #3101
- Added "Response Code Missing" query for OpenAPI. It checks if:
- 500, 429 and 400 responses are not defined for all operations, except head operation.
- 415 response is not defined for the post, put, and patch operations. 
- 404 response is not defined for the get, put, head, delete operations.
- 200 response is not defined for options operation.
- 401 and 403 response are not defined for all operations when the security field is defined.

feat(query); "Response Code Missing" for OpenAPI (#3101)

---

assets/queries/openAPI/components_object_fixed_field_key_improperly_named/metadata.json
assets/queries/openAPI/components_object_fixed_field_key_improperly_named/query.rego
assets/queries/openAPI/components_object_fixed_field_key_improperly_named/test/negative1.json
assets/queries/openAPI/components_object_fixed_field_key_improperly_named/test/negative2.yaml
assets/queries/openAPI/components_object_fixed_field_key_improperly_named/test/positive1.json
assets/queries/openAPI/components_object_fixed_field_key_improperly_named/test/positive2.yaml
assets/queries/openAPI/components_object_fixed_field_key_improperly_named/test/positive_expected_result.json

Closes #3065
- Added "Components Object Fixed Field Key Improperly Named" query for OpenAPI. It checks if components object fixed fields (schemas, responses, parameters, examples, requestBodies, headers, securitySchemes, links, and callbacks) use keys that not match the following REGEX: `^[a-zA-Z0-9\\.\\-_]+$`

feat(query): "Components Object Fixed Field Key Improperly Named" for OpenAPI (#3065)

---

assets/queries/openAPI/encoding_map_key_mismatch_schema_defined_properties/metadata.json
assets/queries/openAPI/encoding_map_key_mismatch_schema_defined_properties/query.rego
assets/queries/openAPI/encoding_map_key_mismatch_schema_defined_properties/test/negative1.json
assets/queries/openAPI/encoding_map_key_mismatch_schema_defined_properties/test/negative2.json
assets/queries/openAPI/encoding_map_key_mismatch_schema_defined_properties/test/negative3.yaml
assets/queries/openAPI/encoding_map_key_mismatch_schema_defined_properties/test/negative4.yaml
assets/queries/openAPI/encoding_map_key_mismatch_schema_defined_properties/test/positive1.json
assets/queries/openAPI/encoding_map_key_mismatch_schema_defined_properties/test/positive2.json
assets/queries/openAPI/encoding_map_key_mismatch_schema_defined_properties/test/positive3.yaml
assets/queries/openAPI/encoding_map_key_mismatch_schema_defined_properties/test/positive4.yaml
assets/queries/openAPI/encoding_map_key_mismatch_schema_defined_properties/test/positive_expected_result.json

Closes #2997
- Added "Encoding Map Key Mismatch Schema Defined Properties" query for OpenAPI. It checks if  'encoding[e]' is not set in schema defined properties

feat(query): "Encoding Map Key Mismatch Schema Defined Properties" for OpenAPI (#2997)

---

pkg/kics/resolver_sink.go
pkg/parser/parser.go

Closes #3104
- Fixed scanning Helm chart with multiple types in kics returns a false error 

fix(parser): fixed scanning helm chart returns false error

---

internal/metrics/metrics.go

Closes #3080
- Check if metric value is NaN and if So return 0

fix(metrics): fix 'NaN' results on profiling cpu flag (#3080)

---

.github/workflows/mkdocs.yml
.github/workflows/update-docs-index.yaml

Closes #
- Added rebase to mike on gh actions workflows, so it uses lastest updates on gh-pages

fix(docs): added rebase when deploying mike

---

assets/queries/openAPI/default_response_undefined_operations/metadata.json
assets/queries/openAPI/default_response_undefined_operations/query.rego
assets/queries/openAPI/default_response_undefined_operations/test/negative1.json
assets/queries/openAPI/default_response_undefined_operations/test/negative2.yaml
assets/queries/openAPI/default_response_undefined_operations/test/positive1.json
assets/queries/openAPI/default_response_undefined_operations/test/positive2.json
assets/queries/openAPI/default_response_undefined_operations/test/positive3.yaml
assets/queries/openAPI/default_response_undefined_operations/test/positive4.yaml
assets/queries/openAPI/default_response_undefined_operations/test/positive_expected_result.json

Closes #3120 
- Created default response is undefined on operations query

feat(query): add 'default response is undefined on operations' query for openapi 3.0

---

assets/queries/openAPI/default_response_undefined_operations/metadata.json
assets/queries/openAPI/default_response_undefined_operations/query.rego
assets/queries/openAPI/default_response_undefined_operations/test/negative1.json
assets/queries/openAPI/default_response_undefined_operations/test/negative2.yaml
assets/queries/openAPI/default_response_undefined_operations/test/positive1.json
assets/queries/openAPI/default_response_undefined_operations/test/positive2.json
assets/queries/openAPI/default_response_undefined_operations/test/positive3.yaml
assets/queries/openAPI/default_response_undefined_operations/test/positive4.yaml
assets/queries/openAPI/default_response_undefined_operations/test/positive_expected_result.json

Signed-off-by: Felipe Avelar felipe.avelar@checkmarx.com
Closes #3120
Created default response is undefined on operations query

feat(query): add 'default response is undefined on operations' query for OpenAPI

---

assets/queries/openAPI/response_operations_body_schema_undefined/metadata.json
assets/queries/openAPI/response_operations_body_schema_undefined/query.rego
assets/queries/openAPI/response_operations_body_schema_undefined/test/negative1.json
assets/queries/openAPI/response_operations_body_schema_undefined/test/negative2.yaml
assets/queries/openAPI/response_operations_body_schema_undefined/test/positive1.json
assets/queries/openAPI/response_operations_body_schema_undefined/test/positive2.json
assets/queries/openAPI/response_operations_body_schema_undefined/test/positive3.json
assets/queries/openAPI/response_operations_body_schema_undefined/test/positive4.json
assets/queries/openAPI/response_operations_body_schema_undefined/test/positive5.yaml
assets/queries/openAPI/response_operations_body_schema_undefined/test/positive6.yaml
assets/queries/openAPI/response_operations_body_schema_undefined/test/positive7.yaml
assets/queries/openAPI/response_operations_body_schema_undefined/test/positive8.yaml
assets/queries/openAPI/response_operations_body_schema_undefined/test/positive_expected_result.json

schema" query for OpenAPI
Closes #3132 
- Added query that checks if an action different from `head` and has a code different from `204` or `304` response content is defined

feat(query): Added "Response on operations that should have a body has undefined" for OpenAPI

---

assets/queries/openAPI/response_operations_body_schema_incorrect_defined/metadata.json
assets/queries/openAPI/response_operations_body_schema_incorrect_defined/query.rego
assets/queries/openAPI/response_operations_body_schema_incorrect_defined/test/negative1.json
assets/queries/openAPI/response_operations_body_schema_incorrect_defined/test/negative2.yaml
assets/queries/openAPI/response_operations_body_schema_incorrect_defined/test/positive1.json
assets/queries/openAPI/response_operations_body_schema_incorrect_defined/test/positive2.json
assets/queries/openAPI/response_operations_body_schema_incorrect_defined/test/positive3.yaml
assets/queries/openAPI/response_operations_body_schema_incorrect_defined/test/positive4.yaml
assets/queries/openAPI/response_operations_body_schema_incorrect_defined/test/positive_expected_result.json

Closes #3137 
- Added query to check if a HEAD response or responses with 204 or 304 codes are defining content

feat(query): "Response on operations that should not have a body has declared content" for OpenAPI

---

.github/workflows/go-ci-integration.yml
.github/workflows/go-ci.yml

Closes #2728
- filtering changes in paths: `"docs/**"`, `"**/**.md"`, `"examples"` from triggering tests workflows

fix(ci): filtering paths that can trigger tests workflows #2728

---

assets/queries/terraform/aws/config_configuration_aggregator_to_all_regions_disabled/query.rego
assets/queries/terraform/aws/config_configuration_aggregator_to_all_regions_disabled/test/positive.tf
assets/queries/terraform/aws/config_configuration_aggregator_to_all_regions_disabled/test/positive_expected_result.json

Closes #3195
- Updated "Configuration Aggregator to All Regions Disabled" query for Terraform. It also checks if the property 'all_regions' is undefined

feat(query): update "Configuration Aggregator to All Regions Disabled" for Terraform (#3195)

---

assets/queries/terraform/aws/elasticache_redis_cluster_without_backup/metadata.json
assets/queries/terraform/aws/elasticache_redis_cluster_without_backup/query.rego
assets/queries/terraform/aws/elasticache_redis_cluster_without_backup/test/negative.tf
assets/queries/terraform/aws/elasticache_redis_cluster_without_backup/test/positive.tf
assets/queries/terraform/aws/elasticache_redis_cluster_without_backup/test/positive_expected_result.json

Closes #3218
- Added "ElastiCache Redis Cluster Without Backup" query for Terraform. It checks if ElastiCache Redis cluster does not have 'snapshot_retention_limit' higher than 0

feat(query): "ElastiCache Redis Cluster Without Backup" for Terraform (#3218)

---

assets/queries/terraform/aws/rds_cluster_with_backup_disabled/metadata.json
assets/queries/terraform/aws/rds_cluster_with_backup_disabled/query.rego
assets/queries/terraform/aws/rds_cluster_with_backup_disabled/test/negative1.tf
assets/queries/terraform/aws/rds_cluster_with_backup_disabled/test/positive1.tf
assets/queries/terraform/aws/rds_cluster_with_backup_disabled/test/positive_expected_result.json

Closes #3226
-  Added RDS Cluster With Backup Disabled query for Terraform
RDS Cluster backup retention period should be specifically defined

feat(query): Added RDS Cluster With Backup Disabled query for Terraform #3226

---

assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/metadata.json
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/query.rego
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/negative.tf
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/positive1.tf
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/positive2.tf
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/positive_expected_result.json

Closes #3247 
- Added "ElastiCache Replication Group Not Encrypted At Rest" query for Terraform. It checks if ElastiCache Replication Group is not encrypted at Rest through attribute 'at_rest_encryption_enabled'

feat(query): "ElastiCache Replication Group Not Encrypted At Rest" for Terraform (#3247)

---

assets/queries/terraform/aws/dax_cluster_not_encrypted/metadata.json
assets/queries/terraform/aws/dax_cluster_not_encrypted/query.rego
assets/queries/terraform/aws/dax_cluster_not_encrypted/test/negative1.tf
assets/queries/terraform/aws/dax_cluster_not_encrypted/test/positive1.tf
assets/queries/terraform/aws/dax_cluster_not_encrypted/test/positive_expected_result.json

Closes #3266
- DAX Cluster Not Encrypted query for Terraform
AWS DAX Cluster should have server-side encryption at rest

feat(query): Added DAX Cluster Not Encrypted query for Terraform #3266

---

assets/queries/terraform/aws/docdb_cluster_without_kms/metadata.json
assets/queries/terraform/aws/docdb_cluster_without_kms/query.rego
assets/queries/terraform/aws/docdb_cluster_without_kms/test/negative1.tf
assets/queries/terraform/aws/docdb_cluster_without_kms/test/positive1.tf
assets/queries/terraform/aws/docdb_cluster_without_kms/test/positive_expected_result.json

Closes #3269
- Added DOCDB Cluster Without KMS query for Terraform
AWS DOCDB Cluster should be encrypted with a KMS encryption key

feat(query): Added DOCDB Cluster Without KMS query for Terraform #3269

---

docs/usage/commands.md
examples/github/kics-docker-runner-sarif.yaml

- Update KICS docs after updating KICS github action to v1.2
- Adding section about profiling with KICS

docs(integrations): update integrations docs

---

assets/queries/terraform/aws/docdb_cluster_not_encrypted/metadata.json
assets/queries/terraform/aws/docdb_cluster_not_encrypted/query.rego
assets/queries/terraform/aws/docdb_cluster_not_encrypted/test/negative1.tf
assets/queries/terraform/aws/docdb_cluster_not_encrypted/test/positive1.tf
assets/queries/terraform/aws/docdb_cluster_not_encrypted/test/positive_expected_result.json

Closes #3271
- Added DOCDB Cluster Not Encrypted query for Terraform
AWS DOCDB Cluster storage should be encrypted

feat(query): Added DOCDB Cluster Not Encrypted query for Terraform #3271

---

assets/queries/terraform/aws/dynamodb_table_not_encrypted/metadata.json
assets/queries/terraform/aws/dynamodb_table_not_encrypted/query.rego
assets/queries/terraform/aws/dynamodb_table_not_encrypted/test/negative1.tf
assets/queries/terraform/aws/dynamodb_table_not_encrypted/test/positive1.tf
assets/queries/terraform/aws/dynamodb_table_not_encrypted/test/positive_expected_result.json

Closes #3273
- Added DynamoDB Table Not Encrypted query for Terraform
AWS DynamoDB Tables should have server-side encryption

feat(query): Added DynamoDB Table Not Encrypted query for Terraform #3273

---

assets/queries/openAPI/property_type_encoding_object_ignored/metadata.json
assets/queries/openAPI/property_type_encoding_object_ignored/query.rego
assets/queries/openAPI/property_type_encoding_object_ignored/test/negative1.json
assets/queries/openAPI/property_type_encoding_object_ignored/test/negative2.json
assets/queries/openAPI/property_type_encoding_object_ignored/test/negative3.yaml
assets/queries/openAPI/property_type_encoding_object_ignored/test/negative4.yaml
assets/queries/openAPI/property_type_encoding_object_ignored/test/positive1.json
assets/queries/openAPI/property_type_encoding_object_ignored/test/positive2.json
assets/queries/openAPI/property_type_encoding_object_ignored/test/positive3.yaml
assets/queries/openAPI/property_type_encoding_object_ignored/test/positive4.yaml
assets/queries/openAPI/property_type_encoding_object_ignored/test/positive_expected_result.json

Closes #3186
- Added "Property 'style' of Encoding Object Ignored" query for OpenAPI. It checks if the property 'style' of the encoding object is defined when the media type of the request body is not 'application/x-www-form-urlencoded'

feat(query): "Property 'style' of Encoding Object Ignored" for OpenAPI (#3186)

---

assets/queries/openAPI/components_response_definition_unused/metadata.json
assets/queries/openAPI/components_response_definition_unused/query.rego
assets/queries/openAPI/components_response_definition_unused/test/negative1.json
assets/queries/openAPI/components_response_definition_unused/test/negative2.yaml
assets/queries/openAPI/components_response_definition_unused/test/positive1.json
assets/queries/openAPI/components_response_definition_unused/test/positive2.yaml
assets/queries/openAPI/components_response_definition_unused/test/positive_expected_result.json

Closes #3235 
- Added "Components Response Definition Is Unused" for OpenAPI

feat(query): added "Components Response Definition Is Unused" for OpenAPI

---

assets/queries/terraform/aws/s3_bucket_object_not_encrypted/metadata.json
assets/queries/terraform/aws/s3_bucket_object_not_encrypted/query.rego
assets/queries/terraform/aws/s3_bucket_object_not_encrypted/test/negative1.tf
assets/queries/terraform/aws/s3_bucket_object_not_encrypted/test/positive1.tf
assets/queries/terraform/aws/s3_bucket_object_not_encrypted/test/positive_expected_result.json

Closes #3279
- Added S3 Bucket Object Not Encrypted query for Terraform
S3 Bucket Object should have server-side encryption enabled

feat(query): Added S3 Bucket Object Not Encrypted query for Terraform #3279

---

assets/queries/terraform/aws/api_gateway_method_settings_cache_not_encrypted/metadata.json
assets/queries/terraform/aws/api_gateway_method_settings_cache_not_encrypted/query.rego
assets/queries/terraform/aws/api_gateway_method_settings_cache_not_encrypted/test/negative1.tf
assets/queries/terraform/aws/api_gateway_method_settings_cache_not_encrypted/test/positive1.tf
assets/queries/terraform/aws/api_gateway_method_settings_cache_not_encrypted/test/positive_expected_result.json

Closes #3276
- Added API Gateway Method Settings Cache Not Encrypted query for Terraform
API Gateway Method Settings Cache should be encrypted

feat(query): Added API Gateway Method Settings Cache Not Encrypted #3276

---

internal/console/printer/printer.go

Closes #3155
- remove filepath.Clean from log path

fix(logs): Fix invalid log path not returning error #3155

---

assets/queries/terraform/aws/ec2_instance_monitoring_disabled/metadata.json
assets/queries/terraform/aws/ec2_instance_monitoring_disabled/query.rego
assets/queries/terraform/aws/ec2_instance_monitoring_disabled/test/negative1.tf
assets/queries/terraform/aws/ec2_instance_monitoring_disabled/test/positive1.tf
assets/queries/terraform/aws/ec2_instance_monitoring_disabled/test/positive2.tf
assets/queries/terraform/aws/ec2_instance_monitoring_disabled/test/positive_expected_result.json

- Check if AWS EC2 instance detailed monitoring is enabled to increase observability.

feat(query): 'EC2 instance monitoring disabled' for AWS Terraform

---

assets/queries/terraform/aws/sagemaker_notebook_instance_without_kms/metadata.json
assets/queries/terraform/aws/sagemaker_notebook_instance_without_kms/query.rego
assets/queries/terraform/aws/sagemaker_notebook_instance_without_kms/test/negative1.tf
assets/queries/terraform/aws/sagemaker_notebook_instance_without_kms/test/positive1.tf
assets/queries/terraform/aws/sagemaker_notebook_instance_without_kms/test/positive_expected_result.json

- Sagemaker Notebook Instance Without KMS query to Terraform
AWS SageMaker should encrypt model artifacts at rest using Amazon S3 server-side encryption with an AWS KMS

feat(query): Added Sagemaker Notebook Instance Without KMS query to Terraform

---

assets/queries/terraform/aws/secretsmanager_secret_without_kms/metadata.json
assets/queries/terraform/aws/secretsmanager_secret_without_kms/query.rego
assets/queries/terraform/aws/secretsmanager_secret_without_kms/test/negative1.tf
assets/queries/terraform/aws/secretsmanager_secret_without_kms/test/positive1.tf
assets/queries/terraform/aws/secretsmanager_secret_without_kms/test/positive_expected_result.json

- Added Secretsmanager Secret Without KMS query for Terraform
"AWS Secretmanager should use AWS KMS customer master key (CMK) to encrypt the secret values in the versions stored in the secret

feat(query): Added Secretsmanager Secret Without KMS query for Terraform

---

assets/queries/terraform/aws/athena_workgroup_not_encrypted/metadata.json
assets/queries/terraform/aws/athena_workgroup_not_encrypted/query.rego
assets/queries/terraform/aws/athena_workgroup_not_encrypted/test/negative1.tf
assets/queries/terraform/aws/athena_workgroup_not_encrypted/test/positive1.tf
assets/queries/terraform/aws/athena_workgroup_not_encrypted/test/positive_expected_result.json

- Added Athena Workgroup Not Encrypted query for Terraform
Athena Workgroup query results should be encrypted, for all queries that run in the workgroup

feat(query): Added Athena Workgroup Not Encrypted query for Terraform

---

assets/queries/terraform/aws/viewer_protocol_policy_allows_http/query.rego

- Updated Viewer Protocol Policy Allows HTTP query for Terraform
aws_cloudfront_distribution.ordered_cache_behavior can be an array

feat(query): Updated Viewer Protocol Policy Allows HTTP query for Terraform

---

pkg/kics/resolver_sink.go
pkg/kics/sink.go
pkg/parser/terraform/terraform.go

Closes #3304
- Fixed Bug with invalid terraform returning panic 
- Invalid files will now only be logged instead of returning an error

fix(parser): Fixed Bug with invalid terraform returning panic #3304

---

assets/queries/openAPI/property_explode_encoding_object_ignored/metadata.json
assets/queries/openAPI/property_explode_encoding_object_ignored/query.rego
assets/queries/openAPI/property_explode_encoding_object_ignored/test/negative1.json
assets/queries/openAPI/property_explode_encoding_object_ignored/test/negative2.json
assets/queries/openAPI/property_explode_encoding_object_ignored/test/negative3.yaml
assets/queries/openAPI/property_explode_encoding_object_ignored/test/negative4.yaml
assets/queries/openAPI/property_explode_encoding_object_ignored/test/positive1.json
assets/queries/openAPI/property_explode_encoding_object_ignored/test/positive2.json
assets/queries/openAPI/property_explode_encoding_object_ignored/test/positive3.yaml
assets/queries/openAPI/property_explode_encoding_object_ignored/test/positive4.yaml
assets/queries/openAPI/property_explode_encoding_object_ignored/test/positive_expected_result.json

Closes #3174
- Added "Property 'explode' of Encoding Object Ignored" query for OpenAPI. It checks if the property 'explode' of the encoding object is defined when the media type of the request body is not 'application/x-www-form-urlencoded'

feat(query): "Property 'explode' of Encoding Object Ignored" for OpenAPI (#3174)

---

assets/queries/terraform/aws/elasticsearch_domain_not_encrypted_node_to_node/metadata.json
assets/queries/terraform/aws/elasticsearch_domain_not_encrypted_node_to_node/query.rego
assets/queries/terraform/aws/elasticsearch_domain_not_encrypted_node_to_node/test/negative1.tf
assets/queries/terraform/aws/elasticsearch_domain_not_encrypted_node_to_node/test/positive1.tf
assets/queries/terraform/aws/elasticsearch_domain_not_encrypted_node_to_node/test/positive2.tf
assets/queries/terraform/aws/elasticsearch_domain_not_encrypted_node_to_node/test/positive_expected_result.json

- Added query "Elasticsearch Domain Not Encrypted Node To Node" query for Terraform

feat(query): added query "Elasticsearch Domain Not Encrypted Node To Node" query for Terraform

---

assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/metadata.json
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/query.rego
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/negative1.tf
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/positive1.tf
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/positive2.tf
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/positive_expected_result.json

- Added ElastiCache Replication Group Not Encrypted At Transit query for Terraform
ElastiCache Replication Group encryption should be enabled at Transit

feat(query): Added ElastiCache Replication Group Not Encrypted At Transit 

---

assets/queries/terraform/aws/ecs_task_definition_volume_not_encrypted/metadata.json
assets/queries/terraform/aws/ecs_task_definition_volume_not_encrypted/query.rego
assets/queries/terraform/aws/ecs_task_definition_volume_not_encrypted/test/negative1.tf
assets/queries/terraform/aws/ecs_task_definition_volume_not_encrypted/test/positive1.tf
assets/queries/terraform/aws/ecs_task_definition_volume_not_encrypted/test/positive2.tf
assets/queries/terraform/aws/ecs_task_definition_volume_not_encrypted/test/positive_expected_result.json

- Added ECS Task Definition Volume Not Encrypted query for Terraform
AWS ECS Task Definition EFS data in transit between AWS ECS host and AWS EFS server should be encrypted

feat(query): Added ECS Task Definition Volume Not Encrypted query for Terraform

---

assets/queries/terraform/aws/iam_user_with_access_to_console/metadata.json
assets/queries/terraform/aws/iam_user_with_access_to_console/query.rego
assets/queries/terraform/aws/iam_user_with_access_to_console/test/negative1.tf
assets/queries/terraform/aws/iam_user_with_access_to_console/test/positive1.tf
assets/queries/terraform/aws/iam_user_with_access_to_console/test/positive_expected_result.json

- Added IAM User With Access To Console query to Terraform
AWS IAM Users should not have access to the console

feat(query): Added IAM User With Access To Console query to Terraform

---

assets/libraries/openapi/library.rego
assets/queries/openAPI/numeric_schema_without_format/metadata.json
assets/queries/openAPI/numeric_schema_without_format/query.rego
assets/queries/openAPI/numeric_schema_without_format/test/negative1.json
assets/queries/openAPI/numeric_schema_without_format/test/negative2.json
assets/queries/openAPI/numeric_schema_without_format/test/negative3.yaml
assets/queries/openAPI/numeric_schema_without_format/test/negative4.yaml
assets/queries/openAPI/numeric_schema_without_format/test/positive1.json
assets/queries/openAPI/numeric_schema_without_format/test/positive2.json
assets/queries/openAPI/numeric_schema_without_format/test/positive3.yaml
assets/queries/openAPI/numeric_schema_without_format/test/positive4.yaml
assets/queries/openAPI/numeric_schema_without_format/test/positive_expected_result.json

- Added "Numeric Schema Without Format" query for OpenAPI. It checks if the numeric schema (type set to 'integer' or 'number') does not have 'format' defined
-  The function `is_operation` (in \kics\assets\libraries\openapi\library.rego) verifies if the path contains an operation. If true, keeps the type of operation and the response code related to it. This function is useful to discard HEAD operations with response code equal to '204' or '304' (through `content_allowed`)

feat(query): "Numeric Schema Without Format" for OpenAPI

---

assets/libraries/openapi/library.rego
assets/queries/openAPI/media_type_object_without_schema/metadata.json
assets/queries/openAPI/media_type_object_without_schema/query.rego
assets/queries/openAPI/media_type_object_without_schema/test/negative1.json
assets/queries/openAPI/media_type_object_without_schema/test/negative2.json
assets/queries/openAPI/media_type_object_without_schema/test/negative3.yaml
assets/queries/openAPI/media_type_object_without_schema/test/negative4.yaml
assets/queries/openAPI/media_type_object_without_schema/test/positive1.json
assets/queries/openAPI/media_type_object_without_schema/test/positive2.json
assets/queries/openAPI/media_type_object_without_schema/test/positive3.yaml
assets/queries/openAPI/media_type_object_without_schema/test/positive4.yaml
assets/queries/openAPI/media_type_object_without_schema/test/positive_expected_result.json

- Added "Media Type Object Without Schema" query for OpenAPI. It checks if the Media Type Object does not have 'schema' defined

feat(query): "Media Type Object Without Schema" for OpenAPI

---

assets/libraries/openapi/library.rego
assets/queries/openAPI/parameter_object_without_schema/metadata.json
assets/queries/openAPI/parameter_object_without_schema/query.rego
assets/queries/openAPI/parameter_object_without_schema/test/negative1.json
assets/queries/openAPI/parameter_object_without_schema/test/negative2.json
assets/queries/openAPI/parameter_object_without_schema/test/negative3.yaml
assets/queries/openAPI/parameter_object_without_schema/test/negative4.yaml
assets/queries/openAPI/parameter_object_without_schema/test/positive1.json
assets/queries/openAPI/parameter_object_without_schema/test/positive2.json
assets/queries/openAPI/parameter_object_without_schema/test/positive3.yaml
assets/queries/openAPI/parameter_object_without_schema/test/positive4.yaml
assets/queries/openAPI/parameter_object_without_schema/test/positive_expected_result.json

- Added "Parameter Object Without Schema" query for OpenAPI. It checks if the Parameter Object does not have 'schema' defined

feat(query): "Parameter Object Without Schema" for OpenAPI

---

assets/queries/terraform/aws/iam_role_policy_passrole_allows_all/metadata.json
assets/queries/terraform/aws/iam_role_policy_passrole_allows_all/query.rego
assets/queries/terraform/aws/iam_role_policy_passrole_allows_all/test/negative1.tf
assets/queries/terraform/aws/iam_role_policy_passrole_allows_all/test/positive1.tf
assets/queries/terraform/aws/iam_role_policy_passrole_allows_all/test/positive_expected_result.json

- Added IAM Role Policy passRole Allows All query for Terraform
Using the iam:passrole action with wildcards (*) in the resource can be overly permissive because it allows iam:passrole permissions on multiple resources

feat(query): Added IAM Role Policy passRole Allows All query for Terraform

---

assets/queries/openAPI/json_reference_does_not_exists_example/metadata.json
assets/queries/openAPI/json_reference_does_not_exists_example/query.rego
assets/queries/openAPI/json_reference_does_not_exists_example/test/negative1.json
assets/queries/openAPI/json_reference_does_not_exists_example/test/negative2.yaml
assets/queries/openAPI/json_reference_does_not_exists_example/test/positive1.json
assets/queries/openAPI/json_reference_does_not_exists_example/test/positive2.yaml
assets/queries/openAPI/json_reference_does_not_exists_example/test/positive_expected_result.json

- Added "Example JSON Reference Does Not Exists" query for OpenAPI

feat(query): add "Example JSON Reference Does Not Exists" query for OpenAPI

---

assets/queries/terraform/aws/ecr_repository_without_policy/metadata.json
assets/queries/terraform/aws/ecr_repository_without_policy/query.rego
assets/queries/terraform/aws/ecr_repository_without_policy/test/negative1.tf
assets/queries/terraform/aws/ecr_repository_without_policy/test/positive1.tf
assets/queries/terraform/aws/ecr_repository_without_policy/test/positive2.tf
assets/queries/terraform/aws/ecr_repository_without_policy/test/positive_expected_result.json

- Added ECR Repository Without Policy query for Terraform
ECR Repository should have Policies attached to it

feat(query): Added ECR Repository Without Policy query for Terraform

---

assets/queries/openAPI/cleartext_api_key_in_global_security/metadata.json
assets/queries/openAPI/cleartext_api_key_in_global_security/query.rego
assets/queries/openAPI/cleartext_api_key_in_global_security/test/negative1.json
assets/queries/openAPI/cleartext_api_key_in_global_security/test/negative2.yaml
assets/queries/openAPI/cleartext_api_key_in_global_security/test/positive1.json
assets/queries/openAPI/cleartext_api_key_in_global_security/test/positive2.yaml
assets/queries/openAPI/cleartext_api_key_in_global_security/test/positive_expected_result.json

- Added "Cleartext API Key In Global Security" query for OpenAPI. It checks if the API Key is not sent as cleartext in a header, cookie or query parameters over an unencrypted channel
The code below was not defined in the OpenAPI library in order to explicit in 'keyExpectedValue' and 'keyExpectedValue' what type of 'in' is set
```
ins := {"cookie", "header", "query"}
doc.components.securitySchemes[s].in == ins[z]
```

feat(query): "Cleartext API Key In Global Security" for OpenAPI

---

assets/queries/openAPI/cleartext_api_key_in_operation_security/metadata.json
assets/queries/openAPI/cleartext_api_key_in_operation_security/query.rego
assets/queries/openAPI/cleartext_api_key_in_operation_security/test/negative1.json
assets/queries/openAPI/cleartext_api_key_in_operation_security/test/negative2.yaml
assets/queries/openAPI/cleartext_api_key_in_operation_security/test/positive1.json
assets/queries/openAPI/cleartext_api_key_in_operation_security/test/positive2.yaml
assets/queries/openAPI/cleartext_api_key_in_operation_security/test/positive_expected_result.json

- Added "Cleartext API Key In Operation Security" query for OpenAPI. It checks if the API Key is not sent as cleartext in a header, cookie or query parameters over an unencrypted channel
The code below was not defined in the OpenAPI library in order to explicit in 'keyExpectedValue' and 'keyExpectedValue' what type of 'in' is set
```
ins := {"cookie", "header", "query"}
doc.components.securitySchemes[s].in == ins[z]
```

feat(query): "Cleartext API Key In Operation Security" for OpenAPI

---

assets/queries/openAPI/api_key_exposed_in_operation_security/metadata.json
assets/queries/openAPI/api_key_exposed_in_operation_security/query.rego
assets/queries/openAPI/api_key_exposed_in_operation_security/test/negative1.json
assets/queries/openAPI/api_key_exposed_in_operation_security/test/negative2.yaml
assets/queries/openAPI/api_key_exposed_in_operation_security/test/positive1.json
assets/queries/openAPI/api_key_exposed_in_operation_security/test/positive2.yaml
assets/queries/openAPI/api_key_exposed_in_operation_security/test/positive_expected_result.json

- Added "API Key Exposed In Operation Security" query for OpenAPI. It checks if the API Key is transported over the network header, cookie or query parameters
The code below was not defined in the OpenAPI library in order to explicit in 'keyExpectedValue' and 'keyExpectedValue' what type of 'in' is set
```
ins := {"cookie", "header", "query"}
doc.components.securitySchemes[s].in == ins[z]
```

feat(query): "API Key Exposed In Operation Security" for OpenAPI

---

assets/queries/openAPI/api_key_exposed_in_global_security_scheme/metadata.json
assets/queries/openAPI/api_key_exposed_in_global_security_scheme/query.rego
assets/queries/openAPI/api_key_exposed_in_global_security_scheme/test/negative1.json
assets/queries/openAPI/api_key_exposed_in_global_security_scheme/test/negative2.yaml
assets/queries/openAPI/api_key_exposed_in_global_security_scheme/test/positive1.json
assets/queries/openAPI/api_key_exposed_in_global_security_scheme/test/positive2.yaml
assets/queries/openAPI/api_key_exposed_in_global_security_scheme/test/positive_expected_result.json

- Added "API Key Exposed In Global Security Scheme" query for OpenAPI. It checks if the API Key is transported over the network header, cookie or query parameters
The code below was not defined in the OpenAPI library in order to explicit in 'keyExpectedValue' and 'keyExpectedValue' what type of 'in' is set
```
ins := {"cookie", "header", "query"}
doc.components.securitySchemes[s].in == ins[z]
```

feat(query): "API Key Exposed In Global Security Scheme" for OpenAPI

---

assets/queries/openAPI/array_schema_without_maximum_number_items/metadata.json
assets/queries/openAPI/array_schema_without_maximum_number_items/query.rego
assets/queries/openAPI/array_schema_without_maximum_number_items/test/negative1.json
assets/queries/openAPI/array_schema_without_maximum_number_items/test/negative2.json
assets/queries/openAPI/array_schema_without_maximum_number_items/test/negative3.yaml
assets/queries/openAPI/array_schema_without_maximum_number_items/test/negative4.yaml
assets/queries/openAPI/array_schema_without_maximum_number_items/test/positive1.json
assets/queries/openAPI/array_schema_without_maximum_number_items/test/positive2.json
assets/queries/openAPI/array_schema_without_maximum_number_items/test/positive3.yaml
assets/queries/openAPI/array_schema_without_maximum_number_items/test/positive4.yaml
assets/queries/openAPI/array_schema_without_maximum_number_items/test/positive_expected_result.json

- Added "Array Schema Without Maximum Number of Items" query for OpenAPI. It checks if the array schema does not have 'maxItems' set

feat(query): "Array Schema Without Maximum Number of Items" for OpenAPI

---

assets/queries/openAPI/security_schemes_using_oauth/metadata.json
assets/queries/openAPI/security_schemes_using_oauth/query.rego
assets/queries/openAPI/security_schemes_using_oauth/test/negative1.json
assets/queries/openAPI/security_schemes_using_oauth/test/negative2.yaml
assets/queries/openAPI/security_schemes_using_oauth/test/positive1.json
assets/queries/openAPI/security_schemes_using_oauth/test/positive2.yaml
assets/queries/openAPI/security_schemes_using_oauth/test/positive_expected_result.json

- Security Scheme Using Oauth 1.0
Oauth 1.0 is deprecated, OAuth2 should be used instead

feat(query): Added Security Scheme Using Oauth 1.0 query for OpenAPI

---

assets/queries/openAPI/unknown_schema_string_format/metadata.json
assets/queries/openAPI/unknown_schema_string_format/query.rego
assets/queries/openAPI/unknown_schema_string_format/test/negative1.json
assets/queries/openAPI/unknown_schema_string_format/test/negative2.json
assets/queries/openAPI/unknown_schema_string_format/test/negative3.yaml
assets/queries/openAPI/unknown_schema_string_format/test/negative4.yaml
assets/queries/openAPI/unknown_schema_string_format/test/positive1.json
assets/queries/openAPI/unknown_schema_string_format/test/positive2.json
assets/queries/openAPI/unknown_schema_string_format/test/positive3.yaml
assets/queries/openAPI/unknown_schema_string_format/test/positive4.yaml
assets/queries/openAPI/unknown_schema_string_format/test/positive_expected_result.json

- Added "Unknown Schema String Format" query for OpenAPI. It checks if the schema string format is not set to 'date', 'date-time', 'password', 'byte', 'binary', 'email', 'uuid', 'uri', 'hostname', 'ipv4' or 'ipv6'

feat(query): "Unknown Schema String Format" for OpenAPI

---

assets/queries/openAPI/security_schemes_http_unknown_scheme/metadata.json
assets/queries/openAPI/security_schemes_http_unknown_scheme/query.rego
assets/queries/openAPI/security_schemes_http_unknown_scheme/test/negative1.json
assets/queries/openAPI/security_schemes_http_unknown_scheme/test/negative2.yaml
assets/queries/openAPI/security_schemes_http_unknown_scheme/test/positive1.json
assets/queries/openAPI/security_schemes_http_unknown_scheme/test/positive2.yaml
assets/queries/openAPI/security_schemes_http_unknown_scheme/test/positive_expected_result.json

-  Added Security Scheme HTTP Unknown Scheme query for OpenAPI
Security Scheme HTTP scheme should be registered in the IANA Authentication Scheme registry

feat(query): Added Security Scheme HTTP Unknown Scheme query for OpenAPI

---

assets/libraries/openapi/library.rego
assets/queries/openAPI/callback_object_incorrect_ref/metadata.json
assets/queries/openAPI/callback_object_incorrect_ref/query.rego
assets/queries/openAPI/header_object_with_incorrect_ref/metadata.json
assets/queries/openAPI/header_object_with_incorrect_ref/query.rego
assets/queries/openAPI/header_object_with_incorrect_ref/test/negative1.json
assets/queries/openAPI/header_object_with_incorrect_ref/test/negative2.json
assets/queries/openAPI/header_object_with_incorrect_ref/test/negative3.yaml
assets/queries/openAPI/header_object_with_incorrect_ref/test/negative4.yaml
assets/queries/openAPI/header_object_with_incorrect_ref/test/positive1.json
assets/queries/openAPI/header_object_with_incorrect_ref/test/positive2.json
assets/queries/openAPI/header_object_with_incorrect_ref/test/positive3.yaml
assets/queries/openAPI/header_object_with_incorrect_ref/test/positive4.yaml
assets/queries/openAPI/header_object_with_incorrect_ref/test/positive_expected_result.json
assets/queries/openAPI/link_object_incorrect_ref/metadata.json
assets/queries/openAPI/link_object_incorrect_ref/query.rego
assets/queries/openAPI/parameter_object_incorrect_ref/metadata.json
assets/queries/openAPI/parameter_object_incorrect_ref/query.rego
assets/queries/openAPI/parameter_object_incorrect_ref/test/positive1.json
assets/queries/openAPI/parameter_object_incorrect_ref/test/positive_expected_result.json
assets/queries/openAPI/request_body_incorrect_ref/metadata.json
assets/queries/openAPI/request_body_incorrect_ref/query.rego
assets/queries/openAPI/response_object_incorrect_ref/metadata.json
assets/queries/openAPI/response_object_incorrect_ref/query.rego
assets/queries/openAPI/schema_object_incorrect_ref/metadata.json
assets/queries/openAPI/schema_object_incorrect_ref/query.rego

- Added "Header Object With Incorrect Ref" query for OpenAPI. It checks if header object reference does not point to '#/components/headers'
- Improving similar queries with the 'walk' function

feat(query): "Header Object With Incorrect Ref" for OpenAPI

---

assets/queries/openAPI/security_scheme_using_http_negotiate/metadata.json
assets/queries/openAPI/security_scheme_using_http_negotiate/query.rego
assets/queries/openAPI/security_scheme_using_http_negotiate/test/negative1.json
assets/queries/openAPI/security_scheme_using_http_negotiate/test/negative1.yaml
assets/queries/openAPI/security_scheme_using_http_negotiate/test/positive1.json
assets/queries/openAPI/security_scheme_using_http_negotiate/test/positive2.yaml
assets/queries/openAPI/security_scheme_using_http_negotiate/test/positive_expected_result.json

- Added Security Scheme Using HTTP Negotiate query for OpenAPI
Security Scheme HTTP should not be using negotiate authentication

feat(query): Added Security Scheme Using HTTP Negotiate query for OpenAPI

---

assets/queries/openAPI/parameters_name_in_should_be_unique/metadata.json
assets/queries/openAPI/parameters_name_in_should_be_unique/query.rego
assets/queries/openAPI/parameters_name_in_should_be_unique/test/negative1.json
assets/queries/openAPI/parameters_name_in_should_be_unique/test/negative2.yaml
assets/queries/openAPI/parameters_name_in_should_be_unique/test/positive1.json
assets/queries/openAPI/parameters_name_in_should_be_unique/test/positive2.yaml
assets/queries/openAPI/parameters_name_in_should_be_unique/test/positive_expected_result.json

- Parameters fields 'name' and 'in' should have unique combinations

feat(query): add "Parameters Name In Combination Should Be Unique" for OpenAPI

---

assets/libraries/openapi/library.rego
assets/queries/openAPI/schema_enum_invalid/metadata.json
assets/queries/openAPI/schema_enum_invalid/query.rego
assets/queries/openAPI/schema_enum_invalid/test/negative1.json
assets/queries/openAPI/schema_enum_invalid/test/negative2.json
assets/queries/openAPI/schema_enum_invalid/test/negative3.yaml
assets/queries/openAPI/schema_enum_invalid/test/negative4.yaml
assets/queries/openAPI/schema_enum_invalid/test/positive1.json
assets/queries/openAPI/schema_enum_invalid/test/positive2.json
assets/queries/openAPI/schema_enum_invalid/test/positive3.yaml
assets/queries/openAPI/schema_enum_invalid/test/positive4.yaml
assets/queries/openAPI/schema_enum_invalid/test/positive_expected_result.json

- Added "Schema Enum Invalid" query for OpenAPI. It checks if the 'enum' field is not consistent with the schema's type

feat(query): add "Schema Enum Invalid" for OpenAPI

---

assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/metadata.json
assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/query.rego
assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/test/negative1.json
assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/test/negative2.json
assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/test/negative3.yaml
assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/test/negative4.yaml
assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/test/negative5.json
assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/test/negative6.yaml
assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/test/negative7.yaml
assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/test/positive1.json
assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/test/positive2.json
assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/test/positive3.yaml
assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/test/positive4.yaml
assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/test/positive5.yaml
assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/test/positive6.yaml
assets/queries/openAPI/property_defining_maximum_not_greater_than_minimum/test/positive_expected_result.json

- Check if schema numeric types has `minimum` larger than `maximum`
- Check if schema array types has `minItems` larger than `maxItems`
- Check if schema string types has `minLength` larger than `maxLength`

feat(query): add "Property Defining Maximum Not Greater Than Minimum" for OpenAPI

---

assets/queries/openAPI/example_not_compliant_with_schema_type/metadata.json
assets/queries/openAPI/example_not_compliant_with_schema_type/query.rego
assets/queries/openAPI/example_not_compliant_with_schema_type/test/negative1.json
assets/queries/openAPI/example_not_compliant_with_schema_type/test/negative2.yaml
assets/queries/openAPI/example_not_compliant_with_schema_type/test/negative3.json
assets/queries/openAPI/example_not_compliant_with_schema_type/test/negative4.yaml
assets/queries/openAPI/example_not_compliant_with_schema_type/test/negative5.json
assets/queries/openAPI/example_not_compliant_with_schema_type/test/negative6.yaml
assets/queries/openAPI/example_not_compliant_with_schema_type/test/negative7.json
assets/queries/openAPI/example_not_compliant_with_schema_type/test/negative8.yaml
assets/queries/openAPI/example_not_compliant_with_schema_type/test/positive1.json
assets/queries/openAPI/example_not_compliant_with_schema_type/test/positive2.yaml
assets/queries/openAPI/example_not_compliant_with_schema_type/test/positive3.json
assets/queries/openAPI/example_not_compliant_with_schema_type/test/positive4.yaml
assets/queries/openAPI/example_not_compliant_with_schema_type/test/positive5.json
assets/queries/openAPI/example_not_compliant_with_schema_type/test/positive6.yaml
assets/queries/openAPI/example_not_compliant_with_schema_type/test/positive7.json
assets/queries/openAPI/example_not_compliant_with_schema_type/test/positive8.yaml
assets/queries/openAPI/example_not_compliant_with_schema_type/test/positive_expected_result.json

- Added Example Not Compliant With Schema Type query for OpenAPI
Examples values and fields should be compliant with the schema type

feat(query): Added Example Not Compliant With Schema Type query for OpenAPI

---

assets/queries/openAPI/schema_object_with_circular_ref/metadata.json
assets/queries/openAPI/schema_object_with_circular_ref/query.rego
assets/queries/openAPI/schema_object_with_circular_ref/test/negative1.json
assets/queries/openAPI/schema_object_with_circular_ref/test/negative2.yaml
assets/queries/openAPI/schema_object_with_circular_ref/test/positive1.json
assets/queries/openAPI/schema_object_with_circular_ref/test/positive2.yaml
assets/queries/openAPI/schema_object_with_circular_ref/test/positive_expected_result.json

- Added Schema Object With Circular Ref query for OpenAPI
Schema Object should not reference it self in 'allOf', 'oneOf', 'anyOf' and 'not' properties

feat(query): Added Schema Object With Circular Ref query for OpenAPI

---

.github/workflows/go-ci-metrics.yaml

fix(ci): adding python3 environment to metrics workflow

---

docs/dockerhub.md
docs/usage/commands.md
e2e/fixtures/E2E_CLI_001
e2e/fixtures/E2E_CLI_002
e2e/fixtures/E2E_CLI_003
e2e/fixtures/E2E_CLI_004
e2e/fixtures/E2E_CLI_010
e2e/fixtures/E2E_CLI_016_INVALID_FLAG
e2e/fixtures/E2E_CLI_016_INVALID_SCAN_FLAG
e2e/fixtures/E2E_CLI_016_INVALID_SHOTHAND
internal/console/kics.go

Closes #3141 
- Now --log-path does not contains a text with default behavior
- Also refactored kics.go to use "P functions" only when there is a shorthand

fix(docs): corrected docs to match KICS behavior

---

assets/queries/openAPI/property_allow_empty_value_ignored/metadata.json
assets/queries/openAPI/property_allow_empty_value_ignored/query.rego
assets/queries/openAPI/property_allow_empty_value_ignored/test/negative1.json
assets/queries/openAPI/property_allow_empty_value_ignored/test/negative2.yaml
assets/queries/openAPI/property_allow_empty_value_ignored/test/negative3.json
assets/queries/openAPI/property_allow_empty_value_ignored/test/negative4.yaml
assets/queries/openAPI/property_allow_empty_value_ignored/test/negative5.json
assets/queries/openAPI/property_allow_empty_value_ignored/test/negative6.yaml
assets/queries/openAPI/property_allow_empty_value_ignored/test/positive1.json
assets/queries/openAPI/property_allow_empty_value_ignored/test/positive2.yaml
assets/queries/openAPI/property_allow_empty_value_ignored/test/positive3.json
assets/queries/openAPI/property_allow_empty_value_ignored/test/positive4.yaml
assets/queries/openAPI/property_allow_empty_value_ignored/test/positive5.json
assets/queries/openAPI/property_allow_empty_value_ignored/test/positive6.yaml
assets/queries/openAPI/property_allow_empty_value_ignored/test/positive_expected_result.json

- Added "Property 'allowEmptyValue' Ignored" query for OpenAPI.
- Since property 'allowEmptyValue' is ignored in the following cases: {"sytle": "simple", "explode": false}, {"sytle": "simple", "explode": true}, {"sytle": "spaceDelimited", "explode": false}, {"sytle": "pipeDelimited", "explode": false}, and {"sytle": "deepObject", "explode": true}, we need to check:
- If `style` is set to `simple` or if it is undefined when `in` is set to `path` or `header` (by default, when `in` is set to `path` or `header`, `style` is `simple` (It is not necessary to check `explode` since it is ignored in both cases - explode set to false or explode set to true)
- If `style` is set to `spaceDelimited` or `pipeDelimited` when …

feat(query): add "Property 'allowEmptyValue' Ignored" for OpenAPI

---

go.mod
go.sum

chore(deps): bump ref nats-server 2.1.9 to 2.2.5

---

assets/queries/dockerfile/apt_get_missing_yes_flag_to_avoid_manual_input/query.rego
assets/queries/dockerfile/apt_get_missing_yes_flag_to_avoid_manual_input/test/negative.dockerfile

Closes #3391
- Updated "APT-GET Missing '-y' To Avoid Manual Input" query for Docker. It supports now the flag "-qy"

feat(query): update "APT-GET Missing '-y' To Avoid Manual Input" for Dockerfile (#3391)

---

assets/queries/openAPI/invalid_media_type_value/metadata.json
assets/queries/openAPI/invalid_media_type_value/query.rego
assets/queries/openAPI/invalid_media_type_value/test/negative1.json
assets/queries/openAPI/invalid_media_type_value/test/negative2.yaml
assets/queries/openAPI/invalid_media_type_value/test/positive1.json
assets/queries/openAPI/invalid_media_type_value/test/positive2.yaml
assets/queries/openAPI/invalid_media_type_value/test/positive_expected_result.json

- Added "Invalid Media Type Value" query for OpenAPI. It checks if the media type value does not match the following format: `<type>/<subtype>[+suffix][;parameters]`

feat(query): add "Invalid Media Type Value" for OpenAPI

---

pkg/parser/yaml/parser.go
pkg/parser/yaml/parser_test.go

Closes #3414
Since nested maps were being converted to type `map[interface{}]interface{}` json marshal was reporting an error
- Added converter to convert `map[interface{}]interface{}` values to `map[string]interface{}`

fix(parser): Fixed MarshalJSON Error on YAML Extend #3414

---

assets/queries/openAPI/schema_object_using_enum_with_keyword/metadata.json
assets/queries/openAPI/schema_object_using_enum_with_keyword/query.rego
assets/queries/openAPI/schema_object_using_enum_with_keyword/test/negative1.json
assets/queries/openAPI/schema_object_using_enum_with_keyword/test/negative2.yaml
assets/queries/openAPI/schema_object_using_enum_with_keyword/test/positive1.json
assets/queries/openAPI/schema_object_using_enum_with_keyword/test/positive2.yaml
assets/queries/openAPI/schema_object_using_enum_with_keyword/test/positive_expected_result.json

- Added Schema Object Using Enum With Keyword query to OpenAPI
Schema Object properties should not contain 'enum' and schema keywords

feat(query): Added Schema Object Using Enum With Keyword query to OpenAPI

---

assets/queries/openAPI/unknown_property/metadata.json
assets/queries/openAPI/unknown_property/query.rego
assets/queries/openAPI/unknown_property/test/negative1.json
assets/queries/openAPI/unknown_property/test/negative2.json
assets/queries/openAPI/unknown_property/test/negative3.json
assets/queries/openAPI/unknown_property/test/negative4.yaml
assets/queries/openAPI/unknown_property/test/negative5.yaml
assets/queries/openAPI/unknown_property/test/negative6.yaml
assets/queries/openAPI/unknown_property/test/positive1.json
assets/queries/openAPI/unknown_property/test/positive2.json
assets/queries/openAPI/unknown_property/test/positive3.json
assets/queries/openAPI/unknown_property/test/positive4.yaml
assets/queries/openAPI/unknown_property/test/positive5.yaml
assets/queries/openAPI/unknown_property/test/positive6.yaml
assets/queries/openAPI/unknown_property/test/positive_expected_result.json

- Added "Unknown Property" query for OpenAPI. It checks if the object in question has unknown properties. The objects were grouped as:
-  **Simple objects**: objects that have direct access to the fields, e.g., info, contact, license, etc.
```
"info": {
"title": "Simple API Overview",
"version": "1.0.0"
}
``` 
- **Map objects**: objects that are defined as a map, e.g., links, headers, responses, etc.
```
"responses": {
"200": {
"description": "OK"
}
}
``` 
- **Array objects**: objects that are defined as an array, e.g., tags, servers, etc.
```
"tags": [
{
"name": "pets",
"description": "Everything about your Pets",
"externalDocs": {
"url": "http://docs.my-api.com/pet-operations.htm"
}
]
``` 
**NOTE**:  It was …

feat(query): add "Unknown Property" for OpenAPI

---

docs/configuration-file.md
docs/dockerhub.md
docs/usage/commands.md
e2e/cli_test.go
e2e/fixtures/E2E_CLI_002
e2e/fixtures/E2E_CLI_003
e2e/fixtures/E2E_CLI_004
e2e/fixtures/E2E_CLI_010
e2e/fixtures/E2E_CLI_016_INVALID_SCAN_FLAG
internal/console/helpers/helpers.go
internal/console/kics_test.go
internal/console/scan.go
pkg/report/commons.go

Closes #2964 
- Added flag to define default name 
- Changed output-path behavior, now it will ignore paths with files

feat(cli): added flag to define default name

---

assets/queries/openAPI/path_ambiguous/metadata.json
assets/queries/openAPI/path_ambiguous/query.rego
assets/queries/openAPI/path_ambiguous/test/negative1.yaml
assets/queries/openAPI/path_ambiguous/test/negative2.json
assets/queries/openAPI/path_ambiguous/test/positive1.yaml
assets/queries/openAPI/path_ambiguous/test/positive2.json
assets/queries/openAPI/path_ambiguous/test/positive_expected_result.json

- This query checks if there is a path that, without template, is equal, so it will generate two occurrences when this happens, one for each path

feat(query): added "Path Is Ambiguous" query for OpenAPI

---

assets/queries/openAPI/security_requirement_object_with_wrong_scopes/metadata.json
assets/queries/openAPI/security_requirement_object_with_wrong_scopes/query.rego
assets/queries/openAPI/security_requirement_object_with_wrong_scopes/test/negative1.json
assets/queries/openAPI/security_requirement_object_with_wrong_scopes/test/negative2.yaml
assets/queries/openAPI/security_requirement_object_with_wrong_scopes/test/negative3.json
assets/queries/openAPI/security_requirement_object_with_wrong_scopes/test/negative4.yaml
assets/queries/openAPI/security_requirement_object_with_wrong_scopes/test/positive1.json
assets/queries/openAPI/security_requirement_object_with_wrong_scopes/test/positive2.yaml
assets/queries/openAPI/security_requirement_object_with_wrong_scopes/test/positive3.json
assets/queries/openAPI/security_requirement_object_with_wrong_scopes/test/positive4.yaml
assets/queries/openAPI/security_requirement_object_with_wrong_scopes/test/positive_expected_result.json

- Added Security Requirement Object With Wrong Scopes query for OpenAPI
Security Requirement Object should only have scopes defined for security schemes of type 'oauth2' and 'openIdConnect'

feat(query): Added Security Requirement Object With Wrong Scopes query for OpenAPI

---

assets/queries/openAPI/default_response_undefined_operations/query.rego
assets/queries/openAPI/header_parameter_named_as_accept/query.rego
assets/queries/openAPI/header_parameter_named_as_authorization/query.rego
assets/queries/openAPI/header_parameter_named_as_content_type/query.rego
assets/queries/openAPI/header_response_named_as_content_type/query.rego
assets/queries/openAPI/operation_without_successful_http_status_code/query.rego
assets/queries/openAPI/parameter_object_content_with_multiple_entries/query.rego
assets/queries/openAPI/parameter_object_schema_content/query.rego
assets/queries/openAPI/parameter_object_undefined_type/query.rego
assets/queries/openAPI/parameter_objects_headers_dup_name/query.rego
assets/queries/openAPI/path_parameter_not_required/query.rego
assets/queries/openAPI/path_server_uses_http/query.rego
assets/queries/openAPI/path_without_operation/query.rego
assets/queries/openAPI/paths_object_empty/query.rego
assets/queries/openAPI/property_allow_empty_value_improperly_defined/query.rego
assets/queries/openAPI/property_allow_reserved_improperly_defined/query.rego
assets/queries/openAPI/responses_wrong_http_status_code/query.rego
assets/queries/openAPI/success_response_code_undefined_delete_operation/query.rego
assets/queries/openAPI/success_response_code_undefined_patch_operation/query.rego
assets/queries/openAPI/success_response_code_undefined_post_operation/query.rego
assets/queries/openAPI/success_response_code_undefined_put_operation/query.rego

- Removed `openapi` from seach keys that it is wrong and, also, not useful

fix(query): removed openapi from openapi.paths search keys

---

pkg/analyzer/analyzer.go

Closes #3461
- Removed `spec` property from K8s file Analyzer

fix(analyzer): Removed spec property from K8s file Analyzer #3461

---

docs/results.md
pkg/report/model/gitlab_sast.go
pkg/report/model/gitlab_sast_test.go

Fixes a few issues in the GitLab SAST output format to conform with v13.1.0 of our SAST schema
- `Severity` should be titlecase
- `Category` is an enum of the report type
Relates to https://github.com/Checkmarx/kics/issues/1986
See discussion in https://github.com/Checkmarx/kics/pull/3432#issuecomment-849764618

fix(report): Update gitlab report fields to match proper formatting

---

assets/queries/ansible/azure/unrestricted_sql_server_acess/query.rego
assets/queries/ansible/azure/unrestricted_sql_server_acess/test/positive.yaml
assets/queries/terraform/azure/unrestricted_sql_server_acess/query.rego
assets/queries/terraform/azure/unrestricted_sql_server_acess/test/positive.tf

Closes #3444
- Updated Unrestricted SQL Server Access query for Terraform and Ansible 
The Azure feature Allow access to Azure services can be enabled by setting start_ip_address and end_ip_address to 0.0.0.0.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_firewall_rule#end_ip_address

update(query): Updated Unrestricted SQL Server Access query 

---

assets/queries/common/passwords_and_secrets_in_url/metadata.json
assets/queries/common/passwords_and_secrets_in_url/query.rego
assets/queries/common/passwords_and_secrets_in_url/test/negative1.yaml
assets/queries/common/passwords_and_secrets_in_url/test/negative2.yaml
assets/queries/common/passwords_and_secrets_in_url/test/negative3.yaml
assets/queries/common/passwords_and_secrets_in_url/test/negative4.tf
assets/queries/common/passwords_and_secrets_in_url/test/negative5.dockerfile
assets/queries/common/passwords_and_secrets_in_url/test/negative6.json
assets/queries/common/passwords_and_secrets_in_url/test/positive1.yaml
assets/queries/common/passwords_and_secrets_in_url/test/positive2.yaml
assets/queries/common/passwords_and_secrets_in_url/test/positive3.yaml
assets/queries/common/passwords_and_secrets_in_url/test/positive4.tf
assets/queries/common/passwords_and_secrets_in_url/test/positive5.dockerfile
assets/queries/common/passwords_and_secrets_in_url/test/positive6.yaml
assets/queries/common/passwords_and_secrets_in_url/test/positive7.json
assets/queries/common/passwords_and_secrets_in_url/test/positive8.json
assets/queries/common/passwords_and_secrets_in_url/test/positive_expected_result.json

Closes #2785
- Added Passwords And Secrets In URL common query 
Query to find passwords and secrets in URL

feat(query): Added Passwords And Secrets In URL common query #2785

---

assets/queries/ansible/azure/sql_server_ingress_from_any_ip/query.rego
assets/queries/ansible/azure/sql_server_ingress_from_any_ip/test/positive.yaml
assets/queries/ansible/azure/sql_server_ingress_from_any_ip/test/positive_expected_result.json
assets/queries/terraform/azure/sql_server_ingress_from_any_ip/query.rego

Closes #3443
-Updated SQLServer Ingress From Any IP query for Terraform and Ansible
The Azure feature Allow access to Azure services can be enabled by setting start_ip_address and end_ip_address to 0.0.0.0
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_firewall_rule#end_ip_address

refactor(query): Updated SQLServer Ingress From Any IP query for Terraform and Ansible

---

assets/queries/terraform/aws/policy_without_principal/metadata.json
assets/queries/terraform/aws/policy_without_principal/query.rego
assets/queries/terraform/aws/policy_without_principal/test/negative1.tf
assets/queries/terraform/aws/policy_without_principal/test/negative2.tf
assets/queries/terraform/aws/policy_without_principal/test/positive.tf
assets/queries/terraform/aws/policy_without_principal/test/positive_expected_result.json

- Added "Policy Without Principal" query for Terraform. It checks if a policy, except IAM identity-based policy, does not have the 'Principal' element defined

feat(query): "Policy Without Principal" for Terraform

---

assets/queries/cloudFormation/ecs_task_definition_invalid_cpu_or_memory/query.rego
assets/queries/dockerfile/pip_install_keeping_cached_packages/query.rego
assets/queries/dockerfile/run_using_wget_and_curl/query.rego
assets/queries/dockerfile/run_utilities_and_posix_commands/query.rego
pkg/detector/helper.go

Closes #2010
- Fixed detector, contains str2 will now look ahead from str1 IDX

fix(detector): Fixed bug with detector getting the wrong line #2010

---

docs/roadmap.md

Remove sprint/milestone concepts, they are internal
Remove ETA, community help is welcomed

docs(roadmap): redesign roadmap page

---

assets/queries/terraform/azure/ad_admin_not_configured_for_sql_server/query.rego

Closes #3437
- Added case where `server_name` is passed like `server_name= azurerm_sql_server.test.name` and removed checking the `resource_group`

update(query): Updated AD Admin Not Configured For SQL Server for Terraform

---

assets/queries/terraform/aws/public_and_private_ec2_share_role/metadata.json
assets/queries/terraform/aws/public_and_private_ec2_share_role/query.rego
assets/queries/terraform/aws/public_and_private_ec2_share_role/test/negative.tf
assets/queries/terraform/aws/public_and_private_ec2_share_role/test/positive.tf
assets/queries/terraform/aws/public_and_private_ec2_share_role/test/positive_expected_result.json

- Added "Public and Private EC2 Share Role" query for Terraform. It checks if a public and a private EC2 instances shares the same role through the same `iam_instance_profile`

feat(query): add "Public and Private EC2 Share Role" for Terraform

---

assets/libraries/terraform/library.rego
assets/queries/terraform/aws/efs_with_vulnerable_policy/metadata.json
assets/queries/terraform/aws/efs_with_vulnerable_policy/query.rego
assets/queries/terraform/aws/efs_with_vulnerable_policy/test/negative.tf
assets/queries/terraform/aws/efs_with_vulnerable_policy/test/positive.tf
assets/queries/terraform/aws/efs_with_vulnerable_policy/test/positive_expected_result.json
assets/queries/terraform/aws/kms_key_with_vulnerable_policy/query.rego
assets/queries/terraform/aws/kms_key_with_vulnerable_policy/test/negative.tf

- Added "EFS With Vulnerable Policy" query for Terraform. It checks if the EFS (Elastic File System) policy defines wildcards in  'Principal' or 'Action'

feat(query): add "EFS With Vulnerable Policy" for Terraform

---

assets/libraries/terraform/library.rego
assets/queries/terraform/aws/elasticsearch_domain_with_vulnerable_policy/metadata.json
assets/queries/terraform/aws/elasticsearch_domain_with_vulnerable_policy/query.rego
assets/queries/terraform/aws/elasticsearch_domain_with_vulnerable_policy/test/negative.tf
assets/queries/terraform/aws/elasticsearch_domain_with_vulnerable_policy/test/positive.tf
assets/queries/terraform/aws/elasticsearch_domain_with_vulnerable_policy/test/positive_expected_result.json
assets/queries/terraform/aws/kms_key_with_vulnerable_policy/query.rego
assets/queries/terraform/aws/kms_key_with_vulnerable_policy/test/negative.tf

- Added "Elasticsearch Domain With Vulnerable Policy" query for Terraform. It checks if the Elasticsearch Domain policy defines wildcards in 'Principal' or 'Action'
- Added 'check_principal' function to Terraform library

feat(query): add "Elasticsearch Domain With Vulnerable Policy" for Terraform

---

assets/queries/terraform/aws/lambda_with_vulnerable_policy/metadata.json
assets/queries/terraform/aws/lambda_with_vulnerable_policy/query.rego
assets/queries/terraform/aws/lambda_with_vulnerable_policy/test/negative.tf
assets/queries/terraform/aws/lambda_with_vulnerable_policy/test/positive.tf
assets/queries/terraform/aws/lambda_with_vulnerable_policy/test/positive_expected_result.json

- Added "Lambda With Vulnerable Policy" query for Terraform. It checks if the Lambda policy defines wildcard in the attribute 'action'. It is not necessary to check the attribute 'principal' since Terraform does not support it as you can see [here](https://github.com/hashicorp/terraform-provider-aws/issues/2776)

feat(query): add "Lambda With Vulnerable Policy" for Terraform

---

assets/libraries/terraform/library.rego
assets/queries/terraform/aws/cloudwatch_logs_destination_with_vulnerable_policy/metadata.json
assets/queries/terraform/aws/cloudwatch_logs_destination_with_vulnerable_policy/query.rego
assets/queries/terraform/aws/cloudwatch_logs_destination_with_vulnerable_policy/test/negative.tf
assets/queries/terraform/aws/cloudwatch_logs_destination_with_vulnerable_policy/test/positive.tf
assets/queries/terraform/aws/cloudwatch_logs_destination_with_vulnerable_policy/test/positive_expected_result.json
assets/queries/terraform/aws/rest_api_with_vulnerable_policy/metadata.json
assets/queries/terraform/aws/rest_api_with_vulnerable_policy/query.rego
assets/queries/terraform/aws/rest_api_with_vulnerable_policy/test/positive_expected_result.json

- Added "CloudWatch Logs Destination With Vulnerable Policy" query for Terraform. It checks if the CloudWatch Logs Destination policy defines wildcards in 'principals' or 'actions'

feat(query): add "CloudWatch Logs Destination With Vulnerable Policy" for Terraform

---

assets/libraries/terraform/library.rego
assets/queries/terraform/aws/secrets_manager_with_vulnerable_policy/metadata.json
assets/queries/terraform/aws/secrets_manager_with_vulnerable_policy/query.rego
assets/queries/terraform/aws/secrets_manager_with_vulnerable_policy/test/negative.tf
assets/queries/terraform/aws/secrets_manager_with_vulnerable_policy/test/positive.tf
assets/queries/terraform/aws/secrets_manager_with_vulnerable_policy/test/positive_expected_result.json

- Added "Secrets Manager With Vulnerable Policy" query for Terraform. It checks if the Secrets Manager policy defines wildcards in 'Principal' or 'Action'

feat(query): add "Secrets Manager With Vulnerable Policy" for Terraform

---

assets/queries/terraform/aws/s3_bucket_public_acl_overridden_by_public_access_block/metadata.json
assets/queries/terraform/aws/s3_bucket_public_acl_overridden_by_public_access_block/query.rego
assets/queries/terraform/aws/s3_bucket_public_acl_overridden_by_public_access_block/test/negative.tf
assets/queries/terraform/aws/s3_bucket_public_acl_overridden_by_public_access_block/test/positive.tf
assets/queries/terraform/aws/s3_bucket_public_acl_overridden_by_public_access_block/test/positive_expected_result.json

- Added "S3 Bucket Public ACL Overridden By Public Access Block" query for Terraform. It checks if the S3 bucket public access is overridden by S3 bucket Public Access Block when the following attributes are set to true - 'block_public_acls', 'block_public_policy', 'ignore_public_acls', and 'restrict_public_buckets'"

feat(query): add "S3 Bucket Public ACL Overridden By Public Access Block" for Terraform

---

internal/console/scan.go
internal/metrics/cpu_metric.go
internal/metrics/mem_metric.go
internal/metrics/metrics.go
internal/metrics/metrics_test.go

Closes #3477 #3476
- Metrics and scanning time will now return formatted as `ms` for time and 'B' for memory for `--ci` flag

feature(metrics): Metrics default to 'ms' and 'b' for 'ci' flag 

---

assets/libraries/terraform/library.rego
assets/queries/terraform/aws/sns_topic_encrypted_with_aws_managed_key/metadata.json
assets/queries/terraform/aws/sns_topic_encrypted_with_aws_managed_key/query.rego
assets/queries/terraform/aws/sns_topic_encrypted_with_aws_managed_key/test/negative.tf
assets/queries/terraform/aws/sns_topic_encrypted_with_aws_managed_key/test/positive1.tf
assets/queries/terraform/aws/sns_topic_encrypted_with_aws_managed_key/test/positive2.tf
assets/queries/terraform/aws/sns_topic_encrypted_with_aws_managed_key/test/positive_expected_result.json

- Added "SNS Topic Encrypted With AWS Managed Key" query for Terraform. It checks if the SNS Topic is encrypted with AWS managed key (`alias/aws/sns`)

feat(query): add "SNS Topic Encrypted With AWS Managed Key" for Terraform

---

assets/libraries/terraform/library.rego
assets/queries/terraform/aws/secretsmanager_secret_encrypted_with_aws_managed_key/metadata.json
assets/queries/terraform/aws/secretsmanager_secret_encrypted_with_aws_managed_key/query.rego
assets/queries/terraform/aws/secretsmanager_secret_encrypted_with_aws_managed_key/test/negative.tf
assets/queries/terraform/aws/secretsmanager_secret_encrypted_with_aws_managed_key/test/positive1.tf
assets/queries/terraform/aws/secretsmanager_secret_encrypted_with_aws_managed_key/test/positive2.tf
assets/queries/terraform/aws/secretsmanager_secret_encrypted_with_aws_managed_key/test/positive_expected_result.json

- Added "Secretsmanager Secret Encrypted With AWS Managed Key" query for Terraform. It checks if the Secrets Manager Secret is encrypted with AWS managed key (`alias/aws/secretsmanager`)

feat(query): add "Secretsmanager Secret Encrypted With AWS Managed Key" for Terraform

---

assets/libraries/terraform/library.rego
assets/queries/terraform/aws/docdb_cluster_encrypted_with_aws_managed_key/metadata.json
assets/queries/terraform/aws/docdb_cluster_encrypted_with_aws_managed_key/query.rego
assets/queries/terraform/aws/docdb_cluster_encrypted_with_aws_managed_key/test/negative.tf
assets/queries/terraform/aws/docdb_cluster_encrypted_with_aws_managed_key/test/positive.tf
assets/queries/terraform/aws/docdb_cluster_encrypted_with_aws_managed_key/test/positive_expected_result.json

- Added "DOCDB Cluster Encrypted With AWS Managed Key" query for Terraform. It checks if the DOCDB Cluster is encrypted with AWS managed key (`alias/aws/rds`)

feat(query): add "DOCDB Cluster Encrypted With AWS Managed Key" for Terraform

---

assets/libraries/terraform/library.rego
assets/queries/terraform/aws/codebuild_project_encrypted_with_aws_managed_key/metadata.json
assets/queries/terraform/aws/codebuild_project_encrypted_with_aws_managed_key/query.rego
assets/queries/terraform/aws/codebuild_project_encrypted_with_aws_managed_key/test/negative.tf
assets/queries/terraform/aws/codebuild_project_encrypted_with_aws_managed_key/test/positive.tf
assets/queries/terraform/aws/codebuild_project_encrypted_with_aws_managed_key/test/positive_expected_result.json

- Added "CodeBuild Project Encrypted With AWS Managed Key" query for Terraform. It checks if the CodeBuild Project is encrypted with AWS managed key (`alias/aws/s3`)

feat(query): add "CodeBuild Project Encrypted With AWS Managed Key" for Terraform

---

assets/queries/terraform/aws/sqs_vpc_endpoint_without_dns_resolution/metadata.json
assets/queries/terraform/aws/sqs_vpc_endpoint_without_dns_resolution/query.rego
assets/queries/terraform/aws/sqs_vpc_endpoint_without_dns_resolution/test/negative.tf
assets/queries/terraform/aws/sqs_vpc_endpoint_without_dns_resolution/test/positive.tf
assets/queries/terraform/aws/sqs_vpc_endpoint_without_dns_resolution/test/positive_expected_result.json

- Added "SQS VPC Endpoint Without DNS Resolution" query for Terraform. It checks if the SQS VPC Endpoint has DNS resolution disabled ('enable_dns_support' set to false). According to the official AWS documentation, the attribute `enableDnsSupport` "indicates whether the DNS resolution is supported", as you can see [here](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html#vpc-dns-support)

feat(query): add "SQS VPC Endpoint Without DNS Resolution" for Terraform

---

assets/queries/terraform/aws/dynamodb_vpc_endpoint_wihout_route_table_association/metadata.json
assets/queries/terraform/aws/dynamodb_vpc_endpoint_wihout_route_table_association/query.rego
assets/queries/terraform/aws/dynamodb_vpc_endpoint_wihout_route_table_association/test/negative.tf
assets/queries/terraform/aws/dynamodb_vpc_endpoint_wihout_route_table_association/test/positive.tf
assets/queries/terraform/aws/dynamodb_vpc_endpoint_wihout_route_table_association/test/positive_expected_result.json

- Added "Dynamodb VPC Endpoint Without Route Association" query for Terraform. It checks if the Dynamodb VPC Endpoint is not associated with Route Table Association

feat(query): add "Dynamodb VPC Endpoint Without Route Table Association" for Terraform

---

pkg/parser/yaml/parser.go
pkg/parser/yaml/parser_test.go

Closes #3529
- Fix yaml parser panics on templated files due to unchecked type assertion

fix(parser): yaml parser panics on templated files #3529

---

assets/queries/openAPI/2.0/path_scheme_accepts_http/metadata.json
assets/queries/openAPI/2.0/path_scheme_accepts_http/query.rego
assets/queries/openAPI/2.0/path_scheme_accepts_http/test/negative1.json
assets/queries/openAPI/2.0/path_scheme_accepts_http/test/negative2.yaml
assets/queries/openAPI/2.0/path_scheme_accepts_http/test/positive1.json
assets/queries/openAPI/2.0/path_scheme_accepts_http/test/positive2.yaml
assets/queries/openAPI/2.0/path_scheme_accepts_http/test/positive_expected_result.json
assets/queries/openAPI/3.0/path_server_uses_http/metadata.json
assets/queries/openAPI/3.0/path_server_uses_http/query.rego
assets/queries/openAPI/3.0/path_server_uses_http/test/positive_expected_result.json

- Added "Path Scheme Accepts HTTP" query to openAPI 2.0

feat(query): added 'Path Scheme Accepts HTTP' to openAPI 2.0

---

assets/queries/openAPI/2.0/security_definitions_undefined_or_empty/metadata.json
assets/queries/openAPI/2.0/security_definitions_undefined_or_empty/query.rego
assets/queries/openAPI/2.0/security_definitions_undefined_or_empty/test/negative1.json
assets/queries/openAPI/2.0/security_definitions_undefined_or_empty/test/negative2.yaml
assets/queries/openAPI/2.0/security_definitions_undefined_or_empty/test/positive1.json
assets/queries/openAPI/2.0/security_definitions_undefined_or_empty/test/positive2.yaml
assets/queries/openAPI/2.0/security_definitions_undefined_or_empty/test/positive3.json
assets/queries/openAPI/2.0/security_definitions_undefined_or_empty/test/positive4.yaml
assets/queries/openAPI/2.0/security_definitions_undefined_or_empty/test/positive_expected_result.json

- Added 'Security Definitions Undefined or Empty' query to openAPI 2.0

feat(query): added 'Security Definitions Undefined or Empty' to openAPI 2.0

---

assets/queries/openAPI/2.0/operation_object_without_produces/metadata.json
assets/queries/openAPI/2.0/operation_object_without_produces/query.rego
assets/queries/openAPI/2.0/operation_object_without_produces/test/negative1.json
assets/queries/openAPI/2.0/operation_object_without_produces/test/negative2.yaml
assets/queries/openAPI/2.0/operation_object_without_produces/test/positive1.json
assets/queries/openAPI/2.0/operation_object_without_produces/test/positive2.yaml
assets/queries/openAPI/2.0/operation_object_without_produces/test/positive_expected_result.json

- Added Operation Object Without 'produces' (v2) query to OpenAPI 2.0

feat(query): Added Operation Object Without 'produces' (v2) query to OpenAPI 2.0

---

assets/queries/dockerfile/apt_get_install_pin_version_not_defined/query.rego
test/queries_content_test.go

fix(query): generate different similarity id for each unpinned package #3675

---

assets/queries/openAPI/2.0/parameter_file_type_not_in_formdata/metadata.json
assets/queries/openAPI/2.0/parameter_file_type_not_in_formdata/query.rego
assets/queries/openAPI/2.0/parameter_file_type_not_in_formdata/test/negative1.json
assets/queries/openAPI/2.0/parameter_file_type_not_in_formdata/test/negative2.yaml
assets/queries/openAPI/2.0/parameter_file_type_not_in_formdata/test/positive1.json
assets/queries/openAPI/2.0/parameter_file_type_not_in_formdata/test/positive2.yaml
assets/queries/openAPI/2.0/parameter_file_type_not_in_formdata/test/positive_expected_result.json

- Added Parameter File Type Not In 'formData' query for swagger

feat(query): added Parameter File Type Not In 'formData' query for swagger

---

assets/queries/cloudFormation/neptune_cluster_with_iam_database_authentication_disabled/metadata.json
assets/queries/cloudFormation/neptune_cluster_with_iam_database_authentication_disabled/query.rego
assets/queries/cloudFormation/neptune_cluster_with_iam_database_authentication_disabled/test/negative1.yaml
assets/queries/cloudFormation/neptune_cluster_with_iam_database_authentication_disabled/test/negative2.json
assets/queries/cloudFormation/neptune_cluster_with_iam_database_authentication_disabled/test/positive1.yaml
assets/queries/cloudFormation/neptune_cluster_with_iam_database_authentication_disabled/test/positive2.json
assets/queries/cloudFormation/neptune_cluster_with_iam_database_authentication_disabled/test/positive_expected_result.json
assets/queries/terraform/aws/neptune_cluster_with_iam_database_authentication_disabled/metadata.json
assets/queries/terraform/aws/neptune_cluster_with_iam_database_authentication_disabled/query.rego
assets/queries/terraform/aws/neptune_cluster_with_iam_database_authentication_disabled/test/negative.tf
assets/queries/terraform/aws/neptune_cluster_with_iam_database_authentication_disabled/test/positive.tf
assets/queries/terraform/aws/neptune_cluster_with_iam_database_authentication_disabled/test/positive_expected_result.json

Closes #3653
- Added "Neptune Cluster With IAM Database Authentication Disabled" query for Terraform and CloudFormation (This query is relevant to ensure the use of the IAM service in database access)

Add "Neptune Cluster With IAM Database Authentication Disabled" query for Terraform and CloudFormation (Closes #3653)

---

.github/workflows/update-install-script.yaml

fix(CI): removing automated trigger to update install script workflow

---

assets/queries/openAPI/2.0/multi_collectionformat_not_valid_in_parameter/metadata.json
assets/queries/openAPI/2.0/multi_collectionformat_not_valid_in_parameter/query.rego
assets/queries/openAPI/2.0/multi_collectionformat_not_valid_in_parameter/test/negative1.json
assets/queries/openAPI/2.0/multi_collectionformat_not_valid_in_parameter/test/negative2.yaml
assets/queries/openAPI/2.0/multi_collectionformat_not_valid_in_parameter/test/positive1.json
assets/queries/openAPI/2.0/multi_collectionformat_not_valid_in_parameter/test/positive2.yaml
assets/queries/openAPI/2.0/multi_collectionformat_not_valid_in_parameter/test/positive_expected_result.json

- Added Multi 'collectionformat' Not Valid For 'in' Parameter query for swagger

feat(query): added Multi 'collectionformat' Not Valid For 'in' Parameter query for swagger

---

assets/queries/openAPI/2.0/schema_with_additional_properties_set_as_boolean/metadata.json
assets/queries/openAPI/2.0/schema_with_additional_properties_set_as_boolean/query.rego
assets/queries/openAPI/2.0/schema_with_additional_properties_set_as_boolean/test/negative1.json
assets/queries/openAPI/2.0/schema_with_additional_properties_set_as_boolean/test/negative2.yaml
assets/queries/openAPI/2.0/schema_with_additional_properties_set_as_boolean/test/negative3.json
assets/queries/openAPI/2.0/schema_with_additional_properties_set_as_boolean/test/negative4.yaml
assets/queries/openAPI/2.0/schema_with_additional_properties_set_as_boolean/test/positive1.json
assets/queries/openAPI/2.0/schema_with_additional_properties_set_as_boolean/test/positive2.yaml
assets/queries/openAPI/2.0/schema_with_additional_properties_set_as_boolean/test/positive3.json
assets/queries/openAPI/2.0/schema_with_additional_properties_set_as_boolean/test/positive4.yaml
assets/queries/openAPI/2.0/schema_with_additional_properties_set_as_boolean/test/positive_expected_result.json

- Added 'Schema with 'additionalProperties' set as Boolean' for openAPI 2.0

feat(query): added 'Schema with 'additionalProperties' set as Boolean' for swagger

---

assets/queries/openAPI/2.0/multi_body_parameters_same_operation/metadata.json
assets/queries/openAPI/2.0/multi_body_parameters_same_operation/query.rego
assets/queries/openAPI/2.0/multi_body_parameters_same_operation/test/negative1.json
assets/queries/openAPI/2.0/multi_body_parameters_same_operation/test/negative2.yaml
assets/queries/openAPI/2.0/multi_body_parameters_same_operation/test/positive1.json
assets/queries/openAPI/2.0/multi_body_parameters_same_operation/test/positive2.yaml
assets/queries/openAPI/2.0/multi_body_parameters_same_operation/test/positive_expected_result.json

- Added Multiple Body Parameters In The Same Operation query for swagger

feat(query): added Multiple Body Parameters In The Same Operation query for swagger

---

assets/queries/openAPI/2.0/basepath_with_wrong_format/metadata.json
assets/queries/openAPI/2.0/basepath_with_wrong_format/query.rego
assets/queries/openAPI/2.0/basepath_with_wrong_format/test/negative1.json
assets/queries/openAPI/2.0/basepath_with_wrong_format/test/negative2.yaml
assets/queries/openAPI/2.0/basepath_with_wrong_format/test/positive1.json
assets/queries/openAPI/2.0/basepath_with_wrong_format/test/positive2.yaml
assets/queries/openAPI/2.0/basepath_with_wrong_format/test/positive_expected_result.json

- Added BasePath With Wrong Format query to Swagger
The 'basePath' value format must match the pattern '^/'

feat(query): Added BasePath With Wrong Format query to Swagger

---

assets/queries/dockerfile/apt_get_install_lists_were_not_deleted/query.rego
assets/queries/dockerfile/apt_get_install_lists_were_not_deleted/test/negative.dockerfile
assets/queries/dockerfile/apt_get_install_lists_were_not_deleted/test/positive.dockerfile
assets/queries/dockerfile/apt_get_install_lists_were_not_deleted/test/positive_expected_result.json

Closes #3717
- fixing false positive by replacing logical operator in `rm -rf /var/lib/apt/lists/*` AND `apt-get clean` check for `rm -rf /var/lib/apt/lists/*` OR `apt-get clean` after `apt-get install`

fix(query): wrong logic in apt-get install lists not deleted

---

install.sh

ci: fixing assets installation with install script

---

e2e/cli_test.go
e2e/fixtures/E2E_CLI_032_RESULT.json
e2e/fixtures/schemas/result-gl-sast.json
e2e/fixtures/schemas/result-sarif-required.json
e2e/fixtures/schemas/result-sarif.json
e2e/fixtures/schemas/result.json
e2e/utils.go

- Add JSON Schema Validation for "gl-sast" and "sarif" results
- This validation allows E2E tests to check the integrity of results (reports) in other formats (**gl-sast** and **sarif**), as it has already been implemented in json report format.

test(e2e): add schema validation for gl-sast & sarif results/reports

---

assets/queries/openAPI/2.0/schemes_uses_http copy/metadata.json
assets/queries/openAPI/2.0/schemes_uses_http copy/query.rego
assets/queries/openAPI/2.0/schemes_uses_http copy/test/negative1.json
assets/queries/openAPI/2.0/schemes_uses_http copy/test/negative2.yaml
assets/queries/openAPI/2.0/schemes_uses_http copy/test/positive1.json
assets/queries/openAPI/2.0/schemes_uses_http copy/test/positive2.yaml
assets/queries/openAPI/2.0/schemes_uses_http copy/test/positive_expected_result.json

- Added Schemes Uses HTTP query for Swagger
Schemes should use 'https' protocol instead of 'http'. A scheme using 'http' allows for clear text credentials

feat(query): add Schemes Uses HTTP query for Swagger

---

mkdocs.yml

Enable search engines to better crawl our documentation page

docs: fixing sitemap.xml generation

---

.github/workflows/sonarcloud.yml

Closes #2221
- Sonacloud scan should not run in forks since SONAR_TOKEN secret is not available

ci: sonarcloud should not run in forks

---

pkg/detector/docker/docker_detect.go

Closes #3784
-  Fixed Panic with Docker Detector multilineSpliter

fix(detector): panic with docker detector multilineSpliter #3784

---

pkg/engine/provider/zipprovider.go

- Fixed path always abs with windows and zip extraction

fix(report): Fix path always abs with windows and zip extraction

---

e2e/fixtures/E2E_CLI_031_RESULT.html
e2e/fixtures/E2E_CLI_040_RESULT.html
internal/console/scan.go
pkg/report/template/html/report.tmpl
sonar-project.properties

Closes #
- Fixed some sonar issues

fix(general): Fixed some sonar issues

---

pkg/detector/helper.go

Closes #3824 
- This changes the way detect line works, now checking the distance on the first term too

fix(core): detect line checking first term when multiple terms exists

---

docs/creating-queries.md
docs/running-kics.md

- Added a section on creating query tutorial, referring to `data.json` file
- Added a section on running kics, explaining how to use `input-data` flag

docs(query): Added docs for `input-data` flag

---

pkg/model/summary.go

Signed-off-by: João Reigota <joao.Reigota@checkmarx.com>

fix(engine): fixed go-getter not returning relative path on windows

---

docs/js/custom.js

- Fixed typo on regex that was not replacing `\n` characters with white spaces
- Updated script to split query id and query name and put them in two different columns

bugfix(docs): fixed CSV export on queries page

---

pkg/parser/terraform/converter/default.go

- Corrected parsing when cty value is unknown

bugfix(parser): Fixed issue when trying to parse invalid variable

---

assets/queries/terraform/aws/s3_bucket_allows_all_actions_from_all_principals/metadata.json
assets/queries/terraform/aws/s3_bucket_allows_all_actions_from_all_principals/query.rego
assets/queries/terraform/aws/s3_bucket_allows_all_actions_from_all_principals/test/negative.tf
assets/queries/terraform/aws/s3_bucket_allows_all_actions_from_all_principals/test/positive.tf
assets/queries/terraform/aws/s3_bucket_allows_all_actions_from_all_principals/test/positive_expected_result.json
assets/queries/terraform/aws/s3_bucket_allows_delete_action_from_all_principals/test/positive_expected_result.json
assets/queries/terraform/aws/s3_bucket_allows_put_action_from_all_principals/query.rego
assets/queries/terraform/aws/s3_bucket_allows_put_action_from_all_principals/test/positive_expected_result.json

Closes #3748 
- Added query to check if action is too permissive, using `s3:*`;
- Corrected search key of `S3 Bucket Allows Delete Action From All Principals` and `S3 Bucket Allows Put Action From All Principals` queries

feat(query): Added query S3 Bucket Allows All Actions From All Principals for terraform

---

.gitignore
pkg/parser/terraform/converter/default.go
pkg/parser/terraform/converter/default_test.go
pkg/parser/terraform/functions/default.go

- Parser evaluates standard functions from terraform;
- The list of functions that are evaluated can be found on `pkg/parser/terraform/functions/default.go`. This list only includes functions from terraform `stdlib`;

feat(parser): Added terraform functions on terraform parser

---

assets/libraries/common/library.rego
assets/queries/azureResourceManager/key_vault_not_recoverable/metadata.json
assets/queries/azureResourceManager/key_vault_not_recoverable/query.rego
assets/queries/azureResourceManager/key_vault_not_recoverable/test/negative.json
assets/queries/azureResourceManager/key_vault_not_recoverable/test/positive1.json
assets/queries/azureResourceManager/key_vault_not_recoverable/test/positive2.json
assets/queries/azureResourceManager/key_vault_not_recoverable/test/positive_expected_result.json
assets/queries/azureResourceManager/phone_number_not_set_security_contacts/metadata.json

- Added Key Vault Not Recoverable query for ARM

feat(query): Added Key Vault Not Recoverable query for ARM

---

assets/queries/azureResourceManager/mysql_server_ssl_enforcement_disabled/metadata.json
assets/queries/azureResourceManager/mysql_server_ssl_enforcement_disabled/query.rego
assets/queries/azureResourceManager/mysql_server_ssl_enforcement_disabled/test/negative.json
assets/queries/azureResourceManager/mysql_server_ssl_enforcement_disabled/test/positive1.json
assets/queries/azureResourceManager/mysql_server_ssl_enforcement_disabled/test/positive2.json
assets/queries/azureResourceManager/mysql_server_ssl_enforcement_disabled/test/positive_expected_result.json
assets/queries/azureResourceManager/phone_number_not_set_security_contacts/metadata.json

- Added MySQL Server SSL Enforcement Disabled query for ARM

feat(query): Added MySQL Server SSL Enforcement Disabled query for ARM

---

assets/queries/azureResourceManager/phone_number_not_set_security_contacts/metadata.json
assets/queries/azureResourceManager/website_not_forcing_https/metadata.json
assets/queries/azureResourceManager/website_not_forcing_https/query.rego
assets/queries/azureResourceManager/website_not_forcing_https/test/negative.json
assets/queries/azureResourceManager/website_not_forcing_https/test/positive1.json
assets/queries/azureResourceManager/website_not_forcing_https/test/positive2.json
assets/queries/azureResourceManager/website_not_forcing_https/test/positive_expected_result.json

- Added Website Not Forcing HTTPS query for ARM

feat(query): Added Website Not Forcing HTTPS query for ARM

---

assets/queries/azureResourceManager/phone_number_not_set_security_contacts/metadata.json
assets/queries/azureResourceManager/website_with_client_certificate_auth_disabled/metadata.json
assets/queries/azureResourceManager/website_with_client_certificate_auth_disabled/query.rego
assets/queries/azureResourceManager/website_with_client_certificate_auth_disabled/test/negative.json
assets/queries/azureResourceManager/website_with_client_certificate_auth_disabled/test/positive1.json
assets/queries/azureResourceManager/website_with_client_certificate_auth_disabled/test/positive2.json
assets/queries/azureResourceManager/website_with_client_certificate_auth_disabled/test/positive_expected_result.json

- Added Website with Client Certificate Auth Disabled query for ARM

feat(query): Added Website with Client Certificate Auth Disabled query for ARM

---

assets/libraries/azureresourcemanager/library.rego
assets/queries/azureResourceManager/postgres_sql_database_server_connection_throttling_disabled/metadata.json
assets/queries/azureResourceManager/postgres_sql_database_server_connection_throttling_disabled/query.rego
assets/queries/azureResourceManager/postgres_sql_database_server_connection_throttling_disabled/test/negative1.json
assets/queries/azureResourceManager/postgres_sql_database_server_connection_throttling_disabled/test/negative2.json
assets/queries/azureResourceManager/postgres_sql_database_server_connection_throttling_disabled/test/positive1.json
assets/queries/azureResourceManager/postgres_sql_database_server_connection_throttling_disabled/test/positive2.json
assets/queries/azureResourceManager/postgres_sql_database_server_connection_throttling_disabled/test/positive3.json
assets/queries/azureResourceManager/postgres_sql_database_server_connection_throttling_disabled/test/positive_expected_result.json

- Added PostgresSQL Database Server Connection Throttling Disabled query to ARM
Microsoft.DBforPostgreSQL/servers/configurations should have 'connection_throttling' property set to 'on'

feat(query): Added PostgresSQL Database Server Connection Throttling Disabled query to ARM

---

assets/queries/azureResourceManager/sql_alert_policy_without_emails/metadata.json
assets/queries/azureResourceManager/sql_alert_policy_without_emails/query.rego
assets/queries/azureResourceManager/sql_alert_policy_without_emails/test/negative.json
assets/queries/azureResourceManager/sql_alert_policy_without_emails/test/positive1.json
assets/queries/azureResourceManager/sql_alert_policy_without_emails/test/positive2.json
assets/queries/azureResourceManager/sql_alert_policy_without_emails/test/positive3.json
assets/queries/azureResourceManager/sql_alert_policy_without_emails/test/positive_expected_result.json

- Added SQL Alert Policy Without Emails query to ARM
SQL Database Server should contain emails to be notified in the event of a Security Alert

feat(query): Added SQL Alert Policy Without Emails query to ARM

---

assets/queries/azureResourceManager/phone_number_not_set_security_contacts/metadata.json
assets/queries/azureResourceManager/website_with_http20enabled_disabled/metadata.json
assets/queries/azureResourceManager/website_with_http20enabled_disabled/query.rego
assets/queries/azureResourceManager/website_with_http20enabled_disabled/test/negative.json
assets/queries/azureResourceManager/website_with_http20enabled_disabled/test/positive1.json
assets/queries/azureResourceManager/website_with_http20enabled_disabled/test/positive2.json
assets/queries/azureResourceManager/website_with_http20enabled_disabled/test/positive3.json
assets/queries/azureResourceManager/website_with_http20enabled_disabled/test/positive_expected_result.json

- Added Website with 'Http20Enabled' Disabled query for ARM

feat(query): Added Website with 'Http20Enabled' Disabled query for ARM

---

assets/queries/azureResourceManager/sql_database_server_firewall_allows_all_ips/metadata.json
assets/queries/azureResourceManager/sql_database_server_firewall_allows_all_ips/query.rego
assets/queries/azureResourceManager/sql_database_server_firewall_allows_all_ips/test/negative1.json
assets/queries/azureResourceManager/sql_database_server_firewall_allows_all_ips/test/negative2.json
assets/queries/azureResourceManager/sql_database_server_firewall_allows_all_ips/test/positive1.json
assets/queries/azureResourceManager/sql_database_server_firewall_allows_all_ips/test/positive2.json
assets/queries/azureResourceManager/sql_database_server_firewall_allows_all_ips/test/positive_expected_result.json

- Added SQL Database Server Firewall Allows All IPS query for ARM
SQL Database Server Firewall endIpAddress should not be '255.255.255.255' when startIpAddress is '0.0.0.0' since this allows all IPS

feat(query): Added SQL Database Server Firewall Allows All IPS query for ARM

---

.github/workflows/release-nightly.yml

fix: add missing descriptions url to nightly build

---

assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/negative.tf
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/positive1.tf
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/positive2.tf
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_rest/test/positive_expected_result.json
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/negative1.tf
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/positive1.tf
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/positive2.tf
assets/queries/terraform/aws/elasticache_replication_group_not_encrypted_at_transit/test/positive_expected_result.json
assets/queries/terraform/aws/iam_password_without_minimum_length/query.rego
assets/queries/terraform/aws/iam_password_without_minimum_length/test/negative.tf

- Updated "IAM Password Without Minimum Length" query for Terraform. Changed minimum password length from 8 to 14

feat(query): updated "IAM Password Without Minimum Length" query for Terraform

---

docs/running-kics.md
pkg/engine/inspector.go
pkg/engine/inspector_test.go
pkg/kics/sink.go
pkg/model/model.go
pkg/model/model_test.go
pkg/parser/docker/parser.go
pkg/parser/docker/parser_test.go
pkg/parser/json/parser.go
pkg/parser/json/parser_test.go
pkg/parser/parser.go
pkg/parser/parser_test.go
pkg/parser/terraform/terraform.go
pkg/parser/terraform/terraform_test.go
pkg/parser/yaml/parser.go
pkg/parser/yaml/parser_test.go
test/helpers.go

Closes #3843 
- KICS now has the ability to ignore, disable/enable for some queries based on comments in file beginning;
- There is no importance in which order the comments are since it will get ALL commands in comments, however, it will always take the LAST values from a command. For example:
```yaml
#... rest of the file
```
In this case, the value of `disable` command will be `<some_other_query_id>`
- In this first version, only three commands are available: disable, enable and ignore
- Ignore does not receive any value;
- Enable/disable receive a list of query IDs, separated by comma;
- The precedence order for this commands are:
1. ignore: this will ignore file for ALL queries;
2. enable: this will flag …

feat(core): Added a ignore/disable/enable feature on commented files

---

assets/queries/terraform/aws/iam_policies_with_full_privileges/query.rego

- Updated "IAM Policies With Full Privileges" query for Terraform. The resource `aws_iam_policy_attachment` does not have the attribute `policy` but actually `policy_arn`, which does not fit this query

feat(query): updated "IAM Policies With Full Privileges" query for Terraform

---

assets/libraries/common/library.rego
assets/queries/ansible/aws/s3_bucket_with_unsecured_cors_rule/metadata.json
assets/queries/ansible/aws/s3_bucket_with_unsecured_cors_rule/query.rego
assets/queries/ansible/aws/s3_bucket_with_unsecured_cors_rule/test/negative1.yaml
assets/queries/ansible/aws/s3_bucket_with_unsecured_cors_rule/test/negative2.yaml
assets/queries/ansible/aws/s3_bucket_with_unsecured_cors_rule/test/positive1.yaml
assets/queries/ansible/aws/s3_bucket_with_unsecured_cors_rule/test/positive2.yaml
assets/queries/ansible/aws/s3_bucket_with_unsecured_cors_rule/test/positive_expected_result.json
assets/queries/cloudFormation/s3_bucket_with_unsecured_cors_rule/metadata.json
assets/queries/cloudFormation/s3_bucket_with_unsecured_cors_rule/query.rego
assets/queries/cloudFormation/s3_bucket_with_unsecured_cors_rule/test/negative1.yaml
assets/queries/cloudFormation/s3_bucket_with_unsecured_cors_rule/test/negative2.json
assets/queries/cloudFormation/s3_bucket_with_unsecured_cors_rule/test/positive1.yaml
assets/queries/cloudFormation/s3_bucket_with_unsecured_cors_rule/test/positive2.json
assets/queries/cloudFormation/s3_bucket_with_unsecured_cors_rule/test/positive_expected_result.json
assets/queries/terraform/aws/s3_bucket_with_unsecured_cors_rule/metadata.json
assets/queries/terraform/aws/s3_bucket_with_unsecured_cors_rule/query.rego
assets/queries/terraform/aws/s3_bucket_with_unsecured_cors_rule/test/negative.tf
assets/queries/terraform/aws/s3_bucket_with_unsecured_cors_rule/test/positive1.tf
assets/queries/terraform/aws/s3_bucket_with_unsecured_cors_rule/test/positive2.tf
assets/queries/terraform/aws/s3_bucket_with_unsecured_cors_rule/test/positive_expected_result.json

Closes #3819
- Added "S3 Bucket with Unsecured CORS Rule" query for Ansible, CloudFormation and Terraform

feat(query): added "S3 Bucket with Unsecured CORS Rule" query for Ansible, CloudFormation and Terraform

---

assets/queries/cloudFormation/http_port_open/metadata.json

- fixing wrong descriptionURL value

fix: incorrect descriptionUrl in 'HTTP Port Open' query

---

assets/queries/terraform/aws/vpc_peering_route_table_with_unrestricted_cidr/metadata.json
assets/queries/terraform/aws/vpc_peering_route_table_with_unrestricted_cidr/query.rego
assets/queries/terraform/aws/vpc_peering_route_table_with_unrestricted_cidr/test/negative.tf
assets/queries/terraform/aws/vpc_peering_route_table_with_unrestricted_cidr/test/positive1.tf
assets/queries/terraform/aws/vpc_peering_route_table_with_unrestricted_cidr/test/positive2.tf
assets/queries/terraform/aws/vpc_peering_route_table_with_unrestricted_cidr/test/positive_expected_result.json

- Added "VPC Peering Route Table with Unrestricted CIDR" for Terraform (missing severity and severity)

feat(query): added "VPC Peering Route Table with Unrestricted CIDR" for Terraform

---

assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/metadata.json
assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/query.rego
assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/negative1.tf
assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/negative2.tf
assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/positive1.tf
assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/positive2.tf
assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/positive_expected_result.json

- Added "S3 Bucket Policy Accepts HTTP Requests" for Terraform (missing severity and severity)

feat(query): added "S3 Bucket Policy Accepts HTTP Requests" for Terraform

---

assets/queries/openAPI/3.0/header_object_without_schema/query.rego
assets/queries/openAPI/3.0/header_object_without_schema/test/positive_expected_result.json

- Refactored header query to use `walk` function;

feat(query): refactored query to use walk

---

Dockerfile.apispec.debian
Dockerfile.debian

Closes #4066
- Removing ENTRYPOINT instruction from Debian based Dockerfiles to enable compatibility with Azure DevOps

fix(Dockerfile): removing ENTRYPOINT from debian images fixes #4066

---

assets/libraries/terraform.rego
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/query.rego
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/negative1.tf
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/negative2.tf
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/negative3.tf
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/positive1.tf
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/positive2.tf
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/positive3.tf
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/positive_expected_result.json
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/query.rego
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/negative1.tf
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/negative2.tf
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/negative3.tf
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/positive1.tf
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/positive2.tf
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/positive3.tf
assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_ssh/test/positive_expected_result.json

- network ACL queries now should cover old terraform providers and `aws_network_acl_rule` associated with `aws_network_acl` resources

fix: Network ACL queries covering more cases

---

assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/query.rego
assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/negative1.tf
assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/negative2.tf

- Correcting "S3 Bucket Policy Accepts HTTP Requests" query. Should be `statement.Condition.Bool["aws:SecureTransport"] == "false"` instead of `statement.Condition.Bool["aws:SecureTransport"] == false`

feat(query): Updated "S3 Bucket Policy Accepts HTTP Requests" for Terraform

---

internal/console/scan.go
pkg/model/summary.go
pkg/model/summary_test.go

Closes #4125
- Removing auth information in URL from reports when remote paths are provided

fix: remove auth information in URL closes #4125

---

pkg/report/pdf.go

Closes #4129
- fixing broken footer when last table line is grey

fix: pdf report last grey line closes #4129

---

pkg/parser/terraform/converter/default.go

- KICS was not treating error when couldn't infer json type when evaluating terraform function

fix(core): Fixed error treating when can't infer type from functions

---

pkg/engine/inspector_test.go
pkg/engine/source/filesystem.go
test/main_test.go

fix: moving custom library not provided warning to debug level

---

assets/queries/terraform/aws/autoscaling_groups_supply_tags/metadata.json
assets/queries/terraform/aws/autoscaling_groups_supply_tags/query.rego
assets/queries/terraform/aws/autoscaling_groups_supply_tags/test/negative.tf
assets/queries/terraform/aws/autoscaling_groups_supply_tags/test/negative2.tf
assets/queries/terraform/aws/autoscaling_groups_supply_tags/test/positive.tf
assets/queries/terraform/aws/autoscaling_groups_supply_tags/test/positive_expected_result.json

- added a query to check if Autoscaling Groups supply tags to launch configurations

feat(query): added Autoscaling Groups Supply Tags for Terraform

---

assets/queries/terraform/aws/ssm_session_transit_encryption_disabled/metadata.json
assets/queries/terraform/aws/ssm_session_transit_encryption_disabled/query.rego
assets/queries/terraform/aws/ssm_session_transit_encryption_disabled/test/negative.tf
assets/queries/terraform/aws/ssm_session_transit_encryption_disabled/test/positive1.tf
assets/queries/terraform/aws/ssm_session_transit_encryption_disabled/test/positive2.tf
assets/queries/terraform/aws/ssm_session_transit_encryption_disabled/test/positive_expected_result.json

- Added "SSM Session Transit Encryption Disabled" for Terraform

feat(query): added "SSM Session Transit Encryption Disabled" for Terraform

---

cx.configuration

fix: excluding .github folder from CxSAST scan

---

pkg/analyzer/analyzer.go
pkg/model/model_yaml.go

Closes #4223 
- fixed bug with yaml parser returning a panic
- added ansible vault files to unwanted files

fix(parser): fix issue with parser returning panic #4223

---

assets/queries/common/passwords_and_secrets/metadata.json

fix: add generic id to passwords and secrets for descriptions api

---

assets/queries/terraform/aws/config_configuration_aggregator_to_all_regions_disabled/query.rego
assets/queries/terraform/aws/config_configuration_aggregator_to_all_regions_disabled/test/positive_expected_result.json

- Correcting "keyExpectedValue" and "keyActualValue" for "Configuration Aggregator to All Regions Disabled"

fix(query): correcting "keyExpectedValue" and "keyActualValue" for "Configuration Aggregator to All Regions Disabled"

---

.github/scripts/coverage/.coverageignore
pkg/kics/sink_test.go
pkg/parser/jsonfilter/parser/error_listener_test.go
pkg/parser/parser_test.go

- Added unit tests to pkg/parser/jsonfilter/error_listener.go
- Added unit tests to pkg/parser/parser.go
- Added unit tests to pkg/kics/sink.go
- Added generated files to .coverageignore

test(pkg): increase unit tests to 80% coverage

---

assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/query.rego
assets/queries/terraform/aws/iam_group_without_users/query.rego
assets/queries/terraform/aws/rds_without_logging/query.rego
assets/queries/terraform/aws/route53_record_undefined/query.rego
assets/queries/terraform/azure/vm_not_attached_to_network/query.rego
assets/queries/terraform/gcp/cloud_storage_anonymous_or_publicly_accessible/query.rego
pkg/parser/terraform/converter/default.go

Closes #
- fixed bug where parsing an empty array in terraform would return null instead of an empty array
- fixed queries related to this problem

fix(parser): fix terraform parser returning null instead of empty array

---

pkg/descriptions/client.go

fix: respect http_proxy environment variable

---

assets/queries/k8s/containers_run_with_low_uid/query.rego
assets/queries/k8s/containers_run_with_low_uid/test/positive3.yaml
assets/queries/k8s/containers_run_with_low_uid/test/positive_expected_result.json
pkg/detector/default_detect.go
pkg/engine/vulnerability_builder.go

Closes #4285
- added searchLine to Container Running With Low UID to improve line detection
- failed to detect line error msg now only appears when both searchLine and searchKey fail to detect line

fix(query): added searchLine to Container Running With Low UID to improve line detection (#4285)

---

sonar-project.properties

fix: filtering golang files for sonarcloud scan

---

sonar-project.properties

fix: excluding query samples from sonarcloud scan

---

assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/query.rego
assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/negative3.tf
assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/positive3.tf
assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/positive_expected_result.json

- Support of Terraform modules for "S3 Bucket Policy Accepts HTTP Requests"

feat(query): support of Terraform modules for "S3 Bucket Policy Accepts HTTP Requests"

---

pkg/parser/terraform/terraform.go

Closes #4301
- fix panic with `model.Document` conversion in tf parser
- check if conversion is possible

fix(parser): fix panic with model.Document conversion in tf parser #4301

---

pkg/engine/secrets/inspector.go
pkg/engine/secrets/inspector_test.go

Closes #4308 
- Now secrets inspector removes queries by severity and category

fix(core): Fixed secrets inspector to remove queries

---

assets/queries/cloudFormation/elastic_search_without_slow_logs/query.rego
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/negative1.yaml
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/negative2.json
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/negative3.yaml
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/positive1.yaml
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/positive2.yaml
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/positive3.yaml
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/positive5.json
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/positive6.json
assets/queries/cloudFormation/elastic_search_without_slow_logs/test/positive_expected_result.json

Closes #4310
- Fixing query FP
- Adding new negative sample
- Query refactoring
- Adding searchLine

fix(query): elastic search without slow logs FP

---

e2e/cli_test.go
e2e/fixtures/E2E_CLI_036_RESULT.json
e2e/fixtures/E2E_CLI_036_RESULT_2.json
e2e/fixtures/E2E_CLI_047_PAYLOAD.json

Closes #
This PR adds several tests focused on increasing the coverage ratio of E2E tests, by testing flags that still weren't covered yet on E2E Tests.
Covered flags:
- cloud-provider
- exclude-severities
- include-queries
- disable-full-descriptions _(partial)_
- payload-lines

feat: added E2E tests to cover new flags

---

assets/queries/cloudFormation/s3_bucket_should_have_bucket_policy/query.rego
assets/queries/cloudFormation/s3_bucket_should_have_bucket_policy/test/negative3.yaml
assets/queries/cloudFormation/s3_bucket_should_have_bucket_policy/test/negative4.json
assets/queries/cloudFormation/s3_bucket_should_have_bucket_policy/test/positive3.yaml
assets/queries/cloudFormation/s3_bucket_should_have_bucket_policy/test/positive4.json
assets/queries/cloudFormation/s3_bucket_should_have_bucket_policy/test/positive_expected_result.json

Closes #4303
- Corrected "S3 Bucket Should Have Bucket Policy" approach: should be check if `Resources.%s.Properties.BucketName` or `Resources.[%s]` is not the same as an `AWS::S3::BucketPolicy Bucket`

fix(query): corrected "S3 Bucket Should Have Bucket Policy" approach

---

.github/workflows/go-ci-coverage.yaml
.github/workflows/go-ci.yml
.github/workflows/go-e2e.yaml
.github/workflows/release-apispec.yml
.github/workflows/release-nightly.yml
.github/workflows/release.yml

ci(deps): bump golang to version 1.17 in pipelines

---

assets/queries/common/passwords_and_secrets/regex_rules.json
assets/queries/common/passwords_and_secrets/test/negative46.tf

- Exclude the results that point to Terraform file function

fix(passwords and secrets): excluded TF file function reference in results

---

internal/console/helpers/helpers.go
internal/console/scan.go

fix(cli): report-formats panics with uppercase input closes #4455

---

e2e/fixtures/samples/queries/invalid/invalid_metadata/terraform/athena_database_not_encrypted/metadata.json
e2e/fixtures/samples/queries/invalid/invalid_metadata/terraform/athena_database_not_encrypted/query.rego
e2e/fixtures/samples/queries/invalid/missing_metadata/terraform/athena_database_not_encrypted/query.rego
e2e/fixtures/samples/queries/valid/single_query/terraform/athena_database_not_encrypted/metadata.json
e2e/fixtures/samples/queries/valid/single_query/terraform/athena_database_not_encrypted/query.rego
e2e/testcases/e2e-cli-018_scan_exclude-categories.go
e2e/testcases/e2e-cli-031_scan_report-formats.go
e2e/testcases/e2e-cli-039_scan_log-path_log-level.go
e2e/testcases/e2e-cli-043_scan_cloud-provider.go
e2e/testcases/e2e-cli-051_scan_custom-queries-path.go

Closes #
- This PR introduces a new E2E Test case related to negative tests for queries-path (-q) flag. The purpose of these tests is to cover custom inputs from the user, mainly focused on bad inputs, such as invalid or badly formatted queries.
- Moreover, to increase the coverage of testing samples, some tests had new inputs, using them as case insensitive (to catch errors related to case sensitivity).

feat(e2e): added negative tests for queries-path

---

pkg/engine/source/filesystem.go
pkg/engine/source/filesystem_test.go

Closes #4413
- Added function to check for fields that if missing causes KICS to panic (`id`, `platform`)

fix(source): fixed KICS panic when reading invalid metadata (#4413)

---

docs/secrets.md
pkg/engine/secrets/inspector.go
pkg/engine/secrets/inspector_test.go
pkg/scan/scan.go
pkg/scanner/scanner_test.go
test/secrets_test.go

- **Exclude Passwords and Secrets query (a88baa34-e2ad-44ea-ad6f-8cac87bc7c71) through --exclude-queries**: this approach took advantage of disableSecretsQuery verification. It was added verification to not include the Password and Secrets mechanism when the --exclude-queries points to Passwords and Secrets query (a88baa34-e2ad-44ea-ad6f-8cac87bc7c71) and --secrets-regexes-path is not used
- **Include Passwords and Secrets query (a88baa34-e2ad-44ea-ad6f-8cac87bc7c71) through --include-queries**: if --include-queries points to the Passwords and Secrets query (a88baa34-e2ad-44ea-ad6f-8cac87bc7c71), it should trigger all the rules defined inside the regex_rules.json. For that, we have some cases:
- --include-queries points to the Passwords and Secrets query …

feat(passwords and secrets mechanism): a88baa34-e2ad-44ea-ad6f-8cac87bc7c71 trigger all the rules defined inside the regex_rules.json

---

pkg/report/model/sarif.go
pkg/report/model/sarif_test.go

Closes #4431 
- Now, when a line is less than 1, will point to file's first line

fix(report): fixed bug with invalid startLine on sarif report

---

pkg/model/comment_yaml.go
pkg/model/comment_yaml_test.go
pkg/model/model_yaml.go

#4420 #4419 
- Users can now ignore lines by comments in the original file
- lines containing comments are now excluded as well for yaml
- this feature should only be enabled when all parsers support this feature

feat(yaml): Added Ignore lines by comments to yaml #4420

---

docs/running-kics.md
pkg/kics/resolver_sink.go
pkg/model/comment_yaml.go
pkg/model/comment_yaml_test.go
pkg/model/comments.go
pkg/model/comments_test.go
pkg/model/model.go
pkg/parser/docker/comments.go
pkg/parser/docker/comments_test.go
pkg/parser/docker/parser.go
pkg/parser/docker/parser_test.go
pkg/parser/terraform/comment/comment.go
pkg/parser/terraform/comment/comment_test.go
pkg/parser/terraform/terraform.go
pkg/parser/terraform/terraform_test.go
pkg/parser/yaml/parser.go
pkg/parser/yaml/parser_test.go

Closes #4420
- Enabled Ignore Line By comments for YAML, Dockerfile, and Terraform Parsers
- Added Unit Tests to parsers for ignoring comments
- Enabled feature for Helm
- Added Helper comment Library to be used by all parsers
- Add Documentation
- changed `kics ignore-...` to `kics-scan ignore-...` for consistency 

feat(parser): Enabled parsers ignore comment by line

---

assets/queries/terraform/azure/function_app_client_certificates_unrequired/metadata.json
assets/queries/terraform/azure/function_app_client_certificates_unrequired/query.rego
assets/queries/terraform/azure/function_app_client_certificates_unrequired/test/negative.tf
assets/queries/terraform/azure/function_app_client_certificates_unrequired/test/positive1.tf
assets/queries/terraform/azure/function_app_client_certificates_unrequired/test/positive2.tf
assets/queries/terraform/azure/function_app_client_certificates_unrequired/test/positive_expected_result.json

- Added "Function App Client Certificates Unrequired" for Terraform

feat(query): added "Function App Client Certificates Unrequired" for Terraform

---

pkg/engine/source/filesystem_test.go

- Added more coverage to pkg source in order to increase unit tests coverage to 80%

tests(source): increased unit tests coverago to 80%

---

docs/running-kics.md
pkg/model/comment_yaml.go
pkg/parser/terraform/comment/comment.go

- There was a problem with YAML parser that [it confuses head comments with footer comments](https://github.com/go-yaml/yaml/issues/695), this is fixed by this PR
- Also removed carriage character to prevent errors on windows system

fix(engine): Fixed comments commands on windows

---

docs/integrations.md

Add blank line so mkdocs displays correctly the bulletpoints

Add blank line so mkdocs displays correctly the bulletpoints

---

assets/queries/terraform/aws/security_groups_not_used/query.rego
assets/queries/terraform/aws/security_groups_not_used/test/negative3.tf
assets/queries/terraform/aws/security_groups_not_used/test/positive2.tf
assets/queries/terraform/aws/security_groups_not_used/test/positive3.tf
assets/queries/terraform/aws/security_groups_not_used/test/positive_expected_result.json

Closes #4501
- Add check against vpc_security_group_ids
- Add test cases:
- Negative: 
- security group attached to aws_instance should not be detected as unused security group
- Positive:
- unused security group declared and no security group attached to aws_instance
- unused security group declared and other security group attached to aws_instance

fix(query) Wrong detection of unused security group

---

docs/platforms.md
pkg/engine/secrets/inspector.go
pkg/engine/secrets/inspector_test.go
pkg/scan/path_utils.go
pkg/scan/post_scan.go
pkg/scan/scan.go

Closes #4485
Closes #4419
- Added documentation about Ansible identification limitation
- Added consideration of `kics-scan ignore` command in passwords and secrets inspector
- Added consideration of LinesIgnore in passwords and secrets inspector (Fix bug #4419)
- Fix bug #4485

feat(docs & passwords and secrets): consideration of kics-scan ignore command and LinesIgnore 

---

pkg/report/template/html/report.tmpl

Closes #4526
- The KICS v{{ getVersion }} - had a redundant v (which means getVersion is returning a v as well)
-
-

Removing redundant "V" in the HTML report

---

go.mod
go.sum

- bump containrd to secure version 1.5.8

bump(containrd): bump containrd to version 1.5.8

---

assets/queries/common/passwords_and_secrets/regex_rules.json

Closes #4528
- Removed hardcoded team name from MS Teams Regex

fix(password and secrets): fixed MS Teams regex hardcoded team_name (#4528)

---

e2e/fixtures/samples/scan-ignore/disable.tf
e2e/fixtures/samples/scan-ignore/enable.tf
e2e/fixtures/samples/scan-ignore/ignore-block.dockerfile
e2e/fixtures/samples/scan-ignore/ignore-lines.yaml
e2e/fixtures/samples/scan-ignore/ignore/sample.dockerfile
e2e/fixtures/samples/scan-ignore/ignore/sample.tf
e2e/fixtures/samples/scan-ignore/ignore/sample.yaml
e2e/testcases/e2e-cli-053_kics_scan_ignore.go

Closes #
- Added E2E Tests for kics comments commands that cover many supported formats (.yaml, .dockerfile & .tf) and all the available commands (ignore, ignore-block, ignore-lines, enable, disable)

feat(e2e): E2E Tests for kics comments commands

---

assets/queries/ansible/aws/api_gateway_without_waf/metadata.json
assets/queries/ansible/aws/api_gateway_without_waf/query.rego
assets/queries/ansible/aws/api_gateway_without_waf/test/negative.yaml
assets/queries/ansible/aws/api_gateway_without_waf/test/positive.yaml
assets/queries/ansible/aws/api_gateway_without_waf/test/positive_expected_result.json
assets/queries/cloudFormation/api_gateway_without_waf/metadata.json
assets/queries/cloudFormation/api_gateway_without_waf/query.rego
assets/queries/cloudFormation/api_gateway_without_waf/test/negative1.yaml
assets/queries/cloudFormation/api_gateway_without_waf/test/negative2.json
assets/queries/cloudFormation/api_gateway_without_waf/test/positive1.yaml
assets/queries/cloudFormation/api_gateway_without_waf/test/positive2.json
assets/queries/cloudFormation/api_gateway_without_waf/test/positive_expected_result.json
assets/queries/terraform/aws/api_gateway_without_waf/metadata.json
assets/queries/terraform/aws/api_gateway_without_waf/query.rego
assets/queries/terraform/aws/api_gateway_without_waf/test/negative.tf
assets/queries/terraform/aws/api_gateway_without_waf/test/positive.tf
assets/queries/terraform/aws/api_gateway_without_waf/test/positive_expected_result.json

- Added "API Gateway without WAF" for Ansible, CloudFormation, and Terraform

feat(query): added "API Gateway without WAF" for Ansible, CloudFormation, and Terraform

---

pkg/parser/yaml/parser.go

Closes #4521
- Added Type check to prevent panic in YAML parser for Ansible files

fix(parser): fixed YAML parser panic with wrong type for interface (#4521)

---

pkg/scan/scan.go

- Added a log when progress bar fails to close

fix(scan): not reporting error when progress bar fails to close

---

.pre-commit-hooks.yaml
docs/integrations_pre_commit.md

Closes #
I use `pre-commit` a lot to check for stuff before pushing it to the repo, and I was missing `kics` integration.
One thing that I noticed is that even though I'm excluding `.terraform`, I think `kics` itself is scanning them because it scans [terraform modules](https://github.com/Checkmarx/kics/issues/4493) by default, but I'm not sure.  Any thoughts?
- Add pre-commit integration

add pre-commit hook

---

README.md

- changed kics logo in README.md to colored logo

docs(logo): changed kics logo in README.md to colored logo

---

assets/queries/dockerfile/multiple_run_add_copy_instructions_listed/query.rego
assets/queries/dockerfile/multiple_run_add_copy_instructions_listed/test/negative4.dockerfile

Closes #4567
- Query now looks if the destinations are identical for `COPY` and `ADD` commands

fix(query): fixed query Multiple RUN, ADD, COPY, Instructions Listed (#4567)

---

e2e/cli_test.go
e2e/fixtures/schemas/result-sonarqube.json
e2e/fixtures/schemas/sonarqubeLocations.json
e2e/testcases/e2e-cli-031_scan_report-formats.go
e2e/testcases/e2e-cli-040_scan_report-formats_validate_outputs.go

- This PR introduces a JSON Schema to validate sonarqube reports generated by kics.
- It also includes the sonarqube report validation in 2 tests.

feat(e2e): add tests to validate sonaqube reports

---

.github/workflows/prepare-release.yaml

- Fix the regex to identify any valid version in kics docs (the current regex didn't identify version 1.4.6.1).

fix(ci): Fixed docs version regex of prepare-release workflow

---

assets/queries/common/passwords_and_secrets/regex_rules.json

- kics reports passwords encrypted with ansible-vault (in the Passwords And Secrets - Generic Password query). However since these passwords are encrypted, they should not be reported

feat(query): add allow rule for ansible-vault

---

e2e/cli_test.go
e2e/fixtures/schemas/result-cyclonedx.json
e2e/testcases/e2e-cli-031_scan_report-formats.go
e2e/utils/xml.go

The aim of this PR is to validate the structure of CycloneDX reports generated by kics.
It includes a JSON-Schema validation that verifies all the fields of a CycloneDX report, applying many asserts, such as regex and enum on specific fields. The CycloneDX report is generated as XML, and the E2E converts it into JSON to validate using a schema.

feat(e2e): added CycloneDX report schema

---

assets/queries/terraform/aws/resource_not_using_tags/query.rego
e2e/fixtures/E2E_CLI_032_RESULT.json
e2e/fixtures/E2E_CLI_033_RESULT.json
e2e/testcases/e2e-cli-037_scan_exclude-results_include-queries.go

- Deleting searchLine in "Resource Not Using Tags" for Terraform

fix(query): deleting searchLine in "Resource Not Using Tags" for Terraform

---

assets/queries/terraform/aws/s3_bucket_without_enabled_mfa_delete/metadata.json
assets/queries/terraform/aws/s3_bucket_without_enabled_mfa_delete/query.rego
assets/queries/terraform/aws/s3_bucket_without_enabled_mfa_delete/test/negative3.tf
assets/queries/terraform/aws/s3_bucket_without_enabled_mfa_delete/test/negative4.tf

Closes #4576
- Updated "S3 Bucket Without Enabled MFA Delete" for Terraform: excluded `s3_bucket` with lifecycle configurations

fix(query): updated "S3 Bucket Without Enabled MFA Delete" for Terraform

---

assets/libraries/common.rego
assets/queries/terraform/aws_bom/ebs/query.rego
assets/queries/terraform/aws_bom/efs/query.rego
assets/queries/terraform/aws_bom/efs/test/positive2.tf
assets/queries/terraform/aws_bom/efs/test/positive_expected_result.json
assets/queries/terraform/aws_bom/elasticache/query.rego
assets/queries/terraform/aws_bom/mq/query.rego
assets/queries/terraform/aws_bom/mq/test/positive2.tf
assets/queries/terraform/aws_bom/msk/query.rego
assets/queries/terraform/aws_bom/s3_bucket/query.rego
assets/queries/terraform/aws_bom/s3_bucket/test/positive8.tf
assets/queries/terraform/aws_bom/sns/query.rego
assets/queries/terraform/aws_bom/sns/test/positive5.tf
assets/queries/terraform/aws_bom/sqs/query.rego
assets/queries/terraform/aws_bom/sqs/test/positive5.tf
test/queries_test.go

- Split encryption from accessibility

feat(bom): split encryption from accessibility

---

assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_http_api_access_logging_settings_undefined/metadata.json
assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_http_api_access_logging_settings_undefined/query.rego
assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_http_api_access_logging_settings_undefined/test/negative1.yaml
assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_http_api_access_logging_settings_undefined/test/positive1.yaml
assets/queries/cloudFormation/aws_sam/serverless_api_xray_tracing_disabled/serverless_http_api_access_logging_settings_undefined/test/positive_expected_result.json

- Added "Serverless HTTP API Access Logging Settings Undefined" for CloudFormation

feat(query): added "Serverless HTTP API Access Logging Settings Undefined" for CloudFormation

---

assets/queries/common/passwords_and_secrets/regex_rules.json

MySQL-password are twiced hashed.
They are always 41 bytes long with the fist byte being an asterisk.

add allow rule for mysql password hashes

---

pkg/model/model_yaml.go
pkg/parser/yaml/parser_test.go
pkg/utils/map.go

Closes #4630
- Support of YAML alias

feat(parser): support of YAML alias

---

internal/console/helpers/helpers.go
pkg/model/summary.go
pkg/scan/path_utils.go
pkg/scan/post_scan.go
pkg/scan/utils.go

Closes #2224
- Added contribution appeal when the user includes external queries (the queries path do not follow assets/queries structure)
- Changed `PrintVersionCheck` location and colour

feat(cli): added contribution appeal when the user includes external queries

---

assets/libraries/common.rego
assets/queries/cloudFormation/aws/elasticsearch_without_iam_authentication/metadata.json
assets/queries/cloudFormation/aws/elasticsearch_without_iam_authentication/query.rego
assets/queries/cloudFormation/aws/elasticsearch_without_iam_authentication/test/negative1.yaml
assets/queries/cloudFormation/aws/elasticsearch_without_iam_authentication/test/negative2.json
assets/queries/cloudFormation/aws/elasticsearch_without_iam_authentication/test/positive1.yaml
assets/queries/cloudFormation/aws/elasticsearch_without_iam_authentication/test/positive2.json
assets/queries/cloudFormation/aws/elasticsearch_without_iam_authentication/test/positive_expected_result.json
assets/queries/terraform/aws/elasticsearch_without_iam_authentication/metadata.json
assets/queries/terraform/aws/elasticsearch_without_iam_authentication/query.rego
assets/queries/terraform/aws/elasticsearch_without_iam_authentication/test/negative.tf
assets/queries/terraform/aws/elasticsearch_without_iam_authentication/test/positive1.tf
assets/queries/terraform/aws/elasticsearch_without_iam_authentication/test/positive2.tf
assets/queries/terraform/aws/elasticsearch_without_iam_authentication/test/positive_expected_result.json

- Added "Elasticsearch Without IAM Authentication" for CloudFormation and Terraform

feat(query): added "Elasticsearch Without IAM Authentication" for CloudFormation and Terraform

---

assets/queries/googleDeploymentManager/sql_db_instance_backup_disable/metadata.json
assets/queries/googleDeploymentManager/sql_db_instance_backup_disable/query.rego
assets/queries/googleDeploymentManager/sql_db_instance_backup_disable/test/negative1.yaml
assets/queries/googleDeploymentManager/sql_db_instance_backup_disable/test/positive1.yaml
assets/queries/googleDeploymentManager/sql_db_instance_backup_disable/test/positive2.yaml
assets/queries/googleDeploymentManager/sql_db_instance_backup_disable/test/positive3.yaml
assets/queries/googleDeploymentManager/sql_db_instance_backup_disable/test/positive_expected_result.json

- Added "SQL DB Instance Backup Disabled" for Google Deployment Manager

feat(query): added "SQL DB Instance Backup Disabled" for Google Deployment Manager

---

.github/workflows/go-ci.yml

- increased ci linter timeout to 15 minutes

fix(linter): increased timeout to 15 minutes

---

pkg/report/model/gitlab_sast.go
pkg/report/model/gitlab_sast_test.go

Closes #4700 
Updates schema version field, since schema fields used by KICS are the same, this change just updates version number on `SchemaVersion` field on gitlab sast model. The chosen version was 14.0.1, since this is the last version available to check on validator.
This change was validated by [gitlab schema validator][1] and using this [sample generated by KICS on this branch][2].
Signed-off-by: Felipe Avelar <felipe.avelar@outlook.com>
[1]:  https://gitlab-org-security-products-secure-schema-validator.34.127.22.151.sslip.io/
[2]: https://gist.github.com/lipeavelar/7bed6400eea9a29ac8d378ec98f674b1

feat(report): update gitlab sast report schema version

---

.github/workflows/go-e2e.yaml
Makefile
pkg/model/comment_yaml.go

- fixed Golang data races caused by analyzer
- fixed make file dev tags
- changed e2e to run with dev tags

fix(golang): fixed golang data races and make file

---

pkg/terraformer/terraformer.go
pkg/terraformer/terraformer_test.go

- generated folder kics-extract-terraformer now has the current timestamp in the folder name

update(terraformer): added timestamp to generated import folder

---

assets/queries/terraform/aws/iam_access_analyzer_undefined/query.rego

Closes #4771 
- Limited "IAM Access Analyzer Undefined" only for AWS

fix(query): limited "IAM Access Analyzer Undefined" only for AWS

---

pkg/model/summary.go
pkg/model/summary_test.go
pkg/report/cyclonedx.go
pkg/report/model/cyclonedx.go
pkg/report/model/cyclonedx_test.go
pkg/scan/post_scan.go
pkg/scan/scan.go

Closes #4754
- Fixed CycloneDX report for compressed files

fix(report): fixed CycloneDX report for compressed files

---

pkg/report/model/asff.go

fix(report): fixed null ASFF report

---

assets/queries/ansible/gcp/project_wide_ssh_keys_are_enabled_in_vm_instances/metadata.json
assets/queries/googleDeploymentManager/project_wide_ssh_keys_are_enabled_in_vm_instances/metadata.json
assets/queries/googleDeploymentManager/project_wide_ssh_keys_are_enabled_in_vm_instances/query.rego
assets/queries/googleDeploymentManager/project_wide_ssh_keys_are_enabled_in_vm_instances/test/negative1.yaml
assets/queries/googleDeploymentManager/project_wide_ssh_keys_are_enabled_in_vm_instances/test/positive1.yaml
assets/queries/googleDeploymentManager/project_wide_ssh_keys_are_enabled_in_vm_instances/test/positive2.yaml
assets/queries/googleDeploymentManager/project_wide_ssh_keys_are_enabled_in_vm_instances/test/positive3.yaml
assets/queries/googleDeploymentManager/project_wide_ssh_keys_are_enabled_in_vm_instances/test/positive_expected_result.json
assets/queries/terraform/gcp/project_wide_ssh_keys_are_enabled_in_vm_instances/metadata.json

- Added "Project-wide SSH Keys Are Enabled In VM Instances" for Google Deployment Manager

feat(query): added "Project-wide SSH Keys Are Enabled In VM Instances" for Google Deployment Manager

---

docs/configuration-file.md
docs/getting-started.md
docs/index.md
docs/integrations_jenkins.md
docs/releases.md
docs/running-kics.md

- Removed binaries from docs
- Changed all cmds to Docker cmds

docs(kics.io): Removed binaries and changed all cmds to Docker cmds

---

docs/integrations_travisci.md

- Removed Travis CI binary example

fix(doc): Removed Travis CI binary example

---

assets/queries/k8s/containers_run_with_low_uid/query.rego
assets/queries/k8s/containers_run_with_low_uid/test/negative2.yaml
assets/queries/k8s/containers_run_with_low_uid/test/negative3.yaml
assets/queries/k8s/containers_run_with_low_uid/test/positive4.yaml
assets/queries/k8s/containers_run_with_low_uid/test/positive5.yaml
assets/queries/k8s/containers_run_with_low_uid/test/positive6.yaml
assets/queries/k8s/containers_run_with_low_uid/test/positive7.yaml
assets/queries/k8s/containers_run_with_low_uid/test/positive_expected_result.json

**Problem**
The K8s rule _containers-run-with-low-uid_ traverses documents recursively, searching for `runAsUser` defintions. By doing so, the implementation disregards hierarchical inheritance, in which a `runAsUser` statement can occur. If defined in the SecurityContext of a pod, it is inherited by all containers, unless redefined in the SecurityContext of a container. More information about precedence is provided [here](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container).
The current rule shows false positive alerts for each SecurityContext definition, which does not include `runAsUser`.
- Change the current implementation to check for possible definitions at multiple locations:
- Does a container …

fix(query): containers-run-with-low-uid k8s query should consider statement precedence

---

Makefile

- This PR increases the E2E Tests execution timeout by 10m to avoid breaking PRs by the current threshold.

fix(ci): makefile - increasing E2E Tests timeout

---

assets/queries/k8s/liveness_probe_is_not_defined/metadata.json
assets/queries/k8s/liveness_probe_is_not_defined/test/positive_expected_result.json

Closes #4755
- Changed severity, description text and URL in "Liveness Probe Is Not Defined" query

fix(query): changed severity, description text and URL in "Liveness Probe Is Not Defined" query

---

assets/queries/k8s/object_is_using_a_deprecated_api_version/query.rego
assets/queries/k8s/object_is_using_a_deprecated_api_version/test/negative.yaml
assets/queries/k8s/object_is_using_a_deprecated_api_version/test/positive.yaml
assets/queries/k8s/object_is_using_a_deprecated_api_version/test/positive_expected_result.json

**Problem**
- `Ingress` in `extensions/v1beta1` recommends `apps/v1` but correct would be `networking.k8s.io/v1`
- `negative.yaml` includes an Ingress with `networking.k8s.io/v1beta1` but this API version is also deprecated
- All findings of a particular type are shown only once in results, even if they appear multiple times in a scanned *.yaml file
- The existing checks do not cover deprecations in K8s > v1.16
- Improvements for all items mentioned above
- Additional checks for commonly defined resource APIs that were [deprecated with K8s v1.22](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22)

fix(query): covered additional deprecated API versions in k8s rule

---

assets/queries/terraform/aws/resource_not_using_tags/query.rego

In the query `aws/resource_not_using_tags`, the query contains the following function
```rego
check_default_tags {
common_lib.valid_key(input.document[_].provider[_].default_tags, "tags")
} else = false {
true
}
```
This function is only able to test if there's a single provider.
```terraform
provider "aws" {
region  = "eu-west-3"
alias   = "foobar"
profile = "foobar"
default_tags {
tags = {
foo = "bar"
}
}
}
```
the payload
```json
{
"document": [
{
"file": "/Users/jycamier/workspace/terraform/00_network_tgw/toto/provider.tf",
"id": "012c8e85-a9ee-405b-9294-2b589e389330",
"provider": {
"aws": {
"alias": "foobar",
"default_tags": {
"tags": {
"foo": "bar"
}
},
"profile": "foobar",
"region": "eu-west-3"
}
}
}
]
}
```
`input.document.provider.aws` is a struct so all is fine.
If you're using …

fix(query): be able to check default_tags on multiple providers

---

assets/queries/terraform/aws/service_control_policies_disabled/metadata.json
assets/queries/terraform/aws/service_control_policies_disabled/query.rego
assets/queries/terraform/aws/service_control_policies_disabled/test/negative.tf
assets/queries/terraform/aws/service_control_policies_disabled/test/positive.tf
assets/queries/terraform/aws/service_control_policies_disabled/test/positive_expected_result.json

Closes #4828
- Fixed "Service Control Policies Disabled" query: since Service Control Policies (SCPs)  are available only if all features of the AWS Organizations are enabled, this query should check if all features are enabled in AWS Organizations.

fix(query): fixed "Service Control Policies Disabled" query

---

.github/scripts/server-mock/package-lock.json
.github/scripts/server-mock/package.json
.github/scripts/server-mock/src/descriptions.json
e2e/fixtures/schemas/result-junit.json
e2e/testcases/e2e-cli-031_scan_report-formats.go

Closes #
- This PR updates some outdated dependencies of the script "server-mock" which is used to validate the CIS_DESCRIPTIONS in E2E Tests.

fix(ci): update dependencies in server-mock script

---

pkg/analyzer/analyzer.go

- Added the possibility of space before `:` in all regexes
- Changed openAPIRegexPath to allow paths, components, or webhooks (from 3.1.0 it is required one of them)
- Improved regexes

fix(analyzer): fixed and improved regexes in analyzer

---

assets/libraries/common.rego
docs/platforms.md
pkg/engine/inspector_test.go
test/fixtures/common_query_test/metadata.json
test/fixtures/common_query_test/query.rego
test/fixtures/get_queries_test/common_query.rego

- When using a custom common query (platform: "Common" in query metadata), KICS inspector reports the error `Generic:354: rego_type_error: rule named engines redeclared at Common:354` and does not load the query. That happens due to the declaration of engines `engines := {` in common.rego. So, this PR changes it to  `engines : {`

fix(library): fixed "Generic:354: rego_type_error: rule named engines redeclared at Common:354"

---

assets/queries/k8s/invalid_image/metadata.json
assets/queries/k8s/invalid_image/query.rego
assets/queries/k8s/invalid_image/test/negative.yaml
assets/queries/k8s/invalid_image/test/positive.yaml
assets/queries/k8s/invalid_image/test/positive_expected_result.json

**Problem**
- The logic to check whether a tag is provided seems flawed. Specifying an empty image is fine, e.g., with `Cronjob` where an empty image tag is provided but shell commands are provided in `command`.
What this rule most likely wanted to target in the first place is whether the **image tag** is empty (or latest), rather than the image itself.
- Extend the rule to cover additional resource kinds, e.g., Deployment, DaemonSet, etc.
- Remove `MissingAttribute` check for `image`
- For a container to be deployable, specifying an image is indispensible (see `type Container struct` [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go)).
- Trying to deploy a pod without an image attribute yields an error: `The Pod …

fix(query): Corrected tag flagging invalid_image k8s rule

---

assets/queries/k8s/volume_mount_with_os_directory_write_permissions/query.rego
assets/queries/k8s/volume_mount_with_os_directory_write_permissions/test/positive_expected_result.json

- Fix typo in `searchKey` preventing successful search results
- Changed `resource.spec` to `getSpecInfo` in order to enable further resource kinds

fix(query): Fix searchKey and additional resource kinds in volume_mount_with_os_directory_write_permissions k8s rule

---

assets/queries/k8s/image_without_digest/metadata.json
assets/queries/k8s/image_without_digest/query.rego
assets/queries/k8s/image_without_digest/test/positive.yaml
assets/queries/k8s/image_without_digest/test/positive_expected_result.json

- Extend the rule to cover additional resource kinds, e.g., Deployment, DaemonSet, etc.
- Remove `MissingAttribute` check for `image` + adapt the testcase
- For a container to be deployable, specifying an image is indispensible (see `type Container struct` [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go)).
- Trying to deploy a pod without an image attribute yields an error: `The Pod "private-image-test-1.2" is invalid: spec.containers[0].image: Required value`
- Note: `image` can be empty (= null) though, e.g., if `command` is also used
- More comprehensive metadata description

fix(query): Extend image_without_digest k8s rule to cover further resource kinds

---

assets/queries/terraform/alicloud/ram_account_password_policy_not_required_numbers/metadata.json
assets/queries/terraform/alicloud/ram_account_password_policy_not_required_numbers/query.rego
assets/queries/terraform/alicloud/ram_account_password_policy_not_required_numbers/test/negative1.tf
assets/queries/terraform/alicloud/ram_account_password_policy_not_required_numbers/test/negative2.tf
assets/queries/terraform/alicloud/ram_account_password_policy_not_required_numbers/test/positive1.tf
assets/queries/terraform/alicloud/ram_account_password_policy_not_required_numbers/test/positive_expected_result.json

- Added Ram Account Password Policy not Required Numbers for Terraform 

Feat(query): Added Ram Account Password Policy not Required Numbers for Terraform

---

assets/queries/terraform/alicloud/ram_password_security_policy_not_require_at_least_one_lowercase_character/metadata.json
assets/queries/terraform/alicloud/ram_password_security_policy_not_require_at_least_one_lowercase_character/query.rego
assets/queries/terraform/alicloud/ram_password_security_policy_not_require_at_least_one_lowercase_character/test/negative1.tf
assets/queries/terraform/alicloud/ram_password_security_policy_not_require_at_least_one_lowercase_character/test/negative2.tf
assets/queries/terraform/alicloud/ram_password_security_policy_not_require_at_least_one_lowercase_character/test/positive1.tf
assets/queries/terraform/alicloud/ram_password_security_policy_not_require_at_least_one_lowercase_character/test/positive_expected_result.json

- Added RAM Account Password Policy Not Required Lowercase Characters for Terraform

Feat(query):  Added RAM Account Password Policy Not Required Lowercase Characters for Terraform

---

assets/queries/terraform/alicloud/ram_password_security_policy_not_require_at_least_one_uppercase_character/metadata.json
assets/queries/terraform/alicloud/ram_password_security_policy_not_require_at_least_one_uppercase_character/query.rego
assets/queries/terraform/alicloud/ram_password_security_policy_not_require_at_least_one_uppercase_character/test/negative1.tf
assets/queries/terraform/alicloud/ram_password_security_policy_not_require_at_least_one_uppercase_character/test/negative2.tf
assets/queries/terraform/alicloud/ram_password_security_policy_not_require_at_least_one_uppercase_character/test/positive1.tf
assets/queries/terraform/alicloud/ram_password_security_policy_not_require_at_least_one_uppercase_character/test/positive_expected_result.json

- Added RAM Account Password Policy Not Required Uppercase Characters for Terraform

Feat(query): Added RAM Account Password Policy Not Required Uppercase Characters for Terraform

---

assets/queries/terraform/alicloud/ram_account_password_policy_not_required_symbols/metadata.json
assets/queries/terraform/alicloud/ram_account_password_policy_not_required_symbols/query.rego
assets/queries/terraform/alicloud/ram_account_password_policy_not_required_symbols/test/negative1.tf
assets/queries/terraform/alicloud/ram_account_password_policy_not_required_symbols/test/positive1.tf
assets/queries/terraform/alicloud/ram_account_password_policy_not_required_symbols/test/positive_expected_result.json

- Added RAM Account Password Policy Not Required Symbols

Feat(query): Added RAM Account Password Policy Not Required Symbols for Terraform.

---

assets/libraries/common.rego

- get_nested_values_info return a object with:
- valid: returns if the array_vals are nested in the object (array_vals should be sorted)
- searchKey: returns the searchKey possible
Work done with @joaoReigota1 

feat(common lib): added get_nested_values_info

---

docs/results.md
pkg/report/model/gitlab_sast.go
pkg/report/model/gitlab_sast_test.go

- This PR introduces small fixes related to `gl-sast` reports, by replacing the old version & schema from 13.1.0 to 14.0.1.

Fix(report): Update GL-SAST reports version/schema

---

.github/workflows/kics-gh-action.yaml

- Remove KICS GitHub Actions Comments so it doesn't fail with forks

ci(kics): Remove comments from KICS Github Actions

---

assets/queries/k8s/container_requests_not_equal_to_its_limits/metadata.json
assets/queries/k8s/container_requests_not_equal_to_its_limits/query.rego
assets/queries/k8s/container_requests_not_equal_to_its_limits/test/positive_expected_result.json

- Extend the rule to cover additional resource kinds, e.g., Deployment, DaemonSet, etc.
- Remove redundant `MissingAttribute` checks that are covered by other rules. While this rule has a LOW severity rating, checks for missing cpu and memory attributes are rated MEDIUM. 
- The concerning rules are:
- [cpu_requests_not_set](https://github.com/Checkmarx/kics/blob/master/assets/queries/k8s/cpu_requests_not_set/query.rego)
- [cpu_limits_not_set](https://github.com/Checkmarx/kics/blob/master/assets/queries/k8s/cpu_limits_not_set/query.rego)
- [memory_requests_not_defined](https://github.com/Checkmarx/kics/blob/master/assets/queries/k8s/memory_requests_not_defined/query.rego)
- [memory_limits_not_defined](https://github.com/Checkmarx/kics/blob/master/assets/queries/k8s/memo …

fix(query): Extend container_requests_not_equal_to_its_limits k8s rule to cover further resource kinds and remove redundant checks

---

assets/queries/terraform/aws/sqs_with_sse_disabled/query.rego
assets/queries/terraform/aws/sqs_with_sse_disabled/test/negative3.tf
assets/queries/terraform/aws/sqs_with_sse_disabled/test/positive7.tf
assets/queries/terraform/aws/sqs_with_sse_disabled/test/positive_expected_result.json

From [the documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue#server-side-encryption-sse), there are 2 way to add SSE on a AWS SQS : 
1)  SSE-SQS
2)  SSE-KMS
Currently, the query `terraform/aws/sqs_with_sse_disabled` check only SSE-KMS.
- Update the query `terraform/aws/sqs_with_sse_disabled` to check if one of the 2 ways is set and not null

fix(query): add a missing SSE way for SQS

---

assets/queries/terraform/alicloud/ram_policy_admin_access_not_attached_to_users_groups_roles/metadata.json
assets/queries/terraform/alicloud/ram_policy_admin_access_not_attached_to_users_groups_roles/query.rego
assets/queries/terraform/alicloud/ram_policy_admin_access_not_attached_to_users_groups_roles/test/negative1.tf
assets/queries/terraform/alicloud/ram_policy_admin_access_not_attached_to_users_groups_roles/test/negative2.tf
assets/queries/terraform/alicloud/ram_policy_admin_access_not_attached_to_users_groups_roles/test/negative3.tf
assets/queries/terraform/alicloud/ram_policy_admin_access_not_attached_to_users_groups_roles/test/positive1.tf
assets/queries/terraform/alicloud/ram_policy_admin_access_not_attached_to_users_groups_roles/test/positive2.tf
assets/queries/terraform/alicloud/ram_policy_admin_access_not_attached_to_users_groups_roles/test/positive3.tf
assets/queries/terraform/alicloud/ram_policy_admin_access_not_attached_to_users_groups_roles/test/positive_expected_result.json

- Query: Ram Policy Admin Access Not Attached to Users Groups Roles

Feat(query): Alicloud Terraform Ram Policy Admin Access Not Attached to Users Groups Roles

---

assets/queries/ansible/aws/unknown_port_exposed_to_internet/query.rego
assets/queries/ansible/aws/unknown_port_exposed_to_internet/test/positive.yaml
assets/queries/ansible/aws/unknown_port_exposed_to_internet/test/positive_expected_result.json
assets/queries/cloudFormation/aws/unknown_port_exposed_to_internet/query.rego
assets/queries/cloudFormation/aws/unknown_port_exposed_to_internet/test/positive_expected_result.json
assets/queries/terraform/alicloud/public_security_group_rule_unknown_port/metadata.json
assets/queries/terraform/alicloud/public_security_group_rule_unknown_port/query.rego
assets/queries/terraform/alicloud/public_security_group_rule_unknown_port/test/negative1.tf
assets/queries/terraform/alicloud/public_security_group_rule_unknown_port/test/negative2.tf
assets/queries/terraform/alicloud/public_security_group_rule_unknown_port/test/positive1.tf
assets/queries/terraform/alicloud/public_security_group_rule_unknown_port/test/positive2.tf
assets/queries/terraform/alicloud/public_security_group_rule_unknown_port/test/positive_expected_result.json
assets/queries/terraform/aws/unknown_port_exposed_to_internet/query.rego

Closes #
-Added Alicloud Public Security Group Rule Unknown Port for Terraform
- Fix bugs in:
&emsp; - Unknown Port Exposed To Internet AWS for Ansible
&emsp; - Unknown Port Exposed To Internet AWS for CloudFormation
&emsp; - Unknown Port Exposed To Internet AWS for Terraform

feat(query): Added Alicloud Public Security Group Rule Unknown Port for Terraform

---

assets/queries/terraform/alicloud/ram_security_preference_not_enforce_mfa/metadata.json
assets/queries/terraform/alicloud/ram_security_preference_not_enforce_mfa/query.rego
assets/queries/terraform/alicloud/ram_security_preference_not_enforce_mfa/test/negative1.tf
assets/queries/terraform/alicloud/ram_security_preference_not_enforce_mfa/test/positive1.tf
assets/queries/terraform/alicloud/ram_security_preference_not_enforce_mfa/test/positive2.tf
assets/queries/terraform/alicloud/ram_security_preference_not_enforce_mfa/test/positive3.tf
assets/queries/terraform/alicloud/ram_security_preference_not_enforce_mfa/test/positive_expected_result.json

-Added Alicloud RAM Security Preference Not Enforce MFA Login for Terraform

feat(Query): Added Alicloud RAM Security Preference Not Enforce MFA Login for Terraform

---

assets/queries/k8s/root_container_not_mounted_as_read_only/metadata.json
assets/queries/k8s/root_container_not_mounted_as_read_only/query.rego
assets/queries/k8s/root_container_not_mounted_as_read_only/test/positive_expected_result.json

- Fold the check for the existence of `container.securityContext` with the check for `readOnlyRootFilesystem`
- Correct the spec reference `searchKey` to the actual path

fix(query): Fix path to spec in root_container_not_mounted_as_read_only k8s rule

---

assets/queries/terraform/alicloud/actiontrail_trail_oss_bucket_is_publicly_accessible/query.rego
pkg/analyzer/analyzer.go

- removed metadata regex for k8s to be possible to identify KubeletConfiguration

update(analyzer): removed metadata regex for k8s

---

assets/queries/k8s/containers_running_as_root/metadata.json
assets/queries/k8s/containers_running_as_root/query.rego
assets/queries/k8s/containers_running_as_root/test/positive4.yaml
assets/queries/k8s/containers_running_as_root/test/positive_expected_result.json

**Problem**
- The condition: `pod.securityContext.runAsNonRoot == false` and `pod.securityContext.runAsUser undefined`, is missing. This leads to false positives.
- The current rule implementation requires that a securityContext is defined at pod level so that `checkRootParent` is evaluated. The same applies to `checkUserContainer`. Patching the rule such that `securityContext` may or may not be specified is tricky and would potentially break the rule logic.
- Rewrite / simplify the current rule implementation by inverting the logic. Instead of looking for spots where runAsUser > 0 or runAsNonRoot == true (and performing a no-op recursion to `checkRootContainer`), the opposite is now looked up

fix(query): Extend containers_running_as_root k8s rule to work if no securityContext is defined

---

assets/queries/k8s/missing_app_armor_config/metadata.json
assets/queries/k8s/missing_app_armor_config/query.rego
assets/queries/k8s/missing_app_armor_config/test/positive.yaml
assets/queries/k8s/missing_app_armor_config/test/positive_expected_result.json

**Problem**
- The current rule only works on pods
- There is no check whether AppArmor is configured for each container
- There is no check whether the provided AppArmor profile is reasonable
- An implementation that addresses the issues described above.

fix(query): refine missing_app_armor_config k8s rule to operate on specific containers

---

assets/queries/common/passwords_and_secrets/regex_rules.json
assets/queries/common/passwords_and_secrets/test/negative48.yaml

Closes #5042
- added "Avoiding Secrets Manager arn"

fix(secrets regex): added "Avoiding Secrets Manager arn"

---

e2e/fixtures/E2E_CLI_032_RESULT.json
e2e/fixtures/E2E_CLI_033_RESULT.json
e2e/fixtures/E2E_CLI_036_RESULT.json
e2e/fixtures/E2E_CLI_036_RESULT_2.json
e2e/fixtures/schemas/result.json
e2e/utils/helper.go
internal/console/helpers/helpers.go
internal/tracker/ci.go
pkg/kics/resolver_sink.go
pkg/kics/service.go
pkg/kics/sink.go
pkg/model/summary.go
pkg/parser/parser.go
pkg/scan/post_scan.go

- added lines scanned and lines parsed

feat(logs): added lines scanned and lines parsed

---

.pre-commit-hooks.yaml
docs/integrations_pre_commit.md

Closes #5022
- pre-commit hook fix and integration update

fix(pre-commit): pre-commit hook fix and integration update

---

.pre-commit-hooks.yaml

- Uncomment pre-commit hook code

fix(pre-commit): Uncomment pre-commit hook code

---

assets/queries/k8s/use_service_account_credentials_not_set_to_true/metadata.json
assets/queries/k8s/use_service_account_credentials_not_set_to_true/query.rego
assets/queries/k8s/use_service_account_credentials_not_set_to_true/test/negative1.yaml
assets/queries/k8s/use_service_account_credentials_not_set_to_true/test/negative2.yaml
assets/queries/k8s/use_service_account_credentials_not_set_to_true/test/positive1.yaml
assets/queries/k8s/use_service_account_credentials_not_set_to_true/test/positive2.yaml
assets/queries/k8s/use_service_account_credentials_not_set_to_true/test/positive_expected_result.json

- Added Use Service Account Credentials Not Set To True for Kubernetes

feat(query): Added Use Service Account Credentials Not Set To True for Kubernetes

---

assets/queries/k8s/node_restriction_admission_control_plugin_not_set/metadata.json
assets/queries/k8s/node_restriction_admission_control_plugin_not_set/query.rego
assets/queries/k8s/node_restriction_admission_control_plugin_not_set/test/negative1.yaml
assets/queries/k8s/node_restriction_admission_control_plugin_not_set/test/negative2.yaml
assets/queries/k8s/node_restriction_admission_control_plugin_not_set/test/positive1.yaml
assets/queries/k8s/node_restriction_admission_control_plugin_not_set/test/positive_expected_result.json

- Added Node Restriction Admission Control Plugin Not Set for Kubernetes

feat(query): Added Node Restriction Admission Control Plugin Not Set for Kubernetes

---

assets/queries/k8s/namespace_lifecycle_admission_control_plugin_disabled/metadata.json
assets/queries/k8s/namespace_lifecycle_admission_control_plugin_disabled/query.rego
assets/queries/k8s/namespace_lifecycle_admission_control_plugin_disabled/test/negative1.yaml
assets/queries/k8s/namespace_lifecycle_admission_control_plugin_disabled/test/negative2.yaml
assets/queries/k8s/namespace_lifecycle_admission_control_plugin_disabled/test/positive1.yaml
assets/queries/k8s/namespace_lifecycle_admission_control_plugin_disabled/test/positive2.yaml
assets/queries/k8s/namespace_lifecycle_admission_control_plugin_disabled/test/positive_expected_result.json

- Added Namespace Lifecycle Admission Control Plugin Disabled for Kubernetes

feat(query): Added Namespace Lifecycle Admission Control Plugin Disabled for Kubernetes

---

assets/queries/k8s/pod_security_policy_admission_control_plugin_not_set/metadata.json
assets/queries/k8s/pod_security_policy_admission_control_plugin_not_set/query.rego
assets/queries/k8s/pod_security_policy_admission_control_plugin_not_set/test/negative1.yaml
assets/queries/k8s/pod_security_policy_admission_control_plugin_not_set/test/negative2.yaml
assets/queries/k8s/pod_security_policy_admission_control_plugin_not_set/test/positive1.yaml
assets/queries/k8s/pod_security_policy_admission_control_plugin_not_set/test/positive_expected_result.json

- Added Pod Security Policy Admission Control Plugin Not Set for Kubernetes

feat(query): Added Pod Security Policy Admission Control Plugin Not Set for Kubernetes

---

assets/queries/k8s/etcd_client_certificate_authentication_set_to_false/metadata.json
assets/queries/k8s/etcd_client_certificate_authentication_set_to_false/query.rego
assets/queries/k8s/etcd_client_certificate_authentication_set_to_false/test/negative1.yaml
assets/queries/k8s/etcd_client_certificate_authentication_set_to_false/test/positive1.yaml
assets/queries/k8s/etcd_client_certificate_authentication_set_to_false/test/positive2.yaml
assets/queries/k8s/etcd_client_certificate_authentication_set_to_false/test/positive_expected_result.json

- Added Etcd Client Certificate Authentication Set To False for Kubernetes

feat(query): Added Etcd Client Certificate Authentication Set To False for Kubernetes

---

assets/queries/dockerCompose/restart_policy_on_failure_not_set_to_5/metadata.json
assets/queries/dockerCompose/restart_policy_on_failure_not_set_to_5/query.rego
assets/queries/dockerCompose/restart_policy_on_failure_not_set_to_5/test/negative1.yaml
assets/queries/dockerCompose/restart_policy_on_failure_not_set_to_5/test/positive1.yaml
assets/queries/dockerCompose/restart_policy_on_failure_not_set_to_5/test/positive2.yaml
assets/queries/dockerCompose/restart_policy_on_failure_not_set_to_5/test/positive3.yaml
assets/queries/dockerCompose/restart_policy_on_failure_not_set_to_5/test/positive4.yaml
assets/queries/dockerCompose/restart_policy_on_failure_not_set_to_5/test/positive_expected_result.json

- Query: Restart Policy On Failure Not Set To 5 for docker compose.

Feat(Query): Restart Policy On Failure Not Set To 5 for docker compose

---

.github/scripts/queries-validator/queries-validator.py

Closes #
- This PR fixes a bug related to the queries validator script which was failing when trying to read files that were removed in the PR.

fix(script): queries validator files filtering

---

assets/queries/terraform/gcp/service_account_with_improper_privileges/query.rego
assets/queries/terraform/gcp/service_account_with_improper_privileges/test/negative3.tf

Closes #5206
- Remove `viewer` from list of improper privileges
- Add test to verify that `role/viewer` does not trigger the query

bug: Remove viewer from list of improper privileges

---

assets/queries/k8s/seccomp_profile_is_not_configured/metadata.json
assets/queries/k8s/seccomp_profile_is_not_configured/query.rego
assets/queries/k8s/seccomp_profile_is_not_configured/test/positive_expected_result.json

**Problem**
#4789 updated the seccomp k8s rule to support `seccompProfile`. For backward compatibility with deprecated annotations, the `MissingAttribute` check only proceeded when a `securityContext` already existed. This introduced an unwanted side effect: if containers didn't specify a `securityContext`, no alert was shown.
There is another rule to check the existence of a `securityContext` but it's only rated LOW, meaning that only after fixing this LOW severity issue, the seccomp issue with MEDIUM severity show up.
- Add a check to the `MissingAttribute` query to also work without `securityContext`. A new check ensures that `MissingAttribute` is not shown, if annotations are used
- Extended the description text and updated the URL to point to the modern way of …

fix(query): extended scope of MissingAttribute rule in seccomp k8s rule

---

assets/queries/k8s/pod_or_container_without_resource_quota/metadata.json
assets/queries/k8s/pod_or_container_without_resource_quota/query.rego
assets/queries/k8s/pod_or_container_without_resource_quota/test/positive4.yaml
assets/queries/k8s/pod_or_container_without_resource_quota/test/positive_expected_result.json

- Change `searchKey` to point to the namespace, where possible, otherwise the document name
- Use `checkKind` and also include `PersistentVolumeClaim`
- Merge the two `MissingAttribute` rules. They still deliver the same matches
- Extend the description text

fix(query): fixed searchKey and resource kind in pod_or_container_without_resource_quota k8s rule

---

assets/queries/k8s/pod_or_container_without_limit_range/metadata.json
assets/queries/k8s/pod_or_container_without_limit_range/query.rego
assets/queries/k8s/pod_or_container_without_limit_range/test/positive4.yaml
assets/queries/k8s/pod_or_container_without_limit_range/test/positive_expected_result.json

- Change `searchKey` to point to the namespace, where possible, otherwise the document name
- Use `checkKind` and also include `PersistentVolumeClaim`
- Merge the two `MissingAttribute` rules. They still deliver the same matches
- Extend the description text

fix(query): fixed searchKey and resource kind in pod_or_container_without_limit_range k8s rule

---

assets/queries/terraform/aws/policy_without_principal/query.rego
assets/queries/terraform/aws/policy_without_principal/test/negative3.tf

**Problem**
[iam_policy_document](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document) is an alternative policy specification. When unmarshalled, `Principals` remains as-is and is thus not understood by the `policy_without_principal` rule, which checks only for `Principal`, as in traditional policies.
- Add a check for `Statement.Principals`
- Add another negative testcase

fix(query): added support for aws_iam_policy_document.Principals to policy_without_principal tf rule

---

docs/integrations_gitlabci.md

- Fix code example for Gitlab CI to use the new path for the asset queries
- With the current example, the pipeline fails to properly run kics

docs(implementations): fix changed directory for kics assets queries in Gitlab CI example

---

assets/queries/cloudFormation/aws/alb_listening_on_http/query.rego
assets/queries/cloudFormation/aws/alb_listening_on_http/test/positive3.yaml
assets/queries/cloudFormation/aws/alb_listening_on_http/test/positive_expected_result.json
e2e/fixtures/E2E_CLI_032_RESULT.json
e2e/fixtures/E2E_CLI_036_RESULT.json

- Fix incorrect line in result exposure
- Add positive sample

fix(query): ALB Listening on HTTP for AWS CloudFormation

---

assets/libraries/terraform.rego
assets/queries/terraform/alicloud/oss_bucket_allows_delete_from_all_principals/metadata.json
assets/queries/terraform/alicloud/oss_bucket_allows_delete_from_all_principals/query.rego
assets/queries/terraform/alicloud/oss_bucket_allows_delete_from_all_principals/test/negative1.tf
assets/queries/terraform/alicloud/oss_bucket_allows_delete_from_all_principals/test/negative2.tf
assets/queries/terraform/alicloud/oss_bucket_allows_delete_from_all_principals/test/negative3.tf
assets/queries/terraform/alicloud/oss_bucket_allows_delete_from_all_principals/test/positive1.tf
assets/queries/terraform/alicloud/oss_bucket_allows_delete_from_all_principals/test/positive_expected_result.json

- Query: OSS Bucket Allows Delete From All Principals for Alicloud Terraform

Feat(Query):  OSS Bucket Allows Delete From All Principals for Alicloud Terraform

---

assets/queries/terraform/aws/ecr_repository_not_encrypted/metadata.json
assets/queries/terraform/aws/ecr_repository_not_encrypted/query.rego
assets/queries/terraform/aws/ecr_repository_not_encrypted/test/positive.tf
assets/queries/terraform/aws/ecr_repository_not_encrypted/test/positive_expected_result.json

**Problem**
The TF rule _ECR Repository Not Encrypted_ issues an alert in case `encryption_configuration` is not specified, assuming there is no encryption at all. This is not correct since encryption-at-rest is enabled out-of-the-box for ECR repositories using AWS managed keys. In the AWS TF provider, this is denoted as `AES256` (see [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_repository#encryption_configuration) and [here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/encryption-at-rest.html)).
Practically, this means that the check this rule performs does not match the rule's purpose and it should actually check whether customer-managed keys are used (see [here](https://aws.amazon.com/about-aws/whats-new/2020/07/ecr-supports-encryption …

fix(query): updated ecr_repositories_not_encrypted TF rule to match KMS encryption

---

assets/libraries/terraform.rego
assets/queries/terraform/alicloud/oss_bucket_allows_list_action_from_all_principals/metadata.json
assets/queries/terraform/alicloud/oss_bucket_allows_list_action_from_all_principals/query.rego
assets/queries/terraform/alicloud/oss_bucket_allows_list_action_from_all_principals/test/negative1.tf
assets/queries/terraform/alicloud/oss_bucket_allows_list_action_from_all_principals/test/negative2.tf
assets/queries/terraform/alicloud/oss_bucket_allows_list_action_from_all_principals/test/negative3.tf
assets/queries/terraform/alicloud/oss_bucket_allows_list_action_from_all_principals/test/positive1.tf
assets/queries/terraform/alicloud/oss_bucket_allows_list_action_from_all_principals/test/positive2.tf
assets/queries/terraform/alicloud/oss_bucket_allows_list_action_from_all_principals/test/positive_expected_result.json

- Query: Oss Bucket Allows List Action From All Principals for Alicloud Terraform

Feat(query): Oss Bucket Allows List Action From All Principals for Alicloud Terraform

---

assets/libraries/terraform.rego
assets/queries/terraform/alicloud/oss_bucket_allows_put_action_from_all_principals/metadata.json
assets/queries/terraform/alicloud/oss_bucket_allows_put_action_from_all_principals/query.rego
assets/queries/terraform/alicloud/oss_bucket_allows_put_action_from_all_principals/test/negative1.tf
assets/queries/terraform/alicloud/oss_bucket_allows_put_action_from_all_principals/test/negative2.tf
assets/queries/terraform/alicloud/oss_bucket_allows_put_action_from_all_principals/test/negative3.tf
assets/queries/terraform/alicloud/oss_bucket_allows_put_action_from_all_principals/test/positive1.tf
assets/queries/terraform/alicloud/oss_bucket_allows_put_action_from_all_principals/test/positive2.tf
assets/queries/terraform/alicloud/oss_bucket_allows_put_action_from_all_principals/test/positive_expected_result.json

- Query: Oss Bucket Allows Put Action For All Principals for Alicloud Terraform

Feat(Query): Oss Bucket Allows Put Action For All Principals for Alicloud Terraform

---

pkg/parser/yaml/parser.go

PR #5222 lost some results because "it found" a bug related to the ignoreLines (that was caught miraculously).
For example, with the flag -`t openapi`, the analyzer will call `checkReturnType` which calls `checkYamlPlatform`. 
In the `checkYamlPlatform` function, the YAML file is unmarshalled and it saves the ignoresLines in `model.NewIgnore`.
Since the `model.NewIgnore` is not reset at the beginning of the parser, it keeps the ignoreLines of the previous files that were discarded.
- This PR resets the model.NewIgnore in at the beginning of the parser.

fix(yaml parser): added model.NewIgnore.Reset() at the beginning of the YAML parser

---

e2e/README.md
pkg/engine/provider/filesystem.go

- fixed GetExcludedPaths
- fixed E2E tests

fix(filesystem): GetExcludedPaths

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/new-feature.md
.github/ISSUE_TEMPLATE/query.md

This change is possible as core team members mostly create PRs.

Add community tag to new issues by default

---

assets/queries/k8s/rbac_roles_with_portforwarding_permissions/metadata.json
assets/queries/k8s/rbac_roles_with_portforwarding_permissions/query.rego
assets/queries/k8s/rbac_roles_with_portforwarding_permissions/test/negative.yaml
assets/queries/k8s/rbac_roles_with_portforwarding_permissions/test/positive.yaml
assets/queries/k8s/rbac_roles_with_portforwarding_permissions/test/positive_expected_result.json

- Add new rule to check whether RBAC roles allow port-forwarding into pods. This is sometimes useful for troubleshooting but dangerous in production. In case of pod compromise, attackers may be able to bypass network security restrictions or probe container ports directly

feat(query): add new k8s rule to detect port-forwarding into containers (RBAC)

---

assets/queries/k8s/rbac_roles_with_impersonate_permission/metadata.json
assets/queries/k8s/rbac_roles_with_impersonate_permission/query.rego
assets/queries/k8s/rbac_roles_with_impersonate_permission/test/negative.yaml
assets/queries/k8s/rbac_roles_with_impersonate_permission/test/positive.yaml
assets/queries/k8s/rbac_roles_with_impersonate_permission/test/positive_expected_result.json

- Add new rule to check whether RBAC roles make use of the 'impersonate' verb to allow impersonation of others users, groups, serviceaccounts. This sudo-like functionality is sometimes useful for troubleshooting but very dangerous in production. In case of pod compromise, attackers may be able to impersonate system:admin or other highly privileged users and thereby escalate their privileges to the whole cluster
- This rule covers CIS Kubernetes Benchmark 1.23, 5.1.8

feat(query): add new k8s rule to detect account impersonation (RBAC)

---

assets/queries/k8s/rbac_roles_allow_privilege_escalation/metadata.json
assets/queries/k8s/rbac_roles_allow_privilege_escalation/query.rego
assets/queries/k8s/rbac_roles_allow_privilege_escalation/test/negative.yaml
assets/queries/k8s/rbac_roles_allow_privilege_escalation/test/positive.yaml
assets/queries/k8s/rbac_roles_allow_privilege_escalation/test/positive_expected_result.json

- Add new rule to check whether RBAC roles are allowed to create new Roles or RoleBindings. This is dangerous, as the created roles may include resources and permissions that exceed the privileges of the role that is used to create them.
- This rule covers CIS Kubernetes Benchmark 1.23, 5.1.8
A longer explanation of why this is a problem, can also be found [here](https://raesene.github.io/blog/2021/01/16/Getting-Into-A-Bind-with-Kubernetes/).

feat(query): add new k8s rule to detect bind or escalate permissions (RBAC)

---

assets/queries/k8s/rbac_roles_with_exec_permission/metadata.json
assets/queries/k8s/rbac_roles_with_exec_permission/query.rego
assets/queries/k8s/rbac_roles_with_exec_permission/test/negative.yaml
assets/queries/k8s/rbac_roles_with_exec_permission/test/positive.yaml
assets/queries/k8s/rbac_roles_with_exec_permission/test/positive_expected_result.json

- Add new rule to check whether RBAC roles allow to run 'kubectl exec' to execute commands in containers. This is sometimes useful for troubleshooting but dangerous in production. In case of compromise, attackers may abuse this to subject to execute malicious code

feat(query): add new k8s rule to detect exec permissions (RBAC)

---

docs/getting-started.md

Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>
References #4871 #5241 https://github.com/Checkmarx/homebrew-tap/issues/1
- _L13_ corrects the `docker run` command, the present code is  `{<200b><200b><200b><200b>path_to_host_folder_to_scan}<200b><200b><200b><200b>`
- Installing KICS using `brew`, _L28:45_, will only result in the installation of an out-of-date release
- Moved "Custom Queries" to after the "Build from Sources" section, since the focus of the page is installation
- Added a note regarding deprecated binaries and updated the notes with links

update installation options and notes

---

assets/queries/k8s/statefulset_without_service_name/metadata.json
assets/queries/k8s/statefulset_without_service_name/query.rego
assets/queries/k8s/statefulset_without_service_name/test/negative.yaml
assets/queries/terraform/kubernetes/statefulset_without_service_name/metadata.json
assets/queries/terraform/kubernetes/statefulset_without_service_name/query.rego

- Modify check for matched labels between Headless service and StatefulSet

update(query):  StatefulSet Without Service Name for Kubernetes

---

assets/queries/k8s/rbac_wildcard_in_rule/metadata.json
assets/queries/k8s/rbac_wildcard_in_rule/query.rego
assets/queries/k8s/rbac_wildcard_in_rule/test/positive_expected_result.json

- Add `searchLine` to point to specific rule attributes
- Combine the CxPolicy rules into one
- Extend description
- Adjust rating from LOW to MEDIUM (or HIGH?) for the following reasons:
- The rule [rbac_roles_with_read_secrets_permissions](https://github.com/Checkmarx/kics/blob/master/assets/queries/k8s/rbac_roles_with_read_secrets_permissions/query.rego) checks for a specific "permission subset" of this rule and  is rated MEDIUM. This rule here implicitly also covers the same case as the other rule by checking for wildcards, which allow even wider access rights
- Wildcard permissions on resources (pods, depoyments, secrets, ...) also include create, update, patch, delete, bind, escalate, impersonate verbs. Attackers may abuse this to perform mutating changes, e.g., …

fix(query): adjusted severity rating and added searchLine in rbac_wildcard_in_rule k8s rule

---

internal/console/helpers/helpers.go
internal/console/pre_scan.go

- If application is running inside docker container, we should look at `/sys/fs/cgroup/cpu/cpu.cfs_quota_us` to get the actual number of cpus available

fix(cpu): fixed number of cpus available info

---

internal/console/pre_scan.go
internal/metrics/metrics.go
internal/metrics/metrics_test.go

- fixed access to CIFlag in InitializeMetrics

fix(InitializeMetrics): fixed access to CIFlag

---

internal/constants/constants.go
pkg/detector/default_detect.go
pkg/detector/docker/docker_detect.go
pkg/detector/helper.go
pkg/detector/helper_test.go
pkg/engine/vulnerability_utils.go
pkg/parser/json/parser.go
pkg/parser/yaml/parser.go
pkg/resolver/file/file.go
pkg/resolver/file/file_test.go

Signed-off-by: João Reigota <joao.Reigota@checkmarx.com>
- cleaned log polution

update(resolver): implemented limit in resolver to 50 files

---

docs/BADGE.md
docs/configuration-file.md
docs/dockerhub.md
docs/getting-started.md
docs/platforms.md
docs/running-kics.md

- Added -t flag on docker run command

update(docs): added -t flag on docker run command

---

assets/queries/terraform/azure/default_azure_storage_account_network_access_is_too_permissive/query.rego
assets/queries/terraform/general/name_is_not_snake_case/query.rego
pkg/parser/json/tfplan.go

Closes #5327
- support child modules
- corrected `searchLine` in queries `assets/queries/terraform/general/name_is_not_snake_case` and `assets/queries/terraform/azure/default_azure_storage_account_network_access_is_too_permissive`

update(tfplan parser): support child modules

---

.github/workflows/go-ci-integration.yml
.github/workflows/go-ci.yml
.github/workflows/go-e2e.yaml
.github/workflows/kics-gh-action.yaml
.github/workflows/sonarcloud.yml
.github/workflows/sync_major_release.yaml

- added a workflow that creates a PR that merges the `master` to `release/1.6` (name of the branch for KICS v1.6 development process) every time a push is done in the master (sync `master` to `release/1.6`). Furthermore, it was added the KICS tests to branch `release/1.6`.
- As an example how the Sync PR will look like, see:

feat(workflows): added branching process for major versions

---

.github/workflows/go-ci.yml
.github/workflows/go-test-race.yml
assets/queries/k8s/object_is_using_a_deprecated_api_version/query.rego
assets/queries/k8s/tiller_is_deployed/query.rego
assets/queries/k8s/tiller_service_is_not_deleted/query.rego
pkg/engine/secrets/inspector.go

- added mutex to lock `addVulnerability` function. This way, the GitHub action `go-test-race` will no longer fail due to data race in `addVulnerability` function
- increased timeout for go-test-race action (to 3600 s)
- increased timeout for go lint action (to 20 min)
- fixed tiller queries

fix(secrets inspector): added mutex to lock addVulnerability

---

Dockerfile

Closes #5486
Closes #5487
- fixed CVE-2022-1586: upgrade pcre2
- fixed CVE-2022-29810: upgrade terraform and terraform azurerm provider

update(dockerfile): fix CVE-2022-1586 and CVE-2022-29810

---

pkg/resolver/file/file.go

Closes #5495
- exclude resolve path in the same path reference

fix(resolver): exclude resolve path call for the same path reference

---

docs/commands.md
docs/dockerhub.md
e2e/fixtures/assets/scan_help
internal/constants/constants.go
pkg/engine/source/filesystem.go
pkg/engine/source/filesystem_test.go

Closes #5560
- support alicloud in the `--cloud-provider` flag

fix(cloud provider flag): support alicloud in the cloud provider flag

---

assets/queries/common/passwords_and_secrets/regex_rules.json
pkg/engine/secrets/inspector.go

Issue #4975 will be closed when the branch `release/1.6` is merged into the master.
- hide secrets in report results
As an example:

feat(report): hide secrets in report results

---

assets/queries/common/passwords_and_secrets/test/negative10.tf
assets/queries/common/passwords_and_secrets/test/negative24.tf
assets/queries/common/passwords_and_secrets/test/negative29.tf
assets/queries/common/passwords_and_secrets/test/negative37.tf
assets/queries/common/passwords_and_secrets/test/positive15.tf
assets/queries/common/passwords_and_secrets/test/positive24.tf
assets/queries/common/passwords_and_secrets/test/positive37.tf
assets/queries/common/passwords_and_secrets/test/positive41.tf
assets/queries/common/passwords_and_secrets/test/positive_expected_result.json
assets/queries/terraform/aws/iam_policy_grants_assumerole_permission_across_all_services/test/negative.tf
assets/queries/terraform/aws/iam_policy_grants_assumerole_permission_across_all_services/test/positive.tf
assets/queries/terraform/aws/instance_with_no_vpc/test/negative1.tf
assets/queries/terraform/aws/security_groups_not_used/test/negative3.tf
assets/queries/terraform/aws/security_groups_not_used/test/negative4.tf
assets/queries/terraform/azure/aks_rbac_disabled/query.rego
assets/queries/terraform/azure/aks_rbac_disabled/test/negative.tf
assets/queries/terraform/azure/aks_rbac_disabled/test/positive.tf
assets/queries/terraform/azure/aks_rbac_disabled/test/positive_expected_result.json
assets/queries/terraform/kubernetes/deployment_without_pod_disruption_budget/test/negative.tf
assets/queries/terraform/kubernetes/network_policy_is_not_targeting_any_pod/test/negative.tf
assets/queries/terraform/kubernetes/statefulset_without_pod_disruption_budget/test/negative.tf

- fixes part of #5453
- "The deprecated block role_based_access_control will be removed in favour of the role_based_access_control_enabled property and the azure_active_directory_role_based_access_control block." - see https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide

fix(query): azure aks rbac-variable changed

---

pkg/parser/terraform/converter/default.go
pkg/parser/terraform/terraform_test.go
test/fixtures/test-tf-parentheses/parenteses.tf

Closes #5605
- added parentheses expr to convertStringPart

fix(tf parser): added parentheses expr to convertStringPart

---

assets/queries/terraform/aws/api_gateway_with_cloudwatch_logging_disabled/metadata.json
assets/queries/terraform/aws/api_gateway_with_cloudwatch_logging_disabled/query.rego
assets/queries/terraform/aws/api_gateway_with_cloudwatch_logging_disabled/test/negative.tf
assets/queries/terraform/aws/api_gateway_with_cloudwatch_logging_disabled/test/positive.tf
assets/queries/terraform/aws/api_gateway_with_cloudwatch_logging_disabled/test/positive_expected_result.json

Closes #5689 
- Change approach in api_gateway_with_cloudwatch_logging_disabled Terraform AWS to recommended naming convention in the documentation

fix(query): change approach in api_gateway_with_cloudwatch_logging_disabled security query for terraform aws

---

assets/queries/dockerfile/curl_or_wget_instead_of_add/metadata.json
assets/queries/dockerfile/curl_or_wget_instead_of_add/query.rego
assets/queries/dockerfile/curl_or_wget_instead_of_add/test/negative2.dockerfile

Closes #5699 
- improve RegEx to check `://` in http/https check inside query

fix(query): improve RegEx rule in curl_or_wget_instead_of_add

---

pkg/parser/docker/parser.go
pkg/parser/docker/parser_test.go

Closes #5621
- added resolver for args

fix(docker parser): added resolver for args

---

pkg/detector/helper.go
pkg/engine/secrets/inspector.go
pkg/model/comment_yaml.go
pkg/model/model_yaml.go
pkg/model/model_yaml_test.go
pkg/resolver/file/file.go
pkg/resolver/file/file_test.go

Closes #5685
- consider comments in YAML resolver

fix(resolver): consider comments in YAML resolver

---

Dockerfile

- Add version pining to KICS DockerFIle gcompat package

fix(bug): add version to gcompat in kics dockerfile

---

examples/gitlab/KICS.gitlabci.yaml
examples/gitlab/KICS.v3.gitlabci.yaml

- add --ci flag to gitlab examples
using the example unnecessarily spams the gitlab output and makes it uncomfortable to work with it. especially results of long lasting scans are hard to read.

chore(gitlab-ci): add --ci flag to gitlab examples

---

assets/queries/openAPI/general/invalid_format/metadata.json
assets/queries/openAPI/general/invalid_format/query.rego
assets/queries/openAPI/general/invalid_format/test/positive_expected_result.json

Closes #5747 
- remove string format check for security query "Invalid Format"

fix(query): remove string check in open api security query

---

assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/query.rego
assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/test/negative3.tf

Closes #5763
- update  s3 bucket policy accepts http requests security to unmarshal JSON before the function
- add a negative sample

fix(query): update s3 bucket policy accepts http requests security query

---

assets/libraries/terraform.rego
assets/queries/terraform/aws/lambda_function_with_privileged_role/metadata.json
assets/queries/terraform/aws/lambda_function_with_privileged_role/query.rego
assets/queries/terraform/aws/lambda_function_with_privileged_role/test/positive.tf
assets/queries/terraform/aws/lambda_function_with_privileged_role/test/positive_expected_result.json

- lambda_function_with_privileged_role was failing with 'multiple outputs for same input' when the policy had multiple statements

fix(query): updated lambda_function_with_privileged_role

---

pkg/parser/terraform/terraform.go

Closes #5808 
- fix unhandled panic form `processElements()` in `terraform.go`
- add support for `processContent` of `certificate_body` from tfvar

fix(bug): add support for certificate body process from tfvar

---

assets/queries/openAPI/general/responses_wrong_http_status_code/query.rego
assets/queries/openAPI/general/responses_wrong_http_status_code/test/negative2.yaml

Closes #5805 
- responses with wrong http status code

fix(query): fix responses with wrong http status code security query

---

.github/workflows/release-docker-github-actions.yaml

- Tag update for the 1.6 KICS version

gh action tag update for 1.6 kics version

---

docs/commands.md
docs/configuration-file.md

- Docs suggestions. When I was trying to setup docs, I had to use the online docs, and finding out anything was an awful pain especially because I had to search through the code.
I did not create an issue first because having something concrete to comment about is faster than explaining my suggestions, and then implementing them. The PR is of course not final, I would like to first know you thoughts, improvements, and I have a few questions. When all is done, I would adjust the JSON, TOML etc. parts as well.
Questions:
- Why is the section "Using commands on scanned files as comments" in "Running KICS" rather than configuration section?
- Does `verbse` flag work? When we set it `verbose=false` there was no difference with `verbose=true` that we could see.
- `type: …

update(docs): improve information in  the configuration docs

---

assets/queries/ansible/gcp/high_google_kms_crypto_key_rotation_period/metadata.json
assets/queries/ansible/gcp/high_google_kms_crypto_key_rotation_period/query.rego
assets/queries/ansible/gcp/high_google_kms_crypto_key_rotation_period/test/negative.yaml
assets/queries/ansible/gcp/high_google_kms_crypto_key_rotation_period/test/positive.yaml
assets/queries/terraform/gcp/high_google_kms_crypto_key_rotation_period/metadata.json
assets/queries/terraform/gcp/high_google_kms_crypto_key_rotation_period/query.rego

**Problem**
- The same query differs for Ansible and TF queries regarding the checked criteria: > 7776000, < 7776000
- The Ansible testcase is wrong as it checks the opposite
- Streamline both queries
- Extend description to include reasoning

fix(query): correct GCP KMS crypto key rotation period queries + descriptions

---

assets/queries/terraform/aws/iam_access_key_is_exposed/metadata.json
assets/queries/terraform/aws/iam_access_key_is_exposed/query.rego
assets/queries/terraform/aws/iam_access_key_is_exposed/test/negative.tf
assets/queries/terraform/aws/iam_access_key_is_exposed/test/positive.tf

Closes #5845
Referring to [AWS CIS Controls 1.12](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-1.12)
- fix the query
- fix the tests

fix(query): terraform/aws/iam_access_key_is_exposed

---

assets/queries/terraform/aws/ec2_instance_using_api_keys/query.rego
assets/queries/terraform/aws/ec2_instance_using_api_keys/test/negative3.tf
assets/queries/terraform/aws/ec2_instance_using_api_keys/test/negative4.tf

Fix user_data in aws_instance reporting false positive, even when API keys are not present in string.
Closes #5890
- Compare the size of the resulting array instead of the array directly 

fix(query): fix false positive in aws_instance

---

assets/queries/ansible/aws/rds_with_backup_disabled/query.rego
assets/queries/ansible/aws/rds_with_backup_disabled/test/negative.yaml
assets/queries/ansible/aws/rds_with_backup_disabled/test/positive.yaml
assets/queries/ansible/aws/rds_with_backup_disabled/test/positive_expected_result.json
assets/queries/terraform/aws/rds_with_backup_disabled/query.rego
assets/queries/terraform/aws/rds_with_backup_disabled/test/negative3.tf
assets/queries/terraform/aws/rds_with_backup_disabled/test/negative4.tf
assets/queries/terraform/aws/rds_with_backup_disabled/test/positive2.tf
assets/queries/terraform/aws/rds_with_backup_disabled/test/positive_expected_result.json

Since the there is a default value for `backup_retention_period`, the query reported a false positive if the field was not set. This has been fixed.
Closes #5882
- Ignore missing backup_retention_period value for rds_instances

fix(query): fix false positive for rds backup_retention_period not set

---

assets/queries/k8s/object_is_using_a_deprecated_api_version/metadata.json
assets/queries/k8s/object_is_using_a_deprecated_api_version/query.rego
assets/queries/k8s/object_is_using_a_deprecated_api_version/test/positive.yaml
assets/queries/k8s/object_is_using_a_deprecated_api_version/test/positive_expected_result.json

- Add more CRD deprecations to the rule (previously mentioned here: https://github.com/Checkmarx/kics/pull/4830#pullrequestreview-881390156)
- Extend description
- Change category to "Best Practices": Using a Kubernetes resource with a deprecated API version is not a security risk, comparable to others in that category (e.g. seccomp profile missing). Newer versions are not "more secure", only less likely to cause problems during K8s upgrades.

fix(query): cover additional deprecated API versions in k8s rule

---

assets/queries/terraform/aws/cloudwatch_log_group_not_encrypted/metadata.json
assets/queries/terraform/aws/cloudwatch_log_group_not_encrypted/test/positive_expected_result.json

Closes #5862
- update query name
- update query severity

fix(query): update CloudWatch Log Group Without KMS Security Query MetaData

---

assets/queries/terraform/aws/hardcoded_aws_access_key_in_lambda/query.rego
assets/queries/terraform/aws/hardcoded_aws_access_key_in_lambda/test/positive.tf
assets/queries/terraform/aws/hardcoded_aws_access_key_in_lambda/test/positive_expected_result.json

Closes #5859
- improved regex to find AWS Access Key in `assets/queries/terraform/aws/hardcoded_aws_access_key_in_lambda`

fix(query): improved regex to find AWS Access Key in assets/queries/terraform/aws/hardcoded_aws_access_key_in_lambda

---

assets/queries/dockerfile/vulnerable_openssl_version/metadata.json
assets/queries/dockerfile/vulnerable_openssl_version/query.rego
assets/queries/dockerfile/vulnerable_openssl_version/test/negative1.dockerfile
assets/queries/dockerfile/vulnerable_openssl_version/test/negative2.dockerfile
assets/queries/dockerfile/vulnerable_openssl_version/test/negative3.dockerfile
assets/queries/dockerfile/vulnerable_openssl_version/test/negative4.dockerfile
assets/queries/dockerfile/vulnerable_openssl_version/test/negative5.dockerfile
assets/queries/dockerfile/vulnerable_openssl_version/test/negative6.dockerfile
assets/queries/dockerfile/vulnerable_openssl_version/test/negative7.dockerfile
assets/queries/dockerfile/vulnerable_openssl_version/test/positive1.dockerfile
assets/queries/dockerfile/vulnerable_openssl_version/test/positive2.dockerfile
assets/queries/dockerfile/vulnerable_openssl_version/test/positive3.dockerfile
assets/queries/dockerfile/vulnerable_openssl_version/test/positive4.dockerfile
assets/queries/dockerfile/vulnerable_openssl_version/test/positive5.dockerfile
assets/queries/dockerfile/vulnerable_openssl_version/test/positive6.dockerfile
assets/queries/dockerfile/vulnerable_openssl_version/test/positive7.dockerfile
assets/queries/dockerfile/vulnerable_openssl_version/test/positive_expected_result.json
pkg/parser/docker/parser.go

- added "Vulnerable OpenSSL Version" for Dockerfile

feat(query): added "Vulnerable OpenSSL Version" for Dockerfile

---

pkg/engine/inspector.go
pkg/scanner/scanner_test.go

Closes #5986
- Return err in `QueryLoader.LoadQuery` when ctx timeout, instead of nil, to prevent nil dereference panic.

fix: scanner panics when ctx timeout

---

assets/libraries/dockerfile.rego
assets/queries/dockerfile/unpinned_package_version_in_apk_add/test/negative2.dockerfile

Closes #6000 
- update with version regex in dockerfile.rego to support packages with '+' in name

fix(query): update with version regex for unpinned package version in apk add security query

---

assets/queries/terraform/azure/aks_disk_encryption_set_id_undefined/metadata.json
assets/queries/terraform/azure/aks_disk_encryption_set_id_undefined/query.rego
assets/queries/terraform/azure/aks_disk_encryption_set_id_undefined/test/negative.tf

Closes #6022 
- add check for os disk type
- add negative sample
- update query description

fix(query): update tf azure aks disk encryption set id undefined security query

---

README.md
mkdocs.yml

docs: update copyright date

---

assets/queries/openAPI/general/array_without_maximum_number_items/query.rego
assets/queries/openAPI/general/array_without_maximum_number_items/test/positive_expected_result.json

- add search line to array without maximum number items open api query

fix(query): add search line to array without maximum number items open api query

---

README.md

Remove release process section, we stopped providing binaries after version 1.5.2

Place documentation link higher in README file

---

.github/workflows/go-ci-coverage.yaml
.github/workflows/go-ci.yml
.github/workflows/go-e2e.yaml
.github/workflows/go-test-race.yml
.github/workflows/release-apispec.yml
.github/workflows/release-commits.yaml
.github/workflows/release-nightly.yml
.github/workflows/release.yml
.github/workflows/statistics.yaml
docker/Dockerfile.ubi8
e2e/testcases/e2e-cli-057_fix_all.go
e2e/testcases/e2e-cli-058_fix_include_ids.go
e2e/testcases/utils.go
go.mod
internal/console/remediate.go
internal/console/scan.go
internal/storage/memory_test.go
pkg/builder/parser/tag/tag_parser_test.go
pkg/builder/writer/rego.go
pkg/descriptions/client.go
pkg/engine/inspector_test.go
pkg/engine/source/filesystem_test.go
pkg/kics/service.go
pkg/parser/terraform/converter/default_test.go
pkg/resolver/helm/resolver_test.go

Closes #
- go major version update (1.19)

bump(go) go version 1.19

---

assets/queries/terraform/aws/unrestricted_security_group_ingress/metadata.json
assets/queries/terraform/aws/unrestricted_security_group_ingress/query.rego
assets/queries/terraform/aws/unrestricted_security_group_ingress/test/negative5.tf
assets/queries/terraform/aws/unrestricted_security_group_ingress/test/negative6.tf
assets/queries/terraform/aws/unrestricted_security_group_ingress/test/negative7.tf
assets/queries/terraform/aws/unrestricted_security_group_ingress/test/negative8.tf
assets/queries/terraform/aws/unrestricted_security_group_ingress/test/positive10.tf
assets/queries/terraform/aws/unrestricted_security_group_ingress/test/positive6.tf
assets/queries/terraform/aws/unrestricted_security_group_ingress/test/positive7.tf
assets/queries/terraform/aws/unrestricted_security_group_ingress/test/positive8.tf
assets/queries/terraform/aws/unrestricted_security_group_ingress/test/positive9.tf
assets/queries/terraform/aws/unrestricted_security_group_ingress/test/positive_expected_result.json

There is currently no limitation on IPV6 security groups in ingress. So I propose rules to avoid opening to everything.
Add the same IPV4 rules with ipv6 settings
I created :
- 4 negative tests : `negative5.tf`, `negative6.tf`, `negative7.tf`, `negative8.tf`
- 5 positive tests : `postive6.tf`, `positive7.tf`, `positive8.tf`, `positive9.tf`, `positive10.tf`

feat(terraform/aws): ingress ipv6 security group

---

assets/queries/terraform/aws/s3_bucket_sse_disabled/query.rego
assets/queries/terraform/aws/s3_bucket_sse_disabled/test/negative4.tf

**Context**
When a bucket and its SSE configuration use `count`, the query evaluates to true (false positive). (AWS provider v4)
- Add function is_associated to lookup all bucket associated with a sse configuration.
**How to test**
- See new test `negative4.tf`
- Comment out line 112 and `kics scan -p test/negative4.tf -q .` -> query is positive
- Put line 112 back and `kics scan -p test/negative4.tf -q .` -> query is negative

fix(terraform/aws): sse query failing on bucket with count

---

assets/queries/common/passwords_and_secrets/regex_rules.json
assets/queries/common/passwords_and_secrets/test/positive25.dockerfile
assets/queries/common/passwords_and_secrets/test/positive_expected_result.json

Closes #6098 
- add password and secrets regex rule for sendgrid API key detection

feat(query): add password and secrets detection for sendgrid api key

---

.github/scripts/report/e2e-html.go
pkg/descriptions/client.go
pkg/report/html.go

- add error checking in deferring in io.close()
[go_sec findings](https://github.com/Checkmarx/kics/pull/6143/checks?check_run_id=11151416752
)

fix(go_sec): add error checking in deferring in io.close()

---

assets/queries/serverlessFW/serverless_function_without_tags/query.rego
assets/queries/serverlessFW/serverless_function_without_tags/test/negative2.yml

- add missing check for stack tags in ServerlessFW Serverless Function Without Tags security query

fix(query): add missing check for stack tags in serverlessfw security query

---

pkg/analyzer/analyzer.go
pkg/analyzer/analyzer_test.go
pkg/model/model.go
pkg/scan/utils_test.go
pkg/utils/line_counter.go
pkg/utils/line_counter_test.go

- add expected loc in the analyzer
- add line_counter to utils
- add/update tests

feat(analyzer): add expected lines of code in analyzer

---

assets/libraries/common.rego

- Per [Terraform's documentation](https://developer.hashicorp.com/terraform/tutorials/aws/aws-iam-policy#:~:text=Copy%20the-,aws_iam_policy_document,-configuration%20below%20into), iam policy statements' `Effect` can be declared as either `Effect` or `effect`
- The proposed change ensures both cases are validated when checking whether the statements is an `Allow` statement
- This solves false-positive cases where statements with `effect: Deny` are evaluated as being `Allow`

Policy effect should be case insensitive

---

assets/queries/serverlessFW/serverless_function_without_unique_iam_role/query.rego
assets/queries/serverlessFW/serverless_function_without_unique_iam_role/test/negative2.yml
assets/queries/serverlessFW/serverless_function_without_unique_iam_role/test/positive2.yml
assets/queries/serverlessFW/serverless_function_without_unique_iam_role/test/positive_expected_result.json

- Update query to check when 'functions' is an array
- Tests added

fix(query): serverless_function_without_unique_iam_role

---

pkg/parser/terraform/comment/comment.go
pkg/parser/terraform/comment/comment_test.go

Closes https://github.com/Checkmarx/kics/issues/6262
- Fixed bug - Terraform ParseComments, in case of comment at the end line do not ignore this line for example:
-			rest_api_id   = "some rest api id" # comment
stage_name    = "development"     // comment
description   = "DEV"             /* comment */
- Added test case 

bug(terraform comments): fix ignore lines with comments only at the end

---

docs/results.md
e2e/fixtures/schemas/result-gl-sast.json
pkg/report/model/gitlab_sast.go
pkg/report/model/gitlab_sast_test.go

Closes #6318
- update SAST report schema to version 15.0.6
- remove deprecated fields from the `vulnerabilities[]` object and add required `analyzer` object

chore(-): update gitlab sast schema to 15.0.6

---

assets/queries/common/passwords_and_secrets/regex_rules.json

- Remove allowRule for query Generic Password (this allow rule is not relevant in any test and the tests pass without it, it is however excluding some good results)

remove unused allowRule

---

Dockerfile

Closes #6459
Drop patch version from alpine docker tag

Drop patch version from alpine docker tag

---

pkg/analyzer/analyzer.go

- Added condition into analyzer's function _shouldConsiderGitIgnoreFile_ to check if gitignore is not empty.

fix(engine): added condition to check if gitignore is not empty to fix unit tests

---

docs/integrations_ghactions.md

Updated github/codeql-action/upload-sarif to v2 since v1 was deprecated
Closes #
- Updated documentation for github/codeql-action/upload-sarif from v1 to v2
- v1 was depecrated by github and if used results in a workflow error

docs(guides): changed code-ql action to v2 due to v1 depecration

---

assets/queries/dockerfile/apt_get_missing_yes_flag_to_avoid_manual_input/query.rego
assets/queries/dockerfile/changing_default_shell_using_run_command/query.rego
assets/queries/dockerfile/missing_flag_from_dnf_install/query.rego
assets/queries/dockerfile/not_using_json_in_cmd_and_entrypoint_arguments/query.rego
assets/queries/dockerfile/yum_clean_all_missing/query.rego
assets/queries/dockerfile/yum_install_allows_manual_input/query.rego

Closes #
-Update the fields informative from the queries (keyExpectedValue & keyActualValue) to not contain the "FROM {%s}" when is not necessary

fix(query): meaningful "Value" and "Expected Value" in multiple queries

---

.github/workflows/release-kics-queries-repo-branch.yaml

- Remove the "/", when trying to exclude the copying of the common queries

fix(workflow): update release-kics-queries-repo-branch.yaml

---

docker/Dockerfile.debian

- bump go version in debian dockerfile

fix(deps): update go version version in debian image

---

docs/results.md
pkg/report/model/cyclonedx.go
pkg/report/model/cyclonedx_test.go

Closes: #6827 
-update cyclonedx reports to support v.1.5 from v.1.3

feat(results): update cyclonedx reports to support v1.5

---

docs/configuration-file.md
docs/performance.md
docs/running-kics.md

- Remove all zero-width spaces from `docs/**/*.md`.
- Where the `IaC Technology` table is touched anyway, also align the `|` cell borders.
Unless those were added intentionally?

docs(guides): remove ZWSPs & align column separators

---

docs/commands.md

- add parallel flag documentation

update(docs): add documentation for parallel flag

---

.github/scripts/queries-validator/metadata-schema.json
assets/queries/terraform/tencentcloud/disk_encryption_disabled/metadata.json
assets/queries/terraform/tencentcloud/disk_encryption_disabled/query.rego
assets/queries/terraform/tencentcloud/disk_encryption_disabled/test/negative1.tf
assets/queries/terraform/tencentcloud/disk_encryption_disabled/test/positive1.tf
assets/queries/terraform/tencentcloud/disk_encryption_disabled/test/positive2.tf
assets/queries/terraform/tencentcloud/disk_encryption_disabled/test/positive_expected_result.json
test/main_test.go

- CBS Disk Without Encrypted for TencentCloud

feat(query): add cbs disk without encrypted for tencentcloud

---

docs/results.md
pkg/report/model/cyclonedx.go
pkg/report/model/cyclonedx_test.go

Closes #6926
- use version 1.5 in cycloneDX reports
- modify correspondent tests

fix(kics): support v1.5 of cyclone dx report format

---

.github/workflows/go-ci-coverage.yaml

- update artifact handling actions

fix(action): update coverage action

---

go.mod
go.sum

- github.com/docker/docker v24.0.9+incompatible

build(deps): github.com/docker/docker v24.0.9+incompatible

---

.github/workflows/release-docker-github-actions.yaml

- kics github action version 2.0 upgrade

update(workflow): kics github action version 2.0 upgrade

---

go.mod
go.sum

update(dependency): upgrade go-getter to v1.7.4

---

.github/workflows/sec-checks.yaml
.grype.yaml
docs/queries/cicd-queries/555ab8f9-2001-455e-a077-f2d0f41e2fb9.md

Updating queries' documentation.
Triggered by SHA: _ad0ab7b83d714786af52699a37db13c9e313b223_

docs(queries): update queries catalog

---

docker/Dockerfile.debian
docker/Dockerfile.ubi8
go.mod

- update go version from 1.22.2 to 1.22.3.

fix(goversion): update go version from 1.22.2 to 1.22.3

---

assets/queries/terraform/databricks/use_lts_spark_version/query.rego

Add new LTS databricks's runtime
https://docs.databricks.com/en/release-notes/runtime/index.html

chore(databricks): add new spark LTS runtime

---

assets/queries/terraform/databricks/use_lts_spark_version/query.rego

Remove deprecated LTS version
https://docs.databricks.com/en/release-notes/runtime/index.html

chore(databricks): remove deprecated spark lts version

---

docs/js/custom.js

Closes #7150
- Download in All Queries page of the docs didn't include all the relevant information
- Replace "more info" column with "query details" and "documentation" columns including the relevant URLs

fix(docs): add urls to all queries download

---

.golangci.yml
docs/CONTRIBUTING.md

Closes #7144
- change contribution guide linting method suggestion;
- remove deprecated linting methods;
- remove deprecated linting methods from golangci.yaml;
- update contribution guide with current linting method used by KICS Repo;

update(linting): update contribuition guide and remove deprecated linting methods

---

Dockerfile

- update chainguard image for libcrypto3 and libssl3 versions update;

update(chainguard): update chainguard image for libcrypto3 and libssl3 versions update

---

pkg/resolver/file/file.go

- Cyclic file path references checking process was throwing a panic when trying to resolve big projects
- Max resolver depth considered while searching for cyclic references

fix(resolver): max resolver depth considered while searching for cyclic references

---

assets/libraries/azureresourcemanager.rego

- ARM queries could give incorrect results in some cases because of a bug in an ARM-specific parameter-checking function.
- Fix parameter-checking function for ARM queries

fix(query): fix unexpected behaviour in parameter-checking function for ARM queries

---

.github/scripts/report/go.mod
.github/scripts/server-mock/package-lock.json
.github/workflows/go-ci-integration.yml
.github/workflows/go-ci.yml
.github/workflows/go-e2e-debian.yaml
.github/workflows/go-e2e.yaml
.github/workflows/release-apispec.yml
.github/workflows/release-nightly.yml
Dockerfile
README.md
docker/Dockerfile.debian
docker/Dockerfile.ubi8
docs/queries/cicd-queries/20f14e1a-a899-4e79-9f09-b6a84cd4649b.md
examples/github/kics-docker-runner-sarif.yaml
go.mod
internal/console/analyze.go
internal/console/pre_scan.go
internal/sentry/sentry.go
pkg/engine/secrets/inspector.go
pkg/parser/buildah/comments.go
pkg/parser/buildah/parser.go
pkg/printer/printer.go
pkg/remediation/remediation.go
pkg/scan/preview_secrets_mask.go
pkg/scan/utils.go
pkg/utils/random.go

- go version 1.22.5 has 3 known vulnerabilities;
- update go version from 1.22.5 to version 1.23.1;
- revert gosec version to [v2.20.0](https://github.com/securego/gosec/releases/tag/v2.20.0); 
- update dockerfile images and add git to dockerfile;
- tackle new golang-lint issues;
- for the linting job, ubuntu-20.04 is the most stable version used for runner;

update(go): update go version to 1.23.1

---

.github/scripts/report/go.mod
.github/workflows/kics-gh-action.yaml
Dockerfile
docker/Dockerfile.debian
docker/Dockerfile.ubi8
go.mod

- KICS always used root, but in the latest release, we changed it to 65532 due to FedRAMP policies. This change is causing issues in AST-CLI. Since we only use the binaries inside the image, there is no relevant reason to use 65532 instead of root. A possible fix is to run the KICS image with the same user as the container running it. However, since this would require users to change their setup, I am reverting this change to avoid that and to prevent other potential issues.
- revert KICS user change from 65532 back to root
- update KICS gh action to v2.1.4
- fix vulnerabilities

update(dockerfile): revert KICS user change from 65532 back to root

---

assets/queries/openAPI/general/array_without_maximum_number_items/query.rego

- Actual and Expected values are swapped.
- Swap Actual and Expected values on query results.

fix(query): correct keyActualValue and keyExpectedValue for maxItems validation

---

assets/queries/openAPI/general/maximum_length_undefined/query.rego
assets/queries/openAPI/general/maximum_length_undefined/test/negative10.yaml
assets/queries/openAPI/general/maximum_length_undefined/test/negative11.json
assets/queries/openAPI/general/maximum_length_undefined/test/negative12.yaml
assets/queries/openAPI/general/maximum_length_undefined/test/negative9.json

- Enum and Format (when set to 'date' or 'date-time') should be recognized as sanitizers
- OpenAPI general query maximum_length_undefined updated to consider format (date and date-time) and enum as sanitizers
- Query negative UTs added

fix(query): openapi maximum_length_undefined query enum and format sanitizers

---

Dockerfile
docs/platforms.md
go.mod
go.sum
mkdocs.yml

Closes # AST-88787
- Ansible limitation is outdated
- Copyright year is updated to 2025
- Update docs

docs(ansible): remove outdated Ansible limitation and update copyright year

---

docs/creating-queries.md
docs/integrations_terraformer.md

- The "_Creating Queries_" documentation page has 2 typos that can be seen in the image bellow: 
- Same problem on "_Running KICS with Terraformer (Deprecated after 1.7.13)_":
- Fix rego_playground image and emojis;
- Fix terraformer gif example: 

docs(typo): fix creating queries documentation page

---

assets/queries/ansible/aws/cloudwatch_without_retention_period_specified/query.rego
assets/queries/crossplane/aws/cloudwatch_without_retention_period_specified/query.rego
assets/queries/terraform/aws/cloudwatch_without_retention_period_specified/query.rego

Pulled from latest documentation @ https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group
Closes #
- Some valid CloudWatch Logs retention periods are not supported and trigger false positives
- Adds the full list of valid CloudWatch Logs retention periods

fix(queries): support all valid CloudWatch Logs retention periods

---

docs/creating-queries.md

- Other docs use docker for sample commands. This update brings the creation of the universal json inline with other sample commands.
- update command samples to be a docker command
- fix discrepancy between `./code/test` and `./src/test`

docs(queries): update universal JSON creation to docker command

---

assets/queries/dockerfile/missing_flag_from_dnf_install/query.rego
assets/queries/dockerfile/missing_flag_from_dnf_install/test/negative4.dockerfile
assets/queries/dockerfile/missing_flag_from_dnf_install/test/positive3.dockerfile
assets/queries/dockerfile/missing_flag_from_dnf_install/test/positive4.dockerfile
assets/queries/dockerfile/missing_flag_from_dnf_install/test/positive_expected_result.json

- Add support for `tdnf`.
- Include `tdnf` in the `hasYesFlag` regex.

fix(query): fix fp for missing_flag_from_dnf_install

---

docker/Dockerfile.debian

- debian e2e tests were failing due to changes on the docker image `buster-slim`;
- change Dockerfile.debian image to `stable-slim`;

fix(dockerfile): update debian dockerfile image with stable-slim version

---

Dockerfile
docker/Dockerfile.debian
docker/Dockerfile.ubi8
go.mod

- Grype is complaining of multiple vulnerabilities;
- Update go version to 1.24.5;
- Update dockerfile images to latest;

fix(vulnerabilities): update go version to fix grype vulnerabilities

---

docker/Dockerfile.ubi8

- update go version in all references to version 1.24.6;
- change ubi8 dockerfile amd go version to 1.24.6;

fix(ubi): update ubi dockerfile go version to 1.24.6

---

go.mod
go.sum

- update go-getter to version 1.7.9;

fix(vuln): update go-getter to fix vulnerability

---

assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/negative3.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/negative4.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/negative5.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/negative6.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/positive1.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/positive10.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/positive11.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/positive12.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/positive2.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/positive3.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/positive4.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/positive5.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/positive6.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/positive7.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/positive8.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/positive9.tf
assets/queries/terraform/aws/s3_bucket_notifications_disabled/test/positive_expected_result.json

- The newly added query "[s3_bucket_notifications_disabled](https://github.com/Checkmarx/kics/commit/b765991383055a2ee7f3f441b791b5d04ead89f4)" was taking into account instances of ```aws_sns_topic``` ,```aws_sqs_queue``` or ```aws_lambda_function```  as arrays but there were no tests to show this behaviour. 
- Moreover the [positive4](https://github.com/Checkmarx/kics/commit/b765991383055a2ee7f3f441b791b5d04ead89f4#diff-7bae4933fa51606139482970b0646854f76f80613421b2019f988bdb10ac08df) test could be applied to the other fields besides just "aws_sns_topic"
- Added 3 new negative tests to show that arrays of the relevant resources are supported. (multiple of the same resource inside the …

test(query): missing tests for  s3_bucket_notifications_disabled

---

assets/queries/cloudFormation/aws/instance_uses_metadata_service_IMDSv1/test/negative5.yaml

Closes #
- The file negative5.yaml for the query "Instance Uses Metadata Service IMDSv1" has an incorrect indentation
- Fixed indentation

fix(test): fixed indentation on a test case for instance uses metadata service imdsv1 query for CloudFormation platform 

---

assets/queries/terraform/aws/unknown_port_exposed_to_internet/test/positive4.tf

- The positive4 test of the "Unknown Port Exposed To Internet" query had a "ipv6_cidr_blocks" field set to ["::/0"] inside an "ingress_with_cidr_blocks" of the "terraform-aws-modules/security-group/aws" module. 
- This was untended since the supported value is actually "cidr_blocks", the ipv4 version of the field. The mistake is not present in the near identical negative4 sample.
- Fixed the field naming and value.

test(query): fix for positive4 test to "Unknown Port Exposed To Internet" query
