Checkmarx/kics

- pkg/kics/service.go
> fixes bad json parsing #547

- assets/queries/terraform/aws/memcached_disabled/metadata.json
- assets/queries/terraform/aws/memcached_disabled/query.rego
- assets/queries/terraform/aws/memcached_disabled/test/negative.tf
- assets/queries/terraform/aws/memcached_disabled/test/positive.tf
- assets/queries/terraform/aws/memcached_disabled/test/positive_expected_result.json
Closes #470 
Checks if the MemCached is enabled in the ElastiCache
> Add memcached_disabled query Closes #470

- assets/queries/terraform/aws/sql_analysis_services_port_2383_is_publicly_accessible/metadata.json
- assets/queries/terraform/aws/sql_analysis_services_port_2383_is_publicly_accessible/query.rego
- assets/queries/terraform/aws/sql_analysis_services_port_2383_is_publicly_accessible/test/negative.tf
- assets/queries/terraform/aws/sql_analysis_services_port_2383_is_publicly_accessible/test/positive.tf
- assets/queries/terraform/aws/sql_analysis_services_port_2383_is_publicly_accessible/test/positive_expected_result.json
> Added query SQL Analysis service port 2383 #319

- assets/queries/terraform/aws/sqs_queue_exposed/metadata.json
- assets/queries/terraform/aws/sqs_queue_exposed/query.rego
- assets/queries/terraform/aws/sqs_queue_exposed/test/negative.tf
- assets/queries/terraform/aws/sqs_queue_exposed/test/positive.tf
- assets/queries/terraform/aws/sqs_queue_exposed/test/positive_expected_result.json
Closes #434  
Check if the queue is publicly accessible
> Add sqs_queue_exposed query Closes #434

- assets/queries/terraform/azure/log_duration_is_not_set/metadata.json
- assets/queries/terraform/azure/log_duration_is_not_set/query.rego
- assets/queries/terraform/azure/log_duration_is_not_set/test/negative.tf
- assets/queries/terraform/azure/log_duration_is_not_set/test/positive.tf
- assets/queries/terraform/azure/log_duration_is_not_set/test/positive_expected_result.json
Closes #578 
Check if the 'log_duration' is set to 'on'
> Add log_duration_is_not_set query Closes #578

- assets/queries/terraform/aws/ecs_task_definition_has_password/metadata.json
- assets/queries/terraform/aws/ecs_task_definition_has_password/query.rego
- assets/queries/terraform/aws/ecs_task_definition_has_password/test/negative.tf
- assets/queries/terraform/aws/ecs_task_definition_has_password/test/positive.tf
- assets/queries/terraform/aws/ecs_task_definition_has_password/test/positive_expected_result.json
> add query ecs_task_definition_has_password #308

- assets/queries/terraform/aws/https_traffic_disabled/metadata.json
- assets/queries/terraform/aws/https_traffic_disabled/query.rego
- assets/queries/terraform/aws/https_traffic_disabled/test/negative.tf
- assets/queries/terraform/aws/https_traffic_disabled/test/positive.tf
- assets/queries/terraform/aws/https_traffic_disabled/test/positive_expected_result.json
Closes #458 
Check if the CloudFront and origin server connection is encrypted
> Add https_traffic_disabled query Closes #458

- assets/queries/terraform/aws/base64_private_key_is_encoded/metadata.json
- assets/queries/terraform/aws/base64_private_key_is_encoded/query.rego
- assets/queries/terraform/aws/base64_private_key_is_encoded/test/negative.tf
- assets/queries/terraform/aws/base64_private_key_is_encoded/test/positive.tf
- assets/queries/terraform/aws/base64_private_key_is_encoded/test/positive_expected_result.json
Base64 Private Key must be encoded
Closes #339
> Added Base64 Private Key Is Encoded query #339

- assets/queries/k8s/allowed_capabilities/metadata.json
- assets/queries/k8s/allowed_capabilities/query.rego
- assets/queries/k8s/allowed_capabilities/test/negative.yaml
- assets/queries/k8s/allowed_capabilities/test/positive.yaml
- assets/queries/k8s/allowed_capabilities/test/positive_expected_result.json
For this query, it is necessary to check if the attribute 'add' of the attribute 'capabilities' is set
Closes #625
> Add allowed_capabilities Closes #625

- assets/queries/k8s/limit_capabilities_of_the_psp/query.rego
Kind should be PodSecurityPolicy
Closes #479
> Checks if kind is PSP #479

- assets/queries/terraform/aws/http_port_open/metadata.json
- assets/queries/terraform/aws/http_port_open/query.rego
- assets/queries/terraform/aws/http_port_open/test/negative.tf
- assets/queries/terraform/aws/http_port_open/test/positive.tf
- assets/queries/terraform/aws/http_port_open/test/positive_expected_result.json
Closes #238
Check if the HTTP port is open to the internet
> Add http_port_open query Closes #238

- assets/queries/k8s/tiller_service_not_deleted/metadata.json
- assets/queries/k8s/tiller_service_not_deleted/query.rego
- assets/queries/k8s/tiller_service_not_deleted/test/negative.yaml
- assets/queries/k8s/tiller_service_not_deleted/test/positive.yaml
- assets/queries/k8s/tiller_service_not_deleted/test/positive_expected_result.json
Check if any Teller service remains undeleted. Closes #428
> Add query to check if teller service has not been deleted. Closes #428

- assets/queries/k8s/tiller_deployment_is_accessible_within_cluster/metadata.json
- assets/queries/k8s/tiller_deployment_is_accessible_within_cluster/query.rego
- assets/queries/k8s/tiller_deployment_is_accessible_within_cluster/test/negative.yaml
- assets/queries/k8s/tiller_deployment_is_accessible_within_cluster/test/positive.yaml
- assets/queries/k8s/tiller_deployment_is_accessible_within_cluster/test/positive_expected_result.json
Check if any Tiller Deployment resource has containers not listening to localhost. Closes #430
> Add query to check if tiller containers are accessible. Closes #430

- assets/queries/k8s/default_namespace/metadata.json
- assets/queries/k8s/default_namespace/query.rego
- assets/queries/k8s/default_namespace/test/negative.yaml
- assets/queries/k8s/default_namespace/test/positive.yaml
- assets/queries/k8s/default_namespace/test/positive_expected_result.json
To ensure the default namespace is not used, I thought in two cases:
- Namespace is not set
- Default namespace is used
Closes #502
> Add default_namespace query Closes #502

- assets/queries/k8s/tiller_is_deployed/metadata.json
- assets/queries/k8s/tiller_is_deployed/query.rego
- assets/queries/k8s/tiller_is_deployed/test/negative.yaml
- assets/queries/k8s/tiller_is_deployed/test/positive.yaml
- assets/queries/k8s/tiller_is_deployed/test/positive_expected_result.json
Check if any resource deploys Tiller. Closes #431
> Add query to check if Tiller is deployed. Closes #431

- assets/queries/k8s/shared_service_account/metadata.json
- assets/queries/k8s/shared_service_account/query.rego
- assets/queries/k8s/shared_service_account/test/negative.yaml
- assets/queries/k8s/shared_service_account/test/positive.yaml
- assets/queries/k8s/shared_service_account/test/positive_expected_result.json
Closes #644 
Checks if a Service Account token is shared between workloads
> Add shared_service_account query for Kubernetes #644

- assets/queries/cloudFormation/ecs_service_admin_role_present/metadata.json
- assets/queries/cloudFormation/ecs_service_admin_role_present/query.rego
- assets/queries/cloudFormation/ecs_service_admin_role_present/test/negative.yaml
- assets/queries/cloudFormation/ecs_service_admin_role_present/test/positive.yaml
- assets/queries/cloudFormation/ecs_service_admin_role_present/test/positive_expected_result.json
Adding ECS Service Admin Role Present query for AWS CloudFormation, that checks if the attribute 'role' is an admin role.
Closes #656
> Add ECS Service Admin Role Present query for AWS CloudFormation

- assets/queries/k8s/statefulset_requests_storage/metadata.json
- assets/queries/k8s/statefulset_requests_storage/query.rego
- assets/queries/k8s/statefulset_requests_storage/test/negative.yaml
- assets/queries/k8s/statefulset_requests_storage/test/positive.yaml
- assets/queries/k8s/statefulset_requests_storage/test/positive_expected_result.json
- assets/queries/k8s/tiller_service_not_deleted/query.rego
Implemented query statefulset_requests_storage.
The query finds StatefulSet definitions that request specific storage.
Closes #697
> Implemented query statefulset_requests_storage #697

- assets/queries/k8s/allowed_capabilities/query.rego
- assets/queries/k8s/allowed_capabilities/test/positive.yaml
- assets/queries/k8s/allowed_capabilities/test/positive_expected_result.json
- assets/queries/k8s/block_privileged_container/query.rego
- assets/queries/k8s/block_privileged_container/test/positive.yaml
- assets/queries/k8s/block_privileged_container/test/positive_expected_result.json
- assets/queries/k8s/resource_with_allow_privilege_escalation/query.rego
- assets/queries/k8s/resource_with_allow_privilege_escalation/test/positive.yaml
- assets/queries/k8s/resource_with_allow_privilege_escalation/test/positive_expected_result.json
Added initContainers to the queries where it should be checked.
Closes #678
> Added initContainers property checking to needed queries

- assets/queries/k8s/allowed_capabilities_sys_admin/metadata.json
- assets/queries/k8s/allowed_capabilities_sys_admin/query.rego
- assets/queries/k8s/allowed_capabilities_sys_admin/test/negative.yaml
- assets/queries/k8s/allowed_capabilities_sys_admin/test/positive.yaml
- assets/queries/k8s/allowed_capabilities_sys_admin/test/positive_expected_result.json
- go.mod
For this query, it is necessary to check if SYS_ADMIN is a capability added.
Closes #516
> Add allowed_capabilities_sys_admin Closes #516

- assets/queries/k8s/resource_with_allow_privilege_escalation/image_defined/metadata.json
- assets/queries/k8s/resource_with_allow_privilege_escalation/image_defined/query.rego
- assets/queries/k8s/resource_with_allow_privilege_escalation/image_defined/test/negative.yaml
- assets/queries/k8s/resource_with_allow_privilege_escalation/image_defined/test/positive.yaml
- assets/queries/k8s/resource_with_allow_privilege_escalation/image_defined/test/positive_expected_result.json
Image must be defined and not be empty or equal to latest.
Closes #555
> Added Image Must Be Defined query #555

- docs/roadmap.md
Milestones for 2020 - updated till M3
> Milestones for 2020

- docs/roadmap.md
Changing the format and adding long term roadmap
> Making the roadmap awesome

- assets/queries/k8s/default_service_account_binding/metadata.json
- assets/queries/k8s/default_service_account_binding/query.rego
- assets/queries/k8s/default_service_account_binding/test/negative.yaml
- assets/queries/k8s/default_service_account_binding/test/positive.yaml
- assets/queries/k8s/default_service_account_binding/test/positive_expected_result.json
The default namespace should not be used #626
> Add Kubernetes Service Account Binding is Default query for Terraform #626

- assets/queries/k8s/kubernetes_docker_socket_volume/metadata.json
- assets/queries/k8s/kubernetes_docker_socket_volume/query.rego
- assets/queries/k8s/kubernetes_docker_socket_volume/test/negative.yaml
- assets/queries/k8s/kubernetes_docker_socket_volume/test/positive.yaml
- assets/queries/k8s/kubernetes_docker_socket_volume/test/positive_expected_result.json
Sees if Docker Daemon Socket is not exposed to Containers #592
> Add Docker Daemon Socket is Exposed to Containers query for Kubernetes #592

- assets/queries/k8s/cpu_requests/metadata.json
- assets/queries/k8s/cpu_requests/query.rego
- assets/queries/k8s/cpu_requests/test/negative.yaml
- assets/queries/k8s/cpu_requests/test/positive.yaml
- assets/queries/k8s/cpu_requests/test/positive_expected_result.json
Since attribute 'containers' is an array, it is necessary to check if all containers have CPU requests.
Closes #487
> Add cpu_requests query Closes #487

- assets/queries/k8s/kubernetes_image_digest/metadata.json
- assets/queries/k8s/kubernetes_image_digest/query.rego
- assets/queries/k8s/kubernetes_image_digest/test/negative.yaml
- assets/queries/k8s/kubernetes_image_digest/test/positive.yaml
- assets/queries/k8s/kubernetes_image_digest/test/positive_expected_result.json
- go.mod
Sees if Kubernetes image has digest on #572.
> Add Kubernetes Image should use digest query for Kubernetes #572

- assets/queries/k8s/kubernetes_host_ports/metadata.json
- assets/queries/k8s/kubernetes_host_ports/query.rego
- assets/queries/k8s/kubernetes_host_ports/test/negative.yaml
- assets/queries/k8s/kubernetes_host_ports/test/positive.yaml
- assets/queries/k8s/kubernetes_host_ports/test/positive_expected_result.json
Add Kubernetes Image Host Port is Specified query for Kubernetes #585
> Add Kubernetes Image Host Port is Specified query for Kubernetes #585

- assets/queries/k8s/apiversion_is_deprecated/metadata.json
- assets/queries/k8s/apiversion_is_deprecated/query.rego
- assets/queries/k8s/apiversion_is_deprecated/test/negative.yaml
- assets/queries/k8s/apiversion_is_deprecated/test/positive.yaml
- assets/queries/k8s/apiversion_is_deprecated/test/positive_expected_result.json
Check if some objects are using a deprecated API version. Closes #601
> Add query to check if API version is deprecated. Closes #601

- assets/queries/k8s/network_policy_not_targeting_pods/metadata.json
- assets/queries/k8s/network_policy_not_targeting_pods/query.rego
- assets/queries/k8s/network_policy_not_targeting_pods/test/negative.yaml
- assets/queries/k8s/network_policy_not_targeting_pods/test/positive.yaml
- assets/queries/k8s/network_policy_not_targeting_pods/test/positive_expected_result.json
Check if there is any network policy that does not target a pod. Closes #605
> Add query to check if any network policy is not targeting a pod. Closes #605

- assets/queries/k8s/deployment_no_podAntiAffinity/metadata.json
- assets/queries/k8s/deployment_no_podAntiAffinity/query.rego
- assets/queries/k8s/deployment_no_podAntiAffinity/test/negative.yaml
- assets/queries/k8s/deployment_no_podAntiAffinity/test/positive.yaml
- assets/queries/k8s/deployment_no_podAntiAffinity/test/positive_expected_result.json
Check if Deployment resources are not setting a podantiaffinity policy. Closes #610
> Add query to check if deployment has anti affinity nodes. closes #610

- assets/queries/k8s/statefulSet_no_podAntiAffinity/metadata.json
- assets/queries/k8s/statefulSet_no_podAntiAffinity/query.rego
- assets/queries/k8s/statefulSet_no_podAntiAffinity/test/negative.yaml
- assets/queries/k8s/statefulSet_no_podAntiAffinity/test/positive.yaml
- assets/queries/k8s/statefulSet_no_podAntiAffinity/test/positive_expected_result.json
Check if any StatefulSet resource is not setting podAntiAffinity policies. Closes #611
> Add query to check if statefulSet has anti affinity nodes. closes #611

- assets/queries/k8s/service_with_external_load_balance/metadata.json
- assets/queries/k8s/service_with_external_load_balance/query.rego
- assets/queries/k8s/service_with_external_load_balance/test/negative.yaml
- assets/queries/k8s/service_with_external_load_balance/test/positive.yaml
- assets/queries/k8s/service_with_external_load_balance/test/positive_expected_result.json
Added new query for Kubernetes.
Provide a Kubernetes resource and a resource to ensure that workload is not exposed
Closes #660
> Add Service With External Load Balance query

- assets/queries/k8s/net_raw_capabilities_disabled_minimized/metadata.json
- assets/queries/k8s/net_raw_capabilities_disabled_minimized/query.rego
- assets/queries/k8s/net_raw_capabilities_disabled_minimized/test/negative.yaml
- assets/queries/k8s/net_raw_capabilities_disabled_minimized/test/positive.yaml
- assets/queries/k8s/net_raw_capabilities_disabled_minimized/test/positive_expected_result.json
Containers need to have NET_RAW or All as Security Context #794
> Add NET_RAW Capabilities Disabled Minimized query for Kubernetes #794

- assets/queries/cloudFormation/security_groups_with_exhibited_admin_ports/metadata.json
- assets/queries/cloudFormation/security_groups_with_exhibited_admin_ports/query.rego
- assets/queries/cloudFormation/security_groups_with_exhibited_admin_ports/test/negative.yaml
- assets/queries/cloudFormation/security_groups_with_exhibited_admin_ports/test/positive.yaml
- assets/queries/cloudFormation/security_groups_with_exhibited_admin_ports/test/positive_expected_result.json
Security Groups should not have port in (20, 21, 22, 23, 115, 137, 138, 139, 2049, 3389)
Closes #684
> Added Sec Groups W/Exhibited Ports query #684

- assets/queries/cloudFormation/iam_policy_assumerole_permission_all_services/metadata.json
- assets/queries/cloudFormation/iam_policy_assumerole_permission_all_services/query.rego
- assets/queries/cloudFormation/iam_policy_assumerole_permission_all_services/test/negative.yaml
- assets/queries/cloudFormation/iam_policy_assumerole_permission_all_services/test/positive.yaml
- assets/queries/cloudFormation/iam_policy_assumerole_permission_all_services/test/positive_expected_result.json
Check if IAM Policy has AssumeRole action grant accessing in all services. Closes #753
> Add query to check if IAM Policy AssumeRole Permissions. Closes #753

- assets/queries/cloudFormation/encrypted_connection_between_cloudfront_origin/metadata.json
- assets/queries/cloudFormation/encrypted_connection_between_cloudfront_origin/query.rego
- assets/queries/cloudFormation/encrypted_connection_between_cloudfront_origin/test/negative.yaml
- assets/queries/cloudFormation/encrypted_connection_between_cloudfront_origin/test/positive.yaml
- assets/queries/cloudFormation/encrypted_connection_between_cloudfront_origin/test/positive_expected_result.json
- assets/queries/terraform/aws/https_traffic_disabled/test/positive.tf
Closes #710 
Checks if the connection between the CloudFront and the origin server is encrypted
> Add encrypted_connection_between_cloudfront_origin query Closes #710 and tf redone

- assets/queries/cloudFormation/s3_bucket_without_ssl_enforcement/metadata.json
- assets/queries/cloudFormation/s3_bucket_without_ssl_enforcement/query.rego
- assets/queries/cloudFormation/s3_bucket_without_ssl_enforcement/test/negative.yaml
- assets/queries/cloudFormation/s3_bucket_without_ssl_enforcement/test/positive.yaml
- assets/queries/cloudFormation/s3_bucket_without_ssl_enforcement/test/positive_expected_result.json
- pkg/engine/vulnerability_builder.go
Implemented S3 Bucket Without SSL Enforcement query
Closes #773
> Implemented S3 Bucket Without SSL Enforcement query #773

- assets/queries/cloudFormation/s3_bucket_without_server_side_encryption/metadata.json
- assets/queries/cloudFormation/s3_bucket_without_server_side_encryption/query.rego
- assets/queries/cloudFormation/s3_bucket_without_server_side_encryption/test/negative.yaml
- assets/queries/cloudFormation/s3_bucket_without_server_side_encryption/test/positive.yaml
- assets/queries/cloudFormation/s3_bucket_without_server_side_encryption/test/positive_expected_result.json
Implemented query S3 Bucket Without Server Side Encryption
Closes #780
> Implemented query S3 Bucket Without Server Side Encryption #780

- assets/queries/dockerfile/run_using_sudo/metadata.json
- assets/queries/dockerfile/run_using_sudo/query.rego
- assets/queries/dockerfile/run_using_sudo/test/negative.dockerfile
- assets/queries/dockerfile/run_using_sudo/test/positive.dockerfile
- assets/queries/dockerfile/run_using_sudo/test/positive_expected_result.json
> Add Run Using Sudo #857

- assets/queries/cloudFormation/iam_user_has_policies/metadata.json
- assets/queries/cloudFormation/iam_user_has_policies/query.rego
- assets/queries/cloudFormation/iam_user_has_policies/test/negative.yaml
- assets/queries/cloudFormation/iam_user_has_policies/test/positive.yaml
- assets/queries/cloudFormation/iam_user_has_policies/test/positive_expected_result.json
Check if an IAM User has policies associated with when they should be addressing groups or roles. Closes #813
> Add query to check if iam user has policies associated. Closes #813

- assets/queries/cloudFormation/security_groups_for_rdp/metadata.json
- assets/queries/cloudFormation/security_groups_for_rdp/query.rego
- assets/queries/cloudFormation/security_groups_for_rdp/test/negative.yaml
- assets/queries/cloudFormation/security_groups_for_rdp/test/positive.yaml
- assets/queries/cloudFormation/security_groups_for_rdp/test/positive_expected_result.json
Security Groups does not allow 0.0.0.0/0 for rdp (port:3389)
Closes #695
> Sec Groups does not allow 0.0.0.0/0 for rdp #695 

- assets/queries/terraform/aws/iam_user_policy_virtual_mfa/metadata.json
- assets/queries/terraform/aws/iam_user_policy_virtual_mfa/query.rego
- assets/queries/terraform/aws/iam_user_policy_virtual_mfa/test/negative.tf
- assets/queries/terraform/aws/iam_user_policy_virtual_mfa/test/positive.tf
- assets/queries/terraform/aws/iam_user_policy_virtual_mfa/test/positive_expected_result.json
> add query IAM User Policy Virtual MFA #268

- assets/queries/cloudFormation/s3_bucket_without_ssl_in_write_actions/metadata.json
- assets/queries/cloudFormation/s3_bucket_without_ssl_in_write_actions/query.rego
- assets/queries/cloudFormation/s3_bucket_without_ssl_in_write_actions/test/negative.yaml
- assets/queries/cloudFormation/s3_bucket_without_ssl_in_write_actions/test/positive.yaml
- assets/queries/cloudFormation/s3_bucket_without_ssl_in_write_actions/test/positive_expected_result.json
- pkg/engine/vulnerability_builder.go
Implemented S3 Bucket Without SSL In Write Actions query
Closes #782
> Implemented S3 Bucket Without SSL In Write Actions query #782

- assets/queries/dockerfile/workdir_path_not_absolute/metadata.json
- assets/queries/dockerfile/workdir_path_not_absolute/query.rego
- assets/queries/dockerfile/workdir_path_not_absolute/test/negative.dockerfile
- assets/queries/dockerfile/workdir_path_not_absolute/test/positive.dockerfile
- assets/queries/dockerfile/workdir_path_not_absolute/test/positive_expected_result.json
> WORKDIR Path Not Absolute #815

- assets/queries/cloudFormation/iam_policy_on_user/metadata.json
- assets/queries/cloudFormation/iam_policy_on_user/query.rego
- assets/queries/cloudFormation/iam_policy_on_user/test/negative.yaml
- assets/queries/cloudFormation/iam_policy_on_user/test/positive.yaml
- assets/queries/cloudFormation/iam_policy_on_user/test/positive_expected_result.json
Implemented IAM Policy On User query 
Closes #817
> Implemented IAM Policy On User query #817

- assets/queries/cloudFormation/security_groups_for_ssh/metadata.json
- assets/queries/cloudFormation/security_groups_for_ssh/query.rego
- assets/queries/cloudFormation/security_groups_for_ssh/test/negative.yaml
- assets/queries/cloudFormation/security_groups_for_ssh/test/positive.yaml
- assets/queries/cloudFormation/security_groups_for_ssh/test/positive_expected_result.json
Security Groups does not allow 0.0.0.0/0 for ssh (port:22)
Closes #692
> Sec Groups does not allow 0.0.0.0/0 for ssh #692

- assets/queries/dockerfile/image_version_not_explicit/metadata.json
- assets/queries/dockerfile/image_version_not_explicit/query.rego
- assets/queries/dockerfile/image_version_not_explicit/test/negative.dockerfile
- assets/queries/dockerfile/image_version_not_explicit/test/positive.dockerfile
- assets/queries/dockerfile/image_version_not_explicit/test/positive_expected_result.json
> Add Image Version Not Explicit #860

- assets/queries/cloudFormation/s3_bucket_website_host_is_disabled/metadata.json
- assets/queries/cloudFormation/s3_bucket_website_host_is_disabled/query.rego
- assets/queries/cloudFormation/s3_bucket_website_host_is_disabled/test/negative.yaml
- assets/queries/cloudFormation/s3_bucket_website_host_is_disabled/test/positive.yaml
- assets/queries/cloudFormation/s3_bucket_website_host_is_disabled/test/positive_expected_result.json
Provide a CloudFormation resource and a resource to ensure that S3 Bucket Website Host Is Disabled
Closes #802
> Add S3 Bucket Website Host Is Disabled query

- assets/queries/cloudFormation/rds_backup_retention_period_insufficient/metadata.json
- assets/queries/cloudFormation/rds_backup_retention_period_insufficient/query.rego
- assets/queries/cloudFormation/rds_backup_retention_period_insufficient/test/negative.yaml
- assets/queries/cloudFormation/rds_backup_retention_period_insufficient/test/positive.yaml
- assets/queries/cloudFormation/rds_backup_retention_period_insufficient/test/positive_expected_result.json
Platform
_CloudFront_
Description
_AWS RDS backup retention policy should be at least 7 days_
Closes #871
> Add 'RDS Backup Retention Period Insufficient' query for CloudFormation

- assets/queries/cloudFormation/efs_without_tags/metadata.json
- assets/queries/cloudFormation/efs_without_tags/query.rego
- assets/queries/cloudFormation/efs_without_tags/test/negative.yaml
- assets/queries/cloudFormation/efs_without_tags/test/positive.yaml
- assets/queries/cloudFormation/efs_without_tags/test/positive_expected_result.json
Platform
_CloudFormation_
Description
_AWS Elastic Filesystem resources should have associated file system tags_
Closes #867
> Add efs_without_tags query for CloudFormation

- assets/queries/dockerfile/maintainer_instruction_being_used/metadata.json
- assets/queries/dockerfile/maintainer_instruction_being_used/query.rego
- assets/queries/dockerfile/maintainer_instruction_being_used/test/negative.dockerfile
- assets/queries/dockerfile/maintainer_instruction_being_used/test/positive.dockerfile
- assets/queries/dockerfile/maintainer_instruction_being_used/test/positive_expected_result.json
> add MAINTAINER Instruction Being Used #825

- assets/queries/dockerfile/secrets_stored_in_dockerfile/metadata.json
- assets/queries/dockerfile/secrets_stored_in_dockerfile/query.rego
- assets/queries/dockerfile/secrets_stored_in_dockerfile/test/negative.dockerfile
- assets/queries/dockerfile/secrets_stored_in_dockerfile/test/positive.dockerfile
- assets/queries/dockerfile/secrets_stored_in_dockerfile/test/positive_expected_result.json
- test/main_test.go
> add query Secrets Stored In Dockerfile #529

- assets/queries/cloudFormation/sns_topic_should_specify_kmsMasterKeyId/metadata.json
- assets/queries/cloudFormation/sns_topic_should_specify_kmsMasterKeyId/query.rego
- assets/queries/cloudFormation/sns_topic_should_specify_kmsMasterKeyId/test/negative.yaml
- assets/queries/cloudFormation/sns_topic_should_specify_kmsMasterKeyId/test/positive.yaml
- assets/queries/cloudFormation/sns_topic_should_specify_kmsMasterKeyId/test/positive_expected_result.json
KmsMasterKeyId attribute should not be undefined #865
> Add Sns Topic Should Specify KmsMasterKeyId Attribute query for CloudFormation #865

- assets/queries/k8s/service_type_is_nodeport/metadata.json
- assets/queries/k8s/service_type_is_nodeport/query.rego
- assets/queries/k8s/service_type_is_nodeport/test/negative.yaml
- assets/queries/k8s/service_type_is_nodeport/test/positive.yaml
- assets/queries/k8s/service_type_is_nodeport/test/positive_expected_result.json
Service type should not be NodePort #830
> Add Service Type is NodePort query for Kubernetes #830

- assets/queries/k8s/k8s_dashboard_integration/metadata.json
- assets/queries/k8s/k8s_dashboard_integration/query.rego
- assets/queries/k8s/k8s_dashboard_integration/test/negative.yaml
- assets/queries/k8s/k8s_dashboard_integration/test/positive.yaml
- assets/queries/k8s/k8s_dashboard_integration/test/positive_expected_result.json
It's important not to allow the implementation of the k8s dashboard.
Closes #641
> Added K8s Dashboard Integration query #641

- assets/queries/cloudFormation/geo_restriction_disable/metadata.json
- assets/queries/cloudFormation/geo_restriction_disable/query.rego
- assets/queries/cloudFormation/geo_restriction_disable/test/negative.yaml
- assets/queries/cloudFormation/geo_restriction_disable/test/positive.yaml
- assets/queries/cloudFormation/geo_restriction_disable/test/positive_expected_result.json
> Added new query for AWS to check geo restriction config

- assets/queries/cloudFormation/Validate_ACM_Certitificate_DomainName/metadata.json
- assets/queries/cloudFormation/Validate_ACM_Certitificate_DomainName/query.rego
- assets/queries/cloudFormation/Validate_ACM_Certitificate_DomainName/test/negative.yaml
- assets/queries/cloudFormation/Validate_ACM_Certitificate_DomainName/test/positive.yaml
- assets/queries/cloudFormation/Validate_ACM_Certitificate_DomainName/test/positive_expected_result.json
> Added new query Validate_ACM_Certitificate_DomainName

- docs/roadmap.md
Update roadmap.md - metadata for queries
> Update roadmap.md - metadata for queries

- assets/queries/cloudFormation/s3_bucket_versioning_not_enabled/metadata.json
- assets/queries/cloudFormation/s3_bucket_versioning_not_enabled/query.rego
- assets/queries/cloudFormation/s3_bucket_versioning_not_enabled/test/negative.yaml
- assets/queries/cloudFormation/s3_bucket_versioning_not_enabled/test/positive.yaml
- assets/queries/cloudFormation/s3_bucket_versioning_not_enabled/test/positive_expected_result.json
Added new query for CloudFormation.
Provide a CloudFormation resource and a resource to ensure that Versioning is Enabled
Closes #706
> Add S3 Bucket Versioning Not Enabled query

- assets/queries/cloudFormation/rds_not_encrypted/metadata.json
- assets/queries/cloudFormation/rds_not_encrypted/query.rego
- assets/queries/cloudFormation/rds_not_encrypted/test/negative.yaml
- assets/queries/cloudFormation/rds_not_encrypted/test/positive.yaml
- assets/queries/cloudFormation/rds_not_encrypted/test/positive_expected_result.json
For this query, it necessary to check if the attribute 'StorageEncrypted' not exists in 'Properties' or if exists in 'Properties' and is set to false.
Closes #841
> Add rds_not_encrypted query Closes #841

- assets/queries/cloudFormation/route53_without_record_set/metadata.json
- assets/queries/cloudFormation/route53_without_record_set/query.rego
- assets/queries/cloudFormation/route53_without_record_set/test/negative.yaml
- assets/queries/cloudFormation/route53_without_record_set/test/positive.yaml
- assets/queries/cloudFormation/route53_without_record_set/test/positive_expected_result.json
Route53 HostedZone must have the Record Set defined.
Closes #879
> Add Route53 Without Record Set query #879

- assets/queries/cloudFormation/ec2_subnet_mapPublicIpOnLaunch_is_true/metadata.json
- assets/queries/cloudFormation/ec2_subnet_mapPublicIpOnLaunch_is_true/query.rego
- assets/queries/cloudFormation/ec2_subnet_mapPublicIpOnLaunch_is_true/test/negative.yaml
- assets/queries/cloudFormation/ec2_subnet_mapPublicIpOnLaunch_is_true/test/positive.yaml
- assets/queries/cloudFormation/ec2_subnet_mapPublicIpOnLaunch_is_true/test/positive_expected_result.json
Provide a CloudFormation resource and a resource to ensure that EC2 Subnet MapPublicIpOnLaunch feature is false
Closes #852
> Add EC2 Subnet MapPublicIpOnLaunch Is True query

- assets/queries/cloudFormation/sage_maker_enabling_internet_access/metadata.json
- assets/queries/cloudFormation/sage_maker_enabling_internet_access/query.rego
- assets/queries/cloudFormation/sage_maker_enabling_internet_access/test/negative.yaml
- assets/queries/cloudFormation/sage_maker_enabling_internet_access/test/positive.yaml
- assets/queries/cloudFormation/sage_maker_enabling_internet_access/test/positive_expected_result.json
SageMaker must have disabled internet access and root access for Creating Notebook Instances.
Closes #823
> Add SageMaker Enabling Internet Access query #823

- assets/queries/k8s/container_runs_unmasked/metadata.json
- assets/queries/k8s/container_runs_unmasked/query.rego
- assets/queries/k8s/container_runs_unmasked/test/negative.yaml
- assets/queries/k8s/container_runs_unmasked/test/positive.yaml
- assets/queries/k8s/container_runs_unmasked/test/positive_expected_result.json
This query checks if a container is running unmasked by evaluating if the string "Unmasked" is explicit in the allowedProcMountTypes list. Closes #640
> Add container_runs_unmasked query for Kubernetes

- docs/img/logo/logo.md
> Logo folder + placeholder

- assets/queries/cloudFormation/ecs_attached_inline_policies/metadata.json
- assets/queries/cloudFormation/ecs_attached_inline_policies/query.rego
- assets/queries/cloudFormation/ecs_attached_inline_policies/test/negative.yaml
- assets/queries/cloudFormation/ecs_attached_inline_policies/test/positive.yaml
- assets/queries/cloudFormation/ecs_attached_inline_policies/test/positive_expected_result.json
Check if any ECS service is using embedded inline policies instead of managed ones. Closes #694
> Add query to check if ECS serviced are using inline policies. Closes #694

- assets/queries/cloudFormation/elb_v2_alb_access_log_disabled/metadata.json
- assets/queries/cloudFormation/elb_v2_alb_access_log_disabled/query.rego
- assets/queries/cloudFormation/elb_v2_alb_access_log_disabled/test/negative.yaml
- assets/queries/cloudFormation/elb_v2_alb_access_log_disabled/test/positive.yaml
- assets/queries/cloudFormation/elb_v2_alb_access_log_disabled/test/positive_expected_result.json
> add ALB Access Log Disabled #759

- assets/queries/cloudFormation/elb_access_log_disabled/metadata.json
- assets/queries/cloudFormation/elb_access_log_disabled/query.rego
- assets/queries/cloudFormation/elb_access_log_disabled/test/negative.yaml
- assets/queries/cloudFormation/elb_access_log_disabled/test/positive.yaml
- assets/queries/cloudFormation/elb_access_log_disabled/test/positive_expected_result.json
> add ELB Access Log Disabled #763

- assets/queries/cloudFormation/api_gateway_method_does_not_contains_an_api_key_or_empty_methods/metadata.json
- assets/queries/cloudFormation/api_gateway_method_does_not_contains_an_api_key_or_empty_methods/query.rego
- assets/queries/cloudFormation/api_gateway_method_does_not_contains_an_api_key_or_empty_methods/test/negative.yaml
- assets/queries/cloudFormation/api_gateway_method_does_not_contains_an_api_key_or_empty_methods/test/positive.yaml
- assets/queries/cloudFormation/api_gateway_method_does_not_contains_an_api_key_or_empty_methods/test/positive_expected_result.json
API Gateway Method should have an API key or empty methods.
Closes #1111
> Add API Gat N/Conta API Or Empty Meths query #1111

- assets/queries/cloudFormation/AWS_RDS_configuration_automatic_backup_disabled/metadata.json
- assets/queries/cloudFormation/AWS_RDS_configuration_automatic_backup_disabled/query.rego
- assets/queries/cloudFormation/AWS_RDS_configuration_automatic_backup_disabled/test/negative.yaml
- assets/queries/cloudFormation/AWS_RDS_configuration_automatic_backup_disabled/test/positive.yaml
- assets/queries/cloudFormation/AWS_RDS_configuration_automatic_backup_disabled/test/positive_expected_result.json
> Added query AWS RDS Config Automatic Backup Disabled #882

- assets/queries/cloudFormation/gamelift_fleet_ec2inboundpermissions_with_port_range/metadata.json
- assets/queries/cloudFormation/gamelift_fleet_ec2inboundpermissions_with_port_range/query.rego
- assets/queries/cloudFormation/gamelift_fleet_ec2inboundpermissions_with_port_range/test/negative.yaml
- assets/queries/cloudFormation/gamelift_fleet_ec2inboundpermissions_with_port_range/test/positive.yaml
- assets/queries/cloudFormation/gamelift_fleet_ec2inboundpermissions_with_port_range/test/positive_expected_result.json
For this query, it is necessary to check if attribute 'FromPort' is different than attribute 'ToPort' in the EC2InboundPermissions
Closes #1097
> Add gamelift_fleet_ec2inboundpermissions_with_port_range Closes #1097

- assets/queries/cloudFormation/congito_userpool_without_mfa/metadata.json
- assets/queries/cloudFormation/congito_userpool_without_mfa/query.rego
- assets/queries/cloudFormation/congito_userpool_without_mfa/test/negative.yaml
- assets/queries/cloudFormation/congito_userpool_without_mfa/test/positive.yaml
- assets/queries/cloudFormation/congito_userpool_without_mfa/test/positive_expected_result.json
For this query, it is necessary to check if MfaConfiguration is set to OFF, since "OFF MFA will not be used for any users".
Closes #1093
> Add cognito_userpool_without_mfa Closes #1093

- assets/queries/dockerfile/unpinned_package_version_in_pip_install/metadata.json
- assets/queries/dockerfile/unpinned_package_version_in_pip_install/query.rego
- assets/queries/dockerfile/unpinned_package_version_in_pip_install/test/negative.dockerfile
- assets/queries/dockerfile/unpinned_package_version_in_pip_install/test/positive.dockerfile
- assets/queries/dockerfile/unpinned_package_version_in_pip_install/test/positive_expected_result.json
*Docker*
*Package version pinning reduces the range of versions that can be installed, reducing the chances of failure due to unanticipated changes*
Closes #1010
> Add 'Unpinned Package Version in pip install' query for Docker

- assets/queries/terraform/aws/iam_password_missing_reuse/metadata.json
- assets/queries/terraform/aws/iam_password_missing_reuse/query.rego
- assets/queries/terraform/aws/iam_password_missing_reuse/test/negative.tf
- assets/queries/terraform/aws/iam_password_missing_reuse/test/positive.tf
- assets/queries/terraform/aws/iam_password_missing_reuse/test/positive_expected_result.json
> added new query for IAM Password Without Reuse Prevention

- assets/queries/terraform/aws/iam_password_lowercase_letter/metadata.json
- assets/queries/terraform/aws/iam_password_lowercase_letter/query.rego
- assets/queries/terraform/aws/iam_password_lowercase_letter/test/negative.tf
- assets/queries/terraform/aws/iam_password_lowercase_letter/test/positive.tf
- assets/queries/terraform/aws/iam_password_lowercase_letter/test/positive_expected_result.json
> added new query for IAM Password Without Lowercase Letter

- assets/queries/terraform/aws/iam_password_symbol_required/metadata.json
- assets/queries/terraform/aws/iam_password_symbol_required/query.rego
- assets/queries/terraform/aws/iam_password_symbol_required/test/negative.tf
- assets/queries/terraform/aws/iam_password_symbol_required/test/positive.tf
- assets/queries/terraform/aws/iam_password_symbol_required/test/positive_expected_result.json
> added new query for IAM Password Without symbols

- assets/queries/cloudFormation/ebs_volume_encryption_key_rule/metadata.json
- assets/queries/cloudFormation/ebs_volume_encryption_key_rule/query.rego
- assets/queries/cloudFormation/ebs_volume_encryption_key_rule/test/negative.yaml
- assets/queries/cloudFormation/ebs_volume_encryption_key_rule/test/positive.yaml
- assets/queries/cloudFormation/ebs_volume_encryption_key_rule/test/positive_expected_result.json
Description: EBS Volume should specify a KmsKeyId value
Close #972
> Added Query  ebs volume encryption key

- assets/queries/dockerfile/unpinned_package_version_in_apk_add/metadata.json
- assets/queries/dockerfile/unpinned_package_version_in_apk_add/query.rego
- assets/queries/dockerfile/unpinned_package_version_in_apk_add/test/negative.dockerfile
- assets/queries/dockerfile/unpinned_package_version_in_apk_add/test/positive.dockerfile
- assets/queries/dockerfile/unpinned_package_version_in_apk_add/test/positive_expected_result.json
> Add 'Unpinned Package Version in Apk Add' query for Docker

- assets/queries/cloudFormation/s3_bucket_acl_allows_read_to_any_authenticated_user/metadata.json
- assets/queries/cloudFormation/s3_bucket_acl_allows_read_to_any_authenticated_user/query.rego
- assets/queries/cloudFormation/s3_bucket_acl_allows_read_to_any_authenticated_user/test/negative.yaml
- assets/queries/cloudFormation/s3_bucket_acl_allows_read_to_any_authenticated_user/test/positive.yaml
- assets/queries/cloudFormation/s3_bucket_acl_allows_read_to_any_authenticated_user/test/positive_expected_result.json
**Platform**
_CloudFormation_
_S3 Bucket ACL should not allow read operations to 'AuthenticatedUser' grantee group_
Closes #793
> Add S3 Bucket ACL Allows Read to Any Authenticated User query for CloudFormation

- assets/queries/ansible/gcp/cloud_sql_instance_is_publicly_accessible/metadata.json
- assets/queries/ansible/gcp/cloud_sql_instance_is_publicly_accessible/query.rego
- assets/queries/ansible/gcp/cloud_sql_instance_is_publicly_accessible/test/negative.yaml
- assets/queries/ansible/gcp/cloud_sql_instance_is_publicly_accessible/test/positive.yaml
- assets/queries/ansible/gcp/cloud_sql_instance_is_publicly_accessible/test/positive_expected_result.json
- test/main_test.go
Check GCP Cloud SQL instances to see if they are publicly accessible. Closes #1181
> Add query to check if cloud sql instance is publicly accessible. Closes #1181

- assets/queries/terraform/aws/neptune_cluster_not_encrypted/metadata.json
- assets/queries/terraform/aws/neptune_cluster_not_encrypted/query.rego
- assets/queries/terraform/aws/neptune_cluster_not_encrypted/test/negative.tf
- assets/queries/terraform/aws/neptune_cluster_not_encrypted/test/positive.tf
- assets/queries/terraform/aws/neptune_cluster_not_encrypted/test/positive_expected_result.json
> added new query for Neptune Cluster not encrypted

- assets/queries/ansible/azure/ssl_connection_is_enabled/metadata.json
- assets/queries/ansible/azure/ssl_connection_is_enabled/query.rego
- assets/queries/ansible/azure/ssl_connection_is_enabled/test/negative.yaml
- assets/queries/ansible/azure/ssl_connection_is_enabled/test/positive.yaml
- assets/queries/ansible/azure/ssl_connection_is_enabled/test/positive_expected_result.json
- test/main_test.go
Implemented query SSL Connection Is Enabled
Closes #1309
> Implemented query SSL Connection Is Enabled #1309

- assets/queries/cloudFormation/iam_user_invalid_password/metadata.json
- assets/queries/cloudFormation/iam_user_invalid_password/query.rego
- assets/queries/cloudFormation/iam_user_invalid_password/test/negative.yaml
- assets/queries/cloudFormation/iam_user_invalid_password/test/positive.yaml
- assets/queries/cloudFormation/iam_user_invalid_password/test/positive_expected_result.json
> Added new query for iam user invalid password

- assets/queries/cloudFormation/ec2_networkAcl/metadata.json
- assets/queries/cloudFormation/ec2_networkAcl/query.rego
- assets/queries/cloudFormation/ec2_networkAcl/test/negative.yaml
- assets/queries/cloudFormation/ec2_networkAcl/test/positive.yaml
- assets/queries/cloudFormation/ec2_networkAcl/test/positive_expected_result.json
> added new query for ec2 network ACL protocols

- assets/queries/cloudFormation/iam_managed_policy_applied_to_a_user/metadata.json
- assets/queries/cloudFormation/iam_managed_policy_applied_to_a_user/query.rego
- assets/queries/cloudFormation/iam_managed_policy_applied_to_a_user/test/negative.yaml
- assets/queries/cloudFormation/iam_managed_policy_applied_to_a_user/test/positive.yaml
- assets/queries/cloudFormation/iam_managed_policy_applied_to_a_user/test/positive_expected_result.json
> Added query IAM Managed Policy Applied to a User #982

- assets/queries/cloudFormation/ecs_allows_inbound_to_all_ipv4_and_ports/metadata.json
- assets/queries/cloudFormation/ecs_allows_inbound_to_all_ipv4_and_ports/query.rego
- assets/queries/cloudFormation/ecs_allows_inbound_to_all_ipv4_and_ports/test/negative.yaml
- assets/queries/cloudFormation/ecs_allows_inbound_to_all_ipv4_and_ports/test/positive.yaml
- assets/queries/cloudFormation/ecs_allows_inbound_to_all_ipv4_and_ports/test/positive_expected_result.json
**Platform**
_CloudFormation_
_ECS Service's security group should not allow unrestricted access to all ports from all IPv4 addresses_
Closes #946
> Add 'ECS Service Allows Inbound To All IPv4 And Ports' query for CloudFormation

- assets/queries/dockerfile/yum_clean_all_missing/metadata.json
- assets/queries/dockerfile/yum_clean_all_missing/query.rego
- assets/queries/dockerfile/yum_clean_all_missing/test/negative.dockerfile
- assets/queries/dockerfile/yum_clean_all_missing/test/positive.dockerfile
- assets/queries/dockerfile/yum_clean_all_missing/test/positive_expected_result.json
Closes #1092 
Check if we are using the 'yum clean all' after the yum command
> Add yum_clean_all_missing Closes #1092

- assets/queries/ansible/gcp/node_auto_upgrade_not_enabled/metadata.json
- assets/queries/ansible/gcp/node_auto_upgrade_not_enabled/query.rego
- assets/queries/ansible/gcp/node_auto_upgrade_not_enabled/test/negative.yaml
- assets/queries/ansible/gcp/node_auto_upgrade_not_enabled/test/positive.yaml
- assets/queries/ansible/gcp/node_auto_upgrade_not_enabled/test/positive_expected_result.json
Closes #1346 
Checks if 'auto_upgrade' nodes is enabled for Kubernetes Clusters.
> Add node_auto_upgrade_not_enabled query for Ansible #1346

- assets/queries/cloudFormation/load_balancer_ssh_is_too_exposed/metadata.json
- assets/queries/cloudFormation/load_balancer_ssh_is_too_exposed/query.rego
- assets/queries/cloudFormation/load_balancer_ssh_is_too_exposed/test/negative.yaml
- assets/queries/cloudFormation/load_balancer_ssh_is_too_exposed/test/positive.yaml
- assets/queries/cloudFormation/load_balancer_ssh_is_too_exposed/test/positive_expected_result.json
The load balancer of the application with SSH connection is too exposed to the public internet.
Closes #1179
> Add Load Balancer SSH Is Too Exposed query #1179

- assets/queries/cloudFormation/aws_lambda_functions_with_unique_iam_roles/metadata.json
- assets/queries/cloudFormation/aws_lambda_functions_with_unique_iam_roles/query.rego
- assets/queries/cloudFormation/aws_lambda_functions_with_unique_iam_roles/test/negative.yaml
- assets/queries/cloudFormation/aws_lambda_functions_with_unique_iam_roles/test/positive.yaml
- assets/queries/cloudFormation/aws_lambda_functions_with_unique_iam_roles/test/positive_expected_result.json
This query checks if there are any AWS Lambda Functions sharing IAM roles. Closes #1106
> Add aws_lambda_functions_with_unique_iam_roles query for CloudFormation

- assets/queries/dockerfile/shell_pipe_without_pipefail_flag/metadata.json
- assets/queries/dockerfile/shell_pipe_without_pipefail_flag/query.rego
- assets/queries/dockerfile/shell_pipe_without_pipefail_flag/test/negative.dockerfile
- assets/queries/dockerfile/shell_pipe_without_pipefail_flag/test/positive.dockerfile
- assets/queries/dockerfile/shell_pipe_without_pipefail_flag/test/positive_expected_result.json
Check if when a shell is used and pipes some output, the pipefail option is set in the shell. Closes #1156
> Add query to check if pipes are used with pipefail. Closes #1156

- assets/queries/dockerfile/copy_2_Args/metadata.json
- assets/queries/dockerfile/copy_2_Args/query.rego
- assets/queries/dockerfile/copy_2_Args/test/negative.dockerfile
- assets/queries/dockerfile/copy_2_Args/test/positive.dockerfile
- assets/queries/dockerfile/copy_2_Args/test/positive_expected_result.json
> Query Copy With More Than 2 Arguments Not Ending With a Slash

- assets/queries/ansible/azure/log_disconnections_is_not_set/metadata.json
- assets/queries/ansible/azure/log_disconnections_is_not_set/query.rego
- assets/queries/ansible/azure/log_disconnections_is_not_set/test/negative.yaml
- assets/queries/ansible/azure/log_disconnections_is_not_set/test/positive.yaml
- assets/queries/ansible/azure/log_disconnections_is_not_set/test/positive_expected_result.json
Implemented query Log Disconnections Is Not Set
Closes #1402
> Implemented query Log Disconnections Is Not Set #1402

- assets/queries/ansible/azure/postgre_sql_log_checkpoints_is_on/metadata.json
- assets/queries/ansible/azure/postgre_sql_log_checkpoints_is_on/query.rego
- assets/queries/ansible/azure/postgre_sql_log_checkpoints_is_on/test/negative.yaml
- assets/queries/ansible/azure/postgre_sql_log_checkpoints_is_on/test/positive.yaml
- assets/queries/ansible/azure/postgre_sql_log_checkpoints_is_on/test/positive_expected_result.json
Implemented query PostgreSQL Logs Checkpoints Is On
Closes #1400
> Implemented query PostgreSQL Logs Checkpoints Is On #1400

- assets/queries/ansible/azure/redis_entirely_accessible/metadata.json
- assets/queries/ansible/azure/redis_entirely_accessible/query.rego
- assets/queries/ansible/azure/redis_entirely_accessible/test/negative.yaml
- assets/queries/ansible/azure/redis_entirely_accessible/test/positive.yaml
- assets/queries/ansible/azure/redis_entirely_accessible/test/positive_expected_result.json
Closes #1386 
Checks if both start_ip_address and end_ip_address equal to '0.0.0.0'
> Add redis_entirely_accessible query for Ansible #1386

- assets/queries/ansible/azure/redis_publicly_accessible/metadata.json
- assets/queries/ansible/azure/redis_publicly_accessible/query.rego
- assets/queries/ansible/azure/redis_publicly_accessible/test/negative.yaml
- assets/queries/ansible/azure/redis_publicly_accessible/test/positive.yaml
- assets/queries/ansible/azure/redis_publicly_accessible/test/positive_expected_result.json
Closes #1377 
Checks if IP range is public.
> Add redis_publicly_accessible query for Ansible #1377

- assets/queries/ansible/azure/aks_network_policy_misconfigured/metadata.json
- assets/queries/ansible/azure/aks_network_policy_misconfigured/query.rego
- assets/queries/ansible/azure/aks_network_policy_misconfigured/test/negative.yaml
- assets/queries/ansible/azure/aks_network_policy_misconfigured/test/positive.yaml
- assets/queries/ansible/azure/aks_network_policy_misconfigured/test/positive_expected_result.json
> Add 'AKS Network Policy Misconfigured' query for Ansible

- assets/queries/ansible/aws/default_security_group_does_not_restrict_all_traffic/metadata.json
- assets/queries/ansible/aws/default_security_group_does_not_restrict_all_traffic/query.rego
- assets/queries/ansible/aws/default_security_group_does_not_restrict_all_traffic/test/negative.yaml
- assets/queries/ansible/aws/default_security_group_does_not_restrict_all_traffic/test/positive.yaml
- assets/queries/ansible/aws/default_security_group_does_not_restrict_all_traffic/test/positive_expected_result.json
Implemented query Default Security Group Does Not Restrict All Traffic
Closes #1366
> Implemented query Default Security Group Does Not Restrict All Traffic #1366

- assets/queries/ansible/azure/sqlserver_ingress_from_any_ip/metadata.json
- assets/queries/ansible/azure/sqlserver_ingress_from_any_ip/query.rego
- assets/queries/ansible/azure/sqlserver_ingress_from_any_ip/test/negative.yaml
- assets/queries/ansible/azure/sqlserver_ingress_from_any_ip/test/positive.yaml
- assets/queries/ansible/azure/sqlserver_ingress_from_any_ip/test/positive_expected_result.json
Implemented query SQLServer Ingress from Any IP
Closes #1372
> Implemented query SQLServer Ingress from Any IP #1372

- assets/queries/ansible/azure/sqlserver_with_public_access/metadata.json
- assets/queries/ansible/azure/sqlserver_with_public_access/query.rego
- assets/queries/ansible/azure/sqlserver_with_public_access/test/negative.yaml
- assets/queries/ansible/azure/sqlserver_with_public_access/test/positive.yaml
- assets/queries/ansible/azure/sqlserver_with_public_access/test/positive_expected_result.json
Implemented query SQLServer with Public Access
Closes #1375
> Implemented query SQLServer with Public Access #1375

- assets/queries/ansible/azure/connection_throttling/metadata.json
- assets/queries/ansible/azure/connection_throttling/query.rego
- assets/queries/ansible/azure/connection_throttling/test/negative.yaml
- assets/queries/ansible/azure/connection_throttling/test/positive.yaml
- assets/queries/ansible/azure/connection_throttling/test/positive_expected_result.json
Implemented query Connection Throttling
Closes #1406
> Implemented query Connection Throttling #1406

- assets/queries/ansible/azure/log_connections_is_not_set/metadata.json
- assets/queries/ansible/azure/log_connections_is_not_set/query.rego
- assets/queries/ansible/azure/log_connections_is_not_set/test/negative.yaml
- assets/queries/ansible/azure/log_connections_is_not_set/test/positive.yaml
- assets/queries/ansible/azure/log_connections_is_not_set/test/positive_expected_result.json
Implemented query Log Connections Is Not Set 
Closes #1404
> Implemented query Log Connections Is Not Set #1404

- assets/queries/dockerfile/pin_versions_apt_get_delete/metadata.json
- assets/queries/dockerfile/pin_versions_apt_get_delete/query.rego
- assets/queries/dockerfile/pin_versions_apt_get_delete/test/negative.dockerfile
- assets/queries/dockerfile/pin_versions_apt_get_delete/test/positive.dockerfile
- assets/queries/dockerfile/pin_versions_apt_get_delete/test/positive_expected_result.json
> Query AptGet Install Delete Lists

- assets/queries/ansible/aws/allUsers_gets_read_access/metadata.json
- assets/queries/ansible/aws/allUsers_gets_read_access/query.rego
- assets/queries/ansible/aws/allUsers_gets_read_access/test/negative.yaml
- assets/queries/ansible/aws/allUsers_gets_read_access/test/positive.yaml
- assets/queries/ansible/aws/allUsers_gets_read_access/test/positive_expected_result.json
Implemented query All Users Group Gets Read Access 
Closes #1325
> Implemented query All Users Group Gets Read Access #1325

- assets/queries/ansible/azure/ssl_enforce_is_disabled/metadata.json
- assets/queries/ansible/azure/ssl_enforce_is_disabled/query.rego
- assets/queries/ansible/azure/ssl_enforce_is_disabled/test/negative.yaml
- assets/queries/ansible/azure/ssl_enforce_is_disabled/test/positive.yaml
- assets/queries/ansible/azure/ssl_enforce_is_disabled/test/positive_expected_result.json
Implemented query SSL Enforce Is Disabled
Closes #1304
> Implemented query SSL Enforce Is Disabled #1304

- assets/queries/ansible/aws/s3_bucket_without_versioning/metadata.json
- assets/queries/ansible/aws/s3_bucket_without_versioning/query.rego
- assets/queries/ansible/aws/s3_bucket_without_versioning/test/negative.yaml
- assets/queries/ansible/aws/s3_bucket_without_versioning/test/positive.yaml
- assets/queries/ansible/aws/s3_bucket_without_versioning/test/positive_expected_result.json
- assets/queries/terraform/aws/ebs_volume_snapshot_encrypted/metadata.json
Implemented query S3 bucket without versioning
Closes #1323
> Implemented query S3 bucket without versioning #1323

- assets/queries/ansible/gcp/compute_disk_is_not_encrypted/metadata.json
- assets/queries/ansible/gcp/compute_disk_is_not_encrypted/query.rego
- assets/queries/ansible/gcp/compute_disk_is_not_encrypted/test/negative.yaml
- assets/queries/ansible/gcp/compute_disk_is_not_encrypted/test/positive.yaml
- assets/queries/ansible/gcp/compute_disk_is_not_encrypted/test/positive_expected_result.json
Implemented query Compute disk is not encrypted
Closes #1258
> Implemented query Compute disk is not encrypted #1258

- assets/queries/dockerfile/yum_update_disabled/metadata.json
- assets/queries/dockerfile/yum_update_disabled/query.rego
- assets/queries/dockerfile/yum_update_disabled/test/negative.dockerfile
- assets/queries/dockerfile/yum_update_disabled/test/positive.dockerfile
- assets/queries/dockerfile/yum_update_disabled/test/positive_expected_result.json
Closes #1090 
Check if we are using yum update
> Add _ yum_update_disabled query Closes #1090

- assets/queries/terraform/azure/sensitive_port_is_exposed_to_wide_private_network/metadata.json
- assets/queries/terraform/azure/sensitive_port_is_exposed_to_wide_private_network/query.rego
- assets/queries/terraform/azure/sensitive_port_is_exposed_to_wide_private_network/test/negative.tf
- assets/queries/terraform/azure/sensitive_port_is_exposed_to_wide_private_network/test/positive.tf
- assets/queries/terraform/azure/sensitive_port_is_exposed_to_wide_private_network/test/positive_expected_result.json
I've added the new query.
In addition, since there were ~10 additional ports that are relevant for this and "entire network" query, then after consultation with AppSec (Erez) I've added these ports also to the "entire network" query.
> Add the new query - ports in private network terraform azure

- assets/queries/ansible/aws/ecs_task_definition_network_mode/metadata.json
- assets/queries/ansible/aws/ecs_task_definition_network_mode/query.rego
- assets/queries/ansible/aws/ecs_task_definition_network_mode/test/negative.yaml
- assets/queries/ansible/aws/ecs_task_definition_network_mode/test/positive.yaml
- assets/queries/ansible/aws/ecs_task_definition_network_mode/test/positive_expected_result.json
> Add ECS Task Definition Network Mode  #1283

- assets/queries/ansible/gcp/project-wide_ssh_keys_enabled_for_vm_instance/metadata.json
- assets/queries/ansible/gcp/project-wide_ssh_keys_enabled_for_vm_instance/query.rego
- assets/queries/ansible/gcp/project-wide_ssh_keys_enabled_for_vm_instance/test/negative.yaml
- assets/queries/ansible/gcp/project-wide_ssh_keys_enabled_for_vm_instance/test/positive.yaml
- assets/queries/ansible/gcp/project-wide_ssh_keys_enabled_for_vm_instance/test/positive_expected_result.json
Check if project-wide ssh keys are blocked in VM instances. Closes #1297
> Add query to check if project-wide ssh keys are blocked for vm. Closes #1297

- assets/queries/ansible/aws/redshift_not_encrypted/query.rego
- assets/queries/ansible/aws/redshift_publicly_accessible/query.rego
- assets/queries/ansible/azure/container_registry_enabled_admin/metadata.json
- assets/queries/ansible/azure/container_registry_enabled_admin/query.rego
- assets/queries/ansible/azure/container_registry_enabled_admin/test/negative.yaml
- assets/queries/ansible/azure/container_registry_enabled_admin/test/positive.yaml
- assets/queries/ansible/azure/container_registry_enabled_admin/test/positive_expected_result.json
Implemented query Admin user is enabled for Container Registry
Closes #1417
> Implemented query Admin user is enabled for Container Registry #1417

- assets/queries/ansible/aws/rds_without_backup/metadata.json
- assets/queries/ansible/aws/rds_without_backup/query.rego
- assets/queries/ansible/aws/rds_without_backup/test/negative.yaml
- assets/queries/ansible/aws/rds_without_backup/test/positive.yaml
- assets/queries/ansible/aws/rds_without_backup/test/positive_expected_result.json
Implemented query RDS without Backup
Closes #1426
> Implemented query RDS without Backup #1426

- README.md
> Updated xmas logo

- assets/queries/ansible/azure/app_gateway_waf_is_disabled/metadata.json
- assets/queries/ansible/azure/app_gateway_waf_is_disabled/query.rego
- assets/queries/ansible/azure/app_gateway_waf_is_disabled/test/negative.yaml
- assets/queries/ansible/azure/app_gateway_waf_is_disabled/test/positive.yaml
- assets/queries/ansible/azure/app_gateway_waf_is_disabled/test/positive_expected_result.json
Check if the app gateway that specifies an SKU tier, uses WAF. Closes #1469
> Add query to check if WAF is disabled in the App Gateway. Closes #1469

- assets/queries/ansible/aws/sqs_queue_exposed/metadata.json
- assets/queries/ansible/aws/sqs_queue_exposed/query.rego
- assets/queries/ansible/aws/sqs_queue_exposed/test/negative.yaml
- assets/queries/ansible/aws/sqs_queue_exposed/test/positive.yaml
- assets/queries/ansible/aws/sqs_queue_exposed/test/positive_expected_result.json
Closes #1300 
Check if the SQS queue isn't publicly accessible
> Add ansible_sqs_queue_exposed query Closes #1300

- assets/queries/dockerfile/last_user_is_root/metadata.json
- assets/queries/dockerfile/last_user_is_root/query.rego
- assets/queries/dockerfile/last_user_is_root/test/negative.dockerfile
- assets/queries/dockerfile/last_user_is_root/test/positive.dockerfile
- assets/queries/dockerfile/last_user_is_root/test/positive_expected_result.json
> Add Last User Is 'root' #1260

- assets/queries/ansible/aws/api_gateway_without_ssl_certificate/metadata.json
- assets/queries/ansible/aws/api_gateway_without_ssl_certificate/query.rego
- assets/queries/ansible/aws/api_gateway_without_ssl_certificate/test/negative.yaml
- assets/queries/ansible/aws/api_gateway_without_ssl_certificate/test/positive.yaml
- assets/queries/ansible/aws/api_gateway_without_ssl_certificate/test/positive_expected_result.json
- assets/queries/terraform/aws/api_gateway_without_ssl_certificate/metadata.json
- assets/queries/terraform/aws/api_gateway_without_ssl_certificate/test/positive_expected_result.json
For this query, it is necessary to check if validate_certs is not set to true
Closes #1206
> Add api_gateway_without_ssl_certificate Closes #1206

- assets/queries/dockerfile/image_version_using_latest/metadata.json
- assets/queries/dockerfile/image_version_using_latest/query.rego
- assets/queries/dockerfile/image_version_using_latest/test/negative.dockerfile
- assets/queries/dockerfile/image_version_using_latest/test/positive.dockerfile
- assets/queries/dockerfile/image_version_using_latest/test/positive_expected_result.json
> Add Image Version Using 'latest'  #1235

- assets/queries/ansible/aws/db_security_group_has_IsPublicIp/metadata.json
- assets/queries/ansible/aws/db_security_group_has_IsPublicIp/query.rego
- assets/queries/ansible/aws/db_security_group_has_IsPublicIp/test/negative.yaml
- assets/queries/ansible/aws/db_security_group_has_IsPublicIp/test/positive.yaml
- assets/queries/ansible/aws/db_security_group_has_IsPublicIp/test/positive_expected_result.json
> added query db_security_group_has_IsPublicIp

- assets/queries/ansible/aws/IAM_policies_with_full_privileges/metadata.json
- assets/queries/ansible/aws/IAM_policies_with_full_privileges/query.rego
- assets/queries/ansible/aws/IAM_policies_with_full_privileges/test/negative.yaml
- assets/queries/ansible/aws/IAM_policies_with_full_privileges/test/positive.yaml
- assets/queries/ansible/aws/IAM_policies_with_full_privileges/test/positive_expected_result.json
> Add IAM policies with full privileges query for Ansible

- assets/queries/ansible/aws/cloudformation_without_stack_policy/metadata.json
- assets/queries/ansible/aws/cloudformation_without_stack_policy/query.rego
- assets/queries/ansible/aws/cloudformation_without_stack_policy/test/negative.yaml
- assets/queries/ansible/aws/cloudformation_without_stack_policy/test/positive.yaml
- assets/queries/ansible/aws/cloudformation_without_stack_policy/test/positive_expected_result.json
For this query, it is necessary to check if the attribute 'stack_policy' is undefined.
(P.S. I did not find a community module to implement this query)
Closes #1244
> Add cloudformation_without_stack_policy Closes #1244

- assets/queries/ansible/aws/cloud_watch_logs/metadata.json
- assets/queries/ansible/aws/cloud_watch_logs/query.rego
- assets/queries/ansible/aws/cloud_watch_logs/test/negative.yaml
- assets/queries/ansible/aws/cloud_watch_logs/test/positive.yaml
- assets/queries/ansible/aws/cloud_watch_logs/test/positive_expected_result.json
> added new query for cloud watch logs

- assets/queries/cloudFormation/cloudformation_specifying_credentials_not_safe/metadata.json
- assets/queries/cloudFormation/cloudformation_specifying_credentials_not_safe/query.rego
- assets/queries/cloudFormation/cloudformation_specifying_credentials_not_safe/test/negative.yaml
- assets/queries/cloudFormation/cloudformation_specifying_credentials_not_safe/test/positive.yaml
- assets/queries/cloudFormation/cloudformation_specifying_credentials_not_safe/test/positive_expected_result.json
Specifying credentials in the template itself is probably not safe to do. #1162
> Add CloudFormation Specifying Credentials Not Safe CloudFormation #1162

- assets/queries/ansible/azure/log_retention_is_not_set/metadata.json
- assets/queries/ansible/azure/log_retention_is_not_set/query.rego
- assets/queries/ansible/azure/log_retention_is_not_set/test/negative.yaml
- assets/queries/ansible/azure/log_retention_is_not_set/test/positive.yaml
- assets/queries/ansible/azure/log_retention_is_not_set/test/positive_expected_result.json
Closes #1522 
Make sure that for PostgreSQL Database, server parameter 'log_retention' is set to 'on'
> Add log_retention_is_not_set query for Ansible #1522

- assets/queries/ansible/aws/not_encrypted_data_in_launch_configuration/metadata.json
- assets/queries/ansible/aws/not_encrypted_data_in_launch_configuration/query.rego
- assets/queries/ansible/aws/not_encrypted_data_in_launch_configuration/test/negative.yaml
- assets/queries/ansible/aws/not_encrypted_data_in_launch_configuration/test/positive.yaml
- assets/queries/ansible/aws/not_encrypted_data_in_launch_configuration/test/positive_expected_result.json
- assets/queries/terraform/aws/not_encrypted_data_in_launch_configuration/metadata.json
For this query, it is necessary to check if the AWS Autoscaling Launch Configurations is encrypted
Closes #1510
> Add not_encrypted_data_in_launch_configuration Closes #1510

- assets/queries/terraform/aws/sensitive_port_is_exposed_to_entire_network/metadata.json
- assets/queries/terraform/aws/sensitive_port_is_exposed_to_entire_network/query.rego
- assets/queries/terraform/aws/sensitive_port_is_exposed_to_entire_network/test/negative.tf
- assets/queries/terraform/aws/sensitive_port_is_exposed_to_entire_network/test/positive.tf
- assets/queries/terraform/aws/sensitive_port_is_exposed_to_entire_network/test/positive_expected_result.json
Copied and modified the Azure query for open ports in the entire network to AWS.
> Add sensitive_port_is_exposed_to_entire_network query for Terraform AWS

- assets/queries/terraform/azure/sensitive_port_is_exposed_to_small_public_network/metadata.json
- assets/queries/terraform/azure/sensitive_port_is_exposed_to_small_public_network/query.rego
- assets/queries/terraform/azure/sensitive_port_is_exposed_to_small_public_network/test/negative.tf
- assets/queries/terraform/azure/sensitive_port_is_exposed_to_small_public_network/test/positive.tf
- assets/queries/terraform/azure/sensitive_port_is_exposed_to_small_public_network/test/positive_expected_result.json
Add the query sensitive ports exposed to small public network for Terraform/Azure.
> Add query sensitive ports exposed to small public network in Terraform/Azure

- assets/queries/ansible/azure/sensitive_port_is_exposed_to_entire_network/metadata.json
- assets/queries/ansible/azure/sensitive_port_is_exposed_to_entire_network/query.rego
- assets/queries/ansible/azure/sensitive_port_is_exposed_to_entire_network/test/negative.yaml
- assets/queries/ansible/azure/sensitive_port_is_exposed_to_entire_network/test/positive.yaml
- assets/queries/ansible/azure/sensitive_port_is_exposed_to_entire_network/test/positive_expected_result.json
Implemented query Sensitive Port Is Exposed To Entire Network
Closes #1503
> Implemented query Sensitive Port Is Exposed To Entire Network #1503

- assets/queries/ansible/aws/redshift_not_encrypted/query.rego
- assets/queries/ansible/aws/redshift_publicly_accessible/query.rego
- assets/queries/ansible/azure/storage_account_forces_https/metadata.json
- assets/queries/ansible/azure/storage_account_forces_https/query.rego
- assets/queries/ansible/azure/storage_account_forces_https/test/negative.yaml
- assets/queries/ansible/azure/storage_account_forces_https/test/positive.yaml
- assets/queries/ansible/azure/storage_account_forces_https/test/positive_expected_result.json
Implemented query Storage Account Forces HTTPS
Closes #1298
> Implemented query Storage Account Forces HTTPS #1298

- assets/queries/ansible/aws/db_instance_storage_not_encrypted/metadata.json
- assets/queries/ansible/aws/db_instance_storage_not_encrypted/query.rego
- assets/queries/ansible/aws/db_instance_storage_not_encrypted/test/negative.yaml
- assets/queries/ansible/aws/db_instance_storage_not_encrypted/test/positive.yaml
- assets/queries/ansible/aws/db_instance_storage_not_encrypted/test/positive_expected_result.json
- assets/queries/terraform/aws/db_instance_storage_not_encrypted/query.rego
- assets/queries/terraform/aws/db_instance_storage_not_encrypted/test/negative.tf
Implemented query DB Instance Storage Not Encrypted 
Closes #1240
> Implemented query DB Instance Storage Not Encrypted #1240

- assets/queries/ansible/aws/ebs_volume_clusters_encrypted/metadata.json
- assets/queries/ansible/aws/ebs_volume_clusters_encrypted/query.rego
- assets/queries/ansible/aws/ebs_volume_clusters_encrypted/test/negative.yaml
- assets/queries/ansible/aws/ebs_volume_clusters_encrypted/test/positive.yaml
- assets/queries/ansible/aws/ebs_volume_clusters_encrypted/test/positive_expected_result.json
Implemented query Volume Clusters Not Encrypted
Closes #1218
> Implemented query Volume Clusters Not Encrypted #1218

- assets/queries/ansible/aws/fully_open_ingress/metadata.json
- assets/queries/ansible/aws/fully_open_ingress/query.rego
- assets/queries/ansible/aws/fully_open_ingress/test/negative.yaml
- assets/queries/ansible/aws/fully_open_ingress/test/positive.yaml
- assets/queries/ansible/aws/fully_open_ingress/test/positive_expected_result.json
Implemented query Fully open Ingress
Closes #1533
> Implemented query Fully open Ingress #1533

- assets/queries/cloudFormation/routertable_with_default_routing/metadata.json
- assets/queries/cloudFormation/routertable_with_default_routing/query.rego
- assets/queries/cloudFormation/routertable_with_default_routing/test/negative.yaml
- assets/queries/cloudFormation/routertable_with_default_routing/test/positive.yaml
- assets/queries/cloudFormation/routertable_with_default_routing/test/positive_expected_result.json
The use of NAT gateways is recommended, and not the default route which permits all traffic, in Route Tables.
Close #1231
> Added New Query RouteTable with default route

- assets/queries/dockerfile/npm_install_without_pinned_version/metadata.json
- assets/queries/dockerfile/npm_install_without_pinned_version/query.rego
- assets/queries/dockerfile/npm_install_without_pinned_version/test/negative.dockerfile
- assets/queries/dockerfile/npm_install_without_pinned_version/test/positive.dockerfile
- assets/queries/dockerfile/npm_install_without_pinned_version/test/positive_expected_result.json
Check if any npm install execution sets the version of the package. Closes #1042
> Add query to check if npm install is executed without versioning. Closes #1042

- assets/queries/ansible/aws/api_gateway_endpoint_config_private/metadata.json
- assets/queries/ansible/aws/api_gateway_endpoint_config_private/query.rego
- assets/queries/ansible/aws/api_gateway_endpoint_config_private/test/negative.yaml
- assets/queries/ansible/aws/api_gateway_endpoint_config_private/test/positive.yaml
- assets/queries/ansible/aws/api_gateway_endpoint_config_private/test/positive_expected_result.json
> added new query for API Gateway Endpoint Config is Private in ansible

- assets/queries/ansible/aws/efs_not_encrypted/metadata.json
- assets/queries/ansible/aws/efs_not_encrypted/query.rego
- assets/queries/ansible/aws/efs_not_encrypted/test/negative.yaml
- assets/queries/ansible/aws/efs_not_encrypted/test/positive.yaml
- assets/queries/ansible/aws/efs_not_encrypted/test/positive_expected_result.json
Implemented query EFS Is Not Encrypted
Closes #1211
> Implemented query EFS Is Not Encrypted #1211

- assets/queries/ansible/aws/IAM_password_policy_expiration/metadata.json
- assets/queries/ansible/aws/IAM_password_policy_expiration/query.rego
- assets/queries/ansible/aws/IAM_password_policy_expiration/test/negative.yaml
- assets/queries/ansible/aws/IAM_password_policy_expiration/test/positive.yaml
- assets/queries/ansible/aws/IAM_password_policy_expiration/test/positive_expected_result.json
> added new query for Incorrect password policy expiration in Ansible

- assets/queries/cloudFormation/iam_access_keys_active_for_root/metadata.json
- assets/queries/cloudFormation/iam_access_keys_active_for_root/query.rego
- assets/queries/cloudFormation/iam_access_keys_active_for_root/test/negative.yaml
- assets/queries/cloudFormation/iam_access_keys_active_for_root/test/positive.yaml
- assets/queries/cloudFormation/iam_access_keys_active_for_root/test/positive_expected_result.json
Check if there is an AccessKey being associated with a root account. Closes #948
> Add query to check if AccessKeys are associated to root account. closes #948

- assets/queries/ansible/aws/unprotected_sql_queue/metadata.json
- assets/queries/ansible/aws/unprotected_sql_queue/query.rego
- assets/queries/ansible/aws/unprotected_sql_queue/test/negative.yaml
- assets/queries/ansible/aws/unprotected_sql_queue/test/positive.yaml
- assets/queries/ansible/aws/unprotected_sql_queue/test/positive_expected_result.json
> Added query Unprotected SQS Queue

- assets/queries/ansible/gcp/google_kms_crypto_key/metadata.json
- assets/queries/ansible/gcp/google_kms_crypto_key/query.rego
- assets/queries/ansible/gcp/google_kms_crypto_key/test/negative.yaml
- assets/queries/ansible/gcp/google_kms_crypto_key/test/positive.yaml
- assets/queries/ansible/gcp/google_kms_crypto_key/test/positive_expected_result.json
Make sure Encryption keys changes after 90 days #1425
> Add Google KMS Crypto Key Rotation Period query for Ansible #1425

- assets/queries/cloudFormation/refreshToken_is_exposed/metadata.json
- assets/queries/cloudFormation/refreshToken_is_exposed/query.rego
Updating RefreshToken Is Exposed query, correcting keyActualValue, keyExpectedValue and description.
#1091
Closes  #1574
> Updating RefreshToken Is Exposed query

- assets/queries/ansible/aws/no_password_reuse_prevention/metadata.json
- assets/queries/ansible/aws/no_password_reuse_prevention/query.rego
- assets/queries/ansible/aws/no_password_reuse_prevention/test/negative.yaml
- assets/queries/ansible/aws/no_password_reuse_prevention/test/positive.yaml
- assets/queries/ansible/aws/no_password_reuse_prevention/test/positive_expected_result.json
Implemented query No password reuse prevention
Closes #1422
> Implemented query No password reuse prevention #1422

- assets/queries/ansible/aws/hard_coded_aws_access_key/metadata.json
- assets/queries/ansible/aws/hard_coded_aws_access_key/query.rego
- assets/queries/ansible/aws/hard_coded_aws_access_key/test/negative.yaml
- assets/queries/ansible/aws/hard_coded_aws_access_key/test/positive.yaml
- assets/queries/ansible/aws/hard_coded_aws_access_key/test/positive_expected_result.json
Check user data in an EC2 instance to see if an access key is hardcoded. Closes #1489
> Add query to check if ec2 instance has hardcoded access key. Closes #1489

- assets/queries/ansible/aws/ssh_port_open/metadata.json
- assets/queries/ansible/aws/ssh_port_open/query.rego
- assets/queries/ansible/aws/ssh_port_open/test/negative.yaml
- assets/queries/ansible/aws/ssh_port_open/test/positive.yaml
- assets/queries/ansible/aws/ssh_port_open/test/positive_expected_result.json
Closes #1488 
Check if the ssh port is open to the internet
> Add ssh_port_open query Closes #1488

- assets/queries/ansible/aws/sqs_policy_with_public_access/metadata.json
- assets/queries/ansible/aws/sqs_policy_with_public_access/query.rego
- assets/queries/ansible/aws/sqs_policy_with_public_access/test/negative.yaml
- assets/queries/ansible/aws/sqs_policy_with_public_access/test/positive.yaml
- assets/queries/ansible/aws/sqs_policy_with_public_access/test/positive_expected_result.json
> added new query SQS policy with Public Access for ansible

- assets/queries/ansible/aws/ami_not_encrypted/metadata.json
- assets/queries/ansible/aws/ami_not_encrypted/query.rego
- assets/queries/ansible/aws/ami_not_encrypted/test/negative.yaml
- assets/queries/ansible/aws/ami_not_encrypted/test/positive.yaml
- assets/queries/ansible/aws/ami_not_encrypted/test/positive_expected_result.json
AWS AMI Encryption is not enabled #1498
> Add Ami Not Encrypted query for Ansible #1498

- assets/queries/ansible/aws/cloudfront_logging_is_disabled/metadata.json
- assets/queries/ansible/aws/cloudfront_logging_is_disabled/query.rego
- assets/queries/ansible/aws/cloudfront_logging_is_disabled/test/negative.yaml
- assets/queries/ansible/aws/cloudfront_logging_is_disabled/test/positive.yaml
- assets/queries/ansible/aws/cloudfront_logging_is_disabled/test/positive_expected_result.json
> Added query Cloudfront Logging is Disabled #1562

- assets/queries/ansible/aws/ecs_ecr_has_public_access/metadata.json
- assets/queries/ansible/aws/ecs_ecr_has_public_access/query.rego
- assets/queries/ansible/aws/ecs_ecr_has_public_access/test/negative.yaml
- assets/queries/ansible/aws/ecs_ecr_has_public_access/test/positive.yaml
- assets/queries/ansible/aws/ecs_ecr_has_public_access/test/positive_expected_result.json
> Add ECS ECR has Public Access query  #1318

- assets/queries/ansible/aws/ebs_encryption_disabled/metadata.json
- assets/queries/ansible/aws/ebs_encryption_disabled/query.rego
- assets/queries/ansible/aws/ebs_encryption_disabled/test/negative.yaml
- assets/queries/ansible/aws/ebs_encryption_disabled/test/positive.yaml
- assets/queries/ansible/aws/ebs_encryption_disabled/test/positive_expected_result.json
> Add 'EBS encryption disabled' query for Ansible

- assets/queries/ansible/gcp/oslogin_is_disabled_for_vm_instance/metadata.json
- assets/queries/ansible/gcp/oslogin_is_disabled_for_vm_instance/query.rego
- assets/queries/ansible/gcp/oslogin_is_disabled_for_vm_instance/test/negative.yaml
- assets/queries/ansible/gcp/oslogin_is_disabled_for_vm_instance/test/positive.yaml
- assets/queries/ansible/gcp/oslogin_is_disabled_for_vm_instance/test/positive_expected_result.json
Check if OSLogin is disabled (it's enabled as default) in VM instances. Closes #1306
> Add query to check if OSLogin is disabled for VM. Closes #1306

- assets/queries/ansible/gcp/serial_ports_enabled_for_vm_instance/metadata.json
- assets/queries/ansible/gcp/serial_ports_enabled_for_vm_instance/query.rego
- assets/queries/ansible/gcp/serial_ports_enabled_for_vm_instance/test/negative.yaml
- assets/queries/ansible/gcp/serial_ports_enabled_for_vm_instance/test/positive.yaml
- assets/queries/ansible/gcp/serial_ports_enabled_for_vm_instance/test/positive_expected_result.json
Check Google VM instances if serial ports are enabled. Closes #1294
> Add query to check if serial ports are enabled in vm instances. Closes #1294

- assets/queries/k8s/service_does_not_target_pod/metadata.json
- assets/queries/k8s/service_does_not_target_pod/query.rego
- assets/queries/k8s/service_does_not_target_pod/test/negative.yaml
- assets/queries/k8s/service_does_not_target_pod/test/positive.yaml
- assets/queries/k8s/service_does_not_target_pod/test/positive_expected_result.json
Service should Target a Pod #1430
> Add Service Does Not Target Pod query for Kubernetes #1430

- assets/queries/ansible/gcp/ssh_access_is_unrestricted/metadata.json
- assets/queries/ansible/gcp/ssh_access_is_unrestricted/query.rego
- assets/queries/ansible/gcp/ssh_access_is_unrestricted/test/negative.yaml
- assets/queries/ansible/gcp/ssh_access_is_unrestricted/test/positive.yaml
- assets/queries/ansible/gcp/ssh_access_is_unrestricted/test/positive_expected_result.json
Check if ingressing traffic is allowed for the public Internet, through SSH (port 22). Closes #1213
> Add query to check if SSH access is unrestricted from the internet. Closes #1213

- assets/queries/terraform/aws/iam_policies_allow_all/metadata.json
- assets/queries/terraform/aws/iam_policies_allow_all/test/positive_expected_result.json
> updated queryName and ID to match ansible query

- assets/queries/ansible/azure/redis_cache_non_ssl_connections_allowed/metadata.json
- assets/queries/ansible/azure/redis_cache_non_ssl_connections_allowed/query.rego
- assets/queries/ansible/azure/redis_cache_non_ssl_connections_allowed/test/negative.yaml
- assets/queries/ansible/azure/redis_cache_non_ssl_connections_allowed/test/positive.yaml
- assets/queries/ansible/azure/redis_cache_non_ssl_connections_allowed/test/positive_expected_result.json
- assets/queries/ansible/gcp/cloud_sql_instance_is_publicly_accessible/query.rego
- assets/queries/ansible/gcp/cloud_sql_instance_is_publicly_accessible/test/negative.yaml
- assets/queries/ansible/gcp/cloud_sql_instance_is_publicly_accessible/test/positive.yaml
- assets/queries/ansible/gcp/cloud_sql_instance_is_publicly_accessible/test/positive_expected_result.json
Check Redis cache instances if non-SSL connections are being allowed. Closes #1396
> Add query to check if Redis cache allows non SSL connections. Closes #1396

- assets/queries/ansible/aws/IAM_role_allows_public_assume/metadata.json
- assets/queries/ansible/aws/IAM_role_allows_public_assume/query.rego
- assets/queries/ansible/aws/IAM_role_allows_public_assume/test/negative.yaml
- assets/queries/ansible/aws/IAM_role_allows_public_assume/test/positive.yaml
- assets/queries/ansible/aws/IAM_role_allows_public_assume/test/positive_expected_result.json
> added new query IAM role allows public assume for ansible

- assets/queries/ansible/aws/memcached_disabled/metadata.json
- assets/queries/ansible/aws/memcached_disabled/query.rego
- assets/queries/ansible/aws/memcached_disabled/test/negative.yaml
- assets/queries/ansible/aws/memcached_disabled/test/positive.yaml
- assets/queries/ansible/aws/memcached_disabled/test/positive_expected_result.json
Closes #1571 
Checks if the MemCached is enabled in the ElastiCache
> Add memcached_disabled query Closes #1571

- assets/queries/ansible/aws/db_instance_publicly_accessible/metadata.json
- assets/queries/ansible/aws/db_instance_publicly_accessible/query.rego
- assets/queries/ansible/aws/db_instance_publicly_accessible/test/negative.yaml
- assets/queries/ansible/aws/db_instance_publicly_accessible/test/positive.yaml
- assets/queries/ansible/aws/db_instance_publicly_accessible/test/positive_expected_result.json
*Ansible*
*AWS*
*RDS Instance publicly_accessible flag should not be true*
Closes #1263
> Add 'DB Instance Publicly Accessible' query for AWS Ansible

- assets/queries/ansible/aws/cloudtrail_logging_disabled/metadata.json
- assets/queries/ansible/aws/cloudtrail_logging_disabled/query.rego
- assets/queries/ansible/aws/cloudtrail_logging_disabled/test/negative.yaml
- assets/queries/ansible/aws/cloudtrail_logging_disabled/test/positive.yaml
- assets/queries/ansible/aws/cloudtrail_logging_disabled/test/positive_expected_result.json
- assets/queries/terraform/aws/cloudtrail_logging_disabled/metadata.json
- assets/queries/terraform/aws/cloudtrail_logging_disabled/query.rego
Closes #1575 
This query checks if the logging has been enabled
> Add cloudtrail_logging_disabled query Closes #1575

- assets/queries/ansible/aws/s3_bucket_without_logging/metadata.json
- assets/queries/ansible/aws/s3_bucket_without_logging/query.rego
- assets/queries/ansible/aws/s3_bucket_without_logging/test/negative.yaml
- assets/queries/ansible/aws/s3_bucket_without_logging/test/positive.yaml
- assets/queries/ansible/aws/s3_bucket_without_logging/test/positive_expected_result.json
S3 bucket without debug_botocore_endpoint_logs
Closes #1492
> Add S3 Bucket Without Logging query #1492

- assets/queries/k8s/net_raw_capabilities_disabled/metadata.json
- assets/queries/k8s/net_raw_capabilities_disabled/query.rego
- assets/queries/k8s/net_raw_capabilities_disabled_minimized/metadata.json
- assets/queries/k8s/net_raw_capabilities_disabled_minimized/query.rego
Update query 30 and 31 from k8s #1610
> Update NET_RAW Capabilities Disabled and Minimized for PodSecurityPolicy query for Terraform #1610

- assets/queries/ansible/azure/cosmosdb_account_ip_range_filter_not_setted/metadata.json
- assets/queries/ansible/azure/cosmosdb_account_ip_range_filter_not_setted/query.rego
- assets/queries/ansible/azure/cosmosdb_account_ip_range_filter_not_setted/test/negative.yaml
- assets/queries/ansible/azure/cosmosdb_account_ip_range_filter_not_setted/test/positive.yaml
- assets/queries/ansible/azure/cosmosdb_account_ip_range_filter_not_setted/test/positive_expected_result.json
Provide a azurerm_cosmosdb_account resource and a resource to manage the ip_range_filter feature
Closes #1438
> Add CosmosDB Acc Ip Range Filter Not Setted query

- assets/queries/ansible/aws/rds_instance_storage_not_encrypted/metadata.json
- assets/queries/ansible/aws/rds_instance_storage_not_encrypted/query.rego
- assets/queries/ansible/aws/rds_instance_storage_not_encrypted/test/negative.yaml
- assets/queries/ansible/aws/rds_instance_storage_not_encrypted/test/positive.yaml
- assets/queries/ansible/aws/rds_instance_storage_not_encrypted/test/positive_expected_result.json
RDS Instance Storage should be encrypted or kms_key_id should be defined.
Closes #1456
> Add RDS Instance Storage Not Encrypted query #1456

- assets/queries/ansible/aws/secure_ciphers_not_used/metadata.json
- assets/queries/ansible/aws/secure_ciphers_not_used/query.rego
- assets/queries/ansible/aws/secure_ciphers_not_used/test/negative.yaml
- assets/queries/ansible/aws/secure_ciphers_not_used/test/positive.yaml
- assets/queries/ansible/aws/secure_ciphers_not_used/test/positive_expected_result.json
- assets/queries/ansible/aws/sqs_queue_exposed/query.rego
- assets/queries/ansible/aws/sqs_queue_exposed/test/negative.yaml
- assets/queries/ansible/aws/sqs_queue_exposed/test/positive.yaml
- assets/queries/ansible/aws/sqs_queue_exposed/test/positive_expected_result.json
Closes #1621 
Check if the CloudFront distribution is using secure ciphers
Made some changes to sqs_queue_exposed query
> Add secure_ciphers_not_used Closes #1621 and changes to sqs_queue_exposed

- assets/queries/ansible/aws/rds_ca_cert_id_expired/metadata.json
- assets/queries/ansible/aws/rds_ca_cert_id_expired/query.rego
- assets/queries/ansible/aws/rds_ca_cert_id_expired/test/negative.yaml
- assets/queries/ansible/aws/rds_ca_cert_id_expired/test/positive.yaml
- assets/queries/ansible/aws/rds_ca_cert_id_expired/test/positive_expected_result.json
> Add 'RDS CA certificate identifier is expired' query for Ansible

- assets/queries/ansible/aws/IAM_Password_Without_Uppercase_letter/metadata.json
- assets/queries/ansible/aws/IAM_Password_Without_Uppercase_letter/query.rego
- assets/queries/ansible/aws/IAM_Password_Without_Uppercase_letter/test/negative.yaml
- assets/queries/ansible/aws/IAM_Password_Without_Uppercase_letter/test/positive.yaml
- assets/queries/ansible/aws/IAM_Password_Without_Uppercase_letter/test/positive_expected_result.json
> added new query  "IAM_password_without_uppercase_letter" for ansible

- assets/queries/ansible/aws/cloudtrail_sns_topic_name_is_undefined/metadata.json
- assets/queries/ansible/aws/cloudtrail_sns_topic_name_is_undefined/query.rego
- assets/queries/ansible/aws/cloudtrail_sns_topic_name_is_undefined/test/negative.yaml
- assets/queries/ansible/aws/cloudtrail_sns_topic_name_is_undefined/test/positive.yaml
- assets/queries/ansible/aws/cloudtrail_sns_topic_name_is_undefined/test/positive_expected_result.json
Check if CloudTrail has SNS topic name undefined or empty. Closes #1408
> Add query to check if CloudTrail has SNS topic name set. Closes #1408

- assets/queries/ansible/gcp/cloud_sql_instance_with_public_ip/metadata.json
- assets/queries/ansible/gcp/cloud_sql_instance_with_public_ip/query.rego
- assets/queries/ansible/gcp/cloud_sql_instance_with_public_ip/test/negative.yaml
- assets/queries/ansible/gcp/cloud_sql_instance_with_public_ip/test/positive.yaml
- assets/queries/ansible/gcp/cloud_sql_instance_with_public_ip/test/positive_expected_result.json
GCP SQL Instance should have IPv4 disabled
Closes #1632
> Add Cloud SQL Instance With Public IP query #1632

- assets/queries/ansible/aws/remote_desktop_port_open/metadata.json
- assets/queries/ansible/aws/remote_desktop_port_open/query.rego
- assets/queries/ansible/aws/remote_desktop_port_open/test/negative.yaml
- assets/queries/ansible/aws/remote_desktop_port_open/test/positive.yaml
- assets/queries/ansible/aws/remote_desktop_port_open/test/positive_expected_result.json
Closes #1486 
Check if the remote desktop port is open
> Add remote_desktop_port_open query Closes #1486

- assets/queries/ansible/aws/IAM_password_without_numbers/metadata.json
- assets/queries/ansible/aws/IAM_password_without_numbers/query.rego
- assets/queries/ansible/aws/IAM_password_without_numbers/test/negative.yaml
- assets/queries/ansible/aws/IAM_password_without_numbers/test/positive.yaml
- assets/queries/ansible/aws/IAM_password_without_numbers/test/positive_expected_result.json
> added new query IAM Password Without Numbers for ansible

- assets/queries/ansible/aws/aws_elb_application_protocol_not_http/query.rego
- assets/queries/ansible/aws/aws_elb_application_protocol_not_http/test/negative.yaml
- assets/queries/ansible/aws/aws_elb_application_protocol_not_http/test/positive.yaml
- assets/queries/ansible/aws/aws_elb_application_protocol_not_http/test/positive_expected_result.json
The search key was incorrect, although the tests were running successfully
Closes #1649
> feature updated

- assets/queries/ansible/azure/log_connections_is_not_set/query.rego
- assets/queries/ansible/azure/log_duration_is_not_set/metadata.json
- assets/queries/ansible/azure/log_duration_is_not_set/query.rego
- assets/queries/ansible/azure/log_duration_is_not_set/test/negative.yaml
- assets/queries/ansible/azure/log_duration_is_not_set/test/positive.yaml
- assets/queries/ansible/azure/log_duration_is_not_set/test/positive_expected_result.json
Closes #1647 
Check if the 'log_duration' is set to 'on'
> Add log_duration_is_not_set query Closes #1647 and typos fix

- assets/queries/ansible/aws/authentication_without_mfa/metadata.json
- assets/queries/ansible/aws/authentication_without_mfa/query.rego
- assets/queries/ansible/aws/authentication_without_mfa/test/negative.yaml
- assets/queries/ansible/aws/authentication_without_mfa/test/positive.yaml
- assets/queries/ansible/aws/authentication_without_mfa/test/positive_expected_result.json
For this query, it is necessary to check if attributes 'mfa_serial_number' and 'mfa_token' exists
Closes #1490
> Add authentication_without_mfa Closes #1490

- assets/queries/ansible/aws/api_gateway_xray_disabled/metadata.json
- assets/queries/ansible/aws/api_gateway_xray_disabled/query.rego
- assets/queries/ansible/aws/api_gateway_xray_disabled/test/negative.yaml
- assets/queries/ansible/aws/api_gateway_xray_disabled/test/positive.yaml
- assets/queries/ansible/aws/api_gateway_xray_disabled/test/positive_expected_result.json
This query evaluates if active tracing with X-ray is enabled for the API Gateway stage.
Closes #1651
> Add api_gateway_xray_disabled query for Ansible

- assets/queries/ansible/aws/s3_bucket_with_public_access/metadata.json
- assets/queries/ansible/aws/s3_bucket_with_public_access/query.rego
- assets/queries/ansible/aws/s3_bucket_with_public_access/test/negative.yaml
- assets/queries/ansible/aws/s3_bucket_with_public_access/test/positive.yaml
- assets/queries/ansible/aws/s3_bucket_with_public_access/test/positive_expected_result.json
S3 Bucket allows public access
Closes #1530
> Add S3 Bucket With Public Access query #1530

- assets/queries/ansible/aws/IAM_password_without_lowercase_letter/metadata.json
- assets/queries/ansible/aws/IAM_password_without_lowercase_letter/query.rego
- assets/queries/ansible/aws/IAM_password_without_lowercase_letter/test/negative.yaml
- assets/queries/ansible/aws/IAM_password_without_lowercase_letter/test/positive.yaml
- assets/queries/ansible/aws/IAM_password_without_lowercase_letter/test/positive_expected_result.json
> added new query IAM Password Without Lowercase Letter for Ansible

- assets/queries/ansible/aws/https_traffic_disabled/metadata.json
- assets/queries/ansible/aws/https_traffic_disabled/query.rego
- assets/queries/ansible/aws/https_traffic_disabled/test/negative.yaml
- assets/queries/ansible/aws/https_traffic_disabled/test/positive.yaml
- assets/queries/ansible/aws/https_traffic_disabled/test/positive_expected_result.json
Closes #1622 
Check if the CloudFront and origin server connection is encrypted
> Add https_traffic_disabled query Closes #1622

- assets/queries/ansible/aws/port22_in_public_scope/metadata.json
- assets/queries/ansible/aws/port22_in_public_scope/query.rego
- assets/queries/ansible/aws/port22_in_public_scope/test/negative.yaml
- assets/queries/ansible/aws/port22_in_public_scope/test/positive.yaml
- assets/queries/ansible/aws/port22_in_public_scope/test/positive_expected_result.json
For this query, it is necessary to check if from_port and to_port are SSH and if cidr is not private 
Closes #1387
> Add port22_in_public_scope Closes #1387

- README.md
> Moving back to regular logo

- assets/queries/ansible/gcp/rdp_access_is_unrestricted/metadata.json
- assets/queries/ansible/gcp/rdp_access_is_unrestricted/query.rego
- assets/queries/ansible/gcp/rdp_access_is_unrestricted/test/negative.yaml
- assets/queries/ansible/gcp/rdp_access_is_unrestricted/test/positive.yaml
- assets/queries/ansible/gcp/rdp_access_is_unrestricted/test/positive_expected_result.json
Check Google firewall if RDP access is allowed from the internet. Closes #1285
> Add query to check if RDP access is unrestricted from the internet. Closes #1285

- assets/queries/ansible/aws/route53_record_without_values/metadata.json
- assets/queries/ansible/aws/route53_record_without_values/query.rego
- assets/queries/ansible/aws/route53_record_without_values/test/negative.yaml
- assets/queries/ansible/aws/route53_record_without_values/test/positive.yaml
- assets/queries/ansible/aws/route53_record_without_values/test/positive_expected_result.json
Route53 Record should have a list of records
Closes #1450
> Add Route53 Record Undefined query #1450

- assets/queries/ansible/gcp/cloud_sql_instance_with_cross_db_ownership_chaining_on/metadata.json
- assets/queries/ansible/gcp/cloud_sql_instance_with_cross_db_ownership_chaining_on/query.rego
- assets/queries/ansible/gcp/cloud_sql_instance_with_cross_db_ownership_chaining_on/test/negative.yaml
- assets/queries/ansible/gcp/cloud_sql_instance_with_cross_db_ownership_chaining_on/test/positive.yaml
- assets/queries/ansible/gcp/cloud_sql_instance_with_cross_db_ownership_chaining_on/test/positive_expected_result.json
GCP SQL Instance should not have Cross DB Ownership Chaining On
Closes #1664
> Add CSQL W/Cross DB Ownership Chaining query #1664

- assets/queries/ansible/aws/SQS_policy_allows_ALL_actions/metadata.json
- assets/queries/ansible/aws/SQS_policy_allows_ALL_actions/query.rego
- assets/queries/ansible/aws/SQS_policy_allows_ALL_actions/test/negative.yaml
- assets/queries/ansible/aws/SQS_policy_allows_ALL_actions/test/positive.yaml
- assets/queries/ansible/aws/SQS_policy_allows_ALL_actions/test/positive_expected_result.json
> added new query for SQS policy allows ALL (*) actions in ansible

- assets/queries/cloudFormation/unused_vpc/metadata.json
- assets/queries/cloudFormation/unused_vpc/query.rego
- assets/queries/cloudFormation/unused_vpc/test/negative.yaml
- assets/queries/cloudFormation/unused_vpc/test/positive.yaml
- assets/queries/cloudFormation/unused_vpc/test/positive_expected_result.json
Closes #1665 
VPCs must have resources attached to them.
> Add unused_vpc query for AWS Clouformation #1665

- assets/queries/cloudFormation/sns_topic_should_specify_kmsMasterKeyId/metadata.json
- assets/queries/cloudFormation/sns_topic_should_specify_kmsMasterKeyId/query.rego
- assets/queries/cloudFormation/sns_topic_should_specify_kmsMasterKeyId/test/negative.yaml
- assets/queries/cloudFormation/sns_topic_should_specify_kmsMasterKeyId/test/positive.yaml
- assets/queries/cloudFormation/sns_topic_should_specify_kmsMasterKeyId/test/positive_expected_result.json
KmsMasterKeyId attribute should not be undefined #1171
> Update Sns Topic Should Specify KmsMasterKeyId Attribute query for CloudFormation #1171

- assets/queries/cloudFormation/dynamodb_table_billing_mode/metadata.json
- assets/queries/cloudFormation/dynamodb_table_billing_mode/query.rego
- assets/queries/cloudFormation/dynamodb_table_billing_mode/test/negative.yaml
- assets/queries/cloudFormation/dynamodb_table_billing_mode/test/positive.yaml
- assets/queries/cloudFormation/dynamodb_table_billing_mode/test/positive_expected_result.json
Checks if DynamoDB Table Billing Mode is set to either PAY_PER_REQUEST or PROVISIONED #1669
> Add DynamoDB Table Billing Mode query for CloudFormation #1669

- .github/dependabot.yml
- docker-compose.yml
Added go modules in dependabot
Added docker compose
> ci improvements

- assets/queries/cloudFormation/rds_open_to_large_scope/metadata.json
- assets/queries/cloudFormation/rds_open_to_large_scope/query.rego
- assets/queries/cloudFormation/rds_open_to_large_scope/test/negative.yaml
- assets/queries/cloudFormation/rds_open_to_large_scope/test/positive.yaml
- assets/queries/cloudFormation/rds_open_to_large_scope/test/positive_expected_result.json
Adding RDS Open To Large Scope query for AWS CloudFormation, that checks if the IP Address in its Security Group has more than 256 hosts.
Closes #1117
> Add RDS Open To Large Scope query for AWS CloudFormation

- assets/queries/ansible/aws/cloudTrail_multiRegion_disabled/metadata.json
- assets/queries/ansible/aws/cloudTrail_multiRegion_disabled/query.rego
- assets/queries/ansible/aws/cloudTrail_multiRegion_disabled/test/negative.yaml
- assets/queries/ansible/aws/cloudTrail_multiRegion_disabled/test/positive.yaml
- assets/queries/ansible/aws/cloudTrail_multiRegion_disabled/test/positive_expected_result.json
Closes #1663 
checks if the Multi Region is enabled in the Cloud Trail
> Add cloudTrail_multiRegion_disabled query Closes #1663

- assets/queries/ansible/aws/codebuild_not_encrypted/metadata.json
- assets/queries/ansible/aws/codebuild_not_encrypted/query.rego
- assets/queries/ansible/aws/codebuild_not_encrypted/test/negative.yaml
- assets/queries/ansible/aws/codebuild_not_encrypted/test/positive.yaml
- assets/queries/ansible/aws/codebuild_not_encrypted/test/positive_expected_result.json
For this query, it is necessary to check if attribute 'encryption_key' is set
Closes #1679
> Add codebuild_not_encrypted query Closes #1679

- assets/queries/cloudFormation/volume_encrypted_is_disabled/metadata.json
- assets/queries/cloudFormation/volume_encrypted_is_disabled/query.rego
- assets/queries/cloudFormation/volume_encrypted_is_disabled/test/negative.yaml
- assets/queries/cloudFormation/volume_encrypted_is_disabled/test/positive.yaml
- assets/queries/cloudFormation/volume_encrypted_is_disabled/test/positive_expected_result.json
EBS volumes should be encrypted.
Closes #1676
> Add Volume Encryption Is Disabled query #1676

- assets/queries/cloudFormation/lambda_permission_badly_configured/metadata.json
- assets/queries/cloudFormation/lambda_permission_badly_configured/query.rego
- assets/queries/cloudFormation/lambda_permission_badly_configured/test/negative.yaml
- assets/queries/cloudFormation/lambda_permission_badly_configured/test/positive.yaml
- assets/queries/cloudFormation/lambda_permission_badly_configured/test/positive_expected_result.json
> Added query Lambda Permission Badly Configured #1671

- assets/queries/ansible/aws/aws_sns_topic_subscription/metadata.json
- assets/queries/ansible/aws/aws_sns_topic_subscription/query.rego
- assets/queries/ansible/aws/aws_sns_topic_subscription/test/negative.yaml
- assets/queries/ansible/aws/aws_sns_topic_subscription/test/positive.yaml
- assets/queries/ansible/aws/aws_sns_topic_subscription/test/positive_expected_result.json
This query checks if SNS Topic is Accessible For Subscription #1368
> Add SNS Topic is Publicly Accessible For Subscription query for Ansible #1368

- assets/queries/ansible/gcp/google_container_node_pool_auto_repair/metadata.json
- assets/queries/ansible/gcp/google_container_node_pool_auto_repair/query.rego
- assets/queries/ansible/gcp/google_container_node_pool_auto_repair/test/negative.yaml
- assets/queries/ansible/gcp/google_container_node_pool_auto_repair/test/positive.yaml
- assets/queries/ansible/gcp/google_container_node_pool_auto_repair/test/positive_expected_result.json
Verifies if Google Container Node Pool Auto Repair is Enabled #1265
> Add Google Container Node Pool Auto Repair is Disabled query for Ansible #1265

- assets/queries/ansible/azure/key_vault_soft_delete_disabled/metadata.json
- assets/queries/ansible/azure/key_vault_soft_delete_disabled/query.rego
- assets/queries/ansible/azure/key_vault_soft_delete_disabled/test/negative.yaml
- assets/queries/ansible/azure/key_vault_soft_delete_disabled/test/positive.yaml
- assets/queries/ansible/azure/key_vault_soft_delete_disabled/test/positive_expected_result.json
Make sure Soft Delete is enabled for Key Vault
Closes #1628
> Add Key Vault Soft Delete Is Disabled query #1628

- assets/queries/cloudFormation/vpc_attached_with_too_many_gateways/metadata.json
- assets/queries/cloudFormation/vpc_attached_with_too_many_gateways/query.rego
- assets/queries/cloudFormation/vpc_attached_with_too_many_gateways/test/negative.yaml
- assets/queries/cloudFormation/vpc_attached_with_too_many_gateways/test/positive.yaml
- assets/queries/cloudFormation/vpc_attached_with_too_many_gateways/test/positive_expected_result.json
Closes #1683 
The number of gateways approaches or goes beyond the limit in a particular VPC
> Add vpc_attached_with_too_many_gateways query for AWS CloudFormation #1683

- assets/queries/ansible/aws/s3_bucket_access_allowed_all/metadata.json
- assets/queries/ansible/aws/s3_bucket_access_allowed_all/query.rego
- assets/queries/ansible/aws/s3_bucket_access_allowed_all/test/negative.yaml
- assets/queries/ansible/aws/s3_bucket_access_allowed_all/test/positive.yaml
- assets/queries/ansible/aws/s3_bucket_with_all_permissions/query.rego
- assets/queries/ansible/aws/s3_bucket_with_all_permissions/test/negative.yaml
- assets/queries/ansible/aws/s3_bucket_with_all_permissions/test/positive.yaml
- assets/queries/ansible/aws/s3_bucket_with_all_permissions/test/positive_expected_result.json
- assets/queries/terraform/aws/s3_bucket_access_allowed_all/metadata.json
- assets/queries/terraform/aws/s3_bucket_access_allowed_all/query.rego
Updating the format for the policy attribute, and correcting some mistakes.
#1544 #1554 #482
Closes #1725
> Updating Queries with a Json Dict Policies to a different format

- assets/queries/ansible/gcp/log_min_duration_statement_wrong_value/metadata.json
- assets/queries/ansible/gcp/log_min_duration_statement_wrong_value/query.rego
- assets/queries/ansible/gcp/log_min_duration_statement_wrong_value/test/negative.yaml
- assets/queries/ansible/gcp/log_min_duration_statement_wrong_value/test/positive.yaml
- assets/queries/ansible/gcp/log_min_duration_statement_wrong_value/test/positive_expected_result.json
Closes #1715 
Check if we arent using '-1' in the flag 'log_min_duration_statement' in PostgreSQL database
> Add log_min_duration_statement_wrong_value query Closes #1715

- assets/queries/ansible/gcp/cloud_sql_instance_ssl_disabled/metadata.json
- assets/queries/ansible/gcp/cloud_sql_instance_ssl_disabled/query.rego
- assets/queries/ansible/gcp/cloud_sql_instance_ssl_disabled/test/negative.yaml
- assets/queries/ansible/gcp/cloud_sql_instance_ssl_disabled/test/positive.yaml
- assets/queries/ansible/gcp/cloud_sql_instance_ssl_disabled/test/positive_expected_result.json
GCP SQL Instance should have require SSL defined
Closes #1710
> Add Cloud SQL Instance SSL Disabled query #1710

- assets/queries/cloudFormation/ecs_without_running_tasks/metadata.json
- assets/queries/cloudFormation/ecs_without_running_tasks/query.rego
- assets/queries/cloudFormation/ecs_without_running_tasks/test/negative.yaml
- assets/queries/cloudFormation/ecs_without_running_tasks/test/positive.yaml
- assets/queries/cloudFormation/ecs_without_running_tasks/test/positive_expected_result.json
ECS Service should have at least 1 task running
Closes #1702
> Add ECS Service Without Running Tasks query #1702

- assets/queries/ansible/aws/all_Auth_Users_get_read_access/metadata.json
- cmd/console/main.go
Added flag generate-id (-g for short) in order to make possible to generate a UUID for the query creation.
Closes #670
> added cmd flag generate-id #670

- assets/queries/ansible/azure/aks_logging_to_azure_monitoring_disabled/metadata.json
- assets/queries/ansible/azure/aks_logging_to_azure_monitoring_disabled/query.rego
- assets/queries/ansible/azure/aks_logging_to_azure_monitoring_disabled/test/negative.yaml
- assets/queries/ansible/azure/aks_logging_to_azure_monitoring_disabled/test/positive.yaml
- assets/queries/ansible/azure/aks_logging_to_azure_monitoring_disabled/test/positive_expected_result.json
For this query, it is necessary to check if 'monitoring', 'enabled' and 'log_analytics_workspace_resource_id' is set. Furthermore, it is necessary to check  if "enabled' is set to 'true' or 'yes'
Closes #1736
> Add aks_logging_to_azure_monitoring_disabled query Closes #1736

- assets/queries/ansible/gcp/log_temp_files_wrong_value/metadata.json
- assets/queries/ansible/gcp/log_temp_files_wrong_value/query.rego
- assets/queries/ansible/gcp/log_temp_files_wrong_value/test/negative.yaml
- assets/queries/ansible/gcp/log_temp_files_wrong_value/test/positive.yaml
- assets/queries/ansible/gcp/log_temp_files_wrong_value/test/positive_expected_result.json
Closes #1712 
Check if we arent using '0' in the flag 'log_temp_files' in PostgreSQL database
> Add log_temp_files_wrong_value query Closes #1712

- assets/queries/ansible/azure/container_registry_with_no_locks/metadata.json
- assets/queries/ansible/azure/container_registry_with_no_locks/query.rego
- assets/queries/ansible/azure/container_registry_with_no_locks/test/negative.yaml
- assets/queries/ansible/azure/container_registry_with_no_locks/test/positive.yaml
- assets/queries/ansible/azure/container_registry_with_no_locks/test/positive_expected_result.json
Provide a azure_rm_containerregistry resource and a resource to manage the azure_rm_lock
Closes #1440
> Add Azurerm Container Registry With No Locks query

- assets/queries/ansible/aws/s3_bucket_without_encryption/metadata.json
- assets/queries/ansible/aws/s3_bucket_without_encryption/query.rego
- assets/queries/ansible/aws/s3_bucket_without_encryption/test/negative.yaml
- assets/queries/ansible/aws/s3_bucket_without_encryption/test/positive.yaml
- assets/queries/ansible/aws/s3_bucket_without_encryption/test/positive_expected_result.json
S3 bucket should have encryption defined
Closes #1624
> Add S3 Bucket Without Encryption query #1624

- assets/queries/dockerfile/unpinned_package_version_in_pip_install/metadata.json
- assets/queries/dockerfile/unpinned_package_version_in_pip_install/query.rego
- assets/queries/dockerfile/unpinned_package_version_in_pip_install/test/positive_expected_result.json
**Platform**
Docker
Query's metadata file has wrong values
Closes #1765
> Update metadata file of 'unpinned_package_version_in_pip_install' query for Docker

- pkg/builder/writer/rego.go
- pkg/builder/writer/rego_test.go
- pkg/engine/vulnerability_builder.go
- pkg/engine/vulnerability_builder_test.go
- pkg/kics/service.go
> fix sonarCloud issues with writer/rego #1751

- cmd/console/main.go
- pkg/model/summary.go
> Added Vulnerabilities Summary in Results.json File #1656

- assets/queries/ansible/azure/log_profile_captures_activities/metadata.json
- assets/queries/ansible/azure/log_profile_captures_activities/query.rego
- assets/queries/ansible/azure/log_profile_captures_activities/test/negative.yaml
- assets/queries/ansible/azure/log_profile_captures_activities/test/positive.yaml
- assets/queries/ansible/azure/log_profile_captures_activities/test/positive_expected_result.json
Monitoring log profile captures all the activities(Action, Write, Delete) #1759
> Add Monitoring Log Profile Captures All Activities query for Ansible #1759

- assets/queries/ansible/gcp/log_min_messages_invalid_value/metadata.json
- assets/queries/ansible/gcp/log_min_messages_invalid_value/query.rego
- assets/queries/ansible/gcp/log_min_messages_invalid_value/test/negative.yaml
- assets/queries/ansible/gcp/log_min_messages_invalid_value/test/positive.yaml
- assets/queries/ansible/gcp/log_min_messages_invalid_value/test/positive_expected_result.json
Closes #1714 
Check if we aren't using a valid value in the flag 'log_min_messages' in the PostgreSQL database
> Add log_min_messages_invalid_value query Closes #1714

- pkg/builder/engine/engine.go
- pkg/builder/parser/tag/tag_parser.go
- pkg/source/filesystem.go
Refractured functions  shown as issues in Sonar Cloud
Closes #1751
> Refractured functions 

- pkg/parser/docker/parser.go
> Improved Dockerfile parser for containers with the same image, but different alias #1777

- .editorconfig
_EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems._
https://editorconfig.org/
Closes #1780
> Project's editorconfig file

- assets/queries/ansible/aws/public_ecr_policy/metadata.json
- assets/queries/ansible/aws/public_ecr_policy/query.rego
- assets/queries/ansible/aws/public_ecr_policy/test/negative.yaml
- assets/queries/ansible/aws/public_ecr_policy/test/positive.yaml
- assets/queries/ansible/aws/public_ecr_policy/test/positive_expected_result.json
Provide a aws.ecs_ecr resource and a resource to manage the policy
Closes #1525
> Add Public ECR policy query

- codecov.yml
*Mocks and Tests files should be ignored from codecov tool*
https://docs.codecov.io/docs/ignoring-paths
Closes #1825
> Configure codecov to ignore tests and mocks files

- .github/workflows/go.yml
Closes #1788
- tweaking usage of GH action to publish unit tests results
> Tweaking unit tests report configuration

- assets/queries/ansible/aws/IAM_policies_attached_to_user/metadata.json
- assets/queries/ansible/aws/api_gateway_public_lambda/metadata.json
- assets/queries/ansible/aws/aws_alb_application_protocol_not_http/metadata.json
- assets/queries/ansible/aws/s3_bucket_with_public_access/metadata.json
- assets/queries/ansible/aws/s3_bucket_without_logging/metadata.json
- assets/queries/cloudFormation/aws_lambda_functions_tracing_disabled/metadata.json
- assets/queries/cloudFormation/iam_policy_on_user/metadata.json
- assets/queries/cloudFormation/workspace_without_encryption/metadata.json
- assets/queries/k8s/volume_mount_with_OS_directory_write_permissions/metadata.json
- test/main_test.go
- test/queries_content_test.go
Closes #1804
- Testing query metadata content.
> Improve query metadata.json unit tests

- internal/console/helpers_test.go
- internal/console/version.go
> updated version to v1.1.2

- cmd/builder/main.go
- internal/console/helpers.go
- internal/console/scan.go
- pkg/engine/query/source.go
- pkg/source/filesystem.go
- test/helpers.go
Closes #1860
- Fixes Gosec issues
> Fixed gosec issues #1860

- assets/queries/ansible/azure/sql_server_accessibility_is_not_minimal/query.rego
Closes #1868
- Added support for: `azure.azcollection.azure_rm_sqlfirewallrule`
> Update 'SQL Server Accessibility is Not Minimal' query for Ansible

- assets/queries/ansible/azure/sql_server_ingress_from_any_ip/query.rego
Closes #1870 
- Added support for module `azure_rm_sqlfirewallrule`
> Update 'SQLServer Ingress from Any IP' query for Ansible

- assets/queries/cloudFormation/ec2_public_instance_exposed_through_subnet/test/negative.yaml
- assets/queries/cloudFormation/ec2_public_instance_exposed_through_subnet/test/positive.yaml
- assets/queries/cloudFormation/unused_vpc/test/negative.yaml
- assets/queries/cloudFormation/unused_vpc/test/positive.yaml
- assets/queries/cloudFormation/vpc_attached_with_too_many_gateways/test/negative.yaml
Closes #1891 
- changed the names of the Resources, since when testing it joins the documents if the Resource has the same name the query would be counting all as one.
> Update VPC Attached With Too Many Gateways query for CloudFormation #1891

- assets/queries/ansible/azure/sql_server_with_public_access/query.rego
- assets/queries/ansible/azure/storage_account_forces_https/query.rego
- assets/queries/ansible/azure/storage_account_not_using_latest_tls_encryption_version/query.rego
Closes #1872 
- Added suport for module `azure_rm_sqlfirewallrule`
Closes #1874 
- Added suport for module `azure_rm_storageaccount`
Closes #1875 
- Added suport for module `azure.azcollection.azure_rm_storageaccount`
> Update queries for Ansible

- docs/CONTRIBUTING.md
- docs/about.md
- docs/index.md
- docs/queries.md
- docs/releases.md
- docs/results.md
- mkdocs.yml
- added query development info
- releases page
- minor fixes / updates to docs
> update docs with releases page and query development help

- .github/workflows/go-ci-publish-unit-tests.yml
- fixes publish unit test report in PR
> hotfix publish unit tests

- .github/workflows/go-ci-publish-unit-tests.yml
hotfix publish unit tests report
> hotfix publish unit tests report

- assets/queries/cloudFormation/cdn_configuration_missing/query.rego
Closes #1896
- The var properties in rule were checking for wrong values
> Changed properties var in query CDN Configuration Is Missing

- .github/workflows/go-ci-publish-unit-tests.yml
- .github/workflows/go-ci.yml
unit tests report comment on PR hotfix
> hotfix for unit tests report

- .gitignore
- go.mod
- go.sum
- internal/console/kics.go
- internal/console/scan.go
Closes #1833
- Added viper integration with cobra for kics to be able to load config from file with '--config'  flag
> Added --config flag to kics #1833

- .github/workflows/go-ci-publish-unit-tests.yml
hotfix for unit tests report PR comment CI job
> hotifix - unit tests PR comment

- .github/workflows/go-ci-publish-unit-tests.yml
> hotfix - unit tests report PR comment

- .github/workflows/go-ci-publish-unit-tests.yml
getting files and publishing it
> hotfix unit tests report publisher

- assets/queries/dockerfile/changing_default_shell_using_shell_command/test/negative.dockerfile
- assets/queries/dockerfile/changing_default_shell_using_shell_command/test/positive.dockerfile
- assets/queries/dockerfile/missing_zypper_clean/test/negative.dockerfile
- assets/queries/dockerfile/run_using_zypper_update/test/negative.dockerfile
- assets/queries/dockerfile/yum_update_disabled/test/negative.dockerfile
- assets/queries/dockerfile/yum_update_disabled/test/positive.dockerfile
Closes #1952 
- Change y- to -y
- Change zypper install -y httpd\>=2.4"  to "zypper install -y httpd=2.4",
> Update Docker Samples query for Docker #1952

- assets/queries/k8s/deployment_no_pod_anti_affinity/query.rego
- assets/queries/k8s/statefulset_no_pod_anti_affinity/query.rego
Closes #1923
- Removed duplicated rules from code
> Update queries for Kubernetes

- docs/about.md
- docs/architecture.md
- docs/index.md
- docs/integrations.md
> Fix images path to absolute path

- assets/libraries/k8s/library.rego
- assets/queries/k8s/default_namespace/query.rego
- assets/queries/k8s/default_namespace/test/negative.yaml
- assets/queries/k8s/default_namespace/test/positive.yaml
- assets/queries/k8s/default_namespace/test/positive_expected_result.json
- assets/queries/k8s/host_aliases_undefined_or_empty/query.rego
- assets/queries/k8s/host_aliases_undefined_or_empty/test/positive.yaml
- assets/queries/k8s/host_aliases_undefined_or_empty/test/positive_expected_result.json
- assets/queries/k8s/service_account_name_undefined_or_empty/query.rego
- assets/queries/k8s/service_account_name_undefined_or_empty/test/positive.yaml
- assets/queries/k8s/service_account_token_automount_not_disabled/query.rego
- assets/queries/k8s/service_account_token_automount_not_disabled/test/positive.yaml
- assets/queries/k8s/service_account_token_automount_not_disabled/test/positive_expected_result.json
Closes #1911
- Add curly brackets to correct the line when the name is nested (e.g: a.b.c)
- Add suported kinds
> Add restricted kinds #1911

- assets/queries/dockerfile/apt_get_without_yes_flag/query.rego
Closes #2003 
- Verify only the cases with "apt-get install" and consider flags between the command
> Update query "APT-GET Missing '-y' To Avoid Manual Input" for Docker Closes #2003

- assets/queries/terraform/azure/ad_admin_not_configured_for_sql_server/test/positive.tf
- assets/queries/terraform/azure/sql_audit_retention/test/negative.tf
Closes #2005 
- The query now gives a positive in this folder positive.tf
- Fixed a file that wasn't giving results
> Update ad_admin_not_configured_for_sql_server query Closes #2005

- docs/contributors.md
- mkdocs.yml
- Added page for contributors and appreciation
> added page for contributors and appreciation

- .github/workflows/go-ci-integration.yml
Closes #2024
- add `--no-progress` flag to integration tests
> Remove progress from integration tests execution

- pkg/engine/vulnerability_builder.go
- pkg/model/model.go
- pkg/model/summary.go
Closes #2016 
- Added platform field on JSON output for each vulnerability found
> Added platform to results output

- docs/contributors.md
- changes the listing of contributors to correct the wrong formatting
> corrected issues with listing of contributors

- assets/queries/k8s/containers_run_as_root/query.rego
Closes #2021 
- Update result block: Add curly brackets to correct the line when the name is nested (e.g: a.b.c) and update keys when issue type is "MissingAttribute".
- Add generic function to check kinds.
> Update Containers Running As Root query #2021

- pkg/kics/service.go
- pkg/source/filesystem.go
Closes #1399 
-Added a file size condition to prevent resource exhaustion
-
-
> File size limit applied

- internal/console/scan.go
- pkg/engine/inspector.go
- pkg/engine/inspector_test.go
- pkg/engine/similarity_id.go
- pkg/engine/similarity_id_test.go
- pkg/engine/vulnerability_builder.go
- pkg/engine/vulnerability_builder_test.go
- pkg/kics/service.go
- pkg/source/filesystem.go
- test/helpers.go
- test/main_test.go
- test/queries_content_test.go
- test/queries_test.go
- test/similarity_id_test.go
Fixes #1977
- computing SimilarityID using relative path to scanned file calculated from the scanned base directory
suggested fix by @nunoocx
> Progress on ComputeSimilarityID refactoring

- .github/workflows/go-ci.yml
Closes #2042
- run CI on MacOS
> Run tests on macOS

- .github/pull_request_template.md
> Add license reference to PR template

- docs/about.md
- docs/getting-started.md
- docs/queries.md
- docs/results.md
- Updated scan flags
- Updated queries docs, now queries supports multiple negative and positive files
- Updated results output
- Corrected checkmarx logo on about
> Updated docs to incorporate new features

- internal/console/version.go
> Updated version number

- pkg/engine/vulnerability_builder.go
- pkg/model/model.go
- pkg/model/summary.go
Closes #2059
-Added Description and category to results json
> Added desciption and category to results json #2059

- assets/queries/terraform/aws/fully_open_ingress/test/positive.tf
- assets/queries/terraform/aws/unknown_port_exposed_to_internet/metadata.json
- assets/queries/terraform/aws/unknown_port_exposed_to_internet/query.rego
- assets/queries/terraform/aws/unknown_port_exposed_to_internet/test/negative.tf
- assets/queries/terraform/aws/unknown_port_exposed_to_internet/test/positive.tf
- assets/queries/terraform/aws/unknown_port_exposed_to_internet/test/positive_expected_result.json
Closes #2017 
- Query now checks for positives in queries with multiple ingresses
- Fixed query giving a false positive in the 'fully_open_ingress' positive file
> Update unknown_port_exposed_to_internet Closes #2017

- assets/queries/ansible/aws/sqs_queue_exposed/query.rego
- assets/queries/ansible/aws/sqs_queue_exposed/test/positive.yaml
- assets/queries/ansible/aws/sqs_queue_exposed/test/positive_expected_result.json
Closes #2049
- query is now catching cases where there are several statements
> Update 'SQS Queue Exposed' query for Ansible

- assets/queries/cloudFormation/route_table_changes_without_alarms/query.rego
Closes #2072
- Corrected inconsistencies between "keyExpectedValues" and "keyActualValues".
> Update Route Table Changes Without Alarms query for AWS CloudFormation 

- assets/queries/cloudFormation/nacl_changes_without_alarms/query.rego
Closes #2069
- Corrected inconsistencies between "keyExpectedValues" and "keyActualValues".
> Update NACL Changes Without Alarms query for AWS CloudFormation 

- assets/queries/cloudFormation/management_console_without_alarms/query.rego
Closes #2067
- Corrected inconsistencies between "keyExpectedValues" and "keyActualValues".
> Update Management Console Without Alarms query for AWS CloudFormation 

- assets/queries/ansible/aws/IAM_Password_Without_Uppercase_letter/metadata.json
- assets/queries/ansible/aws/lambda_hardcoded_aws_access_key/metadata.json
- assets/queries/terraform/aws/iam_password_mininum_length/metadata.json
- assets/queries/terraform/aws/iam_password_missing_uppercase_letter/metadata.json
- assets/queries/terraform/aws/organizations_scp_full_access_is_enabled/metadata.json
- assets/queries/terraform/aws/rds_without_backup/metadata.json
- Changed IAM to Identity & Access Management
- Changed Backup and Disaster Recovery+ to Backup & Disaster Recovery
- Encryption & KeyManagement to Encryption & Key Management
Closes #
-
-
-
> Corrected some categories on metadata

- docs/configuration-file.md
- mkdocs.yml
Closes #2062 
- Added Documentation to --config flag
> added configuration file documentation #2062

- assets/queries/ansible/aws/iam_access_key_is_exposed/query.rego
Closes #2048
-The 'name' field is {{root}}, so it is not being detected
> Update query IAM Access Key Is Exposed #2048

- assets/queries/cloudFormation/rds_backup_retention_period_insufficient/query.rego
Closes #2098
- Correcting inconsistencies in several "keyExpectedValue" and "keyActualValue".
> Update RDS Backup Retention Period Insufficient query for AWS CloudFormation 

- assets/queries/cloudFormation/load_balancer_ssh_is_too_exposed/query.rego
Closes #2088
- Replaced "<" and ">" symbols in the keyExpectedValue and keyActualValue.
> Update Load Balancer SSH Too Exposed query for AWS CloudFormation 

- pkg/kics/service.go
Closes #2123
- removed line with problematic code 
> fixed bug by removing problematic line

- docs/roadmap.md
> Update roadmap.md - update till end of Q1

- assets/queries/ansible/azure/sensitive_port_is_exposed_to_entire_network/metadata.json
- assets/queries/ansible/azure/sensitive_port_is_exposed_to_entire_network/query.rego
- assets/queries/cloudFormation/ec2_sensitive_port_is_publicly_exposed/metadata.json
- assets/queries/cloudFormation/elb_sensitive_port_is_exposed_to_entire_network/metadata.json
- assets/queries/terraform/aws/sensitive_port_is_exposed_to_entire_network/metadata.json
- assets/queries/terraform/aws/sensitive_port_is_exposed_to_small_public_network/metadata.json
- assets/queries/terraform/azure/sensitive_port_is_exposed_to_entire_network/metadata.json
- assets/queries/terraform/azure/sensitive_port_is_exposed_to_small_public_network/metadata.json
- internal/tracker/ci.go
- internal/tracker/ci_test.go
- pkg/engine/inspector.go
- pkg/engine/inspector_test.go
- pkg/engine/query/source.go
- pkg/engine/query/source_test.go
- pkg/model/model.go
- test/fixtures/type-test01/template01/metadata.json
- we should account as our loaded queries the accumulated queries inside a same generic policy
> Counting generic queries with aggregation value on metadata

- docs/roadmap.md
> Update roadmap.md - added 2 more items for Q1

- pkg/kics/service.go
Closes #2156
- read file, 1MB at a time
- Max file size is 5 MB, bigger files will return error
- Refactored 'StartScan()' function for easier readability 
> fixed resource exhaustion vulnerability

- docs/integrations.md
- docs/integrations_azurepipelines.md
- docs/integrations_bitbucketpipelines.md
- mkdocs.yml
- adding bitbucket pipelines example to documentation
> Add bitbucket pipelines integration example to docs

- docs/roadmap.md
Closes #
- Inverts the roadmap view and adds release version info
> inverted the roadmap view and added release version info

- .github/workflows/go-ci.yml
- pkg/engine/vulnerability_builder.go
- Updated go-ci.yml
- Refactored vulnerability_builder, as suggested by @joaoReigota1 
> Updated go-ci and refactored vulnerability_builder

- .github/workflows/go-ci.yml
- Added go-sec workflow to go-ci
> Added go-sec workflow

- .github/workflows/nightly-release.yml
- .github/workflows/release.yml
Closes #2197
- using https://github.com/docker/build-push-action v2
> Docker image displays incorrect release version

- .github/workflows/nightly-release.yml
- .github/workflows/release.yml
Closes #
- fixing wrong secrets key `DOCKERHUB_USERNAME` to `DOCKER_USERNAME`
- fixing wrong secrets key `DOCKERHUB_PASSWORD` to `DOCKER_PASSWORD`
> Fixing releases credentials secrets

- docs/queries.md
- docs/releases.md
- Update categories list in documentation
- Small addition in releases
> Update categories in documentation

- .github/workflows/generate-queries-docs.yaml
> Download generate docs dependencies before running

- .github/workflows/generate-queries-docs.yaml
Closes #
- Creating pull request instead of committing to master after generation
> Creating pull request instead of committing to master after queries docs generation

- assets/queries/cloudFormation/iam_password_without_lowercase_letter/metadata.json
- test/helpers.go
- test/queries_content_test.go
Closes #2193
- Test metadata categories
> Add unit tests for checking queries categories 

- .github/workflows/release.yml
Fixing release workflow GH action
> Fixing release workflow GH action

- docs/index.md
- Update release version in docs
> Update index.md release versions to v1.2.0

- assets/queries/dockerfile/pip_install_keeping_cached_packages/query.rego
- assets/queries/dockerfile/pip_install_keeping_cached_packages/test/negative.dockerfile
- assets/queries/dockerfile/pip_install_keeping_cached_packages/test/positive.dockerfile
- assets/queries/dockerfile/pip_install_keeping_cached_packages/test/positive_expected_result.json
- assets/queries/dockerfile/unpinned_package_version_in_pip_install/query.rego
- assets/queries/dockerfile/unpinned_package_version_in_pip_install/test/negative.dockerfile
- assets/queries/dockerfile/unpinned_package_version_in_pip_install/test/positive.dockerfile
- assets/queries/dockerfile/unpinned_package_version_in_pip_install/test/positive_expected_result.json
Closes #2173
- Include pip3 in queries "Pip install Keeping Cached Packages" and "Unpinned Package Version in Pip Install"
- Add RUN ["param1, "param2", ...] case in the query "Pip install Keeping Cached Packages"
> Update pip queries for Docker #2173

- assets/queries/dockerfile/secrets_stored_in_dockerfile/query.rego
- assets/queries/dockerfile/secrets_stored_in_dockerfile/test/negative.dockerfile
- assets/queries/dockerfile/secrets_stored_in_dockerfile/test/positive.dockerfile
- assets/queries/dockerfile/secrets_stored_in_dockerfile/test/positive_expected_result.json
Closes #2195
- Considering flags "-p" and "--passwordfile" in run command
- Excluding cases like LABEL maintainer="Adam Bien, adam-bien.com" description="Keycloak Standalone server distribution"
> Update "Secrets Stored In Dockerfile" query for Docker Closes #2195

- assets/queries/dockerfile/update_instruction_alone/query.rego
- assets/queries/dockerfile/update_instruction_alone/test/negative.dockerfile
- assets/queries/dockerfile/update_instruction_alone/test/positive.dockerfile
- assets/queries/dockerfile/update_instruction_alone/test/positive_expected_result.json
Closes #2191
- Considering "--update"
- Excluding cases like "apk update && apk add git"
> Update "Update Instruction Alone" query for Docker Closes #2191

- assets/queries/k8s/service_account_allows_access_secrets/query.rego
- assets/queries/k8s/service_account_allows_access_secrets/test/positive_expected_result.json
Closes #2199
- Changed the index of the query, was getting all the resources, instead off the only "secrets" ones
> Updated ServiceAccount Allows Access Secrets query

- assets/queries/cloudFormation/cmk_unencrypted_storage/query.rego
- assets/queries/cloudFormation/cmk_unencrypted_storage/test/positive7.yaml
- assets/queries/cloudFormation/cmk_unencrypted_storage/test/positive8.json
- assets/queries/cloudFormation/cmk_unencrypted_storage/test/positive_expected_result.json
Closes #2149
- Changing the way to determine if a resource can host a database to a list, instead of using keywords;
- Added new samples;
- Deepened a searchKey.
> Update CMK Unencrypted Storage query for AWS CloudFormation 

- assets/queries/dockerfile/run_using_sudo/query.rego
- assets/queries/dockerfile/run_using_sudo/test/negative.dockerfile
- assets/queries/dockerfile/run_using_wget_and_curl/query.rego
- assets/queries/dockerfile/run_using_wget_and_curl/test/negative.dockerfile
- assets/queries/dockerfile/run_using_wget_and_curl/test/positive.dockerfile
- assets/queries/dockerfile/run_using_wget_and_curl/test/positive_expected_result.json
- assets/queries/dockerfile/run_utilities_and_posix_commands/query.rego
- assets/queries/dockerfile/run_utilities_and_posix_commands/test/negative.dockerfile
- assets/queries/dockerfile/run_utilities_and_posix_commands/test/positive.dockerfile
- assets/queries/dockerfile/run_utilities_and_posix_commands/test/positive_expected_result.json
Closes #2180
- "Run Using Sudo": excluding cases like "apt-get install sudo"
- "Run Using 'wget' and 'curl'": excluding cases like "apt-get install wget curl"
- "Run Utilities And POSIX Commands": excluding cases like "apt-get install vim nano"
> Correcting commands consideration in some queries for Docker Closes #2180

- assets/queries/dockerfile/apt_get_not_avoiding_additional_packages/query.rego
Closes #2184
- Excluding cases like "apt-get clean"
> Update "APT-GET Not Avoiding Additional Packages" query for Docker Closes #2184

- assets/queries/cloudFormation/alexa_skill_plaintext_client_secret_exposed/query.rego
- assets/queries/cloudFormation/api_gateway_deployment_without_access_log_setting/query.rego
- assets/queries/cloudFormation/api_gateway_deployment_without_api_gateway_usage_plan_associated/query.rego
- assets/queries/cloudFormation/api_gateway_stage_without_api_gateway_usage_plan_associated/query.rego
- assets/queries/cloudFormation/cdn_configuration_is_missing/query.rego
- assets/queries/cloudFormation/cloudfront_without_minimum_protocol_tls_1.2/query.rego
- assets/queries/cloudFormation/ec2_network_acl_overlapping_ports/query.rego
- assets/queries/cloudFormation/elb_v2_alb_access_log_disabled/query.rego
- assets/queries/cloudFormation/geo_restriction_disabled/query.rego
- assets/queries/cloudFormation/route53_without_record_set/query.rego
- assets/queries/cloudFormation/s3_bucket_should_have_bucket_policy/query.rego
- assets/queries/cloudFormation/s3_bucket_versioning_not_enabled/query.rego
- assets/queries/cloudFormation/s3_bucket_website_host_is_disabled/metadata.json
- assets/queries/cloudFormation/s3_bucket_website_host_is_disabled/query.rego
- assets/queries/cloudFormation/sns_topic_without_subscriber/query.rego
Closes #2246
Correcting typos found in queries:
- 7f8843f0-9ea5-42b4-a02b-753055113195
- e4f54ff4-d352-40e8-a096-5141073c37a2
- 24d932e1-91f0-46ea-836f-fdbd81694151
- 90501b1b-cded-4cc1-9e8b-206b85cda317
- a227ec01-f97a-4084-91a4-47b350c1db54
- ae53ce91-42b5-46bf-a84f-9a13366a4f13
- c62e8b7d-1fdf-4050-ac4c-76ba9e1d9621
- 37fa8188-738b-42c8-bf82-6334ea567738
- 77b6f1e2-bde4-4a6a-ae7e-a40659ff1576
- dc17ee4b-ddf2-4e23-96e8-7a36abad1303
- 7f8f1b60-43df-4c28-aa21-fb836dbd8071
- 783860a3-6dca-4c8b-81d0-7b62769ccbca
- 06ec63e3-9f72-4fe2-a218-2eb9200b8db5
- 3c3b7a58-b018-4d07-9444-d9ee7156e111
> Correcting typos in queries for AWS CloudFormation 

- assets/queries/cloudFormation/cloudfront_distribution_access_log_disabled/query.rego
- assets/queries/cloudFormation/ec2_instance_under_vpc/query.rego
- assets/queries/cloudFormation/iam_user_with_no_group/query.rego
- assets/queries/cloudFormation/sdb_domain_declared_as_a_resource/query.rego
- assets/queries/cloudFormation/vpc_has_flowlog_disabled/query.rego
Closes #2255
Changing the issue type to `MissingAttribute` in queries:
- f6d299d2-21eb-41cc-b1e1-fe12d857500b
- 06933df4-0ea7-461c-b9b5-104d27390e0e
- 6ea57c8b-f9c0-4ec7-bae3-bd75a9dee27d
- 8a6d36cd-0bc6-42b7-92c4-67acc8576861
- de77cd9f-0e8b-46cc-b4a4-b6b436838642
> Update queries with incorrect issue type for AWS CloudFormation 

- pkg/kics/service.go
Closes #2270
- Removed unnecessary file close
- 
> Fixed Filesystem couldn't close file bug #2270

- assets/queries/template/metadata.json
- pkg/engine/source/filesystem.go
Fixes #2272
- adding fake category to template metadata
- refactoring checkQueryExclude()
> Could not find metadata key warning in query template

- .github/workflows/nightly-release.yml
> fix nightly hash

- assets/queries/cloudFormation/api_gateway_deployment_without_access_log_setting/query.rego
Closes #2261
- Removing redundancies in the query.
> Update API Gateway Deployment Without Access Log Setting query for AWS CloudFormation 

- assets/queries/terraform/aws/no_password_policy_enabled/query.rego
- assets/queries/terraform/aws/no_password_policy_enabled/test/positive.tf
- assets/queries/terraform/aws/no_password_policy_enabled/test/positive_expected_result.json
Closes #2280
- Update the query to ignore acceptable missing attributes and updated the expected results accordingly.
> Ignore correct missing attributes. Closes #2280

- .github/workflows/update-docs-index.yaml
> Fixing bug in update docs index variables replace

- assets/queries/terraform/aws/guardduty_detector_disabled/query.rego
- assets/queries/terraform/aws/public_lambda_via_api_gateway/query.rego
- assets/queries/terraform/aws/public_lambda_via_api_gateway/test/positive_expected_result.json
- assets/queries/terraform/aws/rds_without_backup/query.rego
- assets/queries/terraform/aws/rds_without_backup/test/positive_expected_result.json
- assets/queries/terraform/aws/s3_bucket_with_all_permissions/query.rego
- assets/queries/terraform/aws/s3_bucket_with_all_permissions/test/positive_expected_result.json
- assets/queries/terraform/aws/sqs_policy_with_public_access/query.rego
- assets/queries/terraform/aws/sqs_policy_with_public_access/test/positive_expected_result.json
Closes #2294
- Removed unnecessary field `value` from the result output.
> Remove field 'value' from query's result

- docs/roadmap.md
Added more IaC to roadmap. Updated previous milestones
Closes #
-
-
-
> Added more IaC to roadmap. Updated previous milestones

- assets/queries/cloudFormation/rds_configuration_automatic_backup_disabled/query.rego
Closes #2344
- Correcting typo in keyExpectedValue and keyActualValue.
> Update AWS RDS Configuration Automatic Backup Disabled query for AWS CloudFormation 

- .gitignore
- go.sum
- bumping `go.sum` after `go mod tidy`
- add `bin` build directory to .gitignore
> Bumping go.sum, add bin to .gitignore

- assets/libraries/dockerfile/library.rego
- assets/queries/dockerfile/add_instead_of_copy/query.rego
- assets/queries/dockerfile/apt_get_install_pin_version_not_defined/query.rego
- assets/queries/dockerfile/apt_get_missing_yes_flag_to_avoid_manual_input/query.rego
- assets/queries/dockerfile/apt_get_not_avoiding_additional_packages/query.rego
- assets/queries/dockerfile/gem_install_without_version/query.rego
- assets/queries/dockerfile/missing_zypper_clean/query.rego
- assets/queries/dockerfile/missing_zypper_non_interactive_switch/query.rego
- assets/queries/dockerfile/run_using_upgrade_commands/query.rego
- assets/queries/dockerfile/secrets_stored_in_dockerfile/query.rego
- assets/queries/dockerfile/unpinned_package_version_in_apk_add/query.rego
- assets/queries/dockerfile/yum_install_allows_manual_input/query.rego
- assets/queries/dockerfile/yum_install_without_version/query.rego
- assets/queries/dockerfile/yum_update_disabled/query.rego
- assets/queries/dockerfile/zypper_install_without_version/query.rego
Closes #2325 
- Update library: Add ```arrayContains``` function
- General code cleaning
> Update library for Docker #2325

- README.md
- add docker pulls badge to readme
> add docker pulls badge to readme

- go.sum
- pkg/report/html.go
- Embedded report resource files
> Embedding report resource files

- .github/workflows/update-docs-index.yaml
- .github/workflows/update-docs-queries.yaml
- .github/workflows/update-godownloader-script.yaml
- when checked out a commit in a detached state the action must be provided with the master base branch in order to rebase
- renamed automatic PR branch
- remove branch by default after merge
> Fixing automatic docs update workflows

- docs/index.md
**Automated changes**
Triggered by SHA: _5bd5c77be6819e3a3254a5e06b88645164cdf6ab_
> Update documentation index page - 1.2.1

- .github/workflows/update-docs-index.yaml
> Fixing automatic docs update workflow missing v in tag

- assets/queries/cloudFormation/rds_db_cluster_storage_encryption_disabled/metadata.json
- assets/queries/cloudFormation/rds_db_cluster_storage_encryption_disabled/query.rego
Closes #2354
- Fixing typo and removing redundancies.
> Update RDS DBCluster Storage Encryption Disabled query for AWS CloudFormation 

- assets/queries/dockerfile/exposing_port_22/metadata.json
- assets/queries/dockerfile/exposing_port_22/query.rego
- assets/queries/dockerfile/exposing_port_22/test/negative.dockerfile
- assets/queries/dockerfile/exposing_port_22/test/positive.dockerfile
- assets/queries/dockerfile/exposing_port_22/test/positive_expected_result.json
Closes #2327
- Expose only the ports that the application needs and avoid exposing ports like SSH (22)
> Added Exposing Port 22 query

- assets/queries/cloudFormation/cloudtrail_logging_disabled/metadata.json
- assets/queries/cloudFormation/cloudtrail_logging_disabled/query.rego
- assets/queries/cloudFormation/cloudtrail_logging_disabled/test/negative1.yaml
- assets/queries/cloudFormation/cloudtrail_logging_disabled/test/negative2.json
- assets/queries/cloudFormation/cloudtrail_logging_disabled/test/positive1.yaml
- assets/queries/cloudFormation/cloudtrail_logging_disabled/test/positive2.json
- assets/queries/cloudFormation/cloudtrail_logging_disabled/test/positive_expected_result.json
Closes #2417 
- Add query for CloudFormation to check if CloudTrail logging is disabled
> Add query to check if CloudTrail logging is disabled. Closes #2417

- assets/queries/cloudFormation/redshift_cluster_logging_disabled/metadata.json
- assets/queries/cloudFormation/redshift_cluster_logging_disabled/query.rego
- assets/queries/cloudFormation/redshift_cluster_logging_disabled/test/negative1.yaml
- assets/queries/cloudFormation/redshift_cluster_logging_disabled/test/negative2.json
- assets/queries/cloudFormation/redshift_cluster_logging_disabled/test/positive1.yaml
- assets/queries/cloudFormation/redshift_cluster_logging_disabled/test/positive2.json
- assets/queries/cloudFormation/redshift_cluster_logging_disabled/test/positive_expected_result.json
Closes #2429 
- Add query to check if RedShift clusters have logging properties to enforce logging.
> Add query to check if redshift cluster has logging disabled. Closes #2429

- assets/queries/cloudFormation/mq_broker_is_publicly_accessible/metadata.json
- assets/queries/cloudFormation/mq_broker_is_publicly_accessible/query.rego
- assets/queries/cloudFormation/mq_broker_is_publicly_accessible/test/negative1.yaml
- assets/queries/cloudFormation/mq_broker_is_publicly_accessible/test/negative2.json
- assets/queries/cloudFormation/mq_broker_is_publicly_accessible/test/positive1.yaml
- assets/queries/cloudFormation/mq_broker_is_publicly_accessible/test/positive2.json
- assets/queries/cloudFormation/mq_broker_is_publicly_accessible/test/positive_expected_result.json
Closes #2432 
- Add query in CloudFormation to check if MQ Broker is publicly accessible.
> Add query to check if MQ Broker is publicly accessible. Closes #2432

- .github/workflows/nightly-release.yml
Closes #2469
- Nightly builds should only run when there are new commits since the last nightly
> Fixing nightly build workflow #2469

- assets/queries/terraform/kubernetes_pod/non_kube_system_pod_with_host_mount/metadata.json
- assets/queries/terraform/kubernetes_pod/non_kube_system_pod_with_host_mount/query.rego
- assets/queries/terraform/kubernetes_pod/non_kube_system_pod_with_host_mount/test/negative.tf
- assets/queries/terraform/kubernetes_pod/non_kube_system_pod_with_host_mount/test/positive.tf
- assets/queries/terraform/kubernetes_pod/non_kube_system_pod_with_host_mount/test/positive_expected_result.json
Closes #2381 
- Support Non Kube System Pod With Host Mount in Terraform (already exist in Kubernetes)
> Add Non Kube System Pod With Host Mount query Closes #2381

- assets/queries/terraform/kubernetes_pod/statefulset_requests_storage/metadata.json
- assets/queries/terraform/kubernetes_pod/statefulset_requests_storage/query.rego
- assets/queries/terraform/kubernetes_pod/statefulset_requests_storage/test/negative.tf
- assets/queries/terraform/kubernetes_pod/statefulset_requests_storage/test/positive.tf
- assets/queries/terraform/kubernetes_pod/statefulset_requests_storage/test/positive_expected_result.json
Closes #2395 
A StatefulSet requests volume storage.
> Add StatefulSet Requests Storage query #2395

- assets/queries/terraform/kubernetes_pod/image_pull_policy_of_container_is_not_always/metadata.json
- assets/queries/terraform/kubernetes_pod/image_pull_policy_of_container_is_not_always/query.rego
- assets/queries/terraform/kubernetes_pod/image_pull_policy_of_container_is_not_always/test/negative.tf
- assets/queries/terraform/kubernetes_pod/image_pull_policy_of_container_is_not_always/test/positive.tf
- assets/queries/terraform/kubernetes_pod/image_pull_policy_of_container_is_not_always/test/positive1.tf
- assets/queries/terraform/kubernetes_pod/image_pull_policy_of_container_is_not_always/test/positive2.tf
- assets/queries/terraform/kubernetes_pod/image_pull_policy_of_container_is_not_always/test/positive_expected_result.json
Closes #2405
- Image Pull Policy of the container must be defined and set to Always
> Added image_pull_policy Is Not Set To Always query

- assets/libraries/cloudformation/library.rego
- assets/queries/ansible/aws/config_rule_for_encrypted_volumes_is_disabled/metadata.json
- assets/queries/ansible/aws/config_rule_for_encrypted_volumes_is_disabled/test/positive_expected_result.json
- assets/queries/cloudFormation/config_rule_for_encryption_volumes_disabled/metadata.json
- assets/queries/cloudFormation/config_rule_for_encryption_volumes_disabled/query.rego
- assets/queries/cloudFormation/config_rule_for_encryption_volumes_disabled/test/negative1.yaml
- assets/queries/cloudFormation/config_rule_for_encryption_volumes_disabled/test/negative2.json
- assets/queries/cloudFormation/config_rule_for_encryption_volumes_disabled/test/positive1.yaml
- assets/queries/cloudFormation/config_rule_for_encryption_volumes_disabled/test/positive2.json
- assets/queries/cloudFormation/config_rule_for_encryption_volumes_disabled/test/positive_expected_result.json
- assets/queries/terraform/aws/config_rule_for_encrypted_volumes_is_disabled/metadata.json
- assets/queries/terraform/aws/config_rule_for_encrypted_volumes_is_disabled/test/positive_expected_result.json
Closes #2496 
- Add query support in CloudFormation, to check if there isn't a ConfigRule for Encrypted Volumes.
- Updated the query names to the unified names
> Add query to check if there isnt a ConfigRule for Encrypted Volumes. Closes #2496

- assets/queries/ansible/aws/lambda_permission_principal_is_wildcard/metadata.json
- assets/queries/ansible/aws/lambda_permission_principal_is_wildcard/query.rego
- assets/queries/ansible/aws/lambda_permission_principal_is_wildcard/test/negative.yaml
- assets/queries/ansible/aws/lambda_permission_principal_is_wildcard/test/positive.yaml
- assets/queries/ansible/aws/lambda_permission_principal_is_wildcard/test/positive_expected_result.json
- assets/queries/terraform/aws/lambda_permission_principal_is_wildcard/metadata.json
- assets/queries/terraform/aws/lambda_permission_principal_is_wildcard/query.rego
- assets/queries/terraform/aws/lambda_permission_principal_is_wildcard/test/negative.tf
- assets/queries/terraform/aws/lambda_permission_principal_is_wildcard/test/positive.tf
- assets/queries/terraform/aws/lambda_permission_principal_is_wildcard/test/positive_expected_result.json
Closes #2458
- Added a query that checks if the field `principal` contains a wildcard (*)
> Add 'Lambda Permission Principal Is Wildcard' query for Terraform and Ansible

- assets/queries/cloudFormation/http_port_open/metadata.json
- assets/queries/cloudFormation/http_port_open/query.rego
- assets/queries/cloudFormation/http_port_open/test/negative1.yaml
- assets/queries/cloudFormation/http_port_open/test/negative2.json
- assets/queries/cloudFormation/http_port_open/test/positive1.yaml
- assets/queries/cloudFormation/http_port_open/test/positive2.json
- assets/queries/cloudFormation/http_port_open/test/positive_expected_result.json
Closes #2556 
- Add "HTTP Port Open" query for CloudFormation
> Add "HTTP Port Open" query for CloudFormation #2556

- assets/queries/cloudFormation/remote_desktop_port_open/metadata.json
- assets/queries/cloudFormation/remote_desktop_port_open/query.rego
- assets/queries/cloudFormation/remote_desktop_port_open/test/negative1.yaml
- assets/queries/cloudFormation/remote_desktop_port_open/test/negative2.json
- assets/queries/cloudFormation/remote_desktop_port_open/test/positive1.yaml
- assets/queries/cloudFormation/remote_desktop_port_open/test/positive2.json
- assets/queries/cloudFormation/remote_desktop_port_open/test/positive_expected_result.json
Closes #2547 
- Add "Remote Desktop Port Open" query for CloudFormation
> Add "Remote Desktop Port Open" query for AWS CloudFormation #2547

- assets/queries/cloudFormation/msk_cluster_encryption_disabled/metadata.json
- assets/queries/cloudFormation/msk_cluster_encryption_disabled/query.rego
- assets/queries/cloudFormation/msk_cluster_encryption_disabled/test/negative1.yaml
- assets/queries/cloudFormation/msk_cluster_encryption_disabled/test/negative2.yaml
- assets/queries/cloudFormation/msk_cluster_encryption_disabled/test/negative3.json
- assets/queries/cloudFormation/msk_cluster_encryption_disabled/test/negative4.json
- assets/queries/cloudFormation/msk_cluster_encryption_disabled/test/positive1.yaml
- assets/queries/cloudFormation/msk_cluster_encryption_disabled/test/positive2.yaml
- assets/queries/cloudFormation/msk_cluster_encryption_disabled/test/positive3.yaml
- assets/queries/cloudFormation/msk_cluster_encryption_disabled/test/positive4.json
- assets/queries/cloudFormation/msk_cluster_encryption_disabled/test/positive5.json
- assets/queries/cloudFormation/msk_cluster_encryption_disabled/test/positive6.json
- assets/queries/cloudFormation/msk_cluster_encryption_disabled/test/positive_expected_result.json
Closes #2538 
- Add "MSK Cluster Encryption Disabled" query for CloudFormation
> Add "MSK Cluster Encryption Disabled" query for CloudFormation #2538

- assets/queries/terraform/kubernetes_pod/incorrect_volume_claim_access_mode_read_write_once/metadata.json
- assets/queries/terraform/kubernetes_pod/incorrect_volume_claim_access_mode_read_write_once/query.rego
- assets/queries/terraform/kubernetes_pod/incorrect_volume_claim_access_mode_read_write_once/test/negative.tf
- assets/queries/terraform/kubernetes_pod/incorrect_volume_claim_access_mode_read_write_once/test/positive.tf
- assets/queries/terraform/kubernetes_pod/incorrect_volume_claim_access_mode_read_write_once/test/positive_expected_result.json
Closes #2449 
Kubernetes Stateful Sets must have one Volume Claim template with the access mode 'ReadWriteOnce'
> Add Vol.Claim Access ReadWriteOnce query #2449

- assets/queries/cloudFormation/public_lambda_via_api_gateway/metadata.json
- assets/queries/cloudFormation/public_lambda_via_api_gateway/query.rego
- assets/queries/cloudFormation/public_lambda_via_api_gateway/test/negative1.yaml
- assets/queries/cloudFormation/public_lambda_via_api_gateway/test/negative2.json
- assets/queries/cloudFormation/public_lambda_via_api_gateway/test/positive1.yaml
- assets/queries/cloudFormation/public_lambda_via_api_gateway/test/positive2.json
- assets/queries/cloudFormation/public_lambda_via_api_gateway/test/positive_expected_result.json
Closes #2550 
- Add "Public Lambda via API Gateway" query for CloudFormation
> Add "Public Lambda via API Gateway" query for CloudFormation #2550

- assets/queries/terraform/kubernetes/container_host_ipc_is_true/metadata.json
- assets/queries/terraform/kubernetes/container_host_ipc_is_true/query.rego
- assets/queries/terraform/kubernetes/container_host_ipc_is_true/test/negative.tf
- assets/queries/terraform/kubernetes/container_host_ipc_is_true/test/positive.tf
- assets/queries/terraform/kubernetes/container_host_ipc_is_true/test/positive_expected_result.json
Closes #2580
- Container should not share the host IPC namespace
With this query, can we remove these one https://github.com/Checkmarx/kics/pull/2575?
> Add Shared Host IPC Namespace query

- assets/queries/terraform/kubernetes/psp_allows_containers_to_share_the_host_network_namespace/metadata.json
- assets/queries/terraform/kubernetes/psp_allows_containers_to_share_the_host_network_namespace/query.rego
- assets/queries/terraform/kubernetes/psp_allows_containers_to_share_the_host_network_namespace/test/negative.tf
- assets/queries/terraform/kubernetes/psp_allows_containers_to_share_the_host_network_namespace/test/positive.tf
- assets/queries/terraform/kubernetes/psp_allows_containers_to_share_the_host_network_namespace/test/positive_expected_result.json
Closes #2514
-Check if Pod Security Policies allow containers to share the host network namespace.
> Add query to check host_network terraform k8s

- assets/queries/terraform/kubernetes/ingress_controller_exposes_workload/metadata.json
- assets/queries/terraform/kubernetes/ingress_controller_exposes_workload/query.rego
- assets/queries/terraform/kubernetes/ingress_controller_exposes_workload/test/negative1.tf
- assets/queries/terraform/kubernetes/ingress_controller_exposes_workload/test/negative2.tf
- assets/queries/terraform/kubernetes/ingress_controller_exposes_workload/test/negative3.tf
- assets/queries/terraform/kubernetes/ingress_controller_exposes_workload/test/positive1.tf
- assets/queries/terraform/kubernetes/ingress_controller_exposes_workload/test/positive2.tf
- assets/queries/terraform/kubernetes/ingress_controller_exposes_workload/test/positive3.tf
- assets/queries/terraform/kubernetes/ingress_controller_exposes_workload/test/positive_expected_result.json
Closes #2572 
Ingress Controllers should not expose workload in order to avoid vulnerabilities and DoS attacks
> Add Ingress Exposes Workload query #2572

- assets/queries/cloudFormation/open_access_to_resources_through_api/metadata.json
- assets/queries/cloudFormation/open_access_to_resources_through_api/query.rego
- assets/queries/cloudFormation/open_access_to_resources_through_api/test/negative1.yaml
- assets/queries/cloudFormation/open_access_to_resources_through_api/test/negative2.json
- assets/queries/cloudFormation/open_access_to_resources_through_api/test/positive1.yaml
- assets/queries/cloudFormation/open_access_to_resources_through_api/test/positive2.json
- assets/queries/cloudFormation/open_access_to_resources_through_api/test/positive_expected_result.json
Closes #2522 
- Add "Open Access To Resources Through API" query for CloudFormation
> Add "Open Access To Resources Through API" query for CloudFormation #2522

- assets/queries/terraform/kubernetes_pod/shared_service_account/metadata.json
- assets/queries/terraform/kubernetes_pod/shared_service_account/query.rego
- assets/queries/terraform/kubernetes_pod/shared_service_account/test/negative.tf
- assets/queries/terraform/kubernetes_pod/shared_service_account/test/positive.tf
- assets/queries/terraform/kubernetes_pod/shared_service_account/test/positive_expected_result.json
Closes #2485
A Service Account token is shared between workloads.
> Add Shared Service Account query #2485

- assets/queries/cloudFormation/ecs_task_definition_network_mode_not_recommended/metadata.json
- assets/queries/cloudFormation/ecs_task_definition_network_mode_not_recommended/query.rego
- assets/queries/cloudFormation/ecs_task_definition_network_mode_not_recommended/test/negative1.yaml
- assets/queries/cloudFormation/ecs_task_definition_network_mode_not_recommended/test/negative2.json
- assets/queries/cloudFormation/ecs_task_definition_network_mode_not_recommended/test/positive1.yaml
- assets/queries/cloudFormation/ecs_task_definition_network_mode_not_recommended/test/positive2.json
- assets/queries/cloudFormation/ecs_task_definition_network_mode_not_recommended/test/positive_expected_result.json
Closes #2565
- Add query support in CloudFormation to check if Task Definition network mode is not the recommended
> Add query to check if task def network mode is not the recommended. Closes #2565

- assets/queries/cloudFormation/unknown_port_exposed_to_internet/metadata.json
- assets/queries/cloudFormation/unknown_port_exposed_to_internet/query.rego
- assets/queries/cloudFormation/unknown_port_exposed_to_internet/test/negative1.yaml
- assets/queries/cloudFormation/unknown_port_exposed_to_internet/test/negative2.json
- assets/queries/cloudFormation/unknown_port_exposed_to_internet/test/positive1.yaml
- assets/queries/cloudFormation/unknown_port_exposed_to_internet/test/positive2.json
- assets/queries/cloudFormation/unknown_port_exposed_to_internet/test/positive_expected_result.json
Closes #2566 
- Add "Unknown Port Exposed To Internet" query for CloudFormation
> Add "Unknown Port Exposed To Internet" query for CloudFormation #2566

- assets/queries/ansible/aws/iam_policies_attached_to_user/query.rego
- assets/queries/ansible/aws/iam_policies_attached_to_user/test/negative.yaml
- assets/queries/ansible/aws/iam_policies_attached_to_user/test/positive.yaml
Closes #2610
- Updating the query to consider "iam_policy" modules instead of "iam_managed_policy".
> Update IAM Policies Attached To User query for Ansible 

- .github/workflows/go-ci-integration.yml
- fix the incorrect path to info.log
> Archive integration tests logs

- assets/queries/terraform/azure/storage_account_not_using_latest_tls_encryption_version/metadata.json
- assets/queries/terraform/azure/storage_account_not_using_latest_tls_encryption_version/query.rego
- assets/queries/terraform/azure/storage_account_not_using_latest_tls_encryption_version/test/negative.tf
- assets/queries/terraform/azure/storage_account_not_using_latest_tls_encryption_version/test/positive.tf
- assets/queries/terraform/azure/storage_account_not_using_latest_tls_encryption_version/test/positive_expected_result.json
Closes #2596 
- Add "Storage Account Not Using Latest TLS Encryption Version" query for Terraform Azure;
> Add "Storage Account Not Using Latest TLS Encryption Version" query for Terraform #2596

- assets/queries/cloudFormation/kms_key_with_vulnerable_policy/metadata.json
- assets/queries/cloudFormation/kms_key_with_vulnerable_policy/query.rego
- assets/queries/cloudFormation/kms_key_with_vulnerable_policy/test/negative.json
- assets/queries/cloudFormation/kms_key_with_vulnerable_policy/test/negative.yaml
- assets/queries/cloudFormation/kms_key_with_vulnerable_policy/test/positive.json
- assets/queries/cloudFormation/kms_key_with_vulnerable_policy/test/positive.yaml
- assets/queries/cloudFormation/kms_key_with_vulnerable_policy/test/positive_expected_result.json
Closes #2625 
- Add "KMS Key With Vulnerable Policy" query for CloudFormation
> Add "KMS Key With Vulnerable Policy" query for CloudFormation #2625

- .github/workflows/go-ci-integration.yml
- docs/configuration-file.md
- docs/getting-started.md
- internal/console/kics.go
- internal/constants/constants.go
Closes #2628
- add `--log-path` flag
> Add --log-path flag

- .github/workflows/update-docs-index.yaml
- .github/workflows/update-docs-queries.yaml
- .github/workflows/update-godownloader-script.yaml
- Improving automatic PR's message
> Improving kicsbot PR message

- .github/workflows/go-ci-integration.yml
- .github/workflows/go-ci.yml
Closes #2677
- ignore `docs/** `and `README.md`
> Docs changes should not trigger CI #2677

- .github/workflows/nightly-release.yml
Nightly build is broken due to invalid syntax, refactoring conditionals to avoid many if statements
Closes #2686
- Using a pre-job check as output to control nightly releases
> Nightly build conditional refactor #2686

- Dockerfile.integration
this should avoid too many Dependabot PR's
> Removing patch from alpine semver in dockerfile

- .github/workflows/nightly-release.yml
> Nightly build conditional check syntax fix

- .github/new_changes.sh
- .github/workflows/nightly-release.yml
- Attempt to fix nightly build by wrapping check in shellscript
> Fixing nightly build workflow conditional

- .github/workflows/nightly-release.yml
> Fixing nightly build workflow

- internal/console/kics.go
- pkg/engine/source/filesystem.go
Closes #2694
- Fix gosec issues 
> fix gosec issues #2694

- docs/architecture.md
> Typo in architecture.md

- .github/workflows/nightly-release.yml
> Fixing nightly build docker version

- .github/workflows/go-ci-integration.yml
- cmd/console/main.go
- docs/getting-started.md
- docs/results.md
- internal/console/helpers/helpers.go
- internal/console/scan.go
- internal/constants/constants.go
- mkdocs.yml
> Revert "Add status code to results"

- docs/index.md
**Automated changes**
Triggered by SHA: _59eac1c08dd25208dc03561e6c1bef88646c1ec5_
> [kicsbot] Update documentation index page - 1.2.2

- .github/workflows/release-dkr-image.yml
- Adding manual trigger to docker release
> Adding manual trigger to docker release

- go.sum
- pkg/report/html.go
- pkg/report/template/html/report.css
- pkg/report/template/html/report.js
- pkg/report/template/html/report.tmpl
Closes #2723 
- Added a click on each shield and, when clicked, will hide all others result and only show the selected shield
> Added HTML report severity filter

- .github/pull_request_template.md
- .github/workflows/release-nightly.yml
Closes  #2747
- adding msteams nightly build notifications
> Adding nightly build msteams notifications #2747

- .github/workflows/init-versioning.yml
- .github/workflows/update-docs-index.yaml
- docs/js/version-mike.js
- mkdocs.yml
- Added docs versioning using mike 
- Updated CI workflows
> Added versioning and created mike workflow

- .github/workflows/go-ci-integration.yml
- .github/workflows/go-ci.yml
- .github/workflows/mkdocs.yml
- .github/workflows/release-dkr-image.yml
- .github/workflows/release.yml
Closes #2747
- Cancel the previous workflow in go-ci and integration
- Msteams notifications for releases
> CI improvements #2747

- assets/libraries/terraform/library.rego
- assets/queries/terraform/kubernetes/container_host_ipc_is_true/query.rego
- assets/queries/terraform/kubernetes/container_host_pid_is_true/query.rego
- assets/queries/terraform/kubernetes/container_is_privileged/query.rego
- assets/queries/terraform/kubernetes/container_resources_limits_undefined/query.rego
- assets/queries/terraform/kubernetes/container_with_added_capabilities/query.rego
- assets/queries/terraform/kubernetes/containers_with_sys_admin_capabilities/query.rego
- assets/queries/terraform/kubernetes/cpu_limits_not_set/query.rego
- assets/queries/terraform/kubernetes/cpu_requests_not_set/query.rego
- assets/queries/terraform/kubernetes/image_without_digest/query.rego
- assets/queries/terraform/kubernetes/invalid_image/query.rego
- assets/queries/terraform/kubernetes/memory_limits_not_defined/query.rego
- assets/queries/terraform/kubernetes/memory_requests_not_defined/query.rego
- assets/queries/terraform/kubernetes/net_raw_capabilities_not_being_dropped/query.rego
- assets/queries/terraform/kubernetes/no_drop_capabilities_for_containers/query.rego
- assets/queries/terraform/kubernetes/pod_or_container_without_security_context/query.rego
- assets/queries/terraform/kubernetes/privilege_escalation_allowed/query.rego
- assets/queries/terraform/kubernetes/readiness_probe_is_not_configured/query.rego
- assets/queries/terraform/kubernetes/root_container_not_mounted_as_read_only/query.rego
- assets/queries/terraform/kubernetes/secrets_as_environment_variables/query.rego
- assets/queries/terraform/kubernetes/shared_host_network_namespace/query.rego
- assets/queries/terraform/kubernetes/shared_service_account/query.rego
Closes #2757
- Add function 'getSpecInfo' to Terraform library
- Improving Terraform k8s queries that cover various types of resources
> Coverage different types of spec for Terraform k8s Closes#2757

- .github/workflows/update-docs-index.yaml
> Config git user before deploying docs gh-pages

- docs/index.md
**Automated changes**
Triggered by SHA: _a37e5294fb1e635b847474cbe83d3566e9774110_
> [kicsbot] Update documentation index page - 1.2.3

- docs/architecture.md
Closes #2730
- fixing docs preview in .md file
> Fixing arch docs img preview in .md files #2730

- .github/workflows/mkdocs.yml
- .github/workflows/update-docs-index.yaml
> Publishing mike changes after docs generation

- assets/queries/terraform/kubernetes/volume_mount_with_os_directory_write_permissions/query.rego
Closes #2778
- Cover different types of spec
> Update "Volume Mount With OS Directory Write Permissions" query for Terraform Closes #2778

- docs/usage/technologies.md
- mkdocs.yml
Closes #2788
- fixing typo in docs header
> fixing typo in technologies docs header fixes #2788

- .github/workflows/mkdocs.yml
- .github/workflows/update-docs-index.yaml
> Force pushing changes into mkdocs gh-pages branch

- docs/css/custom.css
- docs/js/version-mike.js
- When in mobile device, version select will be inside the dropdown menu
> Added version select to dropdown menu

- .github/workflows/release-nightly.yml
> pin go release version

- docs/usage/technologies.md
> Fixing technologies docs

- .github/workflows/mkdocs.yml
> Fixing docs publishing workflow

- docs/benchmark.md
> Testing docs changes workflow

- .github/workflows/update-docs-index.yaml
> Fixing publication workflow for releases

- mkdocs.yml
Closes #2814
- Adding OpenAPI to mkdocs queries menu bar
> Adding OpenAPI Queries Catalog Entry #2814

- pkg/model/sarif_categories.go
- test/queries_content_test.go
Closes #2821
- Adding new category `Structure and Semantics` to SARIF report and tests
> Add new category Structure and Semantics #2821

- .github/workflows/mkdocs.yml
> Fixing docs workflow for develop version

- .github/workflows/validate-ansible-samples.yml
- .github/workflows/validate-openapi-samples.yaml
- .github/yamllint_ansible.yml
- assets/queries/openAPI/security_empty_array/test/negative1.json
Closes #2831
- Add linters for OpenAPI samples
> Add linters for OpenAPI samples closes #2831

- internal/console/helpers/helpers.go
- internal/console/helpers/helpers_test.go
Closes #2839
- Increased package 'helpers' coverage to 82.7% 
> Increased package 'helpers' coverage to 82.7% #2839

- .github/workflows/release-dkr-image-for-tag.yml
> Adding manual docker push trigger

- assets/queries/openAPI/path_server_uses_http/metadata.json
- assets/queries/openAPI/path_server_uses_http/query.rego
- assets/queries/openAPI/path_server_uses_http/test/negative1.json
- assets/queries/openAPI/path_server_uses_http/test/negative2.yaml
- assets/queries/openAPI/path_server_uses_http/test/positive1.json
- assets/queries/openAPI/path_server_uses_http/test/positive2.yaml
- assets/queries/openAPI/path_server_uses_http/test/positive_expected_result.json
- go.sum
Closes #2819
- Added Path Server Object Uses HTTP query for OpenAPI 
> Added Path Server Object Uses HTTP query for OpenAPI #2819

- assets/queries/openAPI/global_server_uses_http/query.rego
- assets/queries/openAPI/path_server_uses_http/query.rego
- assets/queries/openAPI/security_empty_object_definition/metadata.json
- test/queries_content_test.go
> Fixing unit tests

- .github/workflows/go-ci-metrics.yaml
- .github/workflows/go-ci.yml
- Test metrics script should run for:
- pull requests
- pushes to master
> Test metrics script should also run on pushes to master

- .github/workflows/release-dkr-image-for-tag.yml
> Manual docker tag releaser

- .github/workflows/release-dkr-image-for-tag-latest.yml
- .github/workflows/release-dkr-image-for-tag.yml
> Feature manual docker tag releaser

- .github/workflows/release-dkr-image-for-tag.yml
> Manual docker image releaser

- .github/workflows/mkdocs.yml
> Greping for version-selector in generated docs

- .github/workflows/mkdocs.yml
> Troubleshooting mkdocs

- README.md
> Triggering docs deployment

- assets/queries/openAPI/servers_undefined/metadata.json
- assets/queries/openAPI/servers_undefined/query.rego
- assets/queries/openAPI/servers_undefined/test/negative1.json
- assets/queries/openAPI/servers_undefined/test/negative2.yaml
- assets/queries/openAPI/servers_undefined/test/positive1.json
- assets/queries/openAPI/servers_undefined/test/positive2.json
- assets/queries/openAPI/servers_undefined/test/positive3.yaml
- assets/queries/openAPI/servers_undefined/test/positive4.yaml
- assets/queries/openAPI/servers_undefined/test/positive_expected_result.json
Closes #2861
- Added "Servers Array Undefined" query for OpenAPI (it checks if servers array is undefined or empty)
> Added "Servers Array Undefined" query for OpenAPI Closes #2861

- assets/queries/openAPI/security_scheme_undefined/metadata.json
- assets/queries/openAPI/security_scheme_undefined/query.rego
- assets/queries/openAPI/security_scheme_undefined/test/negative1.json
- assets/queries/openAPI/security_scheme_undefined/test/negative2.yaml
- assets/queries/openAPI/security_scheme_undefined/test/positive1.json
- assets/queries/openAPI/security_scheme_undefined/test/positive2.json
- assets/queries/openAPI/security_scheme_undefined/test/positive3.json
- assets/queries/openAPI/security_scheme_undefined/test/positive4.yaml
- assets/queries/openAPI/security_scheme_undefined/test/positive5.yaml
- assets/queries/openAPI/security_scheme_undefined/test/positive6.yaml
- assets/queries/openAPI/security_scheme_undefined/test/positive_expected_result.json
Closes #2865
- Added query for undefined security scheme for Open API 3.0
> Added query for undefined security scheme

- assets/queries/openAPI/undefined_security_scope_global_security/metadata.json
- assets/queries/openAPI/undefined_security_scope_global_security/query.rego
- assets/queries/openAPI/undefined_security_scope_global_security/test/negative1.json
- assets/queries/openAPI/undefined_security_scope_global_security/test/negative2.json
- assets/queries/openAPI/undefined_security_scope_global_security/test/negative3.yaml
- assets/queries/openAPI/undefined_security_scope_global_security/test/negative4.yaml
- assets/queries/openAPI/undefined_security_scope_global_security/test/positive1.json
- assets/queries/openAPI/undefined_security_scope_global_security/test/positive2.json
- assets/queries/openAPI/undefined_security_scope_global_security/test/positive3.yaml
- assets/queries/openAPI/undefined_security_scope_global_security/test/positive4.yaml
- assets/queries/openAPI/undefined_security_scope_global_security/test/positive_expected_result.json
Closes #2896 
- Added query to check scopes on global security field
> Added "Undefined Scope 'securityScheme' On Global 'security' Field" query for OpenAPI #2896

- .github/scripts/get-coverage.py
- .github/workflows/go-ci-metrics.yaml
- .github/workflows/go-ci.yml
- Makefile
- docs/creating-queries.md
- docs/getting-started.md
- docs/queries.md
- e2e/README.md
- e2e/cli_test.go
- test/README.md
- Adding E2E README
- Adding go tests README
- Adding a script to calculate coverage and replace CodeCov: `Total coverage: 79.02748414376322%`
- Fixing and organizing makefile tasks
- Fixing existing docs
> Adding tests docs, fixing makefile tasks

- assets/queries/openAPI/response_object_incorrect_ref/metadata.json
- assets/queries/openAPI/response_object_incorrect_ref/query.rego
- assets/queries/openAPI/response_object_incorrect_ref/test/negative1.json
- assets/queries/openAPI/response_object_incorrect_ref/test/negative2.yaml
- assets/queries/openAPI/response_object_incorrect_ref/test/positive1.json
- assets/queries/openAPI/response_object_incorrect_ref/test/positive2.yaml
- assets/queries/openAPI/response_object_incorrect_ref/test/positive_expected_result.json
Closes #2911
- Added Response Object With Incorrect Ref query for OpenAPI 
> Added Response Object With Incorrect Ref query for OpenAPI #2911

- assets/queries/openAPI/request_body_incorrect_ref/metadata.json
- assets/queries/openAPI/request_body_incorrect_ref/query.rego
- assets/queries/openAPI/request_body_incorrect_ref/test/negative1.json
- assets/queries/openAPI/request_body_incorrect_ref/test/negative1.yaml
- assets/queries/openAPI/request_body_incorrect_ref/test/positive1.json
- assets/queries/openAPI/request_body_incorrect_ref/test/positive2.yaml
- assets/queries/openAPI/request_body_incorrect_ref/test/positive_expected_result.json
Closes #2920
- Added Request Body With Incorrect Ref query for OpenAPI 
> Added Request Body With Incorrect Ref query for OpenAPI #2920

- assets/queries/cloudFormation/api_gateway_stage_without_api_gateway_usage_plan_associated/test/positive_expected_result.json
- assets/queries/cloudFormation/ecs_service_admin_role_is_present/test/positive_expected_result.json
- assets/queries/cloudFormation/sagemaker_enabling_internet_access/test/positive_expected_result.json
- assets/queries/terraform/aws/default_vpc_exists/query.rego
- pkg/detector/helper.go
Closes #2933
- Fixed Bug with ExtractLineFragment
- Fixed Samples with wrong detect line due to bug
> Fixed Bug with ExtractLineFragment #2933

- assets/queries/openAPI/implicit_flow_oauth2/metadata.json
- assets/queries/openAPI/implicit_flow_oauth2/query.rego
- assets/queries/openAPI/implicit_flow_oauth2/test/negative1.json
- assets/queries/openAPI/implicit_flow_oauth2/test/negative2.yaml
- assets/queries/openAPI/implicit_flow_oauth2/test/positive1.json
- assets/queries/openAPI/implicit_flow_oauth2/test/positive2.json
- assets/queries/openAPI/implicit_flow_oauth2/test/positive3.json
- assets/queries/openAPI/implicit_flow_oauth2/test/positive4.yaml
- assets/queries/openAPI/implicit_flow_oauth2/test/positive5.yaml
- assets/queries/openAPI/implicit_flow_oauth2/test/positive6.yaml
- assets/queries/openAPI/implicit_flow_oauth2/test/positive_expected_result.json
Closes #2913 
- Added Implicit Flow in OAuth2 query for OpenAPI
> Added Implicit Flow in OAuth2 query for OpenAPI #2913

- .github/scripts/get-test-metrics.sh
> Fixing bug in queries metrics

- internal/console/generate_id.go
- Added New Line to command 'generate-id'
> Add New Line to command 'generate-id'

- .github/workflows/update-docs-index.yaml
> fix: update-docs-index workflow

- docs/index.md
**Automated changes**
Triggered by SHA: _7980df62f9ebba6350ec72b9169601569aeae0e4_
> [kicsbot] Update documentation index page - 1.2.4

- .github/workflows/update-docs-index.yaml
- .github/workflows/update-install-script.yaml
> fix post-release workflows

- .github/workflows/go-ci-coverage.yaml
> Troubleshooting coverage workflow

- .github/workflows/release-dkr-image.yml
> fix: docker release workflow

- docs/usage/commands.md
> fix: fixing usage documentation

- .github/workflows/go-ci-coverage.yaml
> fix: troubleshooting coverage workflow

- assets/queries/openAPI/security_field_undefined/metadata.json
- assets/queries/openAPI/security_field_undefined/query.rego
- assets/queries/openAPI/security_field_undefined/test/negative1.json
- assets/queries/openAPI/security_field_undefined/test/negative2.yaml
- assets/queries/openAPI/security_field_undefined/test/positive1.json
- assets/queries/openAPI/security_field_undefined/test/positive2.json
- assets/queries/openAPI/security_field_undefined/test/positive3.yaml
- assets/queries/openAPI/security_field_undefined/test/positive4.yaml
- assets/queries/openAPI/security_field_undefined/test/positive_expected_result.json
Closes #2986
- Added "Security Field Undefined" query for OpenAPI. It checks if a security field is not defined in '#/components/securitySchemes'
> feat(query): "Security Field Undefined" for OpenAPI (#2986)

- .github/scripts/get-digest.sh
- .github/workflows/release-dkr-image.yml
- .github/workflows/release-nightly.yml
> fix(ci): fixing docker release workflow

- assets/queries/openAPI/path_without_operation/metadata.json
- assets/queries/openAPI/path_without_operation/query.rego
- assets/queries/openAPI/path_without_operation/test/negative1.json
- assets/queries/openAPI/path_without_operation/test/negative2.yaml
- assets/queries/openAPI/path_without_operation/test/positive1.json
- assets/queries/openAPI/path_without_operation/test/positive2.yaml
- assets/queries/openAPI/path_without_operation/test/positive_expected_result.json
Closes #3013
- Added "Path Without Operation" query for OpenAPI (it checks if the path object is does not have at least one operation object defined)
> feat(query): "Path Without Operation" for OpenAPI (#3013)

- docs/index.md
Closes #3053 
- Updated contributing link
> fix(docs): updated contribute link

- .github/scripts/get-coverage.py
> fix(coverage): fixing test coverage

- .github/workflows/go-ci-coverage.yaml
- Makefile
Closes #
- Testing only with coverage mode on master branch
> fix(ci): test only with coverage mode on master check

- docs/dockerhub.md
> docs(dockerhub): update dockerhub docs for v2.0.0

- .github/scripts/get-coverage.py
- .github/workflows/go-ci-integration.yml
- disabling sentry in CI workflows
> feat(ci): disable sentry in CI workflows

- docs/index.md
Triggered by SHA: _fb248a8d8d57df9f1ded8eb1ac68a680a37e8ab4_
> docs(index): updating links in index page - 2.0.0

- .github/workflows/release-dkr-image.yml
> fix(ci): release docker image trigger

- docs/changes.md
- mkdocs.yml
- Added KICS v2.0.0 documentation
> docs(2.0) add docs new menu section describing changes in version 2.0

- .github/workflows/release-dkr-image.yml
> fix(ci): automated docker image release

- docs/index.md
Triggered by SHA: _e025565459e555db06c13b3f1e3bd6f7bcdaf990_
> docs(index): updating links in index page - 1.3.0

- docs/changes.md
- docs/dockerhub.md
- docs/index.md
- mkdocs.yml
- Corrected references from v2.0.0 to v1.3.0
> fix(docs): corrected references from v2.0.0 to v1.3.0

- internal/console/printer/printer.go
Closes #3003
- Fix flag --no-color not working with --verbose flag
> fix(cli): flag `--no-color` not working with `--verbose` flag #3003

- .github/workflows/mkdocs.yml
> fixing typo

- Makefile
> fix(ci): fixing makefile test tasks

- assets/queries/openAPI/schema_required_property_undefined/metadata.json
- assets/queries/openAPI/schema_required_property_undefined/query.rego
- assets/queries/openAPI/schema_required_property_undefined/test/negative1.json
- assets/queries/openAPI/schema_required_property_undefined/test/negative2.json
- assets/queries/openAPI/schema_required_property_undefined/test/negative3.yaml
- assets/queries/openAPI/schema_required_property_undefined/test/negative4.yaml
- assets/queries/openAPI/schema_required_property_undefined/test/positive1.json
- assets/queries/openAPI/schema_required_property_undefined/test/positive2.json
- assets/queries/openAPI/schema_required_property_undefined/test/positive3.yaml
- assets/queries/openAPI/schema_required_property_undefined/test/positive4.yaml
- assets/queries/openAPI/schema_required_property_undefined/test/positive_expected_result.json
Closes #3162 
- Added query to check if a required property is not defined
> feat(query): "Schema Has A Required Property Undefined" query for OpenAPI

- .github/workflows/update-docs-index.yaml
> fix(ci): fixed little typo

- assets/queries/openAPI/components_callback_definition_unused/metadata.json
- assets/queries/openAPI/components_callback_definition_unused/query.rego
- assets/queries/openAPI/components_callback_definition_unused/test/negative1.json
- assets/queries/openAPI/components_callback_definition_unused/test/negative2.yaml
- assets/queries/openAPI/components_callback_definition_unused/test/positive1.json
- assets/queries/openAPI/components_callback_definition_unused/test/positive2.yaml
- assets/queries/openAPI/components_callback_definition_unused/test/positive_expected_result.json
Closes #3177 
- Checks if all declared callbacks have references on API declaration
> feat(query): "Components Callback Definition Is Unused" query for OpenAPI #3177

- .github/workflows/go-ci.yml
> Fixing should_skip check

- .github/scripts/.coverageignore
- .github/scripts/get-coverage.py
- internal/metrics/metrics.go
- internal/metrics/metrics_test.go
- internal/tracker/ci_test.go
- pkg/engine/inspector_test.go
- pkg/scanner/scanner_test.go
- add unit testing to scanner pkg
> test(unit): add tests to scanner pkg to increase coverage

- assets/libraries/openapi/library.rego
- assets/queries/openAPI/components_callback_definition_unused/query.rego
- Refactor to create function for queries
> refactor(query): created `check_reference_exists` function for OpenAPI

- internal/metrics/metrics_test.go
> fix(test): fix mem metric unit testing

- .github/workflows/go-ci-integration.yml
- disable canceling other workflows for integration tests
> fix(ci): disable canceling other workflows

- assets/queries/openAPI/components_schema_definition_unused/metadata.json
- assets/queries/openAPI/components_schema_definition_unused/query.rego
- assets/queries/openAPI/components_schema_definition_unused/test/negative1.json
- assets/queries/openAPI/components_schema_definition_unused/test/negative2.yaml
- assets/queries/openAPI/components_schema_definition_unused/test/positive1.json
- assets/queries/openAPI/components_schema_definition_unused/test/positive2.yaml
- assets/queries/openAPI/components_schema_definition_unused/test/positive_expected_result.json
Closes #3236 
- Added "Components Schema Definition Is Unused" query for OpenAPI
> feat(query): added "Components Schema Definition Is Unused" query for OpenAPI

- internal/console/scan.go
Closes #3278 
- Refactor to change functions that not uses shorthand to correct functions
> feat(scan): refactor to remove unused shorthand field

- assets/libraries/openapi/library.rego
- assets/queries/openAPI/schema_required_property_undefined/query.rego
- assets/queries/openAPI/string_schema_without_maximum_length/query.rego
- Refactored some queries for OpenAPI
> refactor(query): using walk to reduce OpenAPI queries

- assets/queries/terraform/aws/rds_without_logging/metadata.json
- assets/queries/terraform/aws/rds_without_logging/query.rego
- assets/queries/terraform/aws/rds_without_logging/test/negative.tf
- assets/queries/terraform/aws/rds_without_logging/test/positive.tf
- assets/queries/terraform/aws/rds_without_logging/test/positive_expected_result.json
- Added "RDS Without Logging" query for Terraform
> feat(query): added "RDS Without Logging" query for Terraform

- assets/libraries/terraform/library.rego
- assets/queries/terraform/aws/neptune_logging_disabled/metadata.json
- assets/queries/terraform/aws/neptune_logging_disabled/query.rego
- assets/queries/terraform/aws/neptune_logging_disabled/test/negative1.tf
- assets/queries/terraform/aws/neptune_logging_disabled/test/positive1.tf
- assets/queries/terraform/aws/neptune_logging_disabled/test/positive_expected_result.json
- Added "Neptune Logging Is Disabled" query for Terraform
> feat(query): added "Neptune Logging Is Disabled" query for Terraform

- docs/roadmap.md
> docs(roadmap): updated roadmap with gRPC

- assets/queries/terraform/aws/global_accelerator_flow_logs_disabled/metadata.json
- assets/queries/terraform/aws/global_accelerator_flow_logs_disabled/query.rego
- assets/queries/terraform/aws/global_accelerator_flow_logs_disabled/test/negative1.tf
- assets/queries/terraform/aws/global_accelerator_flow_logs_disabled/test/positive1.tf
- assets/queries/terraform/aws/global_accelerator_flow_logs_disabled/test/positive2.tf
- assets/queries/terraform/aws/global_accelerator_flow_logs_disabled/test/positive3.tf
- assets/queries/terraform/aws/global_accelerator_flow_logs_disabled/test/positive_expected_result.json
- Added "Global Accelerator Flow Logs Disabled" query for Terraform
> feat(query): added "Global Accelerator Flow Logs Disabled" query for Terraform

- assets/queries/terraform/aws/docdb_logging_disabled/metadata.json
- assets/queries/terraform/aws/docdb_logging_disabled/query.rego
- assets/queries/terraform/aws/docdb_logging_disabled/test/negative1.tf
- assets/queries/terraform/aws/docdb_logging_disabled/test/positive1.tf
- assets/queries/terraform/aws/docdb_logging_disabled/test/positive2.tf
- assets/queries/terraform/aws/docdb_logging_disabled/test/positive3.tf
- assets/queries/terraform/aws/docdb_logging_disabled/test/positive4.tf
- assets/queries/terraform/aws/docdb_logging_disabled/test/positive_expected_result.json
- assets/queries/terraform/aws/neptune_logging_disabled/query.rego
- assets/queries/terraform/aws/neptune_logging_disabled/test/negative1.tf
- assets/queries/terraform/aws/neptune_logging_disabled/test/positive1.tf
- assets/queries/terraform/aws/neptune_logging_disabled/test/positive2.tf
- assets/queries/terraform/aws/neptune_logging_disabled/test/positive3.tf
- assets/queries/terraform/aws/neptune_logging_disabled/test/positive_expected_result.json
- Added "DocDB Logging Is Disabled" query for Terraform
- Corrected neptune query for Terraform
-
> feat(query): added "DocDB Logging Is Disabled" query for Terraform

- assets/queries/terraform/aws/eks_cluster_log_disabled/metadata.json
- assets/queries/terraform/aws/eks_cluster_log_disabled/query.rego
- assets/queries/terraform/aws/eks_cluster_log_disabled/test/negative1.tf
- assets/queries/terraform/aws/eks_cluster_log_disabled/test/positive1.tf
- assets/queries/terraform/aws/eks_cluster_log_disabled/test/positive_expected_result.json
- Added "EKS cluster logging is not enabled" query for Terraform
> feat(query): added "EKS cluster logging is not enabled" query for Terraform

- assets/queries/terraform/aws/alb_listening_on_http/query.rego
- assets/queries/terraform/aws/alb_listening_on_http/test/negative1.tf
- assets/queries/terraform/aws/alb_listening_on_http/test/negative2.tf
- assets/queries/terraform/aws/alb_listening_on_http/test/positive1.tf
- assets/queries/terraform/aws/alb_listening_on_http/test/positive2.tf
- assets/queries/terraform/aws/alb_listening_on_http/test/positive_expected_result.json
Closes #3203
- Updated "ALB Listening on HTTP" query for Terraform. It also checks the resource 'aws_lb_target_group'
> feat(query): update "ALB Listening on HTTP" for Terraform (#3203)

- assets/queries/terraform/aws/workspaces_workspace_volume_not_encrypted/metadata.json
- assets/queries/terraform/aws/workspaces_workspace_volume_not_encrypted/query.rego
- assets/queries/terraform/aws/workspaces_workspace_volume_not_encrypted/test/negative1.tf
- assets/queries/terraform/aws/workspaces_workspace_volume_not_encrypted/test/positive1.tf
- assets/queries/terraform/aws/workspaces_workspace_volume_not_encrypted/test/positive2.tf
- assets/queries/terraform/aws/workspaces_workspace_volume_not_encrypted/test/positive3.tf
- assets/queries/terraform/aws/workspaces_workspace_volume_not_encrypted/test/positive4.tf
- assets/queries/terraform/aws/workspaces_workspace_volume_not_encrypted/test/positive_expected_result.json
- Added Workspaces Workspace Volume Not Encrypted query for Terraform
AWS Workspaces Workspace data stored in volumes should be encrypted
> feat(query): Added Workspaces Workspace Volume Not Encrypted query for Terraform

- assets/queries/openAPI/json_reference_does_not_exists_header/metadata.json
- assets/queries/openAPI/json_reference_does_not_exists_header/query.rego
- assets/queries/openAPI/json_reference_does_not_exists_header/test/negative1.json
- assets/queries/openAPI/json_reference_does_not_exists_header/test/negative2.yaml
- assets/queries/openAPI/json_reference_does_not_exists_header/test/positive1.json
- assets/queries/openAPI/json_reference_does_not_exists_header/test/positive2.yaml
- assets/queries/openAPI/json_reference_does_not_exists_header/test/positive_expected_result.json
- Added "Header JSON Reference Does Not Exists" for OpenAPI
> feat(query): added "Header JSON Reference Does Not Exists" for OpenAPI

- assets/queries/openAPI/json_reference_does_not_exists_link/metadata.json
- assets/queries/openAPI/json_reference_does_not_exists_link/query.rego
- assets/queries/openAPI/json_reference_does_not_exists_link/test/negative1.json
- assets/queries/openAPI/json_reference_does_not_exists_link/test/negative2.yaml
- assets/queries/openAPI/json_reference_does_not_exists_link/test/positive1.json
- assets/queries/openAPI/json_reference_does_not_exists_link/test/positive2.yaml
- assets/queries/openAPI/json_reference_does_not_exists_link/test/positive_expected_result.json
- Added "Link JSON Reference Does Not Exists" for OpenAPI
> feat(query): added "Link JSON Reference Does Not Exists" for OpenAPI

- assets/queries/openAPI/json_reference_does_not_exists_request_body/metadata.json
- assets/queries/openAPI/json_reference_does_not_exists_request_body/query.rego
- assets/queries/openAPI/json_reference_does_not_exists_request_body/test/negative1.json
- assets/queries/openAPI/json_reference_does_not_exists_request_body/test/negative2.yaml
- assets/queries/openAPI/json_reference_does_not_exists_request_body/test/positive1.json
- assets/queries/openAPI/json_reference_does_not_exists_request_body/test/positive2.yaml
- assets/queries/openAPI/json_reference_does_not_exists_request_body/test/positive_expected_result.json
- Added "Request Body JSON Reference Does Not Exists" query for OpenAPI
> feat(query): add "Request Body JSON Reference Does Not Exists" query for OpenAPI

- assets/queries/openAPI/json_reference_does_not_exists_schema/metadata.json
- assets/queries/openAPI/json_reference_does_not_exists_schema/query.rego
- assets/queries/openAPI/json_reference_does_not_exists_schema/test/negative1.json
- assets/queries/openAPI/json_reference_does_not_exists_schema/test/negative2.yaml
- assets/queries/openAPI/json_reference_does_not_exists_schema/test/positive1.json
- assets/queries/openAPI/json_reference_does_not_exists_schema/test/positive2.yaml
- assets/queries/openAPI/json_reference_does_not_exists_schema/test/positive_expected_result.json
- Added "Schema JSON Reference Does Not Exists" query for OpenAPI
> feat(query): added "Schema JSON Reference Does Not Exists" query for OpenAPI

- assets/queries/openAPI/json_reference_does_not_exists_response/metadata.json
- assets/queries/openAPI/json_reference_does_not_exists_response/query.rego
- assets/queries/openAPI/json_reference_does_not_exists_response/test/negative1.json
- assets/queries/openAPI/json_reference_does_not_exists_response/test/negative2.yaml
- assets/queries/openAPI/json_reference_does_not_exists_response/test/positive1.json
- assets/queries/openAPI/json_reference_does_not_exists_response/test/positive2.yaml
- assets/queries/openAPI/json_reference_does_not_exists_response/test/positive_expected_result.json
- Added "Response JSON Reference Does Not Exists" query for OpenAPI
> feat(query): add "Response JSON Reference Does Not Exists" query for OpenAPI

- assets/libraries/openapi/library.rego
- assets/queries/openAPI/json_reference_does_not_exists_parameter/metadata.json
- assets/queries/openAPI/json_reference_does_not_exists_parameter/query.rego
- assets/queries/openAPI/json_reference_does_not_exists_parameter/test/negative1.json
- assets/queries/openAPI/json_reference_does_not_exists_parameter/test/negative2.yaml
- assets/queries/openAPI/json_reference_does_not_exists_parameter/test/positive1.json
- assets/queries/openAPI/json_reference_does_not_exists_parameter/test/positive2.yaml
- assets/queries/openAPI/json_reference_does_not_exists_parameter/test/positive_expected_result.json
Closes #
- Added "Parameter JSON Reference Does Not Exists" for OpenAPI
> feat(query): added "Parameter JSON Reference Does Not Exists" for OpenAPI

- assets/queries/openAPI/oauth2_with_implicit_flow/metadata.json
- assets/queries/openAPI/oauth2_with_implicit_flow/query.rego
- assets/queries/openAPI/oauth2_with_implicit_flow/test/negative1.json
- assets/queries/openAPI/oauth2_with_implicit_flow/test/negative2.yaml
- assets/queries/openAPI/oauth2_with_implicit_flow/test/positive1.json
- assets/queries/openAPI/oauth2_with_implicit_flow/test/positive2.yaml
- assets/queries/openAPI/oauth2_with_implicit_flow/test/positive_expected_result.json
- Added OAuth2 With Implicit Flow query to OpenAPI
OAuth2 implicit flow is vulnerable to access token leakage and access token replay
> feat(query): Added OAuth2 With Implicit Flow query to OpenAPI

- assets/queries/openAPI/oauth2_with_password_flow/metadata.json
- assets/queries/openAPI/oauth2_with_password_flow/query.rego
- assets/queries/openAPI/oauth2_with_password_flow/test/negative1.json
- assets/queries/openAPI/oauth2_with_password_flow/test/negative2.yaml
- assets/queries/openAPI/oauth2_with_password_flow/test/positive1.json
- assets/queries/openAPI/oauth2_with_password_flow/test/positive2.yaml
- assets/queries/openAPI/oauth2_with_password_flow/test/positive_expected_result.json
- OAuth2 With Password Flow
OAuth2 password flow insecurely exposes the credentials of the resource owner to the client
> feat(query): Added OAuth2 With Password Flow query to OpenAPI

- assets/queries/openAPI/schema_array_items_has_no_type/metadata.json
- assets/queries/openAPI/schema_array_items_has_no_type/query.rego
- assets/queries/openAPI/schema_array_items_has_no_type/test/negative1.json
- assets/queries/openAPI/schema_array_items_has_no_type/test/negative2.yaml
- assets/queries/openAPI/schema_array_items_has_no_type/test/positive1.json
- assets/queries/openAPI/schema_array_items_has_no_type/test/positive2.json
- assets/queries/openAPI/schema_array_items_has_no_type/test/positive3.json
- assets/queries/openAPI/schema_array_items_has_no_type/test/positive4.yaml
- assets/queries/openAPI/schema_array_items_has_no_type/test/positive5.yaml
- assets/queries/openAPI/schema_array_items_has_no_type/test/positive6.yaml
- assets/queries/openAPI/schema_array_items_has_no_type/test/positive_expected_result.json
- Added "Schema Array Items Has No Type" query for OpenAPI
> feat(query): added "Schema Array Items Has No Type" query for OpenAPI

- assets/queries/openAPI/global_security_scheme_using_basic_authentication/metadata.json
- assets/queries/openAPI/global_security_scheme_using_basic_authentication/query.rego
- assets/queries/openAPI/global_security_scheme_using_basic_authentication/test/negative1.json
- assets/queries/openAPI/global_security_scheme_using_basic_authentication/test/negative2.yaml
- assets/queries/openAPI/global_security_scheme_using_basic_authentication/test/positive1.json
- assets/queries/openAPI/global_security_scheme_using_basic_authentication/test/positive2.yaml
- assets/queries/openAPI/global_security_scheme_using_basic_authentication/test/positive_expected_result.json
- Checks if securityScheme is set as basic authentication
> feat(query): add "Global Security Scheme Using Basic Authentication" for OpenAPI

- assets/queries/openAPI/security_scheme_using_http_basic/metadata.json
- assets/queries/openAPI/security_scheme_using_http_basic/query.rego
- assets/queries/openAPI/security_scheme_using_http_basic/test/negative1.json
- assets/queries/openAPI/security_scheme_using_http_basic/test/negative2.yaml
- assets/queries/openAPI/security_scheme_using_http_basic/test/positive1.json
- assets/queries/openAPI/security_scheme_using_http_basic/test/positive2.yaml
- assets/queries/openAPI/security_scheme_using_http_basic/test/positive_expected_result.json
- Added Security Scheme Using HTTP Basic query for OpenAPI
Security Scheme HTTP should not be using basic authentication
> feat(query): Added Security Scheme Using HTTP Basic query for OpenAPI

- assets/queries/openAPI/security_scheme_using_http_digest/metadata.json
- assets/queries/openAPI/security_scheme_using_http_digest/query.rego
- assets/queries/openAPI/security_scheme_using_http_digest/test/negative1.json
- assets/queries/openAPI/security_scheme_using_http_digest/test/negative2.yaml
- assets/queries/openAPI/security_scheme_using_http_digest/test/positive1.json
- assets/queries/openAPI/security_scheme_using_http_digest/test/positive2.yaml
- assets/queries/openAPI/security_scheme_using_http_digest/test/positive_expected_result.json
- Added Security Scheme Using HTTP Digest query for OpenAPI
Security Scheme HTTP should not be using digest authentication
> feat(query): Added Security Scheme Using HTTP Digest query for OpenAPI

- assets/queries/openAPI/required_property_default_value/metadata.json
- assets/queries/openAPI/required_property_default_value/query.rego
- assets/queries/openAPI/required_property_default_value/test/negative1.json
- assets/queries/openAPI/required_property_default_value/test/negative2.json
- assets/queries/openAPI/required_property_default_value/test/negative3.yaml
- assets/queries/openAPI/required_property_default_value/test/negative4.yaml
- assets/queries/openAPI/required_property_default_value/test/positive1.json
- assets/queries/openAPI/required_property_default_value/test/positive2.json
- assets/queries/openAPI/required_property_default_value/test/positive3.yaml
- assets/queries/openAPI/required_property_default_value/test/positive4.yaml
- assets/queries/openAPI/required_property_default_value/test/positive_expected_result.json
- Added "Required Property With Default Value" query for OpenAPI
> feat(query): added "Required Property With Default Value" query for OpenAPI

- assets/queries/openAPI/json_ref_alongside_properties/metadata.json
- assets/queries/openAPI/json_ref_alongside_properties/query.rego
- assets/queries/openAPI/json_ref_alongside_properties/test/negative1.json
- assets/queries/openAPI/json_ref_alongside_properties/test/negative2.yaml
- assets/queries/openAPI/json_ref_alongside_properties/test/positive1.json
- assets/queries/openAPI/json_ref_alongside_properties/test/positive2.yaml
- assets/queries/openAPI/json_ref_alongside_properties/test/positive_expected_result.json
- Added "JSON '$ref' alongside other properties" query for OpenAPI
> feat(query): added "JSON '$ref' alongside other properties" query for OpenAPI

- assets/queries/openAPI/schema_invalid_number_format/metadata.json
- assets/queries/openAPI/schema_invalid_number_format/query.rego
- assets/queries/openAPI/schema_invalid_number_format/test/negative1.json
- assets/queries/openAPI/schema_invalid_number_format/test/negative2.yaml
- assets/queries/openAPI/schema_invalid_number_format/test/positive1.json
- assets/queries/openAPI/schema_invalid_number_format/test/positive2.yaml
- assets/queries/openAPI/schema_invalid_number_format/test/positive_expected_result.json
- Added "Schema Invalid Number Format" for OpenAPI
> feat(query): added "Schema Invalid Number Format" for OpenAPI

- .github/workflows/go-ci-metrics.yaml
> fix(ci): wrong paths filter

- assets/queries/openAPI/example_not_compliant_with_schema_type/query.rego
> Update Example Not Compliant With Schema Type

- assets/queries/openAPI/schema_type_invalid_property/metadata.json
- assets/queries/openAPI/schema_type_invalid_property/query.rego
- assets/queries/openAPI/schema_type_invalid_property/test/negative1.json
- assets/queries/openAPI/schema_type_invalid_property/test/negative2.yaml
- assets/queries/openAPI/schema_type_invalid_property/test/positive1.json
- assets/queries/openAPI/schema_type_invalid_property/test/positive2.json
- assets/queries/openAPI/schema_type_invalid_property/test/positive3.json
- assets/queries/openAPI/schema_type_invalid_property/test/positive4.yaml
- assets/queries/openAPI/schema_type_invalid_property/test/positive5.yaml
- assets/queries/openAPI/schema_type_invalid_property/test/positive6.yaml
- assets/queries/openAPI/schema_type_invalid_property/test/positive_expected_result.json
- Added "Schema Type Has Invalid Keyword" query for OpenAPI
> feat(query): added "Schema Type Has Invalid Keyword" query for OpenAPI

- .github/workflows/go-ci-metrics.yaml
> fix(ci): publish queries count badge

- docs/index.md
Triggered by SHA: _f11a07676853de27355a4837128bcce2bb2305d6_
> docs(index): updating links in index page - 1.3.1

- assets/queries/openAPI/parameter_object_undefined_type/test/positive_expected_result.json
- pkg/detector/helper.go
- pkg/detector/helper_test.go
Closes #3386
- Fixed bug with Detect line does not work for OpenAPI template path #3386
> fix(detect-line): Fixed bug with Detect line does not work for OpenAPI template path #3386

- docs/integrations_ghactions.md
Closes #3393
- fixing GitHub actions integration documentation with latest v1.2 action changes
> docs(integrations): fixing github actions docs closes #3393

- README.md
> docs(README): adding MacOS to release process topic

- assets/queries/dockerfile/workdir_path_not_absolute/query.rego
- assets/queries/dockerfile/workdir_path_not_absolute/test/negative.dockerfile
Closes #3390 
- Changed regex to match `/` pattern
> fix(query): issue with '/' on absolute path query from dockerfile

- docs/js/custom.js
- internal/console/scan.go
- pkg/engine/provider/filesystem.go
- pkg/parser/terraform/converter/default.go
- pkg/parser/terraform/terraform.go
- pkg/report/html.go
- pkg/report/template/html/report.js
- pkg/resolver/helm/resolver.go
- test/helpers.go
- Fixed Code smells (GetSources() from pkg/engine/provider/filesystem.go)
> fix(quality): Fixed Code smells 

- docs/BADGE.md
- docs/usage/technologies.md
- mkdocs.yml
- add badge creation instructions
- add OpenAPI under technologies
> docs(badge): add badge creation instructions

- assets/queries/terraform/azure/vault_auditing_disabled/query.rego
- assets/queries/terraform/azure/vault_auditing_disabled/test/positive.tf
Closes #3285
- Updated "Vault Auditing Disabled" query for Terraform. Now, it searches in the entire project instead of in each Terraform sample
> feat(query): update "Vault Auditing Disabled" for Terraform (#3285)

- assets/queries/openAPI/path_template_empty/metadata.json
- assets/queries/openAPI/path_template_empty/query.rego
- assets/queries/openAPI/path_template_empty/test/negative1.yaml
- assets/queries/openAPI/path_template_empty/test/negative2.json
- assets/queries/openAPI/path_template_empty/test/positive1.yaml
- assets/queries/openAPI/path_template_empty/test/positive2.json
- assets/queries/openAPI/path_template_empty/test/positive_expected_result.json
- Added "Path Template is Empty" query for OpenAPI. It checks if there is some path template set as empty
> feat(query): add "Path Template is Empty" for OpenAPI

- assets/libraries/common/library.rego
Updated Passwords And Secrets In Infrastructure Code query for Dockerfile
Closes #3389 
- Added 'version, make, arch' to common values and key so it doesn't return a result
> update(query): Updated Passwords And Secrets In Infrastructure Code 

- docs/dockerhub.md
- docs/usage/commands.md
- e2e/fixtures/E2E_CLI_002
- e2e/fixtures/E2E_CLI_003
- e2e/fixtures/E2E_CLI_004
- e2e/fixtures/E2E_CLI_010
- e2e/fixtures/E2E_CLI_016_INVALID_SCAN_FLAG
- e2e/utils.go
- internal/console/scan.go
> docs(cli): updating usage help text with --include-queries

- assets/queries/openAPI/properties_missing_required_property/metadata.json
- assets/queries/openAPI/properties_missing_required_property/query.rego
- assets/queries/openAPI/properties_missing_required_property/test/negative1.json
- assets/queries/openAPI/properties_missing_required_property/test/negative2.yaml
- assets/queries/openAPI/properties_missing_required_property/test/negative3.json
- assets/queries/openAPI/properties_missing_required_property/test/negative4.yaml
- assets/queries/openAPI/properties_missing_required_property/test/positive1.json
- assets/queries/openAPI/properties_missing_required_property/test/positive2.yaml
- assets/queries/openAPI/properties_missing_required_property/test/positive3.json
- assets/queries/openAPI/properties_missing_required_property/test/positive4.yaml
- assets/queries/openAPI/properties_missing_required_property/test/positive_expected_result.json
- Added Properties Missing Required Property query for OpenAPI
Schema Object should have all required properties defined
> feat(query): Added Properties Missing Required Property query for OpenAPI

- assets/libraries/openapi/library.rego
> feat(query): refactored `check_openapi` to allow 2.0 checks

- assets/libraries/terraform/library.rego
- assets/queries/terraform/aws/kms_key_with_vulnerable_policy/query.rego
- assets/queries/terraform/aws/kms_key_with_vulnerable_policy/test/negative.tf
- assets/queries/terraform/aws/rest_api_with_vulnerable_policy/metadata.json
- assets/queries/terraform/aws/rest_api_with_vulnerable_policy/query.rego
- assets/queries/terraform/aws/rest_api_with_vulnerable_policy/test/negative.tf
- assets/queries/terraform/aws/rest_api_with_vulnerable_policy/test/positive.tf
- assets/queries/terraform/aws/rest_api_with_vulnerable_policy/test/positive_expected_result.json
- Added "Rest API With Vulnerable Policy" query for Terraform. It checks if the Rest API policy defines wildcards in 'Principal' or 'Actions'
> feat(query): add "Rest API With Vulnerable Policy" for Terraform

- assets/libraries/terraform/library.rego
- Removing duplicated functions
> fix(library): removing duplicated functions in terraform library

- assets/libraries/common/library.rego
Closes #3442
- Added 'pa$$' to common password values
> update(query): Updated Passwords And Secrets In Infrastructure Code for Common

- docs/index.md
Triggered by SHA: _73325e34be154af47b7373cb2c4c63cec193a732_
> docs(index): updating links in index page - 1.3.2

- assets/libraries/common/library.rego
Closes #3442
- Updated Passwords And Secrets In Infrastructure Code for Common 
- Added `location` to the common keys slice
> update(query): Updated Passwords And Secrets In Infrastructure Code

- .github/scripts/metrics/get-metrics.py
- assets/queries/openAPI/general/schema_object_with_circular_ref/metadata.json
- aggregation 2 in metadata.json for shared queries
- changed glob pattern
> fix(metrics): fix get-metrics.py for openapi

- assets/queries/openAPI/general/operation_id_not_unique/test/negative1.json
- assets/queries/openAPI/general/operation_id_not_unique/test/negative3.json
- assets/queries/openAPI/general/operation_id_not_unique/test/negative4.yaml
- assets/queries/openAPI/general/operation_id_not_unique/test/positive1.json
- assets/queries/openAPI/general/operation_id_not_unique/test/positive3.json
- assets/queries/openAPI/general/operation_id_not_unique/test/positive4.yaml
- assets/queries/openAPI/general/operation_id_not_unique/test/positive_expected_result.json
- Fix samples in "OperationId Not Unique" query
> feat(query): fix samples in 'OperationId Not Unique' query

- assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative3.json
- assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative4.yaml
- assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative5.json
- assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/negative6.yaml
- assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive3.json
- assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive4.yaml
- assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive5.json
- assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive6.yaml
- assets/queries/openAPI/general/parameter_objects_headers_dup_name/test/positive_expected_result.json
- Fix samples in "Parameter Objects Headers With Duplicated Name" query
> feat(query): fix samples in 'Parameter Objects Headers With Duplicated Name' query

- assets/queries/openAPI/general/path_template_empty/test/negative1.yaml
- assets/queries/openAPI/general/path_template_empty/test/negative2.json
- assets/queries/openAPI/general/path_template_empty/test/negative3.yaml
- assets/queries/openAPI/general/path_template_empty/test/negative4.json
- assets/queries/openAPI/general/path_template_empty/test/positive1.yaml
- assets/queries/openAPI/general/path_template_empty/test/positive2.json
- assets/queries/openAPI/general/path_template_empty/test/positive3.yaml
- assets/queries/openAPI/general/path_template_empty/test/positive4.json
- Fix samples in "Path Template is Empty" query
> feat(query): fix samples in 'Path Template is Empty' query

- assets/queries/openAPI/general/paths_object_empty/test/negative2.json
- assets/queries/openAPI/general/paths_object_empty/test/negative4.yaml
- assets/queries/openAPI/general/paths_object_empty/test/positive4.yaml
- Fix samples in "Paths Object is Empty" query
> feat(query): fix samples in 'Paths Object is Empty' query

- assets/queries/openAPI/general/properties_missing_required_property/test/negative1.json
- assets/queries/openAPI/general/properties_missing_required_property/test/negative2.yaml
- assets/queries/openAPI/general/properties_missing_required_property/test/negative3.json
- assets/queries/openAPI/general/properties_missing_required_property/test/negative4.yaml
- assets/queries/openAPI/general/properties_missing_required_property/test/negative5.json
- assets/queries/openAPI/general/properties_missing_required_property/test/negative6.yaml
- assets/queries/openAPI/general/properties_missing_required_property/test/positive1.json
- assets/queries/openAPI/general/properties_missing_required_property/test/positive2.yaml
- assets/queries/openAPI/general/properties_missing_required_property/test/positive3.json
- assets/queries/openAPI/general/properties_missing_required_property/test/positive4.yaml
- assets/queries/openAPI/general/properties_missing_required_property/test/positive5.json
- assets/queries/openAPI/general/properties_missing_required_property/test/positive6.yaml
- assets/queries/openAPI/general/properties_missing_required_property/test/positive_expected_result.json
- Fix samples in "Properties Missing Required Property" query
> feat(query): fix samples in 'Properties Missing Required Property' query

- assets/queries/openAPI/general/property_defining_maximum_not_greater_than_minimum/test/negative1.json
- assets/queries/openAPI/general/property_defining_maximum_not_greater_than_minimum/test/negative2.json
- assets/queries/openAPI/general/property_defining_maximum_not_greater_than_minimum/test/negative3.yaml
- assets/queries/openAPI/general/property_defining_maximum_not_greater_than_minimum/test/negative4.yaml
- assets/queries/openAPI/general/property_defining_maximum_not_greater_than_minimum/test/negative5.json
- assets/queries/openAPI/general/property_defining_maximum_not_greater_than_minimum/test/negative6.yaml
- assets/queries/openAPI/general/property_defining_maximum_not_greater_than_minimum/test/negative7.yaml
- assets/queries/openAPI/general/property_defining_maximum_not_greater_than_minimum/test/negative8.json
- assets/queries/openAPI/general/property_defining_maximum_not_greater_than_minimum/test/positive1.json
- assets/queries/openAPI/general/property_defining_maximum_not_greater_than_minimum/test/positive3.yaml
- assets/queries/openAPI/general/property_defining_maximum_not_greater_than_minimum/test/positive5.yaml
- assets/queries/openAPI/general/property_defining_maximum_not_greater_than_minimum/test/positive6.yaml
- assets/queries/openAPI/general/property_defining_maximum_not_greater_than_minimum/test/positive7.json
- assets/queries/openAPI/general/property_defining_maximum_not_greater_than_minimum/test/positive_expected_result.json
- Fix samples in "Property Defining Minimum Greater Than Maximum" query
> feat(query): fix samples in 'Property Defining Minimum Greater Than Maximum' query

- assets/queries/openAPI/general/responses_wrong_http_status_code/test/negative1.json
- assets/queries/openAPI/general/responses_wrong_http_status_code/test/negative2.yaml
- assets/queries/openAPI/general/responses_wrong_http_status_code/test/negative3.json
- assets/queries/openAPI/general/responses_wrong_http_status_code/test/negative4.yaml
- assets/queries/openAPI/general/responses_wrong_http_status_code/test/positive4.yaml
- Fix samples in "Responses With Wrong HTTP Status Code" query
> feat(query): fix samples in 'Responses With Wrong HTTP Status Code' query

- assets/queries/openAPI/general/schema_object_with_circular_ref/test/negative1.json
- assets/queries/openAPI/general/schema_object_with_circular_ref/test/negative2.json
- assets/queries/openAPI/general/schema_object_with_circular_ref/test/negative3.yaml
- assets/queries/openAPI/general/schema_object_with_circular_ref/test/negative4.yaml
- assets/queries/openAPI/general/schema_object_with_circular_ref/test/positive1.json
- assets/queries/openAPI/general/schema_object_with_circular_ref/test/positive2.json
- assets/queries/openAPI/general/schema_object_with_circular_ref/test/positive3.yaml
- assets/queries/openAPI/general/schema_object_with_circular_ref/test/positive4.yaml
- assets/queries/openAPI/general/schema_object_with_circular_ref/test/positive_expected_result.json
- Fix samples in "Schema Object With Circular Ref" query
> feat(query): fix samples in 'Schema Object With Circular Ref' query
